### ISSUE TITLE
Support functions in FilterString

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#1000]
Currently we can use x-ms-odata to define the shape of the data for filterString. It would be good it also support defining the custom functions for filterString.

eg. $filter=properties/trigger neq null and search('abc')

**Comment by hovsepm** [comment]
@tonytang-microsoft-com 
it is supported but not documented. I've created an issue to track document update - https://github.com/Azure/autorest/issues/1007
