### ISSUE TITLE
OData custom method solution for C# generator is not documented anywhere

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1007]
e.g. there is a support for custom OData methods in the generated code like this 
```
$filter=atScope() and assignedTo('Microsoft.Websites')
```
that could be done with customization code, but it is not documented anywhere.
Here are the steps that should be added to x-ms-odata documentation: (this sample is for Authorization RoleAssignmentFilter)

- Create a RoleAssignmentFilter type in swagger  https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L836 
- Create a customization layer and add manual code. 
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Authorization/Microsoft.Azure.Management.Authorization/Customizations/RoleAssignmentFilter.cs 
- The code that makes everything work is in ClientRuntime.Azure - https://github.com/Azure/autorest/blob/master/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime.Azure/OData/UrlExpressionVisitor.cs#L311 
- And the test  that shows usage for the caller https://github.com/Azure/autorest/blob/master/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime.Azure.Tests/ODataTests.cs#L354

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
