### ISSUE TITLE
Default value comments are not generated in the operations file

### ISSUE THREAD

**Issue by BurtBiel** [Azure/autorest#1009]
In Azure.Python, generate from a swagger parameter with an enum and a default value.

Result: the enum values are generated in both the operations and model file, but the default values are only generated in the model file.

Expected: both enum and defaults are generated in both locations

We parse comments out of the SDK and surface them to our users, so having the default value text is important

**Comment by fearthecowboy** [comment]
@BurtBiel and @lmazuel Is this still an issue? If this is still a concern, please reopen with details.

**Comment by lmazuel** [comment]
@johanste ?

**Comment by johanste** [comment]
I don't know of any issues around this...
