### ISSUE TITLE
Feature Request: Allow Multiple Exception Type definitions in Swagger

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1024]
Today we only allow for one custom exception type per path, defined by some object schema in the "default" response section. This is fairly limiting if you have a defined set of exceptions that the server returns that you would like to differentiate. For example, we are adhering to the WebHDFS guidance for some of our exceptions (located here: https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Error_Responses), which means that any call can result in one of six different exceptions, which we would like to properly throw.

Today, I can only throw a generic "AdlsErrorException" and then it is up to the caller to dig in and figure out what the exception actually is, like this (in C#), which is a pretty cumbersome approach:
```
try
{
    some ADLS file system operation
}
catch (AdlsErrorException e)
{
    if (e.Body is AdlsFileNotFoundException)
    {
        Do something for file not found
    }
    else if (e.Body is AdlsSecurityException)
    {
        Do something for permissions exception
    }
    ... and so on for all of the exception types ...
}
```

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
