### ISSUE TITLE
Python code throws error on status code other than OK

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/autorest#1041]
Calling REST API's typically returns status code like Created, which will cause an error in the generated client.

**Comment by annatisch** [comment]
Thanks Thomas - I'll get this sorted.

**Comment by annatisch** [comment]
Hi @ThomasArdal,
I've just reviewed the runtime code and it seems that we don't raise an exception for any status codes, so a request failure in the runtime would result from a AAD token expiry, or a failure to reach the endpoint.

For standard calls, whether an error is raised on a given status code is usually part of the generated code, for example:

        response = self._client.send(request, header_parameters, **operation_config)

        if response.status_code not in [200]:
            raise models.ErrorException(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('str', response)

Can I ask a bit more about the request call - is it an Azure long running/polling operation?
Or maybe a list/paged operation?
Are you able to take a look at the generated function to see whether it specifies any status codes on which to raise an exception?
What exception is being raised and does it have any useful message?

Thanks!

**Comment by ThomasArdal** [comment]
@annatisch I see this code in one of the py files in `operations`:

    if (response.status_code not in [200]:
        raise HttpOperationError(self._deserialize, response)

**Comment by annatisch** [comment]
@ThomasArdal,
This means that the swagger spec needs to be amended to support the return code - if this is from one of the specs in the [Azure specs repo](https://github.com/Azure/azure-rest-api-specs) - I would suggest opening an issue there.

**Comment by ThomasArdal** [comment]
@annatisch It's from my own Web API. And you're absolutely right. The endpoint is missing Swagger documentation in regards to status codes. Very clever code-generator :smile:  Sorry, this issue can be closed.

**Comment by annatisch** [comment]
@ThomasArdal, good to hear you were able to resolve it :)

**Comment by hdoubleps** [comment]
It is an Azure long running operation. I also face this error. 
"msrest.exceptions.HttpOperationError: Operation returned an invalid status code 'Bad Request" 
What should I do?
