### ISSUE TITLE
JsonExtensionData needs to be supported by AutoRest

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1057]
For the swagger JSON fields that are not well-defined and schema-less, we can add "additionalProperties" field as follow:

    "def1": {
      "properties": {
       "field1": {
          "type": "string"
       }
      },
      "additionalProperties": {
        "type": "object"
     }
    }

In C# this should be translated to a property, tagged with [JsonExtensionData] attribute similar to [this.](https://github.com/pomortaz/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault/Models/Messages.cs#L58) 

        [JsonExtensionData]
        public Dictionary<string, object> AdditionalProperties { get; set; }

So if there is a schema-less JSON string in the service response, similar to field2 in the following example (for def1 in the swagger spec above), field2 should be serialized to ‘Dictionary<string, object> AdditionalProperties’ property:
 
    {
        "def1": {
            "field1": "this is field 1",
            "field2": {
                "field3": "this is field 3"
             }
         }
    }

**Comment by fearthecowboy** [comment]
Hey @pomortaz ... I'm looking into this, just working out how the same thing can be equally implemented in the other languages, I just have to verify what the behavior would be if there is flattening going on.

I should have some more information in the next day or so.

**Comment by amarzavery** [comment]
@pomortaz  Extending your example to explain @fearthecowboy 's point.

Let's assume that field2 and field3 were also mapped.
- Actual response payload
```
{
    "def1": {
        "field1": "this is field 1",
        "field2": {
            "field3": "this is field 3",
           "field4": "I am not mapped in swagger",
           "field5": "I too am not mapped in swagger. What to do? Where should I go?"
         }
     }
}
```


- Swagger schema definition
```
"def1": {
  "properties": {
   "field1": {
      "type": "string"
   },
   "field2": {
     "x-ms-client-flatten": true,
     "properties": {
         "field3": {
           "type": "string" // Think of this as something like provisioning state
         }
     }
  },
  "additionalProperties": {
    "type": "object"
 }
}
```



So after deserialization,
```
{
    "def1": {
      "field1": "this is field 1", // This will be deserialized properly
      "field3": "this is field 3", //This will be flattened during deserialization
      "additionlaProperties": {
       
//How should unmapped properties look like over here?

     A) Should they be flattened like their siblings?
         "field4": "I am not mapped in swagger",
         "field5": "I too am not mapped in swagger. What to do? Where should I go?"

    B) Should they be present as they were on the actual response payload?
         "field2": {
           "field4": "I am not mapped in swagger",
           "field5": "I too am not mapped in swagger. What to do? Where should I go?"
         }
     }
}
```
