### ISSUE TITLE
.Net sdk, operation returning LRO fails with null reference exception when the RP returns 204 and no operation

### ISSUE THREAD

**Issue by karravi-msft** [Azure/autorest#1063]
I am seeing this issue when our RP returns 204 for delete on a non existing resource. In this case, no asyncoperationhandle is returned by the service.

In generated code in .Net, this causes an issue as the request.Body which is then parsed as a long running operation is null..

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
