### ISSUE TITLE
HttpClient.SendAsync with Stream MultipartFormDataContent stalls forever when server returns status 500

### ISSUE THREAD

**Issue by mms-** [Azure/autorest#1064]
On C#, UWP. If the server return status 500, SyndAsync throws HttpRequestException. After about 15 iterations the error on HttpRequestException changes from 

System.ArgumentException: Value does not fall within the expected range.
to
System.Runtime.InteropServices.COMException: The text associated with this error code could not be found. The Operation has timed out.

With each subsequent connection attempt, the timeout occurs and no actual attempts to connect to the server are made, even if a new HttpClient instance is used. Connecting to another host works however that host is will not connect no matter what the request query path.

The re-connection attempts are made a few seconds apart, the client racks up 12 active connections to the server. These linger and time out eventually. Disposing the client has no effect. No new connections are ever made once the timeout occurs.. The COMException HResult strangely enough is -2147012894 (0x80072EE2)

Is this a retry policy issue? It seems eventually it should try to connect again. Am I missing something? This occurs on latest bits on IoT Raspberry Pi and Windows 10 UWP app, in a PCL assembly targeting .Net 4.5, etc.

Also autorest does not catch HttpRequestException and the response is not disposed by autorest, though this isn't the cause of the above issue.

**Comment by fearthecowboy** [comment]
Hey @mms- ,

Sorry for the delay; This looks like something that we're going to have to look into; I may need you to give me some stuff that reproduces the problem so we can look into it.

**Comment by fearthecowboy** [comment]
Without further information, I can't investigate. Please reopen if you can provide an example
