### ISSUE TITLE
TypeError after upgrade to recent nightly build

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/autorest#1072]
After having upgraded to the recent nightly build, I get a TypeError in the generated Python client:

    client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
    ---> self._serialize = Serializer(client_models)
    self._deserialize = Deserializer(client_models)

    TypeError: __init__() takes exactly 1 argument (2 given)

I have generated a new client from my swagger json and I'm running on Python 2.7.10.

**Comment by annatisch** [comment]
Hi @ThomasArdal,
I think this should be fixed by updated msrest to 0.4.

I will update the generator to state that this is the required runtime version.

**Comment by ThomasArdal** [comment]
@annatisch It worked with msrest 0.4. Thanks!
