### ISSUE TITLE
(C#) HTTP 201 Created does not give back created resource

### ISSUE THREAD

**Issue by RCerff** [Azure/autorest#1077]
Hello,

I've created ApiController method that creates an object.

HTTP Verb is POST. 

The action method is decorated with the following attributes:
[HttpPost, Route("MyDomain/MyEntities")]
[SwaggerResponse(HttpStatusCode.Created, ResponseTextCreated, typeof(MyEntity))]

Return instruction of the method is:
return ApiController.Created($"{route}/{createdEntity.Id.ToString()}", createdEntity);

In the Swagger UI this method works fine. The response body contains the newly created object, together with the Id of it that was created by the underlying ORM or database.

Now we've created the client with Autorest.

The Client method for it is:
Task CreateMyEntityAsync(MyEntity myEntity);

What I miss here is a possibility to get the created entity, e.g. with return value Task<MyEntity> instead of simply void. So I have no information about the created entity. Specially the Id of the newly created entity would be important.

Do I miss something? I could return OK(myEntity) to get the entity, but that does not confirm to "specification" that expect a http return code of 201 (Created), together with the url to the newly created resource.

Any hint is welcome.

Regards

Rolf

**Comment by fearthecowboy** [comment]
Hey @RCerff  -- can you post the swagger spec here so I can look at that?

**Comment by raghur** [comment]
I ran into this just now. Swashbuckle generates a default 200 as well. You can turn that off with `[SwaggerResponseRemoveDefaults]` attribute

Once the swagger spec had **only** 201 in the response, it was creating a client with proper types for the operation.

**Comment by fearthecowboy** [comment]
Without more information to reproduce this, I'm closing it. Please reopen if you have more details.
