### ISSUE TITLE
Use Environment to determine the value of base uri

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#1082]
Today, the value of the baseuri comes from the swagger spec. It defaults to `management.azure.com`.

If the user wants to use the sdk for China or any other cloud, then he/she has to go through several hoops to find the value for the resourcemanager endpoint. (I know that a metadata endpoint service is coming up. However, we still need to hook it up to the client, for the end user experience is seamless).

By default we should generate the client constructor for AzureClients as we are doing today. This solves the problem for data plane clients.
```
this.baseuri = this.environment.azureDataLakeStoreFileSystemEndpointSuffix;
```
However, we should have **an extension that enables Autorest to generate a client that expects environment name instead of base url as the second parameter after credentials in the client constructor**.

Today all the language azure runtimes have the concept of an **AzureEnvironment**. The environment is a repository of different endpoint (resource mgmt., mgmt., auth, tokenaudience, portal url, etc.) values supported in that environment.

As of today we support (Azure, AzureChina, USGovernment, GermanCloud) as environments with metadata about endpoints in the runtime.

This is what we are doing today:
```
function WebSiteManagementClient(credentials, subscriptionId, baseUri, options) {
 . . .
  this.baseUri = baseUri;
  if (!this.baseUri) {
    this.baseUri = 'https://management.azure.com';
  }
  this.credentials = credentials;
}
```

The following would be much better. User has to only provide a name of the Environment. In languages that support an enum, this could simply be an enum value.
```
function WebSiteManagementClient(credentials, subscriptionId, options) {
 . . .
  this.credentials = credentials;
  if (!options.environment) {
   options.environment = 'Azure';
  }
  if (!msRestAzure.AzureEnvironment[options.environment]) {
    throw new Error(util.format('The provided environment "%s" is not a known environment in Azure', options.environment));
  }
  this.environment = msRestAzure.AzureEnvironment[options.environment];
  this.baseuri = this.environment.resourceManagerEndpointUrl;
}
```

The extension would be:
```
{
 ....
  "host": "management.azure.com",
  "x-ms-use-environment": true
  ...
}
```

**Comment by lmazuel** [comment]
The extension does not tell you what attribute use. I guess this should be:
```
 ....
  "host": "management.azure.com",
  "x-ms-use-environment": "resourceManagerEndpointUrl"
  ...
}
```
To generate code:
```
this.baseUri = myenv.resourceManagerEndpointUrl
```

**Comment by amarzavery** [comment]
The Runtime should have [all the values populated for the environment](https://github.com/Azure/autorest/blob/master/ClientRuntimes/NodeJS/ms-rest-azure/lib/azureEnvironment.js#L49). 
It would be logical to use resourceManagerEndpointUrl. But I see no harm in specifying that in the extension.

The effect of this extension would be:
1. environment will be a property of the client
2. baseuri will be set by using the resourcemanagerurl endpoint.

**Comment by lmazuel** [comment]
When looking at [AzureEnvironment in NodeJS](https://github.com/Azure/autorest/blob/master/ClientRuntimes/NodeJS/ms-rest-azure/lib/azureEnvironment.js#L67) it seems that KeyVault, SQL, Datalake and more have specific endpoint. It's why I suggest to use the attribute name in the extension, to keep things absolutely generic.

**Comment by amarzavery** [comment]
sounds good to me.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
