### ISSUE TITLE
(C#) Revise of parameter pre checking necessary?

### ISSUE THREAD

**Issue by RCerff** [Azure/autorest#1088]
Hello,

when I inspect Service Client method implementation, I find checking of null values of parameters even when the parameter is a struct based type e.g. a Guid.

Would it not better to check for default value here?

Regards
Rolf

**Comment by fearthecowboy** [comment]
Is this a nullability issue here? (ie, is it using `Guid?` )

**Comment by RCerff** [comment]
That could be. Parameters are of type Guid not of Type Guid?. Is it mandatory to use nullable types as input parameters?

**Comment by fearthecowboy** [comment]
Not necessarily, but there are a few issues regarding nullability that I'm looking into.

I'm going to target this one for 1.0; (I may accidentally clean it up while doing others ) but we'll keep it open to track it.
