### ISSUE TITLE
AutoRest should expose a switch to turn off sync wrappers

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1099]
Currently, AutoRest will add sync wrappers for almost every async operations.
For Key Vault we don't see any upside for exposing sync wrappers and we want to eliminate sync wrappers to avoid any deadlock scenarios (especially in UI). 
Here is a [related issue](https://github.com/Azure/autorest/issues/446)

**Comment by stankovski** [comment]
As mentioned in the other issue, I would recommend adding a flag in autorest for C# to allow specifying what sync wrappers should be generated `-SyncWrappers None|Essential|All`.

**Comment by amarzavery** [comment]
Default being All.

**Comment by stankovski** [comment]
I would actually keep `Essential` as default for backwards compatability
