### ISSUE TITLE
Various compiler errors when using later version of Microsoft.Rest.ClientRuntime

### ISSUE THREAD

**Issue by Chaotic-Limited** [Azure/autorest#1109]
Steps to reproduce:

1. Have a swagger enabled REST API App hosted in Azure for you to generate the service reference code from.
2. Create Console Application.
3. Right click project, Add, REST API Client.
4. Assuming you are signed in with your Azure credentials, select your API App from the options available and continue.
5. Wait for generation to complete.
6. Right click project, Manage Nuget Packages
7. Update Microsoft.Rest.ClientRuntime to any version greater than 1.  For this I recommend 2.2.0.
8. Return to your code to find many compiler errors.

One might say "just use the old libraries" however I am trying to add this reference in an Azure Website project which requires a version of Microsoft.Rest.ClientRuntime > 2.0.0.  I am forced to manually find / replace the HttpOperationException<object> code, manually add "using Microsoft.WindowsAzure.Common.Internals;" to all the model classes (LazyList) and fix the broken casts that are in there too.  It takes ages.

Let me know if there is any fix or if this is a known issue.  It seems a bit mad that autorest requires such an old version of Microsoft.Rest.ClientRuntime so I'm guessing there is an issue with my setup.

Thank you!

**Comment by devigned** [comment]
I think you will have better luck using the latest version rather than the older version in VS. We are planning on updating this in VS soon. 

/cc @madskristensen @mlorbetske

**Comment by Chaotic-Limited** [comment]
Hi devigned, thanks for the tip.  I have done as you've asked and have the following feedback:

1. I have an entity in my model called a Group - which has autogenerated Groups.cs which refers to a Group class for the model.  However it also conflicts with System.Text.RegularExpressions.Group.  As annoying as it may be, I recommend referencing all classes fully in autogenerated code without any using statements, so that local classes are never overridden.
2. In the same class, I get an error saying that Groups does not implement interface member IGroups.GetWithHttpMessagesAsync(my params)... it does not have the matching return type of Task<HttpOperationResponse<Group>>.  When I correct Group to Models.Group it falls into place.

So that's just one bug, because of class names.  Otherwise there were no other compiler errors.  I'm yet to test it in action though.  Thanks again for the pointer.

**Comment by fearthecowboy** [comment]
I agree, this is in-scope for 1.0 

Removing the using statements and explicitly referencing types will fix a related issues.
