### ISSUE TITLE
Client timeout value should be consistent across languages

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1114]
Currently we handle client side timeouts differently across different languages.
In C# the client call will get cancelled if it exceeds 100 seconds, and throws a TaskCanceledException
In Java, the client will throw a timeout exception after ~10 seconds (it looks like).
I am not sure what the exact timeout behavior is in Python and NodeJS, but in general we should have a similar timeout interval across all languages (my vote is for 100 seconds) and ideally a consistent error messaging pattern (it is kind of strange getting a TaskCanceledException in C# and needing to know that really means the client didn't hear back from the server for 100 seconds).

**Comment by matthchr** [comment]
`TaskCanceledException` is I believe an artifact of the underling C# technology that the client runtime uses to issue requests to the server.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
