### ISSUE TITLE
(c#) Unacceptable time format for System.DateTime

### ISSUE THREAD

**Issue by mosyu** [Azure/autorest#1124]
.net System.Date use [7 digits for the decimal fraction for ISO 8601 format](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx), while autoreset use 6. If we use client library generated by autorest to send a date time parameter, server side can't parse this value to ISO8601 format. Is there any way we can specify the digit for the decimal fraction of date time?

Here is the sample:
Date time parameter.
```
"CreationTime": {
  "readOnly": true,
  "type": "string",
  "format": "date-time"
}
```
Inspect the traffic by fiddler.
`
  "properties": {
    "CreationTime": "2016-05-31T06:02:47.319355Z",
  }
`

Use below .net code to parse this value to ISO8601 format.
```
public static bool ParseTimeFromHttpString(string dateString)
 {
     DateTime dt;
     return DateTime.TryParseExact(dateString, "O", null, DateTimeStyles.RoundtripKind, out dt);
 }
```

**Comment by tbombach** [comment]
Hi @mosyu. I was unable to repro this issue. I have a spec that uses `"format": "date-time"` and when I used fiddler to inspect what was being sent, I saw all 7 digits:

```
"2016-06-02T19:39:38.8073752Z"
```
Could you share your C# code that specifies the DateTime that you pass to the generated code?

[The code that specifies that JsonSerializerSettings](https://github.com/Azure/autorest/blob/f4a4543c4ab1ffaf3734645c96e69218ec488fa8/AutoRest/Generators/CSharp/CSharp/Templates/ServiceClientTemplate.cshtml#L72) just uses the `DateFormatHandling.IsoDateFormat` value to specify ISO 8601, so I don't think we do anything special with the number of digits.

Another question: In the [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13), it specifies that you cannot send values for `readOnly` properties in requests. AutoRest shouldn't be generating code that sends these properties during requests. I'd like to figure out if there's a bug that lets your generated code do this.

**Comment by mosyu** [comment]
@tbombach Can you retry your code? In most case, we get 7 digits. but sometime It just return 6 digits.

This could be a .net json DateTime covert issue. and we need one way to specify the date time format since we don't have agreement on the digits.

for your question about readOnly. I pasted the response spec, sorry for confusion.

**Comment by fearthecowboy** [comment]
I think I found what's actually going on.

It would appear from https://github.com/JamesNK/Newtonsoft.Json/blob/6d7c94e69fa2f52b91fb22972321cb9b51b9abed/Src/Newtonsoft.Json/Utilities/DateTimeUtils.cs#L682 that JSON.NET is omitting trailing zeros in the fractional value. 

ISO 8601 specifies support "_of a decimal fraction to the smallest time unit where higher precision is needed._"

Unfortunately it's also remarked : " _There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties._"
