### ISSUE TITLE
There is no way to define a parameter or property that is just a single character

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1125]
We have an API that takes a parameter that must be a single character. Although this is represented as a string in JSON, it would be helpful if it could map to type `char` (or equivalent) in the code generated by AutoRest. However, there is no way I can see to express this as a `format` in the Swagger spec.

What is the right solution here? Push for a `char` format to be adopted in Open API (or a `char` type in JSON schema)? Just unilaterally define our own...? Until this is solved, I have to use `x-ms-external` on all types that have such single-character parameters (our API deals with lexical analysis, so there are several such cases).

FYI @devigned @amarzavery

**Comment by fearthecowboy** [comment]
Random thought - put a `maxLength` of 1 and a `minLength` of 1 and then maybe AutoRest could detect *that* and generate a char instead of a string...

**Comment by brjohnstmsft** [comment]
That would be one way to solve it. Thanks for the suggestion. If it turns out that AutoRest already does this, I'll close this issue.

**Comment by gitfool** [comment]
@brjohnstmsft My Swashbuckle PR (see #1080) decorates such types with `x-type-dotnet: "System.Char"` :wink:

**Comment by fearthecowboy** [comment]
I'm going to do this, but use `format: char` as the means for keying how we know to emit a `char` 

This should work well for languages that actually have a character type.

**Comment by brjohnstmsft** [comment]
:+1:
