### ISSUE TITLE
Update LRO state machine across all languages

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#1128]
### Description

According to ARM best practices, all LRO operations should work as follows:
- If the original response contaisn both AzureAsyncOperation and Location headers, keep the Location header and follow through the AzureAsyncOperation pattern to a terminal state
  - After a terminal state is reached, if it is a success, follow the Location header in the success case and return the payload from the result
  - After a termina state failure, return the error contained in the AzureAsyncOperation header
  - if the operation is a PUT, preform a get on the original URI to return the completed object
- If the originalresponse contains only an AzureAsyncOperation header, behave as now (follow azure async operation header to conclusion)
- if the original response contains a Location header, follow the location header unbtil a terminal response code and lack of location header
- If the operation is a PUT and neither Location nor AzureAsyncOperation exists, perform Get requests on the original URI until ProvisioningState is a termina state

Need to implement this pattern across languages, and add additional tests  to ensure each of these branches are covered for success / failure / cancellation for all operation tyupes (PUT, POST, DELETE, PATCH)

This will also support the long-running POST operation for Network RP

**Comment by djberg96** [comment]
@markcowl Is this best practice documented anywhere?
