### ISSUE TITLE
Support Base64Url format

### ISSUE THREAD

**Issue by tbombach** [Azure/autorest#1129]
AutoRest modeler supports a base64url format for string types. This is implemented in some languages, but requires serialization/deserialization code in some remaining languages.

This issue: https://github.com/Azure/autorest/issues/805 tracked the changes needed in the modeler. It was implemented in C# in this PR: https://github.com/Azure/autorest/pull/878

Here is the specification for Base64Url format: https://tools.ietf.org/html/rfc4648#page-7

**Comment by tbombach** [comment]
@jianghaolu I've assigned this to you for the Java implementation, but please re-assign to someone else if they're going to end up doing this work.

**Comment by jianghaolu** [comment]
Thanks @tbombach

**Comment by pomortaz** [comment]
@jianghaolu there are issues with the solution when generating the code.
 
Error with []():
```
    public byte[] result() {
        if (this.result == null) {
            return null;
        }
        return this.result.getbyte[]();
    } 
```

Error for not accepting byte[] in the constructor of Base64Url:
```
    public KeyOperationsParameters withValue(byte[] value) {
        this.value = new Base64Url(value);
        return this;
    } 
```

**Comment by jhendrixMSFT** [comment]
This is tracked in https://github.com/Azure/azure-sdk-for-go/issues/2111.
