### ISSUE TITLE
Using Azure.Java.Fluent generator, the client class is not extendable

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1131]
Using Azure.Java.Fluent generator, generates a client that is marked as final and is not extendable. 
The generated client class should be a package internal client (default modifier) and extendable (not marked as final). The class that extends the client class should then be marked as final. This is to allow adding customized code to the generated Java SDK.

**Comment by martinsawicki** [comment]
let's remove the `final` modifier
currently KV needs to work around this manually overriding in the autogend code

**Comment by olydis** [comment]
is this still an issue?

**Comment by jianghaolu** [comment]
final is gone.
