### ISSUE TITLE
Different packages for models generated using Azure.Java.Fluent and customized models

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1132]
The models generated using Azure.Java.Fluent generator are placed in *.implementation.api package.
There is a mixture of classes with *Inner extensions which should be wrapped and classes without *Inner in their names that should not be wrapped and they are both in the same package. There will be inconsistency between the packages used for models that are wrapped and not. Also the *Inner classes are publicly accessible, while they should be package internal. 

I would recommend making all the generated Azure.Java.Fluent classes package internal to enable extending the classes when needed or define a new swagger extension such as x-ms-wrapped and only make those generated classes as package internal.

Because the generated code is package internal, customized and generated code should be in the same package.

**Comment by martinsawicki** [comment]
obsolete as far as the original KV issue is concerned
