### ISSUE TITLE
LRO PUT operation marked as done when not completed

### ISSUE THREAD

**Issue by derekbekoe** [Azure/autorest#1133]
In Python msrestazure 0.4.0 PUT operations are marked as completed when they have not.

I believe the issue is with [azure_operation.py](https://github.com/annatisch/autorest/blob/9f11d41fc85cd78c42bfe255ee3891d7ac671584/ClientRuntimes/Python/msrestazure/msrestazure/azure_operation.py)

In `AzureOperationPoller._poll()` there is a call to `self._operation.is_done()` to check if the LRO is completed.
For a PUT operation, `LongRunningOperation.is_done()` returns `True` when in 0.3.0, it returned `False`.
The expected result is `False` so 1 more request can be made using the initial_url to get the expected response.

This is a related PR that changed the azure_operation.py file https://github.com/Azure/autorest/pull/1078.
This issue may be related to https://github.com/Azure/autorest/issues/1128

**Comment by lmazuel** [comment]
Hi @derekbekoe 
I think you are right this is coming from the PR you point. I guess I should take a closer look at my VM tests because all my tests were Green/OK.
We definitely needs @annatisch here, but I will try to take a look to help.

**Comment by annatisch** [comment]
Thanks! I will take a look.

**Comment by annatisch** [comment]
@derekbekoe - would it be possible to get the contents of the API polling responses?
This will best help us identify what part of the response caused the AzureOperationPoller to decide the operation was finished.
You should be able to see this if logging in debug.

**Comment by annatisch** [comment]
@derekbekoe - actually it would also be helpful to know which service spec the client you're using was generated from and which PUT call was exhibiting this behaviour - I can probably work backwards from that. :)

**Comment by lmazuel** [comment]
@annatisch I reproduce the problem with VM create (so Compute file)

When calling `result()`, RC4 returns an empty `VirtualMachine` object without raise an exception.

**Comment by derekbekoe** [comment]
Thanks!
