### ISSUE TITLE
Add support to not add possible values for enum properties

### ISSUE THREAD

**Issue by daschult** [Azure/autorest#1135]
In ...\autorest\AutoRest\Modelers\Swagger\ObjectBuilder.cs on line 187 the string "Possible values include: " is automatically appended to the documentation for any parameter marked as an EnumType. This documentation is then picked up by any properties that reference this parameter. In JSON schemas, it's not necessary to have this possible value documentation. There should be an option for a CodeGenerator to request that this extra documentation not be added.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
