### ISSUE TITLE
Auto rest adding the suffix "Property" when using "Default" in the swagger spec. 

### ISSUE THREAD

**Issue by matthew-rollitt** [Azure/autorest#1142]
When you define a property in swagger with the keyword "default"
``` json
"Foo": {
      "properties": {
        "default": {
          "$ref": "#/definitions/Bar",
            } 
}
``` 
auto rest will add the suffix "Property" to the generated object in C#
``` csharp
    public partial class Foo
    {
        [JsonProperty(PropertyName = "default")]
        public ExitOptions DefaultProperty { get; set; }
    }
```
Is there any way of keeping the keyword "default" by providing a new name of for this type, but still keeping the JsonProperty.PropertyName as "default".

**Comment by fearthecowboy** [comment]
Well, `default` is a reserved word in c#, so AutoRest is trying to get around that by renaming the property for you.

At this point the only workaround is make a separate c# file that with a partial class :

``` csharp
public partial class Foo {
   public ExitOptions TheDefault { 
      get { return this.DefaultProperty; } 
      set { this.DefaultPropery = value; } 
   }
}
```

Which would at least allow you to improve the convenience. 

Hmm. `Default` with a capital isn't a reserved word, so I'll still keep this bug and see about fixing that soon.

**Comment by matthew-rollitt** [comment]
Thanks!

**Comment by fearthecowboy** [comment]
I'm digging into the code where this stuff is handled, and opportunistically add some better handling, but I can't commit to this being in 1.0.

**Comment by fearthecowboy** [comment]
<hr>

Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by sandves** [comment]
I have the same problem with the word "from". The public property on the DTO is named "FromProperty".

**Comment by fearthecowboy** [comment]
@sandves AutoRest appends the word "Property" when it gets a conflict with a class or keyword name. `from` is a keyword, which is why you're seeing that behavior.

I'm not a big fan of the way AutoRest does name disambiguation; it's overly cautious, and tricky to adjust. 

lemme see if I can give you a Workaround.

**Comment by Badabum** [comment]
@fearthecowboy any updates on this topic?

**Comment by SNaithani** [comment]
I found a similar issue when trying to create a client from a definition that contained a parameter named "Interface". Autorest appended the word "Property" to it, instead of setting the variable name as "Interface"(with a capital 'I').

Any chances this issue will be reopened?
