### ISSUE TITLE
[Python] Implement PackageVersion parameter in the Python extension

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1155]
Version string is currently defined in these two files:
* client\version.py
* setup.py 

And the `PackageVersion` parameter is not supported.

The `PackageVersion` parameter should be supported this way in Python:
* If the user uses the `PackageVersion` parameter, force this string into the two files.
* If the parameter is not used:
  * If Swagger modeler, use API Version
  * If Composite modeler, empty string (no obvious version). A warning should be written.

This will help to fix:
https://github.com/Azure/azure-sdk-for-python/issues/612

**Comment by lmazuel** [comment]
Talked with @xingwu1 the Python extension has a hidden parameter called `Version` which do exactly this behaviour.

So, this bug is now "rename Version to PackageVersion"

**Comment by xingwu1** [comment]
PR #1171 is merged.
