### ISSUE TITLE
[Ruby] All attributes should have return type documented

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#1156]
Attribute readers generated by Ruby AutoRest don't have the type returned and thus there is no intellisense provided in the IDE.

For example, the resource management client doesn't provide the type returned for it's underlying method groups. See: http://www.rubydoc.info/gems/azure_mgmt_resources/0.3.1/Azure%2FARM%2FResources%2FResourceManagementClient%3Aresource_groups. The return type is object since nothing is specified in the documentation.

At a minimum, it should be:
``` ruby
# @return [Azure::ARM::Resources::ResourceGroups] resource_groups
attr_reader :resource_groups
```

I think this is systemic in the generator and needs to be fixed globally.

**Comment by vishrutshah** [comment]
Fix has been checked-in to AutoRest. Closing this bug. Thanks.
