### ISSUE TITLE
Why does call to method "WithHttpMessages" throw HttpOperationException?

### ISSUE THREAD

**Issue by rangp** [Azure/autorest#1164]
Hi, 

I'm trying to use AutoRest to call a service that can return status code 420 or 408 by times if the request wasn't successful. To do so I intended to use the generated method [ServiceName]WithHttpMessagesAsync to read the returned status code and inform the user of an error if it is not 200 OK. However for all status codes apart from 200, 400, 401 and 500 the generated method throws a HttpOperationException. 

What's the reason for this behavior? I mean I specifically use ..WithHttpMessagesAsync to be able to access the response headers and do the exception handling in my application. I'm not quite happy doing both querying the response headers for 400 and 401 results but then dismembering an exception for all other possible error codes.  I would suggest to remove the mentioned exception for generated methods "WithHttpMessages", since the consumer should decide whether a response code is a HttpOperationException or can be salvaged after all.

Cheers
Peter

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
