### ISSUE TITLE
Request : to have C# project instead of generated files under folder structure.

### ISSUE THREAD

**Issue by tpatel11** [Azure/autorest#1168]
As of now, autorest accepts the namespace and generates the appropriate files, but it would be great if it can generate the project file for that namespace. 
Well, **this is not a bug but enhancement request** to have project structure generated for C# files - instead of only generating C# code files.

**Comment by fearthecowboy** [comment]
This is something that we're looking at for the fall :)

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by tpatel11** [comment]
Thanks for kind consideration. :+1:

**Comment by fearthecowboy** [comment]
FYI, we have a PR in right now that will generate a `project.json` and `.xproj` files for a project... #1459
