### ISSUE TITLE
Roll-up: issues deferred until post-1.0 stabilization

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#1169]
#We're looking to quickly reach stabilization (ie, hit version '1.0' ).

In order to focus on the issues at hand, I'm closing (and marking 'deferred') the following issues, with the intention that our post-1.0 design will try to take the idea under consideration and address the underlying issue.

Our _tentative_ date to hit 1.0 stable is **August 24th 

----

**Note:** _If there is an issue on this list that you feel is really important or is blocking your ability to ship something, ping me (@fearthecowboy) and we can see if we can do something about it_ :+1: 

----

### Requires additional planning

- #837 proposal to support batch requests in AutoRest
<del>  - #980 Support for cpprestsdk </del> -- added to vNext list 

### Type Definitions

- #785 Designate "global" parameters explicitly. 
- #787 Mapping status codes to return values 

### Suggestions, discuss more.

- #684 (C#) Generated code should avoid extra copies of request data 
  - this is probably a really good idea, just not sure if it's really easy enough
- #198 Discussion: JSON string parameter
- #382 No way to omit redundant ID parameter on generated PUT methods 
  - I think $WORK > $PAYOFF on that one.
- #660 x-ms-external types should not require for properties to be declared 
  - IIUC, it's not using the actual type when specified? Defaulting to Object?
- #733 Improve the enum modelAsString extension option (for strongly typed languages) 
- #747 CSharp: auto-generated constructors seem brittle 
  - I do prefer object initializer syntax with smart defaults.
- #882 Generated languages are not consistent with their handling of `Content-Type` and `Content-Length` headers 
  - I'm not sure that _we're_ actually doing anything here, isn't that a byproduct of the language used?
- #907 Generated ServiceClient constructor no longer accessible 
  - is there a reason for making some constructors private?
- #976 Can't Mock my AutoRest generated extension methods 
- #977 Azure.CSharp should generate a constructor which includes all required properties
- #995 Support extension for discriminator definition property to allow making base class abstract.
- #1021 Feature request: C# extensibility points at runtime  
- #1024 Feature Request: Allow Multiple Exception Type definitions in Swagger 
- #1111 The error message is general, need to specify the server exception message 
- #1114 Client timeout value should be consistent across languages

### Good ideas

- #452 C# IFooBarAPI should derive from IBaseAPI 
- #609 Generated C# code should be decorated with GeneratedCodeAttribute attribute 
- #638 Generated properties that are prefixed with an underscore are named "Lowline" or "lowline" 
- #673 Streaming non file content using C# client generator 
- #903 All Stream request body APIs should use Transfer-Encoding:chunked 
- #781 Support default value in C# models 
- #855 Specify customize exception type even there is no body 
- #899 ODataQuery.ToString() does not properly encode strings 
- #1025 Bug: Cannot use a discriminator on a nested/flattened property 
- #1063 .Net sdk, operation returning LRO fails with null reference exception when the RP returns 204 and no operation
- #1082 Use Environment to determine the value of base uri  
- #1127 Azure ClientRuntime needs to have it's dependencies cleaned up 

### Test-only issues?

- #296 Some DateTime serialization unit tests are timezone relative 
- #1003 AutoRest tracing with xUnit v2 and test parallelization 

### Documentation

- #1135 Add support to not add possible values for enum properties 
- #325 create a readme for autorest contributors
- #1007 OData custom method solution for C# generator is not documented anywhere 

### additional details required

- #743 Add validation to make sure path parameters are present in the URL 
- #768 Generate Handlers According to Swagger.json input 

### Others...

- #729 Optional path needs to be supported 
- #806 Add concept of "flighting" to code generators 
- #811 Discussion: dealing with multiple models used with different verbs 
- #960 Expose ARM Async operation progress 
- #964 Follow-up for #653 Issue - Duplicate operationIds and underscore symbol - AutoRest has a bug around underscores
- #970 Preserve original request id for async operations 
- #1168 Request : to have C# project instead of generated files under folder structure. 
- #681 Generated C# SDK cannot update optional properties to null 
- #717 Support "multi" collectionFormat 
- #823 XML content for body is JSON encoded in CSharp Generator 
- #931 Return the body of HttpOperationExceptions (to view the detail) 
- # 656 Code generation tool should honor accept headers specified 'paths.{path}.{verb}.produces' swagger json file
- # 863 code generator / client doesn't fill result correctly on successful write requests
- #731 AutoRest to handle "x-ms-pageable" and ListNext() function? 
- #688 Add "x-ms-uuid" extension that would generate unique values 
- #1164 Why does call to method "WithHttpMessages" throw HttpOperationException? 
- #1148 Standardize process by which each language performs normalization and extension management 
- #835 Cannot pass AAD client id in ActiveDirectoryServiceSettings because it's not a Uri

**Comment by eMazeika** [comment]
August 24th has passed a while ago. Any updated "date to hit 1.0"?

**Comment by begoldsm** [comment]
@fearthecowboy friendly ping here :). Any new ETA on when these issues will get revisited? I have a particular interest in: #787, #899, #1111

**Comment by mikeblakeuk** [comment]
@fearthecowboy Any news on the nearly 1 year old https://github.com/Azure/autorest/issues/931 ?

**Comment by fearthecowboy** [comment]
We're finally starting the vNext design, and we've cherry picked the things we think are relevant and linked them in the new thread #2448
