### ISSUE TITLE
Generating client for SendGrid v3 api fails with serialization exception

### ISSUE THREAD

**Issue by SatyKrish** [Azure/autorest#1185]
> AutoRest.exe -Input D:\Temp\SendGrid\SendGrid_swagger.json -ClientName SendGridClient -AddCredentials True -OutputFileName D:\Temp\SendGrid\SendGridClient.cs -Verbose

**error:** [FATAL] Error parsing swagger file. Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Nullable`1[Microsoft.Rest.Modeler.Swagger.Model.DataType]' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'properties.categories.type', line 30, position 16.
INFO: AutoRest Core 0.16.0.0
INFO: Initializing modeler.
INFO: Initializing modeler.
INFO: Parsing swagger json file.

**Comment by SatyKrish** [comment]
SendGrid swagger json is downloaded from this link - https://github.com/sendgrid/sendgrid-oai

**Comment by fearthecowboy** [comment]
Hmm this fails with the latest build too. I'll look at this later today.

**Comment by olydis** [comment]
The Swagger file contains properties with `type: 'null'` which is not valid according to the Swagger spec and has thus no meaning to AutoRest! 
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for datails.
