### ISSUE TITLE
Generating a TypeScript client with -AddCredentials produces code with compile errors

### ISSUE THREAD

**Issue by itsananderson** [Azure/autorest#1190]
When you generate NodeJS code using the "AddCredentials" flag, the generated main client class doesn't compile with the typescript compiler.

I have a repository with a basic repro: https://github.com/itsananderson/autorest-addcredentials-repro

If you look at the [generated d.ts file for the client](https://github.com/itsananderson/autorest-addcredentials-repro/blob/master/lib/autorest/fooClient.d.ts) you can see that it references `ServiceClientCredentials` on lines 30 and 32, but they aren't imported from `ms-rest` on line 7.

As far as I can tell, this issue was introduced in the following commit https://github.com/Azure/autorest/commit/55bd11242cd7cbe7b3688cd19d43de26a9bfbdcb, when the `ServiceClientCredentials` type was converted from a composite type to a class.

**Comment by olydis** [comment]
@amarzavery is this fixed? just cleaning up issues :-)

**Comment by olydis** [comment]
@amarzavery ping

**Comment by balajikris** [comment]
By looking at the client*.d.ts in the current Node library I can tell we're importing `ServiceClientCredentials`, so this looks like its working fine now.

**Comment by olydis** [comment]
thought so, I also assume that this problem would be somewhat so fundamental that we would have heard more noise in the past year :D thanks!
