### ISSUE TITLE
error: [FATAL] OperationId is required (ver 0.16.0)

### ISSUE THREAD

**Issue by tdjastrzebski** [Azure/autorest#1194]
Trying to generate the code I get:

> error: [FATAL] OperationId is required for all operations. Please add it for 'get' operation of '/v1/rest/configuration/backends' path.

There is no such path in my swagger 2.0 file!
Version 0.9.6 distributed with VS 2015 generates code with no problems.
Perhaps I am missing something. Swagger file attached.
[v1.zip](https://github.com/Azure/autorest/files/333518/v1.zip)

**Comment by tbombach** [comment]
Hi @tdjastrzebski. I was unable to repro the issue. I downloaded the Swagger file and was able to successfully generate code with AutoRest 0.16.0. Could you verify that the attached Swagger file is the same as the one that causes the OperationId required error?

**Comment by tdjastrzebski** [comment]
Well, stupid me ..
Please disregard this issue.

**Comment by ngzero** [comment]
I am having the same problem. Can you please tell what you did?
