### ISSUE TITLE
Escaping problem in some parameters default value

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1196]
When we generate the Python code of Datalake, we can see some strange escaping bug:

```python:
    def create_secret(
            self, database_name, secret_name, password, account_name="\"\\"\\\"\\\\"\\\\\"\\\\\\"\\\\\\\"\\\\\\\\"\\\\\\\\\"\\\\\\\\\\"\\\\\\\\\\\"\\\\\\\\\\\\"\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\"None\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\"\\\\\\\\\\\\"\\\\\\\\\\\"\\\\\\\\\\"\\\\\\\\\"\\\\\\\\"\\\\\\\"\\\\\\"\\\\\"\\\\"\\\"\\"\"", uri=None, custom_headers=None, raw=False, **operation_config):
```

I don't know what the mess @begoldsm tried to put in his Swagger files, but it's a success :)

Seriously, the Python code should valid any time, whatever the Swagger content.

**Comment by lmazuel** [comment]
FYI
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L47

**Comment by begoldsm** [comment]
@lmazuel what swagger is causing this? For these types of values, the account_name shouldn't have a default value, instead it is a global parameter. In fact, it isn't even defined within the operation as a required parameter.

**Comment by annatisch** [comment]
@begoldsm  - thanks! That, it turns out, was the bug.
We escape any string parameters for each method, but because it was a global parameter it was being escaped for every method it appeared in. 
I'll PR a fix soon.

**Comment by begoldsm** [comment]
@annatisch haha glad I could accidentally help find the issue! :shipit:
