### ISSUE TITLE
Manifest of Azure Clouds and their Endpoints

### ISSUE THREAD

**Issue by colemickens** [Azure/autorest#1204]
Discussion starts here: https://github.com/Azure/go-autorest/pull/74

It'd be helpful if there was a way for the Azure SDKs to be able to automatically generate a class/struct to represent an instance of Azure and generate definitions for each instance (aka "Mooncake", "Fairfax", "Blackforest", "Public Cloud").

As an example, in the Go SDK we have created these manually:
- [`azure.Environment` struct](https://github.com/Azure/go-autorest/blob/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907/autorest/azure/environments.go#L13)
- [`azure.PublicCloud` instance for public Azure](https://github.com/Azure/go-autorest/blob/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907/autorest/azure/environments.go#L32)
- [`azure.USGovernmentCloud` instance for Fairfax](https://github.com/Azure/go-autorest/blob/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907/autorest/azure/environments.go#L50)
- [`azure.ChinaCloud` instance for Mooncake](https://github.com/Azure/go-autorest/blob/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907/autorest/azure/environments.go#L68)
- [`azure.GermanCloud` instance for Blackforest](https://github.com/Azure/go-autorest/blob/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907/autorest/azure/environments.go#L86)

These could, and I would argue should, be auto-generated rather than manually curated.

**Comment by colemickens** [comment]
Ping? @devigned, do you know anyone we should include in this discussion? Somewhere I'd heard that there might be an ongoing effort to centralize this sort of metadata, but I don't remember who was driving that?

**Comment by devigned** [comment]
@fearthecowboy @markcowl any thoughts on this?

**Comment by colemickens** [comment]
Another reason this should be done: https://github.com/Azure/go-autorest/pull/93 read the comments. This stuff isn't centrally documented anywhere and *our own teams* have trouble aggregating it.

**Comment by fearthecowboy** [comment]
@markcowl has a prototype of how we may handle this.

**Comment by fearthecowboy** [comment]
This will be handled with the profile support.
