### ISSUE TITLE
C# code generated for header parameters with maxItems

### ISSUE THREAD

**Issue by older** [Azure/autorest#1215]
Given the following parameter definitions:

``` javascript
{
    "name": "param1",
    "in": "header",
    "required": false,
    "type": "string",
    "maxItems": 1
},
{
    "name": "param2",
    "in": "header",
    "required": false,
    "type": "string",
    "format": "byte",
    "maxItems": 1
}
```

here's C# code generated with AutoRest 0.16.0:

``` C#
public async Task<...> GetStuffAsync(string param1 = default(string), byte[] param2 = default(byte[]), ...)
{
    if (param1 != null)
    {
        if (param1.Count > 1)
        {
            throw new ValidationException(ValidationRules.MaxItems, "param1", 1);
        }
    }
    if (param2 != null)
    {
        if (param2.Count > 1)
        {
            throw new ValidationException(ValidationRules.MaxItems, "param2", 1);
        }
    }
}
```

This validation code does not compile because neither `string` nor `byte[]` have property `Count`, but even if it would this still doesn't make any sense. Probably `maxItems` is used here in attempt to prevent duplicate HTTP headers for `param1` and `param2` and not to limit maximum number of characters in string or bytes in array.
Even if it is wrong usage of `maxItems` swagger validator does not issue any errors or warnings about it.

**Comment by tbombach** [comment]
I believe this is an incorrect usage of `maxItems`, per JSON Schema: http://json-schema.org/latest/json-schema-validation.html#anchor42 (`maxItems` appears under Array validation, so I don't think it can be used with other types).

I'm adding Swagger validation as a dedicated step in AutoRest (see this PR https://github.com/Azure/autorest/pull/1246) - it will show warnings and errors like this before trying to generate code. I'll add some rules so that there's feedback for using a constraint that can't apply to the specified type.

**Comment by older** [comment]
I do agree that it is incorrect usage of `maxItems` but Swagger UI gives this usage green "VALID" badge and online Swagger Editor gives "Processed with no error" message. But I also think that it is still a bug in AutoRest which generates invalid C# code out of this.

**Comment by olydis** [comment]
I can't reproduce this behavior with the current version.
As one would expect, no `if (param1.Count > 1)` is generated (unless `type` is `array`).

**Comment by older** [comment]
@olydis There should not be any `.Count` generated even if type is array. It should be `.Length` in this case.

**Comment by olydis** [comment]
`type: array` is modeled as `IList`, hence we use `Count`. 

If you have a case that actually creates a C# array, please post it. Your initial example (that generates `byte[]`) does **not** generate `.Count` anymore.
