### ISSUE TITLE
Code Generation when array item of type object is defined inline, produced IList<object> with no definition

### ISSUE THREAD

**Issue by arulnithi** [Azure/autorest#1221]
When I define a object of type array, and define the item type inline, AutoRest is unable to produce a well defined type.

Eg.
```
Schema" : {
			"type" : "object",
			"properties" : {
				"columns" : {
					"type" : "array",
					"items" : {
						"Column" : {
							"type" : "object",
							 "properties" : {
								"name" : {
									"type" : "string",
								},
								"maxLength" : {
									"type" : "integer",
								},
							},
						},
					},
				},
			},
		},
```

produces the following object model, without ever creating a object definition for the inline object.

`public Schema(IList<object> columns)`

Works fine when the object is referenced and defined outside

**Comment by devigned** [comment]
We try to encourage using named schema as it will make your generated clients much better (names and often reuse of types). When we try to infer type names based on context, they tend to turn out badly.

@fearthecowboy do you have any thoughts on this?

**Comment by arulnithi** [comment]
I don't disagree with that, makes plenty of sense to me. 
I guess I was misled by the documentation here : https://github.com/Azure/autorest/blob/master/Documentation/defining-clients-swagger.md#type-name-generation
It seems to suggest that objects can be defined inline

**Comment by devigned** [comment]
Agreed. That should evaluate to a strongly typed generic.

**Comment by fearthecowboy** [comment]
Yeah, Definitely a bug.

**Comment by John-Hart** [comment]
@arulnithi are you still seeing this issue?  I haven't been able to reproduce it.  Can you please provide a full json file that reproduces the problem?   Thanks!
