### ISSUE TITLE
SafeJsonConvert not Deserializing entire object

### ISSUE THREAD

**Issue by bl1nkr** [Azure/autorest#1227]
On one of my methods I get the entire payload back from the server

_responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);

I can see the entire json string. But after 

_result.Body = SafeJsonConvert.DeserializeObject<IList<MyObjectTypeHere>>(_responseContent, this.Client.DeserializationSettings);

I get back the list but only one property has data and the are null.  Any advice?

I used the autorest.exe and i am running Microsoft.Rest.ClientRuntime 2.3.1 and JSON.NET 9.0.1

thanks!

**Comment by brjohnstmsft** [comment]
There is nothing special about `SafeJsonConvert` except that it doesn't inherit global `JsonSerializerSettings` the way that `JsonConvert` does. Can you repro this issue with just `JsonConvert`? What about with older versions of JSON.NET?

**Comment by bl1nkr** [comment]
I had an error in my swagger.json config file.  Sorry for blaming the serialier =)
