### ISSUE TITLE
Java RestClient does not honor x-ms-parameterized-host and host template

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1234]
When parameterized host template is used with [x-ms-parameterized-host](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-parameterized-host), the RestClient does not honor the host template. here is the generated code with autorest:

```
    public KeyVaultClientImpl(ServiceClientCredentials credentials) {
        this("{vaultBaseUrl}", credentials);
    }

    private KeyVaultClientImpl(String baseUrl, ServiceClientCredentials credentials) {
        this(new RestClient.Builder()
                .withBaseUrl(baseUrl)
                .withCredentials(credentials)
                .build());
    }
```
when constructing RestClient, the following error is thrown:
   `java.lang.IllegalArgumentException: Illegal URL: {vaultBaseUrl} `

Also the parameterizedHost is added as a header in the request, while it should be replacing the baseUrl -> `@Header("x-ms-parameterized-host") String parameterizedHost`

Here is an example of an auto-generated method API for Key Vault and the baseUrl is passed in as the first argument:
```
public ServiceResponse<KeyBundle> createKey(String vaultBaseUrl, String keyName, String kty) throws KeyVaultErrorException, IOException, IllegalArgumentException {
        if (vaultBaseUrl == null) {
            throw new IllegalArgumentException("Parameter vaultBaseUrl is required and cannot be null.");
        }
        if (keyName == null) {
            throw new IllegalArgumentException("Parameter keyName is required and cannot be null.");
        }
        if (this.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.apiVersion() is required and cannot be null.");
        }
        if (kty == null) {
            throw new IllegalArgumentException("Parameter kty is required and cannot be null.");
        }
        final Integer keySize = null;
        final List<String> keyOps = null;
        final KeyAttributes keyAttributes = null;
        final Map<String, String> tags = null;
        KeyCreateParameters parameters = new KeyCreateParameters();
        parameters.withKty(kty);
        parameters.withKeySize(null);
        parameters.withKeyOps(null);
        parameters.withKeyAttributes(null);
        parameters.withTags(null);
        String parameterizedHost = Joiner.on(", ").join("{vaultBaseUrl}", vaultBaseUrl);
        Call<ResponseBody> call = service.createKey(keyName, this.apiVersion(), this.acceptLanguage(), parameters, parameterizedHost, this.userAgent());
        return createKeyDelegate(call.execute());
    }
```

And the service Retrofit call definition:
```
@Headers("Content-Type: application/json; charset=utf-8")
@POST("keys/{key-name}/create")
Call<ResponseBody> createKey(@Path("key-name") String keyName, @Query("api-version") String apiVersion, @Header("accept-language") String acceptLanguage, @Body KeyCreateParameters parameters, @Header("x-ms-parameterized-host") String parameterizedHost, @Header("User-Agent") String userAgent);
```

**Comment by jianghaolu** [comment]
The fix I'm planning is described as below.
### Usage
**Scenario 1**: User call
```java
keyVaultClient.createKey("https://www.kid.url", keyName, kty);
```
and it succeeds.
**Scenario 2**: User call
```java
keyVaultClient.createKey("www.kid.url", keyName, kty);
```
also succeeds.
**Scenario 3**: User call
```java
keyVaultClient.createKey("http://www.unsafe-kid.url", keyName, kty);
```
and it succeeds.
**Scenario 4**: User call
```java
keyVaultClient.createKey("www.unsafe-kid.url", keyName, kty);
```
fails.

### What's behind
1. Scheme on base URL is defaulted to `https` when not provided. (Scenario 2 & 4)
2. When a scheme is provided later, URL temporarily turns into "https://https://www.kid.url" (Scenario 1) & "https://http://www.unsafe-kid.url" (Scenario 3). SDK then recognizes this as an invalid URL and cuts all preceding schemes. The last scheme in the URL wins.

### Extension point
For future services that uses other schemes, e.g., `smb`, `ws`, etc, this allows a work-around when Swagger only supports `http` & `https`.

**Comment by pomortaz** [comment]
@jianghaolu Thanks for the proposal! The solution should work for Key Vault.

**Comment by pomortaz** [comment]
@jianghaolu thanks for the fix. The client-runtime library in [this repo](https://github.com/Azure/azure-sdk-for-java) is still missing the solution.
