### ISSUE TITLE
Clean AutoRest.sln configurations

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#1240]
When opening AutoRest.sln in a clean environment the code does not compile. The user needs to know to switch to `Net45-Debug` configuration. That is no longer needed. Please clean build configs and leave only `Debug` and `Release`.

**Comment by fearthecowboy** [comment]
This is actually in progress.... My next PR should cover that.

**Comment by fearthecowboy** [comment]
With the move to `project.json` and `.xproj` projects, we no longer have the `-net45` configurations.
