### ISSUE TITLE
Provide a homebrew formula for OS X

### ISSUE THREAD

**Issue by lumaxis** [Azure/autorest#1247]
It's really nice to be able to run autorest on OS X using mono but it would be even nicer to streamline the installation process a bit.
Is this something you've been looking at/plan to do?

**Comment by devigned** [comment]
We are looking to move AutoRest to .NET Core. When that happens, we won't need the mono dependency, which is rather heavy.

After we make that move, we'll introduce a homebrew formula.

**Comment by lumaxis** [comment]
Sounds perfectly reasonable, thanks @devigned! :)

**Comment by fearthecowboy** [comment]
It's all npm now!
