### ISSUE TITLE
C#: please add options to generate GetHashCode(), Equals()/IEquatable and INotifyPropertyChanged

### ISSUE THREAD

**Issue by tdjastrzebski** [Azure/autorest#1251]
Please add an options to optionally generate GetHashCode(), Equals()/IEquatable and INotifyPropertyChanged methods im Model classes.
The first two are "nice to have" but can be added via partial class although require "manual" maintenance.
The last one, INotifyPropertyChanged, is "must have" in applications employing data binding.

**Comment by fearthecowboy** [comment]
That's a really good idea. I don't know that we can do this for 1.0, but I certianly think it's worth doing.

**Comment by tdjastrzebski** [comment]
Without such features the generated model is suitable only for basic usage.
I can use it only for unit tests. For anything else I have to use other solutions.

**Comment by weitzhandler** [comment]
Very compelling. AutoRest is no news for XAML developers without INPC support.

**Comment by fearthecowboy** [comment]
I've been looking at adding these; it's something that we can address after our immediate set of feature work is done.

**Comment by weitzhandler** [comment]
VS is like an uncomplete product without proper client entity generation...
The only thing I'd really love to see is an additional tab in web projects that customizes the swagger configuration, and runs the client-entity generation process upon each **build** of the web project automatically. That would be awesome!

**Comment by fearthecowboy** [comment]
Adding to the list for inclusion in vNext generator support. INPC/etc is really important to do right. (#2448)

**Comment by weitzhandler** [comment]
Meanwhile, you can use [Fody/PropertyChanged](/Fody/PropertyChanged) to apply on all partial classes of the generated entities. Works like a charm.

**Comment by tdjastrzebski** [comment]
In the meantime I build my own entity generator (just entities, no methods) generating GetHashCode(), Equals()/IEquatable and INotifyPropertyChanged.
