### ISSUE TITLE
[C#] Add DataContract and DataMember(EmitDefaultValue=false) attributes

### ISSUE THREAD

**Issue by tdjastrzebski** [Azure/autorest#1256]
Please decorate model properties with [DataMember(Name="xxx", EmitDefaultValue=false)] attributes, clases with [DataContract]

**Comment by olydis** [comment]
This is nothing we'll "just" add to our code gen (it introduces dependencies, produces overhead...).
Nowadays you may use Roslyn to adjust what AutoRest generates for your own needs, like adding the attributes you suggest.

We are also planning to make user-written customizations pluggable into the AutoRest pipeline, but for custom code-gen needs like yours I would strongly recommend Roslyn for now.

**Comment by fultonm** [comment]
+1 

Is the Simplify suggestion still recommended to check out in 2024?
