### ISSUE TITLE
Common Headers object to be used across multiple operations

### ISSUE THREAD

**Issue by arulnithi** [Azure/autorest#1259]
Currently I have multiple operations that return somewhat similar headers in the response. Say for example a register operation that can be used to POST different assets. However since the type of asset is specified in the path, these are all modeled as different Operation objects in Swagger. 

Hence, when I receive the headers for these operations, they are all different classes modeled by AutoRest, while containing the same basic information. 

I haven't found any way to model it in Swagger for AutoRest to package the response headers into a generic Headers object

Eg.

```

"paths" : {
    "genereric_enpoint/asset_type/AssetA" : {
        "post" : {
            "responses" : {
                "200" : {
                    "headers"  :  {
                        "X"  : {  "type" : "string" },
                        "Y"  : {  "type" : "string" }
                    }
                }
            }
        }
    },  
    "genereric_enpoint/asset_type/AssetB" : {
        "post" : {
            "responses" : {
                "200" : {
                    "headers"  :  {
                        "X"  : {  "type" : "string" },
                        "Y"  : {  "type" : "string" }
                    }
                }
            }
        }
    },
}
```

Currently these two operations return different header objects, and it really adds up over different operations and response types, ( I currently have over 60+ specific header objects when I ideally only need about 4)

I am not sure if there is currently any features in AutoRest to specify a generic Header object, but I have not found any in the documentation.

**Comment by fearthecowboy** [comment]
This is kindof a limitation in swagger. The `headers`  is an associative array that is used to generate the headers class that the response uses.

It is somewhat *possible* to try to compare all the generated `Headers` classes and merge them if they're identical, but I don't see it happening before 1.0 (this fall).  This may be easier to do when we make the pipeline a bit more open.

**Comment by olydis** [comment]
we had this coming up during the hackathon, it was *really* painful there: lots of identical classes, that furthermore had to be processed further (hand-written convenience layer), so the code duplication in the auto generated code caused further code duplication in hand-written code.

**Comment by olydis** [comment]
if we wanna fix this, I'd propose allowing a `$ref` to the `definitions` section in `headers`. AFAIK, this is not allowed as per the OpenAPI 2.0 spec so we don't collide with existing interpretations. It would also automatically allow us to customize the horrible class name chosen for header classes.

**Comment by olydis** [comment]
oh, I have fixed this some time ago! You can now reference model types from the `definitions` section as shown in [this](https://github.com/Azure/autorest/blob/master/Samples/test/shared-response-header-types/shared-headers.yaml#L168) example 😄 
Our recommendation is to *also* model the response headers regularly to express the same information in a standard compliant way.
