### ISSUE TITLE
Redundant collection format suffix in path parameters?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest#1264]
Today when we have an array typed object in path, we add the collection format to the path parameter in the modeler.
E.g., `/arrays/{arrayPath}` will be normalized into `/arrays/{arrayPath:commaSeparated}`, if the collection format is CSV.
However, in `Parameter` in the client model's `ServiceClient` object, we still have the property `CollectionFormat`, which seems to make the normalization redundant. 

The issue arises from Java code generator. Colons (":") are not allowed in path parameters in Retrofit. (In Java 8 there's a mapping between this variable name and actual variable name, which makes : an invalid character) That gives me the chance to look at it and the suffix actually seems to have no need to exist.

**Comment by dsgouda** [comment]
Fixed here https://github.com/Azure/autorest/commit/4983df2cc1335554f244d9ac8cd46c980217847f
