### ISSUE TITLE
IList with MinLength annotation generates incorrect c# code

### ISSUE THREAD

**Issue by bruceharrison1984** [Azure/autorest#1282]
When using the following as a property within a request model on the server side:
```
        [Required]
        [MinLength(1)]
        public IList<StackUser> Users { get; set; }
```

Swashbuckle produces the following swagger.json
```
users: {
  minLength: 1,
  type: "array",
    items: {
        $ref: "#/definitions/StackUser"
    }
}
```
AutoRest produces invalid c# when generating client side libraries for the same object. This is based on a swagger file:
```
        [JsonProperty(PropertyName = "users")]
        public IList<StackUser> Users { get; set; }

        public virtual void Validate()
        {
            if (Users == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Users");
            }
            if (this.Users != null)
            {
                if (this.Users.Length < 1) <---no Length property on IList
                {
                    throw new ValidationException(ValidationRules.MinLength, "Users", 1);
                }
                foreach (var element in this.Users)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
```

IList does not contain a property called `Length`. It instead uses `Count`.

http://stackoverflow.com/questions/34954180/why-ilistt-does-not-contain-a-length-property

**Comment by older** [comment]
It seems to be a bug in Swashbuckle which produces minLength/maxLength not only for strings but for arrays/lists as well while it should be producing maxItems/minItems. In JSON Schema minLength/maxLength are documented only as [validation keywords for strings](http://json-schema.org/latest/json-schema-validation.html#anchor25).
I filed somehow similar but reverse  issue #1215 where maxItems was used for strings and @tbombach pointed out that in JSON Schema these are documented under arrays and not strings.

**Comment by fearthecowboy** [comment]
Yes. We'll add this to the 1.0 buglist.
