### ISSUE TITLE
Error converting value "null" to type  'System.Nullable'

### ISSUE THREAD

**Issue by nandaccio** [Azure/autorest#1287]
I'm not sure about the root cause of this kind of errors:

Code generation failed.
AutoRest.exe -AddCredentials true -NameSpace Nando -CodeGenerator CSharp -Modeler Swagger -Input swagger2.json -verbose
**error: [FATAL] Error parsing swagger file. Error converting value "null" to type
 'System.Nullable`1[Microsoft.Rest.Modeler.Swagger.Model.DataType]'. Path 'type'
, line 2, position 17.**
INFO: AutoRest Core 0.16.0.0
INFO: Initializing modeler.
INFO: Initializing modeler.
INFO: Parsing swagger json file.

Input:

```javascript
 "responses":{
                    "default":{
                        "description":"TODO - what is the hypermedia description of a default response?",
                        "schema":{
                           "type":"null",
                            "description":"No content returned on delete",
                            "title":"No content"
                        }
                    }
                },
```

**Comment by fearthecowboy** [comment]
The error could be better here, but essentially, `null` is not a valid `type` -

The type MUST be one of `string`, `number`, `integer`, `boolean`, or `array`.
