### ISSUE TITLE
Composite Modeler handling of api-version 

### ISSUE THREAD

**Issue by annatisch** [Azure/autorest#1294]
Hi Autorest team, I have a question :)

We have a current open issue on the Azure SDK for Python regarding the handling of api-version in composite modeler generated clients. In summary - they would prefer that it didn't become a method parameter but rather become an attribute of the operations class and therefore less likely to be modified by a user. Fair enough.

So my question is, according to CompositeSwaggerModeler.cs it seems that api-version is handled as an explicit exception during the merging of sub-clients, rather than being part of any generic logic for handling conflicting sub-client parameters. Can you verify that this is this case?

If so, do you think the best way for me to approach this is to also handle api-version explicitly and move this parameter out of the methods and onto the operations class, or would a better solution be to make some adjustments to the Modeler code to mark/identify method parameters that have been moved out of a client so that I can handle them differently when generating the operations (this assumes that in future api-version may not be alone in how it's handled).

Let me know what you think.
Cheers,
Anna

@lmazuel, @johanste
Original issue: https://github.com/Azure/azure-sdk-for-python/issues/697

**Comment by amarzavery** [comment]
CIL.


________________________________

**Comment by annatisch** [comment]
Thanks @amarzavery!
So it looks like in the Node generator - api-version is handled in with generic handling for constants rather than any special treatment. I prefer this approach so I'll add some handling for constants in method to Python and move them to the Operations class level.

**Comment by annatisch** [comment]
Fixed Python handling of operation constants in #1302
