### ISSUE TITLE
HTTP Errors / Exceptions

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#1295]
HTTP Errors and Exceptions should provide all HTTP first principles data in exceptions. They should include the request / response headers, body, uri, etc., so that a consumer of the library could reproduce the request using PS or curl.

The error messaging should also contain actionable content as often as possible.

For an example of inadequate output see: https://github.com/Azure/azure-sdk-for-net/issues/2194

**Comment by rshirani** [comment]
Any update on this? Any possibility that I can debug more while this is in progress?

**Comment by fearthecowboy** [comment]
Yeah, we should look at including this in the 1.0. timeframe.

@rshirani -- no, not yet, we're prioritizing bugs and features for the 1.0 release this fall, and I think this would be really good to get in there, but I have to find time to schedule it in.

**Comment by fearthecowboy** [comment]
This is handled by the client runtimes.
