### ISSUE TITLE
[Python] x-ms-external is interpreted as "true" even if define with "false"

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1304]
The absence of x-ms-external is considered as "false", as it should.

However, its presence, whatever the value is considered as "true". This makes declaration like this one impossible to generate in Python:
```json
    "Resource": {
      "x-ms-azure-resource": true,
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Resource Id"
        },
      },
      "x-ms-external": false
    },
```

@annatisch

**Comment by annatisch** [comment]
Thanks @lmazuel  - I've started on the fix and will PR soon.
