### ISSUE TITLE
x-ms-parameter-grouping cannot have a custom description

### ISSUE THREAD

**Issue by seansaleh** [Azure/autorest#1310]
Today using x-ms-parameter-grouping generates a comment such as 

```
            /// <param name='searchRequestOptions'>
            /// Additional parameters for the operation
            /// </param>
```

When using multiple parameter groupings the comments on an operation become redundant and not useful. 
For example, after adding a second parameter grouping our comments on a operation look like this:

```
            /// <param name='searchRequestOptions'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='accessCondition'>
            /// Additional parameters for the operation
            /// </param>
```

It would be useful to be able to define a description somewhere that would propagate to the operation's parameter comments.

**Comment by brjohnstmsft** [comment]
👍

**Comment by fearthecowboy** [comment]
Yes, let's add a description to the `x-ms-parameter-grouping` construct.

**Comment by fearthecowboy** [comment]
adding to autorest 3.0 design.
