### ISSUE TITLE
Annotation to hide confidential properties from log

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1326]
I got a feedback from a customer that it's not acceptable to write in the log the password of a VM. The customer told me that they are very concerned about security and leak of passwords inside logs, and this might blocks adoption of the SDK. Actually, for Python, in Debug level we write the full payload in the log, including information like the admin password when creating a VM.

I thought about it and it seems to me that it's a cross language problem. We don't want C#, the PythonCLI or NodeJS to display this information as well.

I think an annotation like `x-ms-confidential: True` is the best way to handle this problem. It's cross-language. The implementation is easy: looking for this annotation and replace by `****` if a confidential field is found before logging. It's easy to add into a Swagger file.

Without an annotation, I will have to maintain a manual list of confidential fields. And each language will have to do something on their own if they are concerned about this.

**Comment by annatisch** [comment]
Thanks @lmazuel 
I'm not quite sure what this would look like in practice.
Some thoughts from the Python perspective:
- The easiest option would be to remove the request/response logging that we do, though I find I use it often and it's very helpful - do we know what other teams/customers thoughts on this are?
- Alternatively, rather then try to isolate sensitive properties, is there any way to configure the logging class or give users options to encrypt all the logging if they believe that their traffic is confidential?
- It would be difficult to filter specific properties from the logs, though I guess it would be straight forward to use an extension to mark a whole request body as 'confidential' and not log it, though I guess the same logic would also apply to headers?

**Comment by lmazuel** [comment]
@annatisch 
From the Python perspective:
- Remove all log which use directly the payload
- Add a "confidential: True" flag in impacted model
- Add "confidential mode" to "serialize()", which change impacted model to "******"
- If log level is DEBUG, call "serialize(..., confidential=True)" to compute a JSON payload for log. Yes, it has an extra cost, but if the user is using DEBUG level anyway it can expect an extra cost (and honestly it's not that much...)

**Comment by annatisch** [comment]
@lmazuel,
That sounds like a good plan. We should be able to make these changes to the runtime before the extension is complete.

**Comment by lmazuel** [comment]
Won't fix
