### ISSUE TITLE
[C#] ServiceClientTracing does not log headers added through custom DelegatingHandler

### ISSUE THREAD

**Issue by georgeck** [Azure/autorest#1329]
When a `DelegatingHandler` modifies the `HttpRequestMessage` with custom header, that header is not logged as part of the  `IServiceClientTracingInterceptor.SendRequest()`. Also the `UserAgent` that is added by default is not logged.

In my case, I created a custom DelegatingHandler that adds a correlation ID to the header. I would like this header value to be logged.

This issue happens because, the `ServiceClient` invokes the `ServiceClientTracing.SendRequest()` with the `HttpRequestMessage` object that it creates and not the one that the `HttpClient` is passing through its pipeline.

One solution would be for AutoRest to inject a `DelegatingHandler` before the innermost HTTP handler (which is the end of send HTTP pipeline). At this point the `HttpRequestMessage` would have gone through all the handlers in the pipeline and would be a true representation of what goes on the wire. This injected handler can then call `ServiceClientTracing.SendRequest()`.

**Comment by georgeck** [comment]
Let me know if the above solution is the right approach. If so, I am happy to send a pull request with these modifications.

**Comment by olydis** [comment]
this sounds like a client runtime issue. If this is still an issue, please open an issue against the corresponding [repo](https://github.com/Azure/azure-sdk-for-net)
