### ISSUE TITLE
AutoRest CSharp code assumes JSON - provide support for different formatters (like Bond or Binary)

### ISSUE THREAD

**Issue by chandramouleswaran** [Azure/autorest#1330]
Today the client code generation is great except it is assuming everything happens in JSON which is not the case always - we have a service which supports custom serialization mechanism using **Bond** and also supports JSON.

The content negotiation pipeline on the server decides which serialization mechanism to use.

Ideally, we would like to be able to detect the format (using produces section in swagger JSON) and setup the code generation pipeline accordingly.

Are there any extensibility points into the current code generation pipeline that can be leveraged here?

**Comment by tbombach** [comment]
Hi @chandramouleswaran. One of the things we're looking to do in AutoRest is support other content types besides JSON. Our impetus for this is make sure we support XML for our 1.0 release, but we're looking to do it in an extensible way that allows anyone to plug in serialization code for other types.

We're tracking this work here: https://github.com/Azure/autorest/issues/823, so I'll close this one. Please feel free to follow that issue or add anything to that discussion.
