### ISSUE TITLE
[Java] The enum modeled as string does not accept string type

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1334]
In the swagger spec for the x-ms-enum extension, when the enum type is set to be of type string, e.g. "modelAsString": true, in Java generated code the property is not of type string.

For example for:
```
        "kty": {
          "type": "string",
          "description": "Key type, usually RSA",
          "enum": [ "EC", "RSA", "RSA-HSM", "oct" ],
          "x-ms-enum": {
            "name": "JsonWebKeyType",
            "description": "Supported JsonWebKey key types (kty) for Elliptic Curve, RSA, HSM, Octet",
            "modelAsString": true
          }
```
The generated code sets the type of kty of JsonWebKeyType, where JsonWebKeyType is defined as follow:

```
/**
 * Defines values for JsonWebKeyType.
 */
public final class JsonWebKeyType {
    /** Static value EC for JsonWebKeyType. */
    public static final JsonWebKeyType EC = new JsonWebKeyType("EC");

    /** Static value RSA for JsonWebKeyType. */
    public static final JsonWebKeyType RSA = new JsonWebKeyType("RSA");

    /** Static value RSA-HSM for JsonWebKeyType. */
    public static final JsonWebKeyType RSA_HSM = new JsonWebKeyType("RSA-HSM");

    /** Static value oct for JsonWebKeyType. */
    public static final JsonWebKeyType OCT = new JsonWebKeyType("oct");

    private String value;

    /**
     * Creates a custom value for JsonWebKeyType.
     * @param value the custom value
     */
    public JsonWebKeyType(String value) {
        this.value = value;
    }
```
 This is against the goal of setting the data type of string to avoid code change if an additional value is introduced.

**Comment by pomortaz** [comment]
@jianghaolu, can you please take a look?

**Comment by jianghaolu** [comment]
This is by design. This provides strongly typed method signature. Otherwise users have no idea they can find an enum to fill in the place when the method is asking for a `String`.

**Comment by pomortaz** [comment]
Then what would be the benefit of using "modelAsString": true or "modelAsString": false?

**Comment by jianghaolu** [comment]
E.g.
`void foo(JsonWebKeyType keyType)` indicates you can type `JsonWebKeyType.` and you should be able to find a value you need. (Of course, proper naming is also required to psychologically indicate the user that this is an enum. But bottom line, this provides the same experience as an Enum type.)
However, `void foo(String keyType)` isn't very helpful.

**Comment by jianghaolu** [comment]
`modelAsString` was introduced for the purpose of extendable enums. Traditional enums don't allow any value outside the hardcoded set. This provides that extensibility.

**Comment by pomortaz** [comment]
For other language the ```void foo(String keyType)``` has a documentation describing that what are the accepted values in string.
How can I extend the JsonWebKeyType ```void foo(JsonWebKeyType keyType)``` without making a code change? This contradicts the original goal of it.

**Comment by jianghaolu** [comment]
We don't have the intention to generate code that "looks like other languages".
> How can I extend the JsonWebKeyType void foo(JsonWebKeyType keyType) without making a code change?
Let's weigh the pros and cons.
Pros: You get strongly typed suggestion. It's counter-intuitive to ask developers (at least for me) to find that one class that happens to have a static final field that provides the value I need. 
Cons: Instead of `foo("customValue")` you call `foo(new JsonWebKeyType("customValue"))`. It's intuitive for a developer to try to new a class when they see it on the method signature.

**Comment by pomortaz** [comment]
I see. Thanks @jianghaolu.
