### ISSUE TITLE
Publishing build for client runtimes did not strong name sign a published file

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#1347]
In this job:http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/98/console 

The file Microsoft.Rest.ClientRuntime.Azure.Authentication.dll is shown as fully signed (the check merely checks the strong name token, not the signature, and this check appears to pass for both signed and delay signed assemblies).  However in the package published from this job here: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/2.2.7-preview

It is not.

Need to add a check to signing and publishing jobs that actually checks the strong name signature, using sn.exe -vf or the like.

**Comment by fearthecowboy** [comment]
fixed in build system long ago. (and moved to other repo)
