### ISSUE TITLE
pre processor moniker "portable" is being overloaded for netStandard 1.1 and 1.5

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/autorest#1348]
Currently in Microsoft.Rest.ClientRuntime we have defined "portable" as a preprocessor directive in project.json file for both .netStandard 1.1 and 1.5.
We should stop using "portable" and switch to using NETSTANDARD1_1 and NETSTANDARD1_5 for each of the standards in the code.

**Comment by fearthecowboy** [comment]
Client Runtime is in the azure-sdk-for-net repo now. Please refile there ;D
