### ISSUE TITLE
[Python] Namespace command removes underscore

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1356]
Using Autorest with command "-Namespace azure.mgmt.compute.v2016_03_30" leads to incorrect Docstring:

```python
:type pass_name: str or :class:`PassNames
 <azure.mgmt.compute.v20160330.models.PassNames>`
```

We need to keep the underscore in the Docstring, `azure.mgmt.compute.v2016_03_30` being a valid namespace in Python.

**Comment by annatisch** [comment]
Yeah - I suspect that it goes through some kind of unnecessary class name serialization. Should be simple to resolve.
