### ISSUE TITLE
Support for Collection of Validation Exceptions

### ISSUE THREAD

**Issue by SimonRoodt** [Azure/autorest#1360]
I am using the AutoRest generator to generate a proxy for my WebAPI. I was wondering if you have added support for a collection of validation errors. The generated code for a dto returned from my WebAPI looks something like this....

public virtual void Validate()
{
    if (Property1 == null)
    {
        throw new ValidationException(ValidationRules.CannotBeNull, "Property1");
    }
    if (SchemeName == null)
    {
        throw new ValidationException(ValidationRules.CannotBeNull, "SchemeName");
    }
    if (this.Property2 > 2147483647)
    {
        throw new ValidationException(ValidationRules.InclusiveMaximum, "Property2", 2147483647);
    }
    if (this.Property2 < 1)
    {
        throw new ValidationException(ValidationRules.InclusiveMinimum, "Property2", 1);
    }
}

Exceptions are thrown individually, which makes things rather difficult when we want to validate say some form input in an application. If you have not already added this support would it not be possible to validate every property of the dto adding validation errors to a collection and then throwing a validation exception containing ALL errors at the end.

If this support is already built in, please could you point me in the right direction.

Thanks

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-1.0 planning cycle.

It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 1.0. 🏇 🏇 🏇

We'll make sure we pick this back up at that point. 🎉
