### ISSUE TITLE
[Java] the JSON serialization on the generated code is not working as expected

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1361]
The generated code has partial @JsonProperty annotations, which causes that the default JSON serializer don't work for them. 
For example in [this generated code](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-keyvault/src/main/java/com/microsoft/azure/keyvault/models/Attributes.java), some of the filed that in the swagger are named using x-ms-client-name field, have the @JsonProperty added for them but for the rest of the fields, the annotation is missing. Because those fields are private and not annotated the default JSON serializer using `ObjectMapper`does not serialize them properly.
Also, the Base64Url objects don't get serialized properly and they contain extra fields.

**Comment by martinsawicki** [comment]
pri-2

**Comment by fearthecowboy** [comment]
@jianghaolu  - is this still an issue? can we close this?

**Comment by jianghaolu** [comment]
Fixed.
