### ISSUE TITLE
[C#] Default service client missing "System." in documentation strings

### ISSUE THREAD

**Issue by matthew-rollitt** [Azure/autorest#1363]
By default when generating a service client if the documentation string contains an exception it is missing a reference to "system"

        /// <summary>
        /// Initializes a new instance of the BatchServiceClient class.
        /// <exception cref="ArgumentNullException"> this should be -> /// <exception cref="System.ArgumentNullException">
        /// Thrown when a required parameter is null
        /// </exception>
        protected FooServiceClient(System.Uri baseUri, System.Net.Http.HttpClientHandler rootHandler, params System.Net.Http.DelegatingHandler[] handlers) : this(rootHandler, handlers){....}
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown when a required parameter is null
        /// </exception>
public FooServiceClient(System.Uri baseUri, Microsoft.Rest.ServiceClientCredentials credentials, System.Net.Http.HttpClientHandler rootHandler, params System.Net.Http.DelegatingHandler[] handlers){...}

Note: This only happens for 2 of the default constructors, the other ones generating "<exception cref="System.ArgumentNullException">" are fine

**Comment by matthew-rollitt** [comment]
Hi John, can we get an update on this? We wanted to use the most recent build but this is preventing us from using it.

**Comment by matthchr** [comment]
@John-Hart @tbombach @fearthecowboy -- Is there a build change that has to happen here so that this sort of error can be caught in this repo as part of CI?

The current experience of, "break in AutoRest gets shipped and then causes a build break in some downstream repo which has `warningsAsErrors = true`" is unfortunate.

AutoRest should generate warning free code whenever possible

**Comment by John-Hart** [comment]
@matthchr We do have some CSharp tests that will fail if there are warnings level 2 or worse, we know there are some level 4 and some CS1701 warnings at times in the generated code. In this particular case, I believe you also have to have /doc:file in order for the compiler to produce an error which we do not have.  I'll look at adding a test for that.
