### ISSUE TITLE
[Python] InteractiveCredentials never gets token

### ISSUE THREAD

**Issue by mozlight** [Azure/autorest#1372]
In `azure_active_directory.py`, class `InteractiveCredentials` has `set_token` method and calls it.
However, `set_token` method has a positive parameter `response_url`, and it seems that `InteractiveCredentials` never substitutes this argument.

**Comment by olydis** [comment]
@mozlight @lmazuel This issue is pretty old. If this is still a concern, please reopen it.

**Comment by lmazuel** [comment]
@olydis Still a concern, but moving to https://github.com/Azure/msrestazure-for-python/issues/36
