### ISSUE TITLE
Allow user to specify that LRO threads should be daemon threads

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest#1378]
In our CLI we want the user to be able to exit the program and return to the command line by pressing Ctrl+C. Effectively this allows us to forego waiting for LongRunningOperations to finish. I've created a pull request https://github.com/Azure/azure-cli/pull/757 that permits this by replacing the default implementation of `AzureOperationPoller.__init__` with a custom implementation that sets the poller's thread type to be a daemon thread. This has to happen between the time the thread is created and its start method is called. It would be helpful if one could specify their desire to use daemon threads for LROs so this would not be necessary.

**Comment by lmazuel** [comment]
Released msrestazure 0.4.3 with thread Daemon by default.
Created another issue for adding this to configuration if needed by someone one day (low priority backlog) https://github.com/Azure/autorest/issues/1416

Thanks @tjprescott for the report!
