### ISSUE TITLE
Generated code for ServiceClient and Model Classes do not have XML doc comments for the class

### ISSUE THREAD

**Issue by John-Hart** [Azure/autorest#1387]
For example, notice there are no XMLdoc comments for ResultObject:

namespace Test.Models
{
    using System.Linq;

```
public partial class ResultObject
{
    /// <summary>
    /// Initializes a new instance of the ResultObject class.
    /// </summary>
    public ResultObject() { }
```

**The same is true for Model classes:**

namespace Test.Models
{
    using System.Linq;

```
public partial class ResultObject
{
    /// <summary>
    /// Initializes a new instance of the ResultObject class.
    /// </summary>
    public ResultObject() { }
```

If compiled with /doc option and Warning level 4 the follow errors occur:

Error   CS1591  Missing XML comment for publicly visible type or member 'SimpleAPI'
Error   CS1591  Missing XML comment for publicly visible type or member 'ResultObject'

**Comment by John-Hart** [comment]
There are other XML doc compiler warnings that you may want to clean up. For example for the generated code for azure-rest-api-specs\arm-cdn\2015-06-01\swagger\cdn.json:


\Operation.cs(24,74): warning CS1573: Parameter 'display' has no matching param tag in the XML comment for 'Operation.Operation(string, OperationDisplay)' (but other parameters do)_

These are also just level 4 warnings but it would be nice to be clean here.

**Comment by olydis** [comment]
@fearthecowboy Seems like indeed no XMLdoc is created unless there is a `description` provided for the model. What description should we default for?

**Comment by fearthecowboy** [comment]
Hmm. Description is a highly-recommended field, and is caught by the validation rules. If it's not specified, maybe we don't care? 

If it actually puts the description on for ones with a description, then go ahead and close this.

**Comment by olydis** [comment]
As far as I can tell, it does.

Feel free to reopen with counterexample.
