### ISSUE TITLE
[C#] Unable to use ApplicationTokenProvider.LoginSilentAsync to generate tokens for Azure KeyVault

### ISSUE THREAD

**Issue by anthonyphelps** [Azure/autorest#1389]
I have determined the parameters that I should be using by making an unauthenticated request to my vault:

`curl -i https://mycompany.vault.azure.net/keys?api-version=2015-06-01`

Which returns the relevant header:

`WWW-Authenticate: Bearer authorization="https://login.windows.net/<mytenantidguid>", resource="https://vault.azure.net"`

So I attempted the following:

``` c#
ActiveDirectoryServiceSettings vaultSettings = new ActiveDirectoryServiceSettings()
{
    AuthenticationEndpoint = ActiveDirectoryServiceSettings.Azure.AuthenticationEndpoint,
    TokenAudience = new Uri("https://vault.azure.net", UriKind.Absolute),
    ValidateAuthority = ActiveDirectoryServiceSettings.Azure.ValidateAuthority
};

var creds = ApplicationTokenProvider.LoginSilentAsync(mytenantidguid, new ClientCredential(clientID, clientSecret), vaultSettings);

using (KeyVaultClient client = new KeyVaultClient(creds))
{
    var result = await client.GetKeysAsync("https://mycompany.vault.azure.net/");
}
```

This will throw Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'Unauthorized'

I came across issue #835 and tried the code there (using AuthenticationContext.AcquireToken directly) with the same parameters and was able to generate a token that works. When I cloned autorest and stepped through ApplicationTokenProvider I discovered this line in LoginSilentAsync:

`var audience = settings.TokenAudience.ToString();`

I had created my Uri with `"https://vault.azure.net"` but Uri.ToString() was returning `"https://vault.azure.net/"` and that value is used to acquire the token, which the vault API refuses to accept because the audience does not match exactly what it is expecting.

**Comment by yuedai** [comment]
You can implement a new Uri class based on System.Uri, and remove the trailing slash.

**Comment by olydis** [comment]
Authentication is part of the [client runtime](https://github.com/Azure/azure-sdk-for-net). Please reopen the issue there if it is still a problem.
