### ISSUE TITLE
example element in swagger schema definition cannot be object type

### ISSUE THREAD

**Issue by hongyes** [Azure/autorest#139]
When I try to parse a swagger document which contains an example property under schema definition. It gives following error:
error: [FATAL] Error parsing swagger file. Error reading string. Unexpected token: StartObject. Path 'example', line 11, position 15.

It seems that the tool can only parse example property with string type. However, in swagger 2.0 spec, it defines example as any type. Here is an example model from the spec:

{
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "example": {
    "name": "Puma",
    "id": 1
  }
}

**Comment by matt-gibbs** [comment]
The modeler needs to be changed to support the "example" field of type "any" as described [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object). This refers to model definitions.

**Comment by hovsepm** [comment]
Fixed in Release 0.10.0 - [nuget](https://www.nuget.org/packages/AutoRest/), [chocolatey](https://chocolatey.org/packages/AutoRest), [github] (https://github.com/Azure/autorest/releases/tag/AutoRest-0.10.0)
