### ISSUE TITLE
UWP Use

### ISSUE THREAD

**Issue by RonFrick** [Azure/autorest#1400]
So do I understand this correct, I can use this on iOS and Android but not in a UWP app?

**Comment by tbombach** [comment]
Hi @RonFrick. Are you referring to the code generated by AutoRest? We support a number of languages/platforms. Android is supported with Java generation (see our [building-code documentation page](https://github.com/Azure/autorest/blob/master/Documentation/building-code.md). UWP apps can run with [.NET Core](https://www.microsoft.com/net/core) libraries, which our C# generated code runs on.

We do not support a native language for iOS as of today.
