### ISSUE TITLE
Using Microsoft.Rest.ClientRuntime ServiceClientTracing in multithreaded code

### ISSUE THREAD

**Issue by older** [Azure/autorest#1408]
Current implementation of `ServiceClientTracing` design requires registering tracing interceptors using static method of `ServiceClientTracing` class. So if multiple clients exist in the same app domain they all log to all registered trace interceptors and it is not possible to register trace interceptor which would be attached to one specific client.
Sometimes it could be acceptable to have one common trace interceptor for all threads but is some cases it is not possible to do. For example each WebJob instance in Azure gets its own instance of `TextWriter` for logging and it is not possible to share it between instances.

If tracing interceptor could be injected in client's constructor then it would be possible to have own log for each client instance.

**Comment by gitfool** [comment]
I also don't like this approach. (Issue #1003).

**Comment by olydis** [comment]
This is handled by the client runtime. Please reopen the issue [there](https://github.com/Azure/azure-sdk-for-net).
