### ISSUE TITLE
AutoRest.Azure does not support addition of flattened properties in the derived class.

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1409]
Let's say we have following types defined in swagger:
Model definition A
Model definition B has [All Of] Model A, plus Additional property Foo
Model definition C has flattened property set of type A
Model definition D has flattened property set of type B and [All of] Model C

**Expected:**
After generation Type D should have property Foo (Defined in B) along with all the properties from Model definition A

**Actual:**
Type D has only properties defined in Model Definition A, because during type resolution AutoRest pics flattened properties of base class C.

**Comment by fearthecowboy** [comment]
No. Maybe in vNext high-level generators. But not in classic generators.
