### ISSUE TITLE
Generated C# code cannot compile if property name starting with numbers

### ISSUE THREAD

**Issue by hongyes** [Azure/autorest#142]
The expected solution is to add underscore prefix to such property and decorate JsonProperty/DataMember attribute for real property name.

**Comment by azurecompliance4** [comment]
underscore as a prefix for public properties of a model object wouldn't follow naming guidelines. would probably just prefix with the 'type' the same way suffixes are added for model name conflicts.
123 => Property123

**Comment by hovsepm** [comment]
Thanks for catching this bug! We will fix it in the upcoming release.

**Comment by hovsepm** [comment]
Fixed in Release 0.10.0 - [nuget](https://www.nuget.org/packages/AutoRest/), [chocolatey](https://chocolatey.org/packages/AutoRest), [github] (https://github.com/Azure/autorest/releases/tag/AutoRest-0.10.0)
