### ISSUE TITLE
HttpStatusCodeErrorDetectionStrategy should NOT just retry on any server-side error >= 500

### ISSUE THREAD

**Issue by jelledruyts** [Azure/autorest#1421]
The default behavior of an autorest client is to use a retry policy with an HttpStatusCodeErrorDetectionStrategy which retries the operation on any server-side error >= 500 (InternalServerError).

This sounds like a very bad idea because HTTP 500 does NOT usually indicate a transient error at all. Retries can therefore cause side effects on operations that are not idempotent (as I've witnessed at customers).

The retry behavior like this should not be the default (opt-in instead of opt-out), and optionally the HTTP error codes should be configurable so that customers can define which they consider transient.

**Comment by ealsur** [comment]
I found this, it might help: https://github.com/Azure/autorest/blob/master/Documentation/clients-retry.md

**Comment by jeffreywstevens** [comment]
The link is dead.  I need to be able to turn off the retry.  The Retry is killing my app which has a tight SLA for responses.  500 errors included.

**Comment by olydis** [comment]
Retry logic is part of the [client runtime](https://github.com/Azure/azure-sdk-for-net). Please open an issue there.
