### ISSUE TITLE
AutoRest should be able to generate project files alongside files

### ISSUE THREAD

**Issue by tbombach** [Azure/autorest#1425]
For C#, this would be a `project.json` (with a reference to the ClientRuntime version that AutoRest knows about). For Ruby, it would be things like Rakefiles. I would like to add a new command line option called `-Project` that would instruct the generator to generate any project/build files that would be needed to work with the generated files.

Considerations:
The projects in .NET SDK repo have sections that only make sense in that repo (esp. re: signing). We could generate `project.json` files (only in the Azure version of the generators) that include these sections (so it's less work to get a library project that can be plugged into that repo). However, that project will not build unless it's in a cloned version of that repo. Alternatively, we could have documentation that instructs people to add that section and we don't create it.

The .NET SDK repo projects are all "library" projects - you wouldn't be able to write a Program.cs that runs without adding `emitEntryPoint: true` for that project. Is this an option that AutoRest would provide? Would this be a custom setting for the C# generator?

Additionally, the folders in the .NET SDK repo have a test project as well. Is that something we would want to generate too?

Since this is all going to be generator-based (e.g. the Azure generator can behave differently than the generic generator), I wouldn't see a problem with these special, Azure-focused project customizations being generated in the Azure generators.

Users should also be able to edit these project files, with subsequent executions of AutoRest preserving these changes. That means AutoRest needs to be able to read this file and modify it intelligently for settings that it knows it should change (e.g. ClientRuntime version, which should be updated in `project.json` if it's different from the version that AutoRest knows about).

**Comment by tbombach** [comment]
@begoldsm I believe this was something you were interested in using once I added the functionality. I have a PR almost ready for AutoRest that lets it generate a basic `project.json` that is similar to the ones in the .NET SDK repo. I still need to add the ability to preserve changes to that file when you run AutoRest multiple times, but I'd probably get the basic functionality checked in first and add that afterwords (since I'd want to figure out a solution for all languages).

Do you have any thoughts on how this should be used?

**Comment by fearthecowboy** [comment]
@tbombach hey where is this? I thought you were done... the new Thomas needs this :D

**Comment by tbombach** [comment]
@fearthecowboy No, for this one we decided not to do it in AutoRest yet (instead directing people to the project templates that Abhijeet created. We decided to wait and tackle updating the output files at the same time when you ran AutoRest multiple times. This is the PR I started, but abandoned: https://github.com/Azure/autorest/pull/1459

**Comment by fearthecowboy** [comment]
OK

**Comment by begoldsm** [comment]
@tbombach @fearthecowboy sorry for my late reply on this! Based on what is said here, does this need to be fully closed out? I would very much like to see something like this finished since it will enable our built languages (java, C# and to some extent ruby) be incorporated into the "Auto-generation" pipeline that we have for Node and Python (where the merging of a swagger PR automatically triggers a PR and test run with newly generated code in all the supported languages). It would be awesome to literally have a single entry point that results in all the right clients being updated. This would also drastically reduce the amount of manual PRs that need to be reviewed that are just swagger refreshes + test updates.

**Comment by fearthecowboy** [comment]
There's a lot of things that we're working towards in this regard, making it simpler to generate pretty much everything start to finish. 

This particular activity was a short-term hack that didn't work out.  That doesn't mean that we're not going to try and do it, just not in this way. At the very least it's gonna have to wait until .net ships the next version of the tools before we look into it again. 

One of the proposals that I am working on is significant per-language configuration and client generation support. That whole thing superceedes this in a big way.
