### ISSUE TITLE
Thoughts on versioning each ARM package

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1428]
In Ruby, we are still in preview for all the [azure_mgmt_*](https://rubygems.org/search?utf8=%E2%9C%93&query=azure_mgmt_) azure arm packages. Today, for the reasons on simplicity we revise & release all the packages version at the same pace (example: **_0.4.0 to 0.5.0 for all_**) but we think this wouldn't be idea case once we will reach to 1.0 of all management packages when Ruby & Azure.Ruby generator stabilizes. 

We'd like to know thoughts on following areas from each language team's & AutoRest perspective:

1. How each language team maintains & revise the versioning for each of their ARM packages?
2. Are there any common best practices / guidelines that each team is following?
3. How each language team maintains the breaking changes information (Swagger Perspective) for each ARM packages?
4. How each language team decides which version of swagger to release from when resource provider has more than one. Does the latest checked-in is always stable and accurate to ship?

Thanks,

**Comment by veronicagg** [comment]
To summarize discussions from our meeting:
1 &2. Each SDK team is currently coordinating with service teams to release their versions of packages.
3. Looking into swagger and generator changes done by each team.
4. Generally shipping latest, after confirming with service team.
