### ISSUE TITLE
[NodeJS] Response body is parsed twice

### ISSUE THREAD

**Issue by forivall** [Azure/autorest#1432]
As seen in https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.NodeJS.Tests/Expected/AcceptanceTests/BodyArray/operations/arrayModel.js#L122 and https://github.com/Azure/azure-sdk-for-node/blob/94bc69777e8e310cdb8e3a604e9e4a7f3dc31298/lib/services/graphManagement/lib/operations/applications.js#L326 , `JSON.parse(responseBody)` is called twice.

It should only be done once, especially since `JSON.parse` on large responses can often block the event loop.

**Comment by fearthecowboy** [comment]
If this is still an issue, please update and reopen.
