### ISSUE TITLE
[C#] Defining global params in formData breaks client code

### ISSUE THREAD

**Issue by svickers** [Azure/autorest#1435]
When using global params that live in form data, the client gets generated with some compilation errors.

Swagger:

```
"parameters": {
  "ApiId": {
    "in": "formData",
    "type": "string",
    "name": "API_ID",
    "required": true,
    "x-ms-client-name": "ApiId"
  }
}
```

Generated client code:

```
if (this.APIID != null){
    StringContent _this.APIID = new StringContent(this.APIID, Encoding.UTF8);
    _multiPartContent.Add(_this.APIID, "API_ID");
}
```

Note there are 2 occurrences of **_this.APIID** that should be just **_APIID,** like so:

```
if (this.APIID != null){
    StringContent _APIID = new StringContent(this.APIID, Encoding.UTF8);
    _multiPartContent.Add(_APIID, "API_ID");
}
```

**Comment by dsgouda** [comment]
Investigated this, @fearthecowboy has a fix for this in some of his refactoring changes that will be merged soon

**Comment by fearthecowboy** [comment]
@dsgouda make sure we have a test.

**Comment by dsgouda** [comment]
Fixed here https://github.com/Azure/autorest/commit/23434a2f2909381d5652045213b1270d033ffa6d
