### ISSUE TITLE
wrong url homepage on python msrest?

### ISSUE THREAD

**Issue by ardumont** [Azure/autorest#1437]
On https://github.com/Azure/autorest/blob/master/src/client/Python/msrest/setup.py#L34,
doesn't the homepage url reference be *https://github.com/Azure/autorest/blob/master/src/client/Python/msrest* instead of *https://github.com/xingwu1/autorest/tree/python/ClientRuntimes/Python/msrest*?

It's a nitpick but downstream packaging usually means referencing the homepage and if not correctly initially set means creates a multiple of bad references all other the places.

Cheers,

**Comment by annatisch** [comment]
Hah, yes, that URL is very very out of date. Will get that sorted - thanks!

**Comment by ardumont** [comment]
There is the same typo on msrestazure iirc ;)

**Comment by annatisch** [comment]
Yes I caught that, I've fixed them both :)
