### ISSUE TITLE
Generator for PowerShell?

### ISSUE THREAD

**Issue by wangzq** [Azure/autorest#1439]
Not sure if this is feasible or not but a generated PowerShell module seems useful to access the REST API?

**Comment by tbombach** [comment]
Hi @wangzq. This is something that we're interested in, but we have nothing to announce right now. I'll be sure to circle back to this issue and let you know if we have any news about a PowerShell generator

**Comment by patriksvensson** [comment]
Being able to generate a PowerShell module would be super helpful!

**Comment by olydis** [comment]
see #2452

**Comment by MiYanni** [comment]
@wangzq See https://github.com/Azure/autorest.powershell
