### ISSUE TITLE
LRO properties should be omitted in generated code unless needed

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1441]
(This applies to C#; I haven't checked if it applies to other languages too.)

Not all SDKs support long-running operations, but AutoRest includes the [LongRunningOperationRetryTimeout](https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.search.searchindexclient.longrunningoperationretrytimeout.aspx#P:Microsoft.Azure.Search.SearchIndexClient.LongRunningOperationRetryTimeout) property in the generated `ServiceClient` anyway. This is confusing to end users looking for information on how to control the client's retry behavior.

There should be a way to prevent AutoRest from generating this property when it's not needed.

**Comment by amarzavery** [comment]
Which language are you talking about?
- C#, node.js, ruby, python, java, go - support long running operations.

**Comment by brjohnstmsft** [comment]
I know for sure the issue affects C#. I haven't looked at generated code in the other languages.

**Comment by olydis** [comment]
Since the generated clients inherit from `IAzureClient`, they have to implement `LongRunningOperationRetryTimeout`.
I'd suggest implementing the property explicitly, in case there are no LROs, so at least it is somewhat hidden from end users.

**Comment by brjohnstmsft** [comment]
@olydis Or factor the interface differently, since not all clients support LRO.

**Comment by olydis** [comment]
[IAzureClient](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/IAzureClient.cs) is part of the Azure client runtime, which is now owned by [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) and not AutoRest

Your proposal would require generating a custom client runtime, which is something we'll think about in the 2.0 time frame. Until then, the Azure client runtime is considered unchangeable ;-)

**Comment by brjohnstmsft** [comment]
@olydis As long as that is an explicit decision to ease package versioning pain for customers at the cost of a slightly awkward interface. I'm ok with that tradeoff. :-)

**Comment by fearthecowboy** [comment]
Adding to vNext generator/client runtime feature list.
