### ISSUE TITLE
[C#] Generated ServiceClient does not set HttpClient.Timeout

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1445]
Pre-AutoRest Azure SDKs (generated using Hyak) set `HttpClient.Timeout` to 300 seconds in the generated `ServiceClient`-derived class constructors. In AutoRest-generated code it is left unset, resulting in the lower default of 100 seconds. This is causing some customers to experience premature timeouts on very long-running operations that would have otherwise succeeded. (One might argue that such operations should be modeled as LROs, but I'm talking about data plane operations here where the vast majority of requests are completed in less than a second.)

Generated ServiceClient-derived classes should restore the old default timeout of 300 seconds (the workaround is for code using the client to explicitly set `HttpClient.Timeout`).

**Comment by fearthecowboy** [comment]
Adding to the vNext design (should get this along with the stuff storage is doing)
