### ISSUE TITLE
x-ms-enum extension always hides enum with a single value

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#1449]
In my service we have an API something like this:
`ApplicationPackage_Activate` which has a parameter like this:

```
        "format": {
          "type": "string",
          "description": "The format of the application package binary file.",
          "enum": [
            "zip"
          ],
          "x-ms-enum": {
            "name": "ApplicationPackageFormat",
            "modelAsString": false
          }
        }
```

Our service API only supports a single value today -- but we know in the future we will support more formats (that's why we bothered to expose this property at all, if we thought it wasn't going to change we would've just not exposed an enum in the REST API at all).

Yet, in AutoRest, an enum with a single value is not allowed. See `ObjectBuilder.cs`, specifically:

```
        private static bool IsSwaggerObjectConstant(SwaggerObject swaggerObject)
        {
            return (swaggerObject.Enum != null && swaggerObject.Enum.Count == 1 && swaggerObject.IsRequired);
        }
```

I see multiple good reasons to _not_ hide the Enum even if it only has a single value:
1. It conveys meaning. Compare `ApplicationPackage.Activate(foo, bar, baz, qux, PackageFormat.Zip)` to `ApplicationPackage.Activate(foo, bar, baz, qux)`. Yes, the second has 1 fewer argument, which is nice, but it also loses the extremely clear meaning that the package must be of the `Zip` format. We would be forced to document the limitation that only `Zip` is supported now in the description -- which feels like we're duplicating that information because we already said only `Zip` is supported _in the Swagger specification when we defined the enum_.
2. It protects us from future breaking changes (which is the whole reason we bothered to include the option in the REST API at all). It seems awkward that AutoRest forces our hand here -- we might as well not have included the enum in the REST API.

It would be nice if AutoRest allowed us to either opt-in or opt-out of this behavior, maybe with a flag on `x-ms-enum` called `squash-single-value-enums` or something?

**Comment by matthchr** [comment]
@tbombach @fearthecowboy What are your thoughts?

**Comment by fearthecowboy** [comment]
That's a really good question. Half of me agrees completely. 

The other half wonders why this restriction is there in the first place, and that there is a 'best practice' in place.

 @amarzavery  would certainly know why this is a "best practice"

While one could argue that you might as well suppress the parameter until you actually have a second value, that would certainly be a breaking change later. Whereas, adding a second enum value wouldn't be as much of a breaking change.

**Comment by amarzavery** [comment]
Yes. We had an internal discussion about this before implementing this behavior.

Giving context on the discussion that happened and how we are here today w.r.t enums. 
- **Adding a new value to the enum is also considered to be a breaking change**. (Example: Someone can write a switch statement based on the enum values and adding a new value could break them).
- When the **property is required and enum has 1 value**, then **currently** it is treated as a **constant**. When the second value is added to the enum then it is no longer a constant, but an enum or a static class with constant properties based on the boolean value provided for "modelAsString" property in the x-ms-enum extension. 

So, does the **method of breaking change** (constant -> enum **v/s** enum with 1 value to 2 value) matter in that case?

> Note: I agree that in the second case the method API remains the same.


We can modify this hard (written in stone) rule and make this more flexible by  giving the author of the spec more control:
- Enum with one value and the property/parameter is required
   -  **Treated as a constant** - `"x-ms-enum":  { "name": "MyEnum", "modelAsString": true" }` // You don't want this to be an enum anyways.
  - **Treated as an enum** - `"x-ms-enum":  { "name": "MyEnum", "modelAsString": false" }`

What do you think about it?

**Comment by matthchr** [comment]
@amarzavery Can you point me to where we (msft -- or anybody) says that adding a value to an `enum` is a breaking change? I tried to find somewhere that said that with respect to semver and couldn't -- I only saw an example about reordering enum integer values (i.e. `Foo.A = 1` becomes `Foo.A = 2`).

Certainly, somebody could be broken if they wrote their code in such a way that they were not resilient to enum's being added (i.e. they have no `default` case). But they could've also written their code in such a way that they are dependent on the number of methods on a class (using reflection for example).

Does that make adding a new method a breaking change? (I could certainly craft code which would break if a new method was added) -- I think the answer is no... yet there seems to me to be an isomorphism between that case and the enum case since both correctly work against the current structure defined in the API (this `enum` has 6 values and works, this class has 6 methods and works) and both break when the structure changes under them.

Moreover, is the `enum` thing a hard and fast rule? What about if the `enum` is only ever used as input and never returned from the service? Then certainly that cannot be a breaking change right?

**Comment by fearthecowboy** [comment]
Adding this as a feature consideration for vNext generators. (see #2448)

**Comment by matthchr** [comment]
@fearthecowboy Has there been any movement on this...? I see that it's in the list of considerations for the future... we just got dinged by it again though. Is there any ETA on a fix, opt in flag, etc?

**Comment by amarzavery** [comment]
https://github.com/Azure/autorest/pull/2594
