### ISSUE TITLE
OutOfMemoryException when doing a HEAD request against a large payload

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#1456]
This is directly related to #769 which we fixed some time back. The problem is that while we fixed it for streaming large payloads, we missed the fact that `HEAD` requests can run into the exact same problem.

Since `HEAD` requests by their definition only have headers, we should always use `HttpCompletionOption.ResponseHeadersRead` for reading their response.

We should do two things:
1. Extend the tests which were added as part of #769 to include HEAD requests as well
2. Fix the issue in C# and whatever other languages the problem crops up in

**Comment by matthchr** [comment]
@tbombach @fearthecowboy this is a customer impacting issue for us which ideally we could fix ASAP so we can regenerate our client and unblock our customer. Will you be able to make a fix quickly or does somebody on my team need to contribute the fix?

**Comment by fearthecowboy** [comment]
(looking at #769...)

**Comment by fearthecowboy** [comment]
The fix looks pretty trivial, but I am curious why `HEAD` requests even have this problem... shouldn't they complete as soon as the headers are read anyway? Why is it waiting longer? There isn't a body, right?

**Comment by fearthecowboy** [comment]
@matthchr  are you actually getting an OOM exception on the HEAD request, or is it just stalling?
or throwing something else?

**Comment by fearthecowboy** [comment]
Should be in the nightly tonight @matthchr

**Comment by matthchr** [comment]
@fearthecowboy Nice, thanks for the fast response!

**Comment by matthchr** [comment]
Updating this -- other than a related issue which I filed [here](https://github.com/Azure/azure-sdk-for-net/issues/2403) this seems to be fixed.

Probably can leave this open for some tests to be added in AutoRest itself, but I've confirmed that the fix works for me.
