### ISSUE TITLE
AutoRest should support (or ignore) `additionalProperties: false` in a schema

### ISSUE THREAD

**Issue by tbombach** [Azure/autorest#1458]
In JSON schema, `additionalProperties` can be a boolean or an object, describing a schema (see https://github.com/json-schema/json-schema/wiki/Additionalproperties).

Currently, AutoRest expects only the object format and will throw if `additionalProperties` is a boolean. This is because the deserialization model expects only a schema: https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Model/SwaggerObject.cs#L59

This can be solved via a custom JSON converter (like these https://github.com/Azure/autorest/tree/master/src/modeler/AutoRest.Swagger/JsonConverters) that gets registered in SwaggerParser (https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/SwaggerParser.cs#L42)

**Comment by fearthecowboy** [comment]
Adding to the list of vNext Generator support (definitely need to support round-tripping of unknown data)  -- more importantly the ability to turn that off.
