### ISSUE TITLE
Python msrestazure: LRO doesn't deserialize 'target' and 'details' fields on error

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/autorest#1460]
C# and node versions both handle it. The consequence of not doing it is the error surfaced is too vague 
Azure/azure-cli#1007
For reference, the C# version is here: 
https://github.com/Azure/autorest/blob/master/src/client/Microsoft.Rest.ClientRuntime.Azure/CloudError.cs#L34-L39

**Comment by annatisch** [comment]
Hi @yugangw-msft, are you able to confirm whether the response body returned by the webapp API conforms to the standard CloudError?
For example, I see that the C# implementation has Details as a list of CloudError objects, where as in the response Details has a list of key value pairs, only one of which is an "errorEntity".

**Comment by yugangw-msft** [comment]
`webapp API` does `not` conform to the standard CloudError. So you don't need to special case for webapp api, rather just get de-serialization logic in parity with C# and [node](https://github.com/Azure/autorest/blob/master/src/client/NodeJS/ms-rest-azure/lib/cloudError.js#L89)

I am chatting with webapp team to see whether their service can fix the error body

**Comment by annatisch** [comment]
Thanks @yugangw-msft,
I think I've made some progress with this - one question - I notice that in the error response from webapp API in the CLI issue, all the fields are capitalized ("Code", "Message", etc).
Currently the CloudError deserialization in Python only looks for lower case fields. It appears from the node implementation that it may do so as well. 
So - do you know if this should be completely case insensitive, or is this another formatting issue specific to the webapp API error response?

**Comment by yugangw-msft** [comment]
It should be lower case always, so webapp, again, goes against the guideline :(. @naveedaz

**Comment by lmazuel** [comment]
Fixed here: https://github.com/Azure/autorest/pull/1510

Release soon

**Comment by lmazuel** [comment]
Released in msrestazure 0.4.4
