### ISSUE TITLE
[C#] AutoRest generated SDK does not expose HttpClient

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1461]
AutoRest generated SDK does not expose HttpClient. The HttpClient can be used for different purpose including setting the timeout on connection.

**Comment by fearthecowboy** [comment]
The `HttpClient` is a property in `ServiceClient<T> ` which is the base for all the generated service client classes...

**Comment by older** [comment]
Should this be closed? Works like this for me:
```csharp
var client = new GeneratedClient(baseUri, credentials);
client.HttpClient.Timeout = TimeSpan.FromSeconds(90);
```

**Comment by pomortaz** [comment]
Thanks. Yes we can close this.

**Comment by pomortaz** [comment]
@older do you know how to avoid the client to disconnect a TCP connection after few seconds of idle time?

**Comment by votrubac** [comment]
Does not work in the latest configuration:
'@microsoft.azure/autorest.csharp' (~2.2.45)
'@microsoft.azure/autorest.modeler' (2.3.42)
