### ISSUE TITLE
Include http request message inside of TaskCancelledExceptions

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1462]
AutoRest generated clients should inject the `Request` object into task cancelled exceptions to allow for better debugging of the reasons why the exception was thrown. This is especially true when there is a server problem that is resulting in a normally fast operation taking long enough to result in a `ClientTimeout` triggering a cancellation.
Based on a conversation with @tbombach:

Any info about the request is lost in that case where someone catches a `TaskCancelledException` (I think that exception is thrown from a different level than the `HttpClient` level, so it doesn't preserve any web-related context info). I'm imagining that we would catch `TaskCancelledException` in generated code (which gets thrown both on a timeout and if the user cancels with a cancellation token), add the `Request` object to the `exception.Data`, then rethrow it. That way any request headers, etc. would be available (especially important for headers we add in the method like `x-ms-client-request-id`)

**Comment by fearthecowboy** [comment]
Tricky part, is that the `HttpRequest` is `IDisposable` -- and `TaskCanceledException` isn't `IDisposable` so the `.Data` property won't get disposed... in either event, the catcher of the Exception would have to know that they should dispose of the exception (or the `.Data` property) ,either of which is not really common practice.

**Comment by begoldsm** [comment]
How do we handle this today for things like `CloudException` which contain all of this information? If we can't inject it into the traditional `TaskCanceledException` does it make sense to introduce a new exception type called `CloudTaskCanceledException` that behaves almost identically to a `CloudException` but is specific to the cancellation scenario?

**Comment by fearthecowboy** [comment]
I think they have some wrapper classes that copy over some of the data so they don't have to keep the request/response objects around.

**Comment by fearthecowboy** [comment]
Adding this as a feature consideration for vNext generators and client runtimes. (see #2448)
