### ISSUE TITLE
NoProduceOperationWithBody

### ISSUE THREAD

**Issue by Serjster** [Azure/autorest#1465]
I am getting the NoProduceOperationWithBody: WARNING: Method 'GetByID' does not declare any MIME type for the return body. Generated code will not deserialize the content.

What can I do to prevent this warning?

**Comment by amarzavery** [comment]
Do you have a produces array defined globally in the swagger spec or one defined for the operation "GetByID"? If not then please define one.
```
"produces": ["application/json", "text/json"],
"consumes": ["application/json", "text/json"]
```

**Comment by Serjster** [comment]
So Do I need both of these?
[SwaggerResponse(HttpStatusCode.OK, Type = typeof(TestComplex))]
[Produces(typeof(TestComplex))]

**Comment by Serjster** [comment]
At the top of my controller, I have:

`[Produces("application/json")]`

**Comment by amarzavery** [comment]
Can you provide your swagger spec?

**Comment by Serjster** [comment]
This?
`{
"swagger": "2.0",
"info": {
"version": "v1",
"title": "TestAPI",
"description": "A simple ASP.NET Core RTM Test API",
"termsOfService": "None"
},
"basePath": "/",
"paths": {
"/api/TestComplex/v1/GetAll": {
"get": {
"tags": [
"TestComplex"
],
"operationId": "GetAll",
"consumes": [],
"produces": [],
"responses": {
"200": {
"description": "OK",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/TestComplex"
}
}
},
"204": {
"description": "No Content"
}
},
"deprecated": false
}
},
"/api/TestComplex/v1/GetByID/{id}": {
"get": {
"tags": [
"TestComplex"
],
"operationId": "GetByID",
"consumes": [],
"produces": [],
"parameters": [
{
"name": "id",
"in": "path",
"required": true,
"type": "integer",
"format": "int32"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/TestComplex"
}
},
"204": {
"description": "No Content"
}
},
"deprecated": false
}
},
"/api/TestComplex/v1/GetByManyThings/{id}/{typeID}/{from}/{to}": {
"get": {
"tags": [
"TestComplex"
],
"operationId": "GetByManyThings",
"consumes": [],
"produces": [],
"parameters": [
{
"name": "id",
"in": "path",
"required": true,
"type": "integer",
"format": "int32"
},
{
"name": "typeID",
"in": "path",
"required": true,
"type": "integer",
"format": "int64"
},
{
"name": "from",
"in": "path",
"required": true,
"type": "string",
"format": "date-time"
},
{
"name": "to",
"in": "path",
"required": true,
"type": "string",
"format": "date-time"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/TestComplex"
}
},
"204": {
"description": "No Content"
}
},
"deprecated": false
}
},
"/api/TestComplex/v1/GetByManyThingsNullable/{id}/{typeID}/{from}/{to}/{userID}": {
"get": {
"tags": [
"TestComplex"
],
"operationId": "GetByManyThingsNullable",
"consumes": [],
"produces": [],
"parameters": [
{
"name": "id",
"in": "path",
"required": true,
"type": "integer",
"format": "int32"
},
{
"name": "typeID",
"in": "path",
"required": true,
"type": "integer",
"format": "int64"
},
{
"name": "from",
"in": "path",
"required": true,
"type": "string",
"format": "date-time"
},
{
"name": "to",
"in": "path",
"required": true,
"type": "string",
"format": "date-time"
},
{
"name": "userID",
"in": "path",
"required": true,
"type": "integer",
"format": "int64"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/TestComplex"
}
},
"204": {
"description": "No Content"
}
},
"deprecated": false
}
},
"/api/TestComplex/v1/Post": {
"post": {
"tags": [
"TestComplex"
],
"operationId": "Post",
"consumes": [
"application/json",
"text/json",
"application/json-patch+json"
],
"produces": [],
"parameters": [
{
"name": "complex",
"in": "body",
"required": false,
"schema": {
"$ref": "#/definitions/TestComplex"
}
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/TestComplex"
}
},
"204": {
"description": "No Content"
}
},
"deprecated": false
}
}
},
"definitions": {
"TestComplex": {
"type": "object",
"properties": {
"id": {
"format": "int64",
"type": "integer"
},
"names": {
"type": "array",
"items": {
"type": "string"
}
}
}
}
},
"securityDefinitions": {}
}`

**Comment by amarzavery** [comment]
Example for top level produces/consumes - https://github.com/Azure/autorest/blob/master/Samples/azure-storage/azure-storage.json#L12

**Comment by Serjster** [comment]
This is the top of my ASP.NET Core Web API:
`[Route("api/[controller]/v1/[action]")]
    [Produces("application/json")]
    [Consumes("application/json")]
    public class TestComplexController : Controller`

**Comment by amarzavery** [comment]
As you can see, the produces and consumes for every operation are empty. They should have the correct values. You can define them globally (default) and if the specific operation supports additional content-type values then you can define define them in that operation .


Autorest currently supports json, octet-stream and multipart-formadata.

**Comment by amarzavery** [comment]
You can take a look at this [sample repo](https://github.com/Azure/swashbuckle-resource-provider) that shows how to configure swashbuckle with WebAPI.

**Comment by Serjster** [comment]
Thanks, but that example is for the old Web API not ASP.NET Core... all of that is different now...

**Comment by Serjster** [comment]
Ok, it seems like the new `Attribute` to use in ASP.NET Core is `ProducesResponseType`

```c#
        [HttpGet("{id}/{typeID}/{from}/{to}")]
        [ProducesResponseType(typeof(IEnumerable<TestComplex>), (int)HttpStatusCode.OK)]
        public IActionResult GetByManyThingsNullable(int id, long typeID, DateTime from, DateTime to, [FromQuery]long? userID = null)
        {
            return Ok(new TestComplex() { Id = id });
        }
```

**Comment by amarzavery** [comment]
@yaqiyang - Can you please update the swashbuckle sample in [this repo](https://github.com/Azure/swashbuckle-resource-provider) with ASP.NET Core ?
