### ISSUE TITLE
NodeJS ms-rest package - incomplete typescript definition for ServiceClientCredentials

### ISSUE THREAD

**Issue by christav** [Azure/autorest#1468]
At https://github.com/Azure/autorest/blob/master/src/client/NodeJS/ms-rest/lib/index.d.ts#L222, ServiceClientCredentials is defined as:

``` typescript
// TODO: Finish this;  expose signRequest?
export class ServiceClientCredentials {
}
```

Note the TODO. :-)

A reasonable definition based on the code would be:

``` typescript
export interface ServiceClientCredentials {
    signRequest: { (webResource: WebResource, callback:{(err: Error): void } ) : void };
}
```

The different between class and interface are immaterial in this context, we just need to know what the required method is.

**Comment by amarzavery** [comment]
@christav - the new version of ms-rest "1.1.5.1" has this.

**Comment by olydis** [comment]
it sounds like this issue is solved, the mentioned version is also ancient by now. Hence I'll close, feel free to reopen if I'm mistaken.

**Comment by christav** [comment]
Just double checked, and yes, this is fixed.

**Comment by olydis** [comment]
awesome, thanks for confirming!
