### ISSUE TITLE
Bug in error handling for response status code when calling REST API.

### ISSUE THREAD

**Issue by robertwood62** [Azure/autorest#1469]
I've been staring at the code below... I think the check for the statusCode logic is backwards.  I think it should be...

if((int)_statucDoce == 400 || (int)_statusCode == 500)

Here is the original code...

            HttpStatusCode _statusCode = _httpResponse.StatusCode;
            cancellationToken.ThrowIfCancellationRequested();
            string _responseContent = null;
            if ((int)_statusCode != 400 && (int)_statusCode != 500)
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                ex.Request = new HttpRequestMessageWrapper(_httpRequest, _requestContent);
                ex.Response = new HttpResponseMessageWrapper(_httpResponse, _responseContent);
                if (_shouldTrace)
                {
                    ServiceClientTracing.Error(_invocationId, ex);
                }
                _httpRequest.Dispose();
                if (_httpResponse != null)
                {
                    _httpResponse.Dispose();
                }
                throw ex;
            }

**Comment by fearthecowboy** [comment]
Can you post the swagger for the code that generated this? Did you include just a couple responses for `400` and `500` error codes?

The code there looks to be handling cases that aren't covered elsewhere.

**Comment by fearthecowboy** [comment]
@robertwood62 Is this still an issue?

**Comment by robertwood62** [comment]
Nope.  Someone on my team move the repository and we just had to update our URL reference to fix the issue.
