### ISSUE TITLE
Package name trimming sometimes trims more than needed

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1477]
As explained by @garimakhulbe ...

> We remove package name from type names to avoid stuttering type golint error.
> For example, if there is a swagger for API ABC and it has type ABCAccount, then to use this type in go `ABC.ABCAccount` which gives golint error. To avoid this, we trim the package name in typenames. `ABCAccount` -> `Account`.
> In this case, `tate`..
> package: `subscriptions`
> Enum type: `SubscriptionState` -> after trimming subscriptions, it becomes `tate`.

This shows when trying to generate SDK with [subscriptions](https://github.com/Azure/azure-rest-api-specs/blob/77764435a004d6cc1102edd64a3e44c27fb0bad5/arm-resources/subscriptions/2016-06-01/swagger/subscriptions.json) swagger.

**Comment by garimakhulbe** [comment]
This is a different case.

Package name is `Subscriptions`.
Enumtype name coming from modular is `SubscriptionState -> tate ( generator removing the package name which is correct)`. 

Stuttering type code is working fine here. We need to check why `state` in swagger became `SubscriptionState` in generator. I think `state -> `SubscriptionState` change happened in modular not in generator.

**Comment by jhendrixMSFT** [comment]
The name is changed to "SubscriptionState" because that's how it's specified in the swagger.
```
        "state": {
          "readOnly": true,
          "type": "string",
          "description": "The subscription state. Possible values are Enabled, Warned, PastDue, Disabled, and Deleted.",
          "enum": [
            "Enabled",
            "Warned",
            "PastDue",
            "Disabled",
            "Deleted"
          ],
          "x-ms-enum": {
            "name": "SubscriptionState",
            "modelAsString": false
          }
        }
```
Is it typical for property name to be different than what's specified in the name (as part of the x-ms-enum attribute)?

**Comment by jhendrixMSFT** [comment]
I added a change to package name trimming to not trim across casing boundaries, see change https://github.com/Azure/autorest/commit/3f91c30390f91098517785aba573a6d6d5608a0f.
