### ISSUE TITLE
[Python.Azure] CloudError failed to get error message from response.

### ISSUE THREAD

**Issue by haocs** [Azure/autorest#1500]
`CloudError` class in msrestazure retrieves error message from raw server response by calling [_build_error_message()](https://github.com/Azure/autorest/blob/master/src/client/Python/msrestazure/msrestazure/azure_exceptions.py#L156)

It won't work if "message" attribute starts with `M`(dict.get() is case sensitive in python). I run into this issue when I made `insights` requests. And the raw response from server is 

```
'{"Code":"ResourceNotSupported","Message":"Resource provider not supported: microsoft.web"}'
```

However, error message from CloudError is 

```
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/***/resourceGroups/***/providers/Microsoft.Web/sites/***
```

**Comment by fearthecowboy** [comment]
@lmazuel Any ideas?

**Comment by olydis** [comment]
@lmazuel -- is this still an issue?
If so, please reopen.

**Comment by lmazuel** [comment]
@olydis I honestly don't know, let's keep this close and see if someone complains :p
