### ISSUE TITLE
[Microsoft.Rest.ClientRuntime] argument null exception for each request

### ISSUE THREAD

**Issue by JanEggers** [Azure/autorest#1506]
hi

i generated a api client with autorest. In the visual studio diagnostic tools i get an argument null exception for each request i send. the exception is catched somewhere internally but i dont know why it is thrown.

here is the stack:

Exception	Exception caught: 'System.ArgumentNullException' in System.Net.Http.dll ("SafeHandle cannot be null.")	System.ArgumentNullException
System.Net.Http.dll!<StartRequest>d__101.MoveNext()C#
System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run([An error occurred while fetching the data for this event])	C#
System.Private.CoreLib.ni.dll!MoveNextRunner.RunWithDefaultContext()	C#
System.Private.CoreLib.ni.dll!<>c__DisplayClass4_0.AnonymousMethod()	C#
System.Private.CoreLib.ni.dll!<>c__DisplayClass11_0.AnonymousMethod()	C#
System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()	C#
System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	C#

am i doing something wrong or is this an issue with the client runtime?

**Comment by fearthecowboy** [comment]
Good Question... 
We moved the Client Runtime code over to the https://github.com/azure/azure-sdk-for-net project ... could I get you to file this over there?

**Comment by JanEggers** [comment]
sure

**Comment by fearthecowboy** [comment]
Yes, the purge is coming; is already a PR in for that.
