### ISSUE TITLE
Regresson in property flattening.

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1508]
this is my model definitions:

```
"CheckNameAvailabilityInput": {
      "description": "Input of CheckNameAvailability API.",
      "type": "object",
      "required": [
        "name",
        "type"
      ],
      "properties": {
        "name": {
          "description": "The resource name to validate.",
          "type": "string"
        },
        "type": {
          "description": "The type of the resource whose name is to be validated.",
          "$ref": "#/definitions/ResourceType"
        }
      }
    },
    "ResourceType": {
      "description": "Type of CDN resource used in CheckNameAvailability.",
      "enum": [
        "Microsoft.Cdn/Profiles/Endpoints"
      ],
      "type": "string",
      "x-ms-enum": {
        "name": "ResourceType",
        "modelAsString": false
      }
    },
```

Both Azure.CSharp and Azure.NodeJS generate code that does not allow me to set Resource type. Basically generated methods does not have that parameter. C# Example:

```
 public async Task<AzureOperationResponse<CheckNameAvailabilityOutput>> CheckNameAvailabilityWithHttpMessagesAsync(string name, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
        {
...
            CheckNameAvailabilityInput checkNameAvailabilityInput = new CheckNameAvailabilityInput();
            if (name != null)
            {
                checkNameAvailabilityInput.Name = name;
            }
...
```

How am I supposed to set type value on the wire?
Changing enum to constant strings in "ResourceType" does not help either. The generated method just does not have the "type" parameter. 

Full Swagger: https://raw.githubusercontent.com/hovsepm/azure-rest-api-specs/master/arm-cdn/2016-10-02/swagger/cdn.json 

this works fine in AutoRest version v17-20160601

**Comment by olydis** [comment]
This is due to `ResourceType` being an enum with only one value. AutoRest treats those as constants, i.e. doesn't give you a choice since there is none.
This behavior is indeed controversial: https://github.com/Azure/autorest/issues/1449#issuecomment-249265708

**Comment by olydis** [comment]
@hovsepm Will close as this is by-(bad-)design.
