### ISSUE TITLE
memory leak in genrated code in case of exceptions / cancellation

### ISSUE THREAD

**Issue by JanEggers** [Azure/autorest#1524]
hi 

i had a memory profiler session because i see a steady grow in memory usage in my client app.

It uses autorest generated api as client.

it turns out that i have a webrequest leak in case of json deserializing exceptions or cancellation of the webrequest.

Why doesnt the generated code use using statements for requests and responses?

![10_100_2_102-20161020-135748](https://cloud.githubusercontent.com/assets/6747376/19558948/69d79eb0-96cd-11e6-99ab-f7733d1050b3.png)

**Comment by fearthecowboy** [comment]
The generated code does contain `using` statements as does the ClientRuntime, but in some cases the creation (or longevity) of the `IDisposable` objects are not limited to the calling scope, so are not always able to be automatically handled with `using` statements.

It's certainly possible that there are some `IDisposable` objects that have not been accounted for; do you have a specific scenario that I could duplicate to track this down?

**Comment by JanEggers** [comment]
i did not create a repro yet but i guess it has some relation to timeouts in httpclient. the webrequests all have m_aborted = 1 but i dont use cancellationtokens.

**Comment by JanEggers** [comment]
i fixed the issue by disposing the http client used by the api.

in my opinion the http client should be disposed if the api creates it, when passing in a http client via constructor the current behavior is ok.
