### ISSUE TITLE
Linter complains that description is not present there is a summary defined

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1526]
we say to partners that summary and description are the same thing and we ask them to add any of those, but Linter always complain that description is not present. Moreover MSDN documentation is generated from description fields. We should define one standard both in Linter and CR feedbacks.

**Comment by vishrutshah** [comment]
@hovsepm few questions: 

1. How does SDKs leverage summary and description?
2. Do you know how does doc team leverages summary and description?
3. I believe description is required for SDKs but does that allow them to skip description and provide summary only? 
4. I think we should flag on missing description and but also flag when description and summary are the same like #1826

**Comment by vishrutshah** [comment]
**Q**: What is out take on "Description" V/s "Summary" section in the swagger. I chatted with hovsep and found out that "Initially we were encouraging teams to write either or" If we bring in the rule on description that'd cause lot of Errors in old swagger those have only summary. What is out view on this one?

`summary` looks to be a field only applicable to `operations` from http://swagger.io/specification. Let's figure out how we're using summaries and for now, have our linter rules all based on description. The rule is a warning anyway, so if someone is missing descriptions, the warning would still apply

**Comment by vishrutshah** [comment]
I'm removing this bug fix from the current milestone, as some investigation requires before action item:

- [ ] How `summary` is leveraged by doc team?
- [ ] What are valid places for `summary` in swagger 2.0?
- [ ] How `summary` is leveraged by each SDK team?

we'll address it later.

**Comment by vishrutshah** [comment]
Here is the logic documentation team is using to determine how to use "summary" or "description":

```
What we do is this
 
    if (child.description === null || child.description == child.summary)
    {
      child.description=null;
    }
 
So, if the description is === to the summary, we clear it out
 
When creating the model, then in the actual output template
 
    <h2 id="{{anchor}}" data-uid="{{uid}}">{{operationName}}</h2>
    {{#summary}}{{{summary}}}{{/summary}}
    {{#description}}{{{description}}}{{/description}}
 
 
Which means … 
 
if there is a summary, output it
if there is a description, output it
 
 
So, assuming both the description and the summary are filled out, and they are not the same, then we will output them both onto the page
 
If only description or summary are filled out, we’ll only output one of them.
 
If neither is filled out, we will output nothing below the h2

```

**Comment by vishrutshah** [comment]
Specifically, .NET sdk leverages description and summary as below:

1. If operation has both "summary" and "description" then use "summary" in the `///<summary></summary>` section and use "description" in the `///<remarks></remarks>` section.
2. If operation only has "description" then use "description" in the `///<summary></summary>` and `///<remarks></remarks>` section both.
3. If operation only has "summary" the use "summary" in the `///<summary></summary>` section and `///<remarks></remarks>` section would be empty.

Logic snippet:
```
if (!string.IsNullOrWhiteSpace(Model.Description) || !string.IsNullOrWhiteSpace(Model.Summary))
{
@:/// <summary>
@:@WrapComment("/// ", String.IsNullOrEmpty(Model.Summary) ? Model.Description.EscapeXmlComment() : Model.Summary.EscapeXmlComment())
if (!string.IsNullOrWhiteSpace(Model.ExternalDocsUrl))
{
@:/// <see href="@Model.ExternalDocsUrl" />
}
@:/// </summary>
}
if (!String.IsNullOrEmpty(Model.Description) && !String.IsNullOrEmpty(Model.Summary))
{
@:/// <remarks>
@:@WrapComment("/// ", Model.Description.EscapeXmlComment())
@:/// </remarks>
}
```

Reference: https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.CSharp.Azure/Templates/AzureMethodTemplate.cshtml

**Comment by matthchr** [comment]
I can probably help some here since I implemented the current behavior I think.

On operations, we follow the Swagger specification which states:
>Summary: A short summary of what the operation does. For maximum readability in the swagger-ui, this field SHOULD be less than 120 characters.
>Description: A verbose explanation of the operation behavior. GFM syntax can be used for rich text representation.

On models, we follow the [JSON schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1) which says:
>Both of these keywords can be used to decorate a user interface with information about the data produced by this user interface. A title will preferrably be short, whereas a description will provide explanation about the purpose of the instance described by this schema.

In the corresponding languages, `summary` or `title` becomes the "short form comment" (i.e. C# `<summary>`, or the first line of a python `"""` comment) and `description` becomes the "long form comment" (i.e. C# `<remarks>` or the following paragraph of a python `"""` comment).

For backwards compatibility purposes, if there is no `summary`/`title`, then `description` is treated as that field (so that we never end up in a situation where we have a long form comment but no short form comment).

IMO, the linter rule should suggest people fill out `title`/`summary` as appropriate (all code should have _at least_ short form comments) and `description` optionally if their operation/property requires it.

**Comment by sarangan12** [comment]
Sent an email to Brady Gaster and waiting for his response. Will update the issue once I get more details

**Comment by sarangan12** [comment]
Task Completed
