### ISSUE TITLE
Support text/plain media type if strings are sent over the wire

### ISSUE THREAD

**Issue by HowardvanRooijen** [Azure/autorest#1527]
I have a WebApi method, decorated with Swashbuckle:

`[SwaggerResponse(HttpStatusCode.OK, Type = typeof(string))]`

Which returns plain text as a response:

`return new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent(text, Encoding.UTF8, "text/plain") };`

AutoRest code generates the following C# client code:

```
_responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
try
{
    _result.Body = Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject<string>(_responseContent, this.Client.DeserializationSettings);
}
```

Which throws an exception ("Unexpected character encountered while parsing value: A. Path '', line 1, position 1.") on the line:

`_result.Body = Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject<string>(_responseContent, this.Client.DeserializationSettings);`

Should the generated code just return the string?

**Comment by tbombach** [comment]
Hi @HowardvanRooijen. It's a little difficult to diagnose this - our team doesn't have a lot of Swashbuckle knowledge, since we work on Swagger files directly. Could you post the Swagger file that Swashbuckle creates for your api (or at least the relevant operation and response for it)?

**Comment by HowardvanRooijen** [comment]
Hi @tbombach - thanks so much for replying. The swagger endpoint is public and you can find it here: https://marain.io/swagger/docs/v1 
The operationId is Text_GetTextExtractionResponse and it's the 200 response code, that returns a string that causes a problem.
Many thanks!

**Comment by tbombach** [comment]
I think the issue here is that your Web API method isn't serializing your response as JSON. The produces section of your operation doesn't list text/plain as a MIME type that the operation returns, though your Content is serialized as text/plain.

AutoRest is only focused on JSON right now, so we mostly don't have support for handling other MIME types besides application/json (AutoRest will just ignore other types and assume that the response is JSON data). The DeserializeObject call is likely expecting either a `{` or `"` character to start the content, not the first character of your string.

**Comment by fearthecowboy** [comment]
Streams could also be used to avoid generating a method for this. 

Plugging in support for other media types is going into v.Next generators.

**Comment by fearthecowboy** [comment]
@electricessence  - are you saying that your swagger states a `"produces": [ "text/json"]` and it's not deserializing the json response body correctly?

Or is the body not JSON at all?  

Can you give me an example of the swagger and response body data?

If your body is plain text, and you want to do something different with it, then you probably want to make sure the `"produces": [ "text/plain"]` and then set the body type to `type: string` and `format: file`

**Comment by eosfor** [comment]
Hi @fearthecowboy

> If your body is plain text, and you want to do something different with it, then you probably want to make sure the `"produces": [ "text/plain"]` and then set the body type to `type: string` and `format: file`

May I ask you to elaborate a bit more on this. I mean, i see that the service i'm trying to use returns just a plain strings. 

The thing is that othe penAPI spec service provides is kind of not complete. So I'm trying to fix the spec and generate the code based on it. and as part of response body they return a plain text strings, as messages. So what do I put to the spec for autorest to be able to pick those stings as they are and use them?
