### ISSUE TITLE
Go generator ignores global parameter location

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1532]
Go generator ignores `x-ms-parameter-location`, so parameters like [resource group](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-cdn/2016-10-02/swagger/cdn.json#L2211) are added as client attributes in the SDK.
This parameters should be present in the method signature, not in the cl;ient.

**Comment by jhendrixMSFT** [comment]
This was fixed in the legacy branch in change https://github.com/Azure/autorest/commit/3f91c30390f91098517785aba573a6d6d5608a0f.  I have merged it into my refactoring work.
