### ISSUE TITLE
System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by markiiantsymbalista** [Azure/autorest#1537]
I've generated client for my api using AutoRest on docker image. 
When I use it, on step:

 _httpResponse = await this.HttpClient.SendAsync(_httpRequest, cancellationToken).ConfigureAwait(false);

it throws exception. Here is stack trace:

{System.ObjectDisposedException: Cannot access a closed Stream.\n at System.IO.__Error.StreamIsClosed()\n at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)\n at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)\n at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n at HomeAssistant.IdentityAndAccessManagement.Services.HomeAssitantNotificationsApi.<ApiMailingPostWithHttpMessagesAsync>d__26.MoveNext() in /Users/markiian-tsymbalista/Documents/Projects/identity_and_access_management_api/src/HomeAssistant.IdentityAndAccessManagement.Services/HomeAssitantNotificationsApi.cs:line 344\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n at HomeAssistant.IdentityAndAccessManagement.Services.HomeAssitantNotificationsApiExtensions.<ApiMailingPostAsync>d__1.MoveNext() in /Users/markiian-tsymbalista/Documents/Projects/identity_and_access_management_api/src/HomeAssistant.IdentityAndAccessManagement.Services/HomeAssitantNotificationsApiExtensions.cs:line 46\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\n at HomeAssistant.IdentityAndAccessManagement.Services.NotificationsClient.<SendEmail>d__4.MoveNext() in /Users/markiian-tsymbalista/Documents/Projects/identity_and_access_management_api/src/HomeAssistant.IdentityAndAccessManagement.Services/NotificationsClient.cs:line 34\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n at HomeAssistant.IdentityAndAccessManagement.Controllers.RegistrationController.<Post>d__3.MoveNext() in /Users/markiian-tsymbalista/Documents/Projects/identity_and_access_management_api/src/HomeAssistant.IdentityAndAccessManagement.Api/Controllers/RegistrationController.cs:line 54}

**Comment by fearthecowboy** [comment]
I think we've seen this before, it turns out it's a bug in the dotnet core framework on non-windows OSes.

I'm loathe to just say "upgrade to the latest dotnet-cli bits"... I'm pretty sure that the underlying issue was handled, but I don't know what build to move to to unblock this.

@devigned -- you ran into this ... any ideas?

**Comment by markiiantsymbalista** [comment]
@fearthecowboy 

Thank you. 
You are right. 
It helped immediately:)
We could close this.

**Comment by Mobrockers** [comment]
I'm running into this issue in a project, could you tell me what you updated to resolve this issue? @markiiantsymbalista

**Comment by markiiantsymbalista** [comment]
please, take a look

https://github.com/Azure/autorest/issues/1564
