### ISSUE TITLE
[Go] Generator ignores if inherited attributes are required

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1540]
A concrete example...
[RedisCreateParameters](https://github.com/Azure/azure-rest-api-specs/blob/a3dd6c7030c6adbc39fb3b5ad962996cd6cc7eb8/arm-redis/2016-04-01/swagger/redis.json#L779) inherits form [Resource](https://github.com/Azure/azure-rest-api-specs/blob/a3dd6c7030c6adbc39fb3b5ad962996cd6cc7eb8/arm-redis/2016-04-01/swagger/redis.json#L744), where location is marked as required.
Location should be included in the [method's validation](https://github.com/mcardosos/azure-sdk-for-go/blob/f7600bd13888341c2cadd65b55965c07a52bf386/arm/redis/redis.go#L51) section.

**Comment by marstr** [comment]
Moved to the [Azure/azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) repository. Closing this copy.
