### ISSUE TITLE
Java generator does not handle correctly global parameters which has "x-ms-parameter-location": "method"

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1541]
https://github.com/Azure/autorest/blob/6a1cab3d0ccf5aca762d8a0a5932c41c2b8c0030/src/core/AutoRest.Extensions.Azure/AzureExtensions.cs#L81 this is missing in java generator. 

```
public static void NormalizeAzureClientModel(ServiceClient serviceClient, Settings settings, CodeNamer codeNamer)
        {
...
            ProcessGlobalParameters(serviceClient);
...
        }
```

should be fixed in AzureJavaCodeGenerator.cs and in AzureJavaFluentCodeGenerator.cs

**Comment by olydis** [comment]
@jianghaolu Is this still an issue? If so, please reopen.
