### ISSUE TITLE
Schema of body parameters for a PATCH operation should not have required attributes

### ISSUE THREAD

**Issue by johanste** [Azure/autorest#1547]
...at least not for a content type == application/json (for json-patch etc. this rule would not apply)

It would be odd to require a specific property to be provided in the body parameter for a PATCH operation. Likewise, it would be odd to have a default value for a property in the model for a body parameter for a PATCH operation.

**Comment by olydis** [comment]
We really wanna check for nullability right? An `int` field would always cause a silent overwrite with `default(int)`, pretty much the reasoning about default values applies.

**Comment by veronicagg** [comment]
https://github.com/Azure/autorest/issues/1951

**Comment by olydis** [comment]
will close since #1951 captures this issue, has Px classification, etc.
