### ISSUE TITLE
CompositeSwagger Fails for InsightsClient for Java Only. Python CSharp work. 

### ISSUE THREAD

**Issue by solvingJ** [Azure/autorest#1548]
Autorest Version 0.16.0

When trying to use the compositeSwagger feature under the Insights client, I receive the following error: 

error: [FATAL] Error saving generated code: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.

I am able to generate the Python library and CSharp libraries successfully. Did not test further. 

CSHARP: 
C:\Users\jerry_b828mc0\git-docs\azure-rest-api-specs\insights>autorest.exe -modeler CompositeSwagger -input compositeInsightsClient.json -output c:\users\jerry_b828mc0\git-java\azure-autorest -codeGenerator Azure.CSharp -verbose
The Microsoft.Rest.ClientRuntime.Azure.3.2.0 nuget package is required to compile the generated code.
**Finished generating Azure.CSharp code for ./2016-09-01/swagger/insightsClient.json.**
WARNING: Parameter 'verbose' is not expected.
INFO: AutoRest Core 0.16.0.0
INFO: Initializing modeler.
INFO: Initializing modeler.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Initializing code generator.
INFO: Successfully initialized Azure.CSharp Code Generator 1.0.5976.25332
INFO: Initializing code generator.
INFO: Successfully initialized Azure.CSharp Code Generator 1.0.5976.25332

PYTHON
C:\Users\jerry_b828mc0\git-docs\azure-rest-api-specs\insights>autorest.exe -modeler CompositeSwagger -input compositeInsightsClient.json -output c:\users\jerry_b828mc0\git-java\azure-autorest -verbose -codeGenerator Azure.Python
The msrestazure version 0.3.0 pip package is required to execute the generated code.
**Finished generating Azure.Python code for ./2016-09-01/swagger/insightsClient.json.**
WARNING: Parameter 'verbose' is not expected.
INFO: AutoRest Core 0.16.0.0
INFO: Initializing modeler.
INFO: Initializing modeler.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Initializing code generator.
INFO: Successfully initialized Azure.Python Code Generator 1.0.5976.25334
INFO: Initializing code generator.
INFO: Successfully initialized Azure.Python Code Generator 1.0.5976.25334

JAVA
C:\Users\jerry_b828mc0\git-docs\azure-rest-api-specs\insights>autorest.exe -modeler CompositeSwagger -input compositeInsightsClient.json -output c:\users\jerry_b828mc0\git-java\azure-autorest -verbose -codeGenerator Azure.Java
Code generation failed.
AutoRest.exe -modeler CompositeSwagger -input compositeInsightsClient.json -output c:\users\jerry_b828mc0\git-java\azure-autorest -verbose -codeGenerator Azure.Java
**error: [FATAL] Error saving generated code: Object reference not set to an instance of an object.**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Rest.Generator.Java.PropertyModel..ctor(Property property, String package)
   at Microsoft.Rest.Generator.Java.ModelTemplateModel.<>c__DisplayClass2_0.<.ctor>b__0(Property p)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Microsoft.Rest.Generator.Java.ModelTemplateModel..ctor(CompositeType source, ServiceClient serviceClient)
   at Microsoft.Rest.Generator.Java.ServiceClientTemplateModel.<>c__DisplayClass0_0.<.ctor>b__2(CompositeType m)
   at Microsoft.Rest.Generator.Utilities.Extensions.ForEach[T](IEnumerable`1 sequence, Action`1 action)
   at Microsoft.Rest.Generator.Java.ServiceClientTemplateModel..ctor(ServiceClient serviceClient)
   at Microsoft.Rest.Generator.Java.Azure.AzureServiceClientTemplateModel..ctor(ServiceClient serviceClient)
   at Microsoft.Rest.Generator.Java.Azure.AzureJavaCodeGenerator.<Generate>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Generator.AutoRest.Generate(Settings settings)
WARNING: Parameter 'verbose' is not expected.
INFO: AutoRest Core 0.16.0.0
INFO: Initializing modeler.
INFO: Initializing modeler.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
INFO: Initializing code generator.
INFO: Successfully initialized Azure.Java Code Generator 1.0.5976.25333

**Comment by solvingJ** [comment]
Note: this is the composite file I am trying to build: 

https://github.com/Azure/azure-rest-api-specs/tree/master/insights

Also note, i am able to use azure rest to generate Java from all 4 of the swagger specs in the folder individually.

**Comment by solvingJ** [comment]
I went and got the nightly build of AutoRest.exe from MyGet and now the composite generates successfully, although the success message is misleading.   It only mentions one of the swagger specs it processed (likely to be the last in the list). 

It should probably list all the Swagger specs it generated for.   I did verify that the source directory from the composite build has many more classes and models than just generating 2016-09-01 by itself, so from this cursory glance, it looks like composite is working properly. 

c:\Users\jerry_b828mc0\git-docs\azure-rest-api-specs\insights>AutoRest.exe -modeler CompositeSwagger -output Generated-Azure-Java -Namespace com.logicmon.azure -input compositeInsightsClient.json -CodeGenerator Azure.Java
The com.microsoft.rest:azure-client-runtime:1.0.0-SNAPSHOT from snapshot repo http://adxsnapshots.azurewebsites.net/ maven dependency is required to compile and run the generated code.
**Finished generating Azure.Java code for ./2016-09-01/swagger/insightsClient.json.**

**Comment by fearthecowboy** [comment]
Hey @solvingJ,

I published the latest build to NuGet this morning, so last night's nightly and today's released version will be the same now. 

How very strange with the message... I had not noticed that glitch in the generating message like that.

I do want to do some work with the logging/messaging in AutoRest, there are quite a few strange things that I'm not fond of. 

Since your original issue has been resolved, I'm going to close this, but tag it for review in our 1.0 plans so I can improve logging/messages.

**Comment by solvingJ** [comment]
FYI, yesterday the latest version of AutoRest on chocolatey was v0.16.0 and today it's the same. Shouldn't the version number increment if you published something new?

**Comment by fearthecowboy** [comment]
I wasn't even aware it was in Chocolatey. 

I didn't publish that.. 

It looks like @matt-gibbs owns that package in Chocolatey.

HEY! @matt-gibbs ! wanna update that packge in chocolatey?

**Comment by solvingJ** [comment]
So when you say released, you just mean you merged the latest branch into master on github?

**Comment by fearthecowboy** [comment]
No, I published the nuget package http://www.nuget.org/packages/AutoRest/

I wasn't even aware there was a chocolatey package.  I'm getting control of that right now.
