### ISSUE TITLE
Missing Java AutoRest Class - ServiceResponseCallback

### ISSUE THREAD

**Issue by solvingJ** [Azure/autorest#1550]
Autorest is generating Java code that references the class "ServiceResponseCallback".  This class does not exist in com.microsoft.rest:client-runtime:1.0.0-beta3, but does exist in 1.0.0-beta2

I just made the following comment on that project, showing where the class was removed. The comments do not state why they were removed.

https://github.com/Azure/autorest-clientruntime-for-java/commit/7814d4fabe95e21b566dc07dd8ee693ec91edf07?diff=unified

**Comment by fearthecowboy** [comment]
You probably should file an issue over there, so that the java runtime team will see it. 
(see https://github.com/Azure/autorest-clientruntime-for-java/issues )

**Comment by solvingJ** [comment]
I've created this ticket:  https://github.com/Azure/autorest-clientruntime-for-java/issues/125

However, I think maybe it's a non-issue because I should not have been using beta3 to begin with. 

I've just started using the snapshot builds for those libraries from http://adxsnapshots.azurewebsites.net/ as the autorest generator suggests.  However, when using the snapshots of those libraries, there are far more build errors.

**Comment by fearthecowboy** [comment]
Hmm. 

I was pretty sure that `1.0.0-beta3` was _supposed_ to be the one you should use.

We're still working towards stability with the Java generator.  Recent changes in the workflow model around here should get us a lot closer to things not breaking. 

Can post the swagger file that generates that? 

If the current generator is generating code that's not in the runtime, that's not right, and we should look at that.

@jianghaolu is the master of all things Java, perhaps he can shine a light on this.

**Comment by solvingJ** [comment]
I understand and am glad to try to help. 

It's not the swagger file that says that, it's Autorest:

https://github.com/Azure/autorest/search?utf8=%E2%9C%93&q=http%3A%2F%2Fadxsnapshots.azurewebsites.net%2F

**Comment by fearthecowboy** [comment]
I wanted to see the swagger file so I could reproduce the issue with the generating code that references `ServiceResponseCallback` .

**Comment by jianghaolu** [comment]
Hi @solvingJ 
I believe it's a bug that AutoRest generates reference to that class. Assigned myself.

**Comment by solvingJ** [comment]
@jianghaolu The generator says to use the snapshots 1.0.0, but those are missing far more classes than the beta3.  Should we be using beta3? If so, it seems like the note to use snapshots should be removed.

**Comment by solvingJ** [comment]
Well in that case the line above it is also broken, ServiceCall's constructor is protected. 

final ServiceCall serviceCall = new ServiceCall(call);

**Comment by solvingJ** [comment]
@jianghaolu  It seems it might take a while to see a fix for this issue be released.  Can you tell provide any sort of workaround? We're anxious to use the generated code, and it seems there could be a small fix we could apply to the generated sources for now.

**Comment by solvingJ** [comment]
ServiceResponseCallback is also present in the generated code for batch: 
- https://github.com/Azure/azure-rest-api-specs/tree/master/batch

**Comment by jianghaolu** [comment]
@solvingJ batch uses beta2 runtime and beta2 runtime has that file

For now, if you are okay with using the generator from beta2, you can use the nightly version of AutoRest `0.17.0-Nightly20160707` to generate code compatible with beta2 runtimes.

**Comment by solvingJ** [comment]
Changing to beta2 does enable us to compile, however this simple test does not work: 
(subscription ID obfuscated)
```
        String path = "/subscriptions/01234567-0123-0123-0123-012345678910110"+
                "/resourceGroups/LmProduct" +
                "/providers/Microsoft.Web" +
                "/sites/LmProductTestApp"

        InsightsClientImpl client = new InsightsClientImpl(CREDENTIALS)
                .withSubscriptionId(azSubscription)
                .withResourceUri(path)
        
        println "metricDefs = " + client.metricDefinitions().list().body.toString()

```
java.lang.IllegalArgumentException: URL "{resourceUri}/providers/microsoft.insights/metricDefinitions" does not contain "{subscriptionId}". (parameter #2)
    for method MetricDefinitionsService.list

Not sure what we could be doing wrong.

**Comment by solvingJ** [comment]
We found the source of the issue, it's a bug in the REST spec causing an unnecessary required parameter in the generated source files.  I've submitted the two PRs.
https://github.com/Azure/azure-rest-api-specs/pull/660
https://github.com/Azure/azure-rest-api-specs/pull/661
