### ISSUE TITLE
C# codegen can generate invalid C# comments

### ISSUE THREAD

**Issue by koolraap** [Azure/autorest#1552]
We have a swagger file where info.description contains `. \r</p>\n`. This results in invalid C# as the generated comment contains a spurious CRLF.

Swagger snippet:

```
   {
"swagger" : "2.0",
"info" : {
    "version" : "v1",
    "title" : "Some Api",
    "description" : ".  \r</p>\n"
},
```

Codegen snippet annotated with [CR][LF]

```
/// <summary>
/// .  [CR][LF]
&lt;/p&gt;[CR][LF]
/// </summary>
public partial class SomeApiService : ServiceClient<SomeApiService>, ISomeApiService
```

**Comment by fearthecowboy** [comment]
Hmm. That's not cool.

I'm looking into it.
