### ISSUE TITLE
Move wiki/documentation into code repo

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#1555]
We want to move the documentation into the code repository, and have it possible to generate a github docs pages from that.

To do that:
- rename `Documentation` to `docs`
- make a hierarchy with items like:
  - `client` - documentation for client apps (stuff that starts with client-)
  - `user` - autorest end-user documentation
  - `extensions` - reference documentation for autorest `x-ms` extensions
  - `developer` - notes/reference for autorest developers 
  - `proposals` -  new feature proposal documentation
- move existing docs into place.
- make sure `index.md` files are in place
- update existing wiki to simply point to github.io. docs

**Comment by olydis** [comment]
left to do:
- configure project such that GitHub Pages is created from `/docs`
- apply hack (or something sane) to fix inevitably broken relative paths 
  - rewrite `.md` paths to `.html`
  - fix paths into code

**Comment by fearthecowboy** [comment]
For the time being just rename `index.md` to `readme.md` everywhere, and we'll close this up.
