### ISSUE TITLE
python: configuration field for LRO polling interval is not correct

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/autorest#1558]
The [generated code for client](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute_management_client.py#L77 ) assumes ` long_running_operation_retry_timeout`, but its [operation](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/operations/virtual_machines_operations.py#L219 ) assumes `long_running_operation_timeout`

**Comment by yugangw-msft** [comment]
//cc: @lmazuel @annatisch

**Comment by yugangw-msft** [comment]
Once we fix this, the client side can use normal pattern to configure the timeout through constructor

**Comment by annatisch** [comment]
Hi @yugangw-msft, thanks for spotting this!

After discussing possible fixes with @lmazuel, we're thinking that we will remove this (and other options) from the constructor of the client, so these will need to be set specifically on client.config like you are currently doing in your workaround.

This should help us reduce the size of the generated code.

For example, the generated code will become:
```python
class ComputeManagementClientConfiguration(AzureConfiguration):
    def __init__(self, credentials, subscription_id, base_url=None, filepath=None):

        if credentials is None:
            raise ValueError("Parameter 'credentials' must not be None.")
        if subscription_id is None:
            raise ValueError("Parameter 'subscription_id' must not be None.")
        if not isinstance(subscription_id, str):
            raise TypeError("Parameter 'subscription_id' must be str.")
        if not base_url:
            base_url = 'https://management.azure.com'

        super(ComputeManagementClientConfiguration, self).__init__(base_url, filepath)

        self.add_user_agent('computemanagementclient/{}'.format(VERSION))
        self.add_user_agent('Azure-SDK-For-Python')

        self.credentials = credentials
        self.subscription_id = subscription_id

class ComputeManagementClient(object):
    def __init__(self, credentials, subscription_id, base_url=None, filepath=None):

        self.config = ComputeManagementClientConfiguration(credentials, subscription_id, base_url, filepath)
        self._client = ServiceClient(self.config.credentials, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)
```

And this would be consumed and configured like so:
```python
client = ComputeManagementClient(creds, sub_id, base_url=service_url)
client.config.generate_request_id = False  # Default is True
client.config.accept_language = 'de-DE'  # Default is 'en-US'
client.config.long_running_operation_timeout = 5  # Default is 30
```
This is a breaking change - so will be rolled out into the next major version of the Azure SDK for Python.

What do you think?

Cheers,
Anna

**Comment by yugangw-msft** [comment]
@annatisch , this looks to me.

**Comment by fearthecowboy** [comment]
Is this still a concern? Please reopen with details if it is.

**Comment by lmazuel** [comment]
@fearthecowboy indeed already fixed
