### ISSUE TITLE
Support GitHub flavored Markdown in description

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#1562]
It looks like it is not supported by the spec in "title" (for body) or "summary" (for operations) -- which makes sense since those fields are intended to be short.

The GFM should be translated to the corresponding language documentation idioms somehow from the markdown. (i.e. `<para>`, or `<list>` for C#).

Ideally there would be a way to "link" to code that will be generated as well, so in the Markdown one might specify (the `property`) and that would get translated into `<see cref="Property"/>` for C#, or similar for other languages that support that style).

**Comment by matthchr** [comment]
@fearthecowboy

**Comment by Thraka** [comment]
Does normal markdown work in a description for something? I tried just using ** for bold and in my swagger file and it was translated to ** instead of bold (or stripped out) for the /// commends on the generated C# files

**Comment by matthchr** [comment]
@Thraka Not in AutoRest currently, no. All descriptive text (`summary`, `title`, and `description`) are just raw text, they aren't processed as markdown.

But `description` should allow GitHub flavored Markdown syntax (according to the Swagger specification, for example see [here](http://swagger.io/specification/#operationObject))

**Comment by Thraka** [comment]
Interesting that swagger didn't allow inline styled markdown for summary/title. Bold and Italic are helpful in those areas. OK So we're on the same page. :) Any idea of when this will be added?

**Comment by matthchr** [comment]
No idea when this will be added -- it's tricky because the individual languages will each need their own mapping from GFM to their language specific documentation notation. So for example C#'s might use `<para>` but Python might just use a plain old newline. And given the fact that not every language supports all of the GFM features, etc it'll probably take a while to get it right I would imagine.

@fearthecowboy Might have more insight.

**Comment by fearthecowboy** [comment]
IIRC AutoRest should now be stripping out the markdown cleanly from the inputs. 

Adding support for formatted strings in the generators is a next step -- I believe we support a markdown AST in the codemodel but I don't believe that anyone uses it for code generation.

Definitely something I'd like to handle in the v.Next generators.
