### ISSUE TITLE
nextLinkName to null: check in Core instead of Python

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1573]
Currently the Python generator is the only place where "nextLinkName" not null for a bad reason fails:
```console
AutoRest.exe -i /git-restapi/insights/compositeInsightsClient.json -o /tmp/tmpqemy3mj0/compositeInsightsClient.json -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Modeler CompositeSwagger -Namespace azure.monitor -PackageVersion 0.1.0 -ft 2
FATAL: Error saving generated code: Couldn't find the nextLink property specified by extension on operation Events_List and property EventDataCollection
```

The problem is that since this does not fail during the PR in the REST repo, we discover that only when the Python team actually tries to generate the client.

This check should be made in the core (to fail for everybody) or at least be a rule of the linter.

FYI @fearthecowboy @annatisch

**Comment by fearthecowboy** [comment]
I think that's on the table for a linter rule. We're just cleaning up our backlog of misc bugs, but I think november, we're going to have a blitz on linting rules.

**Comment by olydis** [comment]
added `linter-rule` tag so we definitely won't miss it :)

**Comment by olydis** [comment]
@fearthecowboy @lmazuel Turns out this already *is* a linter rule!
`Warning: The property '...' specified by nextLinkName does not exist in the 200 response schema.`

**Comment by lmazuel** [comment]
The check was removed from Python code. Up to you guys from the Core to force it or not :)
