### ISSUE TITLE
AutoRest does not complain about invalid Swagger and generates invalid code instead

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1576]
Take
```YAML
swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
paths:
  /operationInteger:
    get:
      operationId: test_integer
      responses:
        200:
          description: OK
          type: integer
    parameters:
      - in: query
```

**Note: The single parameter specified does not have a name.**

Still, AutoRest succeeds, the CSharp generator emits garbage code like `if ( != null)`.

Haven't checked the other generators, but AutoRest should probably just validate the Swagger before doing anything else.

**Comment by fearthecowboy** [comment]
should be validation rule
