### ISSUE TITLE
New Rule: If LRO has several status codes defined all of them should have a schema definition for returned type

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1590]
Here is a wrong definition in swagger:
```
"paths": {
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cache/Redis/{name}": {
      "put": {
       ...
        "operationId": "Redis_Create",
        "x-ms-long-running-operation": true,
        "parameters": [
         ...
        ],
        "responses": {
          "201": {
            "description": "",
          },
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/RedisResource"
            }
        ...
      },
```

In this case we will generate 2 methods: Create and BeginCreate. If the callers want to handle polling themselves (in opposite of waiting xx minutes until Create will finish LRO polling workflow) they will receive null object after BeginCreate method call (since 201 does not define a schema). 
Linter tool should just check that in LRO methods each response defines a schema so Begin[Method] operations become usable.

**Comment by amarzavery** [comment]
Not entirely correct. We were doing that previously and I think it was storage that said that they don't return a schema for the initial 202. Here is the example: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-01-01/swagger/storage.json#L102.

I think the above rule could be applied for 201 and 200.

**Comment by olydis** [comment]
I can write a rule for this. 
Just to clarify: Whenever an operation is an LRO, then both 200 and 201 (if present) should have a schema?
- To which HTTP methods does this apply? Not only `put`, I assume?
- I guess this is a warning and not an error
- preferred warning message?

**Comment by veronicagg** [comment]
@dsgouda let's start with Warning on this rule, and SDK Violation. There are some questions above that may need still to be answered to implement this rule.

**Comment by dsgouda** [comment]
To begin with, I will apply this for the PUT operations (DELETE should anyway not return anything)
