### ISSUE TITLE
Generated code contains incorrect version number

### ISSUE THREAD

**Issue by koolraap** [Azure/autorest#1603]
Problem: code generated by AutoRest 0.17.3 (CSharp codegen) says it's generated by AutoRest 0.17.0.0

    // Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0

I know this bug is pure pedantry, but it should be either `0.17` or `0.17.3`

**Comment by fearthecowboy** [comment]
Yeah, somewhere a while back, the part of the build script that updated the `versionattribute` in c# got lost. I'd fix it, but not until we move back away from `project.json` build files. 

I'll try to remember to manually update it when I put thru 1.0 🤒
