### ISSUE TITLE
Since 0.16.0 CSharp codegen no longer contains class ApiErrorException

### ISSUE THREAD

**Issue by koolraap** [Azure/autorest#1604]
Autorest 0.15 generated a combined file containing a class named `MyService.Data.Proxies.Models.ApiErrorException`. AutoRest 0.16 onwards does not do this.

**Note: this is getting odd. Please read all comments**

Is this expected? We use the `-outputfilename MyServiceProxy.cs` option if that matters. If it is expected where can we find ApiErrorException?

This code is from 0.15. Missing 0.16 onwards.

	namespace MyService.Data.Proxies.Models
	{
		using Microsoft.Rest;
		using System;
		using System.Net.Http;
		using System.Runtime.Serialization;
	#if !PORTABLE && !DNXCORE50
		using System.Security.Permissions;
	#endif

		/// <summary>
		/// Exception thrown for an invalid response with ApiError information.
		/// </summary>
	#if !PORTABLE && !DNXCORE50
		[Serializable]
	#endif
		public class ApiErrorException : RestException
		{

**Comment by koolraap** [comment]
Ah! Instead of `ApiErrorException` failure is now `HttpOperationException`. It'd be useful to add that to the 0.16 release notes.

Unless there's anything else of note regarding this change I'm happy to close this.

**Comment by koolraap** [comment]
You know what? I think I may have a beta version or something of 0.15 on my PC. Other people in the team are using 0.15 to generate code that doesn't contain ApiErrorException.

If only #1603 was raised earlier :-)

**Comment by koolraap** [comment]
Is it possible Windows Update has somehow changed the behaviour of AutoRest?

**Comment by koolraap** [comment]
Ahhh... I bet it's because we have our first method returning two 2XX responses with different payloads, so it's now generating proxies returning <object> rather than <Thing>. I think I knew that but forgot. I'll check when I'm back at the office.

**Comment by koolraap** [comment]
I think what's happening is our default response model (ApiErrorException) is no longer being generated because Autorest's behaviour changes when there are any methods returning 2 objects. If that's the case I'll raise a less incoherent issue.

**Comment by amarzavery** [comment]
@koolraap - [This doc](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Responses) will be helpful. Please read the default response and the negative response section for more info.

**Comment by koolraap** [comment]
Thanks @amarzavery. So if there's a single operation that AutoRest deems should return `object` then all operations will return `object`?

**Comment by amarzavery** [comment]
I am sorry didn't understand your comment. How will the return type of one operation have a bearing on the return type of other operations?

**Comment by koolraap** [comment]
@amarzavery that's exactly what I was thinking! Anyway I've found the root cause of my confusion: someone's gone and turned off the `default` response for all our operations... didn't occur to me check the swagger file (we use Swashbuckle). Sorry to waste your time, at the least I hope watching my brain melt was amusing. :-/
