### ISSUE TITLE
Development-time BaseUri is hard-coded in the generated code

### ISSUE THREAD

**Issue by jaxidian** [Azure/autorest#1610]
When generating code, the private Initialize method has the dev-time BaseURI hard-coded in the generated code. This is a dangerous practice if the developer consuming the generated client doesn't explicitly pass in the BaseUri which could allow something to pass through testing successfully but be deployed to production with this dependency on a dev resource.

```
        private void Initialize()
        {
            this.Stuff = new Stuff(this);
            this.BaseUri = new Uri("https://DevTimeStuff.azurewebsites.net");
```

I'd suggest two changes (either one would make me happy):
1) Require all constructors to take a `baseUri` parameter. This would be a breaking change so I understand the reluctance to do this but I don't think dev server info should EVER exist in this generated code that will likely be deployed to production environments.
2) Allow a standard configuration item to **always** override this hard-coded value. For instance, change the generated line of code to something like this:

```
        private void Initialize()
        {
            this.Stuff = new Stuff(this);
            this.BaseUri = new Uri(ConfigurationManager.AppSettings["swag:BaseUri"] ?? "https://DevTimeStuff.azurewebsites.net");
```

For the second option, I'm not sure if the addition of System.ConfigurationManager dependency would cause problems or not, but I think you get the spirit of the suggestion.

NOTE: This is using v0.16.0 via the Chocolatey install. I realize this is slightly out-of-date but my understanding is that this has not changed in ServiceClientTemplate.cshtml. But I reserve the right to be wrong.

**Comment by jaxidian** [comment]
It's probably pretty clear but I'm very obviously talking about the CSharpGenerator here. I suspect other generators may have the same problem and different options might be necessary with them.

My suggestions above were NOT meant to be indicative of well-research solutions - I just try to not communicate problems without at least an idea at a solution. ;-)

**Comment by olydis** [comment]
Why not just set `<clientInstance>.BaseUri` after instantiation? Be aware that your suggestion of putting `ConfigurationManager.AppSettings["swag:BaseUri"]` into the generated code is very specific to your scenario without enabling anything that wasn't possible before since `BaseUri` is already specifiable via constructor or justy setting the property.

Let us know if that doesn't work for you or you have further questions!
