### ISSUE TITLE
New Rule: ensure the order of parameters specified in the parameters array for every operation

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#1611]
I have been seeing this off lately while reviewing swagger specs. Parameters array inside the operation does not follow a consistent order. The order in which the parameters are defined has a direct impact on the method signature of the generate client.

The recommended pattern is [resourceGroupName, any RP specific parameterName [0..*], body parameter, subscriptionId, api-version].

The parameters may be defined inline or in the global parameters section and that is fine.

**Comment by jaredmoo** [comment]
Subscription id and api-version being together makes sense from a client point of view but makes the swagger spec harder to read. IMO the params should be in the same order as in the operation's path, e.g. i.e. subscription id, resource group name, RP parameter names, api version and then body parameter.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
