### ISSUE TITLE
Possible swagger extension x-ms-mark-object?

### ISSUE THREAD

**Issue by pareshverma91** [Azure/autorest#1613]
We are looking into creating our client SDK by creating a swagger doc and using AutoRest. Things look fine except that we are having some trouble in expressing some of our concepts (not just because of swagger or autorest limitations, but also because of some of underlying languages).

Scenario: Our object models are pure JSON objects with a strict structure, except for parameters. e.g. for schema such as
```javascript
"Animal": {
    "properties": {
        "legs":{
            "type": "integer"
        },
        "type": {
            "$ref": "#/definitions/AnimalType"
        }
    }
},
"AnimalType": {
    "properties": {
        "name": {
            "type": "string"
        },
        "wings":{
            "type": "boolean"
        }
    }
}
```
we should be able to accept all of the following jsons
```javascript
a = {
    "legs": 4,
    "type": {
        "name": "dog"
    }
}
```
or
```javascript
b = {
    "legs": "@parameters('myLegs')",
    "type": "@parameters('myType')"
}
```
The idea is that any property value, or array item can either be as per schema or can pick its value from a context object "parameters". The only way we can handle this in swagger/autorest combo is by marking all the properties as type object. This way we only get to generate relevant classes from swagger, and loose the complete serialization and deserialization part (because of the scenario).
However, to generate proper documentation we would still like to mark the property types properly, and add a new extension "x-ms-mark-object" that would convert the model/property type to object as part of the build process. We currently have a custom dll that generates a new swagger doc, based on this flag. Do you guys think that this is generic enough to included in autorest?

**Comment by fearthecowboy** [comment]
That seems awfully narrow to do in AutoRest directly.

However, we're soon going to have the ability in AutoRest to allow you to insert a step into the pipeline so you could write a custom script or exe to tweak the generated Code Model during the generation process, which could easily make some changes for your particular scenario.

We've basically got the infrastructure in AutoRest to handle that, I just have to expose the behavior to the actual AutoRest exe. 

I'm hoping to get that done by the end of the year sometime.

**Comment by bgold09** [comment]
@fearthecowboy sounds good. In the meantime, I guess we can simply have both the template and generated swagger next to each other. On a related note, how would the builds know which JSON file to use as the true spec?

**Comment by pareshverma91** [comment]
Just as I thought. Thanks for looking at this though.
Enabling entry point in the pipeline would be great. I hope extension points would be available at multiple points like before parsing of swagger doc, after generation of code etc.

**Comment by fearthecowboy** [comment]
Hey @pareshverma91 

The extension points are indeed very fine-grained, and there are several points. Plus, you can set a priority within a trigger point in case there are multiple extensions at the same trigger, but you want it to be before or after another.

The extensibility is limited to after the swagger is parsed and the code model (ie, method-groups, methods, parameters etc) is created -- I didn't refactor the swagger parser part, and may not get to that until much later, so it's probably going to be a "AutoRest 2.0" feature.
