### ISSUE TITLE
C#. Byte array parameter not being serialized properly

### ISSUE THREAD

**Issue by alesvi** [Azure/autorest#1616]
We are having problems with requests containing byte arrays as parameters. I think the byte[] values are not being serialized properly.

More details:

We have a POST endpoint with a byte parameter. Something like:

`public HttpResponseMessage Post([FromBody] PostRequest request)`

Where PostRequest is:

```
public class PostRequest
{
 public byte? Parameter { get; set; }
}
```

When we generate the client classes, the byte parameter becomes a byte[]. When we try to call to that client method using something like:

```
var api = new APIClient(new Uri("http://myapi.com/"));
byte[] byteArray = { 1 };
var requestParameters = new RequestParameters()
            {
                Parameter = byteArray
            };
api.ClientClass.Post(requestParameters);
```
requestParameters.Parameter arrives as null to the API endpoint.

I've been debugging the client generated code and I think the problem is when serializing the requestParameters object into a JSON. The resulting JSON is:

```
{  
  "parameter": "AQ==",  
}
```

So I guess that the API can't deserialize that value into a byte.

The generated code that does the serialization is:

```
public async Task<HttpOperationResponse<PostResponse>> PostWithHttpMessagesAsync(PostRequest request, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
 {
...
	// Serialize Request
	string _requestContent = null;
	if(request != null)
	{
		_requestContent = SafeJsonConvert.SerializeObject(request, this.Client.SerializationSettings);
		_httpRequest.Content = new StringContent(_requestContent, Encoding.UTF8);
		_httpRequest.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json; charset=utf-8");
	} 
...
```

**Comment by fearthecowboy** [comment]
Could you post the swagger json file so I can see what you're creating?

**Comment by alesvi** [comment]
Here you go:
[swagger.json.txt](https://github.com/Azure/autorest/files/596965/swagger.json.txt)

I saw now that I have problems with the Get operation too. Getting a Microsoft.Rest.SerializationException: [SerializationException.txt](https://github.com/Azure/autorest/files/597032/SerializationException.txt)

So summarizing, I have problems both with the POST (the serialized JSON can't be properly deserialized by the API), and with the GET (exception deserializing the response from the API). The parameter having problems is a byte in the API and a byte[] in the generated client.

**Comment by fearthecowboy** [comment]
Thanks @alesvi  -- I'll dig into exactly what's going on this morning.

**Comment by olydis** [comment]
You seem to have an issue in your Swagger, AutoRest generates precisely what is supposed to as far as I can tell.

Just to clarify: You are talking about the property that is created from
```
"attributeTypeId": {
    "format":"byte",
    "type":"string"
}
```
in your Swagger? The Swagger spec says that this translates to a base64 encoding of some bytes (and not a single byte! That would probably be modeled as `integer` in Swagger).
Therefore, the JSON you posted is exactly what I would expect an AutoRest generated client to generate.

I suspect that your Swagger simply does not reflect the API correctly, e.g. if your tries to deserialize a `byte` it probably expects a number and not a base64 string.

You say "and with the GET (exception deserializing the response from the API)", could you also post what *that* message looks like, then we can derive what the server expects and can adjust the Swagger accordingly.

**Comment by gitfool** [comment]
Where does the Swagger.json come from?

Swashbuckle would've generated an integer, if that was used: [SchemaRegistry.cs#L146](https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/SchemaRegistry.cs#L146)

**Comment by alesvi** [comment]
Yes, I am using Swashbuckle. The problem was that the version I was using was generating bytes as strings. I updated to the latest version and it's working fine.

Sorry for posting the problem here. It wasn't a problem with AutoRest but with Swashbuckle.

Thanks for your help guys.
