### ISSUE TITLE
Support x-ms-client-flatten in Go generator

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1620]
~~Related [issue](https://github.com/Azure/azure-sdk-for-go/issues/459/)~~ Issue is on the swagger, not the generator. Still, would be cool if the Go generator supported flattening.

**Comment by jhendrixMSFT** [comment]
This has been implemented in the legacy branch in change https://github.com/Azure/autorest/commit/3f91c30390f91098517785aba573a6d6d5608a0f.  I have merged it into my refactoring work.
