### ISSUE TITLE
Go generator ignores x-ms-external

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1625]
About [x-ms-external](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-external)
Example... [SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/redis/models.go#L109) vs [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L670)

**Comment by fearthecowboy** [comment]
@mcardosos Is this still an issue? Reopen if necessary.

**Comment by marstr** [comment]
Not an issue anymore!
