### ISSUE TITLE
.NET SDK does not properly honor optional streams as parameters

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1629]
When generating .NET sdk the following swagger in a method:
```
{
            "name": "streamContents",
            "in": "body",
            "schema": {
              "type": "object",
              "format": "file"
            },
            "required": false
}
```
Results in this generated C# method signature:
```
CreateWithHttpMessagesAsync(string accountName, string directFilePath, System.IO.Stream streamContents = default(System.IO.Stream), bool? overwrite = default(bool?), SyncFlag? syncFlag = default(SyncFlag?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
```
The default value for a stream is simply `null` which results in a "value cannot be null error" when the generated code attempts to do this:
`StreamContent _fileStreamContent = new StreamContent(streamContents);`

The fix here is to honor the optional nature of streams (if they are specified as such) and put the assignment of _fileStreamContent within a conditional statement that requires the stream to != null and != Stream.Null.

which would look something like this:
```
if (streamContents != null && streamContents != Stream.Null)
{
    _httpRequest.Content = new StreamContent(streamContents);
    _httpRequest.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/octet-stream");
}
```

**Comment by fearthecowboy** [comment]
I'm trying to imagine the use case for this :)

On one hand, yeah, we should have better code output for that, so we'll fix the bug. Seems pretty trivial.

From the swagger perspective, uh, what's the use case for an API that takes a file upload, but doesn't actually require an uploaded file?

o_O

**Comment by fearthecowboy** [comment]
We'll take this under consideration with the v.Next generators -- not in classic tho'
