### ISSUE TITLE
AutoRest doesn't remove HTML tags from documentation

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1640]
Not sure if this should be handled by the generators or the Core (Is any language that benefits from the tags?), but yes, AutoRest will generate code like [this](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/machinelearning/webservices.go#L30), from [this](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-machinelearning/2016-05-01-preview/swagger/webservices.json#L5) swagger.

**Comment by fearthecowboy** [comment]
Well, documentation strings in swagger are allowed to be markdown, and markdown permits HTML, so ... hard to tell people not to do that. 

We should be looking at doing something about this soon, but not quite yet.

**Comment by fearthecowboy** [comment]
We're going to fix this better in v.Next generators.
