### ISSUE TITLE
Java service client generator produces bad documentation strings

### ISSUE THREAD

**Issue by jasper-schneider** [Azure/autorest#1642]
If you look at a Java service client, you'll see documentation strings like "Gets Gets or sets the preferred language for the response.." or "Sets Gets or sets the retry timeout in seconds for Long Running Operations. Default value is 30.."
Examples: https://github.com/Azure/azure-batch-sdk-for-java/blob/master/src/main/java/com/microsoft/azure/batch/protocol/BatchServiceClient.java#L46
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-keyvault/src/main/java/com/microsoft/azure/keyvault/KeyVaultClient.java#L91

It looks like the problem is caused by the template for the service clients.  The template automatically starts comments with "Gets" or "Sets" and automatically adds a "." at the end.
https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.Java.Azure/Templates/AzureServiceClientInterfaceTemplate.cshtml#L48

I believe the doc strings for the service clients are coming from here: https://github.com/Azure/autorest/blob/master/src/core/AutoRest.Extensions.Azure/AzureExtensions.cs#L264

**Comment by fearthecowboy** [comment]
I'd think that's corrected, but @jianghaolu  -- could you look at this, and reopen if necessary?
