### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by Serjster** [Azure/autorest#1644]
Any chance you guys can keep this updated? https://github.com/Azure/autorest/blob/master/ChangeLog.md

I notice that you have a new version .173 how is it diff from .16?

**Comment by fearthecowboy** [comment]
Yeah, I was thinking about that. 

Trying to figure out how to distill 250+ commits into a sensible, coherent changelog. 

Basically, EVERYTHING has changed.  😆 

I'll see if I can find a way, but it's not my highest priority this week :D
