### ISSUE TITLE
Chocolatey version out of date?

### ISSUE THREAD

**Issue by erendrake** [Azure/autorest#1645]
Nuget and Chocolately seem to be out of sync for autorest

[![AutoRest NuGet](https://img.shields.io/nuget/v/autorest.svg?style=flat-square)](https://www.nuget.org/packages/autorest/)

[![AutoRest Chocolatey](https://img.shields.io/chocolatey/v/autorest.svg?style=flat-square)](https://chocolatey.org/packages/AutoRest)

Your changelog hasnt been updated with any of the new stuff so i dont know what im missing out on as a chocolately user.  #1644

**Comment by fearthecowboy** [comment]
I attempted a while back to rebuild a new version of the chocolatey package, but recent changes made what it installed not usable. 

With everything else I have going on, I haven't got back to solving the issue with chocolatey.

**Comment by erendrake** [comment]
@fearthecowboy is this something an interested community member could take a stab at?

**Comment by fearthecowboy** [comment]
If you'd like :D  We like pull requests :D

I never inherited whatever files my predecessors used to generate the package, so I don't even have a start point at the moment.

**Comment by erendrake** [comment]
@fearthecowboy do you have access to push to the autorest package on Chocolately. Alternatively we could either start a new feed or abandon Chocolately as a delivery method.

**Comment by erendrake** [comment]
Maybe @matt-gibbs has the info?

**Comment by stankovski** [comment]
@fearthecowboy choco package is the same nupkg file produced by the `autorest-publish` job. Ping me offline and I'll give you the chocolatey password so that you can set up build automation.

**Comment by fearthecowboy** [comment]
I have the credentials.

What I don't have is an actual `.nuspec` file anymore, since the dotnet-cli tools are being used to generate the package currently.

I'm working right now to move back to `.csproj` (which uses the most recent dotnet-cli tools) and wanted to get that working again so I didn't have to jump thru the hoops twice.

Currently, if you want to get the latest stable binary, you can install it like 

``` batch
NuGet.exe install AutoRest -outputdirectory c:\autorest 
```
 or the latest nightly:

``` batch
NuGet.exe install AutoRest -source https://www.myget.org/F/autorest/api/v3/index.json -prerelease -outputdirectory c:\autorest 
```

**Comment by olydis** [comment]
We have moved to `npm`, so a lot of this discussion no longer applies. Please file a new issue if you are (still) interested in a `chocolatey` package, but we currently don't maintain one.
