### ISSUE TITLE
`Client` suffix for Swagger title and Autorest

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1647]
Hi @amarzavery @fearthecowboy @markcowl 

I see that regularly now, new Swagger files remove the `Client` suffix from the title in Swagger (recently new Storage 2015-05-01, changed from [StorageManagementClient to StorageManagement](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-05-01/swagger/storage.json#L4)). I remember having a discussion with @amarzavery where he told me that this is a good behavor, since the Swagger file can describe also the server and is not client only. *BUT* Autorest *might* add `Client` to the main class name if not present.

I wanted to check with you what you think about this. Since this is the only breaking change for the new Storage file in Python, I'd like to have your feeling before release it (if Autorest adds a `Client` suffix in the main class name if not present, this is not breaking). If generated clients should not have `Client` and have to follow strictly the title, (and the client should be named StorageManagement for the storage example), that's ok too (I saw the C# PR integrates the change, so it might be on purpose). Just tell me :)

Thanks!

FYI @annatisch

**Comment by olydis** [comment]
Sounds like this was added with #1665 :-)

**Comment by olydis** [comment]
Although, I see the PR only affects C#/Azure code generation. 
@fearthecowboy Should this be a fix for all azure generators in the long run?

**Comment by lmazuel** [comment]
Thanks @olydis !

@fearthecowboy This is blocking for Storage Mgmt release in Python. Could you confirm that each language should add the `Client` suffix?

@amarzavery for Node, @veronicagg for Ruby, @jianghaolu for Java

**Comment by amarzavery** [comment]
The fix is made in the Swagger modeler. No op for the generator. If you try to generate a py client for the storage spec it should have the Client suffix in the client name.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fearthecowboy** [comment]
It should affect each langauge (in base `CodeModel` class, the `Name` member was changed to `Fixable<string>`, and the implementation tacks on `Client` if it's not present.

@lmazuel if you're sync'd up to master and python's not adding `Client`, ping me and I'll look into it.

**Comment by lmazuel** [comment]
@fearthecowboy I confirm with build 20161212 that it does not work

**Comment by olydis** [comment]
@fearthecowboy @amarzavery Maybe I get the PR wrong but I see the fix in https://github.com/fearthecowboy/autorest/blob/dae3a099b0e0d90fce04df68f59662f5320347a4/src/generator/AutoRest.CSharp.Azure/CodeNamerCsa.cs#L18

So yes, the code model now consults the code namer, but the Csa one seems to be the only one doing anything smart.

**Comment by fearthecowboy** [comment]
Ah, yeah, dammit. That's Why.

The change should only affect `*Azure ` generators, so `GetClientName` has to be overridden in all the `CodeNamer??a` implementations. (and one has to be created for the ones that don't have one. 

*sigh*

And, now that I think deeper about it, there's a bit more to it. 

Leave it for today, If I can recover enough, I'll be in tomorrow, and we can finish solving this right.

**Comment by lmazuel** [comment]
@amarzavery but the spec hasn't, so moving to the new spec is not possible for now.

**Comment by lmazuel** [comment]
@amarzavery we cannot touch the spec without asking the Storage team first, and this is a local workaround (not a bug fix, there is no bug in the spec). And this doesn't change the fact that currently C# code is generating something different than other languages by default.
If we have the opportunity to make it right correctly, we should take it.
My two cents.

**Comment by lmazuel** [comment]
@amarzavery but as a Azure SDK for Python package manager guy, I agree either way works. As long as Autorest is generating the right client, this side of me is happy :)

**Comment by lmazuel** [comment]
Any news here? Now [the storage package is out](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/6.0.0-preview), and this is still a problem for Python. Either we use solution from @amarzavery and change the Swagger, or from @fearthecowboy and make Autorest more homogeneous (I prefer that one). But please tell me it's not already forgotten in the Github tracker :)

**Comment by fearthecowboy** [comment]
Before we jump into anything, let's bring it up for discussion at the next meeting.

**Comment by annatisch** [comment]
@fearthecowboy, @lmazuel,
So it seems we have concluded to behave consistently across languages, and that ideally this should be moved to the core :)

**Comment by fearthecowboy** [comment]
Yes, I'll do that. 

I'm going to have to add in some sort of `azure` mode for generators so we can do this in the core when we know it's for Azure.

**Comment by lmazuel** [comment]
@fearthecowboy any update on this one?

**Comment by fearthecowboy** [comment]
Sorry, I've been in the middle of XmlSerialization stuff. Lemme see if I can get to it this afternoon.

**Comment by lmazuel** [comment]
@fearthecowboy No problem :)

**Comment by fearthecowboy** [comment]
We'll have to work around this in the short term. I'm adding in the `Azure-ARM` flag when we do configuration, which is coming shortly.

**Comment by fearthecowboy** [comment]
IIRC this is done.
