### ISSUE TITLE
Type issues in generated C# code

### ISSUE THREAD

**Issue by Serjster** [Azure/autorest#1648]
I just tried using the latest 0.173 version of the client generator for C# and have these problem with the generated code:

```
foreach (var _item in thingIDs)
{
    _queryParameters.Add(string.Format("thingIDs={0}", System.Uri.EscapeDataString(_item ?? string.Empty)));
}
```

The errors are on that  **_item ?? string.Empty**
The error messages are:

> Operator '??' cannot be applied to operands of type 'long?' and 'string'

and

> Argument 1: cannot convert from 'object' to 'string'

**Comment by fearthecowboy** [comment]
Yeah, that shouldn't be.

Can you post the swagger that you used to generate that? 

I just want to make sure I have a solid repro.

**Comment by Serjster** [comment]
Well... so I tried. Unfortunately, this service is in very rapid development right now the client it generates now doesn't have this issue. I tried branching off the last PR from the day before this post and now can't get the service to run... so I've given up... sorry. I will let you know if I come across this problem again.

**Comment by fearthecowboy** [comment]
Ok.. That's fine.

In the `1.0.0-nightly` series of AutoRest, we have a whole overhaul of the internal type system, so it's possible that we have solved this entirely differently too. 

I'll close this for now, but if you have it come back, post a repro and reopen it.

**Comment by chsienki** [comment]
I'm able to repro this issue in 1.0.0-Nightly20161229

Below is a simple repro swagger file that demonstrates the issue.

``` javascript
{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "title"
    },
    "host": "localhost",
    "schemes": ["http"],
    "paths": {
        "/test": {
            "delete": {
                "tags": ["test"],
                "operationId": "deleteTest",
                "consumes": [],
                "produces": [],
                "parameters": [{
                    "name": "ids",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uuid",
                        "x-nullable": false
                    },
                    "collectionFormat": "multi",
                    "x-nullable": true
                }],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
    },
    "definitions": {

    }
}
```
