### ISSUE TITLE
[C#] Can't set Timeout from generated I***Client interface

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1651]
Currently `ServiceClient`-derived classes generated by AutoRest implement two separate interfaces, `IAzureClient` which lives in `ClientRuntime.Azure`, and the generated interface that has the operation group properties.

The problem with this is that sometimes client code needs to manipulate the `HttpClient` property (e.g. -- by setting the `Timeout`), but it is only accessible by down-casting to the generated `ServiceClient`-derived class. For an example of this class of problem, see this issue: https://github.com/Azure/azure-sdk-for-net/issues/2604

To avoid this undiscoverable cast, would it be possible to have AutoRest generate interfaces that derive from `IAzureClient` instead?

**Comment by fearthecowboy** [comment]
There is work coming from the storage team for creating a much nicer high-perf customizable pipeline for http.  This will likely be leveraged in the v.Next client and generators
