### ISSUE TITLE
Latest 1.0.0 AutoRest does not ifdef System.Security.Permissions

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1659]
In the latest 1.0.0 version of AutoRest, custom exceptions do not properly wrap the using for System.Security.Permissions, which is not supported in CoreCLR (portable). In previous versions, this generated code looked like this:
```
#if !PORTABLE 
    using System.Security.Permissions;
#endif
```

Now it is simply this:
`using System.Security.Permissions;`

Which results in the following exception when building for portable/CoreCLR:
```
The type or namespace name 'Permissions' does not exist in the namespace 'System.Security' (are you missing an assembly reference?)
```

**Comment by fearthecowboy** [comment]
Ach! 

This turns out to be a side effect of the C# simplifier. I will look into this today.

G

**Comment by fearthecowboy** [comment]
@begoldsm  you should be able to disable the c# simplifier step with  `-DisableSimplifier ` ... could you try that?
