### ISSUE TITLE
[C#] AutoRest does not emit <see> links for operations

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1671]
Currently AutoRest will generate `<see>` links for model classes and properties, but not for operation methods.

**Comment by olydis** [comment]
Hmmm, I just ran the https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore-with-external-docs.json (has `externalDocs` set on an operation) through AutoRest and I see 
```
/// <summary>
/// Returns all pets from the system that the user has access to
/// <see href="https://swagger.io/about" />
/// </summary>
```
in front of said operation. On the other hand, I see zero effect for the root-node `externalDocs` property so something is indeed missing...

Do you mean that or have an example? :-)

**Comment by brjohnstmsft** [comment]
I was looking at some generated code from the Search SDK, but I must have been looking in the wrong place because I see the links now. Sorry for the noise. Closing this.
