### ISSUE TITLE
Custom Exceptions and Messages

### ISSUE THREAD

**Issue by twitchax** [Azure/autorest#1679]
If a descriptive exception thrown by an underlying provider is uncaught, the resulting stack is pretty hard to debug, since it looks something like this:
 
Microsoft.Azure.Management.DataLake.Store.Models.AdlsErrorException: Operation returned an invalid status code 'NotFound'
 
Is there some way for me to specify that the nested "message" property should be included in the top level message of the exception when it is thrown? Would I be able to make this happen if I used x-ms-flatten or something similar?

**Comment by fearthecowboy** [comment]
@twitchax -- I don't think there's much we can do right now, but I think we might be able to make something better in the AutoRest 2.0 timeframe (spring-ish). 

This is kindof tied to #1523 in that we need to be able to clearly specify `error` return codes and generate appropriate exceptions for them.

**Comment by twitchax** [comment]
@fearthecowboy, makes sense: thanks for the response!
