### ISSUE TITLE
[Python] Generate incorrect "strPaged" class name

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1685]
The new Autorest (means, after latest big refactoring) is incorrectly generating paged operation of strings for the IoTHub client:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-iothub/2016-02-03/swagger/iothub.json

This generates "strPaged" and not "StrPaged" as expected (cause of issue https://github.com/Azure/azure-sdk-for-python/issues/920). I[ manually fixed the code for now](https://github.com/Azure/azure-sdk-for-python/pull/921/commits/cb305426306f4e737ed8414b484621bdba9aa312) to unlock the issue, but needs to be fixed inside Autorest itself.

I added extensive unittests in Python for IoTHub, so I can catch any bad new generation of the client while this issue is not fixed.

FYI @annatisch @fearthecowboy

**Comment by annatisch** [comment]
@lmazuel - thanks! Is it okay if I take a look in the New Year?

**Comment by lmazuel** [comment]
@annatisch what a good way to start a year indeed :)
