### ISSUE TITLE
[Python] DocString should respect parameter order

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1690]
Example, this is incorrect:
![image](https://cloud.githubusercontent.com/assets/1050156/21372493/41e4fe5a-c6cc-11e6-834d-f2d1e64b928b.png)

The right order of parameters in the DocString is:
- Credentials
- adla_job_dns_suffix
- api_version

I guess it's because required parameters are moved to the start of the method signature. Created confusion with a customer (and me :) ).

FYI @annatisch

**Comment by fearthecowboy** [comment]
@lmazuel  - is this still an issue? Reopen if it needs to  be tracked.

**Comment by lmazuel** [comment]
@fearthecowboy Please re-open this one, I don't have the necessary permission to do it.

**Comment by lmazuel** [comment]
We reduced the number of parameters, making this problem disappeared by itself.
