### ISSUE TITLE
C#: Use fully qualified type names in generated code

### ISSUE THREAD

**Issue by Osipion** [Azure/autorest#1696]
Autorest by default generates C# clients with methods like the following:

```csharp
Task<HttpOperationResponse<string>> GetGreetingWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

However, it can also generate types with names that conflict with system types - this swagger:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "MyClient",
    "version": "1.0.0"
  },
  "host": "swaggersample.azurewebsites.net",
  "paths": {
    "/api/HelloWorld": {
      "get": {
        "operationId": "GetGreeting",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "GETs a greeting.",
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        }
      }
    }
  },
  "definitions":{
    "task": {
      "properties": {
        "prop1": {
          "type": "string"
        }
      }
    }
  }
}
```

produces the following API method:

```csharp
Task<HttpOperationResponse<Task>> GetGreetingWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

Which makes `Task` ambiguous.

I recommend using fully qualified type names (e.g. System.Threading.Tasks.Task) for both autogenerated models and other types referenced by the assembly to avoid this.

Verified with latest Chocolatey package (v0.16.0)

**Comment by fearthecowboy** [comment]
The latest chocolatey package isn't the latest AutoRest... changes to the build system broke the way the chocolatey binary was created, and I'm not going to get back to that until later in January.

Currently, if you want to get the latest stable binary, you can install it from NuGet with : 

``` 
NuGet.exe install AutoRest -outputdirectory c:\autorest 
```

or the latest nightly:

```
NuGet.exe install AutoRest -source https://www.myget.org/F/autorest/api/v3/index.json -prerelease -outputdirectory c:\autorest 
```

WRT to the problem that you're reporting, we actually did change it to generate full qualified names, (and then in recent nightlies, we use Roslyn to do the simplifying. This should give the best of both worlds.

**Comment by olydis** [comment]
whoops, doesn't work for me in the latest build! Maybe we don't generate the fully qualified name before going to Roslyn?

**Comment by Osipion** [comment]
Thanks!
