### ISSUE TITLE
Suport (non-)nullability of return types

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1710]
- review the current default behavior of C#'s  code gen (it generates primitive return types as nullable, other generators don't)
- allow `x-nullable` on responses

**Comment by brjohnstmsft** [comment]
:+1:

**Comment by mieliespoor** [comment]
Yes this is a must. We can't use this at the moment because of this issue - we would need to make too many code changes.

**Comment by dsgouda** [comment]
Fixed here https://github.com/Azure/autorest/commit/bc2c58df08ee5ebabe254d99a36eb712f4a33df3
