### ISSUE TITLE
NullReferenceException in ResponseRefConverter

### ISSUE THREAD

**Issue by michael-x** [Azure/autorest#1721]
Deserialization of a swagger.json file may result in a NullReferenceException when `ResponseRefConverter.ReadJson` tries to read an empty object.

```csharp
        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            JObject jo = JObject.Load(reader);
            string referencePath = null;
            // Unwrap if it's a reference object
            if (jo.First.Path == "$ref")
            {
                ...
            }
            ...
```

The `if` statement should read

```csharp
            if ((jo.First != null) && (jo.First.Path == "$ref"))
```

Whether an empty object here makes sense at all is another agenda, but I don't think that AutoRest should throw here (at least not without giving guidance on what went wrong).

To work around the issue, one can add a description to each operation, which would be required anyways.

**Comment by fearthecowboy** [comment]
@olydis ... I thought we fixed this? Or is this another one the same?

**Comment by michael-x** [comment]
There is another issue #1391 with a very similar description (also a `NullReferenceException` in the  `ResponseRefConverter`), but I don't think it had anything to do with an empty `OperationResponse`.

**Comment by fearthecowboy** [comment]
Ah, the perils of inheriting a code base. 

Thanks for the find @michael-x , I'll get this in today.
