### ISSUE TITLE
[Python] AddCredentials=True using "Python" generator lost credentials

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1723]
Using Python generic generator, Autorest generates
```python
self._client = ServiceClient(None, self.config)
```
instead of 
```python
self._client = ServiceClient(self.config.credentials, self.config)
```

See this diff as example, which is a client with only change is AddCredentials from true to false.
https://github.com/lmazuel/azure-sdk-for-python/commit/9b122f6b89bc45dd6bcd824d93717641180b6072

Discussed with @annatisch already

**Comment by fearthecowboy** [comment]
Is this still an issue? Can we close this?

**Comment by lmazuel** [comment]
@fearthecowboy Since it's Python not-ARM generator, I don't use it a lot and need to confirm.

**Comment by lmazuel** [comment]
Not a problem anymore
