### ISSUE TITLE
Question: Is there a way to share classes between client and server?

### ISSUE THREAD

**Issue by mpoettgen** [Azure/autorest#1730]
I guess the main usage for AutoRest is to consume APIs for which you only have a swagger.json file to begin with. However we are thinking about using AutoRest for internal APIs. For those we would already have the classes that are used to transfer the data and could share those between client and server in a separate assembly.

In our workflow we would first write an ASP.NET Core Web API, use Swashbuckle/Swagger UI to test it and then run AutoRest to generate the client. Is there a way to generate the API client without generating the classes? Could this work at all? (There was a similar feature in Visual Studio to generate Clients for Web Services re-using types from assemblies quite a while ago.)

**Comment by fearthecowboy** [comment]
There is; but it's not as good as idea as you'd think it it would be.

You can use the extension `x-ms-external` to not generate a given class, but they'd have to be pretty damn precisely exactly what AutoRest would generate (since all the methods and client runtime have some expectations as to what the names would be.)

There's really not a lot of direct value in sharing types between the client and server, since part of the point here is that the client doesn't need anything other than the contract with the server. 

Now, that being said, we're starting to experiment generating Server-side code from the same swagger (so, given the swagger interface definition, we generate AspNetCore controllers for the service)

**Comment by mpoettgen** [comment]
Thanks for the quick reply. It's good to see that there is something in the direction I was looking, but I can't get my head around to how that is supposed to work. Imagine you've got multiple clients for your API. Some may want to use a pre-compiled client API so that they don't need to concern themselves with the generation of a client API. This might be the same client library that you use internally, so you want to use the same types as on the server. Other clients may not be able to or want to use your client library, so they would want to use the swagger to create their own client. In one case x-ms-external would have to be set to true, in the other it would have to be set to false. How do I do that without changing the swagger? Wouldn't a command line option be better to switch the behavior?

The benefit of sharing the same types is that of choice: I can implement a service either 'locally' (consumed directly) or 'remotely' (consumed via an API) without having to map between local and remote types.

Let's say you've got an ICalculator.Calculate(ArtithmeticProblem problem). You could implement that by creating a Calculator class that solves the problem or by implementing an API client that invokes the Calculator via an API that runs on a much more powerful machine.

**Comment by fearthecowboy** [comment]
So, we are about to add in per-language configuration into AutoRest in a separate file so you don't have to pollute the swagger with stuff like x-ms-external.

Should be ready to start playing with in a couple weeks.

**Comment by mpoettgen** [comment]
How would you know the proper namespace of the classes that you would like to re-use? When I delete the automatically generated types I also need to add the proper 'using' statements. Otherwise than that this seems to work quite well to the degree that I've tested it.

**Comment by fearthecowboy** [comment]
In the current version, there isn't a way to indicate the namespace the type would be in.

That's on my list of things to fix; ideally, it would be possible to cherry-pick types individually from any namespace, and not have them in a specific namespace. 

This should be possible with the upcoming per-language-configuration support.

**Comment by mpoettgen** [comment]
Sounds good. Keep up the good work and shout, if you need a hand.

**Comment by mpoettgen** [comment]
Just thinking: Would it make sense to define extensions like x-dotnet-name, x-java-name, x-ruby-name, x-python-name, ... to offer a type name to the code generator? If the code generator knows the extension it would act like x-ms-external, but would also use the name specified in the x-...-name attribute.

The following example would define full type names for the "Product" in a .NET and in a Java library:

```json
{
  "definitions": {
    "Product": {
      "x-dotnet-name" : "Company.Catalog.Product",
      "x-java-name" : "com.company.catalog.product",
      "properties": {
        "product_id": {
          "type": "string"
        },
        "product_name": {
          "type": "string"
        }
     }
  }
}
```

This would greatly simplify an implementation your end. A swagger generator like Swashbuckle could use the original type name to add the x-dotnet-name (you can easily hook into the Swashbuckle Swagger Generator [using schema filters](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#schema-filters)) and if the author also provides a Java or whatever implementation he can look up or generate alternative type names as well.

**Comment by fearthecowboy** [comment]
>> Would it make sense to define extensions like x-dotnet-name, x-java-name, x-ruby-name, x-python-name 

Oh hell no ! 😄 

The per-language config work that's going on right now allows for the user to specify per-language settings of things like `client-name` and whatnot. Stay tuned.

**Comment by michael-x** [comment]
But how does the config know which types to use? Wouldn't that be something that is easier to find out for the swagger generator (if it is created by e.g. Swashbuckle Swagger-Gen) or the author of the Swagger file (if it is created 'manually' or in an editor). Trying to 'guess' could yield unexpected results where type names are not really unique. Putting more specific information into the per-language config (assuming that this is a configuration file for AutoRest) causes more work for the consumer of the API who then needs to find out which types are appropriate.

**Comment by fearthecowboy** [comment]
> But how does the config know which types to use? Wouldn't that be something that is easier to find out for the Swagger generator (if the Swagger file is created by e.g. Swashbuckle Swagger-Gen) or the author of the Swagger file (if it is created 'manually' or in an editor). 

It's not guessing, it's just not going to be in the swagger itself. The configuration file has the ability to have different settings for different languages. So you get the effect of `x-dotnet-name`, `x-java-name` etc, without having to pollute the swagger (which should describe the wire protocol, and generally not have a lot of 'code-gen' settings smashed throughout.

> Trying to 'guess' could yield unexpected results where type names are not really unique. 

Autorest does name disambiguation internally during type creation.

> Putting more specific information into the per-language config (assuming that this is a configuration file for AutoRest) causes more work for the consumer of the API who then needs to find out which types are appropriate.

Only if you specifically override them separately.  Generally, it will be pretty damn consistent between languages.

**Comment by mpoettgen** [comment]
Do you have a concept paper or anything (Wiki page, blog post, ...) that would describe how you envision the per-language-config that you are working on? Would be nice to see, whether that solves the problem.

**Comment by fearthecowboy** [comment]
Not quite finished the overview. I'm trying to finish writing it up and make some examples this week.
