### ISSUE TITLE
[Go] Reserve namespace

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1734]
Is it necessary to add the package name to the reserved words list? AFAIK, the namespaces is only useful in the namer to avoid golint stuttering.

**Comment by salameer** [comment]
This wil be released in this milestone v9.0.0-beta-20170228
https://github.com/Azure/azure-sdk-for-go/milestone/6

**Comment by olydis** [comment]
@mcardosos any updates about this?

**Comment by mcardosos** [comment]
This fixed :D
