### ISSUE TITLE
[Go] Use code from the core

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1735]
Some lines in the Go generator are duplicating code from the core, [example](https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.Go/Model/ParameterGo.cs#L19).

**Comment by salameer** [comment]
This wil be released in this milestone v9.0.0-beta-20170228
https://github.com/Azure/azure-sdk-for-go/milestone/6

**Comment by marstr** [comment]
Fixed in #2033
