### ISSUE TITLE
Nuget Install fails for UWP 

### ISSUE THREAD

**Issue by daronyondem** [Azure/autorest#1737]
Just getting the error below trying to add the ClientRuntime v.2.3.4 package into a UWP app targeting Build 14393.

Restoring packages for C:\path\project.json...
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).

This looks like related; https://github.com/StefH/System.Linq.Dynamic.Core/issues/33

**Comment by fearthecowboy** [comment]
As far as I'm aware ahead-of-time isn't supported by some of the things that the dotnet rest client runtime needs.

You should really file this with the sdk-for-net project - https://github.com/Azure/azure-sdk-for-net/issues - they may be able to help you more than we can. (They own the dotnet rest runtime client)

**Comment by daronyondem** [comment]
Just did. Thanks.
