### ISSUE TITLE
[Python] Autorest generates a method signature with twice the same parameter

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1738]
This creates invalid code:
```python
    def resend_request_emails(
            self, resource_group_name, name, name=None, custom_headers=None, raw=False, **operation_config):
        """Verify domain ownership for this certificate order.
        Verify domain ownership for this certificate order.
        :param resource_group_name: Name of the resource group to which the
         resource belongs.
        :type resource_group_name: str
        :param name: Certificate order name
        :type name: str
        :param name: Name of the object.
        :type name: str
```
Based on the docstring, it seems there is two differents objects that wants the same parameter name, but obviously it not possible.

Generated with latest Autorest (20170114) and [WebApp composite client](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/compositeWebAppClient.json). Method is [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/AppServiceCertificateOrders.json#L589):
```json
       "parameters": [
          {
            "$ref": "#/parameters/resourceGroupNameParameter"
          },
          {
            "name": "name",
            "in": "path",
            "description": "Certificate order name",
            "required": true,
            "type": "string"
          },
          {
            "name": "nameIdentifier",
            "in": "body",
            "description": "Email address",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NameIdentifier"
            }
          },
...
    "NameIdentifier": {
      "description": "Identifies an object.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the object.",
          "type": "string"
        }
      }
    },
```

Python code is [here](https://github.com/lmazuel/azure-sdk-for-python/blob/web_app_composite/azure-mgmt-web/azure/mgmt/web/operations/app_service_certificate_orders_operations.py#L940).

Autorest cmd line:
mono /tmp/tmpwl8glpmr/autorest/tools/AutoRest.exe -i /git-restapi/arm-web/compositeWebAppClient.json -o /tmp/tmpwl8glpmr/compositeWebAppClient.json -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Modeler CompositeSwagger -Namespace azure.mgmt.web -PackageVersion 0.31.0 -ft 2

FYI @annatisch @fearthecowboy @yugangw-msft

**Comment by annatisch** [comment]
So this appears to be caused by use of parameter flattening, which is exposing the duplicate names.
@fearthecowboy - is this something that is supposed to be handled in the core or the generator?

**Comment by lmazuel** [comment]
@fearthecowboy any update?

**Comment by fearthecowboy** [comment]
This would have been handled in the core; duplicate names get disambiguated pretty early.

I think that it's sneaking by because of auto flattening which happens later.  (which happens quite a bit later. )

I'm going to have to debug into this and see why it's not getting caught when the params are added back into the collection.

**Comment by fearthecowboy** [comment]
I um... am unable to repro this.

I pulled from master this morning, rebuilt and ran the generator:

` .\src\core\AutoRest\bin\Debug\net451\win7-x64\AutoRest.exe -input https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/compositeWebAppClient.json -CodeGenerator Azure.Python  -modeler CompositeSwagger`

and for that method, I got: 

``` python

def resend_request_emails(
            self, resource_group_name, name, name_identifier, custom_headers=None, raw=False, **operation_config):
        """Verify domain ownership for this certificate order.

        Verify domain ownership for this certificate order.

        :param resource_group_name: Name of the resource group to which the
         resource belongs.
        :type resource_group_name: str
        :param name: Certificate order name
        :type name: str
        :param name_identifier: Email address
        :type name_identifier: :class:`NameIdentifier
         <compositewebappclient.models.NameIdentifier>`
        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the
         deserialized response
        :param operation_config: :ref:`Operation configuration
         overrides<msrest:optionsforoperations>`.
        :rtype: None
        :rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
         if raw=true
        :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`
        """

```

I'm not sure why you might be seeing what you are seeing...

![image](https://cloud.githubusercontent.com/assets/133736/22473487/f4dbd31c-e78d-11e6-8183-434d778ffc62.png)

**Comment by lmazuel** [comment]
Hi @fearthecowboy .

You need the "-ft 2" parameter. Retested this morning bug still in there :(

**Comment by fearthecowboy** [comment]
Ah. Ok, that'll help.

Back on it!

**Comment by fearthecowboy** [comment]
Ah. Found it. Fixed it. 

Um, so when disambiguation kicks in, it renames the second `name` parameter to `name1` . 

Is that what's desired?

I guess the final solution is to modify the swagger with `x-ms-client-name`?

G

G

**Comment by lmazuel** [comment]
Hum... Yes "name1" is not ideal... So yeah, should be renamed somewhere. But will be breaking for release WebApp client :(

**Comment by lmazuel** [comment]
At least, it's valid Python code, that's the most important. :)
