### ISSUE TITLE
Question: Why are all of the operations appended with "WithHttpMessages"?

### ISSUE THREAD

**Issue by JimmyTheChimp** [Azure/autorest#1739]
The documentation shows nice function names like "client.GetPets()" and "client.GetPets()", but when I run the generator all of my functions are along the lines of "client.GetWithHttpMessagesAsync()".

**Comment by fearthecowboy** [comment]
You should see an extensions class that has the `.GetPets() ` as an extension method for the service you generated. it is the convenience method on top of the generated implementation

**Comment by JimmyTheChimp** [comment]
Aha! Knew I had to be missing something simple. Thanks
