### ISSUE TITLE
Question - lifetime management of ServiceClient?

### ISSUE THREAD

**Issue by theo-albers** [Azure/autorest#174]
How should the lifetime of the ServiceClient be managed in an Azure server app like WebJobs or ASP.NET Web API site? In essence the ServiceClient is a wrapper around HttpClient. Disposing the HttpClient results in unexpected behaviour (random connection issues). Articles like this http://chimera.labs.oreilly.com/books/1234000001708/ch14.html#_httpclient_class suggest using a single HttpClient per application (AppPool?), so effectively one per base URI. You would assume that the ServiceClient would map to a single instance as well in that case for best network efficiency. 
Is there any guideline how the typed ServiceClient should be used in a server application doing REST calls?

**Comment by markcowl** [comment]
@theo-albers It depends on what kind of credential you are using and whether you are doing work on behalf of individual users.  HttpClient could have the same lifetime as your application if there is no authentication involved.  If doing user authentication, you would need to have one client per user session.

Is this the kind of advice you are looking for, or do you want more specific recommendations for asp.net?

**Comment by theo-albers** [comment]
Thanks for the feedback. What I wondered about if it's necessary to keep track of service clients (read: HttpClient)  in a static dictionary to avoid the underlying TCP connection overhead. So in a typical Web API server request / response model, would we be better of to create the service client on each request and let the GC dispose it, or should we share a single client across requests?
It's not really clear to me what goes on under the hood of HttpClient ;)

**Comment by markcowl** [comment]
Creating an httpClient is a fairly heavyweight process.  The standard advice is to share them across requests where possible. Closing for now, please reopen or file a new issue if you have additional questions.
