### ISSUE TITLE
setup-developerworkstation.ps1 does not install all needed packages for Android

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1741]
Following the instructions to configure my machine to build Autorest, it fails on Android
```console
* Where:
Build file 'D:\VSProjects\autorest\src\client\Java\azure-android-client-authentication\build.gradle' line: 105

* What went wrong:
A problem occurred evaluating project ':azure-android-client-authentication'.
> failed to find target with hash string 'android-23' in: C:\Users\lmazuel\AppData\Local\Android\android-sdk
```
Actually, after executing the setup-developerworkstation.ps1, I got Android SDK 24.4.1. This was the last one in Chocolatey when I executed the setup: https://chocolatey.org/packages/android-sdk
but the gradle file asks explicitly for 23:
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.0-beta3"
    }
```

@fearthecowboy @amarzavery

**Comment by lmazuel** [comment]
Seems actually that the "client" sub-folder is not existing anymore, guess I misunderstood something, abused by .gitignore and my ignorance.
Close for now, sorry for the noise.

**Comment by amarzavery** [comment]
@cormacpayne - Can you please take a look at this issue?

**Comment by lmazuel** [comment]
I upgraded a little the issue title, finally figured out that I have to install the following packages with "Android SDK Manager" myself:
- Extras - Android Support Repository
- Android 6.0 (API23) - SDK Platform
- Android 6.0 (API23) - Google APIs

So the setup script is not installing all the needed stuffs. Even though I'm not blocked anymore, still thing the script needs an update.

**Comment by fearthecowboy** [comment]
This isn't @cormacpayne's script, it's mine.

And I believe that the Java build was just changed to not need preinstallation of the android stuff, it pulls it in from maven now. right @jianghaolu ?

(I'm updating the script this week to fix a couple other bugs)

**Comment by jianghaolu** [comment]
Correct. In fact, there's no need for your `D:\VSProjects\autorest\src\client\Java` directory anymore. The runtime is now pulled from published bits. 

Ahh the issue was from 5 days ago. Many things can change in 5 days. Please pull from the latest master and see if android is magically not required anymore.
