### ISSUE TITLE
[Go] Generator for composite swaggers is not including API version

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1746]
Try to generate the network or the compute composite swaggers.

**Comment by salameer** [comment]
This wil be released in this milestone v9.0.0-beta-20170228
https://github.com/Azure/azure-sdk-for-go/milestone/6

**Comment by marstr** [comment]
Fixed in PR #2080

**Comment by marstr** [comment]
Done.

**Comment by TamalSaha** [comment]
@marstr , does this mean composite swaggers are now supported?

**Comment by marstr** [comment]
Yep!

For V9, we're releasing web as generated from it's composite swagger. In v10 we will have validated the rest of the composite swaggers and moved to that model.
