### ISSUE TITLE
Create Api for each controller

### ISSUE THREAD

**Issue by piniSolomon** [Azure/autorest#1747]
Hey guys,
Great tool and I find it very useful .
One thing I am missing is to separate the Service Client to different services according to the controller,
I mean ServiceClient for each controller in the swagger file.

**Comment by fearthecowboy** [comment]
AutoRest creates a single client per swagger file. If you want individual service clients, you need to split up the swagger.

I'm not sure why you'd want separate clients, AutoRest does generate separate operation classes for each group of operations (denoted by an underscore in the `operationId` -- ie, `blob_list`, `blob_get`, `blob_delete` would all be on a `Blob` class with methods `List`, `Get`, `Delete` )

**Comment by piniSolomon** [comment]
hey @fearthecowboy 
thanks for the quick response.
In my team we are going to develop a large system with many controllers each controller can be different module in the system and we don't want the client team to be overwhelmed with a single API with many operations in it. let's not forget that each operation has the async version which is very good but doubles the API.

**Comment by fearthecowboy** [comment]
Right, I get that. 

The APIs are broken up into separate classes according the the prefix in the `operationId` -- we do this with Azure services all the time.  

The Service Client ties together the APIs and allows you to consolodate the authentication, but individual API sets are broken up into classes. 

Can I see your swagger file, and I can perhaps help you with that?

**Comment by piniSolomon** [comment]
The swagger file is still work in progress... But I didn't understand you say you can split the client or you suggest I use the inner classes in the api?

**Comment by fearthecowboy** [comment]
Not inner classes.

When you write the swagger, each item in `paths` has to specify an `operationId` that is used to generate the class/method name :

``` yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
paths:
  /my/operation:
    get:
      operationId: my_operation # LOOK HERE
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TestObject'
definitions:
  TestObject:
    properties:
      pattern:
        type: string
        default: '\w+'
```

AutoRest by convention, takes the `operationId` and splits it at the underscore, and uses the first thing as the operations class name, and the rest as the method.

So, `my_operation` creates a `My` operations class with a method `operation`.

If you don't do that, it'll put all the methods into the generated service client class

**Comment by piniSolomon** [comment]
Ok got it, sounds great I will give it try later on...
And again thanks for the quick and useful replays.

**Comment by piniSolomon** [comment]
Great I can say that worked as expected.
also with swashbuckle I created the operations with the name of the api action and the controllerName with underscore as you said before -> {controllerName}_{actionName}
and I got a very good looking APIs.
Thank you for all the help.
