### ISSUE TITLE
Not creating models

### ISSUE THREAD

**Issue by piniSolomon** [Azure/autorest#1750]
Hey,
Is there a way for autoRest to not create models and somehow use my own models from the server?
Let's say I have server and client written in c# and my models are shared with the client, can I make autorest use those models and not generate them?

**Comment by olydis** [comment]
Hi, there is indeed functionality for that:
https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-external
In short, marking a model as `"x-ms-external" : true` will suppress generation. 

Of course, note that other parts of the generated code (specifically the REST calls) may rely on the very model structure AuroRest *would* have generated (i.e. spelling of properties, etc.). If your "personal" models don't match these expectations, stuff may not compile or (worse) JSON serialization may fail at runtime (trying to write into a "Foo" property, while your model has property "foo"). However, you should be able to mirror your personal models precisely using Swagger, so generated code knows what to expect.

**Comment by olydis** [comment]
I'll close this, as there is indeed functionality for what you want, but feel free to add any further questions or problems you encounter!
