### ISSUE TITLE
autorest extensions x-ms-external

### ISSUE THREAD

**Issue by piniSolomon** [Azure/autorest#1752]
Hey,
I am trying to generate a client without models I want to use my own.
I have added the 'x-ms-external' in the [swagger file](https://github.com/Azure/autorest/files/732529/swagger.txt)
and when generating the C# client the model (Mission model) is still being generated and the missions api is referencing the generated model.
* also I tried to manually add a model to the swagger def. with the 'x-ms-external' and the model was still generated by auto rest.
* Can you tell me what I am missing in the swagger file to not generate the models and reference my own models?

**Comment by fearthecowboy** [comment]
I'm not able to reproduce that with AutoRest.  (Did you delete the previously generated files before generating again?)

``` batch 
C:\work\github\tmp\issue> AutoRest -input .\swagger.yaml -CodeGenerator CSharp 
The Microsoft.Rest.ClientRuntime.2.2.0 nuget package is required to compile the generated code.

C:\work\github\tmp\issue> dir /s/b .\Generated\
C:\work\github\tmp\issue\Generated\APIV1.cs
C:\work\github\tmp\issue\Generated\Example.cs
C:\work\github\tmp\issue\Generated\ExampleExtensions.cs
C:\work\github\tmp\issue\Generated\IAPIV1.cs
C:\work\github\tmp\issue\Generated\IExample.cs
C:\work\github\tmp\issue\Generated\IMissions.cs
C:\work\github\tmp\issue\Generated\ISelf.cs
C:\work\github\tmp\issue\Generated\Missions.cs
C:\work\github\tmp\issue\Generated\MissionsExtensions.cs
C:\work\github\tmp\issue\Generated\Self.cs
C:\work\github\tmp\issue\Generated\SelfExtensions.cs

```

What version of AutoRest are you using?

**Comment by piniSolomon** [comment]
hey,
the version I'm using is 0.17.
I'm attaching 2 screenshots for you to see the command line and the output
![autorestexternal1](https://cloud.githubusercontent.com/assets/25340091/22348656/3fea1098-e415-11e6-896a-fe6ee7411466.jpg)
![autorestexternal2](https://cloud.githubusercontent.com/assets/25340091/22348657/3ff6e714-e415-11e6-8446-b1f8fa9d4b63.jpg)

the only difference I can see is that you used the yaml version of swagger input, I will try to convert my swagger json to yaml and give it a try, and will post the results soon.
thanks for the response

**Comment by fearthecowboy** [comment]
YAML doens't make a difference.

Try grabbing the latest nightly (use nuget 3.3 or greater!) : 

```
NuGet.exe install AutoRest -source https://www.myget.org/F/autorest/api/v3/index.json -prerelease -outputdirectory c:\autorest 
```

**Comment by piniSolomon** [comment]
well, grabbed the latest from nuget and still the same result.
Any suggestions?

**Comment by piniSolomon** [comment]
Hey @fearthecowboy 
Can you please send me the yaml you used to generate the client with it?
and please send me the generated output you got  so I could compare them

**Comment by fearthecowboy** [comment]
Here is precisely what I've got:

You can run the exact same things from powershell:

``` powershell
mkdir c:\test
cd c:\test

# Grab the last nightly build
Invoke-WebRequest https://www.myget.org/F/autorest/api/v2/package/AutoRest/1.0.0-Nightly20170131 -out autorest.zip

# Unzip it here
Expand-Archive .\autorest.nupkg

# Run autorest on your swagger
.\autorest\tools\AutoRest.exe -input https://github.com/Azure/autorest/files/732529/swagger.txt -CodeGenerator CSharp -Namespace Test

# check what got created (no models!)

C:\test> dir .\Generated\


    Directory: C:\test\Generated


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2/1/2017   8:58 AM           5983 APIV1.cs
-a----         2/1/2017   8:58 AM           6675 Example.cs
-a----         2/1/2017   8:58 AM           1334 ExampleExtensions.cs
-a----         2/1/2017   8:58 AM           1140 IAPIV1.cs
-a----         2/1/2017   8:58 AM           1208 IExample.cs
-a----         2/1/2017   8:58 AM           3002 IMissions.cs
-a----         2/1/2017   8:58 AM           1202 ISelf.cs
-a----         2/1/2017   8:58 AM          19851 Missions.cs
-a----         2/1/2017   8:58 AM           4098 MissionsExtensions.cs
-a----         2/1/2017   8:58 AM           6657 Self.cs
-a----         2/1/2017   8:58 AM           1322 SelfExtensions.cs
```

**Comment by piniSolomon** [comment]
It seems thay after all my version of AutoRest wasn't the latest. While I got the latest version from nuget it didn't work, when you pointed me to nightly from nuget (which I'm not sure if I could download it without knowing the exact package name) it did work. 
THANK YOU @fearthecowboy 
Now that it's working what is the recommended way for adding the namespace to the generated class that use the models?
(for now I added using inside each class which will be overwritten the next time I generate the client api)

**Comment by fearthecowboy** [comment]
Alas, there isn't a way to reference a different namespace yet.

We're working on some changes that will let you affect the code generation process to do that, but for the immediate term, you'll have  to hack it... :(

**Comment by olydis** [comment]
@olydis Note to self: If we somewhat detach code generation per entity with the final packaging story (e.g. models may be reused if they are identical across API versions and such), this might be one of the things to happen in the final packaging stage. Maybe we can provide a nicer story to tie in external things in general: You (the user) *say* what other files/classes you wanna package with the generated code, that not only gives a story for external namespaces but also enables running the simplifier on "incomplete" code.

Maybe.

**Comment by fearthecowboy** [comment]
Supporting a better way to reuse types is central to the vNext generator stategy.
