### ISSUE TITLE
Inconsistent Grammar applied to Cloud Names

### ISSUE THREAD

**Issue by marstr** [Azure/autorest#1753]
As seen in Azure/go-autorest#79, @boumenot points out that there is not grammatical convention in the names: `AzureGermanCloud` and `AzureChinaCloud`. To be consistent, it would be either
 - `AzureGermanyCloud` and `AzureChinaCloud` or
 - `AzureChineseCloud` and `AzureGermanCloud`

**Comment by fearthecowboy** [comment]
I'm not sure how this is an autorest issue.
