### ISSUE TITLE
[Azure.Python] Completely re-write the folder structure of generated code

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1757]
I actually generate Python code using Autorest, but don't like the generated folder structure. So I use another template generator ([cookiecutter](https://github.com/audreyr/cookiecutter) and [this is my template](https://github.com/Azure/cookiecutter-azuresdk-pypackage)) to generate the right folder structure and I manually move the Autorest code into it.

Yuk (don't blame me too hard, when I've done that I was 1 month at Microsoft and not enough confident to write this kind of issue like today :))

I now think that I should integrate this template in Autorest, so that the actual generation of Python represent a good packaging.

Major issue is the namespace. In Python namespace are folders. So for this command to work
```python
from azure.mgmt.compute import ComputeMgmtClient
```
I need the structure:
```console
- azure
  |- __init__.py
  \- mgmt
      |- __init__.py
      \- compute
          |- compute_management_client.py
          \- __init__.py # contains an alias to compute_management_client.ComputeMgmtClient
```

currently it generates a single folder `compute_management_client`

So we need to iterate on each part of the namespace and generate one folder for each part with a `__init__.py` file (empty) in each sub-folder.

Also, the dependencies are splitted into:
- azure-nspkg
- azure-mgmt-nspkg
- msrestazure

The `nspkg` package are meta-packages that allows to install several azure packages at the same time on the same machine.

We also need this behavor in the Python generator, but I don't think we should use the `nspkg` as dependencies. Because it's a decision we made in Azure that can't be applied to any Python package.

Funny thing is that `-Namespace` is already used to generate accurate docstring in the code. This means that currently generated code documentation is not using the generated folder structure.

FYI @fearthecowboy @annatisch

**Comment by annatisch** [comment]
@lmazuel -so in summary - we want to use the --namespace to generate the folder prefix structure?
Should be pretty straight forward.

**Comment by lmazuel** [comment]
@annatisch yes that's it :).
