### ISSUE TITLE
Confusing warning about subscriptionId

### ISSUE THREAD

**Issue by michael-x** [Azure/autorest#1764]
Using the CSharp generator (last week's nightly) I get the following warning message:

> WARNING: ServiceDefinitionParameters - Parameters "subscriptionId" or "api-version" are referenced but not defined in the parameters section of Service Definition

Since I'm not using the Azure CSharp generator I probably shouldn't get a warning about the "subscriptionId". If "api-version" is the "version" in the "info" object, then that is where it should be. If it's supposed to be something else, then I don't know what I should do about it.

**Comment by fearthecowboy** [comment]
Can you post the swagger, and the command line you used? Something seems not quite correct there.

**Comment by michael-x** [comment]
Unfortunately I'm not allowed to post the swagger.
I've noticed that for #1513 / #1515 a new parameters object with properties for the subscriptionId and api-version has been added to most swagger files for testing. Looks like the ServiceDefinitionParameters and OperationParametersValidation are always applied even though the properties are Azure specific.

**Comment by fearthecowboy** [comment]
Ah. I just figured out what's going on.

we're adding in a bunch of Linting validation rules, but they are getting applied to everything. 

In a separate place, we're going to add the code to filter that stuff back out, but  that part's not done yet. 

Uh, ignore the warnings :D  (should only be a few days)

**Comment by olydis** [comment]
Validation rules are no longer applied to CSharp generation so I'll close this issue.
