### ISSUE TITLE
Linter incorrectly flags missing "description" when fields have "title"

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#1767]
`title` is a valid alternative to `description` as supported by the [official Swagger specification](http://swagger.io/specification/#schema-object-80) -- AutoRest supports both `title` and `description`, one for long form text (think C# `<remarks>`) and one for short form text (think C# `<summary>`), but the linter isn't up to date and still reports a bunch of errors if you have no description:
```
Path: #/Definitions/CloudJob
WARNING: ModelTypeIncomplete - This definition lacks the property 'description', which is required for model types
Path: #/Definitions/JobAddParameter
WARNING: ModelTypeIncomplete - This definition lacks the property 'description', which is required for model types
```

The actual linter rule should be:
1. If the type has no `title` AND no `description`, then flag a warning
2. [optional] If the type has a `description` and no `title`, could flag that they can move to `title` but that may be overkill.

**Comment by veronicagg** [comment]
related https://github.com/Azure/autorest/issues/1526

**Comment by veronicagg** [comment]
@bradygaster should this be a doc rule?

**Comment by bradygaster** [comment]
@veronicagg i don't know if it's isolated to docs. if it were would that mean my team would need to write the rule for you guys? want to understand the implications.

**Comment by matthchr** [comment]
@veronicagg @bradygaster - AFAIK, docs.msft.com generates documentation that looks like this:

`title` + `description` if there are both else `title` or `description` (whichever is there).

I filed a bug a few months back when it didn't do the above, but they have since fixed it and that's the behavior last I checked.

It would be great if we could fix this linter rule as my teams data plane (and management to a lesser extent) makes pretty extensive use of `title`, and we get probably 200+ errors related to missing descriptions which are actually not really missing, they're just in the `title`.

**Comment by veronicagg** [comment]
@bradygaster (sorry for the delay) regarding your question, not necessarily, it'd be great to have doc rules owned by your team, but at least for this one, we could put it in our list as long as we know what the right behavior to enforce is.

@matthchr if we get confirmation from Brady we can look into updating this rule.

**Comment by sarangan12** [comment]
@matthchr 

I see 2 aspects here. 

Aspect 1: How does docs.microsoft.com handles title & description? It combines both (if present) or use one of them. So, from this aspect, I do not have any issues replacing this rule to check for Title and description. You can see the PR here: https://github.com/Azure/autorest/pull/2298 (I am working on the failing build)

Aspect 2: Let us forget docs for a minute. This issue assumes 'title' & 'description' are equivalent. Is that true? In http://swagger.io/specification/#schema-object-80, can you point our where it is mentioned that they are equivalent?

**Comment by matthchr** [comment]
@sarangan12 - I didn't say Swagger said they were equivalent. They definitely _aren't_ equivalent. But both docs.msft.com and AutoRest treat them interchangeably, _and_ I don't think they are both required (do you see somewhere in Swagger or the JSON schema that suggests that they are?)

Also, note that actually `title` is a JSON artifact, as is `description` (for bodies), Swagger links to [here](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.2)

So as far as I see it:
1. They are not both required
2. We want a good docs experience, so at least one must be set.

So the question is which one must be set? And given that Swagger (AFAIK) doesn't give any real guidance here, and that AutoRest and docs.msft.com both treat description/title the same if only one is set, the answer to me seems to be that it doesn't matter which one is set as long as one is.

If you wanted to move to being more strict than that (i.e. require both), we could I suppose.

It would seem strange (to me) to say `description` is mandatory and `title` isn't though as `title` should be a short summary. If you have a long `description` you should always be able to have a short summary of it.

**Comment by sarangan12** [comment]
Task Completed
