### ISSUE TITLE
consolidate and move over extensions docs to AutoRest repo only

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1770]
Missing some extensions / examples that are present in the Swaggers [documentation](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md). ANd the same for the documentation there, it is missing stuff that is present [here](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md). Both files should be updated so they the same.

**Comment by olydis** [comment]
@mcardosos wow, wasn't even aware we have two copies of this... I'm on it

**Comment by olydis** [comment]
@olydis address #2440 in the same go

**Comment by olydis** [comment]
done in 2.0 (next stable release), will remove specs repo copy at that point
