### ISSUE TITLE
Unable to download nightly of AutoRest

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1776]
```
nuget install AutoRest -Source https://www.myget.org/F/autorest/ -pre -OutputDirectory .
```

**Error:**
```
Attempting to resolve dependency 'System.Xml.XDocument (≥ 4.0.0)'.
Unable to resolve dependency 'System.Xml.XDocument (≥ 4.0.0)'.
```

@fearthecowboy / @olydis Can i please have a fix for this as I am using nightly in travis?

**Comment by vishrutshah** [comment]
```
nuget install AutoRest -Source https://www.myget.org/F/autorest/ -pre -OutputDirectory . -Version 1.0.0-Nightly20170129
```

works so something is changed recently.

**Comment by vishrutshah** [comment]
@olydis It's coming from https://github.com/Azure/autorest/pull/1744/files#diff-d00210f49525605fff2d38480fc40abeR44 I believe.

**Comment by fearthecowboy** [comment]
I found/fixed that this morning, will be better in tonight's build.

G

**Comment by vishrutshah** [comment]
Thanks. Issue has been fixed.
