### ISSUE TITLE
Empty Strings added to Querystring from Generated Client

### ISSUE THREAD

**Issue by phil000** [Azure/autorest#1782]
The code generation is causing us a few issues.

When using querystring parameters if they are not null the generated clients add the parameter into the querystring:
```
e.g. generated code:
if (description != null)
{
     _queryParameters.Add(string.Format("description={0}", Uri.EscapeDataString(description)));`
}
```

However, this means an empty string is added into the querystring as:
`&description=`

On the server side with Web API 2.2 we get a validation error:
`A value is required but was not present in the request.`

Yes, we have the parameters with defaults (string description = null). If the parameter is not passed at all in the querystring the request is correctly dispatched to the action method and the parameter gets it's .NET default value. However, if the parameter is passed as "&description=" then we get a validation error.

Any reason for passing empty strings from the client like this?

Ta

**Comment by olydis** [comment]
Not sure what you're saying - if you pass an empty string as an argument then this empty string should absolutely be added as a query parameter, precisely as you describe! Otherwise, how are you supposed to distinguish between sending `null` and sending `""`?

Maybe I misunderstand your question. What are you expecting to happen if you pass an empty string?

**Comment by phil000** [comment]
The issue is really a problem with Web API 2.2 I guess, in that it does not like querystring parameters with no value. 
If the UTL is ?description= then the call fails to be dispatched to the action method with an error. We handle this now by making sure an empty string is not passed to the generated client. I guess we could also do something with custom binding these empty querystring values on the server differently.

**Comment by olydis** [comment]
Hmmm interesting and good to know! I think we cannot really change any of that behavior on our side, AutoRest is used to generate the Azure SDKs and... well, the Azure services can (and sometimes need to!) distinguish empty and `null`. Making this behavior customizable isn't really a high priority for us right now.

I'm no expert for Web API 2.2 but isn't it resolvable like http://stackoverflow.com/questions/34630308/asp-net-webapi-2-how-to-pass-empty-string-as-parameter-in-uri for example?

**Comment by phil000** [comment]
Having a default in the method signature doesn't work (e.g. string description = null).. We just get the error  "A value is required but was not present in the request. "

We can look into this on the web API side as AutoRest behaviour is correct.

Please close.
