### ISSUE TITLE
Dev setup should install nodejs.install

### ISSUE THREAD

**Issue by tamalsaha** [Azure/autorest#1789]
Hi,
https://github.com/Azure/autorest/blob/master/Tools/setup-developerworkstation.ps1#L59

should install `nodejs.install` so that node.exe gets added to environment variable.

See here: https://chocolatey.org/packages/nodejs.install

Thanks.

**Comment by TamalSaha** [comment]
I noticed the same issue with git. Using `git.install` adds git to the environment.

**Comment by fearthecowboy** [comment]
Yeah, I have some updates for this script. 

I'll be dropping the chocolatey installs very soon.

**Comment by olydis** [comment]
Things have changed significantly since then, even running AutoRest requires node now.
Will close, but please reopen if this is still an issue.
