### ISSUE TITLE
[Linter] TrackedResourceValidation - linter is showing a false positive

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1791]
The linter is showing a false positive over [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/199001500#L2344).

```
WARNING: TrackedResourceValidation - Tracked Resource failing validation is: DatabaseAccountCreateUpdateParameters. Validation Failed: 1. 
    A Tracked Resource must have: 
    1. A Get Operation 
    2. A ListByResourceGroup operation with x-ms-pageable extension and 
    3. A ListBySubscriptionId operation with x-ms-pageable extension.
    4. Type, Location, Tags should not be used in the properties.
	Path: #/Definitions
```

[DatabaseAccountCreateParameters](https://github.com/dmakwana/azure-rest-api-specs/blob/2a2d72c4ebdc60b42128a0c5f2aed8fd6541368e/arm-documentdb/2015-04-08/swagger/documentdb.json#L659) is used as an input to the PUT operation. It is an x-ms-azure-resource (basically a tracked resource). However, for some reason the service cannot send and get back the same model in the PUT. Therefore they have two separate models. DatabaseAccountCreateParameters is the input and DatabaseAccount is the output. The linter should verify that the output type must satisfy the above 4  conditions. Not the intput type (as it is not really a resource).

Reference: https://github.com/Azure/azure-rest-api-specs/pull/906

FYI: @amarzavery

**Comment by vishrutshah** [comment]
One more occurrence for investigation: 

Travis Job: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2343

**Comment by veronicagg** [comment]
Problems with this rule are being tracked with https://github.com/Azure/autorest/issues/1860
