### ISSUE TITLE
The published package Nuget 0.17.3 requires .NetFramework 4.5.1

### ISSUE THREAD

**Issue by L3Z4** [Azure/autorest#1794]
The previous package 0.16.0 worked with .NetFramwork 4.5.
Is it possible to compile it and publish a new official NuGet package ?

**Comment by fearthecowboy** [comment]
The build process changed *alot* between 0.16 and 0.17.  With compiler and tool changes it may not be possible. 

The next wave of AutoRest is coming forth in a few days, and it will use the dotnet standard 1.0 and automatically pull in the binaries that it needs, so you won't have to have a specific version of the dotnet framework installed.

Plus, it'll work on Windows, Linux and MacOS

Details soon!

**Comment by L3Z4** [comment]
Since it is a blocking point for us, I took the sources, change the projet.json to adress the dotnet45 framework and publish my own NuGet package on our private repo.

I'm looking forward to the standard 1.0 version !
