### ISSUE TITLE
Move "OperationStatusResponse" type into autorest runtime.

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/autorest#1802]
The latest swagger doc start to let some operations return `operation_status_response` . It is fine, but please define this type inside auto-rest run time lib, and do not let generator emit out duplicate types inside each sdk library. For reason, see 
https://github.com/Azure/azure-cli/issues/2012

{
  "endTime": "2017-02-08T18:02:31.477182+00:00",
  "error": null,
  "name": "02bdfc3f-6236-4064-9894-15b89ad6b70d",
  "startTime": "2017-02-08T18:02:20.070584+00:00",
  "status": "Succeeded"
}

//cc @johanste, @amarzavery

**Comment by fearthecowboy** [comment]
Is this something for a specific generator?
