### ISSUE TITLE
AutoRest does not deserialize error body on HTTP delete

### ISSUE THREAD

**Issue by iouri-s** [Azure/autorest#1806]
Here's the code generated for a DELETE operation:

            if ((int)_statusCode != 204 && (int)_statusCode != 202 && (int)_statusCode != 200)
            {
                var ex = new CloudException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                ex.Request = new HttpRequestMessageWrapper(_httpRequest, _requestContent);
                ex.Response = new HttpResponseMessageWrapper(_httpResponse, _responseContent);
                if (_httpResponse.Headers.Contains("x-ms-request-id"))
                {
                    ex.RequestId = _httpResponse.Headers.GetValues("x-ms-request-id").FirstOrDefault();
                }
                if (_shouldTrace)
                {
                    ServiceClientTracing.Error(_invocationId, ex);
                }
                _httpRequest.Dispose();
                if (_httpResponse != null)
                {
                    _httpResponse.Dispose();
                }
                throw ex;
            }

Here's the missing portion:

                try
                {
                    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                    CloudError _errorBody = SafeJsonConvert.DeserializeObject<CloudError>(_responseContent, this.Client.DeserializationSettings);
                    if (_errorBody != null)
                    {
                        ex = new CloudException(_errorBody.Message);
                        ex.Body = _errorBody;
                    }
                }
                catch (JsonException)
                {
                    // Ignore the exception
                }

You can see this code for any of Compute, Network or Storage DELETE operation. The workaround would be for the specs to specify a "default" response; however, the code is generated correctly for PUT and POST requests even without the "default" specification, and there is no reason for DELETE to be any different. Besides, this is a regression relative to Hyak code generation for core RPs.

**Comment by olydis** [comment]
On my machine it generates precisely the same error handling regardless of the HTTP method used (tested against `arm-compute/2016-09-30/swagger/containerService.json`). As soon as there is a response body, I see your "missing portion" being generated, with or without default section. Where specifically do you see inconsistent behavior across HTTP methods? Could you please post Swagger causing this issue?

**Comment by iouri-s** [comment]
I do not know why you are not seeing the issue. Perhaps it was fixed before. If you look at https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServicesOperations.cs generated from the spec you mentioned, you will see that  BeginDeleteWithHttpMessagesAsync has the issue.

**Comment by dsgouda** [comment]
The code generator seems to not create a default response object if none of the responses have a model set. I have fixed this behavior in C# code generator but we need to test the behavior for other generators too.

**Comment by lmazuel** [comment]
Checked and Python is not impacted.
