### ISSUE TITLE
Autorest does not generate correct C# code when pageable and long running operation extension is applied together on the same operation.

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#1816]
Check this spec for reference. https://github.com/Azure/azure-rest-api-specs/pull/864/commits/3e806aea498549d19b42e3001fd1bec42386bfef#diff-c6520c014adae4dc6c1299c963480f4aR352

We had to ask the spec author to not apply the pageable extension because of this bug.

The error received during deserialization is as follows:
```
"Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Microsoft.Azure.Management.Network.Models.GatewayRoute]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Path 'value', line 2, position 10. "
```

`x-ms-pageable` extension flattens the value property (which is of type array) and returns an `IEnumerable<T>`  **if  nextLinkName in the extension is set to null** or returns an `IPage<T>` otherwise.

So this flattening messes up the final 200 response that is received after polling. 

For long running operations in C# the deserialization of the final 200 happens in the runtime and the method returns from there to the application that called long running method. The runtime does not know that flattening due to the pageable extension has happened and it cannot deserialize an object with value property into an IEnumerable<T>.

I handle this differently in node.js. Instead of returning from the runtime, I send the stringified responseBody back to the [caller in the generated code (for example the create() method)](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/operations/storageAccounts.js#L315). The generated method has the context of how to deserialize it's 200 response . It does that and then returns the final object back to the application that called the create() method.

**Comment by fearthecowboy** [comment]
We can try to make this idea work in vNext generator and client libraries.
