### ISSUE TITLE
Linter - Spurious Unique Resource Paths warning?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/autorest#1821]
In [this PR](https://github.com/Azure/azure-rest-api-specs/pull/883#pullrequestreview-18749328) a warning came up, however I don't understand why, it might be spurious?

WARNING: UniqueResourcePaths - More than one resource path is not allowed in a single spec
        Path: #/Paths

Thanks for consideration

/cc @amarzavery @vishrutshah

**Comment by dsgouda** [comment]
@vishrutshah I am not able to repro the issue with latest AutoRest build and the specs mentioned in the PR, do let me know if you can still see this issue and I can take a look.

**Comment by vishrutshah** [comment]
@dsgouda Cool If we do not repro this then we should close the issue. Thanks!

**Comment by dsgouda** [comment]
Closing this for now, if this happens again, we can reopen the issue.
