### ISSUE TITLE
Feature Request: automate client generation process as post-build of web project

### ISSUE THREAD

**Issue by weitzhandler** [Azure/autorest#1823]
Hi,

Currently, in order to generate client entities you have to run the project, manually save the Swagger file and run the client generation wizard manually upon each change in the API scheme.

The client-entity generation should then be automatically wired as a post build process. The generation should happen upon each **build**.
I wish there could be an additional tab in the web project properties to allow the customization of the Swagger/AutoRest generation, selecting the target projects in the solution so all this happens without such big hassle and without having to run the web app each time the API is changed.

**Comment by olydis** [comment]
created rollup issue
