### ISSUE TITLE
[Potential Bug] Parameter 'internalConstructors' is not expected

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1828]
travis-ci job: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009

Error File: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2328
Error Info: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2336

Doesn't looks like linter rule but needs an investigation.

**Comment by veronicagg** [comment]
@olydis do you know what this error is pointing out?

**Comment by olydis** [comment]
see https://github.com/Azure/autorest/issues/1829#issuecomment-284921396

**Comment by veronicagg** [comment]
Closing as referenced issue which deals with the root cause of the problem is fixed.
