### ISSUE TITLE
[Potential Bug] Parameter 'useDateTimeOffset' is not expected

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1829]
travis-ci job: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009

Error File: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2328
Error Info: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2337

Doesn't looks like linter rule but needs an investigation.

**Comment by veronicagg** [comment]
@olydis do you know what this error is pointing out?

**Comment by olydis** [comment]
Looking at the code that generates it (`Settings.cs#488`), it's complete bogus. Feel free to remove that "validation"! :-)

**Comment by olydis** [comment]
fixed as of #1909
