### ISSUE TITLE
 GuidValidation - Guid used at the ***. Usage of Guid is not recommended

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#1830]
Travis CI Job: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009

Error File: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2340
Error Info: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/200532009#L2350

Code Location: https://github.com/Azure/autorest/blob/5cce029452e94eb0362bf0ea9b1bb43893aca33a/src/modeler/AutoRest.Swagger/Validation/GuidValidation.cs#L39

**Rule:**  "The guidance around GUID is applicable to body parameters. And then too, it’s a strong recommendation and not a requirement. Having GUID for headers like client-request-id [...] is fine and recommended as per RPC (Resource Provider Contract)."

**Action:** Make current rule strict around the requirements.

**Comment by veronicagg** [comment]
@ravbhatnagar could you clarify what this rule should apply to? It currently applies to all properties in model definitions defined in the spec. Is the example pointed to in the job above violating the rule or not?

**Comment by veronicagg** [comment]
I'm removing this bug fix from the current milestone, as the priority of the fix for this rule seems low, we'll address it later.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
