### ISSUE TITLE
[Go] Add `ListAll` or similar to wrap calls to ms-pageable operations

### ISSUE THREAD

**Issue by marstr** [Azure/autorest#1839]
As discussed in Azure/azure-sdk-for-go#296 and a few other places, at the moment consuming paged results is tedious and not idiomatic in Go.

We could do better by generating methods that returned literally all of the results instead of just a single page with a callback for the next. This could be implemented using slices or channels. My personal preference would be channels.

**Comment by marstr** [comment]
@mcardosos, what's the status of this? Didn't you get something out here?

**Comment by mcardosos** [comment]
Ah, yes :D
Forgot to close, fixed in https://github.com/Azure/autorest/pull/2180
