### ISSUE TITLE
Should `ProvidersPathValidation` also apply for tenant-wide paths?

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1840]
Should `ProvidersPathValidation` also apply for tenant-wide paths?

Currently it does not apply to tenant-wide paths like
`/subscriptions/{subscriptionId}/providers/Microsoft.Billing/invoices/{invoiceName}`
and would hence also not fire on stuff like
`/subscriptions/{subscriptionId}/providers/Microsoft.Billing/{invoiceName}/invoices`

**Comment by veronicagg** [comment]
@ravbhatnagar could help with this question? so we can update the rule if necessary?

**Comment by dsgouda** [comment]
Pinging @ravbhatnagar

**Comment by veronicagg** [comment]
related... https://github.com/Azure/autorest/issues/2170

**Comment by ravbhatnagar** [comment]
@dsgouda Please help me understand what all does this rule verify today.

**Comment by ravbhatnagar** [comment]
After syncing with @dsgouda , it seems like we will have to modify this rule. The pattern we are using today needs to be expanded/tweaked since it wont catch all the issues as pointed by @olydis . But, since this is a warning as of now, lets leave it as is and fix it in a later iteration.

**Comment by veronicagg** [comment]
@sarangan12 I believe you were looking into some stuff that was needing to identify tenet-wide stuff, if so you may want to look into this. If that's not the case, feel free to remove your assignment, and we'll figure out who takes it once we get there.

**Comment by sarangan12** [comment]
After synching up with @veronicagg it has been decided that this rule will be removed which makes this issue irrelavant. Closing this issue now.

**Comment by veronicagg** [comment]
https://github.com/Azure/autorest/issues/2383
