### ISSUE TITLE
C# - Deserialization fails if class doesn't use JsonObject attribute but base class does

### ISSUE THREAD

**Issue by dco123** [Azure/autorest#1842]
When PolymorphicJsonConverter tries to find a type for the given type name, it will search types by checking if that type has a JsonObjectAttribute, and if so it uses the type name defined in that attribute rather than the actual name of the type.

The problem is that when it looks for this attribute on a type, it is also looking at inherited attributes, so if a base class of a type has a JsonObject attribute then this value will be inherited by all sub classes.

This causes a problem because the JsonObject attribute is only defined if the discriminator doesn't match the type name. e.g:

    [JsonObject("Base-Class")]
    public class BaseClass { }

    public class SubClass : BaseClass { }

If a type name of 'SubClass' is found in the serialised json, the converter will consider the type SubClass to have a type name of 'Base-Class' because it has inherited the JsonObject attribute from BaseClass.

Could it be changed so the JsonObject attribute is declared regardless of whether it matches the type name?

**Comment by dsgouda** [comment]
Fix is merged
