### ISSUE TITLE
Resolve orphan children (json models) in an external document

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#1854]
While resolving relative swaggers, make sure to bring in all the models that have an allOf on a given model in that file.

For example there is a swagger spec S1 and an external json document (containing model definitions only) E1.

There are operations and models in S1 that refer to a model named "Pet" in E1. There are 2 more models named "Cat" and "Dog" that are an `allOf` "Pet" in E1. 

> The _special condition_ is that there are **NO models or operations in the Swagger spec "S1" or models in the External Doc "E1" that reference "Cat" and "Dog" directly.**

In this scenario, currently we will leave those models. We do a DFS while resolving external references. However, "Cat" and "Dog" in the above scenario are not referenced anywhere. Hence, they are dropped.

The logic over here would be to:
1. Resolve a model definition in an external document (happening currently), 
     1. find out whether there are any model definitions in that document that are an `allOf` on the resolved model definition. 
          1. If there are such models then we should resolve each of those models completely as done in `step 1.` and then follow `step 1.i.` for each of them (recursively).

Until this issue is resolved, the workaround is to have the entire hierarchy present in the swagger spec.

**Comment by fearthecowboy** [comment]
I disagree -- and multiple input files can support this fine at this point.
