### ISSUE TITLE
Linter Rule: ResourceModelValidation should be broken into individual rules

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#1861]
Currently the following error is given out -
WARNING: ResourceModelValidation - The id, name, type, location and tags properties of the Resource must be present with id, name and type as read-only
One validation rule for if these properties are present and one for whether they are set to read-only or not.

**Comment by ravbhatnagar** [comment]
Is this checking the response body for name, id, type and location of a tracked resource? If yes, tags is not required in the response as it is optional. Please check with @ravbhatnagar before changing this rule

**Comment by vishrutshah** [comment]
1. tags cannot be in proxy resource - Error
2. location must be in TrackedResource + must be marked as required - Error
3. location can be in ProxyResource + if present must not be marked as required - Warning

**Comment by vishrutshah** [comment]
Initial PR is out covering this PR https://github.com/dsgouda/autorest/pull/4

@sarangan12 is covering me on this rule. reassigning it to him

**Comment by sarangan12** [comment]
https://github.com/Azure/autorest/pull/2087 Task completed
