### ISSUE TITLE
[C#] FATAL Error generating client model: Value cannot be null - produces image/png

### ISSUE THREAD

**Issue by davidmcg1985** [Azure/autorest#1868]
Looking for some help/advice,

		"/events/{locationId}/{eventId}/evidence": {
			"get": {
				"operationId": "getEventEvidenceByLocationIdAndEventId",
				"description": "Retrieves evidence for the event.",
				"parameters": [{
					"description": "Unique identifier of the location.",
					"in": "path",
					"name": "locationId",
					"required": true,
					"type": "string"
				}, {
					"description": "Unique identifier of the location.",
					"in": "path",
					"name": "eventId",
					"required": true,
					"type": "string"
				}],
				"produces": [
					"image/png"
				],
				"responses": {
					"200": {
						"description": "OK"
					},
					"404": {
						"description": "Valid values for message property are locationNotFound, eventNotFound and evidenceNotFound.",
						"schema": {
							"properties": {
								"message": {
									"enum": [
										"actionNotFound",
										"boilerBrandNotFound",
										"boilerBrandFamilyNotFound",
										"boilerNotFound",
										"propertyNotFound",
										"chartNotFound",
										"comfortZoneControllerNotFound",
										"comfortZoneManagerNotFound",
										"locationNotFound",
										"gatewayNotFound",
										"weatherDataPointsNotFound",
										"deviceDataPointsNotFound",
										"stagesNotFound",
										"stageNotFound",
										"alertNotFound",
										"eventNotFound"
									]
								},
								"messageDetail": {
									"type": "string"
								}
							},
							"required": [
								"message",
								"messageDetail"
							],
							"type": "object"
						}
					}
				}
			}
		},

Similar issue I believe to #1373 

When the block:

    "produces": [
        "image/png"
    ],

is removed the code generation passes. Is there no support for a GET request returning this form of mie-type?

@amarzavery is this something you could advise me on?

I can attach the generation script and full json if required.

Thanks,
David

**Comment by olydis** [comment]
> Is there no support for a GET request returning this form of mie-type?

Unfortunately that is precisely the case! Currently AutoRest is mainly targeting `application/json` and has some support for `application/xml`. Adding further media types would be a nice enhancement that we will look into in the future!

**Comment by olydis** [comment]
Looking at your `responses` definitions, you might also find https://github.com/Azure/autorest/issues/1890#issuecomment-283467009 helpful, but that's not directly related to your question ;-)

**Comment by olydis** [comment]
I'll close this as it is a known problem, but feel free to post further questions that I'll be happy to answer!

**Comment by davidmcg1985** [comment]
Thank you very much @olydis for your help!
