### ISSUE TITLE
[XamarinAndroid-Release] Operation returned an invalid status code 'Bad Request' 

### ISSUE THREAD

**Issue by FBerco** [Azure/autorest#1871]
Hi Devs,
I'm having some trouble doing requests on release. The same requests on debug run perfect, and then, when I run the app on Release mode the calls with AutoRest return "Operation returned an invalid status code 'Bad Request'". Any idea what could it be? 
Thank you.

**Comment by fearthecowboy** [comment]
Apologies @FBerco  - I didn't catch this when you posted it.

did you find a solution to your problem?
