### ISSUE TITLE
autorest ignores e.g. HttpStatusCode.Created

### ISSUE THREAD

**Issue by schittli** [Azure/autorest#188]
Hello

I just started with Swagger and I think there are more valid Response Codes than only HttpStatusCode.OK.

For example, this code throws an Exception - even if HttpStatusCode.Created:

            if (statusCode != HttpStatusCode.OK)
            {
                HttpOperationException<object> ex = new HttpOperationException<object>();
                ex.Request = httpRequest;
                ex.Response = httpResponse;
                ex.Body = null;
                if (shouldTrace)
                {
                    ServiceClientTracing.Error(invocationId, ex);
                }
                throw ex;
            }

Therefore I think it woule be useful if one can pass valid HttpStatusCodes, or if such functions just return the StatusCode and allow the User to decide if something is an exeception :-)

Thanks for your very usefule work!
kind regards,
Tom

**Comment by stankovski** [comment]
@schittli You should be able to specify multiple success status code in swagger (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responses-object). For example:
```
"responses": {
  "200": {
    "description": "xxx",
    "schema": {
      "$ref": "#/definitions/Foo"
    }
  }, 
  "201": {
    "description": "xxx",
    "schema": {
      "$ref": "#/definitions/Bar"
    }
  },
```

**Comment by justin-lovell** [comment]
I disagree that this issue be marked as closed.

A server should be able to respond with anything in the 2xx range (meaning it was **good response**) and the client be able to interpret the body.

The server is in compliance by responding with a 201 response. The client (autorest) interprets the REST specifications incorrectly.

http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by matt-gibbs** [comment]
@justin-lovell, the client isn't making a statement about REST semantics. It is generated from what is explicitly defined in the Swagger spec. AutoRest is trying to produce maximally useful clients based on the Swagger description of the API. Response models for an operation require one or more status codes be defined and can include a "default" model. Where the 200 is explicitly defined, and the 201 is not, the client treats the 201 as a "default" to be surfaced as an exception. Not perfect in all scenarios, but we think it's the right compromise given Swagger's ambiguous statements around response models. In C#, the generated method has a return type that is the common ancestor of the specified 2xx models. Anything else falls into the "default" model and is surfaced as an exception. In Denis' example, the return type of the generated method would be the common ancestor of Foo and Bar models. We find people using "default" as the way to model error responses. It is unlikely that the common ancestor of success responses and error responses is anything better than 'object.' The downside is that you can't use "default" in Swagger to specify success models.
