### ISSUE TITLE
[C#] Constructor parameter descriptions missing for inherited parameters

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#1880]
In the following example, the `name` parameter is defined in the base class, but its documentation is missing from the derived class:

```csharp
     [Newtonsoft.Json.JsonObject("#Microsoft.Azure.Search.UniqueTokenFilter")]
     public partial class UniqueTokenFilter : TokenFilter
     {
         /// <summary>
         /// Initializes a new instance of the UniqueTokenFilter class.
         /// </summary>
         /// <param name="onlyOnSamePosition">A value indicating whether to
         /// remove duplicates only at the same position. Default is
         /// false.</param>
         public UniqueTokenFilter(string name, bool? onlyOnSamePosition = default(bool?))
             : base(name)
         {
         }
```

This issue occurs with version 20170110 of the AutoRest nightly build.

**Comment by dsgouda** [comment]
@brjohnstmsft I'm not able to replicate this issue with the latest AutoRest bit. Can you please check if you still see this and provide the spec in question

**Comment by dsgouda** [comment]
Upon closer look, TokenFilter base class does not have any description associated with any of its properties (something that I saw for the Tokenizer base class as well). If there is no description associated with a parameter the documentation won't be generated by Autorest.
@brjohnstmsft please fix the spec and feel free to reopen this issue if this persists
