### ISSUE TITLE
Categories (or error levels) of linter rules should not be hard-coded in the rule itself

### ISSUE THREAD

**Issue by johanste** [Azure/autorest#1881]
As we expand the usage of the tool, we are finding that there are multiple contexts in which rules need to be applied. For example, there are additional rules around a swagger that describes an Azure Resource Provider than there are for services in general. In addition, the severity of the error depends on the service type - what is a "it would be nice if..." rules for one category of services may be a "you are not allowed to deploy unless..." category of errors for other services. 

I would suggest an external mapping file that has a ruleId -> severity -> description mapping and can be applied depending on which swagger we run the tool on.

**Comment by veronicagg** [comment]
IMO, implementing this would help having documentation always in sync (see https://github.com/Azure/azure-rest-api-specs/pull/1135#pullrequestreview-34083307). Let's think about how we can do this, so we keep it in one place, and have a link in each rule that points to where more details are (a detailed page - evaluate whether we may need fwlinks for this, to avoid hardcoding exact urls).

**Comment by sarangan12** [comment]
The task has been moved to icebox. Removing assignee and moving the task to common pool

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
