### ISSUE TITLE
Feedback for AutoRest installer 

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#1884]
# _PREVIEW AVAILABLE_ : Installer EXE for AutoRest now online 
You can test out the PREVIEW AutoRest installer from : https://github.com/Azure/autorest/releases/download/dotnet-runtime-1.0.3/AutoInstaller.exe

**Note**: 
The Installer is a work-in-progress -- it has been tested for the happy path, some functionality isn't yet implemented:
- Remove/Uninstall - not yet implemented
- Upgrade - minimally tested
- About and Project buttons - not yet implemented
- not yet codesiged
- no silent/unattended mode yet

**Comment by fearthecowboy** [comment]
![image](https://cloud.githubusercontent.com/assets/133736/23370663/440ff1c4-fcca-11e6-9b66-5e0da642af55.png)

**Comment by csharmath** [comment]
Where does it log ?
It failed to install and now can't remove / upgrade.

**Comment by fearthecowboy** [comment]
It's just automating the manual steps -- go to an elevated command line and type:

```
# if this doesn't work, it didn't install autorest at all.
autorest --reset 

# if this doesn't work it doesn't look like it even installed node.js
npm uninstall -g autorest

```

**Comment by csharmath** [comment]
Thanks I've figured that part, just wanted to let you know and see if I can share some logs to help solving the installer issue

**Comment by rlarno** [comment]
Tried the installer, failed.
Ran the above statements to uninstall and install.
Output of running autorest -- reset

> AutoRest Code Generator
> (c) 2017 Microsoft Corporation. https://aka.ms/autorest
> Downloading https://github.com/Azure/autorest/releases/download/dotnet-runtime-1.0.5/dotnet-win7-x64.1.0.5.zip
>         to  C:\Users\RudiLarno.autorest\frameworks
> Unable to find asset for version '1.0.1-20170609-2300-nightly'

**Comment by ericstj** [comment]
Installer is unsigned and requires elevation.  Stopped at that point.

**Comment by fearthecowboy** [comment]
@ericstj 

Good point. -- Install node separately and use npm to install.   I have some fixes I have to do before I can go back and finish the installer.

**Comment by fearthecowboy** [comment]
canning the installer UI entirely.
