### ISSUE TITLE
Source for AutoRest.exe?

### ISSUE THREAD

**Issue by schittli** [Azure/autorest#189]
Good evening

it looks like the source for AutoRest.exe is not in this repository - searchinv for e.g. "CodeGenerator" (an commandline argument) does not find any source-file. 
Isn't it open source?

Thanks a lot in advance,
kind regards,
Tom

**Comment by devigned** [comment]
See: https://github.com/Azure/autorest/issues/55

It's in the dev branch and soon moving to master.
