### ISSUE TITLE
InclusiveMinimum doesn't work with decimal value

### ISSUE THREAD

**Issue by melissalina89** [Azure/autorest#1903]
Have part of swagger specification like this
```
"myProperty": {
      "format": "decimal",
      "minimum": 0.01,
      "type": "number"
},
```

C# codegen generates invalid code. Build was failed with error `CS0019    Operator '<' cannot be applied to operands of type 'decimal' and 'double'`

Checked on develop branch.

**Comment by olydis** [comment]
Sorry for the delay, this should be fixed as of https://github.com/Azure/autorest/pull/2054, let us know if this works for you!

**Comment by melissalina89** [comment]
Thanks a lot! I will check it as soon as possible.
