### ISSUE TITLE
[C#] Ability to override exception handling

### ISSUE THREAD

**Issue by johnamcruz** [Azure/autorest#1910]
Hello,

I was wondering if we can add an ability to customize the exception handling. Maybe add a partial method that is called during each exception. I would like to have the ability to trap exceptions and rethrow specific exceptions.

**Comment by olydis** [comment]
There is no such support currently -- although, I'm wondering what exactly this would enable you to do that you cannot do with ordinary exception handling and re-throwing?

**Comment by fearthecowboy** [comment]
At this point, use catch/throw.
