### ISSUE TITLE
gulp autorest fails to read first argument

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#1911]
This issue happens only when trying to run autorest via gulp

gulp autorest -I "<somePath>" 
should run against the <somePath> json but the gulp script doesn't seem to pass this argument correctly to the dotnet exe

**Comment by dsgouda** [comment]
@olydis any updates here.

**Comment by olydis** [comment]
@dsgouda oh you have to pass `--foo` or something as a first parameter merely because `gulp` *itself* will otherwise interpret the first parameter as a gulp task. due to the limitations of gulp that'll have to do, for a more realistic feel there's no way around installing and using `autorest`
