### ISSUE TITLE
TypeError: this._target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by DavidStrickland0** [Azure/autorest#1914]
Downloaded the Latest Azure SDK But it appears it has an older version of Autorest packaged with it.

Trying to Install the latest version.

Node 7 is istalled,
NPM is installed
`npm install -g autorest
` - appears to install  autorest
however 
`autorest `
produces 
> 
C:\Users\dstrickland>autorest
AutoRest
TypeError: this._target[Symbol.iterator] is not a function

**Comment by svickers** [comment]
I am getting this as well after uninstalling the chocolatey version and switching to npm install.  Node version 6.10.0.

**Comment by olydis** [comment]
you need at least node `7.10` to run latest AutoRest - we added a check for that so people get notified about it 🙂 

Let us know or reopen the issue if you have any further questions or concerns!
