### ISSUE TITLE
ListOperationNamingWarning: update rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1930]
update message to indicate "Since operation {0} returns an array or is x-ms-pageable, then should be named as *_list". Evaluate whether the message could be deterministic/point to accurate root cause, either array or x-ms-pageable.

**Comment by dsgouda** [comment]
@veronicagg if I remember correctly we should apply this rule only for the xmspageable operations since operations that return arrays will be flagged as xmspageable by a different rule. Please confirm

**Comment by veronicagg** [comment]
@dsgouda if you can consume a "list" definition (what we define as a list - either an array or an x-ms-pageable tagged operation), so that this rule also catches cases in which x-ms-pageable is missing, better. This way we could expose as many errors as possible from the start.
