### ISSUE TITLE
Exception in client when processing binary response

### ISSUE THREAD

**Issue by xplicit** [Azure/autorest#1932]
When response schema contains `binary` format for representing `byte []` array similar like in the sample, autorest should generate method with return type `byte[]`

https://github.com/Azure/autorest/blob/32b300809805c3740955e039cf219f995c923ec2/Samples/petstore/petstore.json#L278-L284

But it generates method with return type `string` which tries to convert binary array of bytes to string and when method is called, the exception is raised.

https://github.com/Azure/autorest/blob/75e583cf0c3fc29033f97f470696eea72f913f6d/Samples/petstore/CSharp/SwaggerPetstoreExtensions.cs#L214-L217

Exception is thrown at this line:

https://github.com/Azure/autorest/blob/75e583cf0c3fc29033f97f470696eea72f913f6d/Samples/petstore/CSharp/SwaggerPetstore.cs#L897

Releated info about `binary` format:

https://github.com/OAI/OpenAPI-Specification/issues/50#issuecomment-112063782
https://github.com/OAI/OpenAPI-Specification/issues/430

**Comment by mannyvw** [comment]
Did you get anywhere with this having the same issue @xplicit . At moment am thinking might have to convert end point to return base64 encoded data but not ideal

thanks

**Comment by fearthecowboy** [comment]
Have no idea how we missed seeing this.

Is the whole response a byte array? if so, you should use stream for the response.

Otherwise, if the response is a json with embedded binary data, ... you *have* to encode it as a string. JSON doesn't support directly embedded binary data.

**Comment by MiYanni** [comment]
Answer provided. Closing.
