### ISSUE TITLE
RequiredPropertiesMustExist: remove rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1935]
Verify this rule is covered by semantic validator, and if so, remove the rule.

**Comment by sarangan12** [comment]
@veronicagg 

Yes. This rule has already been handled by the semantic validator. Eg. message from Semantic Validator:

{ code: 'SEMANTIC_VALIDATION_ERROR',
  message: 'The spec E:\\projects\\azure-rest-api-specs\\arm-logic\\2016-06-01\\swagger\\logic.json has semantic validation errors.',
  innerErrors:
   [ { code: 'OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION',
       message: 'Missing required property definition: nameX',
       path: [ 'definitions', 'Sku' ] } ] }

So, removing this rule from linter rule list.
