### ISSUE TITLE
ResourceModelValidation: review how to identify a "Resource"

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1936]
How should resource be found? A model is an allOf of a definition that has x-ms-azure-resource=true

**Comment by veronicagg** [comment]
@dsgouda @ravbhatnagar @amarzavery @vishrutshah @sarangan12 
We've updated this definition to be the following:
Resources list should be built as the union of:
1. Any model that's returned by a PUT operation
2. Any model that has an "allOf" of "Resource" at any level (name of the root model is "Resource") AND it's in 200 response of a GET
3. Any model that has x-ms-azure-resource at some level (excluding the model that actually has x-ms-azure-resource tag - since this one should be the base resource)

Resources can be divided between "Tracked Resources" and "Proxy Resources". A Resource as defined above which contains "location" property as required, is a "Tracked Resource"; any other Resource, is a "Proxy Resource".

**Comment by veronicagg** [comment]
I talked to @olydis about where a good place to put this logic in autorest would be, since we should run this logic once per model and have it available to all our rules. IMO, the Resource list is like a "view" of the swagger model. He suggested to create a class in parallel with RuleContext, though RuleContext doesn't seem to be in the right place in AutoRest. He'll be creating a pull request to move RuleContext most likely to AutoRest.Swagger. After that, we probably need to create a class that has a "Resource" list property and exposes methods to obtain "Resources", "Tracked Resources" and "Proxy Resources".

**Comment by dsgouda** [comment]
So.... just had a thought:
We are saying that model definitions that "allOf" on a Resource type are ResourceModels. What happens if a model definition has a property that references a Resource (of any type)? Are we sure they are not of "Resource" type? I believe there shouldn't be instances that do this currently in our rest spec repo but it would be worth consideration

@ravbhatnagar @amarzavery thoughts?

**Comment by dsgouda** [comment]
On similar lines, when determining a tracked resource, do we have to traverse the property references in order to search for a property named "location"

**Comment by ravbhatnagar** [comment]
@dsgouda As discussed over IM, the scenario in your first comment is highly unlikely to happen. And even if it happens, we should not treat it as a "Resource" since all the properties that make the model a resource are nested inside another property. Same applies to the location as well. We should not traverse property references to find "location"

**Comment by veronicagg** [comment]
Copying from Sarangan's summary:
Resource Determination logic

1. Get the list of model definitions that does not contain x-ms-azure-resource: true. 

2. For each model, check if that model is returned by a PUT operation. (note down the path)
2.1. If the model is returned by a PUT operation and has id, name & type [in its hierarchy], the model is a resource.

3. If the model is not returned by a PUT operation:
3.1. It has 'allOf' Resource at any level [name of the root model is 'Resource']
3.2. And the model is returned by a GET operation in 200 response
3.3. If the model has id, name, type [in its hierarchy], the model is aa resource

4. If a model does not fit in (2) & (3), but if the model has 'x-ms-azure-resource': true in its hierarchy:
4.1. If the model has id, name, type [in its hierarchy], the model is aa resource

If a resource has property 'location', in its hierarchy, it is a TrackedResource. 


Rules on Tracked Resource

Rule I: Now, we have determined a model as a tracked resource, there must be a get operation which returns this tracked resource.

Now, with the path/url noted in step 2 (above), parse it and determine if the tracked resource is a parent resource/child resource.

For Parent Resource:

Rule II: There must be a get operation with id *_ListByResourceGroup which returns the tracked resource
Rule III: Ther must be a get operation with id *_List|*_ListBySubscriptionId|*_ListBySubscription|*_ListBySubscriptions which returns the tracked resource

For Child Resource:

Rule IV: There must be an operation with id *_ListBy[ParentResourceName] which returns the tracked resource

**Comment by dsgouda** [comment]
Hi Veronica,
I’m a little confused here. I have modeled my code to determine resource models entirely based on the comments here<https://github.com/Azure/autorest/issues/1936> which seems incomplete compared to notes on this thread.
Should I consider this as the complete definition instead?
-Deepak

**Comment by dsgouda** [comment]
After multiple discussions this is what we have narrowed down the logic for determining a resource

1. For each model, check if that model is returned by a PUT operation. (note down the path)
        1.1. If the model is returned by a PUT operation, the model is a resource.

2. If the model has an 'allOf' Resource at any level [name of the root model is 'Resource'] AND the model is returned by a GET operation in 200 response.

3.	If the model has 'x-ms-azure-resource': true and is not named either of 'Resource', 'TrackedResource' or 'ProxyResource', consider this as a resource

FYI @ravbhatnagar @amarzavery @veronicagg @sarangan12 @vishrutshah
