### ISSUE TITLE
ServiceDefinitionParameters: update rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1938]
Update: does it have host set to management.azure.com or x-ms-parameterized-host, if it is azure resource, if it's anywhere in the paths, then it should be globally defined, api-version should exist. Messages should be accurate to what's violating the rul.

ID: M2014
Category: SDK Violation
Severity: Error

**Comment by vishrutshah** [comment]
Closing this rule based on https://github.com/Azure/autorest/issues/1940. We do not want distinction on rule based on host.

**Comment by vishrutshah** [comment]
Based on offline sync with @dsgouda & @veronicagg , we are not tailoring any rule targeting towards Azure Management Plane. Hence we do not check on `management.azure.com` or `x-ms-parameterized-host` at all for now. Once we have infrastructure ready, we can update this rule to tailor towards specific planes.
