### ISSUE TITLE
Implement rule categorization around azure/azure management/non-azure

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1940]
Add the following logic to the rule, if host set to management.azure.com or x-ms-parameterized-host, then only https is allowed. Update message to be accurate depending on what condition is not met. For non-azure services, it could be http or https.

ID: M2043
Category: SDK Violation
Severity: Error

**Comment by dsgouda** [comment]
Talked to @fearthecowboy and @olydis and they agree that we should not be making any assumptions about whether a swagger spec is Azure management related or not, which means we cannot differentiate based on host. This rule boils down to checking whether the schemes are https or not.

**Comment by veronicagg** [comment]
@dsgouda based on our offline conversation, we'll keep this rule as is for now, and we'll work on implementing a more structured differentiation of rules that apply to azure/azure management/non-azure specs, so that this one can be split in those buckets.

**Comment by veronicagg** [comment]
We're extending categorization also for "rule applicable to an individual swagger file" versus "rule applicable to a composed swagger"
For example, OperationsAPI should applicable to a composed swagger, so if it's in one of them, the rule is not violated. 
We may have another case with api-version, in which we'd like all operations in one file to be only for one api-version, but a composed swagger could have multiple api-versions involved. So this type of rule should pass only for individual files.

**Comment by dsgouda** [comment]
As step 0 @olydis will implement an AutoRest feature that will enable us to run validation over composite/single specs based on an input argument. This argument will then be passed to the Validator module based on which we can select what rules to run.

**Comment by olydis** [comment]
Stub: https://github.com/Azure/autorest/pull/2164
Enhance with further categories as necessary ;-)
