### ISSUE TITLE
PageableRequires200Response: update rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1945]
Review rule implementation, so it uses shared definition of resource.
ID: ?
Category: SDK Violation
Severity: Error

**Comment by dsgouda** [comment]
@veronicagg need more info here. How is this tied to resource definitions?

**Comment by veronicagg** [comment]
@dsgouda sorry, I included the wrong comment there. Rest is good, we need to add an ID, @kirthik may help you with that.

**Comment by dsgouda** [comment]
@kirthik can you provide an Id here

**Comment by kirthik** [comment]
@dsgouda - M2059 and please make sure you add this to the [checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md)

**Comment by dsgouda** [comment]
@veronicagg Should this be an RPCViolation

**Comment by dsgouda** [comment]
Talked to @veronicagg offline, this should be an SDKViolation, also 2059 is already in use, updating it to 2060
