### ISSUE TITLE
ResourceIsMsResourceValidation: update rule to use common resource definition

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1946]
ID: M2019
Category: SDK Violation
Severity: Error

**Comment by veronicagg** [comment]
Review rule implementation, so that it uses shared definition of resource.

**Comment by vishrutshah** [comment]
Beingcovered as part of https://github.com/Azure/autorest/issues/1861

**Comment by vishrutshah** [comment]
Initial PR is out covering this PR https://github.com/dsgouda/autorest/pull/4

@sarangan12 is covering me on this rule. reassigning it to him. Thanks

**Comment by sarangan12** [comment]
PR seems to have been merged and closed. Closing this issue
