### ISSUE TITLE
New rule: If a model has the properties that define a Resource, then x-ms-azure-resource should be true

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1949]
Category: SDK Violation
ID: ?
Severity: Error

**Comment by dsgouda** [comment]
So, there already exists a rule ```ResourceIsMsResourceValidation``` which checks for the ```x-ms-azure-resource``` extension on all model definitions that have a name ```Resource```, wondering if we should simply extend that rule
@veronicagg thoughts?

**Comment by veronicagg** [comment]
@dsgouda I'm honestly a bit unsure about this rule, after all the conversations we had about resources. 
I'd say let's not implement it, I believe there's already a rule that does check on readonly properties for name, type and id. Thoughts?

**Comment by dsgouda** [comment]
I tend to agree. Now that I think about it we are circling around the same concepts with this rule. Let things play out with our "current" definition of a resource and we can re-evaluate resource-related rules.
Closing this issue for now.
