### ISSUE TITLE
New rule: Same model for body parameter and response in PUT

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1952]
M2017: The model definition for the body parameter and the response MUST be the same for a PUT operation. This ensures that the same entity will be reusable between GET and PUT.
Category: SDK Violation
Severity: Error

**Comment by dsgouda** [comment]
I'm concerned whether this will upset the usual structure most RPs use for PUT operations i.e., using a "ModelCreateParameters" model as request body schema and "Model" as their response model schema. Do we still want this as an error?
