### ISSUE TITLE
New rule: property with "enum" should have an x-ms-enum extension

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1953]
M2018: A parameter or a model property having an "enum": [] constraint, MUST have an "x-ms-enum" extension and the extension's "modelAsString" property MUST be set to false where applicable. (clarify "where applicable")
Category: SDK Violation
Severity: Error

**Comment by dsgouda** [comment]
While enforcing an ```x-ms-enum``` extension for enums is a good idea, I'm not sure why we should encourage what ```modelAsString``` should be set as. At most I think the message should simply convey that not setting ```modelAsString``` to true generates client sdks that will have breaking changes whenever the enums' values are modified.
Thoughts or suggestions?

**Comment by veronicagg** [comment]
@amarzavery could you comment on this?
I believe the intention is to enforce "x-ms-enum" but not necessarily "modelAsString" set to false (because it says where applicable), I think the way this is written in the checklist is a bit misleading. 
Also, is it true that we should have every enum be x-ms-enum? what happens if it's a real enum and people don't use x-ms-enum, what effect does it cause during code generation?

**Comment by dsgouda** [comment]
On similar lines, I wonder if it makes sense to have a linter rule with warning severity that simply flags ```modelAsString:false``` might result into a breaking change every time the enum values change.

**Comment by veronicagg** [comment]
@dsgouda I think that may make sense. @kirthik thoughts? I'm wondering where we draw the line between warnings and guidelines, it seems like a good idea to throw warnings for specific things found in the specs, so people don't have to read the full set of guidelines. On the other hand, we should be careful on flooding the output with warnings. I'm wondering if we should bring in an "Info" category for the "guidelines".
