### ISSUE TITLE
New rule: Every operation should define x-ms-examples

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1954]
M2022: Every operation in the swagger specification MUST have an "x-ms-examples" extension applied with scenarios that provide the MINIMUM AND MAXIMUM properties of the request and response payload. Please feel free to provide more example scenarios for a particular operation.
Category: SDK Violation
Severity: Error

**Comment by dsgouda** [comment]
Per offline discussion with @veronicagg will assign severity to Warning and only check for ```x-ms-examples``` extension set on operations

**Comment by dsgouda** [comment]
@kirthik Please confirm severity of this rule

**Comment by dsgouda** [comment]
Also, should we request ```x-ms-examples``` for Operations_list operation?

**Comment by kirthik** [comment]
@dsgouda : This should be an error not warning. I don't think we should request `x-ms-examples` for Operations_List operation since they only take subscription Id and API Version as parameters.

**Comment by dsgouda** [comment]
Validation rule implemented
