### ISSUE TITLE
New rule: list operations must apply x-ms-pageable with nextLinkName:null

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1955]
M2024: Operations that return a single page and have the response schema {"value": [Array of items] }, MUST apply the "x-ms-pageable" with it's "nextLinkName" property explicitly set to "null". This will ensure that value property gets unwrapped into an IEnumerable.
Category: SDK Violation
Severity: Error

**Comment by jaredmoo** [comment]
@veronicagg when I add `x-ms-pageable` to list operations API (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2014-04-01/swagger/sql.core.json#L1434), I get this error.

```
ERROR: Since operation 'ListOperations' response has model definition 'x-ms-pageable', it should be named as "list_*"
        Path: file:///E:/dsmain1/retail/amd64/Xdb/Manifest/Svc/ManagementService.WebApiHosting.ARM.Tools/swagger/swagger.json#/paths
```

Azure services aren't consistent on what the operationid for GET /operations should be. Some have `Operations_List`, some have `ListOperations` so the method is on the client object. SQL is in the latter camp. What's your guidance here? If latter option is ok, then we need to suppress that linter error.

**Comment by jaredmoo** [comment]
Also if one or the other operationIds is recommended, that should be a new linter rule. :)
