### ISSUE TITLE
New rule or schema update: "examples" property schema

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1956]
M2045: An example specified in a specification as per the swagger specification for a response MUST be in the response object keyed on the "MIME-TYPE". More details can be found here.
 M2046: An example specified in a specification as per the swagger specification for a model in the request body MUST be specified in the free-form example property of that model definition. More details can be found here.
Category: SDK Violation / Schema violation
Severity: Error

**Comment by sarangan12** [comment]
SInce this task is moved to icebox, unassigning myself.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
