### ISSUE TITLE
New rule or schema update: "securityDefinitions" object should be accurately defined

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1957]
M2054: Every swagger spec MUST have a "securityDefinitions" object accurately defined. An example can be found at https://github.com/Azure/azure-rest-api-specs/blob/master/arm-analysisservices/2016-05-16/swagger/analysisservices.json#L26
Category: SDK Violation/ Schema violation
Severity: Error

**Comment by sarangan12** [comment]
Task completed. Closing the issue
