### ISSUE TITLE
New rule: POST operations MUST use a METHOD Name that matches the semantic operation on the resource

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1959]
M1008: POST operations MUST use a METHOD Name that matches the semantic operation on the resource, for example "Start" or "Stop". Any action name MUST be same as what is defined in the Rest APIs, like regenerateAdminKeys should be regenerateAdminKeys in the Swagger as well, where as regenerateKeys is bad example.
Category: SDK Violation
Severity: Warning

**Comment by dsgouda** [comment]
Merged, pending publishing of new validator package
