### ISSUE TITLE
Use -NoProfile in powershell.exe invocations

### ISSUE THREAD

**Issue by codespare** [Azure/autorest#196]
Hello, a customized profile.ps1 can interfere with the build steps invoking PowerShell scripts. Adding the -NoProfile option when calling powershell.exe can prevent that. I modified:
 - tools/AutoRest.Settings.targets
 - tools/RegenerateExpectedClasses.ps1
 - tools/Sync-NuspecDependencies.ps1
with good results on the master branch although I haven't tried it out on the dev branch yet.

**Comment by devigned** [comment]
We are working to remove the .ps1 files from the build process to provide a more platform agnostic build process. I'm hoping we'll get this into the project over the next week.

**Comment by markcowl** [comment]
@codespare This should be fixed now in the dev branch, as we no longer use powershell for this.
