### ISSUE TITLE
New rule: The items property for Schema Objects, or schema-like objects (non-body parameters), MUST be required when type is set to array

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1962]
M2042: The items property for Schema Objects, or schema-like objects (non-body parameters), MUST be required when type is set to array. More details can be found at https://github.com/OAI/OpenAPI-Specification/issues/174.
Category: SDK Violation
Severity: Warning

**Comment by dsgouda** [comment]
Wondering if this can be an error.

**Comment by veronicagg** [comment]
@dsgouda what impact does it have if the type is not set to array?

**Comment by dsgouda** [comment]
Tried generating CSharp client using AutoRest with a model property of type without "items" defined, AutoRest throws an exception. 
We can still keep this validation rule just to warn the user.
@veronicagg thoughts?
@fearthecowboy do you think we should make AutoRest consider some sort of  a default when the "items" is not defined for type array.

**Comment by veronicagg** [comment]
@dsgouda if autorest decides to implement a default, then I wouldn't implement the rule. 
If autorest does not implement a default, we can implement this rule as a SDK Violation error, since not following the rule prevents code generation. 
Thanks!

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-openapi-linter/pull/8

**Comment by dsgouda** [comment]
Merged, pending publishing of new validator package
