### ISSUE TITLE
New rule: Every operation MUST have a "default" status code in the "responses" section

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1963]
M2049: Every operation MUST have a "default" status code in the "responses" section. The "default" corresponds to the error returned by the operation.

Should we be enforcing this rule? I believe Autorest adds a default response even if it's not defined in the swagger, so it's not required at swagger level.

**Comment by dsgouda** [comment]
I'm not sure what we imply by saying "a default status code". We do not consider any 4xx codes anyway in AutoRest, what other status codes can we expect by default?

**Comment by fearthecowboy** [comment]
Currently `"default" ` means anything not specified, and is a catch-all for errors. 

If they don't explicitly state `"default"`, do we still generate the same code?

**Comment by veronicagg** [comment]
See docs here, there's a "default" section in the spec: https://github.com/Azure/autorest/blob/bf30da3ae09718d336a1eca49afd7d053d83657e/docs/developer/guide/defining-clients-swagger.md#error-modeling 

Event though, it says it's a must at the top, I'm still unsure if it should be a warning or an error. I know SQL specs don't have this; and AutoRest defaults to do the right thing, we may just make it a warning.

**Comment by dsgouda** [comment]
We generate the same code with or without the ```default``` section unless there is a default error model specified.
So, unless we ask the authors to also specify the error model I am not sure whether we should have this rule at all.

**Comment by veronicagg** [comment]
@dsgouda I'm agreeing with you, how about we have a pointer to "error modeling" in the manual guidelines instead? @kirthik

**Comment by dsgouda** [comment]
I'm open to the idea but still feel this should only be a warning.

**Comment by dsgouda** [comment]
Reassigning this to Kirthi to evaluate the utility of this rule.

**Comment by vishrutshah** [comment]
@hovsepm I know that we pushed monitor team to have this in all of their swagger. I wanted to check with you and see whether do you have any insights into if fluent generation may be affected by this or not?

**Comment by veronicagg** [comment]
@hovsepm any feedback on the above question?

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
