### ISSUE TITLE
New rule: PATCHING tags on a Resource

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1964]
M2056: If the service (in Azure) only supports PATCHING tags on a Resource in the PATCH operation and has a PUT on the same resource which is named as "CreateOrUpdate", then it MUST NOT expose the "PATCH" operation in the swagger spec.
Category: SDK Violation
Severity: Warning

**Comment by sarangan12** [comment]
Unassigning myself since the task is in icebox

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
