### ISSUE TITLE
New rule: Property "name"of the "Resource" model SHOULD NOT be required and it must be marked as readOnly

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1965]
S2002: Property "name"of the "Resource" model SHOULD NOT be required and it must be marked as readOnly. The name of the Resource is specified as a path parameter. There is no need to require the customer to specify it in the body parameter as well.
Category: SDK Violation
Severity: Warning

**Comment by dsgouda** [comment]
A. Why must this be restricted to name only, shouldn't the same idea extend to ```type``` and ```id``` too?
B. Do you mean all models named as "Resource" or all resource models that are found in a given spec.

**Comment by veronicagg** [comment]
@dsgouda 
A. I'm not sure, the original rule from the checklist was written this way. We may need to find out more from @amarzavery on what the intent was. 
B. I'd say all resource models. 
BTW, note this is a P2 rule.

**Comment by dsgouda** [comment]
Any updates here? @sarangan12 could you follow up on these queries

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
