### ISSUE TITLE
Error when generating C# code

### ISSUE THREAD

**Issue by tjementum** [Azure/autorest#197]
I've been trying to get AutoRest to generate C# code from the official sample from [Swagger.io](http://petstore.swagger.io/v2/swagger.json). I get this error:

error: [FATAL] Error generating service model: The operation 'placeOrder' has a body parameter, but did not have a supported MIME type ('application/json') in its Consumes property.

Is that  bug in AutoRest or the sample swagger file from swagger.io?

I also tried the [Swagger from TheTVDB](https://api-dev.thetvdb.com/swagger.json), where I get what is defiantly a bug in AutoRest:

error: [FATAL] Error generating service model: Object reference not set to an instance of an object.

**Comment by devigned** [comment]
Per the Swagger.io example, placeOrder doesn't have a consumes property and neither does the root, so I get why that is failing. We might need to have some sort of sane default here.

Beyond the sane default, there are mime types we don't handle as of yet. We have only added support for application/json at this point, so anything else will likely cause an error. I think there are ways we could more gracefully degrade the AutoRest generated code in ways that allow the generated code to function even if there are pieces of the Swagger spec that we have not yet implemented.

We do intend on covering the entire spec, but the project is young and we wanted to first concentrate on JSON APIs. While we are filling in the holes in implementation, it would be good for use to provide some sort of a checklist to know the current state of swagger spec implementation.

Per the Swagger from TheTVDB error, we don't ever want to see "Object reference not set to an instance of an object.". We'll look into this and get it fixed.

Thank you for reporting these issues.

**Comment by tjementum** [comment]
Hi. Thanks for feedback. 

I looked into the problem with https://api-dev.thetvdb.com/swagger.json. The "Object reference not set to an instance of an object" occurs because operationId is missing on all paths. I've made some changes, so the operationId defaults to the name of the path (eg. /login, /refresh_token ..). So now I'm able to generate the code without error. I havn't tested the autogenerated code yet, but I will make a fork and maybe a pull-request if it works.

If I read the [Swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) correct the operationId is not required.

**Comment by hovsepm** [comment]
@tjementum, operationID should be unique per swagger spec and defaulting it to the path will not solve the issue in cases when path contains several operations (get, put etc.). Another thing is that users tent to use very long paths which will cause very long method names. e.g. 
```
"paths": {
    "/subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}/unregister": {
      "post": {
```

**Comment by hovsepm** [comment]
Issue with [Swagger.io](http://petstore.swagger.io/v2/swagger.json) is non-repro for latest code in dev branch. Please reopen with more details (adding version of autorest generator) it is still happening.
