### ISSUE TITLE
New rule? Don't repeat enum values, default values or requiredness in the description.

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1973]
/cc @veronicagg, @amarzavery 

Not sure if this rule would make sense or maybe we already track it somewhere?
I see this A LOT when reviewing Swaggers.

**Comment by veronicagg** [comment]
@olydis could you link to an example?

**Comment by olydis** [comment]
@veronicagg Latest encounter: https://github.com/Azure/azure-rest-api-specs/pull/956/files/4f299696e33330ad2a29db8af09717574af751fd#diff-03365d0a4de8c00a8f5a7f72ddc6fbcfR1628

Do we track rules that check for "Get(s)"/"Set(s)" at the beginning of descriptions or check the total number of words (should maybe be at least 3?) - @fearthecowboy will have a current PR that managed to pull all of those cards (a taste: "description: Description")

**Comment by veronicagg** [comment]
@olydis I see. We only currently check for whitespace or empty, we could try to get a bit smarter here, so we'll leave this issue open, though this is one of those in which a human reading the content helps. We should in the meantime at least add one manual rule for these checks. @kirthik could you add this manual rule? thanks!

**Comment by dsgouda** [comment]
Okay, so if I understand correctly we don't want the description to match the name of whatever node they're trying to describe.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
