### ISSUE TITLE
Error while deserializing function with nullable return to xml

### ISSUE THREAD

**Issue by MrBirdman** [Azure/autorest#1976]
Hi,

Autorest generated classes won't compile when generating this json function:

> 
    "/api/DataManager/DoesTechnologyNameExistsInBrand": {
      "post": {
        "tags": [
          "DataManager"
        ],
        "operationId": "DataManager_DoesTechnologyNameExistsInBrand",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "technologyName",
            "in": "query",
            "required": true,
            "type": "string",
            "x-nullable": true
          },
          {
            "name": "brandId",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "x-nullable": false
          },
          {
            "name": "technology",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/tblTechnology"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "boolean",
              "x-nullable": false
            }
          }
        }
      }
    },

This fragment:

```
bool? _tmp_ = null;
                    if (_httpResponse.Content.Headers.ContentType.MediaType == "application/xml" &&
                        XmlSerialization.Root(XmlSerialization.ToDeserializer(e => (bool)e))(System.Xml.Linq.XElement.Parse(_responseContent), out _tmp_))
                    {
                        _result.Body = _tmp_;
                    }
                    else
                    {
                        _result.Body = Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject<bool?>(_responseContent, Client.DeserializationSettings);
                    }
```

Generates an error:

> Argument 2: cannot convert from 'out bool?' to 'out bool'

Because out _tmp is bool but the variable is declared as bool?.

**Comment by fearthecowboy** [comment]
Hmm. Yeah, I don't think that there should be `x-nullable:false ` on a response -- but that's not really the problem. It definitely shouldn't have done that.

On another note, did you really want to support XML in your API? ( ie, `"application/xml", "text/xml",` ) XML has very very very new support, only works for c#, and I wouldn't consider it 100% tested and complete at this point.  I'd recommend that you drop the `/xml` media types.

**Comment by MrBirdman** [comment]
Hi, yeah i've switched off application/xml and it works fine. It is switched on out of the box, i could understand that autorest wouldn't generate proper code if i messed with my rest configuration, but since it's the default behaviour it's a bit strange ;)
Why there shouldn't be an x-nullsnle:false on a response? Shouldn't i be able to return a bool? or a bool if i want to? :)

**Comment by fearthecowboy** [comment]
Off the top of my head, I don't recall if nullable return types was tested for. @olydis might know.. It's possible that it was. 

Still, as a return type, that's a harsh reality for your users-- `true` , `false` , or `maybe`?

**Comment by olydis** [comment]
It was not! Also, we have certain hard-coded shortcuts for the very scenario we created XML serialization for, so I wouldn't expect too much. But of course, this looks like a simple fix, I'll look into it :-)

**Comment by olydis** [comment]
Even better: I just realized that AutoRest didn't support non-nullable return types **at all** until 25 days ago (introduced by https://github.com/Azure/autorest/pull/1804), so it is even younger than our XML support.

**Comment by MrBirdman** [comment]
@fearthecowboy Well maybe more like true,false, not set. But this is not my design, i'm just moving an already working system to REST, and it's quite big so i can't fix every call :)
@olydis Cheers! :)

**Comment by HowardvanRooijen** [comment]
I'm experiencing the same problem - although it's not just generating the same non-compiling method above - it's also generating a missing method:

```
internal static LocalizedContentRequest XmlDeserialize(XElement payload)
{
    var result = new LocalizedContentRequest();
    var deserializeLocalizedContent = XmlSerialization.CreateListXmlDeserializer(XmlSerialization.ToDeserializer(e => LocalizedContent.XmlDeserialize(e)), null);
    IList<LocalizedContent> resultLocalizedContent;
    if (deserializeLocalizedContent(payload, "LocalizedContent", out resultLocalizedContent))
    {
        result.LocalizedContent = resultLocalizedContent;
    }
    return result;
}
```
Where .XmlDeserialize(e) in LocalizedContent.XmlDeserialize(e) doesn't exist.

If XML support is only for a specific scenario, is it not possible to turn it off by default and enable by configuration switch?

The added complexity I have is that one of my operations has to return an XML document (it's a signed XML document) - which seems to trigger this behaviour.

**Comment by MrLinDowsMac** [comment]
I'm also experiencing this problem. Autorest generates from swagger metadata lines like this:
```
 if (_httpResponse.Content.Headers.ContentType.MediaType == "application/xml" &&
                        XmlSerialization.Root(XmlSerialization.ToDeserializer(e => (object)e))(System.Xml.Linq.XElement.Parse(_responseContent), out _tmp_))
                    {

```
That cannot be compiled because "Xmlserialization doesn't exist in current context"

**Comment by fearthecowboy** [comment]
Quick Fix :

You can have AutoRest exclude the generation of XML serialization by creating a configuration file 

FILENAME: readme.md 

~~~ markdown
# My Swagger API

> see https://aka.ms/autorest

``` yaml
input-file: YOURSWAGGERFILE.json
  
directive:
  # disable xml serialization
  - from: swagger-document
    where: $..consumes
    transform: > 
      result = [];
      for( const each of $) {
          if( each != "application/xml" && each != "text/xml" ) {
              result.push(each)
          }
      }
      return result
      
  # disable xml serialization
  - from: swagger-document
    where: $..produces
    transform: > 
      result = [];
      for( const each of $) {
          if( each != "application/xml" && each != "text/xml" ) {
              result.push(each)
          }
      }
      return result

```
~~~

Place that file in the same folder as the `.json` file  and run 

`autorest readme.md --csharp`

And it should do a lot better.

**Comment by fearthecowboy** [comment]
(and yes, we'll stick in a switch to enable it, so that it's off by default)

**Comment by olydis** [comment]
This is off by default now. Please reopen or post a new issue if you encounter related issues.
