### ISSUE TITLE
Port is omitted from URL in generated client code

### ISSUE THREAD

**Issue by ruant** [Azure/autorest#1977]
If there is a port specified -Input URL it's being omitted when the client code is being generated.

Shouldn't this be kept? Not all APIs run on 80/443.

**Comment by fearthecowboy** [comment]
O_o ... this would seem to be not quite right.

Do you have an example of one?

**Comment by ruant** [comment]
Sorry for not replying sooner.

When I did `autorest -Input http://localhost:3150/swagger/v1/swagger.json`

The generated code was like this:

/// <summary>
/// Initializes client properties.
/// </summary>
private void Initialize()
{
    this.BaseUri = new Uri("http://localhost/");
    .....
}

Maybe it's my version. Just found out that I'm using 0.16.0.0.

---

I'm not able to check if the latest version fixes the issue or not due to another issue:
```
FATAL: Error parsing swagger file. Unexpected token when deserializing object: String. Path 'paths./api/Categories.get.tags[0]', line 19, position 31.
```

**Comment by olydis** [comment]
Huh? The `Input` you specify has nothing to do with the base URI of the generated client. That is derived from the Swagger, and I'm fairly certain that we support that. Also, AutoRest has versioned a lot since the version you've used.

Please reopen if this is still an issue or you have questions.
