### ISSUE TITLE
SkuModelValidation too strict

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1979]
It complains that `Sku Model is not valid. A Sku model must have name property.` - however, there is a `name` property, and it has type `string` (I guess it fails since the type is `$ref`ed to instead of being inline).

Example where it fails:
https://github.com/pankajsn/azure-rest-api-specs/blob/09dc69af66af20ca869f4513600ba07dbf28ce8e/arm-logic/2016-06-01/swagger/logic.json#L3696

**Comment by sarangan12** [comment]
Task completed
