### ISSUE TITLE
Discussion: JSON string parameter

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#198]
Hi,

The parameters of our operation looks like below.
```js
 "Workflow": {
    "type": "object",
    "properties": {
        "definition": {
            "$ref": "#/definitions/Object", // this is arbitrary JSON
            "description": "Gets or sets the definition."
        },
    }
}
```
It has a property called "definition" that is a JSON object representing the definition of a workflow. Instead of having it as a Object/JToken in the data model, we want the data model to be a JSON string like below.
```csharp
class Workflow {
    public string Definition { get; set; } // This is a JSON string. eg "{ \"foo\": \"bar\"}"
}
```
We want the JSON string to be converted to JSON object and be embedded in the request as JSON object, and The JSON object in the response will be converted to a JSON string as well.

Is this something that we could do now? Or is this something that we could consider support?

**Comment by markcowl** [comment]
@tonytang-microsoft-com schema-less json is best modeled in Swagger as an Object with no properties.  Can you try this modeling and see how it fits your scenario?

**Comment by tonytang-microsoft-com** [comment]
I currently modeled it as a plain Object. However, user would need to convert between Object and string. For a more friendly developer experience of our SDK, I would like to provide string as the type instead of Object.

I could manually change the generated code to do the conversion, but that means I will need to do it every time the code is regenerated. Adding a helper method in a separate file would avoid having to manually update the generated code, that that ends up leaving unfriendly API in the SDK. Thus it would be good if there's a way to do it in swagger.

**Comment by markcowl** [comment]
@tonytang-microsoft-com Do we really want string, or do we want JToken or JObject?  It seems like the issue with Object is discoverability, and string leaves the possibility of throwing because the provided string cannot be parsed correctly.

**Comment by tonytang-microsoft-com** [comment]
@markcowl For us, I think the issue is more of a developer experience, and discoverability might also be a concern. The value of the property is usually saved in a JSON file or in some blob storage. User opens the JSON file and sees the content. In other words, user *thinks* it as a JSON string rather than a JToken, which is a concept that user may not even be aware. Thus it would be more convenient if user simply work with string, and don't require them to convert the string to a JToken.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
