### ISSUE TITLE
ProvidersPathValidation: update rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1980]
Pattern needs to be better explained, message needs update, "operations" needs to be taken out, and pattern explained, plus additional documentation externally.

Additionally, looks like patter of /typename1/{typename1type} does not require the "{" "}", this value could be just one and therefore not a parameter, so the verification should be more in the line of "even" positions starting wiht the first "typename1" should be typenames, and "odd" positions typename1names, we probably want to flag the ones that don't have parameters as warnings, for the purpose of asking the author, is that's the intent (meaning that there's only one acceptable value for that typenametype. @amarzavery @ravbhatnagar please correct this understanding as necessary.

Please run on top 5 RPs to evaluate violations.
Needs to be discussed with Gaurav.

ID: ?
Category: RPC Violation
Severity: Warning

**Comment by dsgouda** [comment]
I believe "/operations" needs to be taken out, I was wondering if we could just say 
subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/namespace/type1name/{type1value}/type2name/{type2value}/<operationName>
where <operationName> can be empty
@veronicagg I don't think I understand the intent as you described. As per my understanding, we simply want to ensure that urls conform to the pattern ``` .../subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/.../providers/namespace/typename/{typevalue}/<operationName>``` and I have already run this against the rest spec repo with more or less accurate results, the only improvement needed here was the messaging
@amarzavery @ravbhatnagar please confirm

**Comment by veronicagg** [comment]
@dsgouda let's get confirmation on the statement I made above from @ravbhatnagar, as this specific rule was discussed further a little later.
