### ISSUE TITLE
CollectionObjectPropertiesNamingValidation: update rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1984]
This rule should only apply for x-ms-pageable operation.

**Comment by vishrutshah** [comment]
@dsgouda QQ: Regarding this rule as seems like you are the initial author :)

Can ARM post operation be a `x-ms-pageable`? Do we have any example?

Reference: https://github.com/Azure/autorest/blame/master/src/modeler/AutoRest.Swagger/Validation/CollectionObjectPropertiesNamingValidation.cs#L33

**Comment by vishrutshah** [comment]
Duplicate Rule: https://github.com/Azure/autorest/issues/1924 but waiting on question to make sure I understand the rule correctly.

**Comment by vishrutshah** [comment]
Closing it as rule does not hamper the correctness and accuracy.
