### ISSUE TITLE
New rule: For a PUT operation, the response body of 200 should be an Azure Resource

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1986]
it's ubermost "allOf" must have x-ms-azure-resource:true.

**Comment by dsgouda** [comment]
Need more information like ValidationCategory, Id

**Comment by brjohnstmsft** [comment]
@veronicagg I assume this rule will not apply to data plane APIs, correct?

**Comment by veronicagg** [comment]
@brjohnstmsft correct, our linter rules are currently all about management plane (ARM), we are ignoring errors on swaggers that are not ARM for now, we'll introduce categories and applicability of rules a little later.

**Comment by veronicagg** [comment]
@dsgouda I'd do RPC Violation for this one, please confirm with Gaurav. Id, please choose next number based on currently implemented ones, and add it to the checklist. thanks!

**Comment by dsgouda** [comment]
Rule added
