### ISSUE TITLE
New rule: operationresults and azureasyncoperation paths should not be documented

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#1993]
Long running azure rest apis can return links to an /operationResults URI (with Location header) and /azureAsyncOperation URI (with Azure-AsyncOperation header). Should these /operationResults and /azureAsyncOperation APIs be documented in Swagger? We started doing this but I’m not convinced that it’s the right thing to do.

I believe that changing an API to return different paths for Location or AzureAsyncOperation should not be considered to be a breaking change. The reason why this would not be a breaking change is because all current clients get the URL based on the header values, not based on prior knowledge of where the URI should be. 

For example, a PUT to …/myresource/{name} might return
Location = …/myresource/{name}/operationResults/{id}
Azure-AsyncOperation = …/myresource/{name}/azureAsyncOperation/{id}
And then we might change this to instead return 
Location = …/locations/{locationId}/operationResults/{id}
Azure-AsyncOperation = …/ locations/{locationId}/azureAsyncOperation/{id} .

If the above is accurate, then I think it’s clear that these paths are not really part of the public API and are more of an implementation detail that should not be publicly documented, since clients should just GET the URI that they are told (by headers) and should not have any prior expectations on what the path will be.

**Comment by veronicagg** [comment]
@amarzavery, @johanste, should we look into enforcing this rule?

**Comment by johanste** [comment]
This plays into the whole "how should we model long running operations" recommendation. I'm not sure how much value there is, in general, for anyone (today) to include the paths returned in location headers as paths in the swagger. Unless there is a way to enumerate current pending operations, there is very little that a client can do with the API (as @jaredmoo points out above).

**Comment by veronicagg** [comment]
@dsgouda This would be an SDK Violation and Warning, could you evaluate how we could implement this rule?

**Comment by veronicagg** [comment]
Just heard comments of this rule not being necessarily what we want. 
@ravbhatnagar do you have thoughts on this from ARM side? should the operations be documented in swagger? what's the guidance?

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
