### ISSUE TITLE
New rule: operation descriptions should be in third person

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#1994]
No: "Get a widget."
Yes: "Gets a widget."

I believe this is a generally accepted practice across most programming languages. 

e.g. [Javadoc style guide](http://www.oracle.com/technetwork/articles/java/index-137868.html): "Use 3rd person (descriptive) not 2nd person (prescriptive)."

I can't find an explicit guideline but .NET framework follows this consistently, e.g. https://msdn.microsoft.com/en-us/library/3wcytfd1(v=vs.110).aspx "Adds an object to the end of the List<T>.List<T>.Add Method (T)"

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
