### ISSUE TITLE
Microsoft.Rest.ClientRuntime net45 is referencing Newtonsoft 6

### ISSUE THREAD

**Issue by johnwc** [Azure/autorest#2007]
The two .NetStandard's reference Newtonsoft v9, but net45 references v6.  Was this overlooked or on purpose?  It is causing reference issues with Azure SDKs that reference this along with Netwonsoft v9.

**Comment by olydis** [comment]
Note that the [ClientRuntime](https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ClientRuntime) is part of the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) repo - or is this an issue about generated code?

**Comment by johnwc** [comment]
Someone should update the link in nuget then, as it's link for the project is here.

**Comment by olydis** [comment]
> it's link for the project is here

Where?
