### ISSUE TITLE
Wrong implementation for 'multi' collectionFormat in 'formData'

### ISSUE THREAD

**Issue by soldierq** [Azure/autorest#2012]
I'm referring the latest release - 1.0.1-20170313-0919-preview.

I have a Web API to upload a file along with some additional metadata, the function signature is as below:
`public IActionResult UploadFile([FromForm]IFormFile file, [FromForm]DateTime dateCreated, [FromForm]DateTime dateModified, [FromForm]string hash, [FromForm] string[] tags)`

The problem happens for the last parameter 'tags' string array.

I checked the swagger.json, it is generated correctly as below for 'tags':

> {
>   name: "tags",
>   in: "formData",
>   required: true, 
>   type: "array",
>   items: {
>     type: "string"
>   },
>   collectionFormat: "multi"
> }
> 

And Swagger-UI is also working fine, with the following request payload for 'tags' parameter with value '1', '2', '3':
> 
> ------WebKitFormBoundaryYfvryJ4iazDjH6CJ
> Content-Disposition: form-data; name="tags"
> 
> 1
> ------WebKitFormBoundaryYfvryJ4iazDjH6CJ
> Content-Disposition: form-data; name="tags"
> 
> 2
> ------WebKitFormBoundaryYfvryJ4iazDjH6CJ
> Content-Disposition: form-data; name="tags"
> 
> 3
> ------WebKitFormBoundaryYfvryJ4iazDjH6CJ--

However, when using AutoRest to generate the proxy classes, it has the following outcome for 'tags' which I don't think it is correct:
```
  if (tags != null)
  {
                StringContent _tags = new StringContent(SafeJsonConvert.SerializeObject(tags, SerializationSettings).Trim('"'), System.Text.Encoding.UTF8);
                _multiPartContent.Add(_tags, "tags");
   }

```
The result of above codes generates a single JSON string for the 'tags' such as "["1","2","3"]" instead of an form-data array in HTTP request mentioned above.
Thus at the server side, it also gets a single JSON string as the value instead of a string array.

 I tried to correct the error by manually change the above generated codes to:
```
            if (tags != null)
            {
                foreach (string tag in tags)
                {
                    StringContent _tag = new StringContent(tag.Trim(), System.Text.Encoding.UTF8);
                    _multiPartContent.Add(_tag, "tags");
                }
            }
```
And it works fine.

Please check and get it fixed, thanks.

**Comment by olydis** [comment]
Oh, I think we fixed this, sorry for not getting back! Please reopen if this is still an issue with latest AutoRest 🙂

**Comment by Sergey-Maystrenko** [comment]
Hi, 
I have the same problem with latest version of the Autorest
Could you please check code again.
