### ISSUE TITLE
Ruby SDK Generation process does not include models in client

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest#2013]
Ruby SDK Generation process does not include models in client and is thus broken if the swagger operations does not belong to a group.

**Comment by ykitamura-mdsol** [comment]
I was about to report the same issue.

I got the following error when I executed `Petstore::SwaggerPetstore.new.get_pet_by_id(223344)`:
```
MsRest::DeserializationError: {
  "exception_message": "uninitialized constant Petstore::SwaggerPetstore::Pet",
  "message": "Error occurred in deserializing the response",
  "stacktrace": [
    "../lib/generated/petstore/swagger_petstore.rb:697
   :
```

As a quick fix, I added `include Petstore::Models`  to [Petstore::SwaggerPetstore](https://github.com/Azure/autorest/blob/v1.0.1-20170315-2300-nightly/Samples/petstore/Ruby/generated/petstore/swagger_petstore.rb#L9) class:

```diff
module Petstore
  #
  # A service client - single point of access to the REST API.
  #
  class SwaggerPetstore < MsRest::ServiceClient
   include MsRest::Serialization
+  include Petstore::Models
```

FYI @jcarres-mdsol

**Comment by sarangan12** [comment]
Task completed
