### ISSUE TITLE
New rule: body parameters should be named 'parameters'

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2019]
An operation's body parameters should be named 'parameters', e.g. below. This is what is expected by default by [CLI generic update command code](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L211) (see `setter_arg_name`). CLI does allow this be overridden (by specifying e.g. `setter_arg_name=database_threat_detection_policy`), but it's a minor gotcha that can be detected early at the Swagger level.

      "put": {
        .....
        "parameters": [
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          },
          ......
          {
            "name": "parameters",
            "in": "body",
            "description": "The database Threat Detection policy.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DatabaseSecurityAlertPolicy"
            }
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          }
        ],

**Comment by sarangan12** [comment]
Task Completed

**Comment by jaredmoo** [comment]
Nice, thanks!
