### ISSUE TITLE
Error modeling generates code with poor output for the final user

### ISSUE THREAD

**Issue by daviburg** [Azure/autorest#2022]
_Background:_

Here’s some info on how error definitions are handled by AutoRest:
[https://github.com/Azure/autorest/blob/bf30da3ae09718d336a1eca49afd7d053d83657e/docs/developer/guide/defining-clients-swagger.md#error-modeling](https://github.com/Azure/autorest/blob/bf30da3ae09718d336a1eca49afd7d053d83657e/docs/developer/guide/defining-clients-swagger.md#error-modeling) 

Additional info here as well: [https://github.com/Azure/azure-rest-api-specs-pr/blob/master/documentation/creating-swagger.md#negative-responses](https://github.com/Azure/azure-rest-api-specs-pr/blob/master/documentation/creating-swagger.md#negative-responses) 

A related discussion here though technical details may not directly apply
[https://github.com/Azure/autorest/issues/1890](https://github.com/Azure/autorest/issues/1890)

_The issue:_

I’ve followed the recommended way above to do the error modeling in Azure Rest API and it has a detrimental effect to the output of PowerShell cmdlets once the SDK is regenerated with it.

When the error was modeled in swagger like this and not per the recommendation:

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/IntegrationAccountAgreement"
            }
          }
        }

If the user types a non-existent resource group name as input (imagine he made a typo), the error exception comes from the SDK as:

                              ex           {"Resource group 'Random83da135' could not be found."}           System.Exception {Microsoft.Rest.Azure.CloudException}
                              Body      {Microsoft.Rest.Azure.CloudError}           Microsoft.Rest.Azure.CloudError
                                Code     "ResourceGroupNotFound"        string
                             Details  Count = 0x00000000        System.Collections.Generic.IList<Microsoft.Rest.Azure.CloudError> {System.Collections.Generic.List<Microsoft.Rest.Azure.CloudError>}
                                Message              **"Resource group 'Random83da135' could not be found."**               string

AzurePSCmdlet’s WriteExceptionError will write (only) the **string in bold** as cmdlet output.

Get-AzureRmIntegrationAccountAgreement -ResourceGroupName "Random83da135" -IntegrationAccountName "DoesNotMatter" -AgreementName "DoesNotMatter"
Get-AzureRmIntegrationAccountAgreement : Resource group 'Random83da135' could not be found.
At line:1 char:1
 Get-AzureRmIntegrationAccountAgreement -ResourceGroupName "Random83da ...
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : CloseError: (:) [Get-AzureRmIntegrationAccountAgreement], CloudException
     FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountAgreementCommand


When the error is modeled in swagger per the recommendation like this:

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/IntegrationAccountSession"
            }
          },
          "default": {
            "description": "Logic error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }

The error exception comes from the SDK as:

                              ex           {**"Operation returned an invalid status code 'NotFound'"**}              System.Exception {Microsoft.Azure.Management.Logic.Models.ErrorResponseException}
                              Body      {Microsoft.Azure.Management.Logic.Models.ErrorResponse}                Microsoft.Azure.Management.Logic.Models.ErrorResponse
                              Error      {Microsoft.Azure.Management.Logic.Models.ErrorProperties}                Microsoft.Azure.Management.Logic.Models.ErrorProperties
                                Code     "ResourceGroupNotFound"        string
                                Message              "Resource group 'Random83da135' could not be found."               string

**In bold** string is returned by the cmdlet.

Get-AzureRmIntegrationAccountGeneratedIcn -ResourceGroupName "Random83da135" -Name "DoesNotMatter" -AgreementName "DoesNotMatter"
Get-AzureRmIntegrationAccountGeneratedIcn : Operation returned an invalid status code 'NotFound'
At line:1 char:1
 Get-AzureRmIntegrationAccountGeneratedIcn -ResourceGroupName "Random8 ...
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : CloseError: (:) [Get-AzureRmInte...untGeneratedIcn], ErrorResponseException
     FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountGeneratedIcnCommand

Lacking the type and lacking the name of the resource that is not found is much less informative. Further the “invalid status code” complain is somewhat confusing: “Not found” is an expectable result for an attempt to get something.

The underlying generated code is like this:

```
            HttpStatusCode _statusCode = _httpResponse.StatusCode;
            cancellationToken.ThrowIfCancellationRequested();
            string _responseContent = null;
            if ((int)_statusCode != 200)
            {
                var ex = new ErrorResponseException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                try
                {
                    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                    ErrorResponse _errorBody =  Rest.Serialization.SafeJsonConvert.DeserializeObject<ErrorResponse>(_responseContent, Client.DeserializationSettings);
                    if (_errorBody != null)
                    {
                        ex.Body = _errorBody;
                    }
                }
                catch (JsonException)
                {
                    // Ignore the exception
                }
                ex.Request = new HttpRequestMessageWrapper(_httpRequest, _requestContent);
                ex.Response = new HttpResponseMessageWrapper(_httpResponse, _responseContent);
                if (_shouldTrace)
                {
                    ServiceClientTracing.Error(_invocationId, ex);
                }
                _httpRequest.Dispose();
                if (_httpResponse != null)
                {
                    _httpResponse.Dispose();
                }
                throw ex;
            }
```

I agree with Mark Cowlishaw in an internal thread that "the C# generator should be able to throw good errors for known error codes, whether or not there is a default error model."

@markcowl
@veronicagg

#https://github.com/Azure/azure-sdk-for-net/pull/2908
#pullrequestreview-23778630

**Comment by fearthecowboy** [comment]
Proper handling of error result types is something I want to handle in the vNext generators and runtime.
