### ISSUE TITLE
VS integration should work with .NET Core projects

### ISSUE THREAD

**Issue by mjrousos** [Azure/autorest#2023]
Currently, it's possible to create an Autorest client by right-clicking on a project in Visual Studio and selecting "Add -> REST API Client...".
![image](https://cloud.githubusercontent.com/assets/10077254/24020121/3fe6311c-0a71-11e7-9b2e-6f75d785067d.png)

But this menu option is only available for .NET Framework projects even though the Autorest NuGet package and generated code work fine with .NET Core.

To make Autorest easier to use in .NET Core scenarios, the same 'Add REST API Client' option should be available through Visual Studio's UI when editing a .NET Core project.

**Comment by olydis** [comment]
created rollup issue
