### ISSUE TITLE
Consider adding an auto-generated wrapper around code generation comments

### ISSUE THREAD

**Issue by drmohundro** [Azure/autorest#2032]
I noticed that the comment header puts a comment at the top of source that includes that the code was generated by the AutoRest Code Generator with a version... this makes sense. (see https://github.com/Azure/autorest/blob/master/src/core/AutoRest.Core/Settings.cs#L22-L23).

What I'd like to propose is, for C# in particular or other CLR languages, wrapping it in an `<auto-generated>` tag so that code analyzers can know to skip these files, particularly for stylistic issues (e.g. StyleCop).

So, instead of:

```csharp
// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
```

I'd like to see:

```csharp
// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
```

This would these files follow the convention that other auto-generated files have, particularly when used in Visual Studio (such as from the "Add > REST API Client..." dialog).

**Comment by benjaminjrobin** [comment]
+1

**Comment by fearthecowboy** [comment]
:+1: indeed!

**Comment by olydis** [comment]
made it into 2.0 (next stable release)
