### ISSUE TITLE
Missing framework debian.8-x64

### ISSUE THREAD

**Issue by saikatguha** [Azure/autorest#2045]
I am using the official Microsoft dotnet docker image in my CI environment: 
```
FROM microsoft/dotnet:1.1-sdk
RUN ... # install nodejs, autorest
RUN autorest --reset
```

AutoRest detects the OS as `debian.8-x64` and throws the error 
```Unable to find framework for debian.8-x64```

However, AutoRest _does_ support `debian-x64` as per assets in
  https://api.github.com/repos/azure/autorest/releases/tags/dotnet-runtime-1.0.3

AutoRest should either release framrwork assets for `debian.8-x64`, or it should use `debian-x64` as a fallback.

##### Expected
AutoRest works on official dotnet images

##### Actual
AutoRest does not work on official dotnet images

**Comment by fearthecowboy** [comment]
Ah. Apparently a flaw in my platform detection logic. 

Lemme see what I can do.

**Comment by fearthecowboy** [comment]
Can you try it now?

``` bash
# grab the latest 
npm install -g autorest

# reset the installed binaries
autorest --reset 

```

if that doesn't work try this:

``` bash
# force it to use a specific runtime.
autorest --reset --runtime-id=debian-x64 
```

**Comment by olydis** [comment]
@saikatguha I'll assume this is fixed now. Please reopen if this is still an issue.
