### ISSUE TITLE
OpenApi3.0 Modeler?

### ISSUE THREAD

**Issue by erendrake** [Azure/autorest#2047]
Now that OpenAPI3 is in preview, does the admin team know how they are planning to use this new spec?

I imagine it this would be a new modeler project? 
what timeline would you start accepting PRs for this? 
some features like links would likely require changes to the rest client package, how difficult will that be?

**Comment by erendrake** [comment]
There is a pretty good review of the upcoming spec here
https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

I am super pumped for links. I have wanted swagger to have hypermedia support forever

**Comment by fearthecowboy** [comment]
We're going to do a bit of prep work in April, with full design and dev work starting in May.

In the first week of April, we're going to be dropping some pretty significant changes to AutoRest, and this is setting us up for creating a whole new era of Modelers and Generators that are far less limiting than what we currently have.

**Comment by erendrake** [comment]
I'm very happy this is on your radar and I think you are right to say the modeler needs some love. Thank you
