### ISSUE TITLE
Error: spawn dotnet ENOENT

### ISSUE THREAD

**Issue by sorvis** [Azure/autorest#2060]
After I installed autorest through npm as described on in the instructions I get the following error when I run autorest --help

I'm running Windows 7.

>  autorest --help
> AutoRest Code Generator
> (c) 2017 Microsoft Corporation. https://aka.ms/autorest
> Build Information
>   Autorest Bootstrapper :  0.9.21
>   NetCore framework :      1.0.3
>   Latest Core Installed :  1.0.1-20170323-2300-nightly
>   Requested Core Version : <none>
> 
> Output Verbosity
> 
>   --verbose            show verbose output information
>   --debug              show internal debug information
>   --quiet              suppress output
> 
> Versions
> 
>   --list-installed     show all installed versions of AutoRest tools
>   --list-available=nn  lists the last nn releases available from github
>                         (defaults to 10)
> 
> Installation
> 
>   --version=version    uses version of AutoRest, installing if necessary.
>                         for version you can
>                         use a version label (see --list-available) or
>                           latest         - get latest nightly build
>                           latest-release - get latest release version
>   --reset              remove all installed versions of AutoRest tools
>                         and install the latest (override with --version)
> 
> Using AutoRest
> { Error: spawn dotnet ENOENT
>     at exports._errnoException (util.js:1018:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn dotnet',
>   path: 'dotnet',
>   spawnargs:
>    [ 'C:\\Users\\me\\.autorest\\plugins\\autorest\\1.0.1-20170323-2300-nightly\\AutoRest.dll',
>      '-Help' ] }
>

**Comment by fearthecowboy** [comment]
O_o

Can you try: ` autorest --reset` ? 

It seems it's unable find something.

G

**Comment by sorvis** [comment]
Sure, here is the output:

> autorest --reset
> AutoRest Code Generator
> (c) 2017 Microsoft Corporation. https://aka.ms/autorest
> Downloading https://github.com/Azure/autorest/releases/download/dotnet-runtime-1.0.3/dotnet-win7-x64.1.0.3.zip
>         to  C:\Users\me.autorest\frameworks
> Downloading https://github.com/Azure/autorest/releases/download/v1.0.1-20170323-2300-nightly/autorest-1.0.1-20170323-2300-nightly.zip
>         to  C:\Users\me.autorest\plugins\autorest\1.0.1-20170323-2300-nightly
> Use --help to get help information.

It seems to still be throwing the same error when I run autorest --help

**Comment by fearthecowboy** [comment]
O_O

I just did the same thing, but it works for me -- but I'm on Win10.

Random thought:  are you on a 32 bit version of Win7? Maybe  the detection isn't as good as I thought.

also what happens if you run  (assuming that `me` is your username)

`C:\Users\me\.autorest\frameworks\dotnet.exe  C:\Users\me\.autorest\plugins\autorest\1.0.1-20170323-2300-nightly\AutoRest.dll --help`

**Comment by sorvis** [comment]
Progress! That gets us this exception:

> System.IO.FileLoadException was unhandled
> Message: Could not load file or assembly 'AutoRest, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

I'm actually on the 64-bit version of Windows 7.

**Comment by fearthecowboy** [comment]
Ooooh. 

That's different. We may have a problem in strong naming somewhere. Likely most of us have sn verification turned off, and that's why we're not seeing it.

if you have Visual Studio installed, you should be able to use `sn -Vr *` in a vs command line prompt to disable that.

**Comment by sorvis** [comment]
Yes, running sn -Vr * does allow it to run properly. Is there a long term fix we can do to make this work without requiring sn to be disabled?

**Comment by fearthecowboy** [comment]
I'll make sure we fix up strong-naming soon.

**Comment by sorvis** [comment]
OK, thank you very much for your help and hard work!
