### ISSUE TITLE
[Potential Bug] Are api-version pattern case-sensitive? 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#2063]
Linter Rule [APIVersionPattern](https://github.com/Azure/autorest/blob/a2d51c88366b683e1ca92cbeceb91c16b4ffdb6c/src/modeler/AutoRest.Swagger/Validation/APIVersionPattern.cs#L17)

**Reported by** @brjohnstmsft
**Issue:** M3012: "API Version must be in the format: yyyy-MM-dd, optionally followed by -preview, -alpha, -beta, -rc, -privatepreview." Our preview versions have ended in -Preview (with a capital P) for almost four years now, and I'm sure our service is not the only Azure service to do so. IMO this rule has a bug.
**PR:** https://github.com/Azure/azure-rest-api-specs-pr/pull/47

@ravbhatnagar : Can you please verify wether this requirement is case-sensitive or not?

**cc:**
@veronicagg

**Comment by ravbhatnagar** [comment]
For newer APIversions, we should enforce this. So PrivatePreview should be flagged as violation. Existing one is ok.

**Comment by vishrutshah** [comment]
Being said that "Existing one is ok", I'd consider that the rule is accurate and we should keep continue to report this violation as RPCViolation under Error severity and now when we define suppression we should add them for existing services. Is my interpretation right?

**Comment by brjohnstmsft** [comment]
@vishrutshah Who defines these suppressions? Can service teams define them?

**Comment by vishrutshah** [comment]
@brjohnstmsft We are still working towards that feature of suppression we'll keep you posted on how & when we'll have them ready for service teams. 

As of today, it's not Incorporated yet.

**Comment by veronicagg** [comment]
@vishrutshah is this a non-issue? should we close it?

**Comment by vishrutshah** [comment]
@veronicagg As per @ravbhatnagar the rule only is applicable to the newer RPs not existing RPs so we need to take care for these cases using suppression. We should close this one or move to the category somewhere we are collecting the buckets of rules would fall on either new RPs v/s old RPs.

**Comment by ravbhatnagar** [comment]
@vishrutshah @veronicagg - Yes, we can continue flagging it for existing RPs too and ask them to fix. If there is a case that RP cant fix it in the next API version, we can add a suppression.

**Comment by veronicagg** [comment]
thanks, closing this issue then.
