### ISSUE TITLE
[Potential Bug] Should camelCase apply to @odata.***

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#2064]
Linter Rule [DefinitionsPropertiesNamesCamelCase](https://github.com/Azure/autorest/blob/1fbf2aa7ca0fd65c9421e3043062e3f14e0aa5f6/src/modeler/AutoRest.Swagger/Validation/DefinitionsPropertiesNamesCamelCase.cs#L57)

**Reported by** @brjohnstmsft
**Issue:** M3016: "Property named: "@odata.type", for definition: "Analyzer" must follow camelCase style. Example: "@odata.type"." I don't understand why the example exactly matches the property name. In any case, the casing of this name is dictated by the OData protocol and we cannot change it. Same for "@odata.etag"
**PR:** https://github.com/Azure/azure-rest-api-specs-pr/pull/47

@ravbhatnagar : Can you please verify wether this requirement is valid for odata type?

**cc:**
@veronicagg

**Comment by brjohnstmsft** [comment]
This requirement is not valid for OData annotations. Here is the relevant part of the OData specification: http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata03/os/odata-json-format-v4.0-errata03-os-complete.html#_Toc453766627

**Comment by dsgouda** [comment]
To minimize the scope of exceptional cases, I will modify the code to ignore cases where the property names start with `@odata.` Feel free to point out any edge cases we can run into.

**Comment by brjohnstmsft** [comment]
@dsgouda If you plan to run these rules on data plane specs, then please exclude all property names that start with `@`. Built-in annotations are covered by `@odata`, but services are free to define their own custom annotation, which can have any name as long as it starts with `@`.

**Comment by dsgouda** [comment]
@brjohnstmsft Thanks, appreciate that!

**Comment by veronicagg** [comment]
@dsgouda the rule may be looking for '@' and in this case, it doesn't look to have it, we may need to ignore starting with "odata" as well.
