### ISSUE TITLE
[Linter] There should be rule that should ensure consistency in paging on a resource when listingbySubscription and listingByResourceGroup

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#2067]
Either both should be pageable or both should not be pageable. It doesnt make sense to make one pageable and other not pageable.

Actual issue:
https://github.com/Azure/azure-rest-api-specs/issues/1070
/cc @ravbhatnagar @veronicagg

**Comment by veronicagg** [comment]
@sarangan12 when you get to this issue, could you follow up on what this should be?

**Comment by sarangan12** [comment]
Task completed
