### ISSUE TITLE
"Unable to find framework for null" - incorrectly asserting that Dotnet Framework not installed.

### ISSUE THREAD

**Issue by schul016** [Azure/autorest#2069]
I ensured that I had node version 6.10.0 being used and that gulp was installed globally.  After installing autorest with 

```
npm i -g autorest
```
... I then run 

```
autorest --verbose
``` 

... and see the following:

```
>autorest --verbose
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
[0:24:56] Requested '1.0.1-20170325-2300-nightly' version
[0:24:56] Dotnet Framework not installed. Attempting to install it.
Unable to find framework for null
```

But running 

```
dotnet --version
```
... tells me I have 1.0.0 installed.  I am unable to build any client libraries from a swagger.json file, here is that output:

```
>autorest -Input C:\Users\Ryan\Downloads\NewDeployR\SwaggerFiles\swagger.json -CodeGenerator CSharp -OutputDirectory C:\Users\Ryan\Downloads\NewDeployR\ClientLibrary -Namespace SwaggerTest --verbose
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
[0:30:19] Requested '1.0.1-20170325-2300-nightly' version
[0:30:19] Dotnet Framework not installed. Attempting to install it.
Unable to find framework for null
```
Appreciate any insights.

**Comment by schul016** [comment]
I see this is similar to [issue #2037](https://github.com/Azure/autorest/issues/2037), and in response to the additional information requested there, I am running this on Windows 10 x64.

**Comment by fearthecowboy** [comment]
I'm adding a couple of things to see if we can track this down:
- more information as to why it's not determining the runtimeID
- an overidable switch to forceably set the runtimeID

**Comment by fearthecowboy** [comment]
@schul016

I have updated the `autorest` package in npm.

- it should hopefully say something when it doesn't know what it's doing.
- you can override the platform detection, and force it to do the right thing with:

``` batch
# install the x64 build for windows and it's runtime.
> autorest --reset --runtime-id=win7-x64
```

**Comment by schul016** [comment]
Running 

```
autorest --rest --runtime-id=win7-x64
```

allowed autorest to complete initialization.  I was able to generate and use a C# library from a swagger definition after this.  Thank you for the fix!
