### ISSUE TITLE
Linter complains about missing description in a referenced swagger file

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/autorest#2072]
For example

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/214861168 complains about NetworkInterfaceIPConfigurationPropertiesFormat / publicIPAddress property which is defined in 

https://github.com/jobatzil/azure-rest-api-specs/blob/02be03fee65b3378ad3f6da88e5c40aae8d6e4cf/arm-network/2017-03-01/swagger/networkInterface.json#L387

**Comment by vishrutshah** [comment]
Seems like rule should not be fired for the model property with "$refs". 

I'll look into the rule and send PR to fix it.

**Comment by veronicagg** [comment]
@vishrutshah should we not check on the referenced model? I was thinking we needed to provide an appropriate path to the definition (with the file that actually the violation is at).

**Comment by vishrutshah** [comment]
I think "check on the referenced model" would be covered by the same rule when that rule gets fired for that model.

**Comment by vishrutshah** [comment]
As per offline sync, the scenario @veronicagg brought was "If definitions are in separate file then we may not catch that through the validation". That is totally valid scenario for us. We need to think through the scenarios as it is applicable to all the rules.

**Comment by veronicagg** [comment]
@olydis can we get the json path to contain the path to the file where the referenced definition actually is?

**Comment by olydis** [comment]
you as in the consumer side of AutoRest (VSCode extension, messages printed to command line) will absolutely get the correct paths :-) That's what my source map efforts were for - "you" as the validation rule writers may report precisely the jsonpath you see and it'll all work fine!

**Comment by veronicagg** [comment]
@vishrutshah is this still a problem? do we have a way to provide a proper json path in the rule message with the current implementation of autorest or does it get resolved when we move to the typescript entry point of autorest?

**Comment by vishrutshah** [comment]
As per @veronicagg's suggestion, I verified that with the new source mapping we have this fixed. Now the linter points to the right file. Example:

```
gulp autorest --azure-arm --input-file=/Users/vishrut/git-repos/azure-rest-api-specs/arm-network/2017-03-01/swagger/applicationGateway.json --message-format=json

{
  "type": "Warning",
  "code": "DescriptionMissing",
  "message": "'publicIPAddress' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.",
  "id": "M4000",
  "validationCategory": "SDKViolation",
  "providerNamespace": null,
  "resourceType": null,
  "sources": [
    "file:///Users/vishrut/git-repos/azure-rest-api-specs/arm-network/2017-03-01/swagger/networkInterface.json:387:8 ($.definitions.NetworkInterfaceIPConfigurationPropertiesFormat.properties.publicIPAddress)"
  ]
}
```

Even though I am running linter on `applicationGateway.json` file, it is correctly poining to the referenced source file for the error. 

Closing this issue.
