### ISSUE TITLE
GO: Long running operations don't return the object they create

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2079]
For whatever reason LROs don't return the object they create which is different from SDKs in other languages.  The offending code is here.
https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.Go/Model/MethodGo.cs#L92
In practical terms this means that after creating an object (e.g. redis cache) you would then need to call the get operation to retrieve the object that was just created.

**Comment by marstr** [comment]
I think the line referenced above needs to be updated (and maybe locked to a commit.)

**Comment by jhendrixMSFT** [comment]
Fixed it https://github.com/Azure/autorest/pull/2186
