### ISSUE TITLE
AutoRest gives bad error message when Swagger spec has broken link

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2082]
When a Swagger spec has a broken $ref link (i.e. there is "$ref": "#/definitions/Potato" but no "Potato" in the document's definitions), AutoRest gives a very unhelpful error message.

```
FATAL: Error generating client model: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Swagger.Model.Utilities.ValidationUtilities.IsArrayTypeResponseOperation(Operation op, ServiceDefinition entity)
   at AutoRest.Swagger.Validation.ListOperationNamingWarning.<GetValidationMessages>d__7.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Swagger.Model.Utilities.ValidationUtilities.IsArrayTypeResponseOperation(Operation op, ServiceDefinition entity)
   at AutoRest.Swagger.Validation.ListOperationNamingWarning.<GetValidationMessages>d__7.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
```

AutoRest version:
```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  0.9.21
  NetCore framework :      1.0.3
  Latest Core Installed :  1.0.1-20170327-2300-nightly
  Requested Core Version : <none>
```

Command line: `E:\dsmain2\Sql\xdb\manifest\svc\mgmt\WebApiHosting\ARM\Tools>autorest -Input swagger.json -CodeGenerator None`

Source file:
```
{
  "swagger": "2.0",
  "info": {
    "version": "2015-05-01-preview",
    "title": "SqlManagementClient",
    "description": "The Azure SQL Database management API provides a RESTful set of web APIs that interact with Azure SQL Database services to manage your databases. The API enables users to create, retrieve, update, and delete databases, servers, and other entities."
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/providers/Microsoft.Sql/operations": {
      "get": {
        "tags": [
          "Operations"
        ],
        "operationId": "Operations_GetOperations",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Potato"
            }
          }
        },
        "deprecated": false
      }
    }
  }
}
```

**Comment by olydis** [comment]
Thanks for posting this, it turns out this is just a bug in the validator: Without the validator (say, when generating C#), the output is.

```
FATAL: System.ArgumentException: Reference path 'Potato' does not exist in the definition section of the Swagger document.
```

This message is generated at a later point than ARM validation. We'll fix up the validation rule!

**Comment by dsgouda** [comment]
I understand our linter rules would have to make sure keys exist before accessing the definitions (or any other maps) in order to gracefully handle such errors. What I propose is an uber linter rule that simply runs a sanity check over the ServiceDefinition model that gets built, before any validation rule is run. This would make sure we have all the pieces correctly constructed and exit early if not. It might probably need a different ValidationCategory too.
@veronicagg thoughts?

**Comment by olydis** [comment]
@dsgouda Note that this should also be handled by the semantic validator. Just wanna make sure we don't duplicate efforts and introduce new exit logic and categories unnecessarily.

**Comment by dsgouda** [comment]
I'd argue we need this for the validation rule too, just so we don't run validation rules over erroneous  serviceDefinition and run into exceptions like these.

**Comment by olydis** [comment]
One could argue it makes sense to see squigglies even in presence of minor errors like this (a Swagger with a parameter with `type: string` and `default: 4` is also erroneous, still we'll run the validation rules).

**Comment by dsgouda** [comment]
What if we instead say, we will run the validation rules after semantic rules' errors have been fixed, that would take care of such issues then.

**Comment by olydis** [comment]
It would indeed, but as always, getting as many squigglies as possible as early as possible is highly desirable! Be aware that a single semantic error would then also cause the ScottGu report to say "1 issue", i.e. fixing issues can increase the number of errors. We should also not force a run of the semantic validator (that's configurable and should also be parallelizable, so we don't wanna introduce a dependency here), so really: The linter should just be robust.

**Comment by dsgouda** [comment]
Hmmm... I can't beat that. Feel free to reopen the PR, I guess we just need to be more vigilant on our rules.

**Comment by olydis** [comment]
The PR is open (https://github.com/Azure/autorest/pull/2156), just awaiting approval ;-)
