### ISSUE TITLE
Parallelize validation rule execution

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2083]
Parallelize execution of validation rules [here](https://github.com/Azure/autorest/blob/a2d51c88366b683e1ca92cbeceb91c16b4ffdb6c/src/modeler/AutoRest.Swagger/SwaggerModeler.cs#L83)

**Comment by dsgouda** [comment]
@fearthecowboy @olydis 
I made some changes to execute validation rules in parallel [here](https://github.com/Azure/autorest/compare/master...dsgouda:i2083?expand=1)
I also gathered some metrics for the same as below (in number of elapsedticks)

```
With parallelization
52295
```
```
Without parallelization
41109
```
I used the network rest spec composite swagger for testing.
Am I applying the parallelization at the wrong place here or is it just that parallelization won't help us much here

**Comment by dsgouda** [comment]
Pinging @olydis @fearthecowboy

**Comment by olydis** [comment]
@dsgouda are we supposed to look at anything? is there a PR? the compare link in your previous message doesn't work for me. I would also have expected a bigger speedup (theoretically you should get close to <old time>/<number of cores> since you have little chunks of CPU-bound work, correct?).

**Comment by dsgouda** [comment]
Whoops looks like I deleted the branch, will recreate the branch. 
Yes, I was expecting a speedup but multiple runs actually reported a slowdown even though they theoretically are smaller chunks of work which makes me wonder if we should explore this further.
Thoughts?

**Comment by fearthecowboy** [comment]
At this point, I wouldn't worry about it. it looks like we're not benefiting from parallelization, and we're not suffering terribly at this point.

**Comment by dsgouda** [comment]
Thanks for confirming, will close this for now and revisit later if needed.
