### ISSUE TITLE
Discussion: Internal IServiceOperations

### ISSUE THREAD

**Issue by mawt** [Azure/autorest#209]
I'm evaluating Autorest against a lightly modified WebApiProxy project. 

One of my design goals is to bridge local and remote services via a common interface. In other words I would like 'IMemberService' to point to a concrete instance or over-the-wire-by-client instance by toggling the DI registration.

Having looked at the default CSharp code generator it appears that all of the IServiceOperations are internal classes and they can't be constructed outside of the project housing generated code. Ideally I'd like to inject individual services as required (i.e.: Project A might require 2 services and Project B might require 3 different services and one shared) and construct them at DI configuration.

I'd also like to subclass the IServiceOperations to add a 'business façade', for example, shared service 'IUserPreferenceService' might 'get' and 'set' a generic 'UserPreferenceModel ', but the the service would benefit from per-project convenience overloads, such as SetCountry(string country) and string GetCountry().

Can you make the default IServiceOperations a little more decoupled and public?

Kind regards

**Comment by markcowl** [comment]
@mawt Thanks for the feedback, we are investigating.

**Comment by markcowl** [comment]
@mawt we will msake the IServiceOperations public by default, can you describe the other changes you would like in more detail?

**Comment by hovsepm** [comment]
Fixed in dev branch
