### ISSUE TITLE
Why is the Newtonsoft.Json dependency forced to < 10.0.0?

### ISSUE THREAD

**Issue by erick-thompson** [Azure/autorest#2091]
This is causing a number of issues in our build system, as we general take the latest version of dependencies. Is there a hard reason for this?

**Comment by fearthecowboy** [comment]
Ah, this is regarding the c# client runtime?

It's moved to https://github.com/Azure/azure-sdk-for-net

**Comment by erick-thompson** [comment]
It is - thanks for the redirect.

**Comment by CumpsD** [comment]
I am having this chain on my server:

`Microsoft.Extensions.Configuration.AzureKeyVault (>= 1.0.1) -> Microsoft.Azure.KeyVault (>= 2.0.6) -> Microsoft.Azure.KeyVault.WebKey (>= 2.0.4) -> Newtonsoft.Json (>= 9.0.1).`

Is there any way around this? It's the only thing blocking the entire project from moving to Newtonsoft 10.

**Comment by CumpsD** [comment]
Ah probably https://github.com/Azure/azure-sdk-for-net/issues/3003
