### ISSUE TITLE
[Azure Automation] Deserializing fails with SafeJsonConvert.DeserializeObject

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/autorest#2103]
Response
[CompilationGetJobStream.txt](https://github.com/Azure/autorest/files/891093/CompilationGetJobStream.txt)

generated cs file
[CompilationJobsOperations.cs.txt](https://github.com/Azure/autorest/files/891106/CompilationJobsOperations.cs.txt)

Swagger file
[dscCompilationJob.json.txt](https://github.com/Azure/autorest/files/891115/dscCompilationJob.json.txt)

Hi,
   Deserializing the response using statement SafeJsonConvert.DeserializeObject is failing at line 822(CompilationJobsOperations.cs.txt). Any ideas ?

**Comment by olydis** [comment]
To analyze the exception further, it would be helpful to know
- what exception are you getting when it "is failing"?
- how is `./definitions.json#/definitions/ErrorResponse` defined?

**Comment by olydis** [comment]
guess the latter is found in https://github.com/Azure/azure-rest-api-specs/pull/1045

**Comment by olydis** [comment]
indeed, it looks like `ErrorResponse` simply doesn't match the recording you posted! So this looks like a modeling issue.

**Comment by vivlingaiah** [comment]
For response 200, It is a Rest.SerializationException. Please refer attached for response json and also stack trace. Looks like with  "value" object, it was not expecting InvocationInfo ? Could you confirm ? and let me know how to fix ?

definitions
[Uploading definitions.json.txt…]()


[Uploading GetJobStreamSerializationException.docx…]()

**Comment by olydis** [comment]
You said
> SafeJsonConvert.DeserializeObject is failing at line 822(CompilationJobsOperations.cs.txt)
which is (as you can see in line 816) the handler for *non-200* responses, so I was assuming there is a problem with `ErrorResponse` (that's what tries to get deserialized in the line you reference!)

**Comment by olydis** [comment]
Also, you didn't upload anything in the previous comment.

**Comment by vivlingaiah** [comment]
I think we can close this now. I'm doing this. Changed string to object. It's working
https://github.com/Azure/azure-rest-api-specs/pull/1045/commits/1dd67d72c9a44b977e97e737d2be3be0969a9409
