### ISSUE TITLE
autorest with -OutputFileName ./xxx.Api.Client.cs is not working

### ISSUE THREAD

**Issue by ayydevara** [Azure/autorest#2109]
Not generating output file correctly

` generating only one model which is at the end of the swagger.json file`

**Comment by fearthecowboy** [comment]
Hey @ayydevara ,  Any chance you can give us a bunch more information, like, 
- the swagger file
- commandline you used
- version of autorest?

**Comment by ayydevara** [comment]
`
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  0.9.23
  NetCore framework :      1.0.3
  Latest Core Installed :  1.0.1-20170402-2300-nightly
  Requested Core Version : <none>
`

`
autorest -OutputFileName ./Dg.Api.Client.cs -i dgplatform.json -Namespace Dg.Api.Client -AddCredentials true
`

`
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Dg.Api.Client.Models
{
    using Dg.Api;
    using Dg.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WorkflowChange
    {
        /// <summary>
        /// Initializes a new instance of the WorkflowChange class.
        /// </summary>
        public WorkflowChange()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorkflowChange class.
        /// </summary>
        public WorkflowChange(string newStatus = default(string))
        {
            NewStatus = newStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "newStatus")]
        public string NewStatus { get; set; }

    }
}

`

`
https://dgplatform.blob.core.windows.net/venues/autorest-issue/autorest-cmd.txt
https://dgplatform.blob.core.windows.net/venues/autorest-issue/Dg.Api.Client-generated.cs
https://dgplatform.blob.core.windows.net/venues/autorest-issue/dgplatform.json
`

**Comment by fearthecowboy** [comment]
Ah, don't use `-OutputFileName ` -- it's only going to output one file. That's for a different use case.

**Comment by ayydevara** [comment]
@fearthecowboy This used to work fine before, all required classes generated in one single file. Is something changed?

**Comment by ayydevara** [comment]
This used to work fine before, all required classes generated in one single
file. Is something changed?

**Comment by fearthecowboy** [comment]
Yes; it has changed a bit.

@olydis ? is it still possible to save it all in one file?

**Comment by ayydevara** [comment]
@fearthecowboy what is the purpose of -OutputFileName switch?
