### ISSUE TITLE
Python CI failing

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2120]
See:
http://azuresdkci.cloudapp.net/job/autorest/4668/console

**Comment by lmazuel** [comment]
@olydis Made a new release of msrest with paging important fix, tested Python.Tests but not AzurePython.Tests....
Actually the tests is wrong and is doing exactly what is wrong and shouldn't be done. So fixing the test in https://github.com/Azure/autorest/pull/2121

Sorry for the inconvenience ... :(

**Comment by olydis** [comment]
No problem, thanks!
