### ISSUE TITLE
ResourceModelValidation flags false positives

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2127]
Validation rule ResourceModelValidation throws an error message even for models which have the "name", "id" and "type" properties marked as readOnly

Eg.: run autorest against spec [here](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-recoveryservices/2016-06-01/swagger/vaults.json)

FYI @veronicagg @vishrutshah @sarangan12

**Comment by dsgouda** [comment]
The issue is we are enforcing that every model named as ```resource``` Must have the properties 'name', 'id', 'type', 'location' and 'tags'. We have many instances where TrackedResource allOfs on a resource model and then adds the 'location' as a required property. We should relax this rule to check for only 'name', 'id' and 'type' properties.
Any thoughts/suggestions here?

**Comment by veronicagg** [comment]
To add some extra info, we had the following issues opened on this rule: 
https://github.com/Azure/autorest/issues/1936
https://github.com/Azure/autorest/issues/1861 
if appears that something got lost in the discussions, regarding this rule. 
I agree with you, we should be checking whether id, name and type are 'required' properties. I thought we had another rule for this, but can't find it, so if you can't find it either, feel free to turn this one into that. 
Thanks!!
