### ISSUE TITLE
Potential Issue with ServiceDefinitionParameters validation rule

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2128]
For ARM specs we enforce parameters ```subscriptionId``` and ```api-version``` are defined globally by a case insensitive search for all globally defined parameters. However, specs often have these defined as ```subscriptionIdParameter``` or ```ApiVersionParameter```. We need to either relax the matching method to use ```StartsWith``` instead of ```Equals``` or explicitly search for the two variations as well.

@veronicagg @vishrutshah @sarangan12 thoughts?

**Comment by veronicagg** [comment]
the rule should be checking for the "name" of the property "api-version"  and not for the name of the model "ApiVersionParameter". As far as I know, autorest depends on this property "name" being "api-version"
  "parameters": {
    "ApiVersionParameter": {
      "name": "api-version",
      "in": "query",
      "required": true,
      "type": "string",
      "description": "Client Api Version."
    }

**Comment by vishrutshah** [comment]
Example seems like https://travis-ci.org/Azure/azure-rest-api-specs/jobs/226238975#L1457

**Comment by dsgouda** [comment]
Ran the latest version of validator for the example mentioned here (and another test spec) and not able to repro the issue. Please reopen if this persists.
