### ISSUE TITLE
"SecurityDefinitionsStructureValidation" rule doesn't indicate what the "specific structure" is

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2129]
Error is not actionable for the user "A swagger must have security definitions and must adhere to the specific structure." https://travis-ci.org/Azure/azure-rest-api-specs/jobs/219198608#L1079

**Comment by sarangan12** [comment]
https://github.com/Azure/autorest/pull/2211

**Comment by sarangan12** [comment]
Task completed

**Comment by vishrutshah** [comment]
Can we improve this rule by point to _what part of the entire structure_ is incorrect? 

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/226238975#L1471 PR changes looks good visually but not sure why failing? 

@sarangan12 any idea on how can we improve this? Just re-opening this in case we can improve this validation rule. 

Thoughts?

**Comment by sarangan12** [comment]
@vishrutshah The security structure message has already been modified and made to be more clear. Also, it has only 5 short lines in the structure and easier for any user to see where it differs. Trying to give extra information will be over engineering and probably should be of P4/P5 priority and not worth the effort.
