### ISSUE TITLE
Generator targetting UWP

### ISSUE THREAD

**Issue by prapicault** [Azure/autorest#2148]
I've used the CSharp generator to generate a client, but the required dependency of Microsoft.Rest.Client is not available for UWP. 
Is there another generator that should be used for this?

**Comment by olydis** [comment]
Hi, sorry for the delay! I missed this issue between all the "linter" issues we filed ourselves over the past weeks. Hmmm from our perspective: No, there is no other generator, we will always generate a dependency on `Microsoft.Rest.Client`. That one is maintained over in https://github.com/Azure/azure-sdk-for-net, maybe you can open an issue over there :) Maybe they have an answer or plans about supporting UWP.

**Comment by fearthecowboy** [comment]
I just tried to create a UWP app and add Microsoft.Rest.ClientRuntime and was able to do that just fine.
