### ISSUE TITLE
Path Parameters Should Always Set "minLength"

### ISSUE THREAD

**Issue by marstr** [Azure/autorest#2159]
As described in Azure/openapi-validation-tools#77, and seen in Azure/azure-sdk-for-go#576, if a variable passed in the path has an empty value it can change the semantics of the request.

For that reason, I believe the Linter should be extended to flag [path](http://swagger.io/specification/#path-item-object-32) [parameters](http://swagger.io/specification/#parameter-object-44) that do not set a `minLength`. At times, it may make sense for that minimum to be '0', but I believe the vast majority will be greater than or equal to '1'.

**Comment by dsgouda** [comment]
I believe this is an RPCViolation and should be set as an Error. @veronicagg do let me know if otherwise

**Comment by dsgouda** [comment]
I am wondering if this extends to the global properties "SubscriptionId" and "api-version", this rule is bound to generate a lot of noise if we enable it for these global properties

**Comment by veronicagg** [comment]
@ravbhatnagar should this be enforced? is it an RPC violation? 
@amarzavery it'd be good to get your thoughts too.

**Comment by ravbhatnagar** [comment]
The rule makes sense but it is nothing specific to RPC. Yes, agree with @dsgouda that this will trigger a lot of violations. If the SDK team feels strongly about it and can foresee issues in the generated clients if not enforced, you can implement it.

**Comment by dsgouda** [comment]
Discussed this with @veronicagg and we agree this would end up generating a lot of noise without really providing intended benefit. Official OpenAPI specifications do not have any length requirements for path parameters. This indicates that we should probably tweak our sdks to handle empty path parameters.
Will shelve this for now.
