### ISSUE TITLE
[Linter] _ListBySubscriptionId, _ListByResourceGroupName should not enforce "noun" before the underscore

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2168]
We should not enforce the name before the underscore for this rule, just the fact that an operation exists that ends with the above, and returns a list of the resource in question. 
If we wanted to have a naming convention on something else (I'm not sure we want that), then we could create another rule for that, let's discuss it if needed.

**Comment by sarangan12** [comment]
I have checked the rules. They are already checking the response and does not worry about the naming conventions. Also the messages are:

1. The tracked resource, '{0}', must have a list by resource group operation.
2. The tracked resource, '{0}', must have a list by subscriptions operation.

The messages also do not make any reference to the naming convention. So, there seems to be no open action items for this issue. Closing this now.
