### ISSUE TITLE
Property names which violate M3019 not listed

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2169]
M3019 Bug - It is not listing the names of the property that violates the rule.
Sample Spec- https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-04-01/swagger/TopLevelDomains.json
It does list that the property “name” is repeated inside the properties bag. It says Properties [] conflict with ARM top level properties.

**Comment by veronicagg** [comment]
https://github.com/Azure/autorest/pull/2171

**Comment by veronicagg** [comment]
@ravbhatnagar I believe the PR closed today fixes this issue, please close this issue if that's the case.

**Comment by veronicagg** [comment]
feel free to reopen if this is not fixed.
