### ISSUE TITLE
XML file header comments

### ISSUE THREAD

**Issue by jkonecki** [Azure/autorest#217]
Default header comment used by C# generator is created using XML comments `///` instead of standard comments `//`. XML comments are not valid above the namespace.

This results in compiler warning (level 2) [CS1587 - XML comment is not placed on a valid language element](https://msdn.microsoft.com/en-us/library/d3x6ez1z(v=vs.90).aspx)

**Comment by markcowl** [comment]
@jkonecki Jakub, can you please sign the CLA on your PR?  Otherwise we will have to close it and come up with our own fix for the issue.  Thanks!

**Comment by jkonecki** [comment]
I did sign it. Will check again.

**Comment by hovsepm** [comment]
Fixed in dev branch
