### ISSUE TITLE
ListByResourceGroup and ListBySubcription dont apply to tenant level resources

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2170]
Such resources will not have the /resourceGroups or /subscriptions section in the URL. Please discuss with me before fixing this one. 
M3027 – Does not apply to tenant level resources. These resources don’t have subscriptions and resourceGroups section in the URL. The URL looks like /providers/Microsoft.Web/publishingUsers/{name}
Sample spec - https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2016-03-01/swagger/ResourceProvider.json
Model – User

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
