### ISSUE TITLE
[Linter] Remove rule "BodyParametersValidation" 

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2173]
It appears that we don't need to enforce this rule, CLI and SDKs are dealing with this properly and actually it seems like a better experience to name the parameter as appropriate. 
Let's remove the rule. 
Here are the supporting comments:
From @amarzavery 
"It is not compulsory to name all the request body parameters  as "parameters". Rather than naming them like that, I would prefer a context specific meaningful name.
 If you are creating a VirtualMachine then for the PUT request, the name of the request body should be "virtualMachine" or "virtualMachineProperties" as that is what you are saying to the service. "
From @derekbekoe (from Python CLI team):
"The line of code in the CLI that was referenced only provides a default value and we override it with the real name of the body param in several places.
We do not force the body param to be called ‘parameters’.
e.g.
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py#L258
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py#L270
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py#L101
etc.

So the CLI does not enforce the comment ‘An operation's body parameters should be named 'parameters'’ in any way.
Just that in a lot of cases, it is actually called ‘parameters’ so it’s a good default to start with."

**Comment by veronicagg** [comment]
Related to https://github.com/Azure/autorest/issues/2019 @jaredmoo we're removing this rule from validation tools, as it proved not to be necessary nor generic. Feel free to let us know if you have questions.

**Comment by jaredmoo** [comment]
Fair enough. Sounds fine. Thanks for looping me in!

**Comment by sarangan12** [comment]
Task Completed
