### ISSUE TITLE
[Linter]: Fix class naming inconsistencies for linter rules

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#2174]
ListOperationNamingWarning has the severity error but it is named as warning. Please change the name to ListOperationNamingRule or ListOperationNamingValidation
Please remove name warning from NonJsonTypeWarning Class too. It is not consistent with other classes.
In general, it might be good to have consistent pattern for class naming - I am seeing some which end with Rule and some that end with Validation, Warning.

Also typically class name seems to be the same as file name except this one case where file name is OperationIdSingleUnderscore and class name is OneUnderscoreInOperationId

**Comment by veronicagg** [comment]
https://github.com/Azure/autorest/issues/2149

**Comment by sarangan12** [comment]
Task Completed
