### ISSUE TITLE
Default PackageVersion is lost in recent Autorest in Composite mode

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2175]
If I use a Composite file with the same ApiVersion in each file, it used to fill "PackageVersion" if not provided by this ApiVersion.

Not the case anymore in recent Autorest (roughly after April 10th), the string is empty.

**Comment by olydis** [comment]
Think I know why this happens. Just to make sure: You'd expect Python generated from https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/compositeNetworkClient.json to automatically have package version 2017-03-01?

**Comment by lmazuel** [comment]
Hi @olydis 

I thank I dream too much and this never worked that way :/ (I even downloaded old version from myget). For a long time I always used the "PackageVersion" parameter, and when I removed it I think I confused myself on the behavior between std Swagger and CompositeSwagger...
So yes, I expected to see "2017-03-01" and it would be a cool feature I think, but it's not a bug technically...
Sorry about that... I'll let you decide if you close it or not :/

**Comment by olydis** [comment]
@lmazuel No worries, I mean the feature sounds like it makes sense so I'll leave it open as an enhancement. Actually, it is related to some changes down the road (we have ongoing discussions about formalizing what it means for an SDK to have multiple api-versions in Swaggers) so there might even be a centralized, uniform solution coming :-)
