### ISSUE TITLE
Required properties

### ISSUE THREAD

**Issue by jkonecki** [Azure/autorest#219]
C# generator creates all primitive type properties as `Nullable<T>`. If the property is declared as required in swagger.json should we generate property of type `T` instead of `Nullable<T>`?

The required flag is already captured and `PrimaryType` could be easily extended to support nullability explicitly - `SwaggerObject.ToType()` method could just use already present `IsReguired` property.

A config option can be added to turn this behaviour on/off if backwards compatibility is required.

I'm happy to create a PR - just wondering if there are any side-effects I'm not aware of.

**Comment by hovsepm** [comment]
@jkonecki, this was done on purpose. Having nullable primitive types everywhere simplifies logic for PATCH like operations and null validation. Additionally having primitive types in the response insures that deserialization does not throw when the date is missing on the wire (e.g. server changed the field to be nullable but the client was not regenerated with the latest swagger spec). 

We still have a validation for the required fields inside generated methods during runtime.
