### ISSUE TITLE
FATAL: Error generating client model: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kotpal** [Azure/autorest#2194]
I got Node.js 6.10.0 (x64) and latest version of autorest installed. 

Tried to generate a client using the sample at https://github.com/Azure/autorest/blob/master/docs/generating-a-client.md 

Got the following error:

`C:\temp\autorest>autorest -Input petstore.json -CodeGenerator CSharp -OutputDirectory CSharp_PetStore -Namespace PetStore
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
FATAL: Error generating client model: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Swagger.SwaggerModeler.UpdateSettings()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Swagger.SwaggerModeler.UpdateSettings()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
ERROR: AutoRest.dll -Input petstore.json -CodeGenerator CSharp -OutputDirectory CSharp_PetStore -Namespace PetStore`

**Comment by fearthecowboy** [comment]
O_o

I just tried it (had to download the json from a different url) 

``` powershell 
C:\tmp\petstore> iwr https://raw.githubusercontent.com/Azure/autorest/master/Samples/petstore/petstore.json -o petstore.json
C:\tmp\petstore> autorest -Input petstore.json -CodeGenerator CSharp -OutputDirectory CSharp_PetStore -Namespace PetStore

AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
The Microsoft.Rest.ClientRuntime.2.2.0 nuget package is required to compile the generated code.
C:\tmp\petstore> 
```

What's in the file you passed to it?
