### ISSUE TITLE
How can I customize code generation templates easily

### ISSUE THREAD

**Issue by seven1986** [Azure/autorest#2195]
Currently, the CSharp and NodeJS code by generated that is hard to understand for me. Sorry, because the coding style are not same...
I expect **an easy way** to define my own template with CSharp(Server and Client)  and NodeJS(Typescript,Javascript,Angular, etc..)

Thanks for this awesome tool

**Comment by olydis** [comment]
Hi, we are indeed planning to simplify the process of specifying own templates, but currently all you can do is literally modifying/overwriting the existing templates in the sources and recompiling. :-)

**Comment by olydis** [comment]
Simplifying this process is actually tracked here: https://github.com/Azure/autorest/issues/2146
Therefore I will close this issue, feel free to post further questions/wishes in that issue 🙂
