### ISSUE TITLE
Convert Id and ValidationCategory fields in Rule.cs to abstract properties

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2196]
This requires ensuring every single ValidationRule class that inherits from Rule.cs has the ValidationCategory and Id fields overridden. We might also generate some diffs in the regenerated code here.

**Comment by dsgouda** [comment]
Need a few Validation Ids here
@kirthik can you take a look
[SupportedSchemesWarning](https://github.com/Azure/autorest/blob/43a65e4eab01ef64b195d28e42556f9d0d316e7f/src/modeler/AutoRest.Swagger/Validation/SupportedSchemesWarning.cs)
[AvoidMsdnReferences](https://github.com/Azure/autorest/blob/a2d51c88366b683e1ca92cbeceb91c16b4ffdb6c/src/modeler/AutoRest.Swagger/Validation/AvoidMsdnReferences.cs)
[NoControlCharacters](https://github.com/Azure/autorest/blob/a2d51c88366b683e1ca92cbeceb91c16b4ffdb6c/src/modeler/AutoRest.Swagger/Validation/Core/NoControlCharacters.cs)


Need Validation Categories here
[NoControlCharacters](https://github.com/Azure/autorest/blob/a2d51c88366b683e1ca92cbeceb91c16b4ffdb6c/src/modeler/AutoRest.Swagger/Validation/Core/NoControlCharacters.cs)

**Comment by kirthik** [comment]
For what would we check NoControlCharacters rule? Operations or model properties that are strings? or both? It seems like SDKViolation to me. Could you also tell me the impact?  Does validation failing on this rule mean SDK cannot be generated?

**Comment by dsgouda** [comment]
Come to think of it I have never seen ```NoControlCharacters``` violation flagged (checked rest spec logs too), plus there is no test case for this either. Makes me wonder if we even allow control characters anywhere in our specs. @olydis does AutoRest read a document with control characters of any kind?

**Comment by olydis** [comment]
@dsgouda if it's valid JSON/YAML (control characters are perfectly legal if properly escaped and such), AutoRest will read it, yes

Also never saw that rule in action, may be worth an investigation / negative test case ;-)

**Comment by dsgouda** [comment]
Tested with ```NoControlCharacters``` rule control characters in specs, unescaped documents are correctly flagged by AutoRest even before the validator kicks and escaped characters are read as plain strings instead of characters.
Moreover since this is a universal rule this gets applied to practically every node and worsens performance considerably. Removing it unless there is a strong case to keep it around.

**Comment by olydis** [comment]
> unescaped documents are correctly flagged by AutoRest even before the validator kicks and escaped characters are read as plain strings instead of characters

@dsgouda this does not happen for me, where are they getting "flagged"? I just created a trivial test Swagger and get

```
...
ERROR (NoControlCharacters/!!! implement me and make me abstract !!!/None): May not contain control characters (http://www.apache.org/licenses  /LI♀CE-2.0.html contains , 0x9, 0xC)
    - file:///C:/work/autorest/Samples/1a-code-generation-minimal/petstore.json:13:6 ($.info.license.url)
ERROR (NoControlCharacters/!!! implement me and make me abstract !!!/None): May not contain control characters (http://www.apache.org/licenses  /LI♀CE-2.0.html contains , 0x9, 0xC)
    - file:///C:/work/autorest/Samples/1a-code-generation-minimal/petstore.json:13:6 ($.info.license.url)
ERROR (APIVersionPattern/M3012/RPCViolation): API Version must be in the format: yyyy-MM-dd, optionally followed by -preview, -alpha, -beta, -rc, -privatepreview.
...
```

So control characters *do* get passed on unmodified (I would have been surprised if not), they do not get flagged by the core and this rule seems to identify at least some of them.

**Comment by dsgouda** [comment]
Hmm.. there is no existing test case for this rule so difficult to ascertain.
Will sync with @olydis and verify the rule before making further changes.

**Comment by dsgouda** [comment]
```NoControlCharacters``` seems to be buggy and an issue has been filed here to handle it. This may still require an id though.

**Comment by sarangan12** [comment]
https://github.com/Azure/autorest/pull/2277
