### ISSUE TITLE
The Swagger linter should not enforce ARM specific guidance on Data plane Swaggers

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2223]
For example the Swagger in the `batch` folder is a data plane Swagger specification.

A variety of errors are raised which don't apply to data plane Swagger specifications, such as:
>  {
    "type": "Warning",
    "code": "LROStatusCodesValidation",
    "message": "200/201 Responses of long running operations must have a schema definition for return type. OperationId: 'Job_Update', Response code: '200'",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths/~1jobs~1{jobId}/put/responses/200",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths/jobs/{jobId}/put/responses/200",
    "id": "M2064",
    "validationCategory": "SDKViolation",
    "providerNamespace": null,
    "resourceType": null
  },

>  {
    "type": "Warning",
    "code": "PutRequestResponseValidation",
    "message": "A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'ComputeNode_UpdateUser' Request Model: 'NodeUpdateUserParameter' Response Model: ''",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths/~1pools~1{poolId}~1nodes~1{nodeId}~1users~1{userName}/put/operationId",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths/pools/{poolId}/nodes/{nodeId}/users/{userName}/put/operationId",
    "id": "M2017",
    "validationCategory": "SDKViolation",
    "providerNamespace": null,
    "resourceType": null
  },

>   {
    "type": "Error",
    "code": "APIVersionPattern",
    "message": "API Version must be in the format: yyyy-MM-dd, optionally followed by -preview, -alpha, -beta, -rc, -privatepreview.",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/info/version",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/info/version",
    "id": "M3012",
    "validationCategory": "RPCViolation",
    "providerNamespace": null,
    "resourceType": null
  },

>   {
    "type": "Warning",
    "code": "ListOperationNamingWarning",
    "message": "Since operation 'Task_AddCollection' response has model definition 'array', it should be of the form \"*_list*\"",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths",
    "id": "M1003",
    "validationCategory": "SDKViolation",
    "providerNamespace": null,
    "resourceType": null
  },

>   {
    "type": "Error",
    "code": "OperationsAPIImplementationValidation",
    "message": "Operations API must be implemented for '/providers//operations'.",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/paths",
    "id": "M3023",
    "validationCategory": "RPCViolation",
    "providerNamespace": null,
    "resourceType": null
  },

>  {
    "type": "Error",
    "code": "DefinitionsPropertiesNamesCamelCase",
    "message": "Property named: \"odata.nextLink\", for definition: \"CloudJobScheduleListResult\" must follow camelCase style. Example: \"odata.nextLink\".",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/definitions/CloudJobScheduleListResult/properties/odata.nextLink",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/definitions/CloudJobScheduleListResult/properties/odata.nextLink",
    "id": "M3016",
    "validationCategory": "RPCViolation",
    "providerNamespace": null,
    "resourceType": null
  },

In general, I think it would be good to distinguish between Swagger recommendations that apply to all services (things like should have `x-ms-examples`, etc) and ARM specific recommendations such as anything related to LongRunningOperations, etc.

**Comment by olydis** [comment]
in progress here: https://github.com/Azure/autorest/pull/2182

**Comment by veronicagg** [comment]
duplicate issue https://github.com/Azure/autorest/issues/1940
