### ISSUE TITLE
Linter says x-ms-client-name shouldn't match original property name (M2013)

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2226]
>   {
    "type": "Error",
    "code": "XmsClientNamePropertyValidation",
    "message": "Value of 'x-ms-client-name' cannot be the same as 'username' Property/Model.",
    "jsonref": "batch/2017-05-01.5.0/swagger/BatchService.json#/definitions/UserIdentity/properties",
    "json-path": "batch/2017-05-01.5.0/swagger/BatchService.json#/definitions/UserIdentity/properties",
    "id": "M2013",
    "validationCategory": "SDKViolation",
    "providerNamespace": null,
    "resourceType": null
  },

`username` and `userName` differ by case. We use `x-ms-client-name` to make the cleint generated code have nice cased properties (i.e. `userName`) rather than ugly ones (`username`). But our server expects `username` (all lower case).

This seems like a valid use case to me -- is it possible that we make this rule case sensitive instead of case insensitive like it is now?

**Comment by matthchr** [comment]
@dsgouda Are you sure that this issue is resolved? It seems like I'm still hitting it [here](https://github.com/Azure/azure-rest-api-specs/pull/1288)

**Comment by dsgouda** [comment]
Taking a look.

**Comment by dsgouda** [comment]
Looks like the fix got overwritten when we were renaming the validation rules, will post a PR for the fix soon.

**Comment by dsgouda** [comment]
Should be fixed now.
