### ISSUE TITLE
[Go] Composite swagger User Agent

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#2227]
When generating from composite swaggers, this is the generated UserAgent...
`"Azure-SDK-For-Go/v10.0.0-beta arm-network/"`
For comparison, this is how a  non comp swagger gens the UserAgent:
`"Azure-SDK-For-Go/v10.0.0-beta arm-mobileengagement/2014-12-01"`
So the API version is not included. But comp swaggers can have multiple API versions.
How does this look?
`"Azure-SDK-For-Go/v10.0.0-beta arm-network/latest"`

**Comment by marstr** [comment]
Composite swaggers aren't really a thing anymore, and the Go packages certainly don't use them.
