### ISSUE TITLE
Mixed up legacy / new CLI parameters should fail

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2229]
Currently the following command:

```console
autorest --version=latest -i managedapplications.json -o d:/testttt --python --a
zure-arm --payload-flattening-threshold 2
```

Does not fail and generate a C# SDK. I get why, but I think it can be confusing and should fail horribly.

**Comment by olydis** [comment]
it'll print a warning now! I'm good with turning the warning into an error as time goes by, on our long way to a legacy-free world 😄
