### ISSUE TITLE
= in new CLI is required?

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2231]
If I call the new CLI with no =, I get an error:
```console
autorest --version=latest --input-file managedapplications.json --output-folder
d:/testttt --python --azure-arm --payload-flattening-threshold 2

AutoRest Code Generator (latest)
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Error: Found multiple configuration file arguments: 'managedapplications.json', 'd:/testttt'
```

So, I added the =, but I forgot the last one on `payload-flattening-threshold`:
```console
autorest --version=latest --input-file=managedapplications.json --output-folder=d:/testttt --python --azure-arm --payload-flattening-threshold 2
```

And I didn't get a mistake. I'm unsure if this means it's not required for `payload-flattening-threshold` or if my parameter was ignored? Make me feel unsafe about the parameters parsing :(

**Comment by fearthecowboy** [comment]
Yeah, the format for all parameters in the new cli is `--KEY=VALUE` . The equals is required if you are specifying a value.
