### ISSUE TITLE
climb up object path if node not found when resolving source location

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2232]
see https://github.com/Azure/autorest/issues/2106#issuecomment-298757838, thanks @dsgouda

That would improve UX in case of a buggy validation tool. I'd actually also emit a location-less warning then that the reported location wasn't found, so at least we see that something is wrong.

**Comment by dsgouda** [comment]
Will try to get to this myself at some point, should be a good starting point in understanding the mysteries of AutoRest Core
