### ISSUE TITLE
decimal is generated as "Decimal" type in python sdk which causes de-serialization error

### ISSUE THREAD

**Issue by Panda-Wang** [Azure/autorest#2243]
In swagger, the field is defined as "decimal" type: (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-consumption/2017-04-24-preview/swagger/consumption.json#L290)
```
"pretaxStandardRate": {
          "description": "The pretax listing price.",
          "type": "number",
          "format": "decimal",
          "readOnly": true
        }
```
But autorest generates python sdk for this property of type "Decimal": (https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-consumption/azure/mgmt/consumption/models/usage_detail.py#L109)
```
'pretax_cost': {'key': 'properties.pretaxCost', 'type': 'Decimal'},
```

this results de-serialization error in the response:
> DeserializationError: Unable to deserialize to object: type, KeyError: 'Decimal'

manually changing the type to "decimal" (lower case d) will solve the issue. looks like it should be "decimal" instead of "Decimal" at https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.Python/Model/PrimaryTypePy.cs#L66

**Comment by lmazuel** [comment]
So after some investigation:
- The correct type in Python is "decimal.Decimal":
```console
>>> from decimal import Decimal
>>> Decimal('2')
Decimal('2')
- If "decimal" in the Swagger is used, then the key type to generate should be "decimal" (in lower case). Because Upper case syntax is reserved for Models.
- If the Swagger return type is "decimal", Autorest is correct, the bug exists only if "decimal" is used inside a Model

So correct fix:
- Fix the model template to use the same return type that is used if the RestAPI returns directly a "decimal"
- Fix the documentation so type is "decimal.Decimal", not "Decimal".
