### ISSUE TITLE
New rule: Adding Linter rule for Header constant

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/autorest#2251]
Currently Autorests will honor Header field inside the swagger spec.
AutoRest currently have the 2-3 constants that they honor, rest all the text from the swagger is a passthru.
So if there is a linter rule that will check if the header value is the one AutoRest has, that would catch generating incorrect headers in the generated code files.
For e.g.
If swagger has the header value of "MIT", autorest will simply generate that text as license header text, rather the correct value for that is "MICROSOFT_MIT_NO_VERSION" that generates the right header text for the lincese.

**Comment by dsgouda** [comment]
A perfect candidate for our brand new, swanky typescript validator!

**Comment by dsgouda** [comment]
Assigning category Error per discussion with @shahabhijeet also looks like an SDKViolation.
