### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by bootstraponline** [Azure/autorest#2255]
It'd be nice to include support for Swift or Objective-C.

**Comment by fearthecowboy** [comment]
I'd like to add support for Swift and/or Objective-C in the not to distant future.

Our upcoming changes to the plugin model for generators should make that a lot easier to do. 

Stay tuned and let's see what we can work out.

**Comment by ymasaev** [comment]
While AutoRest team is working on that, you may want to use Swagger Codegen (https://github.com/swagger-api/swagger-codegen) to generate Swift, ObjC API clients for the time being. (For C# SDK, my team is still using AutoRest)

**Comment by olydis** [comment]
see #2452
