### ISSUE TITLE
[linter] Reevaluate Ids assigned to Validation rules

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2259]
Ids assigned to some validation rules need to be reevaluated (since ids are dependent on ValidationCategory)
This can be accomplished alongside https://github.com/Azure/autorest/issues/2196
@kirthik please point out the validation rules which need to be updated.

**Comment by kirthik** [comment]
All the IDs have to be updated. The way I am thinking is - RPC errors should be RE<Id> (start from 1) and RPC warnings should start RW<Id>. SDK Errors - SE<ID> and SDK warnings - SW<ID>

@dsgouda and @Veronicagg - Let me know your thoughts

**Comment by veronicagg** [comment]
@kirthik do we want to embed the "categories" (SDK/RPC) and "severity" (Error/Warning) in the ID of the rule? Are we planning to consume it in some way? and if any of those values change for any reason, do we care that the rule ID should get updated?

**Comment by kirthik** [comment]
Yes that is how I thought. I don't think we will consume the IDs in any way. If we change error to warning in future, then yes, i am thinking we will change the rule id too for instance SDK error to warning would be
SE<ID> changed to SW<NewId>. If it is too much hassle we can just go with numbers starting from 1 and remove M and S prefixes.

**Comment by dsgouda** [comment]
Reiterating what @kirthik suggested here. Assigning every single rule id of the form ```[S/R][E/W][number starting from 1]```

**Comment by veronicagg** [comment]
After further discussion on this, we've decided to use ID as R<number> "R" stands for "rule" so we make it generic and no need to change it later. We can leave numbers as they are, except for collisions, as there are rules that use the same number for example S2000 and M2000, so you can pick another subsequent number for one of them. Feel free to re-number if you feel appropriate. 
Please check with Shawn to make sure reporting is not going to be affected.

**Comment by sarangan12** [comment]
Task Completed
