### ISSUE TITLE
[linter] Add doc link and agg info to uber ValidationMessages json node

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2260]
When reporting ValidationMessages in the cli mode in json format it would be handy if we can also provide a link to the documentation describing the validation rules. This can be set as the uber metadata to the Json populated for validation messages.
We can also display other aggregated information like number of violations, number of violations per type, etc. @kirthik feel free to point out any metadata that can provide immediate value here.

**Comment by dsgouda** [comment]
Looked into this further and there is no clean ```AutoRest``` way of aggregating the validation messages before they are displayed. However, we can very easily modify the scripts that run AutoRest validator in the CI builds to actually aggregate information before displaying the errors.
Would this be a reasonable fix? I already have the changes ready but haven't opened a PR since I needed some feedback here.


A sample aggregates JSON in the CI builds would look something like below

```
{
  "Documentation": "some link here",
  "ValidationErrors": 1,
  "ValidationWarnings": 1,
  "TotalValidationViolations": 2,
  "OpenApiDocument": "F:/artemp/SwaggerReview/azure-rest-api-specs/arm-advisor/2016-07-12-preview/swagger/advisor.json",
  "errorList": [
    {
      "type": "Warning",
      "code": "OperationIdNounInVerb",
      "message": "Per the Noun_Verb convention for Operation Ids, the noun 'Recommendations' should not appear after the underscore.",
      "jsonref": "file:///F:/artemp/SwaggerReview/azure-rest-api-specs/arm-advisor/2016-07-12-preview/swagger/advisor.json#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Advisor~1generateRecommendations~1{operationId}/get/operationId",
      "json-path": "file:///F:/artemp/SwaggerReview/azure-rest-api-specs/arm-advisor/2016-07-12-preview/swagger/advisor.json#/paths/subscriptions/{subscriptionId}/providers/Microsoft.Advisor/generateRecommendations/{operationId}/get/operationId",
      "id": "M1001",
      "validationCategory": "SDKViolation",
      "providerNamespace": "Microsoft.Advisor",
      "resourceType": "generateRecommendations"
    },
    {
      "type": "Error",
      "code": "BodyTopLevelProperties",
      "message": "Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity. Model definition 'SuppressionContract' has extra properties ['suppressionId,ttl'].",
      "jsonref": "file:///F:/artemp/SwaggerReview/azure-rest-api-specs/arm-advisor/2016-07-12-preview/swagger/advisor.json#/definitions/SuppressionContract/properties",
      "json-path": "file:///F:/artemp/SwaggerReview/azure-rest-api-specs/arm-advisor/2016-07-12-preview/swagger/advisor.json#/definitions/SuppressionContract/properties",
      "id": "M3006",
      "validationCategory": "RPCViolation",
      "providerNamespace": null,
      "resourceType": null
    }
  ]
}
```

@veronicagg thoughts?

**Comment by veronicagg** [comment]
@dsgouda I like the format, but this may break scripts if there's anyone parsing output from here, please check with Shawn and Gaurav if you wanted to pursue it. It seems to be a P2 if it'll be CI only.

**Comment by dsgouda** [comment]
Yes, this needs to be CI only since we cannot aggregate the information related to validation rules before logging them from AutoRest.
I agree that this could mess with existing builds, we can instead just append an additional node which simply displays the agg info.

**Comment by veronicagg** [comment]
ok, I'd like to think a bit more about this, let keep this as P2 per your label and work on other issues first. thanks for the investigation!
