### ISSUE TITLE
Compatibility with Mono?

### ISSUE THREAD

**Issue by alexreg** [Azure/autorest#2266]
What is the minimum version of Mono required to run the latest released? It would be nice to have this information published.

**Comment by olydis** [comment]
See https://github.com/Azure/autorest#installing-autorest
As stated there, installing AutoRest is the same on all platforms now - no mono required! It's running on dotnet core now which is automatically acquired for most platforms. The table gives prerequirements per platform we've tested for.

**Comment by alexreg** [comment]
Thanks, that's helpful!
