### ISSUE TITLE
What is the lowest compatible version for Newtonsoft.json when using autorest generated code 

### ISSUE THREAD

**Issue by dlgit** [Azure/autorest#2270]
I use AutoRest code generator 1.0.1.0 to get auto generated client from a swagger. May I know what is lowest version for Newtonsoft.Json Nuget package that when using can work properly with the auto generated codes?

**Comment by fearthecowboy** [comment]
The Client Runtime is the thing that ultimately determines that. I believe 6.0.8 is the lowest.

https://github.com/Azure/azure-sdk-for-net/tree/vs17Dev/src/SdkCommon/ClientRuntime

**Comment by dlgit** [comment]
You are right. Thank you!
