### ISSUE TITLE
Unable to change dependency for  io.reactivex » rxjava v1.2.4.  to update 2.1.0

### ISSUE THREAD

**Issue by HATIMS** [Azure/autorest#2273]
Unable to change dependency for  io.reactivex » rxjava v1.2.4.  to update 2.1.0 ('io.reactivex.rxjava2').  I need to be able to do the following:

subscribeOn(Schedulers.newThread())
._observeOn(AndroidSchedulers.mainThread())_
.subscribe(new SettingsObserver(this));

**Comment by fearthecowboy** [comment]
This appears to be a java runtime issue -- please file in https://github.com/Azure/autorest-clientruntime-for-java if this is still an issue.
