### ISSUE TITLE
Request: adding ResourceReference into Azure ClientRuntime dll

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#228]
Hi all,

I have below definition which represent a reference to an azure resource. Looks like it's pretty common. Can we consider adding below data model to the Azure ClientRuntime dll?

        "ResourceReference": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Gets or sets the resource id."
                },
                "name": {
                    "type": "string",
                    "readOnly": true,
                    "description": "Gets the resource name."
                },
                "type": {
                    "type": "string",
                    "readOnly": true,
                    "description": "Gets the resource type."
                }
            }
        },

**Comment by markcowl** [comment]
@tonytang-microsoft-com we decided against a central repository for common swagger objects, for maintenance reasons.
