### ISSUE TITLE
Operations API must be implemented for the service.

### ISSUE THREAD

**Issue by jakubin** [Azure/autorest#2288]
When I try to generate a client for my service I get this error:
```ERROR: Operations API must be implemented for the service.```

Is there any page, explaining what the problem is - the description leaves me clueless.

**Comment by fearthecowboy** [comment]
That looks like you have an older version where the rules for Azure services were turned on by default.

Try updating and try again?

``` bash
npm install -g autorest
autorest --reset 
```

**Comment by jakubin** [comment]
Yes, that was my problem. Thanks for help.
