### ISSUE TITLE
Implement default values query parameters

### ISSUE THREAD

**Issue by israellot** [Azure/autorest#2292]
When a query parameter has a default value, the generated operation method could make it an optional with default value.

`{"name": "q",
                    "in": "query",                 
                    "required": true,
                    "type": "string",
                    "default": "default"}`

would produce

`OperationMethod(string q="default")`

**Comment by olydis** [comment]
The spec also states that `default` values are to be interpreted as "the server assumes this if nothing was specified", hence specifying `required: true` and `default` doesn't really make sense as per the spec.

We are hesitant to extend the spec with our own logic and interpretations. We have done that in the past (yes, if you have `required: false`, we *do* use `default` on the client side, which is already generating discussions), people are now relying on it, so we're stuck with the behavior. We recently added support for "one-off" behavior as yours without having to change AutoRest itself.

In your case, the fix involves adding a custom "transformer" that changes all parameters with `default` value to be `required: false` in memory, right before passing it to later stages of AutoRest (essentially it abuses AutoRest's current interpretation of the world and tweaks the input accordingly).

You will need to run AutoRest with a configuration file (in case you're not already), see https://github.com/Azure/autorest/blob/master/docs/user/cli.md for documentation. A good starting point is https://github.com/Azure/autorest/tree/master/Samples/3b-custom-transformations.

You will then need a directive as follows (not tested, but you'll get the idea):
``` yaml
from: swagger-document
where: $..*[?(@.default)]
transform: $.required = false
```
