### ISSUE TITLE
No way to return response object from long-running POST

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2295]
There seems to be a deficiency in AutoRest-based .NET client (and possibly other language clients, I haven't investigated) regarding database pause/resume, which are long-running POST operation.

These operations are:
1.  `POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/pause` 
2. `POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/resume`. 

The new Swagger/AutoRest-based client does not have a declared response type for Pause/Resume, so in generated clients it just returns void
-	API specification: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2014-04-01/swagger/sql.core.json#L19
-	Generated .NET SDK: https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/SqlManagement/Management.Sql/Generated/DatabasesOperationsExtensions.cs#L507 

In Hyak-based client SDKs, Pause and Resume operations return Database resources 
-	API specification: https://github.com/Azure/hydra-specs-pr/blob/master/Sql2/Microsoft.Azure.Management.Sql.Specification/Database%20Activation/DatabaseActivationOperations.Pause.cs#L41
-	Generated .NET SDK: https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Sql/SqlManagement/Generated/DatabaseActivationOperationsExtensions.cs#L227 ). 

I wanted to update the Swagger to declare the Database response type so that Pause/Resume would no longer return void. However this turns out to not work. Here’s why: both Pause and Resume return Location and Azure-AsyncOperation. Here's an example response (collected by fiddler):

```
HTTP/1.1 202 Accepted
Cache-Control: no-store, no-cache
Content-Length: 77
Content-Type: application/xml; charset=utf-8
Location: https://management.azure.com/subscriptions/f28872d6-4a93-4bb1-84b9-aecb02b6af4c/resourceGroups/sqlcrudtest-5536/providers/Microsoft.Sql/servers/sqlcrudtest-2059/databases/sqlcrudtest-4364/operationResults/a1eb8ae2-c93e-496f-a8a6-c0ae53d06dd0?api-version=2014-04-01-Preview
Retry-After: 30
x-ms-request-id: a1eb8ae2-c93e-496f-a8a6-c0ae53d06dd0
X-Content-Type-Options: nosniff
Preference-Applied: return-content
DataServiceVersion: 3.0;
Strict-Transport-Security: max-age=31536000; includeSubDomains
Azure-AsyncOperation: https://management.azure.com/subscriptions/f28872d6-4a93-4bb1-84b9-aecb02b6af4c/resourceGroups/sqlcrudtest-5536/providers/Microsoft.Sql/servers/sqlcrudtest-2059/databases/sqlcrudtest-4364/azureAsyncOperation/a1eb8ae2-c93e-496f-a8a6-c0ae53d06dd0?api-version=2014-04-01-Preview
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id: bf53d222-b49b-44f3-a841-cf2e93df8f4e
x-ms-routing-request-id: WESTUS2:20170525T230700Z:bf53d222-b49b-44f3-a841-cf2e93df8f4e
Date: Thu, 25 May 2017 23:07:00 GMT

{"operation":"DeactivateDatabaseAsync","startTime":"\/Date(1495753619183)\/"}
```

The hyak client would use Location header to poll and everything would work. However the AutoRest client prefers to use Azure-AsyncOperation. When this eventually completes, here's the response from the server:

```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
Vary: Accept-Encoding
x-ms-request-id: 55502085-26a2-4cb3-9fc7-f866f9a0eecd
X-Content-Type-Options: nosniff
DataServiceVersion: 3.0;
Strict-Transport-Security: max-age=31536000; includeSubDomains
Azure-AsyncOperation: https://management.azure.com/subscriptions/f28872d6-4a93-4bb1-84b9-aecb02b6af4c/resourceGroups/sqlcrudtest-5536/providers/Microsoft.Sql/servers/sqlcrudtest-2059/databases/sqlcrudtest-4364/azureAsyncOperation/a1eb8ae2-c93e-496f-a8a6-c0ae53d06dd0?api-version=2014-04-01-Preview
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14992
x-ms-correlation-request-id: 6b8f7357-fddb-42b1-8a59-dc5617558218
x-ms-routing-request-id: WESTUS2:20170525T230852Z:6b8f7357-fddb-42b1-8a59-dc5617558218
Date: Thu, 25 May 2017 23:08:51 GMT
Content-Length: 88

{"operationId":"a1eb8ae2-c93e-496f-a8a6-c0ae53d06dd0","status":"Succeeded","error":null}
```

Now we get to this point in `AzureClientExtensions.GetLongRunningOperationResultAsync`:

https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/AzureClientExtensions.cs#L130

There are 2 issues here:
1. The server is not telling the client what the location of the final resource is (no location header), so there is no way for the client to find the resource.
2. Even if the location header was provided, the client isn't looking at it. If the operation was PUT, it would try to GET the URI that it PUT to. However this is a POST. So the client doesn't even try to get the response.

We can fix #1 in the service, however I don't want to take action until we have a clear understanding of what the client expects and how the client will handle the response.

**Comment by fearthecowboy** [comment]
Definitely going to have to make this scenario work in with the vNext generator.

**Comment by olydis** [comment]
@shahabhijeet This is a TODO for the ClientRuntime now, correct? Is there an issue to track it? If so, we can close this one here 🙂

**Comment by jaredmoo** [comment]
fyi fixing this will likely require changes to most client runtimes, not just .net.

**Comment by shahabhijeet** [comment]
@olydis yes this is a CR fix and is currently being tested in PowerShell
this is currently being tracked here https://github.com/Azure/azure-sdk-for-net/issues/3715
