### ISSUE TITLE
Get collection (list) should return a "value" array

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2301]
It should check for the presence of value keyword. Something like this -
"OperationListResult": {
     "description": "Result of the request to list Storage operations. It contains a list of operations and a URL link to get the next set of results.",
      "properties": {
        **"value"**: {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Operation"
          },
          "description": "List of Storage operations supported by the Storage resource provider."
        }
      }
    },

**Comment by veronicagg** [comment]
I believe this is already implemented in CollectionObjectPropertiesNamingValidation rule (https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Validation/CollectionObjectPropertiesNaming.cs#L57) 
@ravbhatnagar Are there cases where this rule should trigger that you're not seeing?

**Comment by ravbhatnagar** [comment]
@veronicagg - yes, i dont see this getting triggered. Snippet from swagger -
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/VersionedApplicationTypeList"
            }
          }


"VersionedApplicationTypeList": {
      "description": "The list of versioned application types",
      "properties": {
        "value1": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/VersionedApplicationType"
          }
        }
      }
    },

**Comment by veronicagg** [comment]
@ravbhatnagar ok, we'll look into it, thanks.

**Comment by dsgouda** [comment]
Investigated this and I might have a couple of theories as to what might be going wrong,
A. The list operation does not have the `x-ms-pageable` extension set 
OR
B. The list operation does not have an operationId of the form '*_list*'

If either of these conditions are met we go ahead and check if the list model definition has a property named "value".
@ravbhatnagar Could you provide the entire spec or perhaps check the conditions I outlined above.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved to new repo, see link above.
