### ISSUE TITLE
[NewRule] Response of PUT operation should be a 201 with a provisioningState property

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2302]
If PUT is a long running operation, the response should be a 201
It should have a property called "provisioningState" under properties
The response should not be a 202.

**Comment by ravbhatnagar** [comment]
Make this a warning for now. I know a lot of RPs violate this one.

**Comment by veronicagg** [comment]
@ravbhatnagar We may have conflicting info here, so I'd like to clarify.... we have these guidelines for the x-ms-long-running operations https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-long-running-operation 
we also are working on a rule https://github.com/Azure/autorest/pull/2307 that will check on 202.
Could you provide some supporting documentation on the behavior?

**Comment by ravbhatnagar** [comment]
Its a recommendation. Both patterns are supported but we would like new APIs to adopt to the 201 pattern as it is more deterministic and clients can leverage it better to provide a consistent experience.
Hence I said make this a warning.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved to new repo, see link above.
