### ISSUE TITLE
[NewRule] id, name and type top level properties should be present in the response of GET/PUT/PATCH

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2303]
It is fine if these properties are not present in POST operation response. 
If there is a rule already on this, please ignore.
If this could be merged with an existing similar rule, that is fine too.

**Comment by veronicagg** [comment]
@ravbhatnagar is this related to the response being a resource or not? we have several rules on this, so I'm not sure if this gets covered by them. Once the list of rules is documented, it'd be great if you can take a look and see if this situation gets covered or not - or provide us a valid swagger example that would report this rule and not get flagged by any of the other rules. thanks!

**Comment by ravbhatnagar** [comment]
yes, in the response for a resource. Will open a bug if I find an example. Closing for now.
