### ISSUE TITLE
[BUG] Top level properties should not be repeated inside properties bag

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2304]
Sample swagger in email.

**Comment by veronicagg** [comment]
ArmResourcePropertiesBag rule seems not to be checking on "$ref" for the repeated properties.
Swagger extract:
    "VersionedApplicationType": {
      "description": "The versioned application type resource",
      "properties": {
        "properties": {
          "$ref": "#/definitions/VersionedApplicationTypeProperties"
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        }
      ]
    },
 "VersionedApplicationTypeProperties": {
      "description": "The versioned application type properties",
      "properties": {
	"id": {
          "type": "string",
          "description": "The name of the application type"
        },
        "provisioningState": {
          "readOnly": true,
          "type": "string",
          "description": "The current deployment or provisioning state, which only appears in the response"
        },
        "typeName": {
          "type": "string",
          "description": "The name of the application type"
        },
        "typeVersion": {
          "type": "string",
          "description": "The version of the application type"
        },
        "packagedBuildURL": {
          "type": "string"
        },
        "defaultParameterList": {
          "type": "array",
          "description": "The default parameter list",
          "items": {
            "properties": {
              "Key": {
                "type": "string"
              },
              "Value": {
                "type": "string"
              }
            }
          }
        }
      }
    },

**Comment by veronicagg** [comment]
Closing issues as it's been moved to link above.
