### ISSUE TITLE
[BUG] Top level properties cannot be outside a fixed set

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/autorest#2305]
Sample swagger in email.
lintertest->resource-> foo was added as a top level property. It was added to the "Resource" model which was inherited by other models. So, it should have been shown as violation in each model which did an allOf on Resource. It works and identifies the violation correctly when there is a disallowed top level property directly in the model which does an allOf on “resource” model.

**Comment by veronicagg** [comment]
Swagger extract:
    "Resource": {
      "description": "The resource model definition.",
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Resource ID."
        },
				"foo": {
          "readOnly": true,
          "type": "string",
          "description": "Resource ID."
        },
        "name": {
          "readOnly": true,
          "type": "string",
          "description": "Resource name."
        },
        "type": {
          "readOnly": true,
          "type": "string",
          "description": "Resource type."
        },
        "location": {
          "type": "string",
          "description": "Resource location."
        },
        "tags": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Resource tags."
        }
      },
      "required": [
        "location"
      ],
      "x-ms-azure-resource": true
    },

**Comment by sarangan12** [comment]
Task completed
