### ISSUE TITLE
Evaluate and assign MergeState and DocumentType validation categories to all validation rules

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2313]

**Comment by vishrutshah** [comment]
From the PR https://github.com/Azure/azure-rest-api-specs/pull/1288, we should categorize following rules as ARM specific. Just listing them here for our FYI

- [ ] `APIVersionPattern`
- [ ] `OperationsAPIImplementation`
- [ ] `LROStatusCodesReturnTypeSchema`
- [ ] `PatchInOperationName`
- [ ] `PutInOperationName`

Reviews , please make sure whether this is right and correct on the PR :)

**Comment by dsgouda** [comment]
@vishrutshah please file an issue to this effect it would be easier to track that way.

**Comment by dsgouda** [comment]
PR merged, closing issue.
