### ISSUE TITLE
Url in C# generated code invalid if optional segement

### ISSUE THREAD

**Issue by matthewDDennis** [Azure/autorest#2317]
See the issue in SwashBuckle.AspNetCore
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/406

**Comment by olydis** [comment]
AutoRest does not support optional path parameters and I'm pretty sure it's not part of the Swagger specification.

**Comment by olydis** [comment]
no, this is not allowed according to http://swagger.io/specification/#parameterObject:
```
If the parameter is in "path", this property is required and its value MUST be true. Otherwise, the property MAY be included and its default value is false.
```
