### ISSUE TITLE
Post method with no content does not set ContentType

### ISSUE THREAD

**Issue by matthewDDennis** [Azure/autorest#2320]
If you have a webapi actionwith an optional parameter which is the content for the POST request, the AutoRest client generated method does not set the ContentType if the parameter is null.  This result in an unsupported media error from the webapi.

**Comment by olydis** [comment]
Unfortunately AutoRest's behavior is controversial when sending `null` in general. While JSON knows `null` (i.e. one could literally send the string `null`), AutoRest always sends an empty body when passing `null`. An empty body is not valid JSON, so setting the content type would actually be a lie!

Unfortunately, changing this odd behavior would be a breaking change, users might already rely on that behavior. Fortunately, we will soon write a second generation of generators (leaving the old ones untouched and still usable) which will allow us to do things like this right.

**Comment by matthewDDennis** [comment]
However, at least ASP.NET Core WebAPI handles the case of an empty body with a json content type.

**Comment by fearthecowboy** [comment]
Newtonsoft.json does us a huge disfavor here. 

Adding to the list of things for vNext generator design. Definitely want this to work in the new world.
