### ISSUE TITLE
x-ms-pageable validation

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2323]
[This](https://github.com/Azure/autorest/issues/2275#issuecomment-305332593) issue was caused by a Swagger that contains a broken `x-ms-pageable` definition.

In general, it would be awesome to check whether properties `nextLinkName` or `itemName` exist in the target model. (Note that if `itemName` is not specified, one should also check whether the default is present...).

Bugs like that seem to be flagged by some generators (by failing), but it would be nice to see that immediately, when editing the Swagger!

**Comment by veronicagg** [comment]
@olydis could you share the specific example where this wasn't flagged, we do have some checks on this, specifically https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Validation/Extensions/NextLinkPropertyMustExist.cs

**Comment by olydis** [comment]
@veronicagg We do indeed have a rule for that, sorry for not checking earlier... if I remember right, the issue was simply that some generators "successfully" generate code and don't complain if the `nextLinkName` is bogus, so somehow I deduced that this must mean we don't have a validation rule. 😆
