### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by Alanwe** [Azure/autorest#2327]
Has anyone considered getting R supported?

**Comment by fearthecowboy** [comment]
Hey @Alanwe,

We haven't looked at R yet, but we're close to being able to publish the plugin interface so that someone could create a generator without too much difficulty.

**Comment by Alanwe** [comment]
Once available, if someone can direct me I am happy to have a go. 
I've been working on some R package for Azure and it would be much easier to use swagger.
Thanks

**Comment by olydis** [comment]
see #2452
