### ISSUE TITLE
Discussion: Modeling LRO using swagger

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#233]
Hi,

Let's say I have one operation called RunWorkflow which returns 202, and it have RequestInfo in the response body. The Location header of the 202 response points to another operation named 'GetRunWorkflowResult', which return 200 and have RunResult in the response body.

Looks like we currently model the LRO like below:

```JSON
"RunWorkflow": {
            "post": {
                "description": "Runs a workflow.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "RunResult (instead of RequestInfo)"
                        }
                    }
                },
                "x-ms-long-running-operation": true
            }
        },
```

If my understand it correctly, the **responses** defined in the **RunWorkflowOperation** is really for responses of **GetRunWorkflowResult**. That feels like incorrect from swagger spec's point of view.

Is there any discussion over this topic?

**Comment by markcowl** [comment]
@tonytang-microsoft-com Adding the additional status response for 201 is allowed, please feel free to add this to your swagger to make it more accurate.
