### ISSUE TITLE
"output-folder" is less prioritary than "XXX.output-folder" in md

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2337]
Let's say I call Autorest this way:
```bash
autorest readme.md --output-folder=D:\MyFolder
```
And that the Readme is
```markdown
# Scenario

> see https://aka.ms/autorest

### Python

```yaml
python:
  output-folder: Generated/Python
\```

```

I expect the folder to be used to be D:/MyFolder. Currently it's Generated/Python

IOW, I think the order of priority should be:

1. --XXXX.output-folder
2. --output-folder
3. (inside MD) XXXX: output-folder
4. (inside MD) output-folder

Today it seems to be:
1. --XXXX.output-folder
2. (inside MD) XXXX: output-folder
3. --output-folder
4. (inside MD) output-folder

Thoughts?

**Comment by olydis** [comment]
can you try
```yaml
python:
  output-folder: ${output-folder}/Generated/Python
```
?
The priorities you mention in the issue title are 100% by design 🙂

**Comment by lmazuel** [comment]
ho! that's interesting :) I will try that

**Comment by lmazuel** [comment]
@olydis
![image](https://user-images.githubusercontent.com/1050156/26905025-bc431a0e-4b99-11e7-87ef-682ee1c09894.png)
 :/

**Comment by lmazuel** [comment]
I understand the priority now, that's ok. But being able to re-inject value from a higher level as you suggest would be awesome.

**Comment by fearthecowboy** [comment]
Not Braces!

Parens! 

``` yaml
output-folder: $(output-folder)/foo
```

**Comment by lmazuel** [comment]
Works, thanks!!
