### ISSUE TITLE
Incorrect validation tests

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2338]
The tests [here](https://github.com/Azure/autorest/blob/a238ca19b4f6a095cec01d7ce26da891df26bc64/src/modeler/AutoRest.Swagger.Tests/SwaggerModelerValidationTests.cs#L282) and [here](https://github.com/Azure/autorest/blob/a238ca19b4f6a095cec01d7ce26da891df26bc64/src/modeler/AutoRest.Swagger.Tests/SwaggerModelerValidationTests.cs#L673) are not exactly asserting anything, we should ensure that the tests are enabled and are executed as expected.

**Comment by dsgouda** [comment]
And possibly [this](https://github.com/Azure/autorest/blob/a238ca19b4f6a095cec01d7ce26da891df26bc64/src/modeler/AutoRest.Swagger.Tests/SwaggerModelerValidationTests.cs#L126)

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
