### ISSUE TITLE
Documentation for conditional fenced code blocks

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2339]
I want to do a "and" clause that looks like this:

```markdown
```yaml $(python)
python:
  namespace: foo.bar
\```
```yaml $(python) and $(create)
python:
  package-name: foo-bar
\```
```

To be able to call this way:
```bash
autorest readme.md --python
autorest readme.md --python --create
```

Otherwise, the only way I see is to ask people to write:
```bash
autorest readme.md --python --python.package-name=foo-bar
```

**Comment by fearthecowboy** [comment]
try:

~~~ markdown

``` yaml $(foo) && $(bar)
...
```
~~~

**Comment by lmazuel** [comment]
That works! Thanks!

May I ask you to document to available syntax?

**Comment by olydis** [comment]
see https://github.com/Azure/autorest/blob/2.0/docs/proposals/generator-specific-settings/literate-configuration.md#additional-uses-of-meta-variables
