### ISSUE TITLE
Add an extension point to Deserialise exceptions

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/autorest#2341]
In C#, the Azure Rest client supports "CloudException"s
https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-pageable/example1.cs#L383

It would be nice if the standard Rest client allowed custom deserialisation when the code is not 200.
This will help with the Power BI Client.

Ideally, calls to a service don't require a try catch. The logger should handle the exception and log the details, including the body which normally contains the real exception.

For example, remove the try catch from here;
https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/c5d97250df67cc6c369ac71a810e21e6055e1025/ProvisionSample/Program.cs#L166

**Comment by mikeblakeuk** [comment]
Sample of the issue here https://github.com/Microsoft/PowerBI-CSharp/compare/master...mikeblakeuk:v2_exception_messages?expand=1

**Comment by fearthecowboy** [comment]
This is something we can factor into the vNext generators -- changing this behavior in existing generators isn't possible.
