### ISSUE TITLE
Write documentation for the following set of rules: NextLinkPropertyMustExist, PageableRequires200Response...

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2344]
Please create documentation https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md following similar format as https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3026-trackedresourcepatchoperationvalidation
You may pick up details from https://github.com/Azure/autorest/tree/master/docs/developer/validation-rules if the rule was documented there before. 
Please document the following rules - make sure to update the table and details:
NextLinkPropertyMustExist
PageableRequires200Response
AnonymousBodyParameter
APIVersionPattern
ArmResourcePropertiesBag
AvoidAnonymousTypes
BodyPropertiesNamesCamelCase
BodyTopLevelProperties
DefinitionsPropertiesNamesCamelCase
EnumInsteadOfBoolean
InvalidSkuModel
XmsEnumValidation

**Comment by vishrutshah** [comment]
Just adding one more here `TrackedResourceListBySubscription` regarding https://github.com/Azure/azure-rest-api-specs/pull/1258#discussion-diff-120765831R51

**Comment by veronicagg** [comment]
Need to updated IDs based on the issue @vishrutshah referenced above.

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1318
