### ISSUE TITLE
Write documentation for the following set of rules: MutabilityWithReadOnly, XmsPathsMustOverloadPaths ...

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2346]
Please create documentation https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md following similar format as https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3026-trackedresourcepatchoperationvalidation
You may pick up details from https://github.com/Azure/autorest/tree/master/docs/developer/validation-rules if the rule was documented there before.
Please document the following rules - make sure to update the table and details:
MutabilityWithReadOnly
XmsPathsMustOverloadPaths
AvoidNestedProperties
CollectionObjectPropertiesNaming
DefaultMustBeInEnum
NamePropertyDefinitionInParameter
OperationIdNounConflictingModelNames
OperationIdNounVerb
OneUnderscoreInOperationId
OperationsAPIImplementation
ParameterizeProperties
ParameterNotDefinedInGlobalParameters
RequiredPropertiesMissingInResourceModel
RequiredReadOnlyProperties
SubscriptionIdParameterInOperations
ValidFormats

**Comment by dsgouda** [comment]
Skipping `OperationIdNounConflictingModelNames` since we may have to remove the rule.

**Comment by dsgouda** [comment]
Skipping `ParameterizeProperties` since this may be removed soon.

**Comment by dsgouda** [comment]
PR merged [here](https://github.com/Azure/azure-rest-api-specs/commit/78a9bb3ee08a36ed8266fb43f9eae93c3715555f), closing issue.

**Comment by dsgouda** [comment]
Need to write documentation for `OperationIdNounConflictingModelNames` and `ParameterizeProperties` since these are still in  production

**Comment by veronicagg** [comment]
Closing issue since we're moving linter related issues to https://github.com/Azure/azure-openapi-validator repo.
