### ISSUE TITLE
Unable to find asset for version '1.0.1-20170609-2300-nightly'

### ISSUE THREAD

**Issue by JacekKosciesza** [Azure/autorest#2351]
After installation (I was trying both npm install -g autorest and EXE installer) when I try to use it I get Unable to find asset for version '1.0.1-20170609-2300-nightly'. 

autorest --help
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  0.20.0
  NetCore framework :      1.0.5
  Latest Core Installed :  <none>
  Requested Core Version : <none>

node --version
v7.7.2

Windows

**Comment by rlarno** [comment]
I had the same thing, using ` --version=latest-release` I got it to work.

**Comment by JacekKosciesza** [comment]
@rlarno It worked, thanks.
