### ISSUE TITLE
Linter should categorize errors/warnings in order of severity

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2352]
Right now warnings and errors are intermixed in the report.
Also the bot reports warnings/errors together.

If there is supposed to be a severity difference between warnings and errors (i.e. errors are must fix warnings are should fix) it would be good to order the output into categories by severity so that it's easier for somebody to triage what is must fix vs just a recommendation.

**Comment by veronicagg** [comment]
@matthchr have you tried https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest This should help with the categories. 
We will evaluate command line reporting priorities.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
