### ISSUE TITLE
ApplicationTokenProvider.LoginSilentWithCertificateAsync is missing an overload that allows both ActiveDirectoryServiceSettings and TokenCache to be provided

### ISSUE THREAD

**Issue by matt1883** [Azure/autorest#2356]
Re: Microsoft.Rest.ClientRuntime.Azure.Authentication NuGet package, v2.3.1:

The method ``ApplicationTokenProvider.LoginSilentWithCertificateAsync`` is missing an overload that allows both ``ActiveDirectoryServiceSettings`` and ``TokenCache`` to be provided. Here are the three options that exist today in ``ApplicationTokenProvider``:

    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate);
    
    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate, 
       ActiveDirectoryServiceSettings settings);
    
    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate, 
       TokenCache cache);

For context, ``UserTokenProvider`` and non-cert ``ApplicationTokenProvider`` support the use of both ``ActiveDirectoryServiceSettings`` and ``TokenCache`` today:

    // from UserTokenProvider:
    public static Task<ServiceClientCredentials> LoginWithPromptAsync(string domain, ActiveDirectoryClientSettings clientSettings, 
       ActiveDirectoryServiceSettings serviceSettings, 
       TokenCache cache);
    
    // from ApplicationTokenProvider:
    public static Task<ServiceClientCredentials> LoginSilentAsync(string domain, string clientId, string secret, 
       ActiveDirectoryServiceSettings settings, 
       TokenCache cache);

Supporting both of these parameters is important for scenarios where, for example, a non-default token audience needs to be used in conjunction with a token cache.

**Comment by olydis** [comment]
Hi @matt1883, [ClientRuntime.Azure.Authentication](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SdkCommon/ClientRuntime.Azure.Authentication) (and anything else related to the client runtime) is developed in the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) repo, please open an issue there 🙂 

This repo is responsible for code generation for multiple languages (one of which is C#, which happens to use ClientRuntime.Azure.Authentication), provides OpenAPI validation, etc.

**Comment by matt1883** [comment]
I've recreated the issue in [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net). Thanks for letting me know.

Azure/azure-sdk-for-net#3366

@olydis The NuGet package page for [Microsoft.Rest.ClientRuntime.Azure.Authentication](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/) shows this Azure/Autorest repo as the project URL, hence the mixup.

**Comment by olydis** [comment]
@matt1883 Ahhh thanks for letting me know, I'll ask them to change the repo URL
