### ISSUE TITLE
[linter] Evaluating validation rules applicability to data-plane specs

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2359]
The following validation rules need to be reassessed based on their applicability to data plane specs

- APIVersionPattern.cs
- AnonymousBodyParameter.cs
- ArmResourcePropertiesBag.cs
- AvoidAnonymousTypes.cs
- AvoidMsdnReferences.cs
- AvoidNestedProperties.cs
- CollectionObjectPropertiesNaming.cs
- DeleteMustNotHaveRequestBody.cs
- DescriptionAndTitleMissing.cs
- DescriptiveDescriptionRequired.cs
- EnumInsteadOfBoolean.cs
- MutabilityWithReadOnly.cs
- GuidUsage.cs
- HttpsSupportedScheme.cs
- InvalidVerbUsed.cs
- LROStatusCodesReturnTypeSchema.cs
- ListInOperationName.cs
- NamePropertyDefinitionInParameter.cs
- NonApplicationJsonType.cs
- OperationDescriptionOrSummaryRequired.cs
- OperationIdNounVerb.cs
- OperationIdSingleUnderscore.cs
- OperationNameValidation.cs
- UniqueResourcePaths
- XmsPageableListByRGAndSubscriptions.cs

I have not added anything related to "resources" yet, since I wasn't sure if the concept of `Resource` is applicable to dataplane specs

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
