### ISSUE TITLE
[data-plane priority] Content-Type header parameter next to binary/stream body parameter

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2374]
On our road to enable data plane generation, we (the C# people) have hit a slightly problematic scenario that was no supported in C# but is now. Please make sure it is also supported in your respective language.

## Scenario
An API call accepts images (i.e. binary data) that can be of different types, say `image/png` or `image/jpeg`.
The Swagger for this call says `consumes: ['image/png', 'image/jpeg']`, accordingly.
Since our generated clients accept raw binary data or a stream, we *have* to enable users to specify the content type header of that data, as otherwise what header are we gonna send?
So far so good, so you add a header parameter called `Content-Type` to your Swagger.

## Problem 1
According to the OpenAPI standard, a header parameter called `Content-Type` are to be ignored as if it was not specified at all.
I guess their idea is that the content type should be fully derivable from the request body, which usually makes sense (why would you offer the opportunity to specify and hence possibly screw up derivable information... just derive it).
However, in this very scenario (I think binary data in general), there is no practical way to derive the content type!

### Solution
AutoRest has always ignored that part of the spec, so "you guys" (the language generator) will see the parameters show up on your side already, sweet.

## Problem 2
The generated code may not do the "right thing" with the parameter. This hit us in C# since the method to add custom headers to an HTTP request rejects any attempts to set `Content-Type` ("this is special, please use the dedicated property, blablabla").

### Solution
Make sure your generator does the right thing and generates *working* code (note that the C# bug was only exposed at runtime). If not, please fix it.

## Example and Testing Strategy
I've added an [example](https://github.com/Azure/autorest/tree/master/Samples/test/stream-with-content-type) testing for this very behavior, feel free to use this example as your test case.
Ideally, you can just check if the generated code in there works up to the point where a correct HTTP request is sent out.
Note that the configuration file also contains some more details about what changes I did for C# and language agnostically, maybe it helps.

**Comment by lmazuel** [comment]
@olydis just curious, when you say "According to the OpenAPI standard", you think 2.0 right? What about 3.0?

**Comment by olydis** [comment]
from the OpenAPI 3.0 draft:
![image](https://user-images.githubusercontent.com/9320958/27358352-1269eba2-55cb-11e7-9e8d-399414f71693.png)

**Comment by lmazuel** [comment]
@olydis So in Python, the only problem is the case. If the OpenAPI file uses `Content-Type` *exact* name (like your example) this is fine. However, if string is for example `content-type`, it will be ignored (and the content type sent will be the first one in the `consumes` list).
Will you ensure the `Content-Type` exact naming (at the linting level, or the model core parsing level) or should we be resilient to that?

**Comment by olydis** [comment]
Since parameter names are generally case sensitive (imagine path or query parameters), I think `Content-Type` is no exception. Actually, for my C# fix I made it case sensitive on purpose, so it won't work there either if the Swagger says `content-type` 😉 Thanks for checking!

**Comment by olydis** [comment]
And yes, a linter rule should do, however I imagine it to be a super rare case to send content type anyways, so that's not high priority. Definitely no parsing/auto-correction magic, we should generate exactly what the Swagger says.

**Comment by mcardosos** [comment]
Go has no problem with this.
Unless the methods happen to be paged.

**Comment by olydis** [comment]
@mcardosos let's not go too crazy ;-) no paging

**Comment by amarzavery** [comment]
spoke to @olydis . It is a simple one line change for node.js. I think it would be same for ruby too. This [line](https://github.com/Azure/autorest/blob/master/Samples/test/stream-with-content-type/ClientRuby/generated/stream_with_content_type/image.rb#L71) should go up. It should be at [line 66](https://github.com/Azure/autorest/blob/master/Samples/test/stream-with-content-type/ClientRuby/generated/stream_with_content_type/image.rb#L66) after `request_headers = {}`.

**Comment by amarzavery** [comment]
@sarangan12 - Please take a look for ruby.

**Comment by jianghaolu** [comment]
Verified in Java overwriting `Content-Type` is allowed.

**Comment by amarzavery** [comment]
reopening the issue for ruby.

**Comment by sarangan12** [comment]
Overwriting content-type is allowed for ruby

**Comment by olydis** [comment]
@sarangan12 [no](https://github.com/Azure/autorest/blob/master/Samples/test/stream-with-content-type/ClientRuby/generated/stream_with_content_type/image.rb#L69-L71)

**Comment by sarangan12** [comment]
Synched up with @olydis and cleared up the issue.
