### ISSUE TITLE
Remove NonApplicationJsonType and ParameterizeProperties rules

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2383]
Based on discussions, let's remove these rules:
NonApplicationJsonType - Rule is inaccurate as AutoRest now supports other types.
ParameterizeProperties	-  After the rule was put in practice, ARM team came back allowing non-parameterized properties, so accuracy of the rule is doubtful. ARM guidelines should include this if this is an ARM preference.

**Comment by dsgouda** [comment]
@olydis do we support non-appjson types in AutoRest currently? Is there a reason to discourage authors from using non-appjson types?

**Comment by olydis** [comment]
as said in stand-up: yes, we very much support other media types ('application/xml', anything that's stream-based like 'image/...', ...) but for ARM it makes sense to discourage all except JSON

**Comment by dsgouda** [comment]
@ravbhatnagar are there any guidelines around allowing non-app/json type consumes and produces for ARM specs?

**Comment by ravbhatnagar** [comment]
We don't allow any other type of data like xml or image flowing through ARM. So only type allowed is json. Could we make a rule apply only to ARM Control plane APIs?

**Comment by dsgouda** [comment]
Absolutely, what severity are you thinking, `error` or `warning`?

**Comment by veronicagg** [comment]
@ravbhatnagar could you point us to your documentation indicating only application/json is supported in ARM? 
@dsgouda I think we should adjust the message of the rule in that case to indicate the ARM restriction, in addition to updating the applicability to only arm and the category to RPCViolation. **In this case, we would keep the rule and would ask authors to remove anything other than application/json from their specs.**

**Comment by ravbhatnagar** [comment]
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#client-request-headers

**Comment by veronicagg** [comment]
Closing issue, as it's been moved to new repo, see link above.
