### ISSUE TITLE
2.0 Feature Branch Created

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2385]
# Branch Created:
https://github.com/Azure/autorest/tree/2.0

AutoRest is making a a few structural changes, along with eliminating some deprecated legacy behavior.

### Notable changes in this branch:

- Bumping required node.js version to 7.10 or greater. (Will add checks in to ensure that this is the case)<br>This enables us to target the `ES2017` javascript standard, vastly simplifying compiled code and has significant performance benefits.
- Bumping Dotnet/CLI SDK and Runtime to 2.0
- Updated bootstrapper that implements use-extension
- Moving common TypeScript code into the Perks.Node project so that they can be built and reused independently of building AutoRest.
- Removing all remaining Legacy CLI features, standardizing on the --switch format for all cmdline operations

Also, creating a `2.0` Milestone that features/requests can be added to, and this post should be updated to reference any `2.0` tagged items

**Comment by dsgouda** [comment]
@fearthecowboy  I believe we have finished the tasks mentioned.
