### ISSUE TITLE
Wrong package version was displayed in output of autorest.exe

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#239]
When I run autorest, below is the output:

```Text
The Microsoft.Rest.ClientRuntime.Azure.1.0.12 nuget package is required to compile the generated code.
Finished generating Azure.CSharp code for logic.json.
```

However, the generated code will not work following that output. It should be 1.0.13.

In additionl, it would be cool if the output contains the full list of packages that is needed in order to compile the generated code, which includes some system dll and ClientRuntime 1.1.0, etc.

**Comment by markcowl** [comment]
@tonytang-microsoft-com fixed.
