### ISSUE TITLE
Need support for Title > 20 characters and an updated Error message

### ISSUE THREAD

**Issue by atpetro** [Azure/autorest#2412]
I've been getting the following error when parsing my swagger file.

> [Fatal]Error saving generated code: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

I assumed it had something to do with my long namespaced definition names which were generating long file names and directory structures as the error message indicated. I started by changing my definition names in the swagger to be much smaller and tried again and I kept getting the same error. I then tried to change the Title property in my swagger to something much smaller and to my surprise it just worked. After further testing I was able to determine that the Title must be 20 characters or less otherwise you will see this error.

It would be great to support a number of Title characters up to the combined max of 260 for the file name/structure. At a minimum, an error that indicates that Title is > 20 characters is the actual issue would be helpful for debugging.

**Comment by erendrake** [comment]
260 is a windows limitation on the overall path (e.g C:\very\long\path\with\more\than\260\chars\yourtitle) 

Try putting everything in a folder off of c:\ and see if that fixes it

**Comment by atpetro** [comment]
I understand the Windows limitation but that is not the issue here. I have put my project in the root in C:\Test and it didn't help. The issue is not the 260 characters are being hit but that the info.title value in my Swagger file is more than 20 characters. It is very easy to replicate the bug by simply having a 21 character title value. Once you have a title that big the directory structure won't matter and C:\Test\YourTitleMoreThan20Chars will throw the error.

**Comment by olydis** [comment]
doesn't look that simple to repro for me:
![image](https://user-images.githubusercontent.com/9320958/27880991-d76446d0-617b-11e7-9109-99c96757a4b0.png)

Also, there's no reason for a "The specified path, file name, or both are too long" exception to be thrown if that's not actually the case - the exception is thrown by the BCL, not us.

Please provide a reliable repro if we should investigate further.

**Comment by atpetro** [comment]
Apologies for the difficult repro. I did more testing and was able to repro in various scenarios but none of them managed to make sense because none of the resulting files were never > 260 characters. 

I started wondering if maybe code gen is using temporary storage and because of the temp directory structure and the generated folder structure maybe that's why I was seeing this error. Sure enough, that's the problem. 

I regenerated using my last 'max' size success and found the file of question and it is exactly 260 chars. 

"C:\Users\Administrator\AppData\Local\Temp\1\WebToolsAutoRest\A title with 20chars\201707051500212473\Output\A title with 20chars\Models\SourceCodeWebApiWorkflowModelsPreviewWorkflowLabelsResponseSourceCodeWebApiWorkflowModelsPreviewWorkflowLabelException.cs"

In my example, once the Title is increased by one character the temp file path increased by 2 chars because of the code gen temp directory structure uses title twice.

I think it would be great if you could output the temp file directory structure you are trying to generate files into as part of the error and maybe even the exact Model that causes the failure. These two additional pieces of information would greatly reduce the debugging steps I had to go through to figure this out.

It would also be great if the temp files were deleted after successful code gen. I would probably leave them there on failures to help debugging.

Thank you for the time looking into the issue.

**Comment by olydis** [comment]
AFAIK we do not generate any code into temp directories. The only directory touched is the output folder specified on the command line (or "<current directory>/generated" if nothing was specified).
That *might* have been different in the past, are you using AutoRest 1.1.0?

**Comment by atpetro** [comment]
I downloaded and tested via command line with AutoRest 1.1.0 and you are correct, it no longer uses the temp directory so everything should be fine via that command line.

I've been using AutoRest via the VS 2017 tooling for Add > REST Client API dialog. When that runs it says the AutoRest Core is version 0.16.0.0. I've tried updating via Package Manager but it never seems to take. Do you know how to get Visual Studio to use the latest version of AutoRest Core?

**Comment by olydis** [comment]
Oh yes, the VS integration needs to be updated (created an issue to [track it](https://github.com/Azure/autorest/issues/2419)). Unfortunately, there is currently no (sane) way to point the VS integration to a more recent version, which we will also make easier once we update the integration.

Let us know if your issue is resolved, otherwise I'll close this issue 🙂

**Comment by atpetro** [comment]
Thanks for creating the VS issue. My file path length is resolved so I'll close this issue.
