### ISSUE TITLE
Microsoft.​Azure.​Management.​Service​Bus documentation is still at 0.1.0-preview

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/autorest#2413]
Docs are not updated and use 0.1.0-preview version.

https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Azure.Management.ServiceBus

**Comment by shahabhijeet** [comment]
@SeanFeldman created an issue to be tracked in the right repo
https://github.com/Azure/azure-sdk-for-net/issues/3446

Closing this issue.

**Comment by SeanFeldman** [comment]
@shahabhijeet please note that the nuget package [Project page link](https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceBus/) is bringing to Azure/autorest. That's how I ended up opening the issue here 😃
