### ISSUE TITLE
Make collectionFormat `csv` the default collection format (instead of `none`)

### ISSUE THREAD

**Issue by RemyArmstro** [Azure/autorest#2415]
I am trying to generate an autorest client from https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility.  When I do this, I get the following error:

> FATAL: System.NotSupportedException: Collection format None is not supported.
>    at AutoRest.CSharp.ClientModelExtensions.GetSeparator(CollectionFormat format)
>    at AutoRest.CSharp.ClientModelExtensions.GetFormattedReferenceValue(Parameter parameter, String clientReference)
>    at AutoRest.CSharp.Model.MethodCs.BuildUrl(String variableName)
>    at AutoRest.CSharp.Templates.Rest.Client.MethodTemplate.<ExecuteAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AutoRest.Core.Template`1.ToString()
>    at AutoRest.CSharp.Templates.Rest.Client.MethodGroupTemplate.<ExecuteAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AutoRest.CSharp.CodeGeneratorCs.<GenerateClientSideCode>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AutoRest.CSharp.CodeGeneratorCs.<GenerateRestCode>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AutoRest.CSharp.CodeGeneratorCs.<Generate>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Generator.<ProcessInternal>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NewPlugin.<Process>d__11.MoveNext()
> FATAL: csharp/generate - FAILED
> Process() Cancelled due to exception : Plugin csharp reported failure.
> Error: Plugin csharp reported failure.
>     at C:\Users\UserName\.autorest\plugins\autorest\1.1.0\node_modules\autorest-core\lib\pipeline\pipeline.js:89:19
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\UserName\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
>     at <anonymous>

I did find one item in the swagger.json that specified a collectionFormat, but it was "pipes".  I am not sure if this is an error in the swagger document itself, or in the code generator.  I can successfully generate a client using the swagger codegen tools, but would prefer an autorest client.  When I ran with --debug, it did not narrow down where in the file the error was occurring.  Hoping someone here can help me narrow down the issue.

**Comment by olydis** [comment]
@RemyArmstro Hi, reproducing the error I noticed that AutoRest defaults to `collectionFormat: none` instead of `csv` (as per the Swagger spec) whenever no `collectionFormat` is provided for `array` parameters. This is the case for some of your parameters - so the `pipes` is actually not the problem.

I changed the title of this issue accordingly, not sure when we'll be able to fix this. Until then adding `collectionFormat: csv` would be a workaround.

**Comment by dsgouda** [comment]
@olydis looks like we are actually setting the CollectionFormat to csv for array type data [here](https://github.com/Azure/autorest/blob/4983df2cc1335554f244d9ac8cd46c980217847f/src/modeler/AutoRest.Swagger/CollectionFormatBuilder.cs#L28)
Might need some additional investigation.

**Comment by olydis** [comment]
oh interesting - at the same time, `collectionFormat` (AFAIK) only makes sense for collections anyways (maybe also for dictionaries?), and I *could* repro the above issue, so maybe the code path you found isn't executed for some reason. Yep, investigation necessary.

**Comment by dsgouda** [comment]
PR fixes the issue and I am able to generate code using the provided spec.
