### ISSUE TITLE
Failed to load default-configuration.md with special User name character

### ISSUE THREAD

**Issue by pherbel** [Azure/autorest#2416]
In My case I got this error:
```
Error: Failed to load 'file:///C:/Users/P%C3%A9terHerbel/.autorest/plugins/autorest/1.1.0/node_modules/autorest-core/resources/default-configuration.md' (NotFoundError: File does not exist at the specified endpoint)
    at Object.<anonymous> (C:\Users\PéterHerbel\.autorest\plugins\autorest\1.1.0\node_modules\autorest-core\lib\ref\uri.js:43:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\PéterHerbel\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:15:69)
    at <anonymous>
```
I assume that the problem is the path encoding because the file is exsits here:

`C:/Users/PéterHerbel/.autorest/plugins/autorest/1.1.0/node_modules/autorest-core/resources/default-configuration.md`

Could you provider a workaround to solve my problem before the fix?

**Comment by olydis** [comment]
Tracked down the issue to one of our dependencies. Filed an issue [there](https://github.com/TooTallNate/file-uri-to-path/issues/5).

**Comment by pherbel** [comment]
Thanks @olydis !

I see the dependency have been fixed. 

Any chance to release this fix with 1.1.1 ?

**Comment by olydis** [comment]
Ah thanks for opening the issue against `file-uri-to-path`, was just about to do the same 😄 
Depending on the version bump in `file-uri-to-path`, it might even be in version 1.1.0 AutoRest retroactively, otherwise, I'll update our dependency ASAP. So 1.1.1 should contain it (next AutoRest release is on July 12), but most likely it'll be in our nightlies before that.

**Comment by pherbel** [comment]
Thanks @olydis 
Please ping me if I can check the fix with nightlies build.

**Comment by olydis** [comment]
If the dependency isn't fixed tomorrow (we'll publish an AutoRest release), I'll make it depend on a fixed fork instead, so no worries.

**Comment by olydis** [comment]
fixed by https://github.com/Azure/autorest/pull/2423

**Comment by pherbel** [comment]
@olydis Thanks
It works with the nightly build.

**Comment by olydis** [comment]
@pherbel Cool, thanks for verifying! We've also just made a stable release.
