### ISSUE TITLE
How to write an AutoRest plugin [documentation]

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2418]
@veronicagg I had written a primer on how to write a new AutoRest plugin [here](https://github.com/Azure/autorest/blob/master/docs/developer/guide/writing-a-new-plugin.md), I believe this could do with some more examples and explanation. Feel free to point out what specific pieces we can improve upon.

@olydis can you improve on this, outlining the new plugin model we have implemented in AutoRest so that we can have a 101 tutorial.

@vishrutshah @sarangan12

**Comment by olydis** [comment]
👍
