### ISSUE TITLE
Autorest uses wrong name for route parameters substitution

### ISSUE THREAD

**Issue by OttoVT** [Azure/autorest#2427]
What was generated is an absurd:
![wrongreplacestring](https://user-images.githubusercontent.com/14955144/28060139-6d653a80-6637-11e7-8605-78ac2fd1eb0e.PNG)
It was generated from the next action and models:
![controlleraction](https://user-images.githubusercontent.com/14955144/28059855-943af66e-6636-11e7-8681-4408447b2a98.PNG)
![request](https://user-images.githubusercontent.com/14955144/28059862-977703a4-6636-11e7-949f-724d7a5bd29e.PNG)
![paging](https://user-images.githubusercontent.com/14955144/28059864-998bcf58-6636-11e7-941b-13cc889d1816.PNG)
var _url = new System.Uri(new System.Uri(_baseUrl + (_baseUrl.EndsWith("/") ? "" : "/")), "api/Balance/getBalance/{**address**}").ToString();
            _url = _url.Replace("{**Address**}", System.Uri.EscapeDataString(address));
Please fix it in the upcoming release.

**Comment by fearthecowboy** [comment]
O_o 

Hey @OttoVT 

AutoRest generates code from OpenAPI (aka, swagger) documents. Can you post the OpenAPI spec that you used?

**Comment by OttoVT** [comment]
Here it is.
{"swagger":"2.0","info":{"version":"v1","title":"EthereumSamurai.Api"},"basePath":"/","paths":{"/api/Balance/getBalance/{address}":{"get":{"tags":["Balance"],"operationId":"ApiBalanceGetBalanceByAddress","consumes":[],"produces":["application/json"],"parameters":[{"name":"address","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"Success","schema":{"$ref":"#/definitions/BalanceResponse"}},"400":{"description":"Client Error","schema":{"$ref":"#/definitions/ApiException"}},"500":{"description":"Server Error","schema":{"$ref":"#/definitions/ApiException"}}},"deprecated":false}},"/api/InternalMessages/{address}":{"get":{"tags":["InternalMessages"],"operationId":"ApiInternalMessagesByAddressGet","consumes":[],"produces":["application/json"],"parameters":[{"name":"Address","in":"path","required":true,"type":"string"},{"name":"StartBlock","in":"query","required":false,"type":"integer","format":"int64"},{"name":"StopBlock","in":"query","required":false,"type":"integer","format":"int64"},{"name":"Start","in":"query","required":false,"type":"integer","format":"int32"},{"name":"Count","in":"query","required":false,"type":"integer","format":"int32"}],"responses":{"200":{"description":"Success","schema":{"$ref":"#/definitions/FilteredInternalMessageResponse"}},"400":{"description":"Client Error","schema":{"$ref":"#/definitions/ApiException"}},"500":{"description":"Server Error","schema":{"$ref":"#/definitions/ApiException"}}},"deprecated":false}},"/api/System/isAlive":{"get":{"tags":["System"],"operationId":"ApiSystemIsAliveGet","consumes":[],"produces":[],"responses":{"200":{"description":"Success"}},"deprecated":false}},"/api/Transaction/{address}":{"get":{"tags":["Transaction"],"operationId":"ApiTransactionByAddressGet","consumes":[],"produces":["application/json"],"parameters":[{"name":"Address","in":"path","required":true,"type":"string"},{"name":"Start","in":"query","required":false,"type":"integer","format":"int32"},{"name":"Count","in":"query","required":false,"type":"integer","format":"int32"}],"responses":{"200":{"description":"Success","schema":{"$ref":"#/definitions/FilteredTransactionsResponse"}},"400":{"description":"Client Error","schema":{"$ref":"#/definitions/ApiException"}},"500":{"description":"Server Error","schema":{"$ref":"#/definitions/ApiException"}}},"deprecated":false}},"/api/Transaction/block/number/{blockNumber}":{"get":{"tags":["Transaction"],"operationId":"ApiTransactionBlockNumberByBlockNumberGet","consumes":[],"produces":["application/json"],"parameters":[{"name":"blockNumber","in":"path","required":true,"type":"integer","format":"int64"}],"responses":{"200":{"description":"Success","schema":{"$ref":"#/definitions/FilteredTransactionsResponse"}},"400":{"description":"Client Error","schema":{"$ref":"#/definitions/ApiException"}},"500":{"description":"Server Error","schema":{"$ref":"#/definitions/ApiException"}}},"deprecated":false}},"/api/Transaction/block/hash/{blockHash}":{"get":{"tags":["Transaction"],"operationId":"ApiTransactionBlockHashByBlockHashGet","consumes":[],"produces":["application/json"],"parameters":[{"name":"blockHash","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"Success","schema":{"$ref":"#/definitions/FilteredTransactionsResponse"}},"400":{"description":"Client Error","schema":{"$ref":"#/definitions/ApiException"}},"500":{"description":"Server Error","schema":{"$ref":"#/definitions/ApiException"}}},"deprecated":false}}},"definitions":{"BalanceResponse":{"type":"object","properties":{"amount":{"type":"string"}}},"ApiException":{"type":"object","properties":{"error":{"$ref":"#/definitions/ApiError"}}},"ApiError":{"type":"object","properties":{"code":{"format":"int32","enum":[0],"type":"integer"},"message":{"type":"string"}}},"FilteredInternalMessageResponse":{"type":"object","properties":{"messages":{"type":"array","items":{"$ref":"#/definitions/InternalMessageResponse"}}}},"InternalMessageResponse":{"type":"object","properties":{"transactionHash":{"type":"string"},"blockNumber":{"format":"int64","type":"integer"},"fromAddress":{"type":"string"},"toAddress":{"type":"string"},"depth":{"format":"int32","type":"integer"},"value":{"type":"string"},"messageIndex":{"format":"int32","type":"integer"},"type":{"type":"string"},"blockTimeStamp":{"format":"int32","type":"integer"}}},"FilteredTransactionsResponse":{"type":"object","properties":{"transactions":{"type":"array","items":{"$ref":"#/definitions/TransactionResponse"}}}},"TransactionResponse":{"type":"object","properties":{"transactionIndex":{"format":"int32","type":"integer"},"blockNumber":{"format":"int64","type":"integer"},"gas":{"type":"string"},"gasPrice":{"type":"string"},"value":{"type":"string"},"nonce":{"type":"string"},"transactionHash":{"type":"string"},"blockHash":{"type":"string"},"from":{"type":"string"},"to":{"type":"string"},"input":{"type":"string"},"blockTimestamp":{"format":"int32","type":"integer"},"contractAddress":{"type":"string"},"gasUsed":{"type":"string"},"hasError":{"type":"boolean"}}}},"securityDefinitions":{}}

**Comment by fearthecowboy** [comment]
Your OpenAPI doc is incorrectly created:

``` json
"parameters":[{"name":"Address","in":"path","required":true,"type":"string"},
```

`Address` should be lowercase (to match the path parameter in the URL:

``` json
"parameters":[{"name":"address","in":"path","required":true,"type":"string"},
```

AutoRest can't guess if you incorrectly specify path parameters for replacement.

**Comment by OttoVT** [comment]
Thank you. 
That should help.
