### ISSUE TITLE
Possible error while executing autorest against compute spec

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest#2429]
When I execute autorest against the compute spec, I get the following error:

C:\workspace\azure-sdk-for-ruby>"C:\Program Files\nodejs\node.exe" C:\workspace\autorest\src\core\AutoRest\bin\Debug\netcoreapp1.0\node_modules\autorest-core\app.js https://raw.githubusercontent.com/Azure/azure-rest-api-specs/current/specification/compute/resource-manager/readme.md --package-version=0.10.0 --namespace=Azure::ARM::Compute --package-name=azure_mgmt_compute --output-folder=C:\workspace\lib --ruby --azure-arm

Could not evaulate guard expression 'tag) == 'package-compute-2017-03' && $(python'.
Could not evaulate guard expression 'tag) == 'package-container-service-2017-01' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2016-04-preview' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2016-03' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2015-06' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2017-03' && $(python'.
Could not evaulate guard expression 'tag) == 'package-container-service-2017-01' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2016-04-preview' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2016-03' && $(python'.
Could not evaulate guard expression 'tag) == 'package-compute-2015-06' && $(python'.

**Comment by fearthecowboy** [comment]
FYI -- it's probably working, it's just spitting out errors.

It looks like there is a `console.error` call in there, but it will still return the `false` condition

It actually looks like it's just cosmetic -- the guard fails to evaluate (which defaults to meaning `false`), but this won't throw.

**Comment by fearthecowboy** [comment]
fixed
