### ISSUE TITLE
Polymorphic deserialization 'broken' with more than one level of inheritance (C#)

### ISSUE THREAD

**Issue by stefanvalianu** [Azure/autorest#2430]
The problem is basically this: given the following definitions:

```
"ResponseBase": {
      "discriminator": "_type",
      "type": "object",
      "required": [
        "_type"
      ],
      "properties": {
        "_type": {
          "type": "string"
        }
      }
    },

    "Identifiable": {
      "allOf": [
        {
          "$ref": "#/definitions/ResponseBase"
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Response": {
      "allOf": [
        {
          "$ref": "#/definitions/Identifiable"
        },
        {
          "type": "object",
          "properties": {
            "instrumentation": {
              "$ref": "#/definitions/Instrumentation"
            },
          }
        }
      ]
    },
```

There is no (apparent) way to generate code that allows the generated client to ever return the "Response" class during deserialization. The same discriminator ("_type") is used to return either the class names 'Identifiable' or 'Response', depending on what the server decides to create. In the generated client, the only PolymorphicDeserializeJsonConverter on "_type" is created just for ResponseBase, *not* for Identifiable. This means if we have another schema that declares Identifiable as the base type, but the server actually returns a Response object (with _type = Response), the json deserialization will end up defaulting to the Identifiable object.

Simply duplicating the _type property as well as the discriminator: _type into the Identifiable schema doesn't work, since apparently there is some intelligent filtering in the generator to prevent duplicate property declarations. However, this means that in the SchemaBuilder.cs, nothing will ever set the PolymorphicDiscriminator property (it needs to be the same between some seen property [not including parent properties] and a seen discriminator), which means when generating thge service client in ServiceClientTemplate.cshtml, no converters will be added for Identifiable since IsPolymorphic is false.

If there's a way to support this that I'm missing, that would be great; otherwise, would appreciate an option to use BaseIsPolymorphic instead of IsPolymorphic in the client template (although that would include all the leaf nodes of our complex, schema.org based inheritance tree, which gets wasteful at the number of schemas we have).

We solved this with the default swagger generator by using a serialization binder instead (as part of the Serialization/DeserializationSettings), so that we wouldn't have to instantiate a new converter for each of our polymorphic types (we have about ~400 schemas). If support for a binder is on your radar, that would be wonderful.

So far this is the only quirk I've encountered that I can't seem to bypass; still, autorest seems very useful for us.

**Comment by stefanvalianu** [comment]
Binders are pretty sensitive to json serialization settings, so instead I just threw together a relatively ghetto converter to achieve a similar result. Testing some of our basic use cases seems to work as intended, though I wouldn't be surprised if I run across some issues related to nested invocations of the converter. 

Allows us to replace the various instantiations of the PolymorphicDeserializeJsonConverter with one addition of this TypeAgnosticPolymorphicConverter. Compiles for .netcore 1.1 but relies on reflection for finding types that are derived from. Can optimize it to only look for objects in the Models namespace, but there aren't many classes defined by the generator. For your consideration:

```
namespace SearchApi
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    public class TypeAgnosticPolymorphicConverter : PolymorphicJsonConverter
    {
        private static HashSet<Type> childTypes;
        
        static TypeAgnosticPolymorphicConverter()
        {
            childTypes = new HashSet<Type>();

            var assemblyTypes = typeof(TypeAgnosticPolymorphicConverter).GetTypeInfo().Assembly.GetExportedTypes();

            foreach (var type in assemblyTypes)
            {
                var baseType = type.GetTypeInfo().BaseType;
                if (baseType != null)
                {
                    childTypes.Add(baseType);
                }
            }
        }

        public TypeAgnosticPolymorphicConverter(string discriminator)
        {
            if (discriminator == null)
                throw new ArgumentNullException("discriminator");

            this.Discriminator = discriminator;
        }

        /// <summary>
        /// Returns true if the object being deserialized is the base type. False otherwise.
        /// </summary>
        /// <param name="objectType">The type of the object to check.</param>
        /// <returns>True if the object being deserialized is the base type. False otherwise.</returns>
        public override bool CanConvert(Type objectType)
        {
            return childTypes?.Contains(objectType) ?? false;
        }

        /// <summary>
        /// Reads a JSON field and deserializes into an appropriate object based on discriminator
        /// field and object name. If JsonObject attribute is available, its value is used instead.
        /// </summary>
        /// <param name="reader">The JSON reader.</param>
        /// <param name="objectType">The type of the object.</param>
        /// <param name="existingValue">The existing value.</param>
        /// <param name="serializer">The JSON serializer.</param>
        /// <returns></returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null)
                return (object)null;

            var jobject = JObject.Load(reader);
            var derivedType = PolymorphicJsonConverter.GetDerivedType(objectType, (string)jobject[this.Discriminator]);

            if (derivedType != null)
                return jobject.ToObject(derivedType, serializer);

            return jobject.ToObject(objectType);
        }

        /// <summary>Throws NotSupportedException.</summary>
        /// <param name="writer">The JSON writer.</param>
        /// <param name="value">The value to serialize.</param>
        /// <param name="serializer">The JSON serializer.</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotSupportedException();
        }
    }
}
```

**Comment by olydis** [comment]
Hi @stefanvalianu, sorry for not getting back to you yet. I'll take a deep look at this as soon as I can. Your scenario (multiple levels of inheritance) should definitely be supported, I'm even surprised we don't already. We'll make it work, also thanks for you efforts to make it work! 😃

**Comment by olydis** [comment]
this was fixed by https://github.com/Azure/azure-sdk-for-net/pull/3503
