### ISSUE TITLE
ServiceClientCredential equivalent for swagger "apiKey" security mechanism?

### ISSUE THREAD

**Issue by stefanvalianu** [Azure/autorest#2431]
Is there support for swagger's concept of apiKey auth? The premise is simple; include an apiKey in a named parameter either as a header or a query parameter. Incidentally, this is our team's primary form of providing clients with auth (as opposed to oauth or basic auth).

Was extremely straight forward to include my own key-value based ServiceClientCredentials implementation as part of the SDK offering, but it's a step that should be unnecessary given that the simple key/value auth is outlined in the Swagger specification. All that's required is just an additional query parameter, or header, &x=y.

Just a small feature request to include this maybe in your Microsoft.Rest.ClientRuntime package. As this is an authorization mechanism, we prefer not to include it as an explicit parameter in the API, client users should understand the auth is semantically different than changing some request parameters.

**Comment by olydis** [comment]
This is all part of the C# client runtime, please reopen the issue against https://github.com/Azure/azure-sdk-for-net to get the right audience 🙂
