### ISSUE TITLE
Generate API version and AutoRest version in a separate file

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/autorest#2434]
Can we generate API version as part of a Static class property.
This is going to help in reflecting upon and get this information.

Also is it possible to have AutoRest version not part of every single file.
Currently whenever this version changes, it affect all the files and the PR is really large with no significant changes to SDK.
Rather have it as a static class property as well.

**Comment by olydis** [comment]
> Can we generate API version as part of a Static class property.

You can have more than one API version per client/class, so not sure how that would work - note that we already to add the api version as an instance property of the client *if* it applies to the entire client.

> Also is it possible to have AutoRest version not part of every single file.

100% agree, I'm on it.

> Rather have it as a static class property as well.

Not sure whether having it as a static class property makes more sense than generating some (say) `metadata.json` file that contains all the information. That could be done consistently across all generators, not only C#.

**Comment by shahabhijeet** [comment]
@olydis If the generated client supports more than 1 API version, have it refer from a common const/static property, rather hard coding it inside the code.
Having it referred from a const or some public static property helps in two ways:
1) Tooling can use reflection to detect supported version.
2) Very easy to find all the different API version the generated client represents.

If metadata.json will be generated as part of the code generation, all I am asking is, having it generate that is native to .NET tooling (.cs file) will be more beneficial.

Yes we can represent it in .json or .txt or .csv file, but I am still do not know if there are any hurdles not to represent API version in a .cs file?
Having API version in a separate file does not make sense, because API version is an integral part of the generated client, representing it outside the code is a way, but chances are someone can mistakenly change metadata.json and the generated code can

**Comment by shahabhijeet** [comment]
@olydis it would be great if we can have a file for e.g. SdkInfo.cs.
I thought of AssemblyInfo.cs earlier, but then what if AssemblyInfo.cs has RP specific information, I am not sure if AssemblyInfo.cs would be a better choice, than simply creating a new file with all the metadata that is needed for the SDK inside a new file called SdkInfo.cs

**Comment by olydis** [comment]
we should talk about this in person/via meeting anyways, but just out of curiosity regarding profiles: what exactly are you planning to do with this information for profiles? I totally get the point of what you propose *per se*, just wondering how it will be used, i.e. when will you reflect on it and why? After all, as soon as we have profiles, the API version of each model/operation will be part of its namespace anyways, right (at least in the David Justice version of shipping profiles in .Net)? I'm curious about your plans since maybe there's something more high level we can do in AutoRest to help generate profiles or at least put something on our long term wish list 🙂

**Comment by shahabhijeet** [comment]
@olydis this is primarly to tag nugets that are published.
So whatever we decide to do with creating APIs for others to consume profile, one way is to induce API versions in namespace (that is one way)
But this will actually help to tag nuget version.

**Comment by shahabhijeet** [comment]
@olydis can we make the name of hte class as NetSdkInfo
