### ISSUE TITLE
Unable to find a release matching 'latest'

### ISSUE THREAD

**Issue by MaxMommersteeg** [Azure/autorest#2437]
Whenever I try to run one of the following commands I get the message:
`Unable to find a release matching 'latest'`. I can't find any documentation about this issue. Installed autorest with `npm install -g autorest@latest` (version 1.1.0).

Commands tried:

```cmd
autorest --input-file=swagger.json --output-folder=RelationizeAgents --override-client-name=RelationizeApiAgent --namespace=RelationizeWeb.RelationizeApi.Agents --sync-methods=all --csharp
```

And

```cmd
autorest --reset
```

And

```cmd
autorest --latest
```

![autorest](https://user-images.githubusercontent.com/9657173/28174552-121f0220-67f2-11e7-8319-824022d46134.png)

Anyone knows what I'm doing wrong?

**Comment by fearthecowboy** [comment]
If you've done a `--reset` that will automatically grab the latest. 

But it does look like something broke with the `--latest` switch.

**Comment by Bidimus** [comment]
I'm getting the same problem.  autorest --reset gives the same response. Unable to find a release matching latest.  Also doing a autorest --list-available=10 doesn't list any releases available online.

**Comment by MaxMommersteeg** [comment]
What would be my best bet? Should I try to reinstall NodeJS along with Autorest?

**Comment by fearthecowboy** [comment]
Oh, crap. It's happening to me too now. 

WTF!?

I wonder if the github release API is broken...

**Comment by Bidimus** [comment]
Something changed.  It just now started working for me.

**Comment by MaxMommersteeg** [comment]
@Bidimus Indeed, very strange. The Github CDN was offline?

**Comment by fearthecowboy** [comment]
O_O. 

Yeah... it looks like something was awry with github.

That's ok; next month AutoRest core modules will be transitioning to NPM and we won't ever have an outage again. Ever. For Sure. I just know it.

**Comment by MaxMommersteeg** [comment]
No problem, just strange. For now it works :)
