### ISSUE TITLE
Cannot find module './schema/default_safe'

### ISSUE THREAD

**Issue by MaxMommersteeg** [Azure/autorest#2439]
Whenever I try to run one of the following commands I get the message:
`Error: Cannot find module './schema/default_safe'`. I can't find any documentation about this issue. Installed autorest with `npm install -g autorest@latest` (version 1.1.0).

Commands tried:

```cmd
autorest --input-file=swagger.json --output-folder=RelationizeAgents --override-client-name=RelationizeApiAgent --namespace=RelationizeWeb.RelationizeApi.Agents --sync-methods=all --csharp
```

And

```cmd
autorest --reset
```

And

```cmd
autorest --latest
```
Anyone knows what I'm doing wrong?

**Comment by fearthecowboy** [comment]
O_o

I don't see how that's possible to get that kind of an error. 

let's try this from scratch and see if we can figure out what's gone awry... 

Fist, let's remove the autorest extension folder (powershell, adjust if you use `cmd`)
```  powershell
rmdir -recurse -force "$env:home\.autorest\"
```

just using `--latest` should get the bits:
``` powershell
autorest  --latest
```
Output:

> AutoRest Code Generator (latest)
> (c) 2017 Microsoft Corporation. https://aka.ms/autorest
> Downloading https://github.com/Azure/autorest/releases/download/dotnet-runtime-1.0.5/dotnet-win7-x64.1.0.5.zip
>         to  C:\Users\garretts.autorest\frameworks
> Downloading https://github.com/Azure/autorest/releases/download/v1.2.1/autorest-1.2.1.zip
        to  C:\Users\garretts.autorest\plugins\autorest\1.2.1


And then try your command with `--verbose --debug` :

```source-batchfile
autorest --input-file=swagger.json --output-folder=RelationizeAgents --override-client-name=RelationizeApiAgent --namespace=RelationizeWeb.RelationizeApi.Agents --sync-methods=all --csharp --verbose --debug
```

If that's not working , can you post the outputs?

**Comment by fearthecowboy** [comment]
Hmmm I think I might know what's giving us problems.

can you try this:

In file:

`C:\Users\<USERFOLDER>\.nuget\packages\autorest\1.2.1\node_modules\autorest\installer.js`

edit line 91 , and change it to read:

```
        unpack.on('finish', () => {
            setTimeout(resolve, 500);
        });
```

save it and then run `autorest --reset`

**Comment by fearthecowboy** [comment]
I think I fixed the problem.

@MaxMommersteeg 

Can you install the latest (v1.2.2)   `npm install -g autorest` and try again?

**Comment by MaxMommersteeg** [comment]
@fearthecowboy Hi,

Sorry for not following up on this. Today it started working again. I ran the `autorest --reset` command and it worked. I think the problem was related to the issue I experienced a few days ago: https://github.com/Azure/autorest/issues/2437

I think something goes wrong with the 'Github CDN'. Happy that it works, for today.

Thanks for the help!
