### ISSUE TITLE
Error: Cannot find module 'yaml-ast-parser' only with autorest 1.2.1

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2445]
```
> autorest --version=1.2.1
AutoRest Code Generator (1.2.1)
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Error: Cannot find module 'yaml-ast-parser'
> autorest --version=1.2.0
AutoRest Code Generator (1.2.0)
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
> autorest --version=1.1.0
AutoRest Code Generator (1.1.0)
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
```

**Comment by fearthecowboy** [comment]
You're the second person to run into this. 

O_o

@olydis - any idea? Is this referenced via NPM as a package, or the repo directly?

**Comment by fearthecowboy** [comment]
Hmmm I think I might know what's giving us problems.

can you try this:

In file:

`C:\Users\<USERFOLDER>\.nuget\packages\autorest\1.2.1\node_modules\autorest\installer.js`

edit line 91 , and change it to read:

```
        unpack.on('finish', () => {
            setTimeout(resolve, 500);
        });
```

save it and then run `autorest --reset`

**Comment by jaredmoo** [comment]
Worked for me! BTW the relevant path for me was C:\Users\jaredmoo\AppData\Roaming\npm\node_modules\autorest .

C:\Program Files> autorest --version=1.2.1
AutoRest Code Generator (1.2.1)
(c) 2017 Microsoft Corporation. https://aka.ms/autorest

**Comment by fearthecowboy** [comment]
I've republished the bootstrapper 1.2.2 with an extended timeout.

(this is being replaced in the next stable build anyway)

**Comment by shingz96** [comment]
i still getting the same error on 1.2.2
![image](https://user-images.githubusercontent.com/14905938/29565804-088ff5be-877a-11e7-94ac-b97a27231bfc.png)
