### ISSUE TITLE
No null check on Credentials object in Generated CSharp code

### ISSUE THREAD

**Issue by ldemidov** [Azure/autorest#245]
With this new version (I upgraded from 0.9.6), it looks like there is no null check on the Credentials object in the generated code

```csharp
...
// Set Credentials
cancellationToken.ThrowIfCancellationRequested();
await this.Client.Credentials.ProcessHttpRequestAsync(httpRequest, cancellationToken).ConfigureAwait(false);

// Serialize Request  
...

// Send Request
```

We are generating the code with the -AddCredentials flags but not every request will have the credentials set, particularly the login request will not.  Right now I have to set it to a dummy credentials object just to work around this issue.  Also since the Credentials property of the api is settable to null, it makes no sense to assume the Credentials will never be null

**Comment by hovsepm** [comment]
@ldemidov , 
Thanks for reporting this! 
Fixed in dev branch.
