### ISSUE TITLE
VisualStudio integration

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2450]
- update AutoRest version
- work with .net core projects (see #2023)
- make it easier to update the version used by it (I guess that'll actually be implicit since it would uses the same bootstrapper? Note that this would require absolute stability of the bootstrapper or a solid versioning check, so the bootstrapper won't pick up cores that might not be compatible with it any longer)

**Comment by StevenOlson** [comment]
Is there a workaround to use this with .net core 2 projects?

**Comment by fearthecowboy** [comment]
> Is there a workaround to use this with .net core 2 projects?

What exactly are you asking for?  When used from the cmdline, the code generated works with .net core 2 just fine.

**Comment by StevenOlson** [comment]
Thanks @fearthecowboy I see I should have been more specific - I was referring to the Visual Studio integration as mentioned above in "work with .net core projects (see #2023)". 
It looks like the workaround is to use it from cmdline then thanks.
