### ISSUE TITLE
New language requests

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2452]
- Angular+Typescript (see #1013)
- browser-side JavaScript (or verify & document how it works with browserify, see #639)
- Swift (see #2255)
- Rust
- Objective-C
- R (see #2327)
- PowerShell (see #1439)
- C++ (see #980)
- PHP (see #2502)

**Comment by bkwdesign** [comment]
My .NET busisness entities feature some property decorations via the `System.ComponentModel.DataAnnotations` namespace

For example: 

    using System.ComponentModel.DataAnnotations;

    namespace MyCorp.Biz
    {
        public partial class WidgetEntity
        {       
            public long Id { get; set; }

            [Display(Name ="Widget Description")]
            public string Description { get; set; }

        }
    }

I wish the `[Display]` property decoration shown above would pass through into my AutoRest's generated C# DTOs

**Comment by bkwdesign** [comment]
This would allow my ASP.NET MVC views, which were originally wired to render those `DataAnnotations`,
 to continue to render the correct metadata

(Because my controllers and views originally pointed directly at my business layer at an earlier stage of development. The nature of EF development and Visual Studio's scaffolding makes it very simple to start my project this way, and at a later point, I divorce my MVC app from my Web API and introduce AutoRest into my scaffolded controllers)

**Comment by olydis** [comment]
@bkwdesign Why did you post this in the "new language" issue? It's by no means a new language, it's a regular feature request. Please open a new issue.

**Comment by bkwdesign** [comment]
sorry, I saw "new" and "generator requests" and thought it might be in alignment. will do

**Comment by olydis** [comment]
ah, no worries, that was meant in technical terms, we have sort of a 1:1 relationship between programming language and generator project 😉

**Comment by bootstraponline** [comment]
Kotlin support would be nice also.

**Comment by chgennar** [comment]
Is typescript supported yet?  I see that it is referenced in the autorest header ("OpenAPI (f.k.a Swagger) Specification code generator. Supports C#, Go, Java, Node.js, TypeScript, Python, Ruby and PHP.").

Also there is [this](https://github.com/Azure/autorest.typescript).

If it is supported, can we have an addition to the examples?

**Comment by fearthecowboy** [comment]
@chgnnar -- it's a work-in-progress.

I imagine you'll be able to play with it with AutoRest 2.0 in a few days.

**Comment by chgennar** [comment]
@fearthecowboy -- Any updates on the typescript capabilities?

**Comment by olydis** [comment]
@chgennar supported! @amarzavery will have further detail

**Comment by dsgouda** [comment]
@fearthecowboy unassigning myself, please reassign if needed.

**Comment by richardpineo** [comment]
+1 for R wrapper generation.

**Comment by willhuber** [comment]
@richardpineo for R wrapper generation, you may consider OpenAPI Generator (http://github.com/openapitools/openapi-generator), which comes with a R client generator under active development. Hope this helps.
