### ISSUE TITLE
Enhancement: get YAML conf from autorest CLI

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2458]
Would help me to be able to do something like:
```shell
autorest readme.md --yaml-conf
```
And get in stdout the YAML extracted from the MD.

This should respect the "--tag" ideally:
```shell
autorest readme.md --tag=2017 --yaml-conf
```

**Comment by olydis** [comment]
this would be an `output-artifact`. I propose `--output-artifact=configuration`.

**Comment by olydis** [comment]
see https://github.com/Azure/autorest/blob/2.0/Samples/3b-custom-transformations/readme.md
