### ISSUE TITLE
C# generator: generate code with C#5 syntax, not C#6

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2459]
In SQL we are internally using autorest to generate clients for REST API testing. This is a huge internal repo with complex tooling, so we are still on C#5 compiler. 

This means that we are unable to use recent builds of autorest due to C#6 syntax at https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.CSharp/Templates/Rest/Common/EnumTemplate.cshtml#L41 .

Since this is generated code, the convenient syntax of C#6 does not really give much benefit compared to the cost of requiring the new compiler. So I propose that the generator should be limited to C#5 compatible syntax.

**Comment by fearthecowboy** [comment]
I found it.  1 tiny usage!

I'll fix it for the next release.

**Comment by olydis** [comment]
fixed in 2.0 (next stable release)

**Comment by jaredmoo** [comment]
Thx!
