### ISSUE TITLE
ServiceClientCredentials.InitializeServiceClient<T> not called on client constructor

### ISSUE THREAD

**Issue by ldemidov** [Azure/autorest#246]
We have a ServiceClientCredentials implementation that logins to our service on client creation, then stores to authentication credentials for subsequent requests.  This worked fine with the old version

```csharp
public class CustomLoginCredentials : ServiceClientCredentials {
  private string AuthenticationToken { get; set; }
  public override void InitializeServiceClient<T>(ServiceClient<T> client) {
    // make login request.  save authentication token in AuthenticationToken
  }

 public override Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken) {
   // place AuthenticationToken in request header
 }
}
```

So then declaring our client
`var client = new ClientAPI(new Uri("url"), new CustomLoginCredentials());`

The InitializeMethod would get called and then all requests would be properly authenticated. 

This does work any more in the new version.  Please let me know if this is a bug (I could see into fixing it myself) or some new intended behavior.

**Comment by markcowl** [comment]
@ldemidov  Thank you for the report, we will take a look

**Comment by hovsepm** [comment]
Fixed in dev branch.
