### ISSUE TITLE
.Net Types?

### ISSUE THREAD

**Issue by malichishti** [Azure/autorest#2472]
Hi,

I want to know if there is a way to not create .Net types and map them to actual types? e.g. System.Version etc.

Ali

**Comment by fearthecowboy** [comment]
While it's possible to use `x-ms-external` to not generate a type, but it's not yet possible to redirect what type it is expecting (ie, use something other that what it would have generated) 

It is in the plans to make the next-generation generator allow you to substitute types.

**Comment by fearthecowboy** [comment]
(Closing--added to design considerations issue)
