### ISSUE TITLE
swagger-document compose - FAILED

### ISSUE THREAD

**Issue by Injac** [Azure/autorest#2473]
Followed the instructions setting up autorest using node.js. I downloaded the sample file and executed the following command-line statement:

autorest --input-file=petstore.json --csharp --output-folder=cs_pet --namespace=pts
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
FATAL: swagger-document/compose - FAILED
FATAL: Error: No 'title' in provided OpenAPI definition(s).
Process() Cancelled due to exception : No 'title' in provided OpenAPI definition(s).
Error: No 'title' in provided OpenAPI definition(s).
    at Object.<anonymous> (C:\Users\injac\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\swagger-loader.js:299:19)
    at next (native)
    at C:\Users\injac\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:17:75
    at global.__awaiter (C:\Users\injac\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:13:16)
    at Object.ComposeSwaggers (C:\Users\injac\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\swagger-loader.js:289:12)
    at C:\Users\injac\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:77:48
    at next (native)
    at fulfilled (C:\Users\injac\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at process._tickCallback (internal/process/next_tick.js:109:7)

At first I thought it may not work with the latest node.js version, but the error is there with node.js version 6.10.1 as well. I am using a test-vm running MS Sever 2016. Maybe I did something wrong. According to length of the introduction using petstore.json, I hope not :)

**Comment by Injac** [comment]
I have no specific swagger. Just followed the tutorial. The download of the sample was from the documentation. The link pointing to the JSON file, within this tutorial page is invalid:

Tutorial Page:
**https://github.com/Azure/autorest/blob/master/docs/generating-a-client.md**

Download command:
**curl -O https://raw.githubusercontent.com/Azure/autorest/master/Samples/1a-code-generation-minimal/petstore.json**

I think the problem was, that I did not even bother to open and to check the file. There is only a 404 in there :smile: 

Maybe you just change the link to the Unicode version that is there, within the folder **"1a-code-generation-minimal/pepétstöre.json**

**Comment by olydis** [comment]
ohhhhhhh darn we point to that file from the tutorial, got it... yeah, our fancy shmancy unicode test rüinéd thät. Thanks for finding that, will make sure the link/tutorial is consistent again!

**Comment by olydis** [comment]
@Injac fixed in 2.0 feature branch (master is frozen unless there are major bugs), will become master in ~2 weeks (or sooner). Thanks!
