### ISSUE TITLE
Autorest download files to incorrect location

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#2484]
Here current output
```
Downloading https://github.com/Azure/autorest/releases/download/dotnet-runtime-1.0.5/dotnet-win7-x64.1.0.5.zip
        to  C:\Users\user.autorest\frameworks
Downloading https://github.com/Azure/autorest/releases/download/v1.2.2/autorest-1.2.2.zip
        to  C:\Users\user.autorest\plugins\autorest\1.2.2

```

But actually it is downloaded to `C:\Users\user\.autorest` instead of `C:\Users\user.autorest` which is correct.

**Comment by fearthecowboy** [comment]
Yeah, there is a glitch in the part that prints to the screen -- it's being fixed in the next release.

**Comment by olydis** [comment]
Should be fixed in recently released AutoRest. Please reopen if you still encounter this issue.
