### ISSUE TITLE
Unusable in build farm / CoreXT environment

### ISSUE THREAD

**Issue by ha11awayd** [Azure/autorest#2509]
I have been trying to make autorest generation part of our automated build process.
I have been consuming AutoRest through the published Nuget package.
However, even when consuming this package, AutoRest still insists on calling out to the network and installing itself into the user's profile folder.
This behavior is incompatible with a reproducible build environment.

I would request AutoRest to publish a standalone package usable without any further installation.

**Comment by fearthecowboy** [comment]
Hey @ha11awayd,

We're working on producing something.... unfortunately, it's at least a several weeks away.

**Comment by fearthecowboy** [comment]
@ha11awayd

You can download the Windows Portable release for 2.0: 

https://github.com/Azure/autorest/releases/download/2.0.4143/autorest-windows-portable-2.0.4143.zip

It doesn't have to install anything at runtime and can be xcopy'd into place.

**Comment by olydis** [comment]
I'll close assuming that our portable version suits your needs :) please reopen if it doesn't
