### ISSUE TITLE
If the swagger definiton of an API has a queryParameter of type enum then Autorest fails to generate the correct API signature.

### ISSUE THREAD

**Issue by updixit** [Azure/autorest#2520]
If a swagger API has a query parameter of type enum, Autorest is unable to generate the correct API signature. It treats the enum to be of type 'object'.

I used Autorest 1.2.2  and petStore.json file from Samples/1a-code-generation-minimal to repro this behavior.
Repro steps using petstore.json file:
1. Define a simple enum called "TestEnum" in the definitions section.
2. Update 'addPetUsingByteArray' API to include a queryparameter of 'TestEnum' type.

API generated via Autorest had the following signature:
Task<HttpOperationResponse> AddPetUsingByteArrayWithHttpMessagesAsync(**object sampleEnum**, string body = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

Expected signature is :
Task<HttpOperationResponse> AddPetUsingByteArrayWithHttpMessagesAsync(**TestEnum sampleEnum**, string body = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

**Comment by brjohnstmsft** [comment]
We have confirmed that this is an issue for C# code generation. We haven't tried it with other languages.

**Comment by olydis** [comment]
Doing exactly what you describe can only lead to invalid Swagger:
Defining `TestEnum` in the `definitions` section means you gotta `$ref` to it from your parameter.
I'd be curious how you did that since (for a query parameter) I don't see a valid way, refer to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7
My best guess is that you added a `schema`, which is only valid on `body` parameters (and ignored on others which would lead to `object`).

This *is* a weird limitation of Swagger 2.0 but note that this doesn't mean you have to copy paste your enum definition. Simply use the `parameters` section (don't forget to set `"x-ms-parameter-location": "method"`).
I tested both inline and common parameters section and got the expected result:

```
public async Task<HttpOperationResponse> AddPetUsingByteArrayWithHttpMessagesAsync(TestEnum? test = default(TestEnum?), TestEnumX? test2 = default(TestEnumX?), string body = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by updixit** [comment]
Thanks. This works.

**Comment by updixit** [comment]
Hi @olydis,
As per your suggestion, I defined the enum in the parameters section. eg:
```
"AutocompleteModeParameter": {
	 "name": "autocompleteMode",
      "in": "query",
      "required": true,      
      "type": "string",
      "x-ms-global": true,
	  "enum": [
        "oneTerm",
        "twoTerms",
        "oneTermWithContext"
      ],
      "x-ms-enum": { 
       "name": "AutocompleteMode",
       "modelAsString": false
      },
      "x-ms-parameter-location": "method",
      "description": "The autocomplete mode."
    }
```

It is referenced in the parameter section of the a GET API as follows:
		  ```
{
            "$ref": "#/parameters/AutocompleteModeParameter"
          },
```

This works well in autorest version 1 but fails for autorest version 2, with error:

```
Error: Schema validation failed: [ { code: 'ONE_OF_MISSING',

params: [],

 message: 'Data does not match any schemas from \'oneOf\'',

path: '#/parameters/AutocompleteModeParameter',

schemaId: 'https://raw.githubusercontent.com/Azure/autorest/master/schema/swagger-extensions.json#',

 inner: 

  [ { code: 'OBJECT_MISSING_REQUIRED_PROPERTY',

  params: [ 'schema' ],

 message: 'Missing required property: schema',

 path: '#/parameters/AutocompleteModeParameter',

schemaId: undefined },

 { code: 'ONE_OF_MISSING',

 params: [],

message: 'Data does not match any schemas from \'oneOf\'',

 path: '#/parameters/AutocompleteModeParameter',

schemaId: undefined,

  inner: 

 [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',

 params: [ [ 'x-ms-global' ] ],

  message: 'Additional properties not allowed: x-ms-global',
   path: '#/',
   schemaId: undefined },
 { code: 'OBJECT_ADDITIONAL_PROPERTIES',
  params: [ [ 'x-ms-global' ] ],
 message: 'Additional properties not allowed: x-ms-global',
 path: '#/',
   schemaId: undefined },
 { code: 'OBJECT_ADDITIONAL_PROPERTIES',

  params: [ [ 'x-ms-global' ] ],

 message: 'Additional properties not allowed: x-ms-global',

  path: '#/',

  schemaId: undefined },

 { code: 'OBJECT_ADDITIONAL_PROPERTIES',

 params: [ [ 'x-ms-global' ] ],

message: 'Additional properties not allowed: x-ms-global',

path: '#/',

   schemaId: undefined } ] } ] } ]


```

I'd appreciate your help here.

**Comment by olydis** [comment]
As mentioned via IM, for the record: `x-ms-global` is unexpected. What is its purpose?

**Comment by updixit** [comment]
Thanks, removing x-ms-global resolved all errors related to schema validation.
