### ISSUE TITLE
[Java.Fluent] InnerSupportsListing no longer work as expected

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest#2525]
Both `Resources_List` and `Resource_ListAll` are used to represent an operation for listing resources by subscription. The fluent generator should look for both of these names when deciding whether collection interfaces implementing InnerSupportsListing.

**Comment by RikkiGibson** [comment]
df69d7d addresses the issue

**Comment by RikkiGibson** [comment]
ApplicationGateways failing to generate with InnerSupportsListing conformance; will have to investigate.
