### ISSUE TITLE
Broken documentation with UTF8 test

### ISSUE THREAD

**Issue by praeclarum** [Azure/autorest#2533]
This commit: https://github.com/Azure/autorest/pull/2423

changed the name of the first example.

I was trying to learn auto rest but kept failing to download the example from: https://github.com/Azure/autorest/blob/master/docs/generating-a-client.md

That is,

```
curl -O https://raw.githubusercontent.com/Azure/autorest/master/Samples/1a-code-generation-minimal/petstore.json
```

fails.

**Comment by olydis** [comment]
Thanks @praeclarum, we actually noticed and fixed [this](https://github.com/Azure/autorest/blob/2.0/docs/generating-a-client.md) in our `2.0` branch which is about to be merged into master soon (once stable). Will leave this issue open until then!
