### ISSUE TITLE
[.NET] Parser Package

### ISSUE THREAD

**Issue by cecilphillip** [Azure/autorest#2534]
It would be nice if AutoRest.Swagger could be it's own NuGet package. I don't think there's an independent parser package for .NET Today.

**Comment by fearthecowboy** [comment]
We're undergoing some code reorganization and splitting stuff up right this moment.

within a day or two, there should be an `autorest.common` package that should have the code that you are looking for.

**Comment by cecilphillip** [comment]
@fearthecowboy great. Mind if I leave this issue open until then?

**Comment by olydis** [comment]
@cecilphillip https://www.nuget.org/packages/autorest.common/ is out now 🙂

**Comment by olydis** [comment]
I'll close this issue since such a package now exists. Feel free to post further questions or reopen the issue! :)

**Comment by cecilphillip** [comment]
@olydis Thanks! I'll check this out
