### ISSUE TITLE
Provide support in all the generators for x-ms-pageable and x-ms-long-running-operation extension to be applied together

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#2538]
Based on this change https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json#L346-L352, NetworkInterfaces_ListEffectiveNetworkSecurityGroups a POST operation is both long running and pageable.
We would like to know following things from ARM perspective (Azure RPC guidelines):
-	Is this allowed?
-	If yes, then what would be the status of the request to get the next page based on the url in the next link? Will that be long running too always? Or it may or may not be long running?
-	We have seen the service directly returning a 200 response with body and location header. Should the client discard the response body and simply follow the location header?

@ravbhatnagar - Please update the [LRO spec](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#202-accepted-and-location-headers) for this scenario.

**Comment by sergey-shandar** [comment]
Related PR: https://github.com/Azure/azure-rest-api-specs/pull/1547

**Comment by fearthecowboy** [comment]
My preference would be to re-think this from top-to-bottom and then implement a better pattern in the next generation of generators.

@olydis  and I put this on our 2.0+ feature list. 

really, depends on how bad this is needed...

**Comment by fearthecowboy** [comment]
New ModelerFour takes this into account.
