### ISSUE TITLE
deserialized object does not contain properties or values.

### ISSUE THREAD

**Issue by flauckner** [Azure/autorest#2543]
I used Autorest (2.2.1) to generate a Node.JS client layer.  When I execute a simple API call, a valid json object is returned.

When the deserialze function is called (client.deserialize), the result object does not contain the properties and valid.  The deserialize calls the deserializeCompositeType function which never seems to read the values of the property.

I have attached the object definition and operator classes.

Here is the json returned from the API Server.

[SampleFiles.zip](https://github.com/Azure/autorest/files/1235193/SampleFiles.zip)
[{"CompanyKeywordID":5,"CompanyKeyword":"ASSOC","CompanyKeywordDesc":"Association","ActiveYN":"Y","ModifiedDT":"2016-06-24T10:19:09.820","ModifiedByID":1,"CreatedDT":"2016-06-24T10:19:09.820","CreatedByID":1}]

Thank you for your feed back.

[SampleFiles.zip](https://github.com/Azure/autorest/files/1235186/SampleFiles.zip)

**Comment by olydis** [comment]
Note that the most recent version is 1.2.2, can you confirm?

**Comment by flauckner** [comment]
I have installed the latest version but I still get the same behavior.
With a little more research, it appears that the issue is in deserializeCompositeType in searialziatoin.js.
in the loop around line 462.   for (let key in modelProps) {
The code is looking in responseBody for a key value equal to the the current field.   
ie,      eval(jpath.join ('')):)  
where jpath.join('') has a value of   responseBody["CompanyKeyword"].

When the responseBody is actually a list, so should be evaluating  responseBody[0].CompanyKeyword.


I hope is helps.



Fred Lauckner(713) 471-5873FredLauckner@Yahoo.com


On Friday, August 18, 2017, 3:01:09 PM CDT, Johannes Bader <notifications@github.com> wrote:


Note that the most recent version is 1.2.2, can you confirm?

**Comment by amarzavery** [comment]
Same issue was filed in azure-sdk-for-node and has been resolved. https://github.com/Azure/azure-sdk-for-node/issues/2250
