### ISSUE TITLE
Unable to resolve package @microsoft.azure/autorest-classic-generators

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest#2544]
I think a change happened in the 2.0 branch fewer than 10 days ago causing this error when I run AutoRest on macOS Sierra. I've done a simple `npm i; gulp build` beforehand.

```
$ node src/autorest-core/dist/app.js \
    ~/src/azure-rest-api-specs/specification/eventhub/resource-manager/readme.md \
    --java  --azure-arm --fluent --namespace=com.microsoft.azure.management.eventhub \
    --output-folder=/Users/rigibson/src/azure-sdk-for-java-pr/azure-mgmt-eventhub \
    --license-header=MICROSOFT_MIT_NO_CODEGEN  --payload-flattening-threshold=1 \
    --tag=package-2017-04

{ Error: Unable to resolve package '@microsoft.azure/autorest-classic-generators@>=2.0.0'.
    at fetch (/Users/rigibson/src/autorest/src/autorest-core/node_modules/@microsoft.azure/extension/dist/main.js:230:26)
    at /Users/rigibson/src/autorest/src/autorest-core/node_modules/npm/node_modules/call-limit/call-limit.js:22:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) exitCode: 1 }
```

Maybe some weird transitive dependency issue? `autorest-classic-generators` doesn't seem to be a package on npm.

**Comment by RikkiGibson** [comment]
FYI, I get the same error when running on my Windows 10 PC on `Azure:2.0`. @olydis any clue what could be causing this?

**Comment by RikkiGibson** [comment]
10a36b9 is the latest commit where I can generate successfully. Issue seems to start in 187e06e.

**Comment by olydis** [comment]
Sorry about that, it's a symptom of the ongoing process to split AutoRest across repos. Workaround: Add `--use=<path to AutoRest repo>/src/core/AutoRest` (absolute path).

**Comment by RikkiGibson** [comment]
Thanks, now I'm able to build from the latest off of 2.0 branch.
