### ISSUE TITLE
[Go] Documentation for readonly properties and don't send them over the wire

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#2545]
Thinking about this issue again https://github.com/Azure/go-autorest/issues/112 . Now we don't check for nil readonly properties, but a little documentation for them wouldn't hurt. It would be cool to add a comment after their JSON tag on the models file, `// read only`.

**Comment by jhendrixMSFT** [comment]
Upcoming RPaS will likely require that R/O properties are not sent across the wire.  We should update codegen to include a comment and in the preparer nil out all R/O props.

**Comment by jhendrixMSFT** [comment]
Fixed in 2.1.129.
