### ISSUE TITLE
Why are Client Model Class Property names created with the first character lower case?

### ISSUE THREAD

**Issue by flauckner** [Azure/autorest#2546]
I have a question (or another question).  I have a class where all of the property names have the first character capitalized.  The Swagger definition has the property names correct (as coded in the API layer).

When autorest (1.2.2) creates the node.js classes, the first character is lower case and the serializedName value is correct.

When the json is deserialized from API call, the resulting object (list of objects) has the property names with the first character lower case.

Is this a Node.js convention?
Is there a configuration setting to change this behavior?
Do I just need to get over it and continue working?

[PropertyNameLowerCase.zip](https://github.com/Azure/autorest/files/1240161/PropertyNameLowerCase.zip)

Thank you

**Comment by amarzavery** [comment]
@flauckner - As per javascript convention all the method names and property names of a class are in camelCase. The name of the class is PascalCase. All the file names are in camelCase as well. This has no effect on the model represented in swagger spec. The generated client will serialize as per the casing in swagger spec and will deserialize back in javascript model as per the convention.

**Comment by abhishekgoenka** [comment]
We are facing the same problem. Our REST api are used by multiple applications. We can't afford to change property names to lowercase. Is there any switch I can use to avoid conversion.

**Comment by abhishekgoenka** [comment]
Reference : https://github.com/swagger-api/swagger-codegen/pull/1965

**Comment by amarzavery** [comment]
When you are using a TypeScript or node.js client, then we follow javascript conventions. However, the casing of the (serialized) property sent on the wire is not changed. It remains the same as mentioned in the swagger spec.
