### ISSUE TITLE
Remove markdown file generation from --azureresourceschema

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2556]
When generating `--azureresourceschema`, autorest produces some very pretty markdown files containing human-readable info about the schema. Unfortunately, schema publishing breaks when it sees these files. See https://github.com/Azure/azure-resource-manager-schemas/issues/338  . Please remove generating of markdown from azure resource schema.

**Comment by fearthecowboy** [comment]
I'm looking to see if we can split these behaviors -- I'm not entirely sure why they were created as a single extension.

**Comment by fearthecowboy** [comment]
I think this is done
