### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by talbenari1** [Azure/autorest#2567]
This link appears in the README: [Validation Rules & Linting](https://github.com/Azure/autorest/blob/master/docs/developer/validation-rules/readme.md).

It was broken by #2406 and hasn't been fixed 😢

**Comment by olydis** [comment]
It hereby shall be fixed! Note though that what it points to seems deprecated, I opened an issue against that repo. Let me know if we can help you with validation (or anything AutoRest related) in any way!

Thanks for reporting 🙂
