### ISSUE TITLE
Licence VS license

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2575]
I get this typo a lot (like it's been three service teams....). But it's not really a typo, both are grammatically correct. 

Can we be smart and accept "--licence-header" as an alias to "--license-header"? Problem is that Autorest does not complain on "--licence-header", and license header does not block compilation. Or can be fail for this specific one if the alias is not acceptable?

This is really annoying, and waste of time , since a LOT of people are doing the mistake...
Last one for example:
https://github.com/Azure/azure-sdk-for-python-pr/pull/70#discussion_r137349685

**Comment by fearthecowboy** [comment]
Yeah, we can add in an alias for that.

**Comment by olydis** [comment]
fixed by #2582
