### ISSUE TITLE
AutoREST plugin is a little too intrusive

### ISSUE THREAD

**Issue by darrelmiller** [Azure/autorest#2585]
It would be good if it could be a bit more selective as to when to enable itself.  I edit lots of Markdown files and JSON files that are not OpenAPI and cannot be processed by AutoREST, but it still likes to try provide commentary on unrelated things.

**Comment by fearthecowboy** [comment]
Yeah; I've been rushing to get AutoRest 2.0 out the door; I need fixes in there to fix up some bugs in the VSCode extension.

Should be done with 2.0 this week.

**Comment by olydis** [comment]
I think the VSCode extension folks are releasing soon, the fix will be in there 🙂
