### ISSUE TITLE
[Proposal] Support custom spacing in Autorest JSON output

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2587]
Currently JSON output in Autorest is [2-space indented](https://github.com/Azure/autorest/blob/master/src/autorest-core/lib/configuration.ts#L439). Though that looks good on console or file, it is a bit difficult to parse in a program which is making use of this output. 
Parsing the output is a mess, even though each individual message is JSON but entire output as a whole is not a valid JSON and parsing it without writing bunch on hacks and complex regex in code is not possible.

**How custom spacing will solve it?** 
With custom spacing, I can get single line output of each message and then I can use any [ndjson ](http://ndjson.org/) library or even vanilla Newtonsoft to deserialize each line into valid object.

**Comment by fearthecowboy** [comment]
Um. What are you looking to with the parsed output?

Perhaps there is a better way rather than trying to parse the message outputs from AutoRest. We do have a library that lets you use it programatically.

**Comment by DheerendraRathor** [comment]
I was trying to have an incremental swagger errors and warnings detection for our services with daily build. 

Are there C# or Python libraries to help with it?

**Comment by fearthecowboy** [comment]
We have a nodejs library; I'm just updating it for the imminent AutoRest 2.0 release right this moment.

**Comment by DheerendraRathor** [comment]
Argh, JavaScript! Not a fan of that language in particular. 
Can you point me to library if available publicly?

**Comment by amarzavery** [comment]
Not sure how this will help. However, letting you know - [`JSON.stringify(object, null, <spacing 2,4, 0, etc.>)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) takes in an option for custom spacing.

**Comment by olydis** [comment]
@DheerendraRathor the library is available publicly - in fact it's `autorest` as you have it installed on your machine. I.e. take dependency on the `autorest` package from a NodeJS project and you'll be able use AutoRest as a library. There, you can subscribe to messages, so you will be called per message, no parsing required.
