### ISSUE TITLE
-outputFileName has been removed in latest versions

### ISSUE THREAD

**Issue by anobleperson** [Azure/autorest#260]
"-outputFileName" was a parameter that allowed all the entries for a swagger file to be put into a single file. We automate the generation of the swagger json and generation of the code from it. The single file option was optimal for automation for the following reasons:
  a) When new model elements or methods were generated, the files remained the same, so a new build would include them with no extra work
  b) If new files need to be added, they need to be added to both the Visual Studio project AND source control which is hard/impossible to automate and error prone to do manually

It would be good if this property can be re-enabled.

**Comment by hovsepm** [comment]
Fixed in dev branch.
