### ISSUE TITLE
Provide consistent behavior for 429 status code in all language SDKs

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#2601]
Based on customer feedback, here is the intended behavior that needs to be consistent across all language SDKs

If service sends 429 back, then we must look for `retry-after` header. If `retry-after` header is not available, then by default retry after 20 seconds. If `retry-after` header is available, then we must wait until the time provided by the service before retrying again. Make this a pluggable component so that if customers intend to add their own behavior for 429, they can.

**Comment by lmazuel** [comment]
Python https://github.com/Azure/msrestazure-for-python/issues/47

**Comment by mcardosos** [comment]
Go fixed this here
https://github.com/Azure/go-autorest/pull/155

**Comment by RikkiGibson** [comment]
Java does it like this:
https://github.com/Azure/azure-libraries-for-java/blob/e9f3a59dd1814554a92ce1931914100f993c0ff8/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java

Not certain this is the ideal approach, but it's something. Node and TypeScript SDKs probably need to handle this too.
