### ISSUE TITLE
autorest Error: Cannot find module 'yaml-ast-parser'

### ISSUE THREAD

**Issue by vikram-m** [Azure/autorest#2610]
I installed the latest from the repo ( autorest@1.2.2) and when I ran 

**autorest [path] --azure-validator=true --message-format=json** 

following error is coming:

AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
**Error: Cannot find module 'yaml-ast-parser'**

@fearcowboy - You addressed similar issue in v1.2.1.  Am I missing anything?

**Comment by fearthecowboy** [comment]
I think something corrupted the install 
try

`autorest --reset `

**Comment by fearthecowboy** [comment]
or better yet, try the 2.0 build

`npm install -g autorest@preview`

**Comment by joshuatee** [comment]
same here

`
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\xxx> npm uninstal -g autorest
removed 211 packages in 4.758s
PS C:\Users\xxx> npm install -g autorest
C:\Users\xxx\AppData\Roaming\npm\autorest -> C:\Users\xxx\AppData\Roaming\npm\node_modules\autorest\app.js

> jsonpath@0.2.12 postinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\autorest\node_modules\jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

+ autorest@1.2.2
added 211 packages in 27.985s
PS C:\Users\xxx> iwr https://raw.githubusercontent.com/Azure/autorest/master/Samples/1b-code-generation-multilang/pet
store.yaml -o petstore.yaml
PS C:\Users\xxx> autorest --input-file=petstore.yaml --csharp --output-folder=CSharp_PetStore --namespace=PetStore
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Error: Cannot find module 'yaml-ast-parser'
PS C:\Users\xxx> node -v
v8.5.0
`
Also the colour of the PoSH prompt gets changed to yellow

**Comment by fearthecowboy** [comment]
@joshuatee use `--reset ` to reset the extensions.

or switch to the 2.0 branch.

`npm install -g autorest@preview`

**Comment by vikram-m** [comment]
_npm install -g autorest@preview_ - working for me.

**Comment by vikram-m** [comment]
closing the issue, as it is fixed with latest install.
