### ISSUE TITLE
Autorest does not work after installing latest via npm install

### ISSUE THREAD

**Issue by hitenjava** [Azure/autorest#2616]
After installing autorest via npm install -g autorest, I get the below error.
The version that gets installed is 2.0.4143, but there is no tag corresponding to it in the repository.

c:\>autorest --version
C:\Users\__\AppData\Roaming\npm\node_modules\autorest\dist\app.js:88
const checkBootstrapper = new polyfill_1.LazyPromise(async () => {
                                                           ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (C:\Users\hijava\AppData\Roaming\npm\node_modules\autorest\dist\fs-monkey\patchRequire.js:136:16)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hijava\AppData\Roaming\npm\node_modules\autorest\dist\static-app.js:6:1)

**Comment by fearthecowboy** [comment]
Upgrade to node 7.10 or greater

...

________________________________

**Comment by furier** [comment]
The strange thing is that when I try to reinstall older versions after the upgrade I get the same errors.

`npm i -g autorest@2.0.9` yields the same error... :(

**Comment by furier** [comment]
@fearthecowboy in other words the node.js LTS version is not supported? at version `6.11.3`.

**Comment by hitenjava** [comment]
Worked for me after upgrading node.js.

**Comment by idg10** [comment]
Shouldn't `package.json` be updated to reflect this? Currently it has:

`  "engines": {
    "node": ">=6.9.5"
  },`

That implies it's fine with v6.9.5, but clearly it no longer is.

**Comment by fearthecowboy** [comment]
It already is:

See
https://github.com/Azure/autorest/blob/master/src/autorest/package.json#L5

**Comment by fearthecowboy** [comment]
That's the one for the project (doesn't get published), but I'll fix it too.

**Comment by idg10** [comment]
Ah, sorry, was looking at wrong `package.json`.

I was thrown by the fact that a build agent that I'm using happily attempted to use this version of AutoRest without noticing that it needs a newer engine version than was actually available. I hadn't realised node would totally ignore the engine version requirement and just attempt to run things anyway.

**Comment by fearthecowboy** [comment]
I was under the impression that `npm` would block on engine requirement too. 

I've added an explicit preinstall version check into the package, it's going thru CI right now.
