### ISSUE TITLE
autorest @latest install : throwing R2066/SDKViolation warnings for post requests

### ISSUE THREAD

**Issue by vikram-m** [Azure/autorest#2617]
Currently, for a post request path in spec, autorest is throwing warning : 

_WARNING: Could not find the exact path ["paths","/subscriptions/{subscriptionId}/providers/Microsoft.AlertManagement/alerts/resolve","post","Alerts_Resolve"] for "OperationId should contain the verb: '/subscriptions/{subscriptionid}/providers/microsoft.alertmanagement/alerts/resolve' in:'Alerts_Resolve'. **Consider updating the operationId**"_

_WARNING (**PostOperationIdContainsUrlVerb/R2066/SDKViolation**): OperationId should contain the verb: '/subscriptions/{subscriptionid}/providers/microsoft.alertmanagement/alerts/resolve' in:'Alerts_Resolve'. Consider updating the operationId - file:///C:/repos/github-repos/azure-rest-api-specs-pr/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/2017-10-10-privatepreview/AlertsManagement.json:142:6 ($.paths["/subscriptions/{subscriptionId}/providers/Microsoft.AlertManagement/alerts/resolve"].post)_

Considering it might be problem in my spec, then checked with other specs in repo and it is throwing the same error whenever it see a post call:

_autorest -CodeGenerator None -Input C:\repos\github-repos\azure-rest-api-specs-pr\specification\advisor\resource-manager\Microsoft.Advisor\2017-04-19\advisor.json_

And error code **R2066** doesn't exist in the [automated rules](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md)

**Comment by dsgouda** [comment]
@vikram-m the updated documentation can be found in the `current` branch (here)[https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-automated-guidelines.md]

**Comment by dsgouda** [comment]
Validation related issues can be reported [here](https://github.com/Azure/azure-openapi-validator/issues)

**Comment by vikram-m** [comment]
@dsgouda - closing this issue as it is being tracked in azure-openapi-validator.
