### ISSUE TITLE
HttpResponseMessage return type generates invalid code.

### ISSUE THREAD

**Issue by MrBirdman** [Azure/autorest#2623]
Hi,

We're returning a HttpResponseMessage object from our WebApi:

```
        [HttpPost]
        public HttpResponseMessage SaveOrderNote(int orderId, int operatorId, string note)
        {
            //some code here

            var result = IsNoteOk(orderId, note)
            if (result)
            {
                return new HttpResponseMessage(HttpStatusCode.OK);
            }
            var result = _ordersService.SaveOrderNote(orderId, operatorId, note);
            if (result)
            {
                return new HttpResponseMessage(HttpStatusCode.OK);
            }

            return new HttpResponseMessage(HttpStatusCode.InternalServerError);
        }

```
The code generated with AutoRest return an error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0104	'HttpResponseMessage' is an ambiguous reference between 'OurApi.WebAPI.Client.Models.HttpResponseMessage' and 'System.Net.Http.HttpResponseMessage'	OurApi.WebAPI.Client	

The problem is with AutoRest generating a HttpResponseMessage object in the Models directory.
Autorest Version:

Type       Extension Name                     Version
 core       @microsoft.azure/autorest-core     2.0.4147
 extension  @microsoft.azure/autorest.csharp   2.0.21
 extension  @microsoft.azure/autorest.modeler  2.0.18

**Comment by fearthecowboy** [comment]
If you've put a model type in your swagger that is called `HttpResponseMessage` , it probably doesn't like that.

Post your swagger, I suspect you have improperly modeled the API. You should not have wire types that are `HttpResponseMessage`

**Comment by MiYanni** [comment]
Swagger modelling issue. Closing.
