### ISSUE TITLE
Sample client code generation from x-ms-examples

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2635]
C# has a prototype for that: https://github.com/Azure/autorest.csharp/blob/master/src/vanilla/CodeGeneratorCs.cs#L250

All you need to do in your generators is override this method, a `virtual` function doing nothing already exists (in `autorest.common`).
Also the code path to call that function is already there, together with an example that tests for it: https://github.com/Azure/autorest/blob/master/Samples/3f-example-generation
As you can see, this example already calls out to all generators, but you'll only find generated code in C# so far. As you implement the function, you should automatically see your generated code show up in [the example](https://github.com/Azure/autorest/blob/master/Samples/3f-example-generation) (when doing a `gulp regenerate`) 🙂

**Comment by lmazuel** [comment]
Started to work on a branch:
https://github.com/Azure/autorest.python/tree/generatesample

Super basic replace from C# gives something pretty good actually:
```python
parameters = StorageAccountUpdateParameters(
    network_rule_set = NetworkRuleSet(
        default_action = "Allow"
    )
)

storageAccount = client.storage_accounts.update(
    resource_group_name = "res9407",
    account_name = "sto8596",
    parameters = parameters,
    api_version = "2017-06-01")
```

I need to trim read-only parameters, constant parameters and api_version, otherwise that is really close.

Note for myself:
```shell
autorest ..\azure-rest-api-specs\specification\storage\resource-manager\readme.md --use=C:\Users\lmazuel\Git\autorest.python --python --azure-arm=true --sample-generation=true --output-folder=C:\Users\lmazuel\Git\autorest.python\TESTS
```

FYI @johanste

**Comment by amarzavery** [comment]
FYI - @sarangan12 @mcardosos @anuchandy - There is no deadline for this. However, please add this to your sdk backlog and make sure this gets completed in a reasonable time.
