### ISSUE TITLE
Autorest not returning success error code, batch files do not continue

### ISSUE THREAD

**Issue by ObadahFahmy** [Azure/autorest#2638]
I have the following batch file:

```
pushd %~dp0
autorest --input-file=x.json --csharp --output-folder=x --namespace=x --debug
PAUSE
//do some stuff
```

When I run the batch file, the autorest command runs, files are generated, but the batch stops running after the rest command. The PAUSE command is not hit and the window closes. If I change the autorest command to the following, it will pause after generation: 
`call autorest --input-file=x.json --csharp --output-folder=x --namespace=x --debug`

The logs do not show any issues, and the last message is DEBUG: csharp/emitter - END. I cannot see why the batch file is not continuing execution except if the autorest command is not returning a success code and that is causing the batch file to stop running.

Just to clarify I do intend to get rid of the PAUSE statement, and the purpose of it at the moment is to just verify that autorest completed successfully.

**Comment by fearthecowboy** [comment]
nodejs uses .cmd files on windows when it installs them

So, yeah, you need to use call. Nothing I can do about that at the moment.
