### ISSUE TITLE
error response codes in swagger json are being treated as non-errors in C# code

### ISSUE THREAD

**Issue by anobleperson** [Azure/autorest#265]
If error responses are given in the swagger json, they are not being treated as errors in the C# generated code.

Given the following JSON:
````
				"responses" : {
					"201" : {
						"description" : "Created",
						"schema" : {
							"$ref" : "#/definitions/MyItem"
						}
					},
					"404" : {
						"description" : "If the Actor is not found"
					},
					"409" : {
						"description" : "Conflict - Just because"
					}
				},
````
It will produce the following C# code:
````
            if (!(statusCode == (HttpStatusCode)Enum.Parse(typeof(HttpStatusCode), "Created") || statusCode == (HttpStatusCode)Enum.Parse(typeof(HttpStatusCode), "NotFound") || statusCode == (HttpStatusCode)Enum.Parse(typeof(HttpStatusCode), "Conflict")))
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", statusCode));
````

When we really only want the Created message to be ignored from raising an exception, and everything else should still raise an exception.  One solution of course is to not put the failure response codes in the response part of the json, however then it doesn't appear anywhere in the swaggerUI and so other developers can't see what the expected responses are.

**Comment by devigned** [comment]
I could get behind throwing on 409, but I think throwing on a 404 is much more controversial. In fact, in cases of GET or DELETE, most of the time, I don't really care about the 404.

The other side of this, is we expect to throw when we don't understand the response (i.e. it was not modeled). The responses that are modeled, we expect the user to handle appropriately in their code. This intended to avoid users from using exceptions as flow control.

**Comment by anobleperson** [comment]
Interesting points you raise. On the second point, in order to handle them correctly by not using the verbs that come back, we'd need to introduce a response dto which wrapped the actual response. Or always use the results that use the full result that returns a Task<HttpOperationResponse<>>, which makes the extension classes much less useful. The extension classes encourage users to use them because they're simpler, but they can't be used in the majority of cases.

On the first point, if you do a get and receive a 404, you either have to check for null, or catch an exception. Both are flow control, it's just a matter of degrees, if you have to catch HttpOperationException anyway, it's more maintainable to use the same flow control.  I know the flame wars on exception as flow control, let's park that :).

**Comment by devigned** [comment]
What happens if you model 200, 204 and 202 for a Put to Pet? Should we throw on anything other than 200? On 204 should you just get null back or throw?

**Comment by anobleperson** [comment]
I take your point.  Whilst it would be easy to invent some rules here about successful messages versus error messages, it would be too easy for those rules to be against someone else's expectations. We just shouldn't use the extension methods because there isn't enough control over the response.

I'm happy to close this issue. Thanks for the discussion.

**Comment by devigned** [comment]
Thank you for raising the issue. You bring up valid points about some things that keep me up at night. I'm very happy to continue this conversation as it can only help to find a better solution to this ambiguous situation.

**Comment by anobleperson** [comment]
Okay, happy to continue to discuss. Tomorrow I'll put some code examples up to illustrate the differences and a proposal on handling and we can muse over it some more.

Cheers,
Ash.

**Comment by anobleperson** [comment]
A proposal is that success codes are not treated as failures, whether they are modeled or not, and any error codes are exceptions whether they are modeled or not. Here are a couple of examples of code using the extension methods vs the base methods for further discussion:

**Async Extensions**
```csharp
try
{
	var item = await myApi.PutSomething(param1, param2);
	if (item == null)
	{
		// No Content
	}
	else
	{
		// Do something with my item
	}
}
catch (HttpOperationException e)
{
	if (e.Response.StatusCode == HttpStatusCode.BadRequest)
	{
	}
	if (e.Response.StatusCode == HttpStatusCode.Conflict)
	{
	}
}
```

**Base methods with OperationResponse**
```csharp
try
{
	var response = await myApi.PutSomething(param1, param2);
	if (response.Response.IsSuccessStatusCode)
	{
		if (response.Response.StatusCode == HttpStatusCode.NoContent)
		{
			// Do something
		}
		else
		{
			var item = response.Body;
			// Do something with my item
		}
	}
	else
	{
		if (response.Response.StatusCode == HttpStatusCode.BadRequest)
		{
		}
		if (response.Response.StatusCode == HttpStatusCode.Conflict)
		{
		}
	}
}
catch (HttpOperationException e)
{
	// Really unexpected
}
```

Personally I find the first style easier to read, but it's likely there are use cases that I haven't come across where this doesn't work.
