### ISSUE TITLE
Java missing imports and possibly mistaken `@override`

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2665]
Over [here](https://github.com/Azure/autorest/issues/2652#issuecomment-337180885) it seems we identified an issue orthogonal to the main issue of that thread, the only "important" part is:
> ![image](https://user-images.githubusercontent.com/9320958/31681656-c4a4f762-b32c-11e7-8b09-53bfdb7da90e.png)

Relevant links for your convenience:
- Swagger: https://github.com/Picturepark/Picturepark.SDK.Playground/blob/master/swagger/PictureparkSwaggerAutoRest.json
- Generated file that had to be *manually edited*: https://github.com/Picturepark/Picturepark.SDK.Playground/blob/master/src/Picturepark.SDK.Java/src/main/java/picturepark/implementation/TransferClientsImpl.java

**Comment by RikkiGibson** [comment]
It looks like there were problems with `@Override` on methods implementing an interface method. Certain Java project settings can make this fail to compile. This may help:
https://stackoverflow.com/questions/10947584/error-on-override-annotation-with-interface-implementation

 @RSuter can you verify whether in general you are able to add `@Override` to a method that implements an interface method in your project?

The imports issue looks like we're failing to conditionally add the extra imports when a file upload method is present in the method group.
