### ISSUE TITLE
Add support for APIKey credentials in the generic runtime and CognitiveServices credentials in the azure runtime for every language

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#2672]
Posting this on behalf of @lmazuel who came up with the original proposal. 

-	We need a solution that does not postpone Cognitive Services releases by X months
-	Support ApiKey

Ideally we can have something that:
-	Work right now for CS
-	Will be compatible with the future implementation of ApiKey in Autorest

Reminder of what Swagger ApiKey is:
-	It’s a way to describe in Swagger that in order to call this API, all calls must have the headers XXXX and/or query parameters YYY.
-	This can be global (like subscription id for ARM) or local (for a particular method)

What I  did in Python:
-	Add a ApiKeyCredentials class, that take a dictionary of headers and/or a dictionary of query parameters. This is generic and is in msrest.
-	I added a CognitiveServicesCredentials class that inherits from ApiKeyCredentials and fit the particular “Ocp-Apim-Subscription-Key”.

The point is that this last class can totally be generated in the future. Let’s say this Swagger:

```yaml
securityDefinitions:
   # X-API-Key: abcdef12345
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
   # /path?api_key=abcdef12345
   APIKeyQueryParam:
     type: apiKey
     in: query
     name: api_key
```
If this is global security, we can generate this code :
```python
class MyServiceCredentials(ApiKeyCredentials):
   def __init__(self, x_api_key, api_key):
       super(MyServiceCredentials, self).__init__(
           in_header={‘X-API-Key’: x_api_key},
           in_query={‘api_key’: api_key}
       )
```
If it’s local security, it becomes a parameter of the method (like any parameters).

Advantages:
-	We can release right now CS packages. Adding ApiKey support later is not breaking, since we already have the base class.
-	Each language owner should implement a ApiKeyCredentials based on that model. For short term CS scenario, long term ApiKey scenario. It’s straightforward and does not require any coordination cross team (i.e. not blocked until Autorest.Core has a new feature).
-	Each language owner should provide a CognitiveServicesCredentials class subclass of ApiKeyCredentials with specific CS header and the telemetry header. I still this one is useful, since we have 33 CS api to ship.
-	We add a userstory for Autorest.Core to support ApiKey in the model the language extension receives.
-	We add a userstory per language to support this new model, with the spec I just defined (this one depends on the previous story).

**Comment by amarzavery** [comment]
@jianghaolu @anuchandy @mcardosos @veronicagg @sarangan12 @marstr @kirthik @shahabhijeet - Please take a look at this issue.

**Comment by lmazuel** [comment]
ApiKeyCredentials in Python:
https://github.com/Azure/msrest-for-python/pull/63

**Comment by amarzavery** [comment]
APiKeyCredentials in node SDK 
https://github.com/Azure/azure-sdk-for-node/pull/2311/commits/10725228ee8c3af26b87cd7b1a6b1d791818509d
