### ISSUE TITLE
nested (inline) schemas don't honor `required` properties

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2688]
...in the code model and hence generated code they are just optional anyways

affected SDKs:
- BatchAI
- Web
- ServiceBus
- service-map
- relay
- mobileengagement
- eventhub
- datafactory
- customer-insights
- containerinstance

the fix for this may of course incur breaking changes to the above SDKs - to prevent, edit the corresponding Swaggers: remove `required` array of properties from all nested schema definitions

**Comment by fearthecowboy** [comment]
Wow. 

That's freaking crazy!
