### ISSUE TITLE
How should I fix for the error "[Fatal]Error generating client model: Please specify a field with type of System.Byte[] to deserialize the file contents to"?

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/autorest#2690]
I'm generating C# Client classes from [OpenShift openapi spec json](https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json) with autorest in Visual Studio 2017 15.5 preview. However I got the below error.

```
[Fatal]Error generating client model: Please specify a field with type of System.Byte[] to deserialize the file contents to
```

Looking into the previous issues #2460  and the spec json, I found below definition in spec.

```
     "produces": [
      "*/*"
     ],
```

I've replaced all the produces with ``"*/*"`` to "application/json", but I still have the same error. Could you tell me what this error message means for and how I should fix it?

**Comment by olydis** [comment]
I've replaced all `*/*` with `application/json` and it actually worked 😉  maybe it wasn't just `produces`?

**Comment by tanaka-takayoshi** [comment]
@olydis Thanks! After replacing all ``*/*`` in not only ``produces`` but also ``consumes``, it works!

FYI:
The current OpenShift OpenAPI spec has another issue. If someone is facing the same issue with me, please refer this issue:
https://github.com/openshift/origin/issues/17231
