### ISSUE TITLE
[C#] Reference cycle between generated ServiceClient and MethodGroup causes memory leak

### ISSUE THREAD

**Issue by fiksen99** [Azure/autorest#2697]
Create a simple client with a single methodgroup/method using autorest. csharp flag enabled. azure-arm flag optional

Constructing the client calls Initialize(), in turn constructing the `MethodGroup` with `this` client as its argument and stores the `Client` as a property in the `MethodGroup`. This `MethodGroup` is then set as a property inside the `Client`

We now have a circular reference between the two. 

create a small main method which instantiates the Client 10000 times and notice a memory leak of a few MB is caused.

Fix:

Method Groups should hold on to a `WeakReference` to the client only. Once the user of the library loses reference to the `Client`, the `weakref` will not count towards `Client`s refcount and so will allow the `Client` and all other properties to be GCed. Generated code should look similar to below:

```
        internal ApiGateway(GenevaActionsRestAPIClient client)
        {
            _client = new WeakReference<GenevaActionsRestAPIClient>(client ?? throw new System.ArgumentNullException("client"));
        }

        private readonly WeakReference<GenevaActionsRestAPIClient> _client;

        /// <summary>
        /// Gets a reference to the GenevaActionsRestAPIClient
        /// </summary>
        private GenevaActionsRestAPIClient Client
        {
            get
            {
                _client.TryGetTarget(out GenevaActionsRestAPIClient ret);
                return ret;
            }
        }
```

**Comment by olydis** [comment]
[Circular references of (managed) objects do not cause memory leaks in .NET](https://stackoverflow.com/a/400727/2771806) - the garbage collector will find the participating objects to be unreachable and eventually free the memory. The important word (that explains your observations) is *eventually*: Unless you perform highly unrecommended trickery, *when* the garbage collector runs and performs which kind of search is not in your control.

I actually don't wanna deny memory leaks in our generated code! 🙂 Maybe we're forgetting to release something that has to be explicitly released, but can't think of anything off the top of my head.
Is the memory consumption of generated code an issue for you or was this a general observation?

**Comment by fiksen99** [comment]
This was just through inspection of the code rather than a measured impact we were alerted to. When running a test locally as described above, we were also running GC.Collect() and noticed the references were still around. However part of our test was using Moq which I also saw present in the heap's stack traces, so it seems likely this is why the object was not disposed, and the circular reference a red herring

**Comment by fiksen99** [comment]
Have confirmed removing the reference to Moq removed the appearance of leaks. Thanks for the info around this will bare this in mind in the future
