### ISSUE TITLE
Python doesn't honor x-ms-enum values field

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2704]
According to [here](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-enum) there is a `values` collection supported on enums, for specifying doc-strings for the individual enum values (among other things). But the generated Python code doesn't actually use these doc strings at all.

For example, this snippet of Swagger (from the Azure Batch swagger specification):
```
            "values": [
              {
                "value": "currentuser",
                "description": "Certificates should be installed to the CurrentUser certificate store.",
                "name": "currentUser"
              },
              {
                "value": "localmachine",
                "description": "Certificates should be installed to the LocalMachine certificate store.",
                "name": "localMachine"
              }
            ]
          }
```

generates this Python code:

```
class CertificateStoreLocation(Enum):
    current_user = "currentuser"
    local_machine = "localmachine"
```

It should generate something that looks like this:
```
class CertificateStoreLocation(Enum):
    """Certificates should be installed to the CurrentUser certificate store."""
    current_user = "currentuser"
    """Certificates should be installed to the LocalMachine certificate store."""
    local_machine = "localmachine"
```

**Comment by matthchr** [comment]
@annatisch @lmazuel

**Comment by lmazuel** [comment]
Tried different syntax:
```python
class StatusLevelTypes(str, Enum):

    info = "Info"
    """This is the info tool box"""
    warning = "Warning"
    error = "Error"
```
gives
![image](https://user-images.githubusercontent.com/1050156/37803120-682044ea-2dea-11e8-8c68-00a6780abe3e.png)

**Comment by lmazuel** [comment]
Tried too:
```python
class StatusLevelTypes(str, Enum):

    info = "Info"  #: This is the info tool box
    warning = "Warning"
    error = "Error"
```
gives:
![image](https://user-images.githubusercontent.com/1050156/37803207-d0ea4584-2dea-11e8-9f6f-d3b7abc3f566.png)

**Comment by lmazuel** [comment]
Tried:
```python
class StatusLevelTypes(str, Enum):
    """
    :cvar info: This is the info tool box
    """
    info = "Info"
    warning = "Warning"
    error = "Error"
```
gives:
![image](https://user-images.githubusercontent.com/1050156/37803291-2e1f096a-2deb-11e8-82c9-d5b2b5aa8851.png)

**Comment by matthchr** [comment]
@alpark Since you asked about this -- we have to resolve this bug and then the comments will come back (on the Enum instead of the method).

Thanks for finding the issue.

**Comment by lmazuel** [comment]
Fixed in Autorest.Python 3.0.43
