### ISSUE TITLE
Node.js doesn't honor x-ms-enum values field

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2706]
According to [here](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-enum) there is a `values` collection supported on enums, for specifying doc-strings for the individual enum values (among other things). But the generated Node code doesn't actually use these doc strings at all.

For example, this snippet of Swagger (from the Azure Batch swagger specification):
```
            "values": [
              {
                "value": "currentuser",
                "description": "Certificates should be installed to the CurrentUser certificate store.",
                "name": "currentUser"
              },
              {
                "value": "localmachine",
                "description": "Certificates should be installed to the LocalMachine certificate store.",
                "name": "localMachine"
              }
            ]
          }
```

But in Node, we don't actually define the enums anywhere, so this extra documentation gets lost, which is unfortunate because in some of the strongly typed languages (i.e. C#) this is correctly rendered onto the generated enums and makes the experience for the customer significantly better.

Python has a similar issue, but in Python there is a place to put the docs: See #2704

**Comment by matthchr** [comment]
@amarzavery

**Comment by matthchr** [comment]
I spoke with @amarzavery about this and he said it was a pretty easy fix

**Comment by OzBob** [comment]
The current version 'version: 2.0.4283; node: v12.4.0', throws exceptions: "Values specified by 'enum' mismatch those specified by 'x-ms-enum' (name: 'Reason'): 'AccountNameInvalid', 'AlreadyExists' vs '0', '1'"

When processing: https://github.com/OzBob/autorest/blob/master/Samples/1d-common-settings/base/folder/generated/AwesomeNamespace.json
