### ISSUE TITLE
GO: add support for additionalProperties for discriminated types

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2710]
Updating autorest.go to latest autorest test server uncovered this issue.  The additionalProperties property doesn't have a serialized name (the SerializedName field is null) which results in bad codegen.  It has been worked around (see PR) but needs to be fixed.
https://github.com/Azure/autorest.go/pull/53

**Comment by jhendrixMSFT** [comment]
Change that introduced additionalProperties to a discriminated type.
https://github.com/Azure/autorest.testserver/commit/5e2a34c51ee5d11fac8f78ed4b3d8980607b6ba2#diff-4495679b987a6e74093a1020feee1736

**Comment by vladbarosan** [comment]
tracking here #2773 and in go sdk repo, closing
