### ISSUE TITLE
Incorrect validation error XmsExamplesRequired

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2717]
Hi,
while running autorest with `--azure-validator` I got following error:
```
{
  "type": "Error",
  "code": "XmsExamplesRequired",
  "message": "Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for 
operations.",
  "id": "R2022",
  "validationCategory": "SDKViolation",
  "providerNamespace": null,
  "resourceType": null,
  "sources": [
    "file:///C:/Code/DheerendraRathor/azure-rest-api-specs/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/2016-12-01/backupManagement.json:20:2 ($.paths)"
  ]
}
```

It is throwing error for `paths` node. I don't think this error should be on paths node.

**Comment by olydis** [comment]
Thanks for pointing that out, tagging our validation people. @dsgouda @veronicagg Are you aware of this or is this possibly already fixed in the upcoming stable?

**Comment by dsgouda** [comment]
Thanks for filing this, validation related errors can be file [here](https://github.com/Azure/azure-openapi-validator)
Closing this issue in favor of [this](https://github.com/Azure/azure-openapi-validator/issues/123)
