### ISSUE TITLE
How to share single instance of HttpClient?

### ISSUE THREAD

**Issue by abatishchev** [Azure/autorest#2720]
I see @markcowl said in https://github.com/Azure/azure-sdk-for-net/issues/2779 this possible in Azure Management API client but is this possible in general? For instance, in //Swagger-generated client.

**Comment by olydis** [comment]
What do you mean with "//Swagger-generated client"? @shahabhijeet is this actually possible? All I see getting passed down to the client runtime's "ServiceClient" base class is a `HttpClientHandler`!

**Comment by abatishchev** [comment]
hi @olydis, thanks for responding. I work at Microsoft too, and here at WDG/UST we have a project called MS~Swagger at https://swagger which generates API clients based on XML docs using AutoRest. It might be company-wide project but I'm frankly not sure, see https://osgwiki.com/wiki/Swagger_How_To.

**Comment by abatishchev** [comment]
hi @shahabhijeet, please take a look

**Comment by abatishchev** [comment]
hi @shahabhijeet, please take a look

**Comment by abatishchev** [comment]
hi @shahabhijeet, please take a look

**Comment by votrubac** [comment]
Does not work in the latest configuration:
'@microsoft.azure/autorest.csharp' (~2.2.45)
'@microsoft.azure/autorest.modeler' (2.3.42)

**Comment by abatishchev** [comment]
Any updates on this, please?

**Comment by olydis** [comment]
@abatishchev see [here](https://github.com/Azure/autorest/issues/2785), I think it's the same issue

**Comment by abatishchev** [comment]
Cool, let's merge the issues then.
