### ISSUE TITLE
Add command line help for your generator

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2725]
With upcoming AutoRest, there will finally be a nice, extensible CLI help available if you do `--help`:
![image](https://user-images.githubusercontent.com/9320958/33100093-058f3be6-cec8-11e7-9275-6878645d8083.png)

The indicated part only shows when you add `--csharp` to the same command line, so we won't throw documentation for 8 generators and x validation tools at you at once.
All of you own a generator, so please add your part of the picture, i.e. document any flag or setting that makes your generator behave differently! Most likely, you can start with C# and just remove some stuff, since C# has a pretty wild set of stuff (except `package-version` and such).

### The best part is, it's super easy!!!

Just add a section like [this](https://github.com/Azure/autorest.csharp#help) to your generator's `README.md`. As specified right there, the type of that YAML blob is defined [here](https://github.com/Azure/autorest/blob/master/src/autorest-core/help.ts), but you may not even have to look at that. That's it.

### Testing

To test, install `autorest@preview` and run `autorest --help --use=<path to your generator>`

**Comment by lmazuel** [comment]
Done for Python: https://github.com/Azure/autorest.python/pull/24

**Comment by lmazuel** [comment]
@olydis seems "clear-output-folder" is missing from "Core Settings" help right?

**Comment by marstr** [comment]
Tracking this work for Go in issue Azure/azure-sdk-for-go#2798

**Comment by RikkiGibson** [comment]
Tracking in Azure/autorest.typescript#295
