### ISSUE TITLE
EBUSY

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2726]
@matthchr FYI

>  Process() Cancelled due to exception : spawn EBUSY
>  { Error: spawn EBUSY
>      at exports._errnoException (util.js:1050:11)
>      at ChildProcess.spawn (internal/child_process.js:319:11)
>      at Object.exports.spawn (child_process.js:378:9)
>      at ExtensionManager.start (/node_modules/@microsoft.azure/extension/dist/main.js:488:32)
>      at LocalExtension.start (/node_modules/@microsoft.azure/extension/dist/main.js:208:38)
>      at LazyPromise.CreateView.loadedExtensions.(anonymous function).autorestExtension.lazy_1.LazyPromise [as factory] ([...]\AutoRest.2.0.4166\node_modules\@microsoft.azure\autorest-core\dist\lib\configuration.js:562:182)
>      at LazyPromise.get Value [as Value] ([...]\AutoRest.2.0.4166\node_modules\@microsoft.azure\autorest-core\dist\lib\lazy.js:27:33)
>      at LazyPromise.then ([...]\AutoRest.2.0.4166\node_modules\@microsoft.azure\autorest-core\dist\lib\lazy.js:32:20)
>      at process._tickCallback (internal/process/next_tick.js:109:7) code: 'EBUSY', errno: 'EBUSY', syscall: 'spawn' }
>  error MSB3073: The command "[...]\AutoRest.2.0.4166\AutoRest.cmd -Modeler Swagger -CodeGenerator Azure.CSharp -Namespace

**Comment by matthchr** [comment]
This happens when using a standalone deployment (i.e. I don't have node installed, it's bundled with AutoRest).

**Comment by fearthecowboy** [comment]
I'm wondering if this is a result of blocked files (ie, files unpacked from a zip file and tagged with a zone.identifier stream)

This is the second time I've heard this, and both times, it was the result of someone running autorest unpacked from a zip file (.nupkg file)...

**Comment by matthchr** [comment]
Are you aware of a workaround? I've tried copying the content of the unzipped nupkg locally (into each project building, so there's no parallelism involved), and still get the same error.

Of course to make matters lovely to debug I can only reproduce the problem in official builds, not locally.

**Comment by fearthecowboy** [comment]
I don't think it has anything to do with parallelism.  If the files are tagged with a zone identifier, copying them won't do anything.

The other option is that Defender is dragging it's ass, and it's still locked by the time it runs the extension...

This is in the CoreXT environment on build servers?

I'm back on Monday, I'll have to dig into it more then.

**Comment by matthchr** [comment]
Yes, I can give you some build links if you want to see
