### ISSUE TITLE
Incorrect enum values for boolean property with default values

### ISSUE THREAD

**Issue by djyou** [Azure/autorest#2727]
When generating Azure resource schema from swagger, boolean property with default values don't have the correct enum value set.

[Example property in swagger](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/2017-10-01/containerregistry.json#L1206):

```
        "adminUserEnabled": {
          "description": "The value that indicates whether the admin user is enabled.",
          "default": false,
          "type": "boolean"
        },
```

Generated property in schema:
```
        "adminUserEnabled": {
          "oneOf": [
            {
              "type": "boolean",
              "enum": [
                "false"
              ]
            },
            {
              "$ref": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/expression"
            }
          ],
          "description": "The value that indicates whether the admin user is enabled."
        },
```

The enum set should contain both `true` and `false` boolean values rather than one string value.

The same issue is seen in other published schema such as [Storage](https://github.com/Azure/azure-resource-manager-schemas/blob/0f742766eb22be8d2807283e8055221d373ebf79/schemas/2017-06-01/Microsoft.Storage.json#L467).

This is blocking us from releasing resource schema https://github.com/Azure/azure-resource-manager-schemas/pull/370

**Comment by fearthecowboy** [comment]
Thanks @djyou!

O_o That's just wrong!

Do you know if it only happens when you specify a `default` value?

I'll have someone look into this.

**Comment by djyou** [comment]
Boolean without a default value looks good to me
```
        "adminUserEnabled": {
          "description": "The value that indicates whether the admin user is enabled.",
          "type": "boolean"
        },
```
Generated property in schema:
```
        "adminUserEnabled": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "$ref": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/expression"
            }
          ],
          "description": "The value that indicates whether the admin user is enabled."
        },
```

**Comment by olydis** [comment]
@daschult I see you initially added the above behavior [here](https://github.com/Azure/autorest/blame/42cd6036800f21baa624b2b54b0c013c12d7707d/AutoRest/Generators/AzureResourceSchema/AzureResourceSchema/ResourceSchemaParser.cs#L185-L188). Before touching it I wanted to quickly clarify, was there a reason for this design? The `JsonSchema` type doesn't have a `Default` property (yet), was this maybe just a workaround to somehow encode the information in the resulting schema? 🙂

**Comment by daschult** [comment]
I don't think there was a specific reason for this design. I most likely just hadn't gotten around to supporting it yet. I suggest adding it in.
