### ISSUE TITLE
Long title prevents client generation? 

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2738]
Reported:

There seems to be a bug somewhere in the generation code. Our specification had the following title and generation did not fail, validation did not fail and the client file was not generated. 

``` yaml
swagger: "2.0"
info:
  title: Service Fabric Resource Manager Container group set APIs
  description: APIs to deploy and manage container group set Service Fabric.
  version: "2017-11-01-preview"
```

When we changed the title to following, the client file was generated. 

``` yaml
swagger: "2.0"
info:
  title: SeaBreezeManagementClient
  description: APIs to deploy and manage container group set Service Fabric.
  version: "2017-11-01-preview"
```

If this is expected then I would expect the code generation to fail with the error and not silently continue. Can you please verify?

Thanks,
Vipul

**Comment by olydis** [comment]
@VipulM-MSFT (assuming you reported the above 🙂 )

I cannot reproduce the issue. Using the above long title works fine for me, even after repeating it 4 times:
![image](https://user-images.githubusercontent.com/9320958/33395807-8999e01a-d4fb-11e7-97df-36e154ecba88.png)

Could you provide further information or maybe a full Swagger to reproduce the issue?

**Comment by fearthecowboy** [comment]
@olydis try with python...

**Comment by olydis** [comment]
![image](https://user-images.githubusercontent.com/9320958/33399779-aba320ec-d508-11e7-8073-281c4ed0f9c1.png)

**Comment by VipulM-MSFT** [comment]
ap file gets generated but the Client file is not generated. I will ping you will the full specification

**Comment by olydis** [comment]
not sure what "ap file" vs "Client file" is in your case, the files I posted above *are* the clients 🙂
