### ISSUE TITLE
Update Version Breaks BaseUri Default (CSharp)

### ISSUE THREAD

**Issue by elmo61** [Azure/autorest#2746]
Having updated my Autorest and regenerated my CSharp SDK. The Root Class file has as function

`private void Initialize()`

Within this it sets the BaseUri for the Class With the new code being different from the old version. 
*New Version 2.0.4210*
`BaseUri = new System.Uri("");`

*Old Version 2.0.4147*
`BaseUri = new System.Uri("http://localhost/");`

The New version is not valid in C# as URI class will error out as empty string is not a valid URI. 

Do we know why this was changed? as it completely breaks my SDK as it can never initialise the SDK

**Comment by fearthecowboy** [comment]
@olydis ? Did something change here?

**Comment by fearthecowboy** [comment]
@elmo61 -- do you have a 'host' in your swagger?

**Comment by elmo61** [comment]
@fearthecowboy  are you referencing to the Swagger.json file? then no i don't see any Host property in there before or after. I don't think there ever was. 

The way I set my Host when using the SDK is setting it on initalising the SDK Class

```
var oUri = new Uri(_uri);
client = new AllSubsApi(oUri, creds);
```
Where `_uri = "http://localhost:12356" `

But again this hasn't changed and it seems the Initialize() is called before hand, so it never gets to using my passed in Host / Uri

**Comment by olydis** [comment]
this will be fixed with the next release, you can use `--use=@microsoft.azure/autorest.modeler@2.3.40` until then to get the default URL 🙂
