### ISSUE TITLE
AutoRest client OData support

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2748]
I’m hitting some issues with the OData support in the AutoRest generated clients. What’s the best way to report these issues?

In particular:
-	When “x-ms-client-flatten” is set on a definition, paths to child properties are incorrect. They should use the format “parent/child”, but with flattening turned on, the paths become “parent.child”.
-	Dates and GUID constants should not be quoted in OData filter expressions

There are some examples in the OData spec showing how date constants should be encoded:
http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc371341809

The actual specification for dates and GUIDs is here (see “7. Literal Data Values”):
http://docs.oasis-open.org/odata/odata/v4.01/csprd03/abnf/odata-abnf-construction-rules.txt

Here are some example queries created with AutoRest 2.0.4166, autorest.csharp 2.1.0, autorest.modeler 2.1.22 using the --csharp and --azure-arm options. The client code is using Microsoft.Rest.ClientRuntime.Azure version 3.3.10.
Simple query – Works correctly

Client code:

`client.Assets.List(new ODataQuery<Asset>(a => a.Name == "somename"));`

Query without encoding:
`$filter=name eq 'somename'`

Full request:

`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=name%20eq%20'somename'&api-version=2018-03-30-preview HTTP/1.1`

Query without model flattening – Also works correctly
Client code:

`client.Assets.List(new ODataQuery<Asset>(a => a.Properties.AlternateId == "somename"));`

Query without encoding:
`$filter=properties/alternateId eq 'somename'`

Full request:
`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=properties/alternateId%20eq%20'somename'&api-version=2018-03-30-preview `HTTP/1.1

Query with model flattening – Child resource paths are incorrect
Client code:
`client.Assets.List(new ODataQuery<Asset>(a => a.AlternateId == "somename"));`
`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=properties.alternateId%20eq%20'somename'&api-version=2018-03-30-preview HTTP/1.1`

Query without encoding:
`$filter=properties.alternateId eq 'somename'`
Full request:
`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=properties.created%20gt%20'11%2F29%2F2017%2018%3A11%3A49%20%2B00%3A00'&api-version=2018-03-30-preview HTTP/1.1`

Filtering by date property – Dates should not be quoted
Client code:
`client.Assets.List(new ODataQuery<Asset>(a => a.Created > DateTimeOffset.UtcNow));`

Query without encoding:
`$filter=properties.created gt '11/29/2017 18:01:13 +00:00'`

Full request:
`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=properties.created%20gt%20'11%2F29%2F2017%2018%3A01%3A13%20%2B00%3A00'&api-version=2018-03-30-preview HTTP/1.1`

Filtering by a GUID property – GUIDs should not be quoted
Client code:
``` csharp 
var g = Guid.NewGuid();
client.Assets.List(new ODataQuery<Asset>(a => a.AssetId == g));
```
Query without encoding:
`$filter=properties.assetId eq '650c9ae0-e991-4413-a58f-2b4e40585c97'`

Full request:
`GET https://api-dogfood.resources.windows-int.net/subscriptions/24822430-0200-4092-8065-6ab46f967194/resourceGroups/mediaresources/providers/Microsoft.Media/mediaServices/jopaynmedia22/assets?$filter=properties.assetId%20eq%20'650c9ae0-e991-4413-a58f-2b4e40585c97'&api-version=2018-03-30-preview HTTP/1.1`

**Comment by hfurubotten** [comment]
I have the same problem with Guids and Dates when I'm using this on my odata api atm. I had to result to using manually written filter statements now to actually be able to deliver software out to my customers, and aren't quite happy with that, but is a working workaround. 

Im also having problems with enums, which doesn't seem to be covered in the original post. And it doesn't seem like it follows the odata v4 standard. 

The code im running: 
```cs 
       Expression<Func<Delivery, bool>> exp = x =>
            x.State == State.Active  
            && (x.Status == DeliveryStatus.InProgress
                || x.Status == DeliveryStatus.PendingCustomerInitiation);

        var filter = new ODataQuery<Delivery>(exp)
        {
            Top = 1
        };
```

This results in this filter statement:
`$filter=state eq 0 and status eq 1 or status eq 0&$top=1`

Here the enum `DeliveryStatus` is converted to a int value which actually should be a string variant of the enum, such as the values `'0'`/`'1'` or the written variant `'InProgress'`/`'PendingCustomerInitiation'`. (Alternatively with full namespace if you dont have prefix free enums enabled.) Have I interpeted the odata v4 standard correctly when I say that all enums needs to be represented as a string in filter statements and thus needs single quotes?

In addition it seems to be the linq statements that gives it int representation as this does a convert of the enum on the data before "comparing" it as ints to the constant value in the query.

Generated linq expression: 
`x => ((Convert(x.State) == 0) AndAlso ((Convert(x.Status) == 1) OrElse (Convert(x.Status) == 0)))`

Last note: parentheses also doesn't seem to be translated correctly in my case. Not sure whats correct here.

**Comment by johndeu** [comment]
Is anyone ever going to fix the filtering issue for Odata?

**Comment by fearthecowboy** [comment]
(Closing; we're going to start the discussion for vNext issues soon)

**Comment by binaryroc** [comment]
@fearthecowboy where can I find the discussion on Odata support for vNext? Thanks.
