### ISSUE TITLE
Python client generated no longer includes setup.py after upgrade to 2.0.4215 (core)/2.1.26 (Python extension)

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/autorest#2757]
Since the autorest version was upgraded from 2.0.4166 (core)/2.0.13 (python) to 2.0.4215 (core)/2.1.26 (python), we are experiencing failures in our Python client generation (for this [spec](https://github.com/PakDLiu/azure-rest-api-specs/tree/current/specification/hanaonazure/resource-manager)). It used to work just fine with the previous version with `autorest --python` command (freshly executed every time in a Dockerfile). Now it's failing these days (with the latest autorest version) with "No configuration found at file:///home/user/.autorest/' and "[Exception] No input files provided.". This can be fixed by just running `autorest --reset` prior to running `autorest --python`, but then the generated python code directory no longer includes the setup.py, which we depended to run the `pip install` command. Is this an intended change? Is there a way for us to still get the setup.py so that we can install the individually generated python client directory?

**Comment by fearthecowboy** [comment]
@hosungsmsft I think I know of the `file:///home/user/.autorest/` issue, that fix just went in; I think it's getting added to stable today.

@lmazuel would know more about the `setup.py` issue

**Comment by olydis** [comment]
by design AFAIK, I think you have to pass `--basic-setup-py` to generate it from now on

**Comment by hosungsmsft** [comment]
Thanks @fearthecowboy and @olydis for your quick responses! So I keep avoiding the `file:///home/user/.autorest/` issue by running `autorest --reset` first, and now the `--basic-setup-py` option gives me back the setup.py, so I'm good to go for now.

**Comment by lmazuel** [comment]
Hi @hosungsmsft 
Indeed, I made the generation of this file optional, since it's ok for basic scenarios, but totally not for packaging and release on PyPI.
Indeed, the `--basic-setup-py` keep generates it exactly as before, but at least I make it clear that this is a **basic** setup.py
