### ISSUE TITLE
Error: collectionFormat:pipes is no longer supported except for in:query parameters

### ISSUE THREAD

**Issue by Geogboe** [Azure/autorest#2758]
# Overview

I call Autorest to validate my spec like this:
`autorest.cmd --input-file=swagger.json`

Which returns this error:
```
FATAL: openapi-document/openapi-document-converter - FAILED
FATAL: Error: collectionFormat:pipes is no longer supported except for in:query parameters
Process() Cancelled due to exception : collectionFormat:pipes is no longer supported except for in:query parameters
  Error: collectionFormat:pipes is no longer supported except for in:query parameters
```

The context of this error appears to be this parameter block:
```json
            "name": "views",
            "in": "formData",
            "description": "My description.",
            "required": false,
            "type": "array",
            "collectionFormat": "pipes",
            "items": {
              "type": "string",
              "enum": [
                "External",
                "Internal"
              ]
```

I'm using formData and the docs state this CollectionFormat: pipes supports in:query and in:formData. 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

Yet, why is autorest saying that CollectionFormat:pipes **only** supports in:query?

Background info:
- Windows 10.0.17025
- Autorest 2.0.4215
- npm 5.3.0
- node v8.2.1

Thanks!

**Comment by olydis** [comment]
Wat, sorry about that! I'm on it, fix will be published tomorrow

**Comment by Geogboe** [comment]
@olydis Wow quick response! Thanks and let me know if I can help test or anything!

**Comment by olydis** [comment]
@Geogboe should be fixed now, you can run `autorest --reset` to make sure the recent generator is downloaded. 🙂 Let me know if you encounter any issues!

**Comment by Geogboe** [comment]
@olydis Awesome! Seems to be working!

```powershell
AutoRest code generation utility [version: 2.0.4215]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.45)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.42)
```
