### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by joshmouch** [Azure/autorest#2766]
After updated AutoRest.CSharp from 2.0.0 to 2.2.45, I noticed that the default generated Client class includes a line that throws an exception.  Here is the generated code:

    private void Initialize()
    {
        BaseUri = new System.Uri("");

And the exception is:

    System.UriFormatException: 'Invalid URI: The URI is empty.'

This used to be:

        BaseUri = new System.Uri("http://localhost");

Any thoughts?

**Comment by fearthecowboy** [comment]
We just put a fix in for that a couple days ago.

try `autorest --reset --csharp` and it should update the csharp generator to the latest 

use `autorest --info` after, it should be 2.2.49

``` haskell
AutoRest code generation utility [version: 2.0.4215]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4220     C:\Users\garretts\.autorest\@microsoft.azure_autorest-core@2.0.4220
 extension  @microsoft.azure/autorest.csharp         2.2.49       C:\Users\garretts\.autorest\@microsoft.azure_autorest.csharp@2.2.49
 extension  @microsoft.azure/autorest.modeler        2.3.42       C:\Users\garretts\.autorest\@microsoft.azure_autorest.modeler@2.3.42
```

**Comment by MiYanni** [comment]
Issue resolved. Closing.
