### ISSUE TITLE
Annoying error messages during editing of markdown file

### ISSUE THREAD

**Issue by seoriy** [Azure/autorest#2770]
Now, if I edit markdown file VS Code showing me output window (seems like because of issue like https://github.com/JuliaEditorSupport/julia-vscode/issues/367) with error messages like: 

"[Error - 19:11:16] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Specified file 'file:///some/path/README.md' is not a valid configuration file (missing magic string, see https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md#the-file-format).
  Code: -32603 "

VS Code: 1.18.1

**Comment by fearthecowboy** [comment]
That should be a cosmetic error, (although, I thought that shouldn't show up unless you have `autorest.debug` and/or `autorest.verbose` set to `true` in your vscode settings file.

Can you confirm that you don't have that set? (and I'll go check to see that it's not spewing that in the wrong channel...)

**Comment by fearthecowboy** [comment]
One more thing: can you close vscode, and run 

``` powershell
npm install -g autorest@preview
autorest --reset --latest
``` 

I think the language service should have an update. 

(that being said, I found another glitch while trying to repro your problem, lemme go fix that)

**Comment by seoriy** [comment]
Thanks! It has fixed the problem.
But should it check markdown files in VS Code or it's some issue with AutoRest VS Code extension?
All options was by default. I just install AutoRest VS Code extension yesterday via built-in extension manager (Extensions tab).
Anyway, thanks for fix!

**Comment by fearthecowboy** [comment]
It's supposed to check the markdown files; it was just being over-verbose when it checked the content.
