### ISSUE TITLE
Add support to serialize/deserialize additionalProperties

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#2773]
Today Autorest transforms every model as a closed/tight/strict model for every model definition in the swagger spec. 
If someone specifies `"additionalProperties": true`  **OR**
```json5
"additionalProperties": { 
  "type": "object" // "string" | "number" or any other JSON type
}
```
If the swagger spec has a model definition like this
```
{
  "Foo": {
    "properties": {
      "name": {
        "type": "string"
      },
      "age": {
        "type": "number"
      }
    },
    "additionalProperties": {
      "type": "string"
    }
  }
}
```
then Autorest generated SDKs should be able to serialize and deserialize (round trip) the unknown properties correctly.

### Generated C# clients support this today by having a `Dictionary<string, (someType)> AdditionalProperties`.
Other languages - node.js, python, Go, ruby, Java need to make sure that they support this functionality.

- For **node.js** we have taken the route to have additional(unknown) properties be present wherever they logically belong rather than putting them in a dictionary named additionalProperties. This is intuitive for JS as customers are used to providing a JSON object and receiving the same.
In the above example, 
The TS interface will look like
```typescript
interface Foo {
  name: string;
  age: number;
  [x: string]: string | any;
}
```
and the javascript object will look like
```javascript
var foo = {
  "name": "some name",
  "age": 10,
  "color": "red" //unknown properties are present wherever they logically belong
  "size":  "XL"
};
```
@jianghaolu @veronicagg @sarangan12 @jhendrixMSFT @mcardosos @lmazuel - Please make sure that your language supports this feature.

**Comment by olydis** [comment]
FYI, the modeler will send your generator a property with `SerializedName == null` and `ModelType is DictionaryType` if additionalProperties is used. *This* is how you should detect whether it is the "magic" property bag and not just a regular property called "additionalProperties" - **so don't go by name** 😉

**Comment by lmazuel** [comment]
Obviously I tried by name first, and obviously there is a Swagger that use that :p
Python PR for that:
https://github.com/Azure/msrest-for-python/pull/71

Once merged, I'll remove the tag. Thanks!!

**Comment by vladbarosan** [comment]
https://github.com/Azure/autorest.go/pull/70 for Go

**Comment by amupla** [comment]
What's the latest with this request? Does close mean the feature is complete or dropped?

**Comment by fearthecowboy** [comment]
this was done a long time ago.
