### ISSUE TITLE
Add serialization test scenario for extensible enum tests in testserver

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2777]
We need to ensure that validation is turned off for extensible enums during serialization. Means adding a test case [here](https://github.com/Azure/autorest.csharp/blob/master/test/vanilla/AcceptanceTests.cs#L432) with an unknown enum value

**Comment by olydis** [comment]
@dsgouda didn't you do that? I remember something with days of week or so 🙂

**Comment by dsgouda** [comment]
The link I have posted is daysofweek extensible enum, but it does not have this particular scenario 😞

**Comment by olydis** [comment]
oh lol... and what about the "pinkish-gray" you added to the polymorhpic test case?

**Comment by olydis** [comment]
https://github.com/Azure/autorest.testserver/blob/master/swagger/body-complex.json#L1376
https://github.com/Azure/autorest.testserver/blob/master/routes/complex.js#L340

**Comment by dsgouda** [comment]
Yes, that was serializing deserializing in complex objects and ensuring there isn't funky behavior because of enums, we just need to replicate that here (or not, I'll leave that to you 😄  )

**Comment by olydis** [comment]
got it, yeah would be cleanest to replicate as part of the daysofweek scenario

**Comment by dsgouda** [comment]
@olydis would you like to take over this
