### ISSUE TITLE
autorest doesn't generate code after upgrading to Node.js v9.3.0 and npm 5.6.0

### ISSUE THREAD

**Issue by fbayanati** [Azure/autorest#2778]
Updated autorest to 2.0.4215 and mean while upgraded Node.js to 9.3.0 and npm 5.6.0 then it stoped generating code from swagger json document .

The command line is something like below:
autorest -CodeGenerator CSharp -Input "http://localhost:51176/swagger/1.0/swagger.json" -OutputDirectory "C:\Projects\TfsGit\Application\Application.Api.Sdk" -Namespace "Application.Api.Sdk"

**Comment by fearthecowboy** [comment]
Well; first of all, I'd stop using the old command line syntax; that's just a recipe for disaster :D

``` powershell
autorest --csharp --input-file=http://localhost:51176/swagger/1.0/swagger.json --output-folder=C:\Projects\TfsGit\Application\Application.Api.Sdk --namespace=Application.Api.Sdk
```

You could add a `--debug --verbose ` and it might tell you what's going on.

FYI; we had a few people last week have serious trouble with node 9.x -- you might want to back off to the stable node 8.9.1

**Comment by fbayanati** [comment]
Ok, I downgraded to Node.js 8.9.3 which is the LTS version at the moment and still see the same issue.

by adding below ones:
--debug --verbose 
the output is as following and doesn't generate the codes.

AutoRest code generation utility [version: 2.0.4215]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from

About the old command line syntax I didn't get it, that's based on documentation over [here](https://github.com/Azure/autorest/blob/master/docs/user/cli.md) with passing parameters instead of using config file, please advise.

**Comment by fbayanati** [comment]
Just an update to don't leave the issue open, Cleaned up Node.js completely and re-installed Node.js 8.9.3.
Also changed the command as recommended by @fearthecowboy in above comment, it worked after the Node.js clean re-install

`autorest --csharp --input-file=http://localhost:51176/swagger/1.0/swagger.json --output-folder=C:\Projects\TfsGit\Application\Application.Api.Sdk --namespace=Application.Api.Sdk --debug`
