### ISSUE TITLE
"allowedValues" of "x-ms-enum" is not documented, but part of the testserver

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2787]
The [x-ms-enum](https://github.com/Azure/autorest/blob/4d5a719565dd0ad16403018bada949c2c415aa39/docs/extensions/readme.md#x-ms-enum) documentation does not describe "allowedValues", but this is described in the [testserver](https://github.com/Azure/autorest.testserver/blob/b8df84abe06fbfbcb89e5ad3facb0624904385b0/swagger/extensible-enums-swagger.json#L114-L117):
```json
     "x-ms-enum": {
      "modelAsExtensible": true,
      "name": "IntEnum",
      "values": [
       {
        "value": "2",
        "description": "two",
        "name": "2",
        "allowedValues": [
         "2.1",
         "2.2",
        ]
       },
```
And the fixture `allowedValueEnum` expects that when [the server returns "2.1", the SDK returns the enum "2"](https://github.com/Azure/autorest.testserver/blob/83344d1db6fa29418ae60cf86685544e46c3a28f/routes/extensibleEnums.js#L38-L41). This is [tested in C#](https://github.com/Azure/autorest.csharp/blob/e5f871b7433e0f6ca6a17307fba4a2cfea4942b4/test/vanilla/AcceptanceTests.cs#L429).

Side note: I didn't find any occurrence of this in "real life" Swagger files.

I'm a little concerned about this:
- Is this expected that all language supports that? If yes, at least this should be documented properly.
- If this is deprecated, the testserver fixture should be removed. IOW, this should not be a requirement to reach 100% test coverage.

FYI @johanste @fearthecowboy @olydis @marstr @veronicagg @amarzavery

**Comment by lmazuel** [comment]
I guess this is implied by my message, but Python has no support of that feature.

**Comment by fearthecowboy** [comment]
This is a "feature-in-progress"... It's not required to support at the moment. My bad -- we should disable this test for the moment.
