### ISSUE TITLE
TestServer returns "text/html" content-type for extensible-enums

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2788]
For extensible enums file:
https://github.com/Azure/autorest.testserver/blob/83344d1db6fa29418ae60cf86685544e46c3a28f/routes/extensibleEnums.js

content-type is HTML:
```python
In [4]: import requests
In [5]: r = requests.get("http://localhost:3000/extensibleenums/pet/tommy")
In [6]: r.headers['Content-Type']
Out[6]: 'text/html; charset=utf-8'
```

This blocks the deserialization in Python, since we are picky on the ContentType.

TestServer 2.3.20

@amarzavery @dsgouda

**Comment by dsgouda** [comment]
Thanks for filing this, will take  a look at this soon.

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/autorest.testserver/pull/42
