### ISSUE TITLE
Syntax of transform

### ISSUE THREAD

**Issue by gregorybleiker** [Azure/autorest#2790]
Could someone point me to the documentation on what the syntax for transform is? Especially the meaning of "|", "|-", ">" and ">-" after the transform.
BR

**Comment by fearthecowboy** [comment]
The `|`, `|-`, `>` and `>-` Symbols are all part of [standard YAML encoding](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines#21699210).

A `transform` in AutoRest is a `directive` that modifies the internal representation of a document or DOM. 

The `transform` itself is a javascript snippet that returns a replacement node for a selected node in a DOM.

If you want to examine what the DOM documents look like at a given point, you can use the prototype interactive tool to see what it's doing: `autorest --use=olydis/autorest-interactive --csharp readme.md` and that will install use the `autorest-interactive` extension.

The [original specs ](https://github.com/Azure/autorest/blob/master/docs/proposals/generator-specific-settings/literate-configuration.md#directives---global-or-per-language) for `directives` in autorest is probably not the clearest, as that was the spec that I wrote well before implementation, but the intent should be pretty clear.

The [implementation-level docs ](https://github.com/Azure/autorest/blob/aafd072e035a5a3aad01cfa9803a3663f675a2d3/src/autorest-core/resources/default-configuration.md#directives) for directives is built into the default configuration of AutoRest, and you can look at how we handle a lot of things in there.

The best I can do is point you to the [Samples](https://github.com/Azure/autorest/tree/master/Samples) folder in the repo, as it demonstrates a lot of what's doable.

or a [search](https://github.com/Azure/autorest/search?l=Markdown&q=directive&type=&utf8=✓) for `directive` in the markdown documents in the repository could help find examples that are useful.

If you need more, you'll have to tell me what you're trying to do...

**Comment by gregorybleiker** [comment]
Excellent explanation, thanks Garrett!
I have a json that is missing the operationId, so I tried to get a meaningful name as the opId seems to be used for the code generation. This is what I have come up with
```
    from: swagger-document  
    where: $.paths.*
    transform: >-
      for(var n of Object.keys($)) { $[n].operationId = `${$[n].tags[0]}${$[n].summary}` };
    reason: 'Need to have an operationId'
```
but having the iterator in the javascript seems a bit strange (btw. it might be worth noting somewhere in the docs that this is actually a javascript snippet and what restrictions apply to it, I tried to do a console.log in that part and it wouldn't work)
The reason I used the iterator was because the structure is {"get" :{"feeds": {..}}} or similar and I wanted the operationId to be GetFeeds and there was no way I could see that gets the parent element.

Thanks also for the pointer to the autorest-interactive extension, I will have a look at it.

**Comment by fearthecowboy** [comment]
The javascript is some `saveEval` implementation that @olydis used. I know that `console.log` doesn't work (which was kinda sad, but not the end of the world..) I'll see if I can't dig up the restrictions somewhere.

I was going to suggest another way, but if you were needing the HTTP `method`, then, yeah, the iterator was the way to go.  IIRC, We tried to have some means of finding the parent node, but it was just too much effort, when top-down was good enough.

Dealing with edge cases is why we made it work this way 👍

**Comment by olydis** [comment]
@gregorybleiker the variables available in context of directives are `$` (matched object), `$doc` (root object) and `$path` (should be `['x',3,'asd']` if `$ === $doc.x[3].asd`). Providing something like `$parent` should be implementable for us (via `$path`) *but* it may be misleading in what one could do with it:

We maintain source maps of OpenAPI files as they get processed and mutated by AutoRest - that way, we can give good error messages with source locations in case later stages find an issue in the OpenAPI file. In case of directives, we essentially loose that information (if you renamed a type `Car` to `Auto` with a directive, an issue with `Auto` will not be mapped back to `Car`). We realize this by mutating the object representation of the OpenAPI document as little as possible and in a very isolated manner. In case of directives, precisely the selected object `$` will be replaced in the object graph - if you say `$doc.x = 3`, that change will *not* make it into the resulting OpenAPI document (if we allowed that fidelity, we could not trust our source map anymore at all). Likewise, `$parent` would only be usable to *retrieve* information, but changes to it will not manifest - we could do that, but then we would *always* have to invalidate the source maps of `$parent` and descendants. Huh. So we opted for "forcing" you to explicitly select the parent node, making it explicit that you will modify a larger part of the object.

**Comment by gregorybleiker** [comment]
That makes sense. Thanks for explaining that in such detail. The more magic, the more mess during implementation... I think the current solution is good and I'm very happy with autorest so far (I'm not sure if the swagger.json I'm using is a typical example, however it shows that quite a lot can be done wrong when designing a REST API). I'll close the issue.
