### ISSUE TITLE
Warnings "DescriptionAndTitleMissing" and "ParameterDescriptionRequired" should be errors

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2794]
Hi, currently these two are presented as warnings while DescriptionMustNotBeNodeName is error. 
IMHO, missing description must be treated as error for better documentation of generated swagger.

**Comment by fearthecowboy** [comment]
While the `description` and `title` are indeed warnings, (and Azure rest specs aren't approved missing them), they don't stop us from actually generating code (and since some use this tool for non-Azure purposes), that doesn't rise to the qualification as `Error`

**Comment by DheerendraRathor** [comment]
Same can be said for `DescriptionMustNotBeNodeName` which is error.
And many errors currently reported won't stop code generation as spec is valid. 

Another option can be to report certain warnings as errors by adding customizations in `readme.md` or by marking them as error for `azure-arm` specs.

**Comment by fearthecowboy** [comment]
Touché.

As it is, the validator rules are handled in the project https://github.com/Azure/azure-openapi-validator/ -- if you can convince them, we're golden :D

**Comment by DheerendraRathor** [comment]
Closing it in favour of https://github.com/Azure/azure-openapi-validator/issues/140
