### ISSUE TITLE
Autorest shows error when referencing npm that is located in a Windows folder with space

### ISSUE THREAD

**Issue by annmarinaskowhiri** [Azure/autorest#2804]
Hi there,

I'm currently having issues running autorest where I'm encountering the error below.

I've tried using autorest using the prescribed command line and the other using node.exe explicitly to no avail. 

I have also tried changing the folder paths that node.js and npm use to point to a folder that has no space in the name, and it still did not work

Any help would be highly appreciated.

Many thanks!

------------
> D:\>autorest --input-file=https://myapi/swagger/swagger.json --csharp --namespace=MyNamespace --output-folder=d:\MyClient\
> AutoRest code generation utility [version: 2.0.4215]
> (C) 2017 Microsoft Corporation.
> https://aka.ms/autorest
> No configuration found at 'file:///D:/'.
>    Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51)
>    Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43)
> 'C:\Users\Ann' is not recognized as an internal or external command,
> operable program or batch file.
> Process() Cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> (node:13104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> (node:13104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> D:\>D:\Tools\autorest\tools\win-x64\node.exe D:\Tools\node-js\npm\node_modules\autorest\dist\app.js --input-file=https://myapi/swagger/swagger.json --csharp --namespace=MyNamespace --output-folder=d:\MyClient\
> AutoRest code generation utility [version: 2.0.4215]
> (C) 2017 Microsoft Corporation.
> https://aka.ms/autorest
> No configuration found at 'file:///D:/'.
>    Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51)
>    Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43)
> 'C:\Users\Ann' is not recognized as an internal or external command,
> operable program or batch file.
> Process() Cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> (node:12296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> (node:12296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by fearthecowboy** [comment]
Yeah, I finally reproduced the problem with this one today; I'm gonna try have a fix for tomorrow.

**Comment by annmarinaskowhiri** [comment]
Thanks for that!

**Comment by fearthecowboy** [comment]
Ok, I've gotten a fix. This was trickier than I thought, but I've worked around the problem with spawn.

``` powershell
# grab the latest autorest
npm install -g autorest@2.0.4238

# remove older plugins/core 
autorest --reset 

# try it now
autorest <...>
```

**Comment by annmarinaskowhiri** [comment]
@fearthecowboy: I can confirm that this is now working as expected. Thank you so much for fixing this!
