### ISSUE TITLE
No unique 'title' exception is misleading

### ISSUE THREAD

**Issue by SbiCA** [Azure/autorest#2809]
Hi guys,

I've tried to use 2 swagger files as input with different titles e.g.
```yaml
input-file:
  - internal-v1.0-swagger.json
  - public-v1.0-swagger.json
```
Then I got the following error message:

`FATAL: Error: No unique 'title' across OpenAPI definitions: 'My API - Internal Endpoint - 1.0', 'My API - Public Endpoint - 1.0'. Please adjust or provide an override.`

if I check the loader logic those titles need to match in order be processed:
https://github.com/Azure/autorest/blob/061fa49a3419ae960e39cc83f1518e66b38a002e/src/autorest-core/lib/pipeline/swagger-loader.ts#L353
Whereas the exception tells me they need to be unique

If you need more information let me know cheers

**Comment by olydis** [comment]
Whoopsy, thanks for noticing! Will be fixed with next release. 🙂
