### ISSUE TITLE
Add swagger extension for constant values

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#281]
Hardcoded valueless query string in the path spec.  For example: We have this kind of uri: {BaseUri}/jobs/{jobId}?enable&api-version={version}

**Comment by stankovski** [comment]
Need to add a swagger extension like “x-ms-const” to schema and parameter. It should also support $UtcNow for DateTime.Now.

**Comment by markcowl** [comment]
$UtcNow should not be required client side. 

I worry about adding an extension that seems to be designed for a single case. 

Also, in this case, it's not a constant value for a query parameter, it's actually a constant string at the beginning of the query string.  To see the difference, I'm not sure:
```
{BaseUri}/jobs/{jobId}?enable=&api-version={version}
```
would be accepted. In http 'query' is just a text string, but in swagger, the intent is clearly for following the formData parameterName=parameterValue convention.  If we need to support this, we should either consider allowing replacement of the entire query string with a single string parameter (which would allow for anyone who is not properly using the swagger convention, like this), or if we can identify some convetion that a lot of clients are using that is not the formData convention, then we should consider an extension.

**Comment by stankovski** [comment]
This should be implemented without extensions by relying on enum element. If it contains one value - it is a constant.
