### ISSUE TITLE
Test httpClientFailure_head429 is broken

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2811]
In [httpinfrastructure](https://github.com/Azure/autorest.testserver/blob/master/swagger/httpInfrastructure.json) there is a test with op ID httpClientFailure_head429 that continuously returns 429; this test is broken as it should eventually return something other than 429.  Ideally this would be split into at least two tests, one that returns 429 along with Retry-After and one that doesn't so that SDK-specific waiting between retries can be exercised.  After some amount of iterations the test should return e.g. 200 so that it terminates.

**Comment by olydis** [comment]
Is this related to the LRO tests that Abhijeet recently fixed? https://github.com/Azure/autorest.testserver/pull/44

How did we deal with this so far? :D

**Comment by jhendrixMSFT** [comment]
No this is different.  @amarzavery and I were looking into this today, it appears that most SDKs don't continuously retry on a 429 (in fact a lot of them don't retry at all :()

**Comment by olydis** [comment]
smooth 👍
