### ISSUE TITLE
Feature: "Deprecated" operations, parameters, properties and types

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2812]
### Story

Howdy fellow generator owners! One of our next milestones in providing awesomeness to our customers is a ***good deprecation story***; so RPs have a way to at least warn about removing stuff, ideally long before they do so - AutoRest core also has a new mechanism to create dummy/forwarding properties/types/operations in order to factor out wire breaking changes entirely, but let's start somewhere. 

#### First and foremost: Reference autorest.common >= 2.3.39 and autorest.modeler >= 2.3.47

In your generators, you'll find a property `Deprecated` and `DeprecationMessage` on `ModelType`, `Property`, `Parameter` and `Method`. If your language has a native notion of deprecation, use it, otherwise do the best you can (e.g. prominent display of the `DeprecationMessage` in the inline docs). You are guaranteed that `Deprecated == true` exactly if `DeprecationMessage != null`, i.e. there is a deprecation message exactly if an entity is deprecated - *use that message* and do not come up with your own messages! If the messages I give your generator suck, I'd be happy to adjust them.

Related: https://github.com/Azure/autorest/issues/1285

### Testing

[Here](https://github.com/Azure/autorest/tree/master/Samples/test/deprecated) is a everything-covering test Swagger. You generate correct code if:
- all things having "no" in their name are not marked as deprecated in your code
- all things having "yes" in their name are deprecated in your code
- all things having "custom" in their name are deprecated in your code, but with a custom message saying something about "2005"
- all things having "replace" in their name are deprecated in your code, but with a message pointing people towards the "no" entity

# PLEASE track your progress below

#### C#

- [x] methods
- [x] types
- [x] properties
- [x] parameters

#### Go

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### Java

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### NodeJS

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### PHP

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### Python

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### Ruby

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

#### TypeScript

- [ ] methods
- [ ] types
- [ ] properties
- [ ] parameters

**Comment by olydis** [comment]
done in C# via https://github.com/Azure/autorest.csharp/pull/58

**Comment by lmazuel** [comment]
@olydis I did that in October 2017:
https://github.com/Azure/autorest.python/pull/16
I think it's covering `Method` at least, could you confirm? Thanks!

**Comment by olydis** [comment]
@lmazuel confirm 🙂 Method deprecation was already part of AutoRest since I'm here, just wanna make sure every language supports it - together with the new stuff

**Comment by marstr** [comment]
Delegating my assignment over to the very capable @jhendrixMSFT and @vladbarosan.

**Comment by amarzavery** [comment]
For node.js jsdoc supports [@deprecated](http://usejsdoc.org/tags-deprecated.html) annotation with a free form message.
Deprecation can have two flavors and we should provide a mechanism to express that correctly in the swagger spec. This will enable the docs team to represent information correctly on the docs website
- this thing is deprecated forever
- this thing is deprecated and replaced by something else

**Comment by vladbarosan** [comment]
Removing Go as we have a fix available in the generator that will go in with the next release.

**Comment by olydis** [comment]
@vladbarosan Please check the boxes in the main issue then, making sure you guys support deprecation of all 4 entities.

**Comment by vladbarosan** [comment]
@jhendrixMSFT not sure about parameters. we don't explicitly document parameters in Go. Not sure how we would mark a parameter as deprecated in an idiomatic fashion.

**Comment by dpwatrous** [comment]
Is there a reason this was closed? Deprecation warnings are an extremely important tool to communicate what parts of the API users can rely on, and to help them avoid unexpected breakages on upgrades.
