### ISSUE TITLE
Autorest as REST service?

### ISSUE THREAD

**Issue by tiwari-abhishek** [Azure/autorest#2818]
Is it possible to run Autorest as a REST service? Basically I dont want to manually run the CLI command to generate code but rather automate it through a webapi. That would enable me to to call a webapi from C# code which can spwan an autorest process per request using the provided Swagger JSON and give back the client code as zip or a stream. Is that possible?

If this was a nuget I could add it as a dependecy and use it within a webapi but since its a CLI tool I dont know how to host it as a webservice.

Any ideas?

**Comment by fearthecowboy** [comment]
So, the core of AutoRest is written in TypeScript and some of the plugins are written in c# -- the core does have an interface that can be used from an application, but you'd have to write it for nodejs at the moment.

Doing that (in nodejs, so, javascript or typescript) is actually kind of easy; you take a dependency on the autorest package, and in like 5 lines, you can use autorest to generate code.

If you'd like to do that, I can write a small sample to show you how.

**Comment by tiwari-abhishek** [comment]
Absolutely, it would help if you can provide me with a sample.

**Comment by amarzavery** [comment]
It is super simple to create a web service in node.js using express.js. All you would have to do is use `process.exec('autorest ....')` get the output, zip it and send it back.

**Comment by fearthecowboy** [comment]
@amarzavery  EEEEW! AutoRest is designed as a library to avoid that very model!

@tiwari-abhishek  -- I'm just finishing up some high-priority work, I'm adding this into my todo list for this week.

**Comment by zikalino** [comment]
@tiwari-abhishek i think i am right now implementing something a bit similar:
- i have created a docker container with my entire toolchain.
- travis ci picks up changes from repo A, updates and runs autorest in the container and
- creates pr to another repo B with autogenerated files

**Comment by andreperegrina** [comment]
This could be very useful
