### ISSUE TITLE
Timespan/duration support

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#282]
Timespan/duration support, batch REST API have some operations with request/response body include some fields are timespan format (ISO 8601).

**Comment by brjohnstmsft** [comment]
+1 on this. Search has a TimeSpan property too.

**Comment by markcowl** [comment]
We should support this as an extension format for type 'string'  this way, generic swagger processors will still parse correctly.

**Comment by brjohnstmsft** [comment]
Related PR: https://github.com/Azure/autorest/pull/369

**Comment by matthchr** [comment]
@devigned This is now added.
