### ISSUE TITLE
Autorest should support "format": "password"

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/autorest#2829]
`"format": "password"` is a valid format in [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types). It would be good to have this type (as a metadata) in some cases. For example, when we need to display models in UI, print to console, etc.

For example, in C# may use `SecureString` or an attribute, something like `[SecureStringAttribute]`.

**Comment by MiYanni** [comment]
`Credential` is added to our deduplicator at https://github.com/Azure/autorest.modelerfour. Closing.
