### ISSUE TITLE
Specifying Content-Length with stream request bodies

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest#2831]
I'm wondering how Swagger authors and generators should describe requirements around Content-Length in their APIs. The standard InputStream type in many languages does not tell you the length of the stream but the server may require a Content-Length header. In other cases, it's acceptable to omit Content-Length and use Transfer-Encoding: chunked instead.

After discussion with @fearthecowboy it's sounding like it's not the right move to ask Swagger authors to specify a Content-Length parameter. Rather, the generator should decide if such a parameter needs to be added synthetically, or it can reference its own "wrapped" stream type that has a length parameter on it. Perhaps if the Swagger DOES specify Transfer-Encoding: chunked as an optional header parameter then such a generated Content-Length parameter can be elided or marked optional.

Am I missing anything? Is the right way forward to simply add the Content-Length parameter in the particular language's generator/runtime? Thanks for any perspective you may have on this.

**Comment by fearthecowboy** [comment]
Sorry about the delay on this; I finally am done with the P0 blockers.

I went back and looked at the C#, and we're definitely not doing anything to help out `content-length` at this point at all.

Given that streams tend not to have length associated with them, I'm actually looking to err on the side of, "Lets not, while we don't have a solution".

The trouble with "TE:chunked" is that a lot of language runtimes hide that from the developer ever doing anything other than asking for it in the runtime.  IIRC, Ruby has dodgy support, C# it works, but only if you say "sure, do it" and close your eyes.

Do we have a concrete case that actually absolutely requires content-length sent to the server?

**Comment by RikkiGibson** [comment]
Blob Service's Put Blob requires a Content-Length.
https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types

**Comment by fearthecowboy** [comment]
$.50 says that it's not actually "required."

@jhendrixMSFT  - Do you recall doing *anything* with content-length for storage blob?

**Comment by jhendrixMSFT** [comment]
Yes it's a required header, the value will depend on the type of the blob though.

**Comment by RikkiGibson** [comment]
If you don't include it for a BlockBlob upload the Java runtime produces this error:
```
Status code 411, "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

If you then pass `Transfer-Encoding: chunked` you get:

```
Status code 411, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>MissingContentLengthHeader</Code><Message>Content-Length HTTP header is missing.
RequestId:(...)
Time:(...)</Message><HeaderName>Content-Length</HeaderName></Error>"
```

**Comment by RikkiGibson** [comment]
On the Java side it looks like we'll settle with simply generating an extra Content-Length parameter when a stream request body is present because it's not easy to get the length of our stream type. We will probably not handle `Transfer-Encoding: chunked` until a service comes along which really needs it.
