### ISSUE TITLE
Documentation generator from swagger yaml/json specification which uses autorest extensions.

### ISSUE THREAD

**Issue by pareshverma91** [Azure/autorest#2833]
Is there a documentation generator or a swagger-ui like interface for swagger specification that is using autorest specifications? Using something like swagger-ui is difficult because say if the specification is using autorest specific properties, like x-ms-discriminator-value which changes the generated model object, the the object will show up differently when swagger-ui is used directly.
We have adopted autorest for code generation for our Microsoft internal project, and were wondering if an autorest documentation generator exists.

**Comment by olydis** [comment]
I checked with the team, we unfortunately do not have a dedicated usable tool for that... so in an automated fashion, the only thing I could come up with in your case is pulling out the C# documentation with existing tools - but then you get documentation for the C# client, not really the API. But at least `x-ms-` stuff will be "compiled" into meaningful things.

**Comment by olydis** [comment]
Will close since the answer to your question is "no" - but feel free to ask more questions in here, we'll gladly try to help!
