### ISSUE TITLE
Autorest generating azure resource schema which is deemed invalid by resource schema validators

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2839]
Azure resource schema PR: https://github.com/Azure/azure-resource-manager-schemas/pull/396 
Swagger spec PR: https://github.com/Azure/azure-rest-api-specs/pull/2208

The mentioned schema is generated after mentioned PR was merged. Azure resource schema validation tools are marking them as invalid schemas:
E.g. `$ref '/definitions/Microsoft.Sql/servers/databases'` is not getting resolved but the definition is clearly present there (file: https://github.com/Azure/azure-resource-manager-schemas/pull/396/files#diff-99ff29d4da619b433be1576a768a6020). Similar errors are coming for definitions which are direct json nodes as `Message: Could not find definition "definitions/Microsoft.ClassicCompute/virtualMachines`.

I clearly see a big disconnect between schemas generated from here and schema validator tools being used there. Also neither schema generator nor schema validator is adhering to JSON pointer guidelines which says if `/` is part of key then it should be escaped with `~1` and vice versa (https://tools.ietf.org/html/rfc6901#section-3). 

cc @Tiano2017

**Comment by olydis** [comment]
@DheerendraRathor huh that schema looks weird indeed, you're right about `~1`, not sure why the generator even picks a name like `definitions/Microsoft.Sql/servers/databases` in the first place - haven't seen that in other generated schemas so far. Will investigate.

**Comment by olydis** [comment]
Ha, seems like we actually fixed that recently - the key is to not use "x-ms-discriminator-value" as the freakin' type name... `AzureSqlProtectedItem` is the correct name for `definitions/Microsoft.Sql/servers/databases` - discriminator values aren't even guaranteed to be unique across a spec!

Can you add `"--use=@microsoft.azure/autorest.azureresourceschema@preview"` to your command and see if that generates a better schema? If so, I think we can release that generator as stable 🙂
