### ISSUE TITLE
Plans to support JSON-Schema 

### ISSUE THREAD

**Issue by hartmannr76** [Azure/autorest#2852]
I noticed that there is some similarities to this and the the [Azure Resource Schema](https://github.com/Azure/autorest.azureresourceschema) but out of curiosity I tried having the tool run with a plain JSON Schema (draft 4) resource similar to the one you can find [on the README of this repo](https://github.com/RSuter/NJsonSchema) and it was throwing an error "is not a valid OpenAPI 2.0 definition".

I'm just curious if there are intentions on generating code from resources like this as well. Not all messages may be transported via REST or HTTP for that matter and it would be cool to support messages that may be documented in this way as well with a single tool.

**Comment by olydis** [comment]
100% agree! We're thinking about supporting other forms of input in general for a while now (e.g. OpenAPI 3.0), but unfortunately, it's not a priority so far. So yes, there are intentions, but our planning for this year does not include work in that space so far. 🙁 I could imagine a light-weight layer in our pipeline that's simply transforming JSON schema into an as-good-as-possible Swagger spec (with only `definitions`, no operations). Maybe creating a little tool like that does that right before calling AutoRest would be a short-term solution, long term, we'd gladly consider absorbing that code into AutoRest - external contributions are always appreciated 😉
