### ISSUE TITLE
Request to support setting of serialization and deserialization settings

### ISSUE THREAD

**Issue by kalyanaj** [Azure/autorest#2856]
This is a request to support customization of serialization and deserialization settings in the generated classes. Currently, the setter is not public and hence developers who want to customize the serialization/deserialization settings cannot override the default settings.

**Comment by olydis** [comment]
@kalyanaj note that you can simply implement the partial method [`CustomInitialize`](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Network/Management.Network/Generated/NetworkManagementClient.cs#L455) and modify (de)serialization settings as you wish! This is the intended extension point for service teams.
