### ISSUE TITLE
Flattening discrepancy between "vanilla" autorest and "azure-arm" 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2860]
Hello,

These two commands:

> AutoRest --python --clear-output-folder --output-folder=test/vanilla/Expected/AcceptanceTests/ModelFlattening --license-header=MICROSOFT_MIT_NO_VERSION --enable-xml --basic-setup-py --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/model-flattening.json --python.payload-flattening-threshold=1

> AutoRest --python --clear-output-folder --output-folder=test/azure/Expected/AcceptanceTests/ModelFlattening --license-header=MICROSOFT_MIT_NO_VERSION --enable-xml --basic-setup-py --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/model-flattening.json --python.azure-arm=true --python.payload-flattening-threshold=1

Does NOT generate the same code for operation `putSimpleProductWithGrouping` ([Swagger](https://github.com/Azure/autorest.testserver/blob/master/swagger/model-flattening.json)). And the azure one is completely broken.

Looking in debug mode, the `InputParameterTransformation` I get is not the same:

vanilla:
![image](https://user-images.githubusercontent.com/1050156/36867122-11c1bd56-1d49-11e8-80ff-01d80e52d565.png)

azure:
![image](https://user-images.githubusercontent.com/1050156/36867142-21b6fc6c-1d49-11e8-82f6-ae4d10a145cb.png)

It turns out that the difference is created by [this call](https://github.com/Azure/autorest.python/blob/31de457961e821756ad99a890dadc34a077aacc1/src/azure/TransformerPya.cs#L34) in the Azure Python Transfomer:
`ParameterGroupExtensionHelper.AddParameterGroups(codeModel);`

When I removed it, everything works well (test server included...). After a few search, only Python and [Java](https://github.com/Azure/autorest.java/blob/4df275f858a158c98a224d2044f9d2be664a2cb8/src/azure/TransformerJva.cs#L44) are using this method. And for Python this breaks azure flattening in some cases...

@olydis @fearthecowboy Seems to me the best fix is to remove this call that I don't know why it's there, and anyway breaks stuff. But if you know what it's supposed to do, and why I might want to use it please let me know :)

(don't ask me why I generate this vanilla file using arm, I have my reasons :p)

**Comment by lmazuel** [comment]
@annatisch if it rings a bell

**Comment by olydis** [comment]
huh, not sure about details, but agree 100% with @annatisch, no reason for a difference IMO. Note that `AddParameterGroups` is also part of [NormalizeClientModel](https://github.com/Azure/autorest.common/blob/0e4b65a95724459720ec227becb2f86018019401/src/SwaggerExtensions.cs#L43) and [NormalizeAzureClientModel](https://github.com/Azure/autorest.common/blob/54c21aff3bf9dbae3b0bd12271d8271d7064cbff/src/AzureExtensions.cs#L78), which is also called by C#, so not sure why it breaks in Python (maybe wrong order of calls or called twice, ...)

**Comment by lmazuel** [comment]
Ok, so definitely this is called twice, since Python is calling `NormalizeClientModel` as well.
I will comment it for now, with this issue number so we remember it if something weird appears in the future.
Thanks!
