### ISSUE TITLE
New versions break Default BaseUri (CSharp)

### ISSUE THREAD

**Issue by giperFox** [Azure/autorest#2862]
Similar to the issue 2746 (https://github.com/Azure/autorest/issues/2746)

Autorest version: 2.0.4245

As in the original bug, the root class has a method:
`private void Initialize()`
Where the last versions of autorest set BaseUri within the relative path:
`BaseUri = new System.Uri("/SomeService.Api.Services/SomeService");`
Previously it was:
`BaseUri = new System.Uri("http://localhost/SomeService.Api.Services/SomeService");`

System.Uri constructor expect the absolute path and as a result throw next error: `System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.'`

PS: I'm calling the clients constructor providing baseUri, but it still call `Initialize` using the default one.

**Comment by olydis** [comment]
@giperFox could you provide a small repro (Swagger)? The version you're using should indeed contain the fix performed for #2746, so it would be nice to see what causes the issue in your case 🙂

**Comment by giperFox** [comment]
@olydis please find swagger file attached. Together with swagger.json in the package you can find two auto-generated C# clients (version 2.0.4245, and 2.0.4147). The cause of the issue is similar to the #2746, but not the same, so probably the previous fix does not cover this particular case.
[SwaggerAutoRest.zip](https://github.com/Azure/autorest/files/1799455/SwaggerAutoRest.zip)

**Comment by olydis** [comment]
@giperFox Thanks! Will fix with upcoming release, you can unblock yourself by specifying a `host` until then, of course.

**Comment by pekkah** [comment]
For me this got fixed by setting the host in Swashbuckle. By default it didn't get set.

**Comment by giperFox** [comment]
@pekkah, @olydis - thank you for your answers, setting the host work as a temporary solution, though I do not need it for my application directly. As @olydis mentioned - waiting for the next release with the proper fix.

**Comment by vnikiti** [comment]
This is not fixed still. Host needs to be configurable in consume. Hard coding host into client path is non-sense. I wish I never had to use it. Microsoft has not changed since 2000s, issues are getting closed when they are not!
