### ISSUE TITLE
Should command line args override readme settings?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest#2869]
This readme: https://github.com/azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/readme.md#java

when generated with command 
```
Command: autorest ---version=latest /Users/jianghlu/Documents/code/azure-rest-api-specs/specification/authorization/resource-manager/readme.md --java  --azure-arm --fluent --namespace=com.microsoft.azure.management.graphrbac  --java.output-folder=/Users/jianghlu/Documents/code/azure-libraries-for-java/azure-mgmt-authorization  --license-header=MICROSOFT_MIT_NO_CODEGEN  --payload-flattening-threshold=1 --tag=package-2018-01-01-preview
```

generates code in `com.microsoft.azure.management.authorization` namespace. Should it be in `com.microsoft.azure.management.graphrbac` namespace?

**Comment by fearthecowboy** [comment]
because of the order that things get applied, if the value is in a category in the readme:

``` yaml
java:
  namespace: com.microsoft.azure.management.authorization
``` 

you have to override it on the command line with the same prefix category:

`--java.namespace=com.microsoft.azure.management.graphrbac`

**Comment by olydis** [comment]
@jianghaolu Closing assuming this is resolved. Reopen otherwise.

**Comment by jianghaolu** [comment]
Works like a charm. Thank you!
