### ISSUE TITLE
Modeler should fail when duplicate header response types don't match

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2880]
Consider the following snippet.
```json
        "responses": {
          "200": {
            "description": "Returns the content of the entire blob.",
            "headers": {
              "Content-MD5": {
                "type": "string",
                "format": "byte",
              }
            },
            "schema": {
              "type": "object",
              "format": "file"
            }
          },
          "206": {
            "description": "Returns the content of a specified range of the blob.",
            "headers": {
              "Content-MD5": {
                "type": "string",
              }
            },
            "schema": {
              "type": "object",
              "format": "file"
            }
          }
        }
```
Since the OpenAPI spec doesn't allow the use of $refs for header responses the response types must be duplicated.  Here the format specifier is missing for the 206 response.  As a result, the format specifier is lost during operation building, see OperationBuilder.BuildMethod() [here](https://github.com/Azure/autorest.modeler/blob/master/src/OperationBuilder.cs#L123).  Since we cannot use $refs the modeler should ensure that the definitions match and if they don't it should fail.

**Comment by jhendrixMSFT** [comment]
Or if there's a way we can switch to using $refs and eliminate the need for duplication that would be a better fix.

**Comment by fearthecowboy** [comment]
Well... we actually did add support to use $refs ...since the alternative was painful. 

https://github.com/Azure/autorest/tree/49f63f33ef98cc9e300675e62d5183a69728e059/Samples/test/shared-response-header-types

**Comment by jhendrixMSFT** [comment]
Interesting, I didn't see this extension in the documentation.  This might be sufficient, let me play around with it.  Per the example it looks like you can only ref a set of headers yes?

**Comment by fearthecowboy** [comment]
I think so. IIRC, we did this because of the massive duplication in the storage spec.
