### ISSUE TITLE
None of the Autorest Samples have content

### ISSUE THREAD

**Issue by RedBlue1776** [Azure/autorest#2891]
All of the .cs files in the link below are missing content.  

In all cases Line 1 == "SRC"

https://github.com/Azure/autorest/tree/master/Samples

**Comment by fearthecowboy** [comment]
As Designed.

The sample *outputs* that are checked in are just a part of our CI validation (we don't validate changes to the generated code in this project, it's done in the actual generator tests). 

The samples are there for illustration purposes for inputs/configuration. If you want to see the outputs, clone the repository and just run autorest in the folder where the sample is.
