### ISSUE TITLE
not able to solve the json problem.please help me

### ISSUE THREAD

**Issue by Akansha999** [Azure/autorest#2895]
below is my code-
JObject allJsonData = new JObject();
            var tempData = CallRestApi(url, "GET", conn.sessionID, conn.xApiVersionString);
            var dictKeys = tempData.Properties().Select(p => p.Name).ToList();
            if (dictKeys.Contains("total") && dictKeys.Contains("count"))
            {
                var tempDataTotal = Int32.Parse(tempData["total"].ToString());
                var tempDataCount = Int32.Parse(tempData["count"].ToString());
                if (tempDataTotal == tempDataCount)
                    return tempData;
                List<JToken> dictDataList = new List<JToken>();
                foreach ( var eachDict in tempData["members"])
                    dictDataList.Add(eachDict);
                var perPageCount = (tempDataCount < tempDataTotal) ? tempDataCount : tempDataTotal;
                int loopCount = (int)Math.Ceiling((double)tempDataTotal / (double)tempDataCount);
                allJsonData = tempData;
                for (int i = 1; i < loopCount; i++)
                {
                    var tempMembers = CallRestApi(url + "?start=" + (i * perPageCount).ToString() + "&count=" + perPageCount.ToString(), "GET",
                        conn.sessionID, conn.xApiVersionString)["members"];
                    foreach (var myDict in tempMembers)
                        dictDataList.Add(myDict);
                    allJsonData["members"] = (allJsonData["members"].ToString() + "," + tempMembers.ToString());
                }
                allJsonData["count"] = tempDataCount;
                allJsonData["members"] = JObject.Parse(allJsonData["members"].ToString());
getting error in line- allJsonData["members"] = JObject.Parse(allJsonData["members"].ToString());
error-"error reading Jobject from jsonReader.current jsonreader is not an object.Statrarray,Path"line1,position 1

**Comment by fearthecowboy** [comment]
Um. You need to find some general programming help page somewhere.
