### ISSUE TITLE
Support for strongly typed header values on error responses

### ISSUE THREAD

**Issue by rickle-msft** [Azure/autorest#2900]
When specifying a default response in the swagger, I noticed that headers that are defined as part of that response are currently added as properties to the normal response object, but it seems like they should probably be properties on the generated exception in the same way that properties of the inner schema are properties of the exception. 
I've included a zip of a json file that can reproduce the issue as well as the code generated off the included swagger. I included generated Go files, but the same issue appears in Java, which suggests that this could be an issue with the modeler. 

Thanks for your help!

[Go_BlobStorage.zip](https://github.com/Azure/autorest/files/1909691/Go_BlobStorage.zip)

**Comment by fearthecowboy** [comment]
Hmm. 

I think that we've got a fundamental design flaw that happened a couple years before I even got involved.

With the current modeler design, on a given operation, you basically get one or two return objects; the class that represents the 'body' and a class that represents the 'headers'.  The 'body' result class is used as a result for the generated function, and when headers are specified, a tuple of sorts is used.  

If there are multiple response codes which infers multiple response types, the function ends up returning the most common base class (if the types are not related, that ends up being 'object') ... for the header, I believe that it just merges all the definitions to make a common model that supports the aggregate sum of headers.

These are not ideal.

Fixing this in the scope of the existing modeler/generators is not likely possible, and the only workaround at this point is to craft some convenience methods that work the way you want it to.

The good news, is that I'm working on a whole new generation of modeler and generator right now, that doesn't have this limitation -- at the lower level, the generated API calls have callbacks for each possible output and aren't restricted to a common return type (and result models are enhanced with header properties that are returned from operations where they are involved in)  The new pattern would totally resolve this issue.

**Comment by rickle-msft** [comment]
Alright well we will investigate some other way of exposing this to the customer while we wait for the new generator. 

What comes to mind right now is not including the errorCode header in the swagger since that would likely confuse customers examining properties on a successful response and finding some way to wrap the generated exception in our own exception type that neatly exposes this header to the user. Does that seem like a reasonable solution? The downside is that our swagger doesn't capture this header at all.

**Comment by fearthecowboy** [comment]
Wait -- are the response header properties only showing up available on the non-`default` response?  (ie, not showing up on error cases) or are they on both?

**Comment by fearthecowboy** [comment]
I can give you a configuration `directive` to specifically delete the properties where they aren't wanted. Would that suffice?

**Comment by rickle-msft** [comment]
They are only showing up on the non-default response. 

I think if we are able to specify the header in our swagger but not generate off it with this directive that would be very helpful. Then we can just change the configuration when the code generation works and we don't have to change our swagger again.

**Comment by RikkiGibson** [comment]
We're still seeing the headers defined only on the error response show up in the CompositeType in CodeModel.HeaderTypes, merged with the headers on the success response. Is a configuration directive still the suggested way to handle this?

I think in the specific case of Storage, a catch block that parses the error headers manually might be reasonable, but @rickle-msft and @XiaoningLiu may want to chime in on this.

**Comment by rickle-msft** [comment]
This is still what the Java client is doing. It would be nice to have it totally handled by Autorest, but the workaround hasn't presented any problems.
