### ISSUE TITLE
What do you mean by RESTful

### ISSUE THREAD

**Issue by enemyofthedawn** [Azure/autorest#2902]
> The AutoRest tool generates client libraries for accessing RESTful web services

I read few things and I realized that most web apis are not restful at all.

https://devblast.com/b/calling-your-web-api-restful-youre-doing-it-wrong

How autorest code gen deal with things like HATEOAS, I don't understand it.

**Comment by fearthecowboy** [comment]
What?

**Comment by enemyofthedawn** [comment]
@fearthecowboy I don't know, you tell me.
