### ISSUE TITLE
Cannot use autorest as a library

### ISSUE THREAD

**Issue by vladbarosan** [Azure/autorest#2903]
When running an app with autorest as a library I am getting the following error.

```
Unhandled Promise rejection: Package '@microsoft.azure/autorest-core' - '2.0.4275' failed to install:
  Cannot convert a Symbol value to a string ; Zone: AI-|8C63F91E-DE79-4D22-8F62-FB199D7B8314. ; Task: Promise.then ; Value: { Error: Package '@microsoft.azure/autorest-core' - '2.0.4275' failed to install:
  Cannot convert a Symbol value to a string
```

**Comment by vladbarosan** [comment]
@fearthecowboy thanks for the quick reply.

So I was doing `autorest --help` as a subprocess but it doesn't seem to be enough. To make sure I understnad I need to do `autorest --reset --help` + any plugin I need to use ?

**Comment by vladbarosan** [comment]
also can I use the latest version of autorest or should I stick to 2.0.4272 ? ( Johannes mentioned at one point to stick to that one for a while )

**Comment by vladbarosan** [comment]
sorry I think it was 62

**Comment by fearthecowboy** [comment]
You need to specify the plugins too (that'll actually install the plugins). 

The latest *probably* works, but you might as well stick with `@2.0.4272`  (aka `@preview`)

**Comment by vladbarosan** [comment]
because of the classic validator had to install also `libunwind8` aah. 

Either way, it worked thanks. If you want you can keep the issue open to track the workaround.

**Comment by scott-lin** [comment]
> When running an app with autorest as a library I am getting the following error.

@fearthecowboy answered this same question in https://github.com/Azure/autorest/issues/2896, so thought I'd echo the solution here on his behalf.

Call initialize with the path to autorest-core before using AutoRest in any other way. No need to go with the command line mitigation then.

```
// The initialize function
export async function initialize(requestedVersion: string = "latest-installed", minimumVersion?: string) 

// should be able to use :
await initialize( "/path/to/node_modules/@microsoft.azure/autorest-core")
```

**Comment by vladbarosan** [comment]
@fearthecowboy we will be trying to update to the latest version of autorest. does running the autorest command before using it as a library still the recommended workaround or using the workaround @scott-lin  mentioned, namely to call `await initialize( "/path/to/node_modules/@microsoft.azure/autorest-core")` ?
