### ISSUE TITLE
Unalbe to set Storage_URI to null once enabled on boot_diagnostics on VM

### ISSUE THREAD

**Issue by VaijanathB** [Azure/autorest#2908]
Here is the scenario, 
1) User creates a VM with boot_diagnostics enabled
2) User disables boot_diagnostics and deletes the Storage Account. 
3) When we send  the following json blob in the VM payload we expect the server to update the Storage_URI to null. 
"diagnosticsProfile": {
       "bootDiagnostics": {
        "enabled": false,
        "storageUri": ""
    }
},
4) Even though the boot_diagnostics is disabled, the storage_uri variable still has the old value which is returned to the user in the GET api.  This is an issue and needs to be fixed.

**Comment by fearthecowboy** [comment]
How is this an AutoRest issue?

**Comment by VaijanathB** [comment]
Sorry meant to ope it on azure-rest-api-specs. Closing this issue.
