### ISSUE TITLE
Inconsistent case sensitivity behavior of $ref file path resolution

### ISSUE THREAD

**Issue by mentat9** [Azure/autorest#2914]
Autorest resolves JSON references to external files using different casing rules for the file path, depending on the method it uses to find/read the input file. Running Autorest against a local repo on my dev box resolves $ref of a file as case INsensitive on the path, but when it runs against the same file in the corresponding remote (GitHub) repo, it resolves that same $ref as case SENsitive on the path of the same file. This causes difficult-to-understand failures that can only be detected/repro'd after changes have been pushed to the remote repo. This is a bad tool bug, IMO.

**Comment by marstr** [comment]
This issue is a result of Azure/azure-rest-api-specs#3032, but has been a problem for me as a reviewer in a few other PRs.

**Comment by fearthecowboy** [comment]
ROFL. Welcome to Windows 😄 

>This is a bad tool bug, IMO.

Unfortunately, kinda tricky to resolve neatly, given that if I as for `FOO.JSON` on windows and the filesystem has `foo.json` it returns me the file just fine and dandy. To prevent that, every file open would have to be preceded by a enumerate files and filter (which can't be done on `https://` references)

**Comment by mentat9** [comment]
Thanks for looking at this @fearthecowboy. Thing is, that doesn't help. The way I read your response, you've identified the issue as a design bug instead of a coding bug, which I agree with. But the category of the issue doesn't really matter to people using the tool. Maybe the right fix is to get GitHub to support case insensitive repo access (are we sure they don't? Not supporting it seems like a bug farm). A simpler option that's not a fix, but is worth considering: a [informational/warning/error] message if the item returned by the local file system doesn't match the case in the JSON. Windows file systems preserve path case even though they are case insensitive, so this would be a big clue to help prevent later problems. Thanks again for your consideration.

**Comment by fearthecowboy** [comment]
Websites are generally by default case-sensitive. The exception to that is Windows/IIS ; primarily because the filesystem is case insensitive. 

Github won't be making the repository access as case-insensitive, all other platforms other than Windows are not case-insensitive -- doing so would break them.  

>  simpler option that's not a fix, but is worth considering: a [informational/warning/error] message if the item returned by the local file system doesn't match the case in the JSON

Without enumerating the parent folder's contents prior to opening the file, there is no way to know the actual filename from the filesystem read call. To do so on every file read request would extraordinarily painful. 

FYI - this affects virtually every language ever created that works cross platform.  In C, if you `#include "SomeFile.H"` -- on Windows, that will pick up any file that matches case insensitively. On every other OS, it will fail to find `Somefile.h` because the case does not match.

**Comment by mentat9** [comment]
At the risk of belaboring the point, I'd like to make one last appeal. I agree this problem stems from different casing rules between different file providers. The core problem is an artifact of GitHub and/or git which joins systems with different filename casing rules into a distributed SCCS. I'm sure this creates many other pitfalls, including the likelihood that other language tools might manifest a similar problem. It's worth pointing out that the aggregate SCCS is actually logically case insensitive if any part of it stores files case insensitively. I don't claim to understand all of the nuances of how GitHub and/or git deal with that fact. Regardless, I think it's worth considering generally how we can make this highly-connected-and-heterogeneous distributed computing world work better for all of us.

To detect a case mismatch on a Windows file system, you don't need to enumerate the parent folder's contents. You only need to enumerate the parent folder for files whose names start with the given name. In most situations, exactly one (or no) file(s) will match. For example: if the JSON $ref-erences a file name xyZzy.jsOn, but a file exists with name xyzzy.json, you can retrieve files matching xyZzy.jsOn*, and you will most likely get back just that one file. Even if there happen to be a few additional matching files, the desired one will be the only one whose name is the same length. At that point, a case sensitive string compare gives you the information you want. I've seen extraordinarily painful, and that isn't it.

Thanks for reading. I'll stop bugging you now.
