### ISSUE TITLE
Q: Multiple response schemas

### ISSUE THREAD

**Issue by espray** [Azure/autorest#2920]
The Api I am working with has multiple response schemas for 200 OK (see below for response example). I have no control over the Api. Any  recommendations on handling this scenario? 

Success Response - 200 OK
`
{
"QueryResponse": {
  "Date": [
    "Company": {
    }
  ],
  "maxResults": number 
},
"time": "string"
}
`

Error Response - 200 OK
`
{
"Fault": {
  "Error": [
    {
      "code": string
      "message": string
    }
  ]
},
"time": string
}
`

**Comment by fearthecowboy** [comment]
Ah. Ouch. 

They really shouldn't do that. That's not ok.

You'd have to have a response model that has all the fields, and then check the contents on return.

**Comment by espray** [comment]
@fearthecowboy yup not fun

Autorest has `--use-internal-constructors` does it have a similar parameter that can make the operators in the client and extensions internal?
Then I could hide this Ickiness
