### ISSUE TITLE
(node:9672) UnhandledPromiseRejectionWarning: TypeError: volume[member].bind is not a function

### ISSUE THREAD

**Issue by kgreed** [Azure/autorest#2921]
I installed autorest using Chocolatey
Choco install autorest

(I am using WIndows 10 and want to a generate c# sdk)
When I type autorest at a command prompt I see the following

[(`Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>autorest
AutoRest code generation utility [version: 2.0.4262; node: v10.1.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
(node:9672) ExperimentalWarning: The fs.promises API is experimental
Failure:
Error: Unable to start AutoRest Core from C:\Users\kirst\.autorest\@microsoft.azure_autorest-core@2.0.4278\node_modules\@microsoft.azure\autorest-core
Error: Unable to start AutoRest Core from C:\Users\kirst\.autorest\@microsoft.azure_autorest-core@2.0.4278\node_modules\@microsoft.azure\autorest-core
    at main (C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\app.js:232:19)
(node:9672) UnhandledPromiseRejectionWarning: TypeError: volume[member].bind is not a function
    at patchFilesystem (C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:277:43)
    at C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:281:18
    at Object.global.staticloader.undo (C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:163:7)
    at process.exit.n [as exit] (C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:170:27)
    at main (C:\Users\kirst\AppData\Roaming\npm\node_modules\autorest\dist\app.js:239:17)
(node:9672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What should I do?

**Comment by fearthecowboy** [comment]
Node 10 has some weird breaking changes; you should probably downgrade node to the [latest LTS release](https://nodejs.org/download/release/latest-v8.x/)

**Comment by kgreed** [comment]
Thanks
