### ISSUE TITLE
Better validation needed from AutoRest code generators for x-ms-parameterized host

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#2924]
x-ms-parameterized host name provides option to either use scheme prefix or not use it. While this is a great option to provide, it causes confusion to a customer who is consuming the API methods from an SDK.

For ex -  [EventGrid](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventGrid/stable/2018-01-01/EventGrid.json#L8) uses `useSchemePrefix: true` which means the expectation from user is to just provide host name not the url
[KeyVault](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L8) uses `useSchemePrefix: false` expecting the user to provide complete url.

Given the inconsistency in different Azure services, it is easy for users to pass url or hostname incorrectly,

If a user accidentally provides complete url for EventGrid's topicHostName in Node.js,the error we see is `ENOTFOUND: getaddrsinfo https: https 443`. The error message is cryptic and does not provide any help to the user on why he/she is getting the error. Error message in C# is not that helpful either.

It would be great if we can add validation in all code generators that does some thing in the lines of following
- if `useSchemePrefix: true`, and if we see user providing url, then throw an error message that only hostname is expected in this case. complete url will not be accepted or instead of throwing an error, go a step further and just strip the hostname from the url 
- if `useSchemePrefix: false` and user does not provide url, throw an error message that url is expected. 
    - I did not validate this case so not sure what error we see if user does not provide a url.

cc @fearthecowboy, @amarzavery

**Comment by fearthecowboy** [comment]
openapi3 has a different format for this.
