### ISSUE TITLE
What is meant by the magic string?

### ISSUE THREAD

**Issue by kgreed** [Azure/autorest#2928]
I am trying to set up a config.md file to generate my csharp Client SDK.
I have been looking at https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md  which refers to the "magic string" what is that?

**Comment by bkwdesign** [comment]
In your link, it's in the first paragraph under **File Format** heading.. they don't say 'magic' there, but it's a 'must contains' string...

    In order that AutoRest identifies a CommonMark document as a AutoRest Configuration file, the 
    markdown must contain the following string exactly (and not as the first line in the file!) :

    > see https://aka.ms/autorest

**Comment by kgreed** [comment]
Thankyou
