### ISSUE TITLE
Urls Incorrect when BaseUri contains Segments

### ISSUE THREAD

**Issue by OliverRC** [Azure/autorest#293]
The generated code builds the url like this:

    var url = new Uri(this.Client.BaseUri, "/myroute/{id}").ToString();

However this creates incorrect urls if ```BaseUri``` contains segmets for example ```http://somesite/segment1``` the resulting url will drop the ```segment1``` and use the base address only.
The resulting url is therefore ```http://somesite/myroute/{id}```.

This is because the beginning of relativeUri begins with a ```/```

It should be:

    var url = new Uri(this.Client.BaseUri, "myroute/{id}").ToString();

This was introduced in 11.0 as it worked perfectly in 10.0

**Comment by markcowl** [comment]
@OliverRC Thanks for the report assigning appropriately for resolution

**Comment by ttrevorr** [comment]
any update on this? We are experiencing the same bug.

**Comment by hovsepm** [comment]
Fixed in dev branch.

**Comment by OliverRC** [comment]
Nice :)
