### ISSUE TITLE
Formatting in /user/cli.html

### ISSUE THREAD

**Issue by kgreed** [Azure/autorest#2930]
The formatting under Commonly Used Settings looks really strange to me
Is it intentional?

![image](https://user-images.githubusercontent.com/1795966/40812268-486e94ba-6578-11e8-98e7-b019f441dea3.png)

There is a similar issue under Validation
I have tried Chrome and Edge and different computers.

**Comment by olydis** [comment]
lol seems like an inconsistency between GitHub pages (http://azure.github.io/autorest/user/cli.html) and the repo browser (https://github.com/Azure/autorest/blob/master/docs/user/cli.md).
