### ISSUE TITLE
Is there a way to prevent parameter re-ordering for C# codegen?

### ISSUE THREAD

**Issue by cthrash** [Azure/autorest#2940]
The swagger code snippet looks like this:

```
"/recognizeText": {
    "post": {
    "description": "...",
    "operationId": "RecognizeText",
    "parameters": [
        {
        "$ref": "../../../Common/Parameters.json#/parameters/ImageUrl"
        },
        {
        "$ref": "#/parameters/TextRecognitionMode"
        }
    ],
```

In the generated C# the argument order is reversed:

```
public async Task<HttpOperationHeaderResponse<RecognizeTextHeaders>>
RecognizeTextWithHttpMessagesAsync(
    TextRecognitionMode mode,
    string url,
    Dictionary<string, List<string>> customHeaders = null,
    CancellationToken cancellationToken = default(CancellationToken))
```

It appears required parameters are re-ordered alphabetically.  Is there a way to instruct  codegen to honor swagger document order?

**Comment by fearthecowboy** [comment]
It will reorder parameters to make the required ones up front. are all parameters marked required?

**Comment by cthrash** [comment]
`mode` and `url` are both required.

**Comment by cthrash** [comment]
The reason I raise this is because we have an overload, that takes a stream (called `imageStream`) instead of an `url`, plus the 'mode` argument, and for the two overloads to have different position for mode is not great.

**Comment by fearthecowboy** [comment]
O_o ... that ... hmm.

That shouldn't be happening. Can you point me towards/forward me the whole swagger file (alias :  garretts )

There must be another factor at play here.

**Comment by fearthecowboy** [comment]
Update:
Figured out this is because there is parameter flatting happening, and it's less than ideal.

Solution: add a `directive` in the configuration to change the generated code.

~~~ markdown
``` yaml $(csharp) 

directive: 
  from: source-file-csharp
  where: $
  transform: >
    $ = $.replace( /TextRecognitionMode mode, string url,/g, "string url, TextRecognitionMode mode," );
    $ = $.replace( /mode, url,/g, "url, mode," );
```

~~~
