### ISSUE TITLE
AutoRest crash on start (Unable to start AutoRest)

### ISSUE THREAD

**Issue by omerlh** [Azure/autorest#2941]
I installed autorest using `yarn global add autorest`. the installation completed successfully, but when trying to run it (for example, `autorest --help`) it fails with the following error:
```
root@b1063bbd6c8c:/app# autorest --help
AutoRest code generation utility [version: 2.0.4280; node: v10.4.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to start AutoRest Core from /root/.autorest/@microsoft.azure_autorest-core@2.0.4280/node_modules/@microsoft.azure/autorest-core
Error: Unable to start AutoRest Core from /root/.autorest/@microsoft.azure_autorest-core@2.0.4280/node_modules/@microsoft.azure/autorest-core
    at main (/usr/local/share/.config/yarn/global/node_modules/autorest/dist/app.js:232:19)
```
I was able to reproduce it on my mac (running node `v9.5.0`), and on the latest NodeJS docker image.
I tried to google the error - but couldn't find anything helpful. I guess this is an issue with my environment.

**Comment by fearthecowboy** [comment]
Hmm. Seems a bit weird.

Try `autorest --reset` ...

**Comment by fearthecowboy** [comment]
Well, that's at least explaining why it's not working.  It can't install some stuff.

IIRC Node `9.5` had some broken bits in it, you might want to upgrade that to `9.11` or so. I've got `9.11.1` and it works ok.

**Comment by omerlh** [comment]
Great, it worked. It was an issue with node 9.5, worked on 9.11.2
