### ISSUE TITLE
Update testserver to eliminate vulnerabilities

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2942]
We're starting to get reports back about AutoRest modules having security vulnerabilities because the testserver uses an old version of Jade (which uses constatinople 3.0.2, which has a serious vulnerability.)

**Comment by epet** [comment]
specifically, 
"@microsoft.azure/autorest.csharp" & "@microsoft.azure/autorest.modeler"
tracked vulnerability is [https://nodesecurity.io/advisories/568](url)

These are dev dependencies.

**Comment by epet** [comment]
@amarzavery, @fearthecowboy looks like autorest.testserver has been updated to use Pug since jade was deprecated. Can you guys take a bump in version for .csharp and .modeler?

**Comment by epet** [comment]
@amarzavery , @fearthecowboy, modeler probably should get updated first as csharp references modeler and testserver. PR is submitted.
