### ISSUE TITLE
Document AutoRest DataType Formats

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#2949]
It's hard for folks to see that UUID and other formats are supported in AutoRest. There should be better documentation for the format values supported.

Also, the link for AutoRest DataTypes is broken here: https://github.com/Azure/autorest/wiki/valid-formats

/cc @deathly809

**Comment by deathly809** [comment]
I think I found some of the supported formats, might be missing a few though.

[SwaggerObject](
https://github.com/Azure/autorest.modeler/blob/6b63ce8eeaf15b7e51df6daea698c0ef3ff6122f/src/Model/SwaggerObject.cs)
[KnownFormat](
https://github.com/Azure/autorest.common/blob/4b478755f40b54b6cef711d51af9be8a1cd037f2/src/Model/KnownFormat.cs)
[KnownPrimaryType](
https://github.com/Azure/autorest.common/blob/4b478755f40b54b6cef711d51af9be8a1cd037f2/src/Model/KnownPrimaryType.cs)
