### ISSUE TITLE
Some DateTime serialization unit tests are timezone relative

### ISSUE THREAD

**Issue by codespare** [Azure/autorest#296]
Running unit tests locally in AEST time zone, DateTime serialization tests end up with results similar to:

``` bash
autorest\master\ClientRuntimes\CSharp\ClientRuntime.Tests\JsonSerializationTests.cs(250): error : Microsoft.Rest.ClientRuntime.Tests.JsonSerializationTests.DateSerializationWithMaxValue [FAIL] [\autorest\master\build.proj]
              Assert.Equal() Failure
                                            ↓ (pos 45)
              Expected:   "dt": "9999-12-31T23:59:59Z",\r\n  "dn": "9999-12-31T23:59:59
              Actual:     "dt": "9999-12-31T12:59:59.9999999Z",\r\n  "dn": "9999-12-31T
                                            ↑ (pos 45)
```

As you specify a timezone in the test strings, I think you should use DateTimeStyles.AssumeUniversal instead of AdjustToUniversal, otherwise outcome depends on host timezone as there is a conversion to local time.

**Comment by markcowl** [comment]
@codespare Thanks for the report we will take a look

**Comment by devigned** [comment]
Can you try executing these against the dev branch. I think we have solved this as the tests are executing in Travis? I believe has the machine configured to UTC and thus caused these issues to corrected.

**Comment by devigned** [comment]
@codespare if you find this works for you, please ping back.

**Comment by codespare** [comment]
Looking into it in more details, those modifications pass the tests:

**DateSerializationWithMaxValue** with <br>
```
""dton"": """ + new DateTimeOffset(localDateTime).ToString("yyyy-MM-ddTHH:mm:sszzz") + @"""
```
because 'zzz' is local time zone relative for DateTime (but not DateTimeOffset).

**DateSerializationWithoutNulls** with
```
test.Date = localDateTimeOffset.UtcDateTime;
test.DateNullable = localDateTimeOffset.UtcDateTime;
test.DateTime = localDateTimeOffset.UtcDateTime;
test.DateTimeNullable = localDateTimeOffset.UtcDateTime;
```
as I think it is what the test tries to show.

I can't find a fix to **DateSerializationWithNulls** without significant changes though.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
