### ISSUE TITLE
No way of documenting eventual result of long-running-operation

### ISSUE THREAD

**Issue by chgennar** [Azure/autorest#2967]
For any long running operation, there isn't currently a way to document the eventual result.  Is it possible to add a property to [x-ms-long-running-operation-options](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-long-running-operation-options) to specify a definition for the response given by the "Location" or "Azure-Async-Operation" header?

**Comment by fearthecowboy** [comment]
That should be specified in the `200` response.

**Comment by chgennar** [comment]
How would this be done?  The long running POST operation only returns a 202 response in this case.

**Comment by fearthecowboy** [comment]
LRO operations should document a 202 and a 200 response for the terminal state. Precisely for that purpose.

**Comment by chgennar** [comment]
Can you point me to documentation by any chance?  I'm a little bit concerned about specifying a 200 response for an operation that doesn't return 200.

**Comment by deathly809** [comment]
@chgennar If your response never returns a 200 then how will you ever get a response?  

This combined with the link you have for x-ms-long-running-operation says that you need a terminal state in your spec.

https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#R2005

**Comment by chgennar** [comment]
We currently have our Long Running Operations implemented so that the "Location" header in the 202 response contains the link of the final result and not the state.  I think it is becoming clear that this isn't the intended pattern.  Can you confirm?

**Comment by deathly809** [comment]
The Location is what you retry on.  Usually what happens is that Location points to somewhere that returns 200.  From what I have usually seen is that Location never changes.

**Comment by chgennar** [comment]
@deathly809 Great, thank you!

**Comment by harouny** [comment]
As a suggestion. If API method doesn't return a ```200``` like this case, its properly not a good idea to describe the eventual result this way in the API definition.

Alternative:
Same way ```x-ms-long-running-operation``` used as a custom vendor extension. API definition can have ```x-ms-notification-content``` that can describe eventual result. ```x-ms-notification-content``` is used for the same purpose while describing web hooks in MS Flow for example ([documentation](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger#creating-the-webhook)).

@deathly809
