### ISSUE TITLE
baseUri on generated clients not valid

### ISSUE THREAD

**Issue by pwfraley** [Azure/autorest#2974]
When we generate clients using the latest autorest, the default baseUri is set to "/test" on older versions it used to be "http://localhost/test"

The problem here is, that when you run tests the baseUri in the testenvirnmont gets overriden to late, causing an error that the baseUri is not valid.

Using dotnet core v2.1.301 and mstest.

**Comment by JasonSmyr** [comment]
possibly related to https://github.com/Azure/autorest/issues/2978
