### ISSUE TITLE
How to pin autorest extension versions?

### ISSUE THREAD

**Issue by co3k** [Azure/autorest#2976]
Our project generates TypeScript REST client by using autorest, but we've faced some troubles about incompatibilities between generated client and depended library (ms-rest-js).

A developer installs autorest (and typescript extension) and generates clients on 21 Jun, all of them are fine. But another developer installs autorest (and typescript extension) and generates client on 22 Jun, generated clients are not compatible with the old version of ms-rest-js.

Our project pin libraries by using package-lock.json but autorest might not have a way to do so.
How should I do to solve this problem? Should we consider about new feature to pin extension versions in a project?

**Comment by fearthecowboy** [comment]
you can specify the version by adding  `use` to the command line: ie  `"--use=@microsoft.azure/autorest.csharp@2.3.79"` 

or  you can put it in the `readme.md` configuration file:

~~~ markdown
# c# settings:

``` yaml $(csharp)
use:
  - @microsoft.azure/autorest.csharp@2.3.79
``` 
~~~

**Comment by co3k** [comment]
Oh, I didn't know this option. Thanks!
