### ISSUE TITLE
Feature request: Inline suppressions

### ISSUE THREAD

**Issue by keburek** [Azure/autorest#2977]
I wish I could write warning/error suppressions inline.  From and Where would be picked up from context.
  
    {
      "definitions": {
        "Model": {
          "properties": {
            "enabled": {
              "type": "boolean",
              "x-ms-autorest-directive": {
                "reason": "A boolean really is the best fit.",
                "suppress": [ 
                  "EnumInsteadOfBoolean"
                ]
              }
            }
          }
        }
      }
    }

**Comment by fearthecowboy** [comment]
Not gonna happen, sorry.
