### ISSUE TITLE
AutoRest fails on schema validation for securityDefinitions.oauth2

### ISSUE THREAD

**Issue by conniey** [Azure/autorest#2982]
## Repro Steps:
1. Download: https://gist.github.com/conniey/3a02ce174bf7038ae4d2dec2b7eadcf7
1. Execute: `autorest --typescript --input-file=C:\swagger.json --output-folder=generated/typescript --verbose`

This was generated from my ASP.NET Core application using:
`<PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />`

## Expected
It generates a typescript client.
The definition matches the one described here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object

## Actual
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///C:/users/connie/Desktop/swagger.json:46:4 ($.securityDefinitions.oauth2)
FATAL: swagger-document/individual/schema-validator - FAILED

It works when I remove the "securityDefinitions" node.

```bash
λ  autorest --typescript --input-file=C:\users\connie\Desktop\swagger.json --output-folder=generated/typescript --verbose
AutoRest code generation utility [version: 2.0.4283; node: v8.11.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\connie\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
No configuration found at 'file:///E:/git/connie/'.
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.367)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///C:/users/connie/Desktop/swagger.json:46:4 ($.securityDefinitions.oauth2)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.
```

**Comment by dipansaha** [comment]
If you remove TokenUrl from the Swagger securityDefinition section it will resolve the issue. Token url is not defined in the implicit flow schema definition. here is the [link](http://json.schemastore.org/swagger-2.0#/definitions/securityDefinitions) for the schema definition

**Comment by conniey** [comment]
Ahh.. you're right. It's an issue with Swashbuckle where it allows me to set the TokenUrl for an implicit flow without warning. Thank you for the response!

**Comment by kostyrin** [comment]
I had same issue in v. 2.0.4283. You have to remove 'AuthorizationUrl' section in the version.
