### ISSUE TITLE
Packages failing BinSkim analysis

### ISSUE THREAD

**Issue by barborico** [Azure/autorest#2996]
Hi,

I am working on a Microsoft service and our deployment pipeline (CDPx) runs BinSkim analysis as part of official builds. I have had to create an exception because our dependency on Azure Key Vault library dependencies is causing this analysis to break the build. Specifically, the following packages yield BadSigningAlgorithm (BA2022) errors with the message: "Cryptographically weak signatures: [digest algorithm: 'sha1NoSign' + digest encryption algorithm: 'RSA']".

  -  Microsoft.Azure.KeyVault.dll
      -  Microsoft.Rest.ClientRuntime.dll
      -  Microsoft.Rest.ClientRuntime.Azure.dll

Given that BinSkim is a part of Azure SDL, published Azure libraries should pass its muster. Is there a plan to use an approved signing process for these packages? And if not, can one be formed?

Thank you!

**Comment by fearthecowboy** [comment]
You probably want to post this in https://github.com/Azure/azure-sdk-for-net -- this is not an AutoRest issue.
