### ISSUE TITLE
Idea: CloudError subclasses

### ISSUE THREAD

**Issue by akx** [Azure/autorest#2998]
As requested by @lmazuel, this is a copy of https://github.com/Azure/azure-sdk-for-python/issues/3349 .

The code and implementation ideas below are Python, but this is not a Python-specific issue.

--- 

It would be very nice to have concrete CloudError subclasses for the various errors Azure spews out, instead of everything being CloudError.
Currently, to handle a particular error type you need to do something awkward like 

```python
try:
    self.compute_client.virtual_machines.get(...)
except CloudError as ce:
    if ce.error.error == 'ResourceNotFound':
        # ... process resource not found...
    else:
        raise  # some other error...
```

while you could do

```python
try:
    self.compute_client.virtual_machines.get(...)
except ResourceNotFound:
    # ... process resource not found...
```

instead.

Some technical notes/thoughts:

* I'd probably steer away from magic such as generating these exception classes at runtime, because that tends to just confuse static analysis and IDEs.
* Generating an `exceptions.py` sort of file for each service should be easy, since the it seems the various error codes are well-known, see e.g. [here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/error-messages). (However, it doesn't look like any error responses are specified in the [spec files](https://github.com/Azure/azure-rest-api-specs/blob/03757d26912ec4e36205e2792a24f73bd3707786/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json#L1624-L1675) themselves. Some spec files for other services such as SQL do have mentions of these error codes, but only in prose form, not as responses.)
* Call sites raising `CloudError` won't need to be modified, since `__new__` magic could be added to `CloudError`; that is, raising a `CloudError` could actually end up raising a more specific subclass thereof. For a less magical (Explicit Is Better Than Implicit) approach, though, `raise CloudError.from_response(resp)` could also work.

**Comment by akx** [comment]
@fearthecowboy Was this resolved in any way, or just closed?

**Comment by lmazuel** [comment]
Hi @akx this will be resolved in the new autorest to come, see this PR:
https://github.com/Azure/autorest.python/pull/388/
