### ISSUE TITLE
Custom code generator

### ISSUE THREAD

**Issue by Ellaiyaraja** [Azure/autorest#3001]
Hi 

Using Auto rest common (https://github.com/Azure/autorest.common), i am developing my tool. 
I have following questions. 

1. How to refer autorest.common in my my C# project ? 
2. How to handle different versions, specially newer versions? 
3. What is autorest.common release frequency ? 

Please reply me if you have any idea around this questions.

Thanks & Regards,
Ellaiyaraja.B

**Comment by fearthecowboy** [comment]
O_o

AutoRest.Common isn't really designed for direct consumption.  It's only purpose is to share common code between the current generation of AutoRest generators.  Newer generators will not likely use that at all. 

We don't update it except for important cross-generator bugs at this point, and we don't publish new versions to nuget (as we consume via a submodule now)

**Comment by fearthecowboy** [comment]
If you're looking to build a new generator to plug into AutoRest, it's better done in TypeScript.

**Comment by Ellaiyaraja** [comment]
We are thinking of to follow C# code generator model. In place of C#
generator we have our custom code generator and thought consume/reference
common project. Can I?

cc

On Sep 19, 2018 21:18, "Garrett Serack" <notifications@github.com> wrote:

If you're looking to build a new generator to plug into AutoRest, it's
better done in TypeScript.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/autorest/issues/3001#issuecomment-422854328>, or mute
the thread

**Comment by fearthecowboy** [comment]
Ah, I see. Go ahead. You can fork it and do as you please.

**Comment by MiYanni** [comment]
Question answered. Closing.
