### ISSUE TITLE
Schema validator chokes on numbers in scientific notation

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest#3006]
Repro:
```sh
$ autorest --input-file=https://tripletex.no/v2/swagger.json
```

Error:
```
AutoRest code generation utility [version: 2.0.4280; node: v10.4.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (2.0.4283).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      '/Users/rigibson/.autorest/@microsoft.azure_autorest-core@2.0.4283/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4283)
ERROR: Schema violation: Expected type number but found type string
    - https://tripletex.no/v2/swagger.json:1:242238 ($.definitions.TravelExpense.properties.attachmentCount.maximum)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.
```

Culprit appears to be this "maximum" property: 

```js
"attachmentCount": {
  "type": "integer",
  "format": "int32",
  "readOnly": true,
  "minimum": 0.0,
  "maximum": 2.147483647E9
},
```

Related to Azure/autorest.typescript#311

**Comment by fearthecowboy** [comment]
Adding as a testing scenario

**Comment by josh-oakes** [comment]
Was this actually fixed? I'm currently running into this issue on core version 3.0.6247

> ERROR: Schema violation: Expected type number but found type string
    - file:///C:/.../Development/python/autorest_dev/swagger.json:1:170779 ($.definitions.MonitoringPointDetailModelV3.properties.RunningSpeedMultiplier.minimum)
	FATAL: swagger-document/individual/schema-validator - FAILED

This is the part of the definition giving the issue:

`"RunningSpeedMultiplier": {
            "format": "double",
            "minimum": 5E-324,
            "type": "number"
          },`

Is there a workaround for this?

**Comment by fearthecowboy** [comment]
try ... `--pass-thru:schema-validator ` --

**Comment by josh-oakes** [comment]
Still getting the same error...
```
$ autorest --pass-thru:schema-validator --input-file=swagger.json --python --output-folder=sd_python_sdk

AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\joakes\.autorest\@microsoft.azure_autorest-core@2.0.4417\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.62)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
ERROR: Schema violation: Expected type number but found type string
    - file:///C:/KCFTech/Development/python/autorest_dev/swagger.json:9520:12 ($.definitions.MonitoringPointDetailModelV3.properties.RunningSpeedMultiplier.minimum)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.
```

**Comment by fearthecowboy** [comment]
gah. it could be `--pass-thru:schema-validator-swagger` (trying to do this off the top of my head)

**Comment by josh-oakes** [comment]
Heh, still a no go. Is this documented anywhere? I don't see the pass-thru argument in the help docs

**Comment by fearthecowboy** [comment]
No, it's not -- it's an internal thing ... Oh. I just noticed that it's using the 2.0 core, which doesn't have `--pass-thru`.

if you're just trying to express greater than zero, use `exclusiveMinimum: 0`

**Comment by josh-oakes** [comment]
Ah ok, I got that working. It looks like exclusiveMinimum takes a boolean value along with your minimum, this is what worked for me...

```
"RunningSpeedMultiplier": {
        "format": "double",
        "minimum": 0.00,
        "exclusiveMinimum": true,
         "type": "number"
}
```

Thanks for the help!

**Comment by fearthecowboy** [comment]
OH FOR &%@(..

My whole life, I thought `exclusiveMinimum` was a number ... well, that tells you how many people use it, because the powershell generator and the whole V3 modeler aren't using it right. 

At the end of the day, this is so typical of JSON Schema -- use two properties, when one would have done.
