### ISSUE TITLE
VSTS - autorest/core load very slow affecting pipeline performance

### ISSUE THREAD

**Issue by VaclavK** [Azure/autorest#3011]
@fearthecowboy as requested, filing new issue
running autorest as part of release pipeline on VSTS (hosted or private agents)
being aware of #2987 I have configured sample pipeline with node.js install to 8.12 - it would run 8.11 without this being explicit
what we do
npm install -g autorest@latest
autorest --reset (this is house keeping for private agents and does not need to be done for vsts hosted agents)
autorest... (client generation)
I see considerable time being spent on the following
018-10-02T16:48:09.2854655Z Loading AutoRest core 'C:\Users\VssAdministrator.autorest@microsoft.azure_autorest-core@2.0.4289\node_modules@microsoft.azure\autorest-core\dist' (2.0.4289)
2018-10-02T16:54:09.8089158Z Installing AutoRest extension '@microsoft.azure/autorest.csharp' (https://github.com/eShopWorld/autorest.csharp)
with the --reset and the client gen itself this sub-step is run twice - incurring considerable time running this - long enough to stress the agent queue and prompt questions from dev teams
second invocation timeline
2018-10-02T16:55:42.9123158Z Loading AutoRest core 'C:\Users\VssAdministrator.autorest@microsoft.azure_autorest-core@2.0.4289\node_modules@microsoft.azure\autorest-core\dist' (2.0.4289)
2018-10-02T16:57:02.5343003Z Loading AutoRest extension '@microsoft.azure/autorest.csharp' (https://github.com/eShopWorld/autorest.csharp->2.2.0)
last time I ran this - total duration - 9:54.060, time spent on loading autorest core 7:20
we have been running this task for quite a long time across different versions of the autorest modules always seeing this level of performance so I would not attribute it to a particular version
I cannot repro this locally with the same autorest version and node.js version (and very slow AV engine)

**Comment by VaclavK** [comment]
to give more context, we have wrapped autorest as VSTS tasks

the source code is - https://github.com/eShopWorld/vsts-autorest/blob/master/src/AutoRestNuGetGenerator/AutoRestNuGetGenerator/AutoRestNuGetGenerator.ps1

the latest version (for private rigs) does not always attempt to install autorest (devops would put it there) and so we do not even reset anymore

**Comment by kwskii** [comment]
Why the no explanation close?

**Comment by fearthecowboy** [comment]
We've re-written so much underneath, and with node12 or node13 and autorest 3.0.+ you should not be seeing any significant perf loading time problems.
