### ISSUE TITLE
Need additional parameter hook data for completers

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3025]
### Description
In general - need a mechanism for returning tab completer list of suggested parameter values, and using these in a tab completer in the associated parameter.
- For Location Completer: need input: list of resource types
- For Resource Completer: resource type, list of parent resource parameter names *and* bound parameter data

In each case, returned data is a list of strings, which should be used in the tab completer

**Comment by fearthecowboy** [comment]
This is a another delegate that we can call from the generated code to get the list of things to complete on.

**Comment by fearthecowboy** [comment]
Added delegate for Completer support  - https://github.com/Azure/azure-powershell/pull/8506
