### ISSUE TITLE
Mask Http Parameters in script cmdlet proxies

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3026]
### Description

In the script cmdlet public API, mark Http parameters (Proxy/ProxyCredential/httppieline*) with ```DontShow``` attribute

**Comment by deathly809** [comment]
Should this be done through a configuration files like PSSwagger?  Alternatively you could create new OpenAPI extensions like 

```
"x-ms-powershell-dontshow" : true
```

**Comment by fearthecowboy** [comment]
`Proxy/ProxyCredential/httppieline` are parameters that inserted by the generator, not from the swagger.

**Comment by fearthecowboy** [comment]
Notes: 
 - this is in the proxy generator.
