### ISSUE TITLE
Each cmdlet that produces output should have OutputType attribute

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3028]

**Comment by fearthecowboy** [comment]
Notes:
 - probably the proxy generator.

**Comment by fearthecowboy** [comment]
The output type is now propagating to the exported cmdlet

However, we need to unwrap output types that are collections.

**Comment by MiYanni** [comment]
@fearthecowboy That will be handled in: https://github.com/Azure/autorest/issues/3085
