### ISSUE TITLE
Minimize Parameter attributes for parameters in all parameter sets

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3033]

**Comment by fearthecowboy** [comment]
Notes; 
 - The build-module script which creates the proxies needs to collapse common parameters that are in all sets

**Comment by MiYanni** [comment]
Discussed with Mark. This is a 'beautification' process. To do this currently in the build-module.ps1 would be messy. Mark said it could be deferred until later.

For additional detail: We create a 'skeleton' cmdlet in our script. Then, using the ProxyCommand object to fill in the rest of the information from the variants. So, the ParameterSets ARE the variants, but aren't something we explicitly create in the script. To implement this currently, I'd have to do some crazy regex magic on the resulting text from the ProxyCommand. ProxyCommand itself is not an object, it is just a concept. The only other way is to generate the ParameterSets ourselves onto the CommandMetadata, which we use to create the ProxyCommand. It would be messy.
