### ISSUE TITLE
Generate Format.ps1xml for output types

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3034]
- Formats should include a table format, with selected properties (this may require additionala ttributes, or powershell-specific configuration
- Formats should include a list format (also configurable via config, or post-generation)

**Comment by MiYanni** [comment]
Initial implementation: https://github.com/Azure/autorest.incubator/pull/35

**Comment by MiYanni** [comment]
Added initial generation of .format.ps1xml. It works for all public models and currently outputs all 'top level' properties as columns. There are other fixes soon to get all properties for a model. And, configuration is part of work Nelson is doing. Closing this issue.

@markcowl If you want List format, it should be entered as a separate issue. It can be implemented after we have configuration points to specify format.
