### ISSUE TITLE
HTML tags transformed to HTML character entities in XML docs

### ISSUE THREAD

**Issue by mmacy** [Azure/autorest#3045]
HTML tags (`<b>`, `<ul>`, `<li>`, et. al) that appear in Swagger description fields are transformed into their character entity equivalents (e.g. `&lt;`) in generated XML documentation.

HTML tags should remain untranslated as they are supported by Open API's support for GFM in that field, and by extension, [so are the HTML tags](https://github.github.com/gfm/#html-blocks).

**AutoRest-generated source code**: [VirtualMachineScaleSetOSProfile.cs](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/Generated/Models/VirtualMachineScaleSetOSProfile.cs#L118-L140)

**Reference page**: [VirtualMachineScaleSetOSProfile.AdminUsername](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachinescalesetosprofile.adminusername?view=azure-dotnet#Microsoft_Azure_Management_Compute_Models_VirtualMachineScaleSetOSProfile_AdminUsername)

![image](https://user-images.githubusercontent.com/13394541/48294621-39937000-e43a-11e8-8cb6-de5afefb205f.png)

**Swagger spec**:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json#L6415-L6417
 
**REST ref** renders it as expected:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/update

![image](https://user-images.githubusercontent.com/13394541/48294685-a6a70580-e43a-11e8-8435-d7de416cb9a2.png)

**Comment by James-Don** [comment]
I am using Swashbuckle 5.6.0 and VS2017 and the HTML tags in comments are simply ignored, output in Swagger UI is not indented or formatted.

**Comment by mmacy** [comment]
Closing this issue in favor of [azure-sdk-for-net #5208](https://github.com/Azure/azure-sdk-for-net/issues/5208).

Cc: @salameer @shahabhijeet
