### ISSUE TITLE
Schema validation fails on empty version property even though this is valid.  

### ISSUE THREAD

**Issue by darrelmiller** [Azure/autorest#3047]
Although `version` is a required property, it doesn't actually have to have a value.  Only the property needs to be present.  It's a JSON Schema thing.  I suppose we should clarify this in the OpenAPI spec somewhere.

```
{
  "swagger": "2.0",
  "info": {
    "title": "Empty Version Fail",
    "version": ""
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

```
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\darrmi\.autorest\@microsoft.azure_autorest-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4289)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
ERROR: Schema violation: String is too short (0 chars), minimum 1
    - file:///C:/Users/darrmi/test/psgraph/empty-version-fail.json:5:4 ($.info.version)
FATAL: swagger-document/individual/schema-validator - FAILED
```
This shouldn't fail.  However, this isn't a very high priority issue as it doesn't cause many problems.

**Comment by fearthecowboy** [comment]
O_o 

I'm not sure I'm ok with version being an empty string. I get that the spec isn't all that clear, and it may be 'technically' correct, but... stuff like that makes me get stabby.  🔪  

Before I go anywhere on this one, I'll have to see if it impacts stuff elsewhere.
