### ISSUE TITLE
Schema validation gives oneOf error when x- property is in parameter

### ISSUE THREAD

**Issue by darrelmiller** [Azure/autorest#3048]
This schema fails due to the presence of `x-ms-docs-key-type`.
```
{
  "swagger": "2.0",
  "info": {
    "title": "oneOf parameter Fail",
    "version": "1.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "test_op",
        "parameters": [
          {
            "in": "path",
            "name": "user-id",
            "description": "key: user-id",
            "required": true,
            "type": "string",
            "x-ms-docs-key-type": "user"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```
This error is reported.  
```
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\darrmi\.autorest\@microsoft.azure_autorest-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4289)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///C:/Users/darrmi/test/psgraph/oneof-parameter-fail.json:11:8 ($.paths["/"].get.parameters)
FATAL: swagger-document/individual/schema-validator - FAILED
```

Extension properties should be allowed in parameters.

**Comment by fearthecowboy** [comment]
Again, it's not the `x-*` that it's mad about, it's that it's `x-ms-*` that the schema is being a jerk over.

**Comment by arthurderyckere** [comment]
@fearthecowboy what's the solution here? I don't see "x-ms-docs..." in the extensions list.
http://azure.github.io/autorest/extensions/

**Comment by darrelmiller** [comment]
I believe AutoREST has already been changed to make these warnings rather than errors.  We also have the ability to strip these `x-ms-*` extension from the input document if necessary.

**Comment by anganti** [comment]
I am still seeing similar issues. Is there a specific way to resolve this issue 

autorest --version:3.0.6306  --typescript --input-file:c:\Connectors-SDK\src\AzureConnectorsSdk.Tests\SampleFiles\office365-openapi.json
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\anganti\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
ERROR: Schema violation: Additional properties not allowed: x-ms-capabilities ()
    - file:///c:/Connectors-SDK/src/AzureConnectorsSdk.Tests/SampleFiles/office365-openapi.json:1:1


ERROR: Schema violation: Additional properties not allowed: x-ms-summary (definitions > ContactResponse_V2 > properties > createdDateTime)

**Comment by fearthecowboy** [comment]
if you have `x-ms-*` things that are not in autorest's schema you can add `--pass-thru:schema-validator` on the command line.

**Comment by anganti** [comment]
@fearthecowboy  Thank you for the prompt response.

unfortunately that flag dint resolve the issues :( 

C:\Connectors-SDK>autorest --version:3.0.6306  --typescript --pass-thru:schema-validator --input-file:c:\Connectors-SDK\src\AzureConnectorsSdk.Tests\SampleFiles\office365-openapi.json
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\anganti\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
ERROR: Schema violation: Additional properties not allowed: x-ms-capabilities ()
    - file:///c:/Connectors-SDK/src/AzureConnectorsSdk.Tests/SampleFiles/office365-openapi.json:1:1
ERROR: Schema violation: Additional properties not allowed: x-ms-summary (definitions > ContactResponse_V2 > properties > lastModifiedDateTime) 
    - file:///c:/Connectors-SDK/src/AzureConnectorsSdk.Tests/SampleFiles/office365-openapi.json:1:1
ERROR: Schema violation: Additional properties not allowed: x-ms-visibility (definitions > ContactResponse_V2 > properties > lastModifiedDateTime)
    - file:///c:/Connectors-SDK/src/AzureConnectorsSdk.Tests/SampleFiles/office365-openapi.json:1:1

**Comment by anganti** [comment]
This helped --pass-thru:schema-validator-swagger

**Comment by fearthecowboy** [comment]
Hmm. I think something changed a while back and I don't recall when.

try `--pass-thru:schema-validator-swagger` for swagger (openapi2) 
or `--pass-thru:schema-validator-openapi` for OpenAPI3 

Weird.  I really don't recall that getting split

**Comment by anganti** [comment]
Thank you!!
