### ISSUE TITLE
C# Client No Longer Supports Framework 4.0.3

### ISSUE THREAD

**Issue by thecontrarycat** [Azure/autorest#305]
I just tried to do a nuget update in my solution and found that it wouldn't upgrade to the latest version.  Further investigation shows that for some reason you have withdrawn support for Framework 4.0.3.

Can someone from the team explain why this decision was made?  4.0.3 is the last version of .Net that runs on XP and has real value for lots of people - including my project which is due for deployment to 20,000 devices.

**Comment by stankovski** [comment]
Unfortunately we do not have a plan for supporting 4.0.3, however we are adding support for coreclr and dotnet target.
