### ISSUE TITLE
Code Generation design

### ISSUE THREAD

**Issue by Ellaiyaraja** [Azure/autorest#3051]
Hi,

I would lile to know to why Code Model is used instead of  T4 Code Generation  for HTTP Client Proxy code genration. 

If i get some information around these two technique, it will be helpful for me to take a direction.

Thanks & Regards,
Ellaiyaraja.B

**Comment by fearthecowboy** [comment]
Because it doesn't. 

T4 templates are a terribly primitive means to generate code which don't work for almost any useful situation
