### ISSUE TITLE
[C#] Ability to specify generated file type. [*.g.cs convention]

### ISSUE THREAD

**Issue by DerekChasse** [Azure/autorest#3056]
I've used Swashbuckle and AutoRest in my solution to automatically generate my API's client as part of my build process.  The client is a separate assembly as I am extending the client and providing further logic and helpers which are not able to be generated.

Ideally, I would not like to commit the generated code into my source control, and the best way that I can see to do this is to modify my `.gitignore` file, however as my API evolves, this becomes a burden to keep the `.gitignore` file updated.

I'd like to know if it is possible to specify that files generated as part of AutoRest can use the `*.g.cs` convention.

**Comment by fearthecowboy** [comment]
Not at the very moment (filenames are specified by the generator, and there isn't an extensibility point that allows them to be changed.)

in the mean time, the best I can say is generate into a subfolder (ie.`--output-folder=./generated`) and just exclude that folder.
