### ISSUE TITLE
Why does generating a client try to open a TLS connection to...something?

### ISSUE THREAD

**Issue by TWolverson** [Azure/autorest#3057]
I'm attempting to generate a client using the normal `autorest --input-file=swagger.json --csharp --output-folder=\.--namespace=mynamespace`

I'm getting a mysterious error:

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:134:17)
    at Object.connect (_tls_wrap.js:1121:48)
    at ondata (/node_modules/npm/node_modules/pacote/node_modules/make-fetch-hap
pen/node_modules/https-proxy-agent/index.js:153:20)
    at Socket.read (/node_modules/npm/node_modules/pacote/node_modules/make-fetc
h-happen/node_modules/https-proxy-agent/index.js:88:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Why is this appearing to try to make a TLS connection? I expected everything that was required for client generation to be specified by the swagger file. The documentation doesn't mention connecting to any outside resources for this step.

**Comment by fearthecowboy** [comment]
It's doing a check for a newer version. use `--skip-upgrade-check` to not check for a new version of autorest itself.

Additionally, autorest doesn't have the generators built-in, it pulls them down from NPM, so the first time you use a given generator it will go get it.

**Comment by fearthecowboy** [comment]
It's using NPM internally for this; I don't think there is a way at the moment to work around with a proxy; NPM is kindof terrible to use programatically.

AutoRest 3.0+ will use YARN internally, and we can work around stuff like that a lot better with that.  That should be ready around the end of January.

I don't have a complete workaround for you, but I have a starting point:

https://github.com/Azure/autorest.aio

If you can clone that repo, and update the script to use the proxy, that will create a standalone installation of autorest and plugins that shouldn't need to go to the network to install anything more.
