### ISSUE TITLE
[Question] PHP Client Runtime?

### ISSUE THREAD

**Issue by tpirc3** [Azure/autorest#3064]
Sample code generated by AutoRest:
```PHP
/**
 * @param \Microsoft\Rest\RunTimeInterface $_runTime
 * @param string $subscriptionId
 */
public function __construct(
    \Microsoft\Rest\RunTimeInterface $_runTime,
    $subscriptionId
)
{
    $_client = $_runTime->createClientFromData(
        self::_SWAGGER_OBJECT_DATA,
        ['subscriptionId' => $subscriptionId]
    );
    $this->_ListPets_operation = $_client->createOperation('listPets');
    $this->_CreatePets_operation = $_client->createOperation('createPets');
    $this->_ShowPetById_operation = $_client->createOperation('showPetById');
}
```

I didn't find `\Microsoft\Rest\RunTimeInterface` implementation on [Azure/autorest.php](https://github.com/Azure/autorest.php) or [Azure/azure-sdk-for-php](https://github.com/Azure/azure-sdk-for-php). 
So where can I find PHP Client Runtime required for the generated code? 

 Can someone help? 🙂

**Comment by kant2002** [comment]
I have same problem, and after giving up a bit on Autorest decide that https://jane.readthedocs.io/en/latest/OpenAPI/introduction.html could do the trick of generation PHP client . But unfortunately without Autorest

**Comment by kant2002** [comment]
@fearthecowboy could you give some information about what's in the https://github.com/Azure/autorest.php ? Does it maintained?

**Comment by fearthecowboy** [comment]
I don't think so ... @sergey-shandar might know more

**Comment by imissyouso** [comment]
I have the same problem.

**Comment by skoruppa** [comment]
Same here. Where we can find `\Microsoft\Rest\RunTimeInterface`?

**Comment by fearthecowboy** [comment]
After a recent re-org, I believe it's been abandoned. Sorry folks.

**Comment by douyoung** [comment]
@fearthecowboy thanks for the update. Do you have more information on the re-org? What else has been abandoned?

**Comment by kant2002** [comment]
@feathercowboy Subsequent question. Is there any chance that some parts for PHP can be dropped as open source code by MS? It maybe practical to resurrect that using community only.

**Comment by rolfec** [comment]
FYI. My company switched to the following open-source alternatives as the support for PHP and other languages seem to be dead end in autorest.

- NSWag: https://github.com/RicoSuter/NSwag
- OpenAPI Generator: https://github.com/OpenAPITools/openapi-generator
