### ISSUE TITLE
Process() cancelled due to exception : Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by jchannon** [Azure/autorest#3068]
I've just installed autorest and run the command against my openapi v3 document and get the above error.  Not really sure what I can do to move past this.

Screenshot below:
<img width="1128" alt="screen shot 2019-01-23 at 19 12 22" src="https://user-images.githubusercontent.com/105126/51630777-f168f180-1f42-11e9-97e5-692bafe6271e.png">

**Comment by fearthecowboy** [comment]
Support for OAI 3.0 is coming soon.

**Comment by jchannon** [comment]
Is what the error relates to?

**Comment by fearthecowboy** [comment]
I would assume so, given that  openapi v3 is not supported at this point.

adding `--debug --verbose` to the command line *might* show more information.

**Comment by jchannon** [comment]
<img width="1161" alt="screen shot 2019-01-23 at 19 44 31" src="https://user-images.githubusercontent.com/105126/51632484-59213b80-1f47-11e9-81c6-a6214ab9b990.png">

**Comment by Harsh-Wardhan-Agarwal** [comment]
Any update on this issue? I am stuck on the same issue.

**Comment by fearthecowboy** [comment]
you can try the autorest-beta to try opienapi3 support

```
npm install -g "@autorest/autorest"
autorest-beta ...
``
It can be installed side-by-side with the release version.
