### ISSUE TITLE
Proper cmdlet prefix using module name

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3074]
The generated cmdlets currently only have `Az` before the noun. They should have the full module name before the noun by default.
### Ex:
Generated Maps module. The Maps module name would be `Az.Maps`, thus:
`Get-AzAccount` => `Get-AzMapsAccount`
`New-AzAccount` => `New-AzMapsAccount`
`New-AzAccountKey` => `New-AzMapsAccountKey`
etc.

The cmdlet prefix should also be configurable for special cases. For example, `Az.Compute` does not have `AzCompute` before each cmdlet. Instead, they only have `Az`.

**Comment by deathly809** [comment]
So if you have the Module Azs.AzureBridge.Admin then it would be New-AzsAzureBridge???Noun?

**Comment by MiYanni** [comment]
@deathly809 By default, it should do that, yes. That's how 90% of our cmdlets are named. There are exceptions, like Compute. So, this prefix would need to be configurable.

**Comment by MiYanni** [comment]
@deathly809 Since this is now implemented, when using --azure (which you will for Stack), the `noun-prefix` will default to the `service-name`. So, to fix this, in the readme.md, you'd just put `noun-prefix: ''`. Then, it'll not contain the service name in your cmdlet names.
