### ISSUE TITLE
For Name parameters, have an alias to their full parameter name

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3078]
Related to: https://github.com/Azure/autorest/issues/3027
When we change the default parameter to be `Name`, it should also have an alias to the original name.
Ex. `Name` would have an alias to `AccountName`, `Name` would have an alias to `ServerName`, etc.

**Comment by deathly809** [comment]
Make sure you handle the case of collision where flattened objects have properties with identical names.  PSSwagger hit that one because our Admin modules were so gud....

**Comment by MiYanni** [comment]
@deathly809 When we do flattening, we are avoiding this by using the original property name as a prefix to the flattened properties. Meaning, if you had property `Key1` of type `KeyItem`, property `Key1` of type `KeyItem`, and `KeyItem` contained `Name` and `Value`, you'd result in creating properties `Key1Name`, `Key1Value`, `Key2Name`, and `Key2Value`.
