### ISSUE TITLE
Namespace should reflect module/service name

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3080]
It seems like we generate the base namespace as `Sample.API`. Needs to, by default, have a meaningful namespace. In Azure PowerShell currently, we use `Microsoft.Azure.PowerShell.Cmdlets.<SERVICE>` as the namespace.

**Comment by fearthecowboy** [comment]
use `--namespace:Microsoft.Azure.PowerShell.Cmdlets.Service` on the cmdline or `namespace:Microsoft.Azure.PowerShell.Cmdlets.Service ` in the configuration.

This is standard behavior.
