### ISSUE TITLE
Need Description documentation (help) for cmdlets

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3083]
Right now, if you generate help docs for cmdlets, they won't have a cmdlet description: 
```powershell
## DESCRIPTION
{{Fill in the Description}}
```

To remedy this, we need to generate the correct syntax in the script (proxy) cmdlets. Right now, the summary in the .cs files:
```cs
/// <summary>Implement a variant of the cmdlet New-Account.</summary>
```
This seems to be a generic output. Instead, the summary should represent the cmdlet description (which is what is used for binary modules). Then, in the script cmdlet, the syntax should look like:
```powershell
<#
.Description
Creates a new account.
#>
```

You can find the information on the syntax here:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-6#syntax-for-comment-based-help-in-functions

Note: I just noticed this exists, but I wasn't able to get it to do anything... https://github.com/PowerShell/PowerShell/blob/d9be6483f6396b647052ce3a65f3ca73463fc952/src/System.Management.Automation/engine/ProxyCommand.cs#L66

**Comment by MiYanni** [comment]
Uhhh. So, using that comment notation does not seem to be supported by platyPS. I added it to our generated script cmdlet, and ran platyPS over it. It still was not filled in. Oy.

**Comment by fearthecowboy** [comment]
![](https://media1.tenor.com/images/5035a1d5a7a88844c45e6a22b0614a9c/tenor.gif?itemid=4862594)

**Comment by deathly809** [comment]
PSSwagger would just use the summary/description of the endpoint for that specific action.  It worked okay and it really made our PMs/devs put more effort into documentation.

**Comment by MiYanni** [comment]
@deathly809 I've already tested to see if the would work. It does, but we haven't implemented it in the generator yet.
