### ISSUE TITLE
IoTHub generates RoutingSource for FallbackRouteProperties as enum instead of const, overrides values for RoutingSource

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3087]
For IoTHub, they use RoutingSource enum 3 times. The first 2 times, it has all the appropriate enum values. However, for FallbackRouteProperties, it only defines 1 enum value. This property for that model should be a constant instead. What happens is the csharp v2 generator overrides the RoutingSource type it generated with this version that only has 1 value. So, you end up with a enum with 1 value in the end.

**Comment by NelsonDaniel** [comment]
Just run this with the fix from the PR: https://github.com/Azure/autorest/pull/3130 and it gets all the enum values.
@MiYanni can you verify that this please.

**Comment by MiYanni** [comment]
@NelsonDaniel Tested it. It works. Closing.
