### ISSUE TITLE
Please make the variables not clash with parameters

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/autorest#309]
I have a Web API with parameter "url"

     [HttpGet]
     public async Task<HttpResponseMessage> Get(string url)

but the c# partial IServiceOperations class generator contains local variables names that clash

     // Construct URL
     var url = new Uri(this.Client.BaseUri, "/api/Controller").ToString();

Thanks

**Comment by mikeblakeuk** [comment]
I guess the workaround is to change the https://github.com/Azure/autorest/blob/master/AutoRest/Generators/CSharp/CSharp/Templates/MethodTemplate.cshtml

**Comment by devigned** [comment]
Perhaps any of the internal variables used in the generated code should have some naming prefix such as to not interfere with standard argument naming. Perhaps, an underscore or some other prefix char to denote it's a generated variable.

```csharp
// Construct URL
var __url = new Uri(...).ToString();
```

**Comment by stankovski** [comment]
Tracking via: https://www.pivotaltracker.com/story/show/107076454
