### ISSUE TITLE
Why do examples all say SRC?

### ISSUE THREAD

**Issue by StingyJack** [Azure/autorest#3112]
![image](https://user-images.githubusercontent.com/15381181/52680568-e03e4f80-2f06-11e9-82d4-7432f57c2b64.png)
![image](https://user-images.githubusercontent.com/15381181/52680572-e59b9a00-2f06-11e9-8177-ec348ddf8580.png)
... and so on

**Comment by NelsonDaniel** [comment]
@StingyJack, 'SRC' is a placeholder for the source code that will be generated when you run AutoRest. If you run AutoRest using the literate readme.md, it will override those files with the generated code. 

For example, try running:

```
C:\...\Samples\1a-code-generation-minimal> autorest
```

AutoRest will detect the readme.md file in the current working directory and generate cde. You will see the contents of those files get replaced by the actual source code.

**Comment by StingyJack** [comment]
I was expecting to see samples of what was generated.

**Comment by MiYanni** [comment]
Question has been answered. Closing.

**Comment by StingyJack** [comment]
If it helps to clarify the point I was making, I was curious about this project and if it would be something I could have used, but because all the _examples_ are missing, I couldn't tell if it would be useful or not (and missing examples usually means a project that isn't quite ready) , so I continued looking elsewhere.
