### ISSUE TITLE
Open Api 3 specification with ASP.NET WEB API

### ISSUE THREAD

**Issue by piyushthummar** [Azure/autorest#3113]
Can i **automatically** generate the **Openapi 3.0.0 Specification** from my existing APIs (which are already built), as i can generate **Swagger 2.0 with Swashbuckle** in **ASP.NET 4.5 or 4.6**?

Please suggest a way by which I can generate Openapi 3 specification for all my existing APIs automatically.

**Comment by manigandham** [comment]
Swashbuckle supports OpenAPI 3.0 in the 5.0 beta version but that is only for asp.net core.

You can try NSwag instead to generate the spec which does support 3.0.

**Comment by MiYanni** [comment]
AutoRest doesn't generate OpenAPI specs, it consumes them. Closing.

**Comment by itrice** [comment]
> Can i **automatically** generate the **Openapi 3.0.0 Specification** from my existing APIs (which are already built), as i can generate **Swagger 2.0 with Swashbuckle** in **ASP.NET 4.5 or 4.6**?
> 
> Please suggest a way by which I can generate Openapi 3 specification for all my existing APIs automatically.

Hello piyushthummar, now, I meet the same question. I need to make the .net framework to support OAS3. So could you tell me did you find a good way to implement this? And how you generate the Openapi 3.0 specification. Thank you very much, if you can give me any recomment.
