### ISSUE TITLE
Visual Studio Generated client name

### ISSUE THREAD

**Issue by njabulomp** [Azure/autorest#3129]
Good day, 

I am using swagger in a web API project and would like to kindly know how to control the generated client names from AutoRest in Visual Studio.

e.g. The API controller name is PackageController, I would like the generated client name to be PackageClient.

I have had scenarios where the word 'Operations' are being appended to the generated client name and other scenarios where the word is not being appended can I be kindly guided as to how this is being generated.

**Comment by eberkund** [comment]
I am also curious about this.

**Comment by fearthecowboy** [comment]
Set `--title=MyClientName` on the command line
