### ISSUE TITLE
autorest 2.0.42

### ISSUE THREAD

**Issue by OzBob** [Azure/autorest#3144]
Similar errors to #2941 but can't resolve using NPM commands.

1
New Windows build, install VS2017Pro, then Node, then use NPM to install autorest.
^^^^^^^^^^^^^
node --version
v10.15.1
^^^^^^^^^^^^^
npm --version
6.4.1
^^^^^^^^^^^^^
npm install -g autorest

> autorest@2.0.4283 preinstall {userdir}\AppData\Roaming\npm\node_modules\autorest
> node ./preinstall-check

{userdir}\AppData\Roaming\npm\autorest -> {userdir}\AppData\Roaming\npm\node_modules\autorest\dist\app.js
+ autorest@2.0.4283
added 1 package from 1 contributor in 12.902s

^^^^^^^^^^^^^
autorest --reset
AutoRest code generation utility [version: 2.0.4283; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
{userdir}\.autorest\@microsoft.azure_autorest-core@2.0.4302\autorest-core -> {userdir}\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist\app.js
{userdir}\.autorest\@microsoft.azure_autorest-core@2.0.4302\autorest-language-service -> {userdir}\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist\language-service\language-service.js
   Loading AutoRest core      '{userdir}\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4302)

^^^^^^^^^^^^^
npm i @microsoft.azure\autorest-core
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@microsoft.azure\autorest-core" as it does not contain a package.json file.
^^^^^^^^^^^^^

2
Downloading the Windows Zip from [Releases](https://github.com/Azure/autorest/releases/tag/2.0.4222) , extracting it and running the autorest command:
autorest --input-file=petstore.yaml --csharp --output-folder=CSharp_PetStore --namespace=PetStore

works fine

**Comment by fearthecowboy** [comment]
do an `autorest --reset` -- plugin directory may have a bad entry.

**Comment by OzBob** [comment]
npm uninstall -g autorest
npm install -g autorest
npm list -g --depth=1
{navigate to that directory, e.g. {userdir}\AppData\Roaming\npm}
autorest --reset
autorest --help

not sure what went wrong previously but all good today
