### ISSUE TITLE
Docker Image tagging

### ISSUE THREAD

**Issue by viktorpeacock** [Azure/autorest#3145]
Hi, 

Can you please confirm if this is the official microsoft image for AutoRest? https://hub.docker.com/u/azuresdk 

I ask because the image is not tagged and looks like a community user image. If it's not the official image, then can you please point us to where we can get one? 

Thank you,
Viktor

**Comment by fearthecowboy** [comment]
We don't currently produce one. 

maybe when I get past autorest 3.0
