### ISSUE TITLE
Allow notation in .ps1 files for config replacement

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3154]
This is similar to: https://github.com/Azure/autorest/issues/3137
We need a way to add configuration information to copied .ps1 files. Currently, all path information is hard-coded. Instead, it should come from configuration. The `${}` syntax exists in PowerShell itself, so that won't work like it would for .md files. So, need to figure out a notation and then implement the string replacement.

**Comment by fearthecowboy** [comment]
done
