### ISSUE TITLE
Feature request: Add command line option for generating everything as internal

### ISSUE THREAD

**Issue by dennizino** [Azure/autorest#3174]
We want to make sure that we are not using anything generated outside of the assembly. We want to make our own models and api-clients as a facade to prevent our clients to be exposed to irrelevant data, as well as not being forced to change.

**Comment by brjohnstmsft** [comment]
It would be useful to have an extension to allow this on a per-operation and per-schema/type basis as well.

**Comment by fearthecowboy** [comment]
I'll add it to the feature request list for autorest 3.1.
