### ISSUE TITLE
x-ms-code-generation-settings deprecated but link to configuration files missing

### ISSUE THREAD

**Issue by OzBob** [Azure/autorest#3179]
https://github.com/Azure/autorest/edit/master/docs/extensions/readme.md
says:
* [x-ms-code-generation-settings](#x-ms-code-generation-settings) - enables passing code generation settings via OpenAPI definition (*deprecated! Please use [configuration files](https://github.com/Azure/autorest/proposals/generator-specific-settings/literate-configuration.md) instead.*)

but the link to 'literate-configuration' link is broken. 

Original 'literate-configuration' content is in 'proposals':
https://github.com/Azure/autorest/blob/87a5600e4af7ea185a887c63ad3153f0936fb0fa/.attic/proposals/generator-specific-settings/readme.md

Is that the only guidance on autorest 'configuration files' format?

**Comment by fearthecowboy** [comment]
At the moment yes; we're woefully behind on docs. 

look in the samples directory for some examples
