### ISSUE TITLE
PowerShell directives for verb renaming fail on compilation (always use VerbsCommon)

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#3185]
When writing a directive that remaps a cmdlet verb to a verb outside of the common set (for example: Start, Stop, Invoke), the resulting code will not compile, as the verb is always written as if it  were a property of VerbsCommon, whether it is or not.

Note that this only occurs in configuration remapping - when the geenrator maps to one of these verbs without configuration, it selects the correct static class for the verb.

For example, the following configuration in Compute:
```yaml
- where
    noun: (.*)PowerOff
  set:
    noun: $1
    verb: Stop
```
results in generated cmdlets using the noun name:
```c#
VerbsCommon.Stop
```
which fails to compile.

**Comment by fearthecowboy** [comment]
Ah, it's not tracking to the new category (which isn't exposed to the user) 

@NelsonDaniel  -- this shouldn't be too tricky, in the modifier, you'll have to find the new category when the noun is changed.
