### ISSUE TITLE
How to define x-ms-example when operation requires files to be submitted?

### ISSUE THREAD

**Issue by hendrytl** [Azure/autorest#3190]
I have an operation where the body is a multipart form upload requiring two files.  One is a zip archive and another is a json file.
How do I represent that in an example file with the x-ms-example extension? 

Here is the relevant operation in the swagger document:
"/execution/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/run": {
      "post": {
        "tags": [
          "Execution"
        ],
        "summary": "Start a run on a remote compute target.",
        "description": "Starts an experiment run using the provided definition.json file to define the run.\r\n            The source code and configuration is defined in a zip archive in project.zip.",
        "operationId": "StartRun",
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "subscriptionId",
            "in": "path",
            "description": "The Azure subscription Id.",
            "required": true,
            "type": "string",
            "format": "uuid"
          },
          {
            "name": "resourceGroupName",
            "in": "path",
            "description": "The resource group name.",
            "required": true,
            "type": "string"
          },
          {
            "name": "workspaceName",
            "in": "path",
            "description": "The workspace name.",
            "required": true,
            "type": "string"
          },
          {
            "name": "experimentName",
            "in": "path",
            "description": "The experiment name.",
            "required": true,
            "type": "string"
          },
          {
            "name": "files",
            "in": "formData",
            "description": "Two files are required: 'project.zip':\r\n            A zip archive of a folder containing the source code to use for the run.\r\n            'definition.json': A text file that is a JSON-serialized run definition structure.",
            "required": true,
            "type": "array",
            "items": {},
            "collectionFormat": "multi",
            "uniqueItems": false
          },
          {
            "name": "runId",
            "in": "query",
            "description": "A run id. If not supplied a run id will be created automatically.",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "A run was succesfully started.",
            "schema": {
              "$ref": "#/definitions/RunStatus"
            }
          },
          "400": {
            "description": "The run was submitted with missing or invalid values.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "403": {
            "description": "Access denied."
          },
          "500": {
            "description": "An internal error has occurred and the run could not be created at this time."
          },
          "504": {
            "description": "A timeout occurred trying to process the request."
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }

**Comment by fearthecowboy** [comment]
Hmm. Not sure; you'd have to ask the folks who maintain the validator
