### ISSUE TITLE
GUI For Code Generation

### ISSUE THREAD

**Issue by RonFrick** [Azure/autorest#3200]
This is such an awesome project, has anyone given thought on setting up a website to just upload a swagger doc and spit out a zip file with the code generated files?

**Comment by fearthecowboy** [comment]
We're so deep in feature work, it'll be a long time before we get to that.

It wouldn't be terribly hard, tho' ... We have a nice API that can be used if someone wanted to do that.

**Comment by kumarRaj** [comment]
This has it. https://editor.swagger.io/ Can have a look.
