### ISSUE TITLE
File functionality not implemented

### ISSUE THREAD

**Issue by avilensky** [Azure/autorest#321]
Hi fellow developers, I've implemented an initial version of "type": "file", "in": "formData" functionality in AutoRest and would like to merge my changes if possible. What's your policy on code contributions?

**Comment by devigned** [comment]
We :heart: pull requests! Please target the dev branch with the changes. This functionality will span all of the languages, so if you would like some feedback regarding approach or anything else, ping back.

**Comment by avilensky** [comment]
I can do C# and Java, as those are the languages i'm most familiar with. Do you usually write a unit test for the new functionality?

**Comment by devigned** [comment]
Unit tests would cover the functionality added to the client runtime(s) if needed, which I'm pretty sure the feature will require something added to the client runtime (it'll require us to send something other than application/json as we expect currently).

There are integration tests via a node server. The test server is our local server side implementation of the functionality and provides a report at the end of the integration tests to show how many of the tests a language implementation covers (see: https://github.com/Azure/autorest/tree/dev/AutoRest/TestServer). This will need to verify the client sends the file to the server in the way that is expected.

I've added an issue for creating a readme to cover how one would contribute and provide test for contributing a feature #325. The examples called out in the issue show where these tests live for node and a followed by each of the language implementations.

**Comment by avilensky** [comment]
I've tried to create a pull request, but it failed with the following message: you don not have permission to push your changes to this repository.

**Comment by devigned** [comment]
To create a pull request, you should push changes to your fork of the AutoRest repository. When you feel your changes are ready to be reviewed, then you should create a pull request via the GitHub UI targeting the dev branch of the AutoRest repository.

**Comment by avilensky** [comment]
Let me do that.

**Comment by avilensky** [comment]
Pull request created. I'd like to hear from core contributors and make changes as necessary.

**Comment by devigned** [comment]
It looks like you make the pull request against your fork rather than azure/autorest.

**Comment by avilensky** [comment]
Do I have permission to create a fork in azure?

**Comment by stankovski** [comment]
https://github.com/Azure/autorest/pull/328
