### ISSUE TITLE
credentials::InitializeServiceClient not called

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/autorest#322]
generate with Azure.CSharp. The generated client constructors with a ServiceClientCredentials parameter invoke this(handlers) which calls this.Initialize. This happens before the body of the constructor where the credentials property is set. The initialize method can't call this.Credentials.InitializeServiceClient because Credentials hasn't been set yet.

**Comment by devigned** [comment]
Thank you, @matt-gibbs. This is definitely a priority issue.

**Comment by stankovski** [comment]
https://github.com/Azure/autorest/pull/419
