### ISSUE TITLE
Running from .NET Core 2.1 SDK docker

### ISSUE THREAD

**Issue by daniel-white** [Azure/autorest#3225]
How would I run with in the official .NET Core 2.1 SDK container? I installed node from nodesources. Yet, the 2.0 runtimes are still expected:

```
Failed to load �	�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/root/.net/2.0.0/node_modules/dotnet-2.0.0-linux/shared/Microsoft.NETCore.App/2.0.0/libcoreclr.so'
Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
```

**Comment by KyleGobel** [comment]
I use a custom docker image to use autorest, based off the microsoft/dotnet stretch images.

No idea what this library does or is used for (google probably knows), but seems to be a requirement to use autorest.

Within my dockerfile I have this line that seems to clear the issue up.

```docker
RUN sudo apt-get install libunwind-dev -y
```

**Comment by maxfriedmann** [comment]
This is done in https://hub.docker.com/r/azuresdk/autorest/dockerfile already, so you can use that image.

**Comment by maxfriedmann** [comment]
Or use `registry.gitlab.com/smallstack/infrastructure/autorest-git-node:master` if you also need Git

**Comment by MiYanni** [comment]
Answers were suggested. Closing.
