### ISSUE TITLE
naming conflict for "models"

### ISSUE THREAD

**Issue by KeXu444** [Azure/autorest#3226]
If there are api/actions with tags "Model" exist.
Then in generated typescript operations, a models class will be generated, which conflicts with pre-existing "Models" in model folder

**Comment by KeMicrosoft** [comment]
to be clear, looks like the word "models" is from operation Id
If I use "operationId": "Models_QueryById", it will generate an issue.

**Comment by fearthecowboy** [comment]
We're not making changes to V2-generators, but I'll add this as a test scenario for AutoRest 3.0.
