### ISSUE TITLE
Support for pagination using continuation token.

### ISSUE THREAD

**Issue by grmadala** [Azure/autorest#3237]
I am currently using autorest to generate a combined swagger for all my micro services and planning to extend its usage to generate language specific libraries.

Most of my micro services use pagination with continuation token(instead of nextpageuri) to handle page-able responses by operations.

ContinuationToken is an opaque string that may be provided in a subsequent request to the same URL in order to continue the list. If ContinuationToken is not null, then the list is not complete, and the token may be used to retrieve the remaining elements. A null value indicates that the list has no remaining items yet to be returned.

For getting next set of objects, client should call the exact same URL as in the original request whose response produced the continuation token, except that it should add that continuation token in the optional continuationToken query parameter that those APIs support and remove all the other optional API parameters.

I don't see continuation token being supported by x-ms-pageable. 
Is there a plan to support it in the future?
Is there a work around for me to make them compatible?

The documentation say x-ms-pageable extension can be used only by azure-arm. what does it mean? My service is not an azure-arm

**Comment by fearthecowboy** [comment]
It's not a scenario currently supported. Added to the autorest 3.1 discussion
