### ISSUE TITLE
AutoRest C# 401 Unauthorized

### ISSUE THREAD

**Issue by printvisa** [Azure/autorest#3242]
I generated client using below command,

autorest --namespace=Testporject --add-credentials --input-file=C:\temp\swagger.json --output-folder=Testproject --csharp

When I call a method in the client, I am getting 401 Unauthorized. It is Asp.net core webapi which works fine from Swagger (browser)

Any idea why?

**Comment by datr93** [comment]
@printvisa did you find a fix? running into the same issue.

**Comment by jasonsee61** [comment]
You may want to give [NSWag](https://github.com/RicoSuter/NSwag), which works pretty well for me. Hope this helps.

**Comment by fearthecowboy** [comment]
You need to add support for how you authenticate to the service. 

`--add-credentials` adds support for credentials, but not how they are used.
