### ISSUE TITLE
Support Model only mode from cli

### ISSUE THREAD

**Issue by erick-thompson** [Azure/autorest#3246]
I have a fairly common need of generating models only from a Swagger/OpenAPI definition. I found the approach detailed in https://github.com/Azure/autorest/issues/2847, but this is C# specific. The clients for these APIs are in csharp, node, typescript, and python. I can probably figure out the transforms for these languages, but it seems like this should be able to done via the command line.

For example:

autorest --model-only --nodejs --input-file=...

**Comment by fearthecowboy** [comment]
Adding to v3 design discussion.

see #3332
