### ISSUE TITLE
create a readme for autorest contributors

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#325]
This readme should provide instructions for creating a new feature in the generators and client runtimes which will require unit tests and integration tests. This should include (at a min) the following:

- Regeneration of expected output (gulp regenerate:expected)
- Add Unit tests executed by each client runtime (node example see: https://github.com/Azure/autorest/tree/dev/ClientRuntimes/NodeJS/ms-rest/test)
- Extending the integration tests (see: Test Server: https://github.com/Azure/autorest/tree/dev/AutoRest/TestServer and example of Node tests against the Test Server: https://github.com/Azure/autorest/tree/dev/AutoRest/Generators/NodeJS/NodeJS.Tests)

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
