### ISSUE TITLE
Allow x-ms-long-running-operation to support Operation-Location

### ISSUE THREAD

**Issue by bojunehsu** [Azure/autorest#3251]
Azure Cognitive Services currently returns the operation response uri via the Operation-Location header instead of the recommended Azure-AsyncOperation or Location.  Thus, it is not possible to use AutoRest to generate such a long running operation.  Can we extend x-ms-long-running-operation-options to specify arbitrary headers to obtain the response uri?  For example:

```
"paths": {
  "/products/{name}": {
    "put": {
      "operationId": "products_create",
      "x-ms-long-running-operation": true,
      "x-ms-long-running-operation-options" : {
          "header": "Operation-Location"
      },
      "description": "A pageable list of Products."
    }
  }
}
```

**Comment by fearthecowboy** [comment]
Adding to v3 design discussion.

see #3332
