### ISSUE TITLE
x-ms-pageable extension support for non Azure-Arm swaggers

### ISSUE THREAD

**Issue by grmadala** [Azure/autorest#3252]
we (Azure Machine Learning services Team) are planning to take dependency over autorest tool to generate client specific libraries. we have around 70 API calls in total and many calls among them return paginated results which makes x-ms-pageable extension a very useful feature to have.

From the Documentation, x-ms-pageable extension is currently supported only for Azure-Arm swaggers, can we extend the support to non Azure swaggers to take advantage of this feature?

Does autorest have a plan to support this feature? If so, can you guys provide an ETA for this feature? This will help to timeline our client side work accordingly.

**Comment by fearthecowboy** [comment]
We may be able to handle this in the v3 generators.

Adding to v3 design discussion.

see #3332
