### ISSUE TITLE
Unexpected "might be pageable" warning

### ISSUE THREAD

**Issue by EvgenyAgafonchikov** [Azure/autorest#3254]
Repro:
1. Clone https://github.com/Azure/azure-rest-api-specs
2. git checkout network-april-release
3. cd azure-rest-api-specs\specification\network\resource-manager
4. Run autorest --azure-validator --openapi-type=arm
5. Look for the warning like
```
WARNING (PageableOperation/R2029/SDKViolation): Based on the response model schema, operation 'AzureFirewalls_Get' might be pageable. Consider adding the x-ms-pageable extension.
    - file:///C:/Projects/azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/azureFirewall.json:87:9 ($.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/azureFirewalls/{azureFirewallName}"].get)
```

Expected:
No warning for get method that doesn't return list of objects.

Details:
[Response type](https://github.com/Azure/azure-rest-api-specs/blob/network-april-release/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/azureFirewall.json#L119) doesn't look as a typical list result: [Link](https://github.com/Azure/azure-rest-api-specs/blob/network-april-release/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/azureFirewall.json#L359)

Note:
Command `autorest --azure-validator --openapi-type=arm --tag=package-2019-02` doesn't shows the same warning though the only meaningful change between versions is adding of zones property and related examples.

**Comment by fearthecowboy** [comment]
The configuration file `readme.md` has suppression entries for that.
