### ISSUE TITLE
PowerShell examples for Autorest not working

### ISSUE THREAD

**Issue by dcaro** [Azure/autorest#3259]
The nyt example provided here: https://github.com/Azure/autorest/tree/master/docs/powershell/samples 
fails to compile with the following issue using autorest version: 3.0.5199

`./generated/build-module.ps1 -Run
Creating isolated process...
Cleaning build folders...
Compiling module...
generated/api/Models/TimesNewswireIdentity.TypeConverter.cs(119,52): error CS0117: 'TimesNewswireIdentity' does not contain a definition for 'Id' [/Users/dcaro/test/nyt/generated/TimesNewswire.csproj]
/Users/dcaro/test/nyt/generated/build-module.ps1 : Compilation failed.
At /Users/dcaro/test/nyt/generated/build-module.ps1:70 char:3
+   Write-Error 'Compilation failed.'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1
`

**Comment by ili101** [comment]
I'm getting the same error on version 3.0.5454. Please help.

**Comment by dcaro** [comment]
@ili101 this has been fixed with the version from earlier today. Please clean the generated files and give it a try.

**Comment by ili101** [comment]
Working Thank you
