### ISSUE TITLE
Add command-line argument to increase plugin lock timeout

### ISSUE THREAD

**Issue by daschult** [Azure/autorest#3260]
I am running several (5 - 6) instances of autorest at the same time and each one needs to install different plugins. Sometimes (not very often) I get the following error message:
```
Error: Unable to acquire exclusive lock on '_root_.autorest.busy-lock' before timeout 20000 msec.
```
I understand that under normal circumstances 20 seconds would be plenty of time, but my scenario isn't a very normal circumstance. Please allow me to pass in the number of seconds that the plugin lock should wait before timing out, such as:
```
autorest ... --plugin-lock-timeout=60s
```

**Comment by fearthecowboy** [comment]
I'm deferring this until AutoRest 3.1+
