### ISSUE TITLE
Port is removed from URL in generated c# client

### ISSUE THREAD

**Issue by Keschke** [Azure/autorest#3267]
Hi,

When I generate a C# client the port will no be imported in the base url in the generated C# code.

Snpitted from the openapi json:
{
    "openapi": "3.0.1",
     "info": {
        "title": "PocService",
        "version": "1.0"
    },
 "servers": [
    {
      "url": "https://localhost:8475",
      "variables": {
        "Port": {
          "default": "8475",
          "enum": [
            "8475"
          ]
        }
      }
    }
  ],
...

C# client:
        private void Initialize()
        {
        . ...
            BaseUri = new System.Uri("http://localhost");
        ....
       }

Autorest version:
![image](https://user-images.githubusercontent.com/33954372/59088206-1f097280-8907-11e9-9284-17c57bdb8124.png)

Do I set the port wrong in the json or is this a bug in the Autorest beta?

Thanks in advance!

**Comment by Keschke** [comment]
Ok, this bug is now solved. 
So I close this issue.

Thanks! :)

**Comment by ansgarm** [comment]
How did you solve it? I noticed the same behavior of autorest dropping properties that only have a single value valid specified via `enum`.

**Comment by Keschke** [comment]
I did nothing. Maybe the fixed it with some update. 
With the above used swagger.json the generated client BaseUri gets the port,
