### ISSUE TITLE
AutoRest does not allow access to anonymous access endpoints when --add-credentials is used

### ISSUE THREAD

**Issue by perezdev** [Azure/autorest#3268]
As far as I understand, I have to instantiate an instance of the primary client class in order to call the extension methods. When I browse through the public constructors, I find these five:

`public IOIWebAPI(ServiceClientCredentials credentials, params DelegatingHandler[] handlers) : this(handlers)`

`public IOIWebAPI(ServiceClientCredentials credentials, HttpClient httpClient, bool disposeHttpClient) : this(httpClient, disposeHttpClient)`

`public IOIWebAPI(ServiceClientCredentials credentials, HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : this(rootHandler, handlers)`

`public IOIWebAPI(System.Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers) : this(handlers)`

`public IOIWebAPI(System.Uri baseUri, ServiceClientCredentials credentials, HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : this(rootHandler, handlers)`

Each one of these constructors requires `ServiceClientCredentials.` In my case, my auth is bearer tokens. So I need to create `TokenCredentials` and pass it in the constructor. The issue is that in order to get the auth token, I have to call one of the endpoints. But I can't call the endpoint without having the token. It's a circular issue. Instead, I create a separate helper class to call the login endpoint manually and then pass those details to the main client class when I create it. It works but isn't ideal.

**Comment by fearthecowboy** [comment]
there currently isn't a way to have some operations without credentials.
