### ISSUE TITLE
Import statements is missing when generating Java code

### ISSUE THREAD

**Issue by m-moris** [Azure/autorest#3278]
@jianghaolu 

I'm trying to generate Java code, some implementation class does not have following import statements.

```
import okhttp3.MediaType;
import okhttp3.RequestBody;
```

I debugged and I fixed this problem in my forked repository. I can not determine if this fix is correct. Please fix this problem correctly, or should I create a pull request?

https://github.com/m-moris/autorest.java/commit/82205f5ee673c7503fe0aa69cdb9b970741c844d

Thanks.

**Comment by lmazuel** [comment]
Hi @m-moris 
Please create a pull on the autorest.java and tag @anuchandy on it (or mention it in text if you can't set reviewers).
Thanks!
