### ISSUE TITLE
Autorest fails to create client with multiple enums

### ISSUE THREAD

**Issue by nbp828** [Azure/autorest#3281]
My controller has an enum property, but the enum property has two items mapped to the same value. This is causing an error during the client creation.

**enum class**

    public enum HttpStatusCode
    {
        Continue = 100,
        SwitchingProtocols = 101,
        OK = 200,
        Created = 201,
        Accepted = 202,
        NonAuthoritativeInformation = 203,
        NoContent = 204,
        ResetContent = 205,
        PartialContent = 206,
        MultipleChoices = 300,
        Ambiguous = 300,
        MovedPermanently = 301,
        Moved = 301,
        Found = 302,
        Redirect = 302,
        SeeOther = 303,
        RedirectMethod = 303,

**autorest command:**
E:\Projects\DropServices\ArtifactService\MS.Eng.AS.TypeScriptClient> autorest --input-file=swagger2.json --typescript --output-folder=E:\Projects\DropServices\ArtifactService\MS.Eng.AS.TypeScriptClient --typescript.namespace=MS.Eng.AS.TypeScriptClient --verbose --add-credentials
AutoRest code generation utility [version: 2.0.4283; node: v10.16.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\neipatel\.autorest\@microsoft.azure_autorest-core@2.0.4387\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4387)
No configuration found at 'file:///E:/Projects/DropServices/ArtifactService/MS.Eng.AS.TypeScriptClient/'.
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.683)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
ERROR: Schema violation: Array items are not unique (indexes 9 and 10)
    - file:///E:/Projects/DropServices/ArtifactService/MS.Eng.AS.TypeScriptClient/swagger2.json:1:18102 ($.definitions.HttpResponseMessage.properties.statusCode.enum)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.

**json file:**
"statusCode":{"format":"int32","enum":[100,101,200,201,202,203,204,205,206,300,300,301,301,302,302,303,303,304,305,306,307,307,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,426,500,501,502,503,504,505]

**Comment by fearthecowboy** [comment]
AutoRest v2 definitely doesn't like duplicate values. 

Sorry, the only solution I have right now, is 'don't have duplicate values' 

In our planning for driving towards a stable '3.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-3.0 planning cycle.

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 3.0._ 🏇 🏇 🏇

see #3333
