### ISSUE TITLE
Serialization/Deserialization drops null values

### ISSUE THREAD

**Issue by hvermis** [Azure/autorest#3288]
There are scenarios where property being present with null value has different meaning than not specified property. Autorest serialization always drops them, which creates issues for our customers.
Example: We have a stored procedure type which has parameters. If parameter is not specified, that means the customer made a mistake by forgetting about that parameter, but if it is present with null value, then it should be passed to the procedure as null. It causes issues with our validations.

**Comment by johanste** [comment]
@hvermis , can you please add a link to the openapi specification that describes the API for which autorest exhibits the problematic behavior? It can help us scope the problem. @weshaggard may be interested in this discussion...

**Comment by hvermis** [comment]
This is our model that is currently hitting it:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L2425

**Comment by johanste** [comment]
My first observation is that none of the properties are marked as `"x-ms-nullable": true` in this swagger document. Which would have to be the first thing that needed to be changed.

My second question is, assuming that it is the value property of the #/definitions/StoredProcedurParameter that is nullable, what is the difference between omitting the `value` attribute and specifying the `value` attribute with a `null` value?

**Comment by hvermis** [comment]
When the value is omitted the parameter is not passed to the executor, when the parameter is present with null value, that gets passed on.

**Comment by johanste** [comment]
And what would happen if you specify a key (name) in the [`storedProcedureParameters`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L2678) with a `null` value?

**Comment by fearthecowboy** [comment]
AutoRest V2 generators don't support sending `null` values across the wire.

In our planning for driving towards a stable '3.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-3.0 planning cycle.

see #3333

**Comment by msfcolombo** [comment]
Related: #4929
