### ISSUE TITLE
Setting x-nullable on string field

### ISSUE THREAD

**Issue by amiramit** [Azure/autorest#3300]
I'm trying to create a string field which could accept null (using x-nullable: true), but when I run the generated code Validate() method I'm getting back error: 

Message: Microsoft.Rest.ValidationException : 'Query' cannot be null.

**Link to relevant line in swagger:**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/Microsoft.Security/stable/2019-08-01/iotSecuritySolutions.json#L460

**Generated validate() code:**
```
        public virtual void Validate()
        {
            if (Query == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Query");
            }
            if (QuerySubscriptions == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "QuerySubscriptions");
            }
        }
```

**Comment by amiramit** [comment]
Hi, Any updates about this?

**Comment by fearthecowboy** [comment]
Support for `x-nullable` is not quite as expected in Autorest 2.0.

The only thing you can do at this point is mark it not-required. 

--- 

In our planning for driving towards a stable '3.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-3.0 planning cycle.

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 3.0._ 🏇 🏇 🏇

We'll make sure we pick this back up at that point. 🎉
