### ISSUE TITLE
Does there any plans to support ServiceProjectReference tag?

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#3303]
With .NET Core 2.2 introduced tag `ServiceProjectReference` which allow code generators to pickup generation of the clients for the services. That allow run code generation as part of the build without need of having global autorest tool installed.

**Comment by fearthecowboy** [comment]
In our planning for driving towards a stable '3.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-3.0 planning cycle.

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 3.0._ 🏇 🏇 🏇

We'll make sure we pick this back up at that point. 🎉

see #3333
