### ISSUE TITLE
Enable-xml doesn't seem to respect produces/consumes on each operation

### ISSUE THREAD

**Issue by officeSpacePirate** [Azure/autorest#3329]
I work on a few C# web APIs and we are trying to use generated autorest libraries for our client teams and test suites. The majority of our controllers return JSON, but we have a few endpoints that return XML instead for integration with other applications we don't manage. By adding `--enable-xml=true` it appears that every method gets an `if (_httpResponse.Content.Headers.ContentType.MediaType == "application/xml"...` instead of only the ones that produce/consume application/xml.

Is there something I'm missing or is this the only support for XML from autorest right now?

**Comment by fearthecowboy** [comment]
Yeah, the existing c# generator does that. It's being re-written, with XML in the mix from up front so this shoudn't be a problem in the new generator.

**Comment by officeSpacePirate** [comment]
@fearthecowboy Is there a ticket or release I can watch? I am currently not able to use the client for one use case until the new version is available.

**Comment by fearthecowboy** [comment]
We're just getting the project tracking set up right now.

Probably in the next week or so there should be something to track either in this repo or azure/autorest.csharp
