### ISSUE TITLE
AutoRest 3.0 Design Issues Rollup

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#3332]
I'm collection AutoRest 3.0 design issues here, so that things that need to be addressed are in a single location.

Design:
- Expanding LRO  supoprt? (ref #3251)
- Expanding pagable support? (ref #3252)
- Model-only generation (ref #3246)
- descriptions for x-ms-parameter-group (see #1310)

- Pick request body type when multiple are offered? ( ref #3239)
- support other credential types in generation (see #2672, #2918) 

Test Scenarios:
- Ensure that 'models' operation group doesn't fail. ( see #3226)
- Allow default values that are arrays (see #3188)
- relax schemas to pass some x-ms-docs (#3207)
- scientific notation breaks validation (#3006)

**Comment by daviwil** [comment]
@dima117 There are many issues being discussed here.  Is there something in particular you're interested in?

**Comment by dima117** [comment]
I'm interested in https://github.com/Azure/autorest/issues/3188

**Comment by cyptus** [comment]
@daviwil is there any progress at #3246 ?
