### ISSUE TITLE
x-ms-enum enum with value

### ISSUE THREAD

**Issue by auriou** [Azure/autorest#3334]
is it possible to add values for the enum with  x-ms-enum  attribut ?
by default enum values is 0 ,  1,  2 ...

```
public enum RelaisColisService
{
    ExpressReturn = 8,
    SmartReturn = 9
}
```

**Comment by fearthecowboy** [comment]
You want numeric values for enums? I don't recall if we currently support numeric values for that at the moment.

**Comment by fearthecowboy** [comment]
Not possible for certain without the attribute.
