### ISSUE TITLE
Block issues in autorest core

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3336]
The latest autorest core (version:3.0.6138) failed to generate some services for powershell. And there must be some blocking regression issues in recent changes since the @autorest/autorest 3.0.6130 still works fine.

For detailed failing info, please refer to https://dev.azure.com/azure-sdk/public/_build/results?buildId=191110&view=logs&jobId=66ba4e4b-0549-5b2a-428e-6f5c762b53a8&j=dd663787-6ee6-5df3-6274-f7ede4d40085.

**Comment by fearthecowboy** [comment]
Fixed it, reran the tests.
