### ISSUE TITLE
Error: autorest swagger validation fails on my machine but passes for others

### ISSUE THREAD

**Issue by ranishan** [Azure/autorest#3340]
When running the following command for validating Swagger I get an error on my machine. The validation with the same command passes on other machines. I have tried 'autorest --reset' but that does not help.

Command:
>autorest --input-file=swagger.json --azure-validator

Failure log:
AutoRest code generation utility [version: 2.0.4407; node: v12.13.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407
   Loading AutoRest core      'C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4407)
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
/node_modules/vscode-jsonrpc/lib/messageReader.js:68
                throw new Error('Message header must separate key and value using :');
                ^

Error: Message header must separate key and value using :
    at /node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at Socket.<anonymous> (/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at Socket.emit (events.js:215:7)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

Versions I am using:
>autorest --version
AutoRest code generation utility [version: 2.0.4407; node: v12.13.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Showing All Installed Extensions
 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4407     C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407
 extension  @microsoft.azure/classic-openapi-validator 1.0.14       C:\Users\ranishan\.autorest\@microsoft.azure_classic-openapi-validator@1.0.14
 extension  @microsoft.azure/openapi-validator       1.0.4        C:\Users\ranishan\.autorest\@microsoft.azure_openapi-validator@1.0.4
 extension  oav                                      0.4.70       C:\Users\ranishan\.autorest\oav@0.4.70

>npm --version
6.13.1

>node --version
v12.13.1

**Comment by fearthecowboy** [comment]
It looks like something is printing to stdout in the extension.

What does `autorest --info ` show? 

can you do the same thing with `--debug --verbose` and capture the output?

**Comment by ranishan** [comment]
> autorest --info
AutoRest code generation utility [version: 2.0.4407; node: v12.13.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4407     C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407
 extension  @microsoft.azure/classic-openapi-validator 1.0.14       C:\Users\ranishan\.autorest\@microsoft.azure_classic-openapi-validator@1.0.14
 extension  @microsoft.azure/openapi-validator       1.0.4        C:\Users\ranishan\.autorest\@microsoft.azure_openapi-validator@1.0.4
 extension  oav                                      0.4.70       C:\Users\ranishan\.autorest\oav@0.4.70


With --verbose and --debug and removing some of the validator options
> autorest --input-file=C:\Users\ranishan\sql-iaas\out\Debug\x64\arm.gen.csproj\swagger\Microsoft.SqlVirtualMachine\2017-03-01-preview\swagger.json --azure-validator --debug --verbose
AutoRest code generation utility [version: 2.0.4407; node: v12.13.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407
   Loading AutoRest core      'C:\Users\ranishan\.autorest\@microsoft.azure_autorest-core@2.0.4407\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4407)
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
/node_modules/vscode-jsonrpc/lib/messageReader.js:68
                throw new Error('Message header must separate key and value using :');
                ^

Error: Message header must separate key and value using :
    at /node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at Socket.<anonymous> (/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at Socket.emit (events.js:215:7)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

**Comment by fearthecowboy** [comment]
I can't tell what's spewing text into the stream; at this point, I recommend you update to the latest v3 RC and try again:

``` bash
# install the v3 RC
npm install -g https://github.com/Azure/autorest/releases/download/autorest-3.0.6187/autorest-3.0.6187.tgz

# reset the plugins
autorest --reset

# try again
autorest --input-file=C:\Users\ranishan\sql-iaas\out\Debug\x64\arm.gen.csproj\swagger\Microsoft.SqlVirtualMachine\2017-03-01-preview\swagger.json --azure-validator  

```
