### ISSUE TITLE
Error: Unable to start AutoRest Core

### ISSUE THREAD

**Issue by kitzmark** [Azure/autorest#3341]
I have not been able to get past this for a couple of days. I have tried different versions, tried to install nodejs via nvm, choco and msi installer. Always the same error trying to use autorest.  This was working a few months ago, it might have stopped when I reinstalled Nodejs (this time inclusing Chocolatey)

AutoRest code generation utility [version: 2.0.4407; node: v13.2.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to start AutoRest Core from C:\Users\kitzmark.autorest@microsoft.azure_autorest-core@2.0.4407\node_modules@microsoft.azure\autorest-core
Error: Unable to start AutoRest Core from C:\Users\kitzmark.autorest@microsoft.azure_autorest-core@2.0.4407\node_modules@microsoft.azure\autorest-core
at main (C:\Users\kitzmark\AppData\Roaming\npm\node_modules\autorest\dist\app.js:233:19)

**Comment by iatodoro** [comment]
I was able to get around this issue by running `autorest --reset` after installing from npm

**Comment by kitzmark** [comment]
Thanks for the reply. I get the same error with the autorest --reset command.

**Comment by rolfec** [comment]
Encountered the same issue a couple of times and sometimes `autorest --reset` fixes it if you're lucky.

Here are some open-source alternatives you can try while waiting for a permanent fix in autorest:

- NSWag: https://github.com/RicoSuter/NSwag
- OpenAPI Generator: https://github.com/OpenAPITools/openapi-generator

**Comment by fearthecowboy** [comment]
I haven't tested with unstable NodeJS 13.x.

The v3 beta *might* work 

``` powershell
# install autorest beta
npm install -g @autorest/autorest

# use `autorest-beta` instead of `autorest`
autorest-beta --reset 
```

**Comment by fearthecowboy** [comment]
Pretty sure this was a node 13 incompatibility.
autorest-beta should be working.

**Comment by george-chakhidze** [comment]
Tried using `autorest-beta`, received this error:

```
AutoRest code generation utility [version: 3.0.6149; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6149'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6149'.
    at Object.selectVersion (C:\Users\gchakhidze\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\autorest-as-a-service.js:228:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Exactly same error with NodeJS v13.6.0 too.

**Comment by fearthecowboy** [comment]
@george-chakhidze 

O_o 

I just tried it on a blank machine 
can you run: `autorest-beta --reset` and then `autorest-beta --help --verbose --debug`

**Comment by george-chakhidze** [comment]
@fearthecowboy Thanks for reply. `autorest-beta --help --verbose --debug` failed with the same error. Full output:

```
> autorest-beta --reset

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.6.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Cleared the AutoRest extension folder.
On the next run, extensions will be reacquired from the repository.
```

and then:

```
> autorest-beta --help --verbose --debug

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.6.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6149'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6149'.
    at Object.selectVersion (C:\Users\gchakhidze\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\autorest-as-a-service.js:228:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by fearthecowboy** [comment]
Are you behind a proxy of some kind?

**Comment by george-chakhidze** [comment]
@fearthecowboy Oh, sorry, I should've mentioned it from the start: I'm behind Forcepoint Content Gateway (HTTP proxy with NTLM authentication), that is performing TLS MITM content sniffing by decrypting traffic and replacing server certificates with its own. I have configured NodeJS/npm accordingly, inside `.npmrc`:

```
strict-ssl=false
proxy=http://proxyhostname/
https-proxy=http://proxyhostname/
```

Also `HTTP_PROXY` and `HTTPS_PROXY` environment variables are defined; and NodeJS TLS validation is disabled too: `NODE_TLS_REJECT_UNAUTHORIZED=0`

npm itself does work, I can install other packages from npmjs.com (autorest is the exception).

**Comment by fearthecowboy** [comment]
Ah, it uses `yarn` internally. I would have hoped that yarn picked up the settings from npmrc but it might not.

let's try:

``` sh
# let's install yarn so we can easily configure it.
npm install -g yarn

# set strict-ssl to false
yarn config set strict-ssl false

# yarn proxy 
yarn config set proxy http://proxyname/
yarn config set https-proxy http://proxyname/
```

**Comment by kitzmark** [comment]
installing yarn fixed it for me, too.  I only had to run the strict-ssl false command.

thanks!

**Comment by drmcclelland** [comment]
The suggestion to install yarn separately worked for me, then I was able to issue the command `yarn config set strict-ssl false -g` to fix this error message:

```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Yarn log:
--------------------------------------------------
{"type":"info","data":"No lockfile found."}
{"type":"step","data":{"message":"Resolving packages","current":1,"total":4}}
{"type":"error","data":"An unexpected error occurred: \"https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz: unable to get local issuer certificate\"."}
{"type":"info","data":"If you think this is a bug, please open a bug report with the information provided in \"C:\\\\Users\\\\dmcclelland1\\\\.autorest\\\\@autorest_csharp@3.0.0-beta.20210428.6\\\\yarn-error.log\"."}
{"type":"info","data":"Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command."}

--------------------------------------------------
Failure:
Error: Package '@autorest/csharp' - '3.0.0-beta.20210428.6' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz' -- Error: Process Failed.
```
