### ISSUE TITLE
AutoRest V3 - Validate current V2 generators work unmodified without breaking generated code

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#3342]
Validation for AutoRest V3: 
 - generate the contents of the rest-specs repo with the current V2 build, for each language generator (c#, java, python, go, typescript)
 - generate the same with v3 build; identify if there are unacceptable breaking changes in the generated code
 - identify that 

Known Issues: 
 - Validator will not work on V3, because the step that converts to openapi3 is much earlier in the pipeline, a new validator will be required for AutoRest V3. (existing validator will still work with v2)
 - Ruby did not upgrade to the correct v2 modeler (a couple years ago), and probably fails on v3. Not sure if this is a concern.

**Comment by daviwil** [comment]
Is this issue still relevant now that v2 generators can now be executed with the v2 pipeline in v3?  Or do we still want to validate v2 generators with v3 pipeline?
