### ISSUE TITLE
Project status? new release?

### ISSUE THREAD

**Issue by wendyleach** [Azure/autorest#3346]
What's the status of this project? Is it still actively maintained? Is there a new release (v3?) ?

I notice a lot of issues (150+) have been closed recently but haven't seen any release with fixes to those issues.

**Comment by fearthecowboy** [comment]
We're working on a new release right now.  Outside of some specifics for Azure (multi-api-version/profiles), the primary thing this adds is support for OpenAPI3. 

The language-specific issues have been migrated out to the language generator repositories.

I've been collecting a lot of the issues to schedule features in the upcoming releases. 

We're also working on a new set of generators (c#, typescript, go, python, java) that produce code in line with the new Azure Core guidelines.

**Comment by fearthecowboy** [comment]
As soon as we reach some stability with the v3 release, I'm looking down the road for v4, where we can really address some of the functionality gaps and address some performance issues with extremely-large api-surfaces that v3 introduced.

**Comment by wendyleach** [comment]
Sad to hear the reorg turns this project into chaos.

For Ruby-related issues like https://github.com/Azure/autorest/issues/2806, where is the best repo to track these moving forward?

**Comment by rolfec** [comment]
> For Ruby-related issues like #2806, where is the best repo to track these moving forward?

You may have better luck with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator), which supports many more generators including Ruby and is a lot more active.

[NSWag](https://github.com/RicoSuter/NSwag) is also a pretty good alternative but doesn't come with a Ruby client generator.

Hope this helps.

**Comment by wendyleach** [comment]
Thanks for the tips. I'm aware of these alternatives. We've several teams in my company piloting these alternatives and are pretty happy with the result so far.

**Comment by fearthecowboy** [comment]
The 3.0 RC can be installed by
``` bash
# Install from github link
npm install -g https://github.com/Azure/autorest/releases/download/autorest-3.0.6180/autorest-3.0.6180.tgz

# reset the plugins
autorest --reset
```

The V3 release is only days away, but we have a few Azure-specific fixes to put in.
