### ISSUE TITLE
Add New OAI Validator plugin

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#3359]
We need a validator/linter plugin that checks the quality of the documents, and allows for an easy expression of new checks.

I'm thinking a linting rule should be simple enough to express as a single statement: 

``` javascript
$.operations.where( each => !each.operationId  ).error( `Operations must have an 'operationId' field` , 'MissingOperationId', 'A1010');

```

**Comment by qiaozha** [comment]
@fearthecowboy hi, I've create a new issue in azure-openapi-validator repo to track the process.
