### ISSUE TITLE
“- remove-operation” directive does not work in autorest v3

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3367]
How "- remove-operation" work could be found in https://github.com/Azure/autorest/tree/master/Samples/test/remove-methods.

**Comment by fearthecowboy** [comment]
Hmm. the internal configuration needed a correction. 

With autorest/core v3.0.6237 you can remove an operation by it's `operationId` again. 

``` yaml 
directive: 
  - remove-operation: users_createOrUpdate  
```

**Comment by dolauli** [comment]
Verified.
