### ISSUE TITLE
Specifying a swagger file in private repo with "input-file" in readme.md does not work

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3368]
It works well if the swagger file is located in https://github.com/Azure/azure-rest-api-specs. But if the swagger file is located in a private repo, it will report an error as below.
![error](https://user-images.githubusercontent.com/11451757/71875906-6f2c0a00-3160-11ea-8dfa-c9b973ee269b.jpg)

**Comment by fearthecowboy** [comment]
You can create a github auth token and use it on the command line:

` --github-auth-token=<string>  OAuth token to use when pointing AutoRest at files living in a private GitHub repository`

**Comment by dolauli** [comment]
@fearthecowboy  Would you confirm whether it works?

I still run into the same issue even using the token. And I follow the instruction in https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line to create the token with all permissions granted.

```
PS C:\Users\xidi\src\azure-powershell-pr\src\Desktopvirtualization> autorest.cmd --github-auth-token=my-token-here --debug
AutoRest code generation utility [cli version: 3.0.6187; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\xidi\.autorest\@autorest_core@3.0.6274
   Loading AutoRest core      'C:\Users\xidi\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.337)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
DEBUG [5.36 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [5.37 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [5.42 s]: pipeline-emitter - START inputs = 0
DEBUG [5.47 s]: configuration-emitter - START inputs = 0
DEBUG [5.5 s]: pipeline-emitter - END [0.13 s]
DEBUG [5.51 s]: configuration-emitter - END [0.14 s]
C:\Users\xidi\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
C:\Users\xidi\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Could not read 'https://github.com/datr93/azure-rest-api-specs-pr/blob/master/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2019-12-10-preview/desktopvirtualization.json'. / Error: Could not read 'https://github.com/datr93/azure-rest-api-specs-pr/blob/master/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2019-12-10-preview/desktopvirtualization.json'.
    at ReadThroughDataSource.ReadStrict (/node_modules/@azure-tools/datastore/dist/data-store/data-store.js:44:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Could not read 'https://github.com/datr93/azure-rest-api-specs-pr/blob/master/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2019-12-10-preview/desktopvirtualization.json'.
[6.12 s] Shutting Down.
[6.12 s] Exiting.
```

**Comment by daviwil** [comment]
Reopening so that I can investigate whether this is still an issue.  @dolauli, are you still having trouble with this?

**Comment by dolauli** [comment]
@daviwil I just have a try with the latest autorest. The issue still exists.
```
PS C:\Users\xidi\src\azure-powershell\src\Databricks> autorest --github-auth-token=<my-token-here> --debug
AutoRest code generation utility [cli version: 3.0.6247; node: v10.16.0, max-memory: 1280 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
(node:27316) ExperimentalWarning: The fs.promises API is experimental
Starting @autorest/core from C:\Users\xidi\.autorest\@autorest_core@3.0.6320
   Loading AutoRest core      'C:\Users\xidi\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
(node:2400) ExperimentalWarning: The fs.promises API is experimental
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.401)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
DEBUG [2.42 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.42 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.46 s]: pipeline-emitter - START inputs = 0
DEBUG [2.54 s]: configuration-emitter - START inputs = 0
DEBUG [2.58 s]: pipeline-emitter - END [0.16 s]
DEBUG [2.59 s]: configuration-emitter - END [0.17 s]
C:\Users\xidi\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
C:\Users\xidi\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Could not read 'https://github.com/Azure/azure-rest-api-specs-pr/blob/9120c925c8de6840da38365bb8807be2e0e617c0/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json'. / Error: Could not read 'https://github.com/Azure/azure-rest-api-specs-pr/blob/9120c925c8de6840da38365bb8807be2e0e617c0/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json'.
    at ReadThroughDataSource.ReadStrict (/node_modules/@azure-tools/datastore/dist/data-store/data-store.js:44:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Could not read 'https://github.com/Azure/azure-rest-api-specs-pr/blob/9120c925c8de6840da38365bb8807be2e0e617c0/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json'.
[3.38 s] Shutting Down.
[3.38 s] Exiting.
```

**Comment by ChristopherL-STCU** [comment]
I also experience the same issue while specifying a `github-auth-token`. I am inside a network which uses self signed certificates. This has caused issues with other tools in the past. I do not see any indication that this is the reason for the failure I'm experiencing, but still a possibility.

> (C) 2018 Microsoft Corporation.
> https://aka.ms/autorest
> Network Enabled: true
> Starting @autorest/core from C:\Users\christopherl\.autorest\@autorest_core@3.0.6320
>    Loading AutoRest core      'C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
>    Loading AutoRest extension '@autorest/azure-functions-csharp' (latest->0.2.0-preview-dev.321054549)
>    Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
> DEBUG [2.02 s]: swagger-document/loader-swagger - START inputs = 0
> DEBUG [2.02 s]: openapi-document/loader-openapi - START inputs = 0
> DEBUG [2.02 s]: pipeline-emitter - START inputs = 0
> DEBUG [2.07 s]: configuration-emitter - START inputs = 0
> DEBUG [2.08 s]: pipeline-emitter - END [0.05 s]
> DEBUG [2.08 s]: configuration-emitter - END [0.05 s]
> C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
> C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
> Process() cancelled due to exception : Could not read 'https://github.com/ChristopherL-STCU/xxxxxxxxxxxxxx/blob/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'. / Error: Could not read 'https://github.com/ChristopherL-STCU/xxxxxxxxxxxxxx/blob/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'.
>     at ReadThroughDataSource.ReadStrict (/node_modules/@azure-tools/datastore/dist/data-store/data-store.js:44:19)
>     at processTicksAndRejections (node:internal/process/task_queues:93:5)
>     at async LoadLiterateSwagger (C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\loaders.js:37:20)
>     at async LoadLiterateSwaggers (C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\loaders.js:69:29)
>     at async C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\loaders.js:93:26
>     at async ScheduleNode (C:\Users\christopherl\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
>   Error: Could not read 'https://github.com/ChristopherL-STCU/xxxxxxxxxxxxxx/blob/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'.
> [2.57 s] Shutting Down.
> [2.57 s] Exiting.
>

**Comment by timotheeguerin** [comment]
@dolauli Reproduced the same issue when creating a new Github token and trying to access the private spec repo `https://raw.githubusercontent.com/Azure/azure-rest-api-specs-pr/master/specification/adp/resource-manager/Microsoft.AutonomousDevelopmentPlatform/preview/2020-07-01-preview/adp.json`

I believe in this case the issue is due to the Github change with SSO for organization which require to explicitly give a token permission to access an organization as well. After I authorized Azure for the token it worked. See image below
![image](https://user-images.githubusercontent.com/1031227/101676041-75c99e00-3a0f-11eb-8259-1d8baa99f58b.png)

Let me know if that solve your issue.

I think the only issue here is a lack of documentation.

**Comment by ChristopherL-STCU** [comment]
Thank you for the reply and looking into this. I don't see that option next to my personal access token. I do see it [referenced in GitHub's documentation in connection to SAML](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on). So I'm not sure about this setting. But I am trying to retrieve a file in my own private repository, so maybe it isn't relevant for me? 🤷 

I tried using the personal access token in PowerShell. That successfully retrieves the file.
```
$headers = @{"Authorization"="token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";"Accept"="application/yaml"}
Invoke-RestMethod -Method 'GET' -Headers $headers 'https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'
```
So I think the token works. I also tried the request without the token to see what would happen. That resulted in a 404. So I think the token is being used and works in PowerShell.
```
$headers = @{"Accept"="application/yaml"}
Invoke-RestMethod -Method 'GET' -Headers $headers 'https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'
```

**Comment by timotheeguerin** [comment]
@ChristopherL-STCU Could you share the command line you are using(minus the private data). I see in your previous comment you are using the github.com url for the file. Could you try with the `raw.githubusercontent.com` as well.
I do seem to have the same issue with using the `github.com` one but it is working with the raw.

**Comment by ChristopherL-STCU** [comment]
Yes, I wasn't sure what URL was appropriate. My initial usage was based off of an example. I updated it to `raw.githubusercontent.com` after seeing your example (which makes more sense to me to use).

I was using a README.md to execute it. I converted the README to the command line and that does work for me:
```
autorest --version:3.0.6320 --title:"xxxxxxxxxxxxxxxx" --github-auth-token:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --azure-functions-csharp --namespace:xxxxxxxxxxxxxx --input-file:"https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml" --input-file:"https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxx.yaml" --output-folder:"src/xxxxxxxxxxxxxxxxxxxxxxxx"
```

But in the README it still fails for me:

```
version: 3.0.6320
title: xxxxxxxxxxxxxxxx
input-file:
    - https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml
    - https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxx.yaml
github-auth-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
azure-functions-csharp:
    namespace: xxxxxxxxxxxxxx
output-folder: $(this-folder)/src/xxxxxxxxxxxxxxxxxxxxxxxx
```
```
autorest .\README.md
```
> Error: Could not read 'https://raw.githubusercontent.com/ChristopherL-STCU/xxxxxxxxxxxxxx/main/xxxxxxxxxxxxxxxxxxxxxxxx.yaml'.

Perhaps I'm not specifying something correctly in the file?

**Comment by timotheeguerin** [comment]
Can you try passing ` --github-auth-token=`  in the cli instead of in the readme.

`autorest  --github-auth-token=xyz ./Readme`

**Comment by ChristopherL-STCU** [comment]
Yes, that works as well. And I guess that makes sense because the token shouldn't be stored in the README permentatly anyway, so supporting the token in the file does not make sense.

Thanks for the help. I guess my ask would be if when using a configuration file if AutoRest could provide feedback about invalid/unsupported configuration file content which it is being ignored.

**Comment by timotheeguerin** [comment]
I agree, we have some rework of the docs in progress to improve experience. 
I guess the only issue then here is using `github.com` instead of `raw.githubusercontent.com`. I have a fix for that which should let you use `github.com` url.
