### ISSUE TITLE
[Perf] "model-deduplicator" step takes ~8 minutes when processing swagger of data factory

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest#3370]
In Autorest V3, the "model-deduplicator" step takes ~8 minutes when process swagger of data factory: ...\azure-rest-api-specs\specification\datafactory\resource-manager\readme.md

![image](https://user-images.githubusercontent.com/6038235/72063615-10f45800-3315-11ea-9380-0b627309f7da.png)

**Comment by fearthecowboy** [comment]
The deduplicator is an intensive operation. The latest v3 build, with Node 13 will speed that up a lot, but there isn't much that is going to be done at this point.
