### ISSUE TITLE
PHP generator ignores --output-folder on Linux

### ISSUE THREAD

**Issue by kevinoid** [Azure/autorest#3372]
On Linux, the PHP generator appears to ignore the `--output-folder` option.  Using the OpenAPI petstore example in a fresh project:

```sh
cd "$(mktemp -d)"
npm init -y
npm install autorest
wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml
./node_modules/.bin/autorest --php --input-file=petstore.yaml --output-folder=generated-php
```
Fails with the following output:

    AutoRest code generation utility [version: 2.0.4407; node: v10.17.0]
    (C) 2018 Microsoft Corporation.
    https://aka.ms/autorest
       Loading AutoRest core      '/home/kevin/.autorest/@microsoft.azure_autorest-core@2.0.4407/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4407)
       Loading AutoRest extension '@microsoft.azure/autorest.php' (~2.0.12->2.0.16)
       Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
      Error: EACCES: permission denied, open '/SwaggerPetstore.php'

It appears that autorest ignores `--output-folder` and tries to create the files at the filesystem root.

Thanks,
Kevin

**Comment by douyoung** [comment]
FYI. The PHP generator has been deprecated/abandoned https://github.com/Azure/autorest/issues/3064#issuecomment-557661090

**Comment by kevinoid** [comment]
Good to know.  Thanks @douyoung.
