### ISSUE TITLE
--latest and --reset give exception

### ISSUE THREAD

**Issue by deathly809** [Azure/autorest#3374]
```
Windows 10
AutoRest code generation utility [version: 2.0.4407; node: v12.14.1]
```

I installed the newest autorest and when I do the commands,

```
> autorest --latest
> autorest --reset
```

I get the following error,

```
[Exception] No input files provided.
```

Here is the screenshot.

![image](https://user-images.githubusercontent.com/1381210/72197265-414efb80-33d4-11ea-9f01-9fc1d4d262aa.png)

**Comment by fearthecowboy** [comment]
You clipped the picture -- I can't see what version it was trying to use, but I assume it was `2.0.4407`

Hmm. Just did this in a sandbox:

![image](https://user-images.githubusercontent.com/133736/72299932-28825800-3617-11ea-825f-dd8c5e6e8dee.png)

what does `autorest --info ` show

**Comment by deathly809** [comment]
@fearthecowboy This was part of trying to install the beta and I saw this.  I have since uninstalled and have been trying to get the beta to work :(

**Comment by enterprisebug** [comment]
Info:

    PS> autorest --info

    AutoRest code generation utility [version: 2.0.4413; node: v12.6.0]
    (C) 2018 Microsoft Corporation.
    https://aka.ms/autorest


    Showing All Installed Extensions

    Type       Extension Name                           Version      Location
    core       @microsoft.azure/autorest-core           2.0.4413     C:\Users\<User>\.autorest\@microsoft.azure_autorest-core@2.0.4413


Latest:

    PS> autorest --latest

    AutoRest code generation utility [version: 2.0.4413; node: v12.6.0]
    (C) 2018 Microsoft Corporation.
    https://aka.ms/autorest
    Loading AutoRest core      'C:\Users\<User>\.autorest\@microsoft.azure_autorest-core@2.0.4413\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4413)

Reset:

    PS> autorest --reset
    
    AutoRest code generation utility [version: 2.0.4413; node: v12.6.0]
    (C) 2018 Microsoft Corporation.
    https://aka.ms/autorest
    Loading AutoRest core      'C:\Users\<User>\.autorest\@microsoft.azure_autorest-core@2.0.4413\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4413)
