### ISSUE TITLE
[autorest-beta] Says it cannot find a file that definitely exists

### ISSUE THREAD

**Issue by deathly809** [Azure/autorest#3375]
@bganapa Create a bug.

I removed nodejs from the machine.  Deleted all npm folders and caches.  Reinstalled nodejs v10.15.3 and installed using the following command and it still doesn't work,

```
 npm install -g @autorest/autorest
```

```
E:\github\azure-powershell\src\StackAdmin\Azs.Compute.Admin>autorest-beta
AutoRest code generation utility [version: 3.0.6149; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\jerobins.REDMOND\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4407)
Failed to acquire 'require'd configuration 'file:///E:/github/azure-powershell/src/StackAdmin/Azs.Compute.Admin/readme.azurestack.md'
  Error: Could not read 'file:///E:/github/azure-powershell/src/StackAdmin/Azs.Compute.Admin/readme.azurestack.md'.
```

**Comment by fearthecowboy** [comment]
Hmm. You shouldn't be getting `2.0.4407` unless you're trying to use an v2 generator. 

whats in the `readme.md` file?

**Comment by bganapa** [comment]
@fearthecowboy  This is the readme
https://github.com/Azure/azure-powershell/blob/stackadmin/src/StackAdmin/Azs.Compute.Admin/readme.md

The following is the file that it complains for as Not found
https://github.com/Azure/azure-powershell/blob/stackadmin/src/StackAdmin/readme.azurestack.md

I could not reproduce the error. It happens with @deathly809 everytime even after a fresh uninstall of node/autorest-beta

**Comment by fearthecowboy** [comment]
try:

`autorest-beta --reset`
`autorest-beta --version:3.0.6184 --powershell `

and if that fails:

`autorest-beta --info` and tell me what it says

**Comment by fearthecowboy** [comment]
I just cloned the repo and tried it:

![image](https://user-images.githubusercontent.com/133736/72300969-3685a800-361a-11ea-82f3-b75260edb43a.png)


Past that, add `--debug --verbose` and maybe it will say something useful.

**Comment by bganapa** [comment]
Thanks @fearthecowboy , I was not able to repro as well and we have a CI that generates the modules as well. Its just @deathly809 box. @deathly809  Can you pls get the --debug, --verbose output.. we already tried autorest --reset

**Comment by deathly809** [comment]
Error has now changed, yay!

First part,

![image](https://user-images.githubusercontent.com/1381210/72301915-2e7b3780-361d-11ea-9f4c-c2f1327af356.png)

Second part (--verbose --debug)

![image](https://user-images.githubusercontent.com/1381210/72301936-3a66f980-361d-11ea-98a3-bdfa3b212d3a.png)

**Comment by fearthecowboy** [comment]
I'm going to have to go add some more logging in the extension installer/loader.

Something is failing, and it's not telling us what.

**Comment by deathly809** [comment]
@fearthecowboy New error!

after each remove and install I get the two errors below (tried as admin).


On first run I see this,
```
AutoRest code generation utility [version: 3.0.6149; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\jerobins.REDMOND\node_modules\@autorest\core\dist' (3.0.6184)
   Installing AutoRest extension '@autorest/powershell' (~2.1.327)
Failed to install or start extension '@autorest/powershell' (~2.1.327)
  Error: Package '@autorest/powershell' - '2.1.355' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/powershell/-/powershell-2.1.355.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/powershell/-/powershell-2.1.355.tgz' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:307:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

After that I just keep getting the following message

```
E:\github\azure-powershell\src\StackAdmin\Azs.Compute.Admin>autorest-beta --debug --verbose
AutoRest code generation utility [version: 3.0.6149; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
{ Error: ENOENT: no such file or directory, stat 'C:\Users\jerobins.REDMOND\node_modules\@autorest\core\dist\static_modules.fs'
    at Object.statSync (fs.js:850:3)
    at new StaticVolumeFile (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:7143)
    at exports.StaticFilesystem.load (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:9792)
    at Object.load (C:\Users\jerobins.REDMOND\node_modules\@autorest\core\dist\static-loader.js:1:5249)
    at Object.<anonymous> (C:\Users\jerobins.REDMOND\node_modules\@autorest\core\entrypoints\app.js:5:56)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:19485)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.tryRequire (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\autorest-as-a-service.js:145:20)
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path:
   'C:\\Users\\jerobins.REDMOND\\node_modules\\@autorest\\core\\dist\\static_modules.fs' }
```

**Comment by fearthecowboy** [comment]
I want you to remove the following folders:

``` bash
# this one should never be there. that's just suicide.
C:\Users\jerobins.REDMOND\node_modules

# autorest module folders
C:\Users\jerobins.REDMOND\.autorest
C:\Users\jerobins.REDMOND\.net
```
Then run these:
``` bash
# remove packages
npm remove -g autorest 
npm remove -g @autorest/autorest
npm --force cache clear
```

then install again (make sure it's with `-g` )
``` bash
npm install -g @autorest/autorest 
autorest-beta --powershell --help 
```

**Comment by deathly809** [comment]
@fearthecowboy Now it is a new one!

```
E:\github\azure-powershell\src\StackAdmin\Azs.Compute.Admin>autorest-beta --powershell --help
AutoRest code generation utility [version: 3.0.6161; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to start AutoRest Core from C:\Users\jerobins.REDMOND\.autorest\@autorest_core@3.0.6197\node_modules\@autorest\core
Error: Unable to start AutoRest Core from C:\Users\jerobins.REDMOND\.autorest\@autorest_core@3.0.6197\node_modules\@autorest\core
    at main (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\app.js:316:19)
```

**Comment by deathly809** [comment]
@fearthecowboy So... it appears that autorest downloads modules into node_modules, but looks in .autorest to load them.  So I manually copied from node_modules\@autorest to .autorest (with some folder name changes)

```
# Empty
C:\Users\jerobins.REDMOND\.autorest
# Full of stuff
C:\Users\jerobins.REDMOND\node_modules\@autorest
```

**Comment by dolauli** [comment]
@deathly809 You may have a try to build a docker image by using the latest autorest and related plugins. See https://github.com/Azure/autorest.powershell/tree/master/tools/docker for details.

**Comment by bganapa** [comment]
![image](https://user-images.githubusercontent.com/12038849/74882428-ef2ebd80-5323-11ea-8bb4-af26e1409ad1.png)

We still hit this issue @fearthecowboy , our workaround is to use 3.0.6158 in the same machine and everything is fine
![image](https://user-images.githubusercontent.com/12038849/74882543-2604d380-5324-11ea-858c-e8316c1e0ab0.png)

**Comment by bganapa** [comment]
@fearthecowboy This issue is being hit in our dev ops pipelines as well now.  This has the potential of blocking us from consuming the latest autorest. Appreciate your investigation.

**Comment by fearthecowboy** [comment]
Can you point me to the devops pipeline where it's failing.

I have no way to even repro this in a place I can find out what's going on.

**Comment by fearthecowboy** [comment]
When I try this:

``` bash
autorest https://github.com/Azure/azure-powershell/tree/stackadmin/src/StackAdmin/Azs.Compute.Admin/readme.md --verbose --debug
```

You're `require` ing the file at https://github.com/Azure/azure-rest-api-specs/tree/stackadmin/specification/azsadmin/resource-manager/compute/readme.md which lists 

``` yaml
input-file:
    - Microsoft.Compute.Admin/preview/2015-12-01-preview/Compute.json
    - Microsoft.Compute.Admin/preview/2015-12-01-preview/PlatformImages.json
    - Microsoft.Compute.Admin/preview/2018-02-09/Quotas.json
    - Microsoft.Compute.Admin/preview/2015-12-01-preview/VMExtensions.json
    - Microsoft.Compute.Admin/preview/2018-07-30-preview/Disks.json
    - Microsoft.Compute.Admin/preview/2018-07-30-preview/DiskMigrationJobs.json

```

which are all files listed without `$(this-folder)` which means they are to be loaded relative to the `$(base-folder)` which would be where the `readme.md` file is that you start with. (https://github.com/Azure/azure-powershell/tree/stackadmin/src/StackAdmin/Azs.Compute.Admin/)

I don't think you want to include the file https://github.com/Azure/azure-rest-api-specs/tree/stackadmin/specification/azsadmin/resource-manager/compute/readme.md  at all. You have a different file which is listing your inputs anyway.  (https://github.com/Azure/azure-rest-api-specs/blob/stackadmin/specification/azsadmin/resource-manager/compute/readme.azsautogen.md ) which does have the `$(this-folder)`.

**Comment by bganapa** [comment]
@fearthecowboy Awesome. Thanks for the investigations.  The following commit fixes the issue
https://github.com/Azure/azure-rest-api-specs/commit/c70efa60201b0925ca77831ca5a366d0f5467387

As you mentioned we need to explicitly mention $(this-folder), somehow we missed it. WE will be deleting the readme.azsazutogen.md file

@deathly809 FYI

**Comment by bganapa** [comment]
Though the changes worked, still need to see whether this change was intended, since it is breaking from the previous releases.
