### ISSUE TITLE
"Azure-arm: true" makes some bad side effect in autorest v3

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3377]
When "Azure-arm: true" is set, api-version will be missing in the generated code. And the error is as below when running a powershell cmdlet.

_PS C:\Users\xidi\src\azure-powershell\src\HanaOnAzure [Az.Hana]> Get-AzHanaInstance
Get-AzHanaInstance : The api-version query parameter (?api-version=) is required for all requests.
At line:1 char:1
+ Get-AzHanaInstance
+ ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: ({ SubscriptionId = System.String[] }:<>f__AnonymousType2`1) [Get-AzHanaInstance_List], RestException`1
+ FullyQualifiedErrorId : MissingApiVersionParameter,Microsoft.Azure.PowerShell.Cmdlets.Hana.Cmdlets.GetAzHanaInstance_List_

According to comments from Garrett, "Azure-arm: true" is what the v2 generators used, and we need to fix this bad side effect this switch makes on autorest v3.

**Comment by fearthecowboy** [comment]
In your readme.azure.md configuration you probably just want to specify `azure-arm: false`

**Comment by lmazuel** [comment]
Closed since we believe this is fixed
