### ISSUE TITLE
AutoRest Azure code gen should support resources that are a dictionary of properties

### ISSUE THREAD

**Issue by naveedaz** [Azure/autorest#338]
Essentially the following resource json should be supported by AutoRest
{
  "id": "/subscriptions/{subId}/resourceGroups/{rg}/providers/{pns}/{resourcetype}/{resourceName}",
  "name": "{resourceName}",
  "type": "pns/resourcetype",
  "tags": { },
  "properties": {
    "key1": "My first value",
    "key2": "My second value"
  }
}

Here the expected generated client code would be something like:
Class Resource1 : DictionaryResource<string,string>
{
}

Class Resource2: DictionaryResource<string, object>
{
}

where 
Class DictionaryResource<T,K> : Dictionary<T,K> 
{
String Id { get; set; }
String Name { get; set; }
String Location {get; set; }
Dictionary<string, string> Tags {get; set; }
}

Please also recommend the swagger json required to get this behavior once this resource object is supported by AutoRest

**Comment by fearthecowboy** [comment]
I think we satisfy this, in a somewhat different way.

See: https://github.com/Azure/autorest/blob/master/Documentation/defining-clients-swagger.md#dictionaries 

You can generate a property as a dictionary, or get a catch-all property for unspecified properties.
