### ISSUE TITLE
Fix behavior around tag=all-api-versions and lack of multi-api support

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3384]
See azure-mgmt-keyvault generation with following command line for example:
autorest-beta https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/keyvault/resource-manager/readme.md --use=. --output-folder=KeyVault --python

**Comment by fearthecowboy** [comment]
fixing in #3383  (enforce all-api-versions only when `--profile` or `--api-version` is set)
