### ISSUE TITLE
Error reported for 'model-validator' not found

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest#3389]
repo: run autorest v3 against ..\azure-rest-api-specs\specification\service-map\resource-manager\readme.md with output-artifact 'code-model-v4-no-tags'

DEBUG [18.11 s]: modelerfour/notags/emitter - END [0.13 s]
Process() cancelled due to exception : Plugin 'model-validator' not found. / Error: Plugin 'model-validator' not found.
    at ScheduleNode (c:\git\v3\autorest\core\lib\pipeline\pipeline.ts:307:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Plugin 'model-validator' not found.

**Comment by fearthecowboy** [comment]
install the latest cli and core and try again

```  bash
npm install -g @autorest/autorest
autorest-beta --reset

autorest-beta ... 
```
