### ISSUE TITLE
Autorest generated code tries to JSon serialize text/plain string body

### ISSUE THREAD

**Issue by almaasrawi** [Azure/autorest#3391]
### Overview
We have an API that takes a free form text input, which could be either JSON, NDJSon, CSV or TSV. The api defined as:

~~~JSon
...
"paths: {
   ...
   "/my/api/path": {
      "post" : {
         ...
         "consumes": [ "text/plain" ]
         "parameters": [
            {
               "in": "body",
               "name": "body",
               "required": true,
               "schema": {
                   "type": "string",
             }
         ]
         ...
~~~

However, in the autorest generated code, it tries to serialize the input body using the JSon Serializer, as in:

~~~C#
if(body != null)
{
    _requestContent = SafeJsonConvert.SerializeObject(body, SerializationSettings);
    _httpRequest.Content = new StringContent(_requestContent, System.Text.Encoding.UTF8);
    _httpRequest.Content.Headers.ContentType =System.Net.Http.Headers.MediaTypeHeaderValue.Parse("text/plain");
}
~~~

This causes added string type double quotation added to the start and end of the body, which breaks the service.

The only mitigations available for the issue is:
* Adding a JsonConveter to handle the string type, converting using the writer.WriteRaw method. However this would break any actual strings that are parts of actual Json for other objects.
* Manual edit of the generated code.

**Comment by fearthecowboy** [comment]
It's a limitation in the v2 generators. use `format: binary` (or 'format: file' ? ) with `type:string` -- you'll be able treat it as a stream. 

We're trying to make this work elegantly in the v3 generators.

**Comment by fearthecowboy** [comment]
V3 generators now do this differently; the `consumes` takes priority and will produce code for streams or text
