### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by simondel** [Azure/autorest#3396]
The changelog hasn't been updated in two years. Since Autorest automatically updates newer versions, it's very handy if we can see what's changed.

I understand that it's not practical to add all the missing changes to the changelog, but perhaps the future changes can be added to make sure there is at least a changelog for changes to come.

**Comment by fearthecowboy** [comment]
Really, very little has happened in the master v2 branch other than little fixes for specific glitches.

I've been starting to update the v3 branch more often and should be making that 'stable' soon.
