### ISSUE TITLE
Regression issue in autorest.core 3.0.6192

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3398]
Huh. I think there were two actual problems here. 

I did the package publish rollback, but it looks like something in autorest-core definitely broke something in powershell around build 3.0.6192. 

for the next day or two, add --version:3.0.6158 on the autorest-beta command line,  and you will get past the other problem. (you do not need to roll back the autorest-beta command line, 3.0.6165 works just fine with --version:3.0.6158 ) 

G

From: Xiaogang Ding <Xiaogang.Ding@microsoft.com> 
Sent: Monday, February 3, 2020 9:28 PM
To: Garrett Serack <garretts@microsoft.com>
Cc: Dingmeng Xue <Dingmeng.Xue@microsoft.com>; Bala Ganapathy <Balsu.G@microsoft.com>; Mark Cowlishaw <Mark.Cowlishaw@microsoft.com>
Subject: RE: latest autorest-beta/powershell extension broken
Importance: High

Hi Garrett,

It looks recent update in autorest/autorest-core/peak break the code generation of Azure PowerShell.

My case is a little different from Bala’s.

When using autorest 3.0.6165 and autorest core 3.0.6200, code generation will failed. See https://dev.azure.com/azure-sdk/public/_build/results?buildId=250923&view=logs&j=3b09f592-39e4-5bb9-790e-876c78e30c33&t=5153f57d-ce37-50a8-d3c6-acd7295cb8f5 for an example.

When I move back to use autorest 3.0.6149 and autorest core 3.0.6158 which used to work before, code generation could pass but the build failed. See https://dev.azure.com/azure-sdk/public/_build/results?buildId=250922&view=logs&j=3b09f592-39e4-5bb9-790e-876c78e30c33&t=64035f9c-1f7d-5772-d871-594b3cc37981 for an example. This failure looks caused by the peak change. And I tried to diff a working version and a failure version. It looks the space name is renamed.

Last, since it is a blocking issue, is there any work around for the issue?

Thanks,
Xiaogang Ding

**Comment by fearthecowboy** [comment]
resolved in core .6205
