### ISSUE TITLE
 Error: Collision detected inserting into object: items

### ISSUE THREAD

**Issue by SPEMoorthy** [Azure/autorest#3399]
Installed Latest Preview Release...

A) npm install -g  https://github.com/Azure/autorest/releases/download/autorest-core-3.0.6200/autorest-core-3.0.6200.tgz

B) autorest --v3 --input-file=Api.txt --csharp --output-folder=GSWayApi --namespace=GSWaySyncCore.Data.GSWay.API --add-credentials --verbose

Got Error As Follows

VERBOSE [22.62 s]: Reading OpenAPI 3.0 file file:///C:/Users/SITSLN/Desktop/WIP/GWayAPI/Api.txt
  Error: Collision detected inserting into object: items

Note: Attached Spec File 
[Api.txt](https://github.com/Azure/autorest/files/4153361/Api.txt)

**Comment by fearthecowboy** [comment]
After removing the 'additionalProperties:false ' it complains because you're using `allOf` on `ObjectState` which is an enum. I don't know what you're trying to do, but it don't like that.

if you want to make your `state` property an enum, set the property's schema to `ObjectState`, don't make it try to inherit that.

**Comment by fearthecowboy** [comment]
The next v3 build should handle `additionalProperties: false` for v2 generators.

**Comment by SPEMoorthy** [comment]
> After removing the 'additionalProperties:false ' it complains because you're using `allOf` on `ObjectState` which is an enum. I don't know what you're trying to do, but it don't like that.
> 
> if you want to make your `state` property an enum, set the property's schema to `ObjectState`, don't make it try to inherit that.

enum Was inherited... The Api.txt was generated by  app.UseSwagger(); Swagger generater. whch generates enum as inherited one... but  app.UseSwagger(o => o.SerializeAsV2 = true);  v2 is generating the object state as properity not inheritng.. as you said. Is there any problem with new asp.netcore swagger generator?

**Comment by fearthecowboy** [comment]
I have no idea what `new asp.netcore swagger generator` you're talking about. I don't use swagger generators.
