### ISSUE TITLE
[Feature Request] Autorest -> Ibiza Integration

### ISSUE THREAD

**Issue by rileymckenna** [Azure/autorest#3403]
I am not sure if this is the place to do this, but id like to propose a change to add an Ibiza integration.
What i mean by this is to make it easier to generate Ibiza models and calls from the arm spec. This would be great because it would save a lot of time when we implement new APIs for our resource Providers. I've received numerous asks from new ibiza developers to add this functionality.

**Comment by fearthecowboy** [comment]
You'd have to talk to the folks that build Ibiza. That ain't here.
