### ISSUE TITLE
Protocol https is not supported for writing

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3410]
autorest-beta https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/readme.md --use=. --python --multiapi --python-mode=update --python-sdks-folder=D:\VSProjects\azure-sdk-for-python\sdk --keep-version-file

gives:
Failure during batch task - {"tag":"package-2019-06"} -- Error: Cannot write data to 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/generated/storage_management_client/models/_models.py'. Protocol 'https:' not supported for writing. Make sure to specify a local, absolute path as target file/folder..
  Error: Cannot write data to 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/generated/storage_management_client/models/_models.py'. Protocol 'https:' not supported for writing. Make sure to specify a local, absolute path as target file/folder.

**Comment by lmazuel** [comment]
With a local readme path, it's actually ignoring my output folder totally and generates in a "generated" close to the Readme.md

**Comment by daviwil** [comment]
I don't see the same https error when trying to reproduce this but I do see a different one.  Can you tell me which version of @autorest/autorest you're using?

**Comment by daviwil** [comment]
I just updated to @autorest/autorest 3.0.6180 and I see this error:

```
Failure during batch task - {"tag":"package-2019-06"} -- Error: The 'title' across provided OpenAPI definitions has to match. Found: 'StorageManagementClient', 'StorageManagement'. Please adjust or provide an override (--title=...)..
  Error: The 'title' across provided OpenAPI definitions has to match. Found: 'StorageManagementClient', 'StorageManagement'. Please adjust or provide an override (--title=...).
```

This is when using the last dev-released @autorest/python package and not the latest master.  I noticed that an older @autorest/core was being chosen from its configuration so I bumped it to the latest 3.0.6220 and got the same error you did:

```
Failure during batch task - {"tag":"package-2019-06"} -- Error: Cannot write data to 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/generated/storage_management_client/models/_models.py'. Protocol 'https:' not supported for writing. Make sure to specify a local, absolute path as target file/folder..
  Error: Cannot write data to 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/generated/storage_management_client/models/_models.py'. Protocol 'https:' not supported for writing. Make sure to specify a local, absolute path as target file/folder.
```
Seems like something broke this in @autorest/core, looking into it.

**Comment by lmazuel** [comment]
Discussed a little with @fearthecowboy offline, here' sthe full context:

> [12:18 PM] Laurent Mazuel
>     seems some regression in the output-folder behavior?
> ​[12:19 PM] Laurent Mazuel
>     I used to have the Readme say:
> 
> output-folder=$(python-sdks-folder)/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01
> (1 liked)​[12:20 PM] Laurent Mazuel
>     
> and then specify --python-sdks-folder
> ​[12:20 PM] Laurent Mazuel
>     doesn't seem to work anymore with autorest-beta?
> ​[12:23 PM] Laurent Mazuel
>     Fun fact: if I remove the $(python) in my yaml block it works
> ​[12:24 PM] Laurent Mazuel
>     I knew that having $(python) condition in a readme.python.md was useless, since the file is not loaded anyway if --python was not there in the first place
> ​[12:24 PM] Laurent Mazuel
>     but it was working, so got lazy enough to just keep it (tongueout)

> [12:24 PM] Laurent Mazuel
>     it seems now the $(python) condition are not evaluated to true anymore inside the readme.python.d

This workarounded the issue:
https://github.com/lmazuel/azure-rest-api-specs/commit/af19958fcd645f638baa56eb0742665ebb999967
>

**Comment by fearthecowboy** [comment]
It's actually related to the lack of a pipeline step called `python` -- I sent a PR to the python/v3 branch to add the requisite fix, (which references the build of core that fixes it.
