### ISSUE TITLE
autorest core detected collisions

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3416]
Trying to run network package-2018-12, after emitting python files, autorest core crashed due to "Detected Collisions".
Here's a snippet of the debug output:
DEBUG [409.86 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/init.py
DEBUG [409.86 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/_network_management_client.py
DEBUG [409.86 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/_configuration.py
DEBUG [409.86 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/aio/init.py
DEBUG [409.87 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/aio/_network_management_client_async.py
DEBUG [409.87 s]: Emitting 'python-files' at file:///F:/azure-rest-api-specs/specification/network/resource-manager/$%28python-sdks-folder%29/network/azure-mgmt-network/azure/mgmt/network/v2018_12_01/aio/_configuration_async.py
DEBUG [409.87 s]: python/codegen/emitter - END [0.25 s]
Process() cancelled due to exception : Detected Collisions. / Error: Detected Collisions.
    at quickCheck (C:\Users\iscai\.autorest\@autorest_core@3.0.6223\node_modules\@autorest\core\dist\lib\pipeline\plugins\quick-check.js:45:19)
    at async ScheduleNode (C:\Users\iscai\.autorest\@autorest_core@3.0.6223\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:292:33)
  Error: Detected Collisions.
[409.87 s] Shutting Down.
[409.87 s] Exiting.

Versions
core: 3.0.6223
m4: 4.6.199
autorest CLI: 3.0.6182

**Comment by fearthecowboy** [comment]
The command line?

**Comment by iscai-msft** [comment]
autorest-beta --version:3.0.6223 ../azure-rest-api-specs/specification/network/resource-manager/readme.md --use=. --python --multiapi --python-mode=update --keep-version-file

**Comment by iscai-msft** [comment]
Adding advisor;

autorest-beta ..\azure-rest-api-specs\specification\advisor\resource-manager\readme.md --use=. --python-sdks-folder=F:\azure-sdk-for-python\sdk --python --python-mode=update --keep-version-file

Versions:
core: 3.0.6115
m4: 4.7.207
cli: 3.0.6187

**Comment by fearthecowboy** [comment]
Ah found it. 

It was colliding when there was two enums with the same name, but in different case. 

The next build of autorest-core will just merge those definitions.

**Comment by fearthecowboy** [comment]
autorest-core  3.0.6233+ fixes this -- it will merge enum definition with the same name regardless of case.
