### ISSUE TITLE
Can't update autorest core to nightly build

### ISSUE THREAD

**Issue by phredBAS** [Azure/autorest#3420]
According to the releases page: https://github.com/Azure/autorest/releases, the latest version of autorest-core is 3.0.6225 (as of this issue creation). When I do "autorest --latest" or "autorest --latest --preview" and thenautorest --list-installed, I get:

Type       Extension Name                           Version      Location 
 core       @microsoft.azure/autorest-core           3.0.5537     C:\Users\phred.menyhert\.autorest\@microsoft.azure_autorest-core@3.0.5537

When I list the available versions using this command:
autorest --list-available
or
autorest --list-available --preview
...I get "No available versions of package @microsoft.azure/autorest-core found."

How do I get autorest to update autorest-core to the latest nightly build?

**Comment by fearthecowboy** [comment]
You need to update to the latest cli build -- you're on a reaaaaly old one:

``` bash

# autorest v3 RC    
npm install -g https://github.com/Azure/autorest/releases/download/autorest-3.0.6187/autorest-3.0.6187.tgz      

# reset the core to the latest
autorest --reset
--



```
