### ISSUE TITLE
golang code is not generated when using autorest 3.0

### ISSUE THREAD

**Issue by Asakuri** [Azure/autorest#3425]
Hi,

When I'm using autorest 3.0 to generate golang code, if I don't force to use 'version=2.0', no codes are generated, but for other languages like python/java, autorest will automatically switch to version 2.0.

Is this a known issue?

![image](https://user-images.githubusercontent.com/6874067/75333349-f6743f00-58c0-11ea-8838-cc8c24ea89b8.png)

**Comment by fearthecowboy** [comment]
O_O 

That's unexpected.

Just out of curiosity, can you add `--verbose --debug` to the command line. I'd like  to see what it's doing

**Comment by fearthecowboy** [comment]
Fixed it -- run:
``` bash
autorest --reset
``` 

and try again.

**Comment by Asakuri** [comment]
fix confirmed, thanks.
