### ISSUE TITLE
Error: Collision detected inserting into object: constructor

### ISSUE THREAD

**Issue by Agne-ops** [Azure/autorest#3428]
I keep getting the following error when using autorest with swagger json

AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\.autorest\@autorest_core@3.0.6237
   Loading AutoRest core      'C:\Users\.autorest\@autorest_core@3.0.6237\node_modules\@autorest\core\dist' (3.0.6237)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [2.15 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.15 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.15 s]: pipeline-emitter - START inputs = 0
DEBUG [2.17 s]: configuration-emitter - START inputs = 0
DEBUG [2.23 s]: pipeline-emitter - END [0.08 s]
DEBUG [2.23 s]: configuration-emitter - END [0.08 s]
DEBUG [2.43 s]: swagger-document/loader-swagger - END [0.29 s]
DEBUG [2.44 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2.44 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2.44 s]: swagger-document/identity - SKIPPING
DEBUG [2.44 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2.44 s]: openapi-document/openapi-document-converter - SKIPPING
autorest-beta : C:\Users\.autorest\@autorest_core@3.0.6237\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
At line:1 char:1
+ autorest-beta --debug --version=3.0.6237 --input-file=BackendSwagger. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\.... {"exitCode":1}:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Process() cancelled due to exception : Collision detected inserting into object: constructor / Error: Collision detected inserting into object: constructor
    at Object.set (/node_modules/@azure-tools/datastore/dist/graph-builder.js:45:23)
    at RefProcessor.newObject (/node_modules/@azure-tools/datastore/dist/processor.js:40:24)
    at RefProcessor.process (C:\Users\.autorest\@autorest_core@3.0.6237\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Collision detected inserting into object: constructor
[2.58 s] Shutting Down.
[2.59 s] Exiting.

Packages:
- Swashbuckle 5.0.0
- Autorest 3.0.6237

**Comment by surfaace** [comment]
I have the same issue running autorest cli version 3.0.6187 with autorestcore 3.0.6246

autorest-beta --v3 --input-file="../swaggerv1.json" --output-folder="Generated" --override-client-name="Clientv1" --csharp --debug --preview
AutoRest code generation utility [cli version: 3.0.6187; node: v12.13.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246
   Loading AutoRest core      'C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist' (3.0.6246)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (preview)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp' (preview->2.3.84)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)
   Installed AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [9.91 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [9.92 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [9.92 s]: pipeline-emitter - START inputs = 0
DEBUG [9.95 s]: configuration-emitter - START inputs = 0
DEBUG [10.01 s]: pipeline-emitter - END [0.09 s]
DEBUG [10.01 s]: configuration-emitter - END [0.09 s]
DEBUG [10.29 s]: swagger-document/loader-swagger - END [0.38 s]
DEBUG [10.3 s]: swagger-document/individual/transform - SKIPPING
DEBUG [10.3 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [10.31 s]: swagger-document/identity - SKIPPING
DEBUG [10.31 s]: swagger-document/individual/identity - SKIPPING
DEBUG [10.33 s]: openapi-document/openapi-document-converter - SKIPPING
C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: constructor / Error: Collision detected inserting into object: constructor
    at Object.set (/node_modules/@azure-tools/datastore/dist/graph-builder.js:45:23)
    at RefProcessor.newObject (/node_modules/@azure-tools/datastore/dist/processor.js:40:24)
    at RefProcessor.process (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RefProcessor.process (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:17)
    at async RefProcessor.process (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:17)
    at async RefProcessor.process (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:17)
    at async RefProcessor.process (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:17)
    at async RefProcessor.runProcess (/node_modules/@azure-tools/datastore/dist/processor.js:76:17)
    at async RefProcessor.getOutput (/node_modules/@azure-tools/datastore/dist/processor.js:14:9)
    at async crawl (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:19:24)
    at async C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:45:22
    at async Promise.all (index 0)
    at async Object.crawlReferences (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:43:5)
    at async C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\loaders.js:110:22
    at async ScheduleNode (C:\Users\dummyuser\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Collision detected inserting into object: constructor
[10.47 s] Shutting Down.
[10.47 s] Exiting.

**Comment by hisuwh** [comment]
I'm getting the same issue:
```
autorest --input-file=apiDefinitions.json --csharp --output-folder=ServiceApi --namespace=ServiceApi --v3 --debug
AutoRest code generation utility [cli version: 3.0.6187; node: v10.19.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\HenryIng-Simmons\.autorest\@autorest_core@3.0.6258
   Loading AutoRest core      'C:\Users\HenryIng-Simmons\.autorest\@autorest_core@3.0.6258\node_modules\@autorest\core\dist' (3.0.6258)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [1.48 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.48 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.48 s]: pipeline-emitter - START inputs = 0
DEBUG [1.51 s]: configuration-emitter - START inputs = 0
DEBUG [1.55 s]: pipeline-emitter - END [0.06 s]
DEBUG [1.55 s]: configuration-emitter - END [0.07 s]
DEBUG [1.87 s]: swagger-document/loader-swagger - END [0.39 s]
DEBUG [1.87 s]: swagger-document/individual/transform - SKIPPING
DEBUG [1.87 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [1.87 s]: swagger-document/identity - SKIPPING
DEBUG [1.88 s]: swagger-document/individual/identity - SKIPPING
DEBUG [1.88 s]: openapi-document/openapi-document-converter - SKIPPING
C:\Users\HenryIng-Simmons\.autorest\@autorest_core@3.0.6258\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: constructor / Error: Collision detected inserting into object: constructor
    at Object.set (/node_modules/@azure-tools/datastore/dist/graph-builder.js:45:23)
    at RefProcessor.newObject (/node_modules/@azure-tools/datastore/dist/processor.js:40:24)
    at RefProcessor.process (C:\Users\HenryIng-Simmons\.autorest\@autorest_core@3.0.6258\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Collision detected inserting into object: constructor
[2.06 s] Shutting Down.
[2.06 s] Exiting.
```

**Comment by fearthecowboy** [comment]
Did anyone want to share the swagger files they are using?

**Comment by hisuwh** [comment]
@fearthecowboy can I email it to you?  I don't really want to share it on here.

**Comment by fearthecowboy** [comment]
Send it to me at `garretts` @ `microsoft.com`

**Comment by cyptus** [comment]
got the same issue. is there any workaround yet?

**Comment by Agne-ops** [comment]
@cyptus I don't think there is, at least I did not find a solution and am still having the same issue.

**Comment by fgheysels** [comment]
I am having the same issue as well when trying to generate classes for an OpenApi v3.0.1 spec file

**Comment by racoco** [comment]
i also had the same issue as of 4/26/2020

**Comment by kieseld** [comment]
Any update on this? We are seeing the same issue.

**Comment by lukewis** [comment]
I'm new to this repo/tool chain but am trying to investigate this issue.  Can anyone point me to how to run autorest locally after I clone the repo?  I have it building, but can't figure out where the build "output" goes....

**Comment by lukewis** [comment]
Well, I did get things running locally, but I'm not much closer to finding the issue.  I had to add the following line to app.ts because it was complaining that isDebuggerEnabled was not defined.  Maybe a configuration issue with the launch.json?   I'm not sure.
```
const isDebuggerEnabled = !!require('inspector').url();
```
My next step is to try to figure out how to get VSCode to break on an unhandled exception cause the line that's throwing is called in a loop, so it's tough to tell which iteration is failing.

**Comment by lukewis** [comment]
Of interest, I tried reverting to OpenAPI v2 format and I get the same error

**Comment by lukewis** [comment]
Indeed, converting to an object that has a parameterless constructor seemed to resolve this error.  Would still like to fix the underlying issue if anyone has any tips!

**Comment by remy90** [comment]
@fearthecowboy did you receive a swagger file?

**Comment by timotheeguerin** [comment]
Can anybody reshare an openapi file having this issue? @lukewis if you manage to pinpoint the issue could you share the  minimal repro?

**Comment by lukewis** [comment]
@timotheeguerin I tried again using the latest version and ran into https://github.com/Azure/autorest/issues/3492.  After pinning the version to 3.0.6274 I was able to generate successfully using a model without a parameterless constructor.  From my perspective, this issue seems to be resolved
```
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.3, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '...\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
```

**Comment by timotheeguerin** [comment]
Thanks @lukewis. I'll close for now, if anybody else still has this issue., please reopen or create a new issue with reproducable specs+parameters if possible

**Comment by YohanSciubukgian** [comment]
Hello,

I faced this issue when a response contains System.Exception.
A simple repro could be to setup a health endpoint like this :

```csharp
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using System.Net;
using System.Threading.Tasks;

namespace MyProject.Controllers
{
    [AllowAnonymous]
    [Route("health")]
    public class HealthController : Controller
    {
        private readonly HealthCheckService _healthCheckService;
        public HealthController(HealthCheckService healthCheckService)
        {
            _healthCheckService = healthCheckService;
        }

        /// <summary>
        /// Get Health
        /// </summary>
        /// <remarks>Provides an indication about the health of the API</remarks>
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(HealthReport))]
        public async Task<IActionResult> GetHealth()
        {
            var report = await _healthCheckService.CheckHealthAsync();
            return report.Status == HealthStatus.Healthy ? Ok(report) : StatusCode((int)HttpStatusCode.ServiceUnavailable, report);
        }
    }
}
```

The HealthReport.cs contains a HealthReportEntry.cs which reference a lot of System object such as System.Exception.
The swagger is generated with these properties :
```csharp
"Microsoft.Extensions.Diagnostics.HealthChecks.HealthReport": {
  "type": "object",
  "properties": {
    "entries": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/components/schemas/Microsoft.Extensions.Diagnostics.HealthChecks.HealthReportEntry"
      },
      "nullable": true
    },
    "status": {
      "$ref": "#/components/schemas/Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus"
    },
    "totalDuration": {
      "$ref": "#/components/schemas/System.TimeSpan"
    }
  },
  "additionalProperties": false
},
"Microsoft.Extensions.Diagnostics.HealthChecks.HealthReportEntry": {
  "type": "object",
  "properties": {
    "data": {
      "type": "object",
      "additionalProperties": { },
      "nullable": true
    },
    "description": {
      "type": "string",
      "nullable": true
    },
    "duration": {
      "$ref": "#/components/schemas/System.TimeSpan"
    },
    "exception": {
      "$ref": "#/components/schemas/System.Exception"
    },
    "status": {
      "$ref": "#/components/schemas/Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "nullable": true,
      "readOnly": true
    }
  },
  "additionalProperties": false
},
"Microsoft.Extensions.Diagnostics.HealthChecks.HealthStatus": {
  "enum": [
    0,
    1,
    2
  ],
  "type": "integer",
  "format": "int32"
},
```
