### ISSUE TITLE
Error: Plugin imodeler1 reported failure. when generating V3 typescript client

### ISSUE THREAD

**Issue by engelhardtda** [Azure/autorest#3433]
I recently tried switching to OpenApiV3 generating a typescript client and got the followingen error:

> AutoRest code generation utility [cli version: 3.0.6187; node: v10.14.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\user\.autorest\@autorest_core@3.0.6246
   Loading AutoRest core      'C:\Users\user\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist' (3.0.6246)
DEBUG [1.94 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.94 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.95 s]: pipeline-emitter - START inputs = 0
DEBUG [1.96 s]: configuration-emitter - START inputs = 0
DEBUG [1.99 s]: pipeline-emitter - END [0.04 s]
DEBUG [1.99 s]: configuration-emitter - END [0.04 s]
VERBOSE [2 s]: Reading OpenAPI 3.0 file file:///C:/dev/axaas/autorest/client/swagger.json
DEBUG [2 s]: swagger-document/loader-swagger - END [0.05 s]
DEBUG [2 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2 s]: swagger-document/identity - SKIPPING
DEBUG [2 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [2.01 s]: openapi-document/loader-openapi - END [0.07 s]
DEBUG [2.01 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [2.02 s]: openapi-document/individual/transform - END [0 s]
DEBUG [2.02 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [2.03 s]: openapi-document/individual/schema-validator-openapi - END [0.01 s]
DEBUG [2.03 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [2.03 s]: openapi-document/individual/identity - END [0 s]
DEBUG [2.03 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [2.04 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [2.04 s]: openapi-document/transform - START inputs = 1
DEBUG [2.04 s]: openapi-document/transform - END [0 s]
DEBUG [2.05 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [2.05 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [2.05 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [2.06 s]: openapi-document/tree-shaker - END [0 s]
DEBUG [2.06 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2.07 s]: openapi-document/multi-api-merger - END [0.01 s]
DEBUG [2.07 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [2.1 s]: openapi-document/components-cleaner - END [0.02 s]
DEBUG [2.1 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [2.11 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [2.11 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [2.12 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [2.12 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.12 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.12 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.12 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.12 s]: openapi-document/emitter - END [0 s]
DEBUG [2.13 s]: openapi-document/model-deduplicator - END [0.01 s]
DEBUG [2.13 s]: openapi-document/compose - START inputs = 1
DEBUG [2.15 s]: openapi-document/compose - END [0.01 s]
DEBUG [2.15 s]: openapi-document/identity - START inputs = 1
DEBUG [2.15 s]: openapi-document/identity - END [0 s]
DEBUG [2.15 s]: typescript/imodeler1 - START inputs = 1
FATAL: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable1 source, Func2 selector)
   at AutoRest.Modeler.Model.RequestBody.AsParameters() in c:\publish\autorest.modeler\src\Model\RequestBody.cs:line 38
   at AutoRest.Modeler.SwaggerModeler.Unwrap(SwaggerParameter swaggerParameter) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 452
   at AutoRest.Modeler.OperationBuilder.BuildMethodParameters(Method method) in c:\publish\autorest.modeler\src\OperationBuilder.cs:line 255
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in c:\publish\autorest.modeler\src\OperationBuilder.cs:line 100
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in c:\publish\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
C:\Users\user\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin imodeler1 reported failure. / Error: Plugin imodeler1 reported failure.
    at C:\Users\user\.autorest\@autorest_core@3.0.6246\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin imodeler1 reported failure.
[2.58 s] Shutting Down.
[2.58 s] Exiting.

Reproducible with this swagger-file:

>{
  "openapi": "3.0.1",
  "info": {
    "title": "Test API",
    "version": "v1"
  },
  "paths": {
    "/api/v1/test/download": {
      "post": {
        "operationId": "Download",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "FormFile",
                  "SHA256"
                ],
                "type": "object",
                "properties": {
                  "SHA256": {
                    "type": "string"
                  },
                  "Compile": {
                    "type": "boolean"
                  },
                  "FormFile": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              },
              "encoding": {
                "SHA256": {
                  "style": "form"
                },
                "Compile": {
                  "style": "form"
                },
                "FormFile": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/DownloadResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DownloadResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/DownloadResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              }
            }
          },
          "413": {
            "description": "Client Error",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyProblemDetails"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "MyProblemDetails": {
        "type": "object",
        "properties": {
          "messages": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          },
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": {
          "type": "object",
          "additionalProperties": false
        }
      },
      "DownloadResponse": {
        "type": "object",
        "properties": {
          "messages": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}

Any idea what is wrong here? The swagger-file is generated via Swashbuckle. When the project is serialized to OpenApiV2 the client generation works fine.

**Comment by daviwil** [comment]
Hi @engelhardtda, the currently released TypeScript generator only supports Swagger specs and does not support OpenAPI 3.0 yet.  We are currently working on a new version that works with the AutoRest v3 pipeline and OpenAPI 3.0 but it isn't ready for general usage yet:

https://github.com/Azure/autorest.typescript/tree/v6

If you're curious, you could give it a shot by additionally passing in the parameter `--use:@autorest/typescript@0.1.0-dev.20200203.1` when you invoke `autorest`.

I'll close this issue for now since this is an unsupported scenario with the current TypeScript generator.  If you run into any particular issues with the in-development generator mentioned above, please file them over at the [`autorest.typescript` repo](https://github.com/Azure/autorest.typescript).  Thanks!
