### ISSUE TITLE
M4 version not updating to the one specified in readme

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3438]
**Describe the issue**
Hi, @kristapratico ran into an issue when she ran autorest with a [released version](https://github.com/Azure/autorest.python/releases/tag/v5.0.0-dev.20200227.1) of autorest.python and m4 (she had 4.7.207) )didn't update to what was specified in the readme (4.8.221. I can't link to it, but it can be accessed through the released version's downloadable source code).

![moderror](https://user-images.githubusercontent.com/43154838/75923809-afcf9900-5e1a-11ea-9484-a71d4e367849.PNG)

However, once she called an autorest --reset, the run was able to pull 4.8.221.

** REQUIRED ** 
**ModelerFour** version: 4.7.207
**AutoRest-core** version: 3.0.6237
**CommandLine** : C:\Users\krpratic\autorestv3\autorest.python>autorest --use=@autorest/python@5.0.0-dev.20200227.1  --v3 --add-credentials --namespace=azure.ai.formrecognizer --package-name=azure-ai-formrecognizer --no-namespace-fol
ders ---clear-output-folder --output-folder=FormRecognizer_xmspath_v3/ --input-file=C:\Users\krpratic\autorestv3\autorest.python\rest-api-formrecognizer\FormRecognizer.json --credential-scopes=https://cognitiveservices.azu
re.com/.default
OpenAPI/Swagger file: https://github.com/iscai-msft/azure-rest-api-specs/tree/working_form_recognizer (this is not up to date with the version @kristapratico has locally. If you end up needing this, let me know)

**Comment by timotheeguerin** [comment]
Tried to reproduce this issue by doing 
1. `autorest --reset`
2. Running autorest using the python package requesting m4 `4.8.221`
3. Running autorest using the python package `5.5.0` request m4 `4.15.421`

And on step 3 it did use `4.15.421` as epxected
![image](https://user-images.githubusercontent.com/1031227/103659168-f69d8c00-4f20-11eb-9170-c99fa2a487e5.png)

As this was a while ago I don't know if it already got fixed. I'll close the issue for now but please reopen if this can reproduce again
