### ISSUE TITLE
C#: KeyNotFoundException or invalid code for x-ms-error-response on primitive type

### ISSUE THREAD

**Issue by kevinoid** [Azure/autorest#3446]
Adding [`x-ms-error-response`](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-error-response) to a response with `type: string` (or another primitive type) such as the following:

```yaml
swagger: '2.0'
info:
  title: x-ms-error-response example
  version: '1.0.0'
definitions:
  ExampleObject:
    type: object
    properties:
      prop1:
        type: string
paths:
  /example:
    get:
      operationId: getExample
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ExampleObject'
        400:
          x-ms-error-response: true
          description: Failure
          schema:
            type: string
```

Causes C# code generation to fail with core version 3.0.6246, with an error such as the following:

    AutoRest code generation utility [cli version: 3.0.6187; node: v10.17.0, max-memory: 8192 gb]
    (C) 2018 Microsoft Corporation.
    https://aka.ms/autorest
       Loading AutoRest core      '/home/kevin/.autorest/@autorest_core@3.0.6246/node_modules/@autorest/core/dist' (3.0.6246)
       Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
       Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
    FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
       at System.ThrowHelper.ThrowKeyNotFoundException()
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at AutoRest.Modeler.SwaggerModeler.<Build>b__20_10(String modelRef) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 170
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at AutoRest.Core.Utilities.Extensions.ForEach[T](IEnumerable1 sequence, Action1 action)
       at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 171
       at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NewPlugin.<Process>d__15.MoveNext()
      Error: Plugin imodeler1 reported failure.

With core version 2.0.4413 it generates code which does not compile:

```csharp
// Deserialize Response
if ((int)_statusCode == 400)
{
    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
    try
    {
        _result.Body = SafeJsonConvert.DeserializeObject<string>(_responseContent, DeserializationSettings);
    }
    catch (JsonException ex)
    {
        _httpRequest.Dispose();
        if (_httpResponse != null)
        {
            _httpResponse.Dispose();
        }
        throw new SerializationException("Unable to deserialize the response.", _responseContent, ex);
    }
}
```
which fails to compile due to assigning `string` to `_result.Body` of type `ExampleObject`:

    XMsErrorResponseexample.cs(273,36): error CS0029: Cannot implicitly convert type 'string' to 'Swagger.Models.ExampleObject'

From the documentation, the semantics and limitations of `x-ms-error-response` are not clear to me.  What does it mean for a response to be "an error"?  How should it affect code generation?  Can error response types differ (from non-errors or from each other)?

For my current uses, the workaround is simply to remove the `400` response and deserialize the error response body in the caller as needed.

Thanks for considering,
Kevin

**Comment by kevinoid** [comment]
Note that for non-primitive error response types, Autorest currently generates invalid code in both versions if the type differs from the non-error response type.  For v3 it also generates an exception type, but does not appear to use it.

**Comment by fearthecowboy** [comment]
Currently, `x-ms-error-response` isn't supported in v2 generators -- there was a c# branch at one time that could, but nothing else did it. the v3 generators should support it when they're ready.

**Comment by kevinoid** [comment]
Good to know.  Thanks @fearthecowboy!

If appropriate, feel free to [transfer this issue](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) and the other C# ones I submitted around the same time to [Azure/autorest.csharp](https://github.com/Azure/autorest.csharp).  I lack permissions to correct the mistake myself.

**Comment by kevinoid** [comment]
(Or close, if support in v3 is sufficient.)
