### ISSUE TITLE
C#: Invalid code for x-ms-parameterized-host client params

### ISSUE THREAD

**Issue by kevinoid** [Azure/autorest#3448]
If [`x-ms-parameterized-host`](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-parameterized-host) references parameters defined in the [Parameters Definitions Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parametersDefinitionsObject) and there are operations with and without an operation group (i.e. with and without an underscore in their name), invalid C# code is generated.  For example:

```yaml
swagger: '2.0'
info:
  title: x-ms-parameterized-host example
  version: 1.0.0
x-ms-parameterized-host:
  hostTemplate: '{subdomain}.example.com'
  useSchemePrefix: true
  parameters:
  - $ref: '#/parameters/subdomain'
parameters:
  subdomain:
    name: subdomain
    in: path
    required: true
    type: string
paths:
  /example1:
    get:
      operationId: getExample1
      responses:
        '200':
          description: Success
          schema:
            type: string
  /example2:
    get:
      operationId: Group_getExample2
      responses:
        '200':
          description: Success
          schema:
            type: string
```

Generates `GetExample1WithHttpMessagesAsync` starting with:

```csharp
if (this.Client.Subdomain == null)
{
    throw new ValidationException(ValidationRules.CannotBeNull, "this.Client.Subdomain");
}
```

Which fails to compile with the following error:

    XMsParameterizedHostexample.cs(144,22): error CS1061: 'XMsParameterizedHostexample' does not contain a definition for 'Client' and no accessible extension method 'Client' accepting a first argument of type 'XMsParameterizedHostexample' could be found (are you missing a using directive or an assembly reference?)
    XMsParameterizedHostexample.cs(161,81): error CS1061: 'XMsParameterizedHostexample' does not contain a definition for 'Client' and no accessible extension method 'Client' accepting a first argument of type 'XMsParameterizedHostexample' could be found (are you missing a using directive or an assembly reference?)

This occurs with both Autorest core 2.0.4413 and 3.0.6246.

Thanks,
Kevin

**Comment by fearthecowboy** [comment]
I suspect that there ends up being a case that the class for the non-grouped method just doesn't get a reference to `Client`

Maybe you could create a partial class to go along with that and declare a reference to the client? 

The other alternative would be to put those into a group, and then create a class to wrap that.

Again, the v3 generator is completely different, so I can't imagine that's gonna happen there.

**Comment by fearthecowboy** [comment]
Ah, the client is the same class right? Just add a partial class that has a member `Client` that => `this` ...

**Comment by kevinoid** [comment]
> Ah, the client is the same class right? Just add a partial class that has a member `Client` that => `this` ...

Yes indeed.  That's a slick workaround.  Thanks @fearthecowboy!
