### ISSUE TITLE
[C#] Invalid code for non-string urlencoded formData parameters

### ISSUE THREAD

**Issue by kevinoid** [Azure/autorest#3449]
Generating C# code for an OpenAPI document with an operation that consumes `application/x-www-form-urlencoded` with parameters `in: formData` and `type` other than `string` generates code which does not compile.  For example:

```yaml
swagger: '2.0'
info:
  title: Non-string formData parameter
  version: '1.0.0'
paths:
  /example:
    post:
      operationId: updateExample
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: count
        in: formData
        required: true
        type: number
      responses:
        204:
          description: Success
```
Autorest core 2.0.4413 generates:
```csharp
public async Task<HttpOperationResponse> UpdateExampleWithHttpMessagesAsync(double count, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
{
    // ...
    var values = new List<KeyValuePair<string, string>>();
    if(count != null)
    {
        values.Add(new KeyValuePair<string,string>("count", count));
    }
```
Which fails to compile:

    NonStringformDataparameter.cs(211,69): error CS1503: Argument 2: cannot convert from 'double' to 'string' [/path/to/generated.csproj]

Note that `multipart/form-data` generates valid code (although it also causes `CS0472` due to `count != null`).

Thanks,
Kevin

**Comment by fearthecowboy** [comment]
Hmm. V3 generators shouldn't have that limitation -- the modeling is done much more consistently (although, I'm not sure how fast they will support `formData` -- I don't know if it's used in Azure at all. )

I don't think I have an answer for v2 generators

**Comment by timotheeguerin** [comment]
Latest version of autorest and csharp generator handles this.
