### ISSUE TITLE
Republish to docker hub

### ISSUE THREAD

**Issue by oneslash** [Azure/autorest#3452]
Could you please update image in docker hub?

https://hub.docker.com/r/azuresdk/autorest

**Comment by ozonni** [comment]
if you take current Dockerfile and try to use autorest to build C# API client, it's returns error. I've spend hours already trying to fix that. That's bad :(

```
No usable version of the libssl was found
FATAL: csharp/simplifier - FAILED
FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
```

**Comment by timotheeguerin** [comment]
Republished the base image using latest version of autorest. This is just the basic autorest image with node installed which means plugins that need other dependencies(csharp => dotnet, java, etc,) won't work without additional changes.
Created a new issue tracking additional images to cover all scenarios. #4285
