### ISSUE TITLE
Update repo description to not include PHP

### ISSUE THREAD

**Issue by toymachiner62** [Azure/autorest#3457]
It looks like PHP is no longer supported based on [this](https://github.com/Azure/autorest/issues/3372#issuecomment-574070807).

If that's the case you should update the description in this repo so that it doesn't include PHP.

![image](https://user-images.githubusercontent.com/485782/76965012-9ab23a00-68f1-11ea-9de4-c1861fe5ed1c.png)

**Comment by fearthecowboy** [comment]
Fixed.
