### ISSUE TITLE
AutoRest /? should not display raw markdown

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/autorest#346]
AutoRest command line help is markdown. That greatly hampers the readability.

type AutoRest.exe /?

Expected: text
Actual: 
pound pound text
backtick backtick backtick bash
text
backtick backtick backtick 
star star -parameter star star text

**Comment by matt-gibbs** [comment]
in the dev branch

**Comment by stankovski** [comment]
Fixed in 0.12.0
