### ISSUE TITLE
setup-developerworkstation.ps1 was removed but documentation not updated

### ISSUE THREAD

**Issue by abatishchev** [Azure/autorest#3468]
Hi,
[The doc](https://github.com/Azure/autorest/blob/master/.attic/developer/workstation.md) how to install AutoRest locally says to run a script:

```powershell
iwr https://raw.githubusercontent.com/Azure/autorest/master/Tools/setup-developerworkstation.ps1 -OutFile c:\install-software.ps1 ; c:\install-software.ps1
```

I can find this files in several forks of this repo:

- https://github.com/m-moris/AutoRest/blob/master/Tools/setup-developerworkstation.ps1
- https://github.com/jianghaolu/AutoRest/blob/master/Tools/setup-developerworkstation.ps1

However [searching in this repo](https://github.com/Azure/autorest/search?q=setup-developerworkstation.ps1&unscoped_q=setup-developerworkstation.ps1) itself yields only outdated  documentation and no script per se.

How can I install AutoRest locally _today_?

**Comment by fearthecowboy** [comment]
That's not for installing Autorest.

**Comment by abatishchev** [comment]
Are you going to update the doc to remove the references to the script?
