### ISSUE TITLE
Upgraded from 2.0.4283 to latest 3.0.6187, now autorest is unusable.

### ISSUE THREAD

**Issue by ericbrumfield** [Azure/autorest#3471]
Initially I was hitting the same problem discussed in #3249 without any luck of resolving.  I've tried numerous times now running npm uninstall, manually removing @autorest from node_modules.  I've also ran the commands for autorest --reset as well as autorest --latest.

I'm running on Windows 10, npm 6.13.1 and node v10.16.0

The initial errors I get after the update and also on a clean install are:

`Error: EPERM: operation not permitted, stat 'C:\Users\DirtMcGirt\node_modules\@autorest\core\dist\static_modules.fs'`

What I'm seeing is that this file exists on a new install, but then when I actually try to use autorest and generate a client proxy off an openapi file, this static_modules.fs file gets removed, then the error.  I have other projects that rely on this tool and was updating it to v3 for use in a new project, and now I'm regretting this decision to update the tool.

I also tried installing the latest beta using steps I saw in [#3375](https://github.com/Azure/autorest/issues/3375#issuecomment-577359611) .  When I do these steps and run 'autorest-beta --powershell help' I get the following:
`Failure:
Error: Unable to start AutoRest Core from C:\Users\DirtMcGirt\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core
Error: Unable to start AutoRest Core from C:\Users\DirtMcGirt\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core
    at main (C:\Users\DirtMcGirt\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\app.js:308:19)`

Are there any other steps I can take to resolve?  Appreciate any help.

**Comment by ericbrumfield** [comment]
So static_modules.fs is definitely removed when I try to generate off a fresh install/upgrade of latest. 
 Here's a before of the dist dir:

![image](https://user-images.githubusercontent.com/11402298/78386663-f9dba400-75ab-11ea-9ad5-769d8c6c9c62.png)


and then the after:

![image](https://user-images.githubusercontent.com/11402298/78386695-065ffc80-75ac-11ea-9c95-bff0f38e5957.png)

Those are some wonky looking dates on the files as well in the former.

**Comment by ericbrumfield** [comment]
I've back pedaled to 3.0.5231 and this version works as my v3 upgrade for now, so I can move onto using v3 things.  I wouldn't call this ticket closed though, there's something off with the latest version I obtained through npm earlier today.

**Comment by fearthecowboy** [comment]
WEIRD.

I don't understand why you're getting a `node_modules` in your user folder, and a few other things make me curious.

I gotta find out what conditions cause this -- can I get some info from you: ( you can mail me at garretts at microsoft.com if you don't want to post it) 

- how did you install node.js (nvs, nvm, just the msi from nodejs.org, chocolatey ? )
- can you dump your environment (ie, cmd /c set )
- are you running any virus checkers (other than Windows Defender) -- are there any events in there that say something relevant?
- are you behind a proxy? 
- `npm -v `
- `node -v`

**Comment by ericbrumfield** [comment]
I emailed you information, let me know if you need anything else or for me to try anything.

**Comment by daviwil** [comment]
Hi @ericblumfield, did you ever reach a resolution on this issue?  If not, I can get Garrett to forward me the information you sent him a while back.

**Comment by ericbrumfield** [comment]
@daviwil I haven't looked back since back pedaling to 3.0.5231 and moving on.  This dev machine I'm still on and 3.0.5231 is still in place.  I'll likely be retiring this machine in the next month or two.

Here is the email I had sent Garrett.
[Upgraded from 2.0.4283 to latest 3.0.6187, now autorest is unusable.,#3471.txt](https://github.com/Azure/autorest/files/5353420/Upgraded.from.2.0.4283.to.latest.3.0.6187.now.autorest.is.unusable.3471.txt)
