### ISSUE TITLE
[Java] Feature request: Support per call headers through @HeaderMap

### ISSUE THREAD

**Issue by aaronoe** [Azure/autorest#3472]
We found the following limitations with headers when working with the AutoRest Java (v3) generated code:
- Headers that are specified in the Swagger spec cannot be used on the generated method in the interface, but only on the top level services class.
- The other supported way of setting headers through the [CustomHeadersInterceptor](https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/interceptors/CustomHeadersInterceptor.java) does also not facilitate per-call headers.

The only workaround right now would be to create an instance of the service class for each call being made but this is quite undesirable.

**Proposal:**
Given that the generated code internally uses Retrofit, I would propose adding the capability of adding a [@HeaderMap](https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/HeaderMap.html) param for each call which would give us the desired flexibility.

Please advise on whether there is an existing solution that I'm not finding or if this can be added.

**Comment by jianghaolu** [comment]
Hi @aaronoe 
HeaderMap is an annotation from Retrofit that's for our v1 generator. For v3 and v4 we are using the annotations from https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core/src/main/java/com/azure/core/annotation. `HeaderCollection` is closest to being able to do your job but it requires a common header prefix. So I'll have to do some tweaks there first.

**Comment by daviwil** [comment]
Hi @aaronoe, looks like it's possible to get this behavior today based on what @jianghaolu suggested.  I'll go ahead and close this issue for now, let me know if there's still an issue and I'll be happy to reopen it.
