### ISSUE TITLE
ENAMETOOLONG: name too long, error on Ubuntu

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3474]
`ENAMETOOLONG: name too long, open '/tmp/autorest-FPhpen/mem-177-https-3A-2F-2Fgithub.com-2FAzure-2Fazure-rest-api-specs-2Fblob-2F49fc16354df7211f8392c56884a3437138317d1f-2Fspecification-2Fazsadmin-2Fresource-manager-2Fsubscriptions-2FMicrosoft.Subscriptions.Admin-2Fpreview-2F2015-11-01-2FDelegatedProviderOffer.json'`

**Comment by fearthecowboy** [comment]
Resolved in `--version:3.0.6268` - please confirm

**Comment by pakrym** [comment]
Confirmed
