### ISSUE TITLE
Configuration file version not working

### ISSUE THREAD

**Issue by jobeaudette** [Azure/autorest#3479]
Currently using cli version 3.0.6187. We use a configuration file when generating of our client code. The majority of the parameters work fine but the version and v3 parameters are never considered. Yes, as a workaround, it works if I pass them directly as a command line argument, but I would like to be able to use the version specified in the configuration files of our different projects. I tested this using all 3 supported file types with no success.

**Comment by timotheeguerin** [comment]
Hi, will close this as this issue is quite old and is  missing information to investigate. If you are still having this issue please reopen or create a new issue with details of which parameters you are having problems with, the command line you are using, etc.
