### ISSUE TITLE
Support ASP.NET Core 5 vNext

### ISSUE THREAD

**Issue by YZahringer** [Azure/autorest#348]
Microsoft.Rest.ClientRuntime Library is not compatible with ASP.NET Core 5 vNext.

It is not possible to use AutoRest with ASP.NET Core 5?

**Comment by matt-gibbs** [comment]
Changes to support CoreCLR were merged into dev [here](https://github.com/Azure/autorest/pull/340) last week.

**Comment by olavt** [comment]
How can I add the Package 'Microsoft.Rest.ClientRuntime' to a .NET Core project?

I get:

error: Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Newtonsoft.Json 8.0.3
 supports:
error:   - net20 (.NETFramework,Version=v2.0)
error:   - net35 (.NETFramework,Version=v3.5)
error:   - net40 (.NETFramework,Version=v4.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
error:   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.1.
error: Package 'Microsoft.Rest.ClientRuntime' is incompatible with 'all' frameworks in project
