### ISSUE TITLE
autorest 3 beta?

### ISSUE THREAD

**Issue by toymachiner62** [Azure/autorest#3486]
Is autorest 3 still beta? On [this page](https://github.com/Azure/autorest#new-autorest-version-30) it says it's released, but on [this page](https://github.com/Azure/autorest/blob/master/docs/installing-autorest.md) it mentions the v3 beta version. Should really clean these docs up for consistency.

**Comment by daviwil** [comment]
Thanks for the heads up!  I've corrected the installation docs: 

https://github.com/Azure/autorest/commit/6ad8958b65506899b3889a1606e39f1c2d17cc79.
