### ISSUE TITLE
Why have both autorest and @autorest/autorest on npm?

### ISSUE THREAD

**Issue by toymachiner62** [Azure/autorest#3487]
It is very confusing that both `autorest` and `@autorest/autorest` exist on npm. If you install `@autorest/autorest` you have to use the command `autorest-beta`. 

This causes unnecessary confusion to your users. Please rectify this by deprecating one so that it has a warning when installed or upgraded.

**Comment by timotheeguerin** [comment]
`@autorest/autorest` used to be a beta version of `autorest` it has been deprecated in npm to remove the confusion
