### ISSUE TITLE
No docs on config options for specific language generators

### ISSUE THREAD

**Issue by toymachiner62** [Azure/autorest#3488]
I'm trying to find the docs with the config options for java. I can't find anything on the docs here on github, but if I run `$ autorest --help` I see this:

![image](https://user-images.githubusercontent.com/485782/79998322-2a627f80-8480-11ea-810a-4119144bf0ef.png)

But If i run `$ autorest --help --java` there are no java specific config options that exist when running with `c#` instead.

**Comment by timotheeguerin** [comment]
All the docs have been rewritten, docs for flags and configuration can be found here https://github.com/Azure/autorest/blob/master/docs/generate/flags.md
