### ISSUE TITLE
Autorest does not generate powershell code from OAS3.0 files

### ISSUE THREAD

**Issue by krraghavan** [Azure/autorest#3490]
I have an OAS 3.0 compatible file (loads fine on editor.swagger.io).  Autorest fails to generate the powershell client code from this spec.  I get an error (could be due to inability to process vendor extensions).

AUTREST INFO:
```
$ autorest --info
AutoRest code generation utility [cli version: 3.0.6187; node: v11.12.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location 
 core       @autorest/core                           3.0.6274     /Users/raghavan.kollivakkam/.autorest/@autorest_core@3.0.6274
 extension  @autorest/powershell                     2.1.380      /Users/raghavan.kollivakkam/.autorest/@autorest_powershell@2.1.380
 extension  @autorest/remodeler                      2.1.27       /Users/raghavan.kollivakkam/.autorest/@autorest_remodeler@2.1.27

```
Swagger file attached (with .txt extension to upload to GitHub)
[swagger-all-0.1.0-SNAPSHOT.yaml.txt](https://github.com/Azure/autorest/files/4540512/swagger-all-0.1.0-SNAPSHOT.yaml.txt)

**Comment by jdelforno** [comment]
You might save people time trying to correct this by providing the error / message.
