### ISSUE TITLE
Sample running Autorest as part of gated build?

### ISSUE THREAD

**Issue by abatishchev** [Azure/autorest#3495]
HI,
I'm thinking to run Autorest as part of gated build, something like this:

    autorest --azure-validator --openapi-type=arm --input-file=specification\myrp.json

I'm wondering if you have any sample or recommendations if I should/shouldn't do that. How to detect errors? Would autorest.exe exit with non-0 code if there were validation errors?

**Comment by abatishchev** [comment]
Ping, anyone. A piece of advice, please?

**Comment by abatishchev** [comment]
Ping. Anyone? A piece of advice, please?

**Comment by daviwil** [comment]
Yes, AutoRest will exit with a non-zero error code if there are any errors during execution.  If you find that it doesn't, let us know and we'll look into it.
