### ISSUE TITLE
Can you please provide Azure async operation  GET response type spec 

### ISSUE THREAD

**Issue by kattamudi-karthik** [Azure/autorest#3496]
Can you please give an example on  how to declare  a response type for azure async operation in swagger 2.0. 
So user submits a post request and
it gets accepted (202) and as part of its response  we get a Get  URL to monitor the post request.Then after polling the URL we will be  getting a response for the posr request. 
Basically I should be able to declare a get response type for my async operation .

**Comment by timotheeguerin** [comment]
There is some example for long running operations here https://github.com/Azure/autorest.testserver/blob/master/swagger/lro.json, 
here is some info about the flag https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-long-running-operation
