### ISSUE TITLE
OpenAPI V3 - Cannot parse OpenAPI v3 definition file with schema containing 'additionalProperties' with boolean value

### ISSUE THREAD

**Issue by cermakp** [Azure/autorest#3497]
Hello,

I started to use the latest version of autorest (3.0.6187) which supports OpenApi v3. I have definition file generated from swagger using SwashBuckle library (using .net core application).

I am generating client with autorest using parameter `--v3`. However autorest returns following error
`FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.BrandDto.additionalProperties', line 1, position 1439.`

![image](https://user-images.githubusercontent.com/49719500/81270542-2ec79480-904b-11ea-91e0-192571a4d955.png)

It seems that autorest does not support boolean values for `additionalProperties` as it is supported by OpenApi v3. **Anyway if I change the `additionalProperties : false` to `additionalProperties : {}` it starts to work.** 

Here is the sample json used:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Product Global Taxonomy Service API",
    "version": "v1"
  },
  "paths": {
    "/taxonomy/brands": {
      "get": {
        "summary": "Provides taxonomy brands",
        "operationId": "GetTaxonomyBrandsDeprecated",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BrandCollection"
                }
              }
            }
          }
        },
        "deprecated": true
      }
    }
  },
  "components": {
    "schemas": {
      "BrandDto": {
        "type": "object",
        "properties": {
          "taxonomyBrandId": {
            "type": "integer",
            "description": "Surrogate Brand Id",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "description": "Brand name",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "BrandCollection": {
        "type": "object",
        "properties": {
          "collection": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BrandDto"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by kevinoid** [comment]
Looks like the same issue as #3439?

**Comment by cermakp** [comment]
Hi, the thread  #3439 is more likely related to v2 of autores as the user runs the old implementation (without `--v3 `parameter). Anyway as it is mentioned that it should be fixed - no unfortunately it is not fixed.

**Comment by daviwil** [comment]
Copying my comment over from #3439 

> You also need to use an AutoRest extension that works with the v3 pipeline, `2.3.82` does not support it.  Try adding this parameter `--use:@autorest/csharp-v3@3.0.0-dev.20200512.1`.  Note that the new v3-supporting C# generator is under development and not fully released yet.

**Comment by cermakp** [comment]
Hi, using `--use:@autorest/csharp-v3@3.0.0-dev.20200512.1` or `--use:@autorest/csharp-v3@https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200512.9/autorest-csharp-v3-3.0.0-dev.20200512.9.tgz` (as mentioned [here](https://github.com/Azure/autorest/issues/3439#issuecomment-627650877)) did not help. 

However using parameter `--version=3.0.6274` helped! Thanks to [bernarden](https://github.com/Azure/autorest/issues/3492#issuecomment-626982911)

**Comment by ffMathy** [comment]
I am experiencing this too.

**Comment by ffMathy** [comment]
@cermakp can this somehow be applied to `@autorest/typescript` too?

**Comment by timotheeguerin** [comment]
@ffMathy is your issue around schema validation? If so I have a fix here to resolve that  #4006.

**Comment by ffMathy** [comment]
@timotheeguerin interesting. However, with the latest version, it still happens. How can I test those changes?

**Comment by boulc** [comment]
> @timotheeguerin interesting. However, with the latest version, it still happens. How can I test those changes?

I just had the same issue and managed to test the fix:
1. Upgraded autorest to next version (this might not be required): `npm install -g autorest@next`
2. Update the configuration file to use next version of `@autorest/modelerfour`
```yaml
use-extension:
  "@autorest/modelerfour": "next"
```
3. Call `autorest` with `--version=next`

**Comment by ffMathy** [comment]
Thank you! 🙏

**Comment by timotheeguerin** [comment]
The only thing that should matter here is the core version (`--version=next`). Closing as this seems to have been resolved. Will publish to latest in the next few days.
