### ISSUE TITLE
Subdomain is not used

### ISSUE THREAD

**Issue by RonFrick** [Azure/autorest#350]
Hello, 

I just want to start off by saying how awesome this whole project is and how excited I am to be able to use it. That being said I am having an issue. The ServiceClient is cutting off the subdomain for my API. When the class is initiated I am telling it to use http://localhost/my.api/ as the base URI but all request are simply made to https://localhost/

So for one of my methods I would expect this...
 http://localhost/my.api/GetColors
but what it shows in fiddler is this...
http://localhost/GetColors

Any ideas?

Thanks, Ron

**Comment by devigned** [comment]
Should be fixed in the dev branch via https://github.com/Azure/autorest/pull/333.
