### ISSUE TITLE
README "Client Runtimes" link 404

### ISSUE THREAD

**Issue by southpolesteve** [Azure/autorest#3501]
https://github.com/Azure/autorest/blame/master/readme.md#L63

I took a quick look at the docs, but couldn't determine which page this link was supposed to go to

**Comment by silasary** [comment]
So, it links to https://github.com/Azure/autorest/blob/master/.attic/developer/architecture/Autorest-and-Clientruntimes.md

But that file is not very useful, and has more 404s
