### ISSUE TITLE
Code generation of JSON string payload as object needing custom serialization/deserialization code 

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest#3504]
For properties designated as object but in reality is a JSON string payload, for many languages, custom serialization/deserialization logic needs to be added to help correctly handle it. 

If we keep the current type definition, we should have out of box handling for passed in string values.

**Comment by timotheeguerin** [comment]
I added some documentation around handling raw content https://github.com/Azure/autorest/blob/master/docs/openapi/howto/binary-payload.md
Please reopen if this doesn't resolve the problem
