### ISSUE TITLE
Style: form is the default, yet autorest seems to default to CollectionFormat: none

### ISSUE THREAD

**Issue by Terra-jin** [Azure/autorest#3519]
Hi,

When using Swashbuckle 5.4.1 and autorest 3.0.6282, query parameters need to be manually set to style: form in spite of this being the default according to [the spec](https://swagger.io/specification/#parameter-object).

For details, please see [this issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1701) logged with Swashbuckle.

**Comment by mshasib** [comment]
Any update on when this will be fixed?

**Comment by timotheeguerin** [comment]
Hi, 
Autorest with v3 generators shouldn't be overriding the default. If you can still reproduce with the latest generators it might be an issue with the generator or the azure core library itself. Please share the autorest command line you used if you are stil having issues
