### ISSUE TITLE
CSharp Long Running Operation Compiler Error

### ISSUE THREAD

**Issue by trebconnell** [Azure/autorest#3526]
> `[cli version: 3.0.6187; node: v14.2.0]`

I am getting compilation errors when I try to use the `x-ms-long-running-operation` extension in C#.

Error is: `error CS1503: Argument 2: cannot convert from 'Microsoft.Rest.Azure.AzureOperationHeaderResponse<Microsoft.Azure.Test.Models.TestsCreateHeaders>' to 'Microsoft.Rest.Azure.AzureOperationResponse'`
Because; `AzureOperationHeaderResponse` Implements `IAzureOperationResponse`, not `AzureOperationResponse`

I tried using newer versions of the Microsoft.Rest.ClientRuntime nuget feeds but hit more issues with those.  I can't find reference to specific versions to use, are there?  I'm using these currently:
`"Microsoft.Rest.ClientRuntime" Version="2.3.21", "Microsoft.Rest.ClientRuntime.Azure" Version="3.3.19"`

Repro is here.  Should be able to just `autorest readme.md --csharp` then `dotnet build`.
Or just `dotnet build` because I included my generated files for reference.
[AutoTest.zip](https://github.com/Azure/autorest/files/4838684/AutoTest.zip)

Thanks for assistance!

**Comment by timotheeguerin** [comment]
Believe this is resolve in the latest versions, please reopen an new issue if you are still encountering a problem.
