### ISSUE TITLE
Error: Collision detected inserting into object: toString

### ISSUE THREAD

**Issue by omerlh** [Azure/autorest#3530]
Trying to generate TS client for Jira using the public [openapi spec](https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json?_ga=2.42618085.1961817143.1593935971-2095355151.1588598316). This is the command I used:
```
autorest-beta --v3 --add-credentials  --input-file=swagger.json --typescript --package-name=<> --output-folder=generated
```

Version - "@autorest/autorest": "^3.0.6187"

**Comment by timotheeguerin** [comment]
Closing in favor of #4029
