### ISSUE TITLE
Autorest azure-validator provides incorrect warning on OperationId.

### ISSUE THREAD

**Issue by whisper6284** [Azure/autorest#3531]
I am receiving the following warning when I run autorest with the azure-validator flag, on the Swagger file listed below.

WARNING (PostOperationIdContainsUrlVerb/R2066/SDKViolation): OperationId should contain the verb: 'something' in:'something_do'. Consider updating the operationId

Command: autorest --v3 --input=sample.json --azure-validator

Swagger:
```json
{
    "swagger": "2.0",
    "info": {
      "title": "Sample service",
      "description": "Sample service",
      "contact": {
        "email": "sampleaddress@mail.com"
      },
      "version": "2020-07-20-sample"
    },
    "paths": {
      "/something": {
        "post": {
          "tags": [
            "something"
          ],
          "summary": "Does something",
          "operationId": "something_do",
          "responses": {
            "200": {
              "description": "Something got done.",
              "schema": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
```
The format contradicts the guidelines for OperationIds given in https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#OperationOperationId.

If I replace the OperationId with "do_something", then the warning goes away. But this is again inconsistent with the guidelines given.

**Comment by timotheeguerin** [comment]
This is an issue with the azure validator, could you reopen an issue there https://github.com/Azure/azure-openapi-validator
