### ISSUE TITLE
How to suppress Autorest Azure Validator errors that applies only to ARM specs, and not data plane specs.

### ISSUE THREAD

**Issue by whisper6284** [Azure/autorest#3533]
When I run autorest --v3 --input=sample.json --azure-validator on my Swagger file, I receive the following error.

ERROR (OperationsAPIImplementation/R3023/ARMViolation): Operations API must be implemented for '/providers//operations'

I understand this is required for ARM (control-plane) API. According to the list of violations, https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#arm-violations, this is not required for the data-plane API.

Is there a way to suppress ARM-only violations when running autorest? I tried --azure-arm=false, but to no avail.

**Comment by timotheeguerin** [comment]
You can use suppression directives to ignore some errors See this other data-plane and their suppression as an example https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imds/data-plane/readme.md#suppression
