### ISSUE TITLE
Azure Digital Twins API SDK - Module doesn't work properly

### ISSUE THREAD

**Issue by pauldj54** [Azure/autorest#3541]
Dear Autorest team, 
I hope this is the right place to discuss this issue.
I auto-generated the python SDK to manage Azure Digital Twins preview (V2) models using the swagger file as proposed in https://docs.microsoft.com/en-us/azure/digital-twins/how-to-create-custom-sdks 
When trying to **add** some models I am not able to get the error if the response code is different than 200.
The error is produced, because the name of one of the packages (models) is the same as the name of a variable in the add function (models).
Hier an excerpt from the code:

**Main script**
`client = AzureDigitalTwinsAPI(credentials = credentials, base_url = config['endpoint'])
with open(r"..\models\SampleModel.json") as f:
  dtdl = json.load(f)
dtdl_list = []
dtdl_list.append(dtdl)`

**module: digital_twin_models_operations.py:**
`def add(
            self, **models**=None, custom_headers=None, raw=False, **operation_config):`

**Here the error handling:**
`        if response.status_code not in [200]:
            raise models.ErrorResponseException(self._deserialize, response)`

models in this context has two meanings:

- models from the package digitaltwins.models

- models from the "add" function input variable, which is a list

The code throws an error:
`'list' object has no attribute 'item'`

Because the wrong models is used. 

It is not recommended to change auto-generated code, but how should I proceed in this case?

Changing the input variable from models to model solved this issue but I cannot determine the side effects. 

Best regards, 
Paul

**Comment by lmazuel** [comment]
Got fixed in recent autorest.python releases
