### ISSUE TITLE
Request: Add line numbers to errors

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest#3559]
It would be convenient and handy to know what line number caused this issue:

![image](https://user-images.githubusercontent.com/21269347/88874733-a03f5b00-d1d4-11ea-8625-393e89e1407a.png)

**Comment by pakrym** [comment]
cc @daviwil

**Comment by timotheeguerin** [comment]
Syntax error in the json have the correct lines reported in the latest version of core.

**Comment by annelo-msft** [comment]
@pakrym , @chamons, will a change be needed to our c# code generator to output the JSON line numbers in the generator output?  I would help us debug if we could know what line in the swagger file was causing a given error.

**Comment by chamons** [comment]
I filed https://github.com/Azure/autorest.csharp/issues/1082 to cover this.

**Comment by annelo-msft** [comment]
Thanks @chamons!!
