### ISSUE TITLE
Inconsistent behavior with different autorest versions. 

### ISSUE THREAD

**Issue by priyankajayaswal1** [Azure/autorest#3563]
I am using swagger spec 3.0.1 to generate a python client using autorest. I see varied behavior with different versions.
Observation:
```
1. from 6267 - 6277 - FATAL: System.NullReferenceException: Object reference not set to an instance of an object. is coming
2. from 6280 - 6300 - FATAL: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.SomeObject.additionalProperties', line 1, position 88165. is coming
3. from 6302 and above it is creating client but without base_url which we need for implementation. 
```
Can you help us figure out either:
1. How to use the clients generated using ```azure.core``` 
2. How to fix above issues **even manually meantime** so that somehow we may create client with base_url support.

Related to issue: https://github.com/Azure/autorest/issues/3492
Since I see this swagger.json is eventually able to create a client, I suspect it is not wrong.
Would need to understand what manual update I may make to make autorest work for my swagger.json.

cc: @fearthecowboy

**Comment by priyankajayaswal1** [comment]
Is there a baseline validator tool for swagger 3.0 spec?

**Comment by iscai-msft** [comment]
@priyankajayaswal1 it looks like this error is thrown before it actually reaches the "python" part of the pipeline. For autorest core and modelerfour parse the swagger and output it to the python generation, these errors look like they're thrown while parsing the swagger file. These steps have also changed with the new autorest, which is probably why you're seeing this different behavior.
I'm not super familiar with these errors so I can't give a good answer without looking at the swagger, tagging @daviwil who owns this part of the pipeline. 

One thing is that it looks like you don't have a base URL defined. There's two ways of defining one. The simplest looks like [this](https://github.com/Azure/autorest.testserver/blob/master/swagger/body-complex.json#L8), but replace this value with the actual base URL you're using. For management plane, it would be `management.azure.com`. A more complicated scenario would be a custom base URL, that takes in parameters. See [here](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-parameterized-host) for an intro to that.

**Comment by timotheeguerin** [comment]
Hi @priyankajayaswal1 are you still having some issue? If so could you share your latest specs and command line used?
