### ISSUE TITLE
Fail on Ubuntu 20.04 LTS on WSL

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/autorest#3566]
The same MD and JSON file work on Windows 10 with the same Node version , while fail on WSL.
[log.txt](https://github.com/Azure/autorest/files/5083759/log.txt)
[input-file](https://github.com/Azure/azure-rest-api-specs/blob/145513669e3d329e1549d714877ba720d8f0d253/specification/signalr/data-plane/AzureSignalR/v1/azuresignalr.json)
# Azure SignalR Service REST API

> see https://aka.ms/autorest

This is the AutoRest configuration file for SignalR.

``` yaml
input-file: docs/swagger/v1.json
```

## Alternate settings

``` yaml $(csharp)
license-header: MICROSOFT_MIT_NO_VERSION
override-client-name: GeneratedRestClient
namespace: Microsoft.Azure.SignalR
output-folder: src/Microsoft.Azure.SignalR.Common/Generated
add-credentials: true

**Comment by daviwil** [comment]
This line provides a hint:

```
No usable version of the libssl was found
```

Try running `sudo apt install libssl-dev` and try AutoRest again.

**Comment by Y-Sindo** [comment]
> Try running sudo apt install libssl-dev and try AutoRest again.
Thanks. This works. But a new exception was thrown: [Exception] No input files provided.

**Comment by Y-Sindo** [comment]
Sorry, I found Ubuntu 20.04 is not supported yet.
