### ISSUE TITLE
Multiple inheritance giving issues in python client generation (_subtype_map)

### ISSUE THREAD

**Issue by mitsha-microsoft** [Azure/autorest#3573]
I have an interface and an abstract class in this way
```csharp
public interface IAnimal
{
   public someEnum Type;
}

public abstract class Pet
{
  public someEnum Type;
}
```
There are few classes that inherit + implement both and some of them implement either one of them, for (the lack of better?) example

```csharp
public class Dog: IAnimal, Pet
{
  public string Name;
}

public class Tiger: IAnimal
{
  public int NoOfTeeth;
}
```

The respective OpenApi spec that is created looks like this (relevant part)
```json
"Pet": {
...
"discriminator": "type"
}
"Dog": {
  "allOf": [
    {
        "$ref": "#/definitions/Pet
    }   
   ]
}
```

Since there is no support for `anyOf` or `oneOf` in the current version of AutoRest and `allOf` can only be one, the generated client class for `IAnimal` doesn't contain a `_subtype_map` for `Dog` and thus the deserialization for `Dog` when sent to a model that expects `IAnimal` fails. What can be the workaround/solution to have this multiple inheritance, since we can't have a multiple `allOf`? Also, is there any plan to support it in coming future, because we have a dependency on this client for an API and if this doesn't work, we might need to change our model.

**Comment by mitsha-microsoft** [comment]
I assume this was also mentioned in #1180 and it was said in that one that support will be added later.

**Comment by timotheeguerin** [comment]
Hi @mitsha-microsoft are you still having this issue, I tried the example linked in your comment and it does seem to be declaring the subchild types accordingly. If you do could you share the entire spec(or at least all the schemas) that repro the issue
