### ISSUE TITLE
C# AutoRest Generates code that blows out BaseUrl parameters

### ISSUE THREAD

**Issue by mrcunninghamz** [Azure/autorest#3577]
In the case that a swagger document doesn't show the `api-version` parameter for a particular endpoint... 
(this is a limitation that we ran into with Azure APIM implantation of api versioning via parameter)

We are attempting to include the parameter as part of the base URL.

```csharp
    var credentials = new TokenCredentials(token);
    var uriBuilder = new UriBuilder(customersApiOptions.BaseUrl);
    uriBuilder.Query = $"api-version={customersApiOptions.ApiVersion}";
    var baseUri = uriBuilder.Uri;
    var client = new CustomersApiClient.CustomersApiClient(baseUri, credentials);
```

Unfortunately the code generated by autorest blows away any parameters in the url:

```csharp
    var _baseUrl = Client.BaseUri.AbsoluteUri;
    var _url = new System.Uri(new System.Uri(_baseUrl + (_baseUrl.EndsWith("/") ? "" : "/")), "api/Customers/{id}").ToString();
    _url = _url.Replace("{id}", System.Uri.EscapeDataString(id));
```

If its possible afterwards check to see if parameters exist and then add them?

```csharp
if (!string.IsNullOrEmpty(Client.BaseUri.Query))
{
     _queryParameters.Add(Client.BaseUri.Query.Substring(1));
}
```

At the moment, the above is what we are adding in manually. But if possible it would be nice if the generated code did that.

**Comment by timotheeguerin** [comment]
Hi @mrcunninghamz  are you still having problems?

Are you using swagger 2 or openapi 3.0, for swagger 2 we have a custom extension that should let you do that(unless I misunderstand your issue) https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-parameterized-host

If this doesn't solve the issue could you share your openapi spec?
