### ISSUE TITLE
Can we specify what line ending to create clients in via commandline parameters.

### ISSUE THREAD

**Issue by priyankajayaswal1** [Azure/autorest#3581]
The use case is that our dev machine is windows and WSL2 and our pipeline is in Linux. We have enabled LF in VScode and VS. We tend to see autorest generated clients as CRLF always, since we mostly run it in windows. Is there a way we may parametrize the line endings for clients in windows at the time of client generation?

**Comment by BlackRider97** [comment]
We are also searching for similar configurations. Currently git shows files modified in not-staged area but they only differ by line encoding.

**Comment by BlackRider97** [comment]
@stankovski  Please let us know if there is any configuration to do that.

**Comment by timotheeguerin** [comment]
Hi all, 

Have this PR implementing this functionality. You can give it a try following the instructions here https://github.com/Azure/autorest/pull/4194#issuecomment-869913063 and let us know if everything works as expected.
