### ISSUE TITLE
c# validation nullable value

### ISSUE THREAD

**Issue by audunn** [Azure/autorest#3585]
Hi,
We have a swagger spec with a value that is conditional/optional i.e. can be null with some validation constraints this is presented like so:
```
        "totalThroughputMibps": {
          "type": "number",
          "x-nullable": true,
          "description": "Total throughput of pool in Mibps",
          "example": 164.221,
          "readOnly": true,
          "multipleOf": 0.001
        }
```

This causes issues with c# generated SDK where the validation code does not allow null values.

```
            public double? TotalThroughputMibps { get; private set; }
.
.
.
.
.
            if (TotalThroughputMibps % 0.001 != 0)
            {
                throw new ValidationException(ValidationRules.MultipleOf, "TotalThroughputMibps", 0.001);
            }
```

Is it possible to present this in the swagger so that the validation in the generated code handles null values correctly?

**Comment by johanste** [comment]
Why is the value sent with a `null` value from the service rather than the key/value being omitted alltogether?

**Comment by johanste** [comment]
...and why does the C# code generator ever run validation on a `readOnly` value?

**Comment by audunn** [comment]
The issue is client side, f.ex. when creating the parent resource and with validation like this the user/caller cannot construct the parent object without initializing this property that is not required i.e. not mandatory as it is nullable.
I cannot see why the validation is implemented like this and I am mostly interested in what would be the correct/best way to do this.

**Comment by audunn** [comment]
Sitting for a while now is there a way to get issue looked at here?

**Comment by srchilu** [comment]
We are facing similar issue in office machines (msft) while generating c# sdk.
autorest version:
core       @autorest/core                           3.0.6274     C:\Users\srchilu\.autorest\@autorest_core@3.0.6274
AutoRest code generation utility [cli version: 3.0.6187; node: v12.19.0, max-memory: 8192 gb]

Seen this issue with both .net core 3.1.9 and 3.1.8 versions.

**Comment by daviwil** [comment]
@srchilu Can you provide an example of how you're invoking AutoRest when you see this issue?

**Comment by priyankajayaswal1** [comment]
We are invoking it by using the following command.
`autorest --csharp --v3 --input-file=docs\open-api-specs\latest\swagger.json --output-folder=service_client --verbose --namespace=auto_generated --version=3.0.6274
`
This is the exact command we use. The behavior seems to be inconsistent when running in office systems (msft ) and when running in my laptop.

**Comment by priyankajayaswal1** [comment]
@daviwil can you have a look at it, since we are really dependent on autorest to not change it's behavior and break things in between for our system to work. This looks more of a regression issue (not sure of what exactly). Adding a snippet on how is the change breaking things for nullable entities.
![image](https://user-images.githubusercontent.com/7633366/98280417-60e98d00-1fc1-11eb-8399-dd188ef6331a.png)

Without the null checks the created csharp client using command:

`autorest --csharp --v3 --input-file=docs\open-api-specs\latest\swagger.json --output-folder=service_client --verbose --namespace=auto_generated --version=3.0.6274`

is bound to not be robust. We really need this to resolve ASAP. You may reach out to me at alias: prjayasw on MSTeams

**Comment by pakrym** [comment]
@priyankajayaswal1 can you clarify why the code change you included is breaking?

**Comment by pakrym** [comment]
As to the original issue in this thread, I believe it's fixed as part of https://github.com/Azure/autorest.csharp/issues/885.

Try adding `--use:@microsoft.azure/autorest.csharp@2.3.90` to your command line.

**Comment by priyankajayaswal1** [comment]
@pakrym above links exactly what we wanted to have resolution for. I somehow ended on this thread. But thanks for sharing the details. Above resolves my issue.
Just curious what made the default behavior to break exactly. Any idea?

**Comment by pakrym** [comment]
>Just curious what made the default behavior to break exactly. Any idea?

I'm sorry, I don't fully understand the question.

**Comment by priyankajayaswal1** [comment]
What caused bug [Azure/autorest.csharp#885](https://github.com/Azure/autorest.csharp/issues/885)?

**Comment by pakrym** [comment]
We didn't generate a null-check before trying to validate nullable properties causing the generated code not to compile.

**Comment by daviwil** [comment]
@audunn Does the [above resolution](https://github.com/Azure/autorest/issues/3585#issuecomment-726358959) fix your issue?

**Comment by audunn** [comment]
@daviwil  apologies for the late reply, yes indeed this does seem to fix the issue.
