### ISSUE TITLE
Error running autorest commands

### ISSUE THREAD

**Issue by RupengLiu** [Azure/autorest#3587]
While I was running any commands of autorest, I got error like, but didn't get error by running other npm module
![image](https://user-images.githubusercontent.com/29927264/93128152-eae13d80-f683-11ea-9795-82573920cdcc.png)

even after try increase the space size 
![image](https://user-images.githubusercontent.com/29927264/93128256-0ea48380-f684-11ea-86d8-6069a72d13f2.png)

**Comment by daviwil** [comment]
Hi @RupengLiu, can you try this with the latest AutoRest?  Just run `npm install -g autorest` and you should receive the latest version.

If you still see the issue after updating, you may be using the bundled version of Node.js that comes with Visual Studio.  Other people have had issues running AutoRest with it so I'd recommend uninstalling it and install the official Node.js 12 LTS release from https://nodejs.org.
