### ISSUE TITLE
Disable unnecessary warnings to surface the important ones

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#3593]
Some warnings are very noisy and people get distracted by those. We want people to see the actual warnings, so that they can diagnose the real issue. To avoid these situations can we disable these kind of warnings, if we are not planning to fix it in near future?

I see `AllOfWhenYouMeantRef`, `SchemaMissingType` and `CheckDuplicateSchemas` warnings a lot. If we hide these, then people can concentrate on the actual issue.

**Comment by timotheeguerin** [comment]
Closing this as you can use `suppressions` to ignore warnings
```yaml
suppressions:
  - code: <error-code>
     reason: <reason>
```
