### ISSUE TITLE
How to use swagger.json with example attributes with locale changes with autorest

### ISSUE THREAD

**Issue by priyankajayaswal1** [Azure/autorest#3596]
Use case:

We are using OpenAPI.NET - [https://github.com/microsoft/OpenAPI.NET](https://github.com/microsoft/OpenAPI.NET) to modify swagger.json to accommodate examples. Our model uses `OpenApiDouble` which internally updates the example with locale changes as per implementation here: [LINK](https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs#L192)

With this swagger.json when we try to run autorest for client gen it fails. Wanted to understand, it that capability is there in autorest? If not, what might be a suggested way to go about it?

**Comment by priyankajayaswal1** [comment]
I am able to create clients with the locale changes swagger.json file on a system where locale is not set. That is I asked the file from the person for which this was failing and it worked for me. Can you once validate if that behavior is expected?

**Comment by timotheeguerin** [comment]
Hi @priyankajayaswal1 I am not really sure what you are asking here. Do you have a swagger.json that is not doing what you expect? Or are you asking how to update the file correctly?
