### ISSUE TITLE
Need to update document to clarify which linux distro that autorest supports now.

### ISSUE THREAD

**Issue by rollingage** [Azure/autorest#3601]
I'm trying to use autorest on "WSL 2 + ubuntu" (the default version in Windows Store is "Ubuntu 20.04.1 LTS")

Autorest does not work on ubuntu 20.04.1 LTS!

`
autorest --input-file=petstore.yaml --csharp --output-folder=CSharp_PetStore --namespace=PetStore
`
```
... 
No usable version of the libssl was found
FATAL: csharp/simplifier - FAILED
FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
```

This forked repository mentioned that autorest supports up to ubuntu 16.04
https://github.com/amarzavery/AutoRest

I tried ubuntu 16.04, and it works, but have to install another package firstly. (it was also mentioned in amarzavery's repo)
sudo apt-get install libunwind8 -y

**Comment by daviwil** [comment]
Try running `sudo apt install libssl-dev` and then try AutoRest again.

**Comment by rollingage** [comment]
@daviwil, thanks for your help, I tried it but got the same error.

`AutoRest code generation utility [cli version: 3.0.6247; node: v12.18.4, max-memory: 2048 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/home/dylandev/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist' (3.0.6320)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.90)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
realpath(): Permission denied
realpath(): Permission denied
realpath(): Permission denied
No usable version of the libssl was found
Process() cancelled due to failure`

Also, there is some annoying info in the log "realpath(): Permission denied", (known issue? I also have it on Ubuntun 16.04 but no issue to get generated code)

I'm wondering how does it used in teams, is there anyone use WSL2+Ubuntun latest?

**Comment by archanaiyer** [comment]
I'm trying to run the sample in the autorest project here: https://github.com/Azure/autorest/blob/master/docs/examples/generating-a-client.md 

I'm seeing the same issue as mentioned above (even after trying to install libssl-dev)
```
autorest --input-file=petstore.yaml --csharp --output-folder=CSharp_PetStore --namespace=PetStore
AutoRest code generation utility [cli version: 3.0.6247; node: v12.18.4, max-memory: 2048 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/home/ariye/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.90)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
realpath(): Permission denied
realpath(): Permission denied
realpath(): Permission denied
No usable version of the libssl was found
FATAL: csharp/simplifier - FAILED
FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
```

Is this a known issue on WSL? What else can I try?

**Comment by daviwil** [comment]
Thanks for pointing this out, it seems like the current release of @microsoft.azure/autorest.csharp is built with an older .NET Core SDK which expects libssl 1.0 where Ubuntu 20 has libssl 1.1 installed.  More info can be found here: https://github.com/dotnet/runtime/issues/28079.

I'll see if I can get a new build of the generator shipped with a newer update of the SDK.

**Comment by lugolven** [comment]
Did someone find a work around for this issue?

**Comment by older** [comment]
So are there any plans to update autorest to use LTS version of .NET?

As far as I understand current version of aurorest is using .NET Core SDK 2.0 which has reached end of life more than 2 years ago in 2018 and is not supported by Microsoft any more. So it means that autorest doesn't work on Ubuntu 20.04 which is now default version for WSL2 and in [Microsoft hosted agents in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-177-update#ubuntu-latest-pipelines-will-soon-use-ubuntu-2004).

**Comment by timotheeguerin** [comment]
The newest CSharp generator(v3 -  `@autorest/csharp`) is using dotnet 3.1+ and should resolve this. It is now the default when running autorest. Let me know if you are still having issue on this

**Comment by timotheeguerin** [comment]
Closing, please open a new issue if you still have this problem
