### ISSUE TITLE
head-as-boolean spec

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3603]
Wanted a place to confirm the spec for this CLI parameter:

If the flag is set to true, and the operation is HEAD:
- If status is 2xx: return true
- If status is 4xx: return false
- Else raise the usual exceptions
- We SHOULD extract the Swagger description strings for the refdoc if available

Testserver:
https://github.com/Azure/autorest.testserver/blob/master/swagger/head.json

**Comment by pakrym** [comment]
Is there a work item for autorest to turn this by default for `azure-arm`?

**Comment by daviwil** [comment]
There was :) #3602
