### ISSUE TITLE
Add support for polymorphism

### ISSUE THREAD

**Issue by cfauchere** [Azure/autorest#3605]
As the readme.md mentions oneOf and anyOf are not supported. AutoRest should support polymorphism to enable scenarios like this one:
Cat : Animal
Dog: Animal

Animal[] GetAnimals() -> return a list that includes cats and dogs
Is this in the roadmap? Is there a timeline?

**Comment by Sowmyacv** [comment]
Is there any plan to support this in autorest latest

**Comment by timotheeguerin** [comment]
Hi, Polymorhism is supported using swagger/openapi `discriminator` and `allOf`? Is there something you can't do with those?

**Comment by Sowmyacv** [comment]
@timotheeguerin thanks for checking this , we need oneof , most of our API's use oneof .  I am using the latest autorest

**Comment by timotheeguerin** [comment]
Polymorphism as described in the description of this issue can be achieved in OpenAPI with the discriminator field. Using `oneOf` cannot be represented in most languages and won't be able to generate much more than an `Object` type as the union.
