### ISSUE TITLE
parameters in="header" not supported

### ISSUE THREAD

**Issue by 9Rune5** [Azure/autorest#3612]
I had the following defined for each method:
```
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Language",
            "description": "Enables translation of localized resources."
          }
        ]
```

// exp: Generate an optional parameter for this parameter
// act: 
```
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///C:/repos/restclient/swaggerunmodified.json:131:8 ($.paths["/api/v1/Job/{id}"].get.parameters)
```

**Comment by daviwil** [comment]
I think you're missing a `type` on this parameter definition, adding that will resolve the schema validation error.  See the OpenAPI (Swagger) 2.0 spec on the topic:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headerObject
