### ISSUE TITLE
Generating ansible modules

### ISSUE THREAD

**Issue by spakhare** [Azure/autorest#3613]
Hi Team,

We are looking for generating ansible modules using AutoRest. But from the readme I see as of now Autorest supports only Powershell, Python, Java, and few other languages.

Can you please confirm if there are any plans to support generating ansible modules?

Thanks!

**Comment by daviwil** [comment]
Highly unlikely without someone from the community kicking off the effort.  What exactly would an AutoRest-generated Ansible module do?  AutoRest is focused on generating code from Swagger(REST API) specs so I'm curious to know how it'd relate to Ansible.

**Comment by spakhare** [comment]
Thanks, @daviwil for sharing details. Actually, we have certain actions available in the form of REST APIs. As most of the users prefer ansible modules over making direct API calls if we could get equivalent Ansible modules that could simplify their tasks. 

I also noticed another project (https://github.com/Azure/autorest.ansible) but looks like there are not many developments there. The last commit was around 4 months back. Not sure if we could go ahead and use that.

Between, I also see Azure provides ansible collections. Any idea of how these modules are generated?
Azure Ansible collections: https://github.com/ansible-collections/azure

**Comment by timotheeguerin** [comment]
There is no plans to add ansible generation at this time. For you question on how the module are generated, I don't really know, I would ask that question on their repo.
