### ISSUE TITLE
Set head-as-boolean to true for azure-arm libraries

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3614]
See https://github.com/Azure/autorest/issues/3603

**Comment by daviwil** [comment]
I just merged a fix for this earlier today in PR https://github.com/Azure/autorest/pull/3610 but apparently it didn't get shipped due to a new error in the release pipeline.  I'll get this fixed and shipped in the morning.

**Comment by daviwil** [comment]
OK, finally got CI fixed and the new update is out!
