### ISSUE TITLE
Multiple `requestBody` with `type: object` results in BodyModelModelModel....

### ISSUE THREAD

**Issue by absolutejam** [Azure/autorest#3619]
Alright, so I murdered the title a little...

I have a built OpenApi spec for MatterMost that I've had to perform a few tweaks on to get working (thank god for transforms!), but I noticed when I built it, I ended up with `Models/BodyModel.cs` all the way to `BodyModelModelModelModelModelModelModelModelModelModel...cs`.

When I compared the fields in the generated classes, it looks like these `BodyModel`s are created for each instance of a `requestBody` with `type: object`. Stripping the spec down to just 2 instances confirmed this, as I ended up with `BodyModel` and `BodyModelModel`.

Is there a way around this without altering the generated spec? Can I transform some of these `BodyModel`s into appropriately named classes for the path involved?

Thanks!

**Comment by timotheeguerin** [comment]
Can you try setting the `title` property on the body definition. It should be using that for generating the model name.
