### ISSUE TITLE
Use-DateTimeOffset config is not supported by AutoRest

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest#3620]
According to [this guide](https://github.com/Azure/autorest/blob/master/docs/user/command-line-interface.md#commonly-used-settings), specifying `use-datetimeoffset` should change the type of date-time properties from `DateTime` to `DateTimeOffset`. AutoREST doesn't seem to respect this configuration.

### Repro steps:
- Environment
``` ps
AutoRest code generation utility [cli version: 3.0.6187; node: v13.11.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\peter\.autorest\@autorest_core@3.0.6258\node_modules\@autorest\core\dist' (3.0.6258)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.370)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
WARNING: Schema violation: Data does not match any schemas from 'oneOf'
```
- Generation
``` ps
autorest --powershell --use-datetimeoffset --input-file:.\Users.user.yml 
```
- [Users.user.yml](https://gist.github.com/peombwa/b036a1d4b70dfe4cccd6003cb5265022)

The generated models still have date-time properties of type `DateTime`.
``` cs
/// <summary>Backing field for <see cref="CreatedDateTime" /> property.</summary>
private global::System.DateTime? _createdDateTime;

/// <summary>The created date of the user object.</summary>
[Sample.API.Origin(Sample.API.PropertyOrigin.Owned)]
public global::System.DateTime? CreatedDateTime { get => this._createdDateTime; set => this._createdDateTime = value; }
```

Related to https://github.com/Azure/autorest.powershell/issues/584

**Comment by timotheeguerin** [comment]
Hi #peombwa are you still having problem?

The spec you linked has some errors. The latest autoerst does a much better work telling you what it is. But you can see that on `editor.swagger.io` it shows you those errors.
![image](https://user-images.githubusercontent.com/1031227/113227661-0ee32580-9248-11eb-8f26-7317b0316698.png)

**Comment by peombwa** [comment]
This is still a blocking issue for us. MS Graph API expects all date time properties to be of type `DateTimeOffset` for `Edm.DateTimeOffset`.
