### ISSUE TITLE
Add a new flag to ensure the use of V2-era generators

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest#3622]
After some discussion, it sounds like we intend to start defaulting the `--[language]` parameters to the new V3 generators and add a new `--legacy` parameter which will be configured to load the V2-era language generator for users who need it.  For example, `autorest --python --legacy` would load `@microsoft.azure/autorest.python` with V2 core instead of the new V3 generator and core.

Pavel requested that we have an internal configuration parameter called `track2` which is the inverted value of `--legacy` (e.g. it is `true` when `--legacy` is false or not specified).  This would enable V3 generators to know with certainty whether the users intent was to generate a Track 1 or Track 2 library.

The only other question that occurred to me: should we immediately start defaulting to V3 generators for languages that are GA-ready or wait until all V3 generators are ready?

/cc @lmazuel @pakrym

**Comment by pakrym** [comment]
I think we need to notify partners and update all existing usages to start passing `--legacy` before we do any changes to defaults.

**Comment by pakrym** [comment]
We might also consider adding a warning sometime before the change to prepare customers for migration.

**Comment by daviwil** [comment]
I am currently looking into a way to log messages from AutoRest configuration blocks so that we can start displaying messages like this.
