### ISSUE TITLE
autorest failing to override package-name

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3625]
![image](https://user-images.githubusercontent.com/43154838/97755385-6e89a900-1acf-11eb-8dd2-c3abb583961e.png)

In this case, package-name should be overridden to `multiapiwithsubmodule#submodule`, however it's still the original (it's not just an issue bc of the `#`). Other configs, i.e. `clear-output-folder`, and `output-folder` are correctly overridden in this case

**Comment by daviwil** [comment]
Thanks @iscai-msft!
