### ISSUE TITLE
"allof" with "$ref" will cause infinite loop

### ISSUE THREAD

**Issue by yishengjin1413** [Azure/autorest#3628]
We are using following command to resolve external reference. 

`autorest --version=2.0.4166 -FANCY -g SwaggerResolver -i $swaggerPath -outputFileName $swaggerPath`

Why we use an old version here is because we have really lots of swagger files which are not strictly follow swagger 2.0.

But now we find that if the definitions contains following content , the command will go into a infinite loop.

```
"PrivateEndpointConnectionProxy": {
      "allOf": [
        {
          "$ref": "#/definitions/PrivateEndpointConnectionProxyBase"
        }
      ]
    }
```

I just checked the code and find that the root cause is that in `swagger-loader.js` line 138, `if (typeof defSec === "string" && typeof model === "string" && visitedEntities.indexOf(model) === -1)`, it should be `if (typeof defSec === "string" && typeof model === "string" && visitedEntities.indexOf("#/"+defSec +"/"+model ) === -1)`.

can I get a fixed version base on 2.0.4166?

**Comment by timotheeguerin** [comment]
As this issue is happening on a older version of 2.x but not the latest 2.x, it is very unlikely will patch on that version. As autorest 2.x itself is will only get patch for major issues. Please open a new issue if you are having problems with the latest versions.
