### ISSUE TITLE
Duplicate header type processing issue

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3629]
**Describe the issue**
For headers, you cannot use the `schema: $ref` pattern as used for other things in swagger (it doesn't allow it). You have to define the type each time for every header. That said, currently, duplicate header definitions are handled properly (deduplicated) for request header parameters and response headers independently. However, if you define the same header in both a request header parameter AND response header, it will blow up. It seems to process these 2 things separately, which causing it to think they are duplicates. There may be other issues here since these types are extensible enums. So, fixing this issue might uncover others. Currently, this is a blocking issue for using the SchemaRegistry swagger.

Parameters `schema` usage: https://swagger.io/docs/specification/2-0/describing-parameters/#faq
Responses `schema` usage (see Response Body section): https://swagger.io/docs/specification/2-0/describing-responses/#response-body

** REQUIRED ** 
**ModelerFour** version: 4.15.423
**AutoRest-core** version: 3.0.6326
**CommandLine** : No idea
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/arerlend.sr.init/specification/schemaregistry/data-plane/Microsoft.EventHub/preview/2020-09-01-preview/schemaregistry.json

**Comment by timotheeguerin** [comment]
Just tried to repro with this simple spec and it seems to be deduplicating across both request and response headers.

```yaml
swagger: "2.0"
info:
  title: "Test"
  description: "Test"
  version: "1.0"
paths:
  /ping:
    get:
      summary: Checks if the server is alive.
      operationId: Get_Ping
      parameters:
        - in: header
          name: Flag
          type: string
          enum: ["Foo", "Bar"]
          x-ms-enum:
            "name": "MyEnum"
          required: true
      responses: 
        200:
          description: OK
          headers:
            Flag:
              type: string
              enum: ["Foo", "Bar"]
              x-ms-enum:
                "name": "MyEnum"

```

**Comment by MiYanni** [comment]
@timotheeguerin The example you have above does not have extensible enums. You need `modelAsString: true` as seen in the docs here: https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-enum

You're in luck. I found the swagger: https://github.com/Azure/azure-rest-api-specs/blob/1e23d91e875e4464e57667639e06408cef99868d/specification/schemaregistry/data-plane/Microsoft.EventHub/preview/2020-09-01-preview/schemaregistry.json
The type `SerializationType` is the one with the issue.
