### ISSUE TITLE
Support duplicate operationId and maybe overloading

### ISSUE THREAD

**Issue by brenovieira** [Azure/autorest#363]
I have these two methods Get on ClientController:
```
[RoutePrefix("api/clients")]
public class ClientController
{
	[HttpGet]
	[Route("")]
	public Client[] Get([FromUri]GetClients request)
	{
		return _clienteDao.Get(request.Condition).ToArray();
	}

	[HttpGet]
	[Route("{id}")]
	public Client Get(int id)
	{
		return _clienteDao.GetById(id);
	}
}
```

Using swashbuckle, it generates this swagger spec:
```
{
	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "API",
		"description": "API"
	},
	"host": "IP:port",
	"schemes": ["http"],
	"paths": {
		"/api/clients": {
			"get": {
				"tags": ["Client"],
				"summary": "Get all clients",
				"operationId": "Client_Get",
				"consumes": [],
				"produces": ["application/json"],
				"parameters": [{
					"name": "request.name",
					"in": "query",
					"description": "Filter by name",
					"required": false,
					"type": "string"
				},
				...
				],
				"responses": { ... },
				"deprecated": false
			}
		},
		"/api/clients/{id}": {
			"get": {
				"tags": ["Client"],
				"summary": "Get client by id",
				"operationId": "Client_Get",
				"consumes": [],
				"produces": ["application/json"],
				"parameters": [{
					"name": "id",
					"in": "path",
					"required": true,
					"type": "integer",
					"format": "int32"
				}],
				"responses": { ... },
				"deprecated": false
			}
		},
	},
	"definitions": {
		"Client": {
			"required": [...],
			"type": "object",
			"properties": {...}
		},
		"GetClients": {
			"required": [...],
			"type": "object",
			"properties": {
				"Name": {
					"description": "Filter by name",
					"type": "string"
				},
				...
			}
		},
		...
	}
}
```

When I run ```AutoRest.exe -AddCredentials true -Input '...' -Namespace API.Client -OutputDirectory '...' -OutputFileName '...' -CodeGenerator CSharp -Modeler Swagger -ClientName API```, I get this error:

> AutoRest.exe : error: [FATAL] Error generating client model: Found operation objects with duplicate operationId 'Client_Get'. OperationId must be unique among all operations described in the API.At line:1 char:1

I know I could just rename one of my methods (to GetById, for instance), or change my sawshbuckle config to generate unique operationId by appending a hash or something.

But I'd like to understand why there is this unique ```operationId``` constraint since swagger-ui works normally.

And I'd like to see ```AutoRest``` generating overload methods like these:

```public static IList<ClientModel> Get(this IClientOperations operations, string requestname = default(string))```

and

```public static ClientModel Get(this IClientOperations operations, int? id)```.

That would be great, because to make AutoRest works now I need to rename several overloaded methods in my controllers.

What do you think ?

**Comment by stankovski** [comment]
According to swagger specification 2.0 Operation Id "MUST be unique among all operations described in the API."

Source: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object

**Comment by brenovieira** [comment]
@stankovski , ok.
thanks.

**Comment by VR-Architect** [comment]
Check out this document to help with this issue. 
https://azure.microsoft.com/en-us/documentation/articles/app-service-api-dotnet-swashbuckle-customize/

Though I am still having issues, the author does seem to know this issue and proposes a solution.

**Comment by whambly** [comment]
Thank you! William Hambly.

**Comment by heldersepu** [comment]
I had this same issue and it took me a while to figure to how to fix it:
```c#

public class ClientController
{
    public Client[] Get()
    {
        return _clienteDao.Get().ToArray();
    }

    public Client Get(int id)
    {
        return _clienteDao.GetById(id);
    }
}
```

such a simple change, just rename the second method to  **GetById**
```c#
public class ClientController
{
    public Client[] Get()
    {
        return _clienteDao.Get().ToArray();
    }

    public Client GetById(int id)
    {
        return _clienteDao.GetById(id);
    }
}
```
