### ISSUE TITLE
Error on Circular $ref in policy PR

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest#3630]
**Describe the issue**
A clear and concise description of what the problem is. Help me find your problem, don't just drop a vague message and run.

Output
```
WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
FATAL: Error: Circular $ref in Model -- #/components/schemas/schemas:0 :: ["#/components/schemas/schemas:0"]
  Error: Plugin prechecker reported failure.
```

The cause is likely this line: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-03-01/policyAssignments.json#L582

A previous api-version with a different ref pattern would pass: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json#L586-L594

The definition is a bit wired, but we tried it on swagger, this is not an invalid definition.
![image](https://user-images.githubusercontent.com/53292327/97270945-e60ace80-186a-11eb-8f0a-4e315c3420a7.png)

Please let us know whether this is m4 bug, or there is indeed problem with the swagger spec.

** REQUIRED ** 
**ModelerFour** version:4.15.423
**AutoRest-core** version:3.0.6326
**CommandLine** :`autorest https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/readme.md --tag=package-policy-2020-03 --java ...`
OpenAPI/Swagger file:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-03-01/policyAssignments.json

**Comment by timotheeguerin** [comment]
This seems to be an issue with the merger. The issue only happens when there is a circular reference in the model(Property of same type of the model for example) but that is in another file.

**Comment by timotheeguerin** [comment]
Issue seems to actually be part of the deduplication. It is exactly the scenario described in openapi `$ref and Sibling Elements` here https://swagger.io/docs/specification/using-ref/

**Comment by timotheeguerin** [comment]
@weidongxu-microsoft This issue should be fix in modelerfour version . You can use the flag `--@autorest/modelerfour@4.15.441` when the pr is merged .

However you should note that the result will be that `CloudError` is not a model present in the code and all references will be pointing to `ErrorDetails` directly. If having the `CloudError` model is wanted then using `allOf` with the `$ref` inside is what you should be looking at.

**Comment by weidongxu-microsoft** [comment]
Thanks @timotheeguerin, I will try it when released.

`CloudError` not present is fine, though I think for this swagger it should be replace by `ErrorResponse` (not `ErrorDetails`)?

**Comment by timotheeguerin** [comment]
yes my bad, not sure why I endedup using ErrorDetails in my repro
