### ISSUE TITLE
"format" is dropped for password string

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3637]
**Describe the issue**
A schema sample for password is as below. Currently, m4 simply drops the format and hands it as a normal string
```
{
“db-passwd”: {
          “type”: “string”,
          “format”: “password”
}
}
```
**Potential solution**
Add a password type or carry across the format info

**Comment by timotheeguerin** [comment]
This doesn't seem to be an issue anymore, the passwrod get marked as `credential`
