### ISSUE TITLE
Distinct schemas for the same host parameter

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest#3640]
Getting distinct schema references for endpoint parameter in Form recognizer, it is being referenced with distinct schemas up to 7 times. 

Form recognizer for reference: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/FormRecognizer

Used the autorest command with tag: release_2_0

**Comment by timotheeguerin** [comment]
Hey @catalinaperalta are you still having problem with this? If so do you have more details on what schemas are duplicated
