### ISSUE TITLE
Swagger comments with \U, \N have errors generating

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3641]
**Describe the issue**
@richardpineo opened an [issue](https://github.com/Azure/autorest.python/issues/84) against old autorest about errors with \U or \N in the docstrings. It appears now that modelerfour throws an error . I think the behavior we have now is valid (throwing with these tokens), but wanted to open this up for discussion to hear what you think @daviwil @richardpineo

![image](https://user-images.githubusercontent.com/43154838/92768562-1d2e2a80-f366-11ea-8d02-093ff00c7f7e.png)
** REQUIRED ** 
**ModelerFour** version:4.15.416
**AutoRest-core** version: 3.0.6306
**CommandLine** To repro thius, i just added \U to a description in the body complex swagger
OpenAPI/Swagger file:

**Comment by richardpineo** [comment]
No particular thoughts here. I don't work on this portion of our project much any more and so I haven't run into this issue since I filed that bug a year and a half ago. I believe we worked around it by cleansing the source at some point to remove \U, \N from our source.

**Comment by timotheeguerin** [comment]
This is definitely not valid json/yaml. editor.swagger.io and vscode both fail on this
![image](https://user-images.githubusercontent.com/1031227/113331809-3b914e80-92d5-11eb-988b-36045fd61c0d.png)
I have seen some parser that will act as if this was meant to be written `"Value\\Units"` but I don't think this is worth adding this.
