### ISSUE TITLE
Add a default list of headers ignore

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3643]
There is some headers are known to be handled correctly by track2 SDK by default and we don't want to appear in method signature and generated code, that we might wish to document in Swagger/RestAPI doc.

This issue about when we recognized those headers, they shall not be generated in any `headers` of M4. This allows correct documentation for customers of RestAPI and external consumers of Swaggers, while not bloating our SDKs with things that the pipeline is handling automatically.

We shall implement that with  `--ignore-spec-headers` (happy to discuss the name), where the default value should be `traceparent,tracestate` by default ([see for details](https://www.w3.org/TR/trace-context/)). This allows for further customization if necessary.

We might add more default later, like request-id, etc. will discuss when necessary.

FYI @johanste

**Comment by johanste** [comment]
x-ms-client-request-id, if-match, if-non-match, if-modified-since, if-unmodified-since, if-range are also things that should be handled in special ways. As is repeatibility-request-id and friends.
