### ISSUE TITLE
Bad type name when generating resources.json

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#3648]
**Describe the issue**
When generating resources.json we get a really ugly type name.

`ComponentsSgqdofSchemasIDentityPropertiesUserassignedidentitiesAdditionalproperties`

This is used as the dictionary value for userAssignedIdentities.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-01/resources.json#L3317

Seems like the name could be greatly improved.

** REQUIRED ** 
**ModelerFour** version: 4.13.351
**AutoRest-core** version: 3.0.6282
**CommandLine** :
autorest --use=\git\Azure\autorest.go --license-header=MICROSOFT_MIT_NO_VERSION --input-file=C:\git\Azure\azure-rest-api-specs\specification\resources\resource-manager\Microsoft.Resources\stable\2019-05-10\resources.json --output-folder=\git\Azure\autorest.go\test\temp

OpenAPI/Swagger file:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-01/resources.json

**Comment by lmazuel** [comment]
Let's be explicit in Swagger like @daviwil says
