### ISSUE TITLE
M4 produces duplicated model errors where it shouldn't 

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3655]
https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/redis/resource-manager/readme.md 
and
https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/storage/resource-manager/readme.md

Are affected.

Worked fine in 4.13.356 and adding the switch doesn't change the generated code.

**Comment by timotheeguerin** [comment]
I have looked at this issue and I think this actually is an issue with the OAI2 -> OAI3 converted not modeler. This is the change that caused the issue https://github.com/Azure/autorest.modelerfour/pull/280/files. The change included `x-ms-client-name` in the duplicate name checks.


Here is a repro with minimal fields:

**OAI2:**
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Test",
    "description": "test",
    "version": "test-0.1"
  },
  "host": "test.com",
  "paths": {},
  "definitions": {
    "ScheduleEntries": {
      "properties": {
        "scheduleEntries": {
          "x-ms-client-name": "ScheduleEntries",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**OAI3 Converted**
```
{
  "openapi": "3.0.0",
  "info": {
   "title": "Test",
   "description": "test",
   "version": "test-0.1"
  },
  "paths": {},
  "components": {
   "schemas": {
    "ScheduleEntries": {
     "properties": {
      "scheduleEntries": {
       "$ref": "#/components/schemas/ScheduleEntries-scheduleEntries"
      }
     }
    },
    "ScheduleEntries-scheduleEntries": {
     "x-ms-client-name": "ScheduleEntries",
     "type": "array",
     "items": {
      "$ref": "#/components/schemas/ScheduleEntries-scheduleEntriesItem"
     }
    },
    "ScheduleEntries-scheduleEntriesItem": {
     "type": "string"
    }
   }
  },
  "servers": []
 }
```

You can see the OAI3 version now has 2 components that techinically have the same name:
- `ScheduleEntries`
- `ScheduleEntries-scheduleEntries` with `"x-ms-client-name": "ScheduleEntries"`
