### ISSUE TITLE
Should Prechecker delete "empty" polymorphic types?

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest#3659]
PR Azure/autorest.modelerfour#263 adds a new Prechecker phase which performs some early checks and fixes to the OpenAPI 3 document that comes from an earlier phase of the pipeline.  One of these fixes is `fixUpSchemasThatUseAllOfInsteadOfJustRef` which deletes any schema which matches the following checks:

- Typed as `object`
- Has no properties or additionalProperties
- Is `allOf` a single `$ref` to another schema

In practice such a schema looks like `cookiecuttershark` from `body-complex.json`:

```
    "cookiecuttershark": {
      "type":  "object",
      "allOf": [
        {
          "$ref": "#/definitions/shark"
        }
      ]
    },
```

In practice this schema is just a new name for the existing `shark` schema.  @fearthecowboy gives some [context](https://github.com/Azure/autorest.modelerfour/pull/274#issuecomment-623713245) in PR Azure/autorest.modelerfour#274 about why this fixup was added in PR Azure/autorest.modelerfour#263.

Before turning this back on, I think we need to figure out the following:

- Which Azure specs in `azure-rest-api-specs` repo are using this pattern?
- How can we migrate these specs away from this pattern?
- How strict should we be on this pattern, i.e. should we just warn or both warn and delete the schema?

**Comment by timotheeguerin** [comment]
This is now enabled behind a flag `remove-empty-child-schemas`
