### ISSUE TITLE
Should property re-definition be an error?

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3663]
https://github.com/Azure/azure-rest-api-specs/blob/48a0185c914511a4e963f7e334f97bede2886d9b/specification/network/resource-manager/Microsoft.Network/stable/2019-12-01/virtualWan.json#L4225

`VpnServerConfiguration` inherits from `Resource` but redefines `name` property.

Should this be an error?

I think it's done here to update the description? Can we support that in some other way?

**Comment by timotheeguerin** [comment]
A warning is logged and the property is removed now
