### ISSUE TITLE
ComputerVision: Multipart error

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3666]
Not sure if it's Swagger or M4, creating it here for now

C:\Users\lmazuel\AppData\Roaming\npm\autorest.CMD C:\Users\lmazuel\Git\azure-rest-api-specs\specification\cognitiveservices\data-plane\ComputerVision\readme.md --keep-version-file --multiapi --no-async --python --python-mode=update --python-sdks-folder=C:\Users\lmazuel\Git\azure-sdk-for-python\TEST --use=@autorest/python@5.0.0-dev.20200326.1
AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@autorest/python' (5.0.0-dev.20200326.1->5.0.0-dev.20200326.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.276->4.12.276)
FATAL: Error: Requests with 'multipart/formdata' can not be combined in a single operation with other media types application/octet-stream,multipart/form-data
  Error: Plugin modelerfour reported failure.

**Comment by timotheeguerin** [comment]
Doesn't seem to be an issue with latest version
