### ISSUE TITLE
Optional parameter with a constant schema should be in methodSignature

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3674]
Because even if the value is constant, the parameter is not, so this is still an interesting parameter, since I can still decide to not provide it.

Example:
https://github.com/Azure/azure-rest-api-specs/blob/719827a2f6560db22a873828100b8aff1317c483/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L394-L405

**Comment by timotheeguerin** [comment]
Believe this was resolve recently
