### ISSUE TITLE
Fully support significant null values

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#3687]
In AutoRest v2 we've had terrible support for `null` values.  Significant nulls were not really handled at all. 

I propose that we rectify this in V3/ModelerFour , and make `null` values actually fully supported. 

This does create some interesting issues for some languages, as there needs to be a difference between 'not set' and `null`

**Comment by lmazuel** [comment]
I'm closing this issue that is mostly to an epic level, and will re-create focused issues when we see the need in practice
