### ISSUE TITLE
Deduplicate headers that are the 'same'

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest#3689]
It seems that 'same' headers are not deduplicated. So, for AppConfiguration, they have a `Sync-Token` header. But, every time it exists in a response, it is using a new schema. So, it is declaring this schema like many, many times. It is just a string schema, no description, same name. So, it should just be a single schema.

**Comment by lmazuel** [comment]
Might be ugly, by pragramatically causes no problem :)
