### ISSUE TITLE
Unable to generate empty class for no-property schema

### ISSUE THREAD

**Issue by mjohnst** [Azure/autorest#3693]
Hello,

I have a schema in my OpenApi JSON that only contains a `description` and a `type` - multiple schemas inherit from it
e.g.
```
"Foo": {
        "type": "object",
        "description": "Foo description."
},
"Bar": {
        "type": "object",
        "description": "Bar description."
        "allOf": [
          {
            "$ref": "#/components/schemas/Foo"
          }
        ],
        "properties": { ... }
},
"Fizz": {
        "type": "object",
        "description": "Fizz description."
        "allOf": [
          {
            "$ref": "#/components/schemas/Foo"
          }
        ],
        "properties": { ... }
}
``` 

When I run my autorest generation, I get this error:
`autorest --v3 --verbose --version=3.0.6274  .\config.yaml`
`FATAL: The schema's 'Bar' ancestors should have at lease one property`

Adding `--generate-empty-classes` should fix this issue, but then I get this error:

```
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SwaggerModeler.cs:line 128
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```

Here are the relevant bits of version information on my above runs:
```
AutoRest code generation utility [cli version: 3.0.6247; node: v12.16.1, max-memory: 2048 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\mjohnst\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.91)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.88->2.1.95)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25->2.1.128)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.62)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
```

If I try using a more recent version of core in combination with `--generate-empty-classes`
e.g. `autorest --v3 --verbose --version=3.0.6302 --generate-empty-classes .\config.yaml` (and higher versions)

I get this error instead:
`Error: Cannot resolve pipeline stage 'openapi-document/identity'.`

I've played around with a few preview versions, but get the "cannot resolve pipeline stage" error.

Is there anything I can do to get this working with the empty schemas/classes or debug the issue further?
Is there a known fix for these issues in a particular version or preview version?

A workaround would be for us to exclude the empty schemas, but I am weary this will limit some functionality of the generated libraries talking with our API.

**Comment by timotheeguerin** [comment]
Could you try using the flag `--use:@autorest/modelerfour@4.15.440`. I don't seem to be able to repro this issue with the latest.
