### ISSUE TITLE
The autorest validation error message is not very correct for DeleteOperationResponses/R4011/ARMViolation

### ISSUE THREAD

**Issue by aim-for-better** [Azure/autorest#3694]
For example, when I run 
```
autorest --validation --azure-validator --openapi-type=arm --use=@microsoft.azure/classic-openapi-validator@1.1.4 --use=@microsoft.azure/openapi-validator@1.5.0
```

There is an error as bellow:
![image](https://user-images.githubusercontent.com/12733681/98936879-9261db80-2520-11eb-986d-4b447a868ebc.png)

It shows **without** 200 or 204, I am very confused because our operation has 200 response. 

When I find definition of [DeleteOperationResponses/R4011/ARMViolation](https://github.com/Azure/azure-rest-api-specs/blob/fbe9266483321792bcb4b3cce511b17cf685a123/documentation/openapi-authoring-automated-guidelines.md#r4011-deleteoperationresponses)
The description is as bellow:
![image](https://user-images.githubusercontent.com/12733681/98937334-3481c380-2521-11eb-8201-012c240e4dbc.png)

It is must have 200 and 204.  

So the autorest  error message is not very correct, we need to change or to and.

**Comment by timotheeguerin** [comment]
This seems like an issue with the openapi-validator more than autorest itself https://github.com/Azure/azure-openapi-validator
