### ISSUE TITLE
Make autorest generated files compatible with Xamarin

### ISSUE THREAD

**Issue by DanMirandaITx** [Azure/autorest#370]
It would be nice to enable suport for profile "portable-net403+win+wpa81+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10" in order to use generated files in Xamarin.

**Comment by stankovski** [comment]
We do support Xamarin via portable-net45+win8+wpa81 (profile 111) and netcore which are based on net45. However we do not currently have plans to provide backwards compatibility for net403.
