### ISSUE TITLE
Description in responses in Code Model file is missing

### ISSUE THREAD

**Issue by sacheu** [Azure/autorest#3704]
When I generate code model from a swagger file using this command:

`autorest --v3 --input-file=communicationserviceschat.json --inspector --inspector.output-folder=./inspector --inspector.clear-output-folder --use:@autorest/modelerfour@4.15.396`

I see the description of responses are blank.
![image](https://user-images.githubusercontent.com/8701731/99857279-b7b5a180-2b3f-11eb-9a06-960458999fd0.png)

From the swagger file, I see
![image](https://user-images.githubusercontent.com/8701731/99857239-a40a3b00-2b3f-11eb-938e-b676f3596021.png)

Here is the swagger file where i see the issue.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/Microsoft.CommunicationServicesChat/preview/2020-09-21-preview2/communicationserviceschat.json

**Comment by daviwil** [comment]
This fix is available in `@autorest/modelerfour@4.15.438`
