### ISSUE TITLE
Autorest failure with Node 14.15.0

### ISSUE THREAD

**Issue by josh-oakes** [Azure/autorest#3706]
I'm seeing the following error in my build pipeline in Azure Devops...

```

========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/670d10df-438b-4166-90e4-649f59e656dd.sh
AutoRest code generation utility [cli version: 3.0.6247; node: v14.15.0, max-memory: 2048 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.62)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
  TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
```
OS: ubuntu-latest image
AutoRest CLI: 3.0.6247
node: 14.15.0

I think the issue is some weird combination between ubuntu and node as I'm not able to replicate this on my local windows machine. But my actual question how does Autorest choose the version of node to run against? Can we specify the node version on the command line? In my pipeline I am overriding the node version back to 12.19.0 (this version worked as of a few weeks ago), but autorest is still running against 14.15.0 (node -v is showing 12.19.0 in my pipeline)

This very well could be an azure pipelines issue, but I thought I would start here first for any suggestions.

**Comment by timotheeguerin** [comment]
How are you using autorest?

If you installed autorest using `npm install -g autorest` it will use the version of node available in the path. With Azure Devops you can use the Use the [NodeTool task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) to install a specific version of node.

However it should be working just fine on node 14. Could you share the command line you are using?

**Comment by josh-oakes** [comment]
My apologies, didn't realize I left this out initially...

Here is the command:

`sudo autorest --input-file=https://sd.kcftech.com/swagger/internal/swagger.json --python --override-client-name=SmartDiagnosticsApi --output-folder=./python --namespace=smartdiagnostics_sdk --package-name=kcf_sd_sdk`

I was using the NodeTool Task initially trying to set a specific version, but I don't think the path was being set appropriately as autorest wasn't using the correct version. I switched the NodeTool task to `12.x` (instead of a specific version) and its working fine again.

**Comment by timotheeguerin** [comment]
Don't seem to encounter this issue with node 14. Might have been an issue at the time. I'll close this, please reopen if you reencounter the problem.

**Comment by nagarakesh4** [comment]
same issue for me, works fine with the csharp example, however python is throwing the same error

doesn't work with python:
`autorest --input-file=petstore.yaml --python --output-folder=./CSharp_P --namespace=PetStore`
error:
`The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView`

works fine with csharp:
`autorest --input-file=petstore.yaml --csharp --output-folder=./CSharp_PetStore --namespace=PetStore`

installed autorest using
> npm install -g autorest

Python 3.8.3

node version: 14.15.0

while fetching autorest version:
```
>>  autorest --version
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (/usr/local/lib/node_modules/autorest/dist/src/autorest-as-a-service.js:267:23)
    at async main (/usr/local/lib/node_modules/autorest/dist/src/app.js:106:31)
```

**Comment by timotheeguerin** [comment]
@nagarakesh4 Could you share the openapi file you are using? Also that 2nd error, is it happening consitently?

**Comment by nagarakesh4** [comment]
if you meant the input file, then i just got the petstore.yaml from git repo 

`https://github.com/Azure/autorest/blob/master/docs/examples/generating-a-client.md`

`curl -O https://raw.githubusercontent.com/Azure/autorest/master/Samples/openapi-v2/1b-code-generation-multilang/petstore.yaml`

**Comment by timotheeguerin** [comment]
Yeah sorry `--version` is not showing the version it is used to pick which version of autorest core to use if not the default

**Comment by timotheeguerin** [comment]
is the first error still hapening after you run `autorest --reset`

**Comment by nagarakesh4** [comment]
i did autorest --reset, this time i got python no module found error

> autorest --input-file=petstore.yaml --python --output-folder=./CSharp_P --namespace=PetStore

```
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      '/Users/USERNAME/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist' (3.0.6349)
   Loading AutoRest extension '@autorest/python' (latest->5.5.0)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)
Traceback (most recent call last):
  File "/Users/USERNAME/opt/miniconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/USERNAME/opt/miniconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/USERNAME/.autorest/@autorest_python@5.5.0/node_modules/@autorest/python/autorest/__init__.py", line 10, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Executing: venv/bin/python3 -m autorest.jsonrpc.server
Command '['venv/bin/python3', '-m', 'autorest.jsonrpc.server']' returned non-zero exit status 1.
Process() cancelled due to failure
```

**Comment by timotheeguerin** [comment]
I think that issue is due to having some different version of python available where it seems like it does part of the job with different python version(My guess). I would open an issue on the autorest.python repo for this, they might have more insight on it.

**Comment by vbrbms** [comment]
I am also getting the same error. I am using NodeJs 14.x with npm 6.x and autorest v 2.0.4413 and python 3.0.56
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer
any suggestions?

**Comment by timotheeguerin** [comment]
Can you double check this is not happening with the latest version of `2.0.x`: (`2.0.4421`). Think this might be due to a change on node 14 when writting file not accepting null which was fixed in v2
