### ISSUE TITLE
Collision detected inserting into object

### ISSUE THREAD

**Issue by pecjag** [Azure/autorest#3707]
Receiving an error when attempting to run autorest against the attached swagger file:
[swagger-4.0.0-dist.json.zip](https://github.com/Azure/autorest/files/5612632/swagger-4.0.0-dist.json.zip)

This is the error I'm receiving:
`
C:\Users\Peter>autorest --v3 --powershell --input-file:c:\temp\swagger-4.0.0-dist.json --debug
AutoRest code generation utility [cli version: 3.0.6247; node: v14.15.1, max-memory: 4096 gb](C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\Peter\.autorest\@autorest_core@3.0.6320
   Loading AutoRest core      'C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.401)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
DEBUG [1.78 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.78 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.78 s]: pipeline-emitter - START inputs = 0
DEBUG [1.83 s]: configuration-emitter - START inputs = 0
DEBUG [1.83 s]: pipeline-emitter - END [0.05 s]
DEBUG [1.83 s]: configuration-emitter - END [0.05 s]
DEBUG [3.09 s]: openapi-document/loader-openapi - END [1.31 s]
DEBUG [3.1 s]: openapi-document/individual/transform - SKIPPING
DEBUG [3.1 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [3.14 s]: openapi-document/individual/identity - SKIPPING
DEBUG [3.85 s]: swagger-document/loader-swagger - END [2.07 s]
DEBUG [3.85 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [5.96 s]: swagger-document/individual/transform - END [2.1 s]
DEBUG [5.96 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
DEBUG [6.28 s]: swagger-document/individual/schema-validator-swagger - END [0.31 s]
DEBUG [6.28 s]: swagger-document/identity - START inputs = 1
DEBUG [6.28 s]: swagger-document/individual/identity - START inputs = 1
DEBUG [6.28 s]: swagger-document/identity - END [0 s]
DEBUG [6.28 s]: swagger-document/individual/identity - END [0 s]
DEBUG [6.29 s]: openapi-document/openapi-document-converter - START inputs = 1
DEBUG [6.78 s]: openapi-document/openapi-document-converter - END [0.49 s]
DEBUG [6.78 s]: openapi-document/transform - START inputs = 1
DEBUG [6.88 s]: openapi-document/transform - END [0.09 s]
DEBUG [6.88 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [6.96 s]: openapi-document/allof-cleaner - END [0.07 s]
DEBUG [6.96 s]: openapi-document/tree-shaker - START inputs = 1
C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: enterprise_update_enterprise / Error: Collision detected inserting into object: enterprise_update_enterprise
    at Object.set (/node_modules/@azure-tools/datastore/dist/graph-builder.js:45:23)
    at OAI3Shaker.newObject (/node_modules/@azure-tools/datastore/dist/processor.js:40:24)
    at OAI3Shaker.dereference (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:496:30)
    at OAI3Shaker.dereferenceItems (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:395:18)
    at OAI3Shaker.visitComponents (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:402:26)
    at OAI3Shaker.process (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:98:26)
    at OAI3Shaker.runProcess (/node_modules/@azure-tools/datastore/dist/processor.js:76:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async OAI3Shaker.getOutput (/node_modules/@azure-tools/datastore/dist/processor.js:14:9)
    at async shakeTree (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:549:64)
    at async ScheduleNode (C:\Users\Peter\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Collision detected inserting into object: enterprise_update_enterprise
[7.68 s] Shutting Down.
[7.68 s] Exiting.

`

I have reviewed the swagger file and it doesn't appear to have duplication.

I am running:
Windows 10
 .Net Core : 5.0.100
Autorest: 3.0.6247
Node: v14.15.1

**Comment by timotheeguerin** [comment]
Issue here is that your body title `enterprise_update_enterprise` and it tries to extract that as a definition of that name. However there is already one with that name hence the conflict.

There is here at the very least a lack of communication on the issue from the error that should be looked at. Will see if there is a good way to resolveg the conflict

**Comment by pecjag** [comment]
Thanks very much for looking into it.
Please excuse my ignorance, but would you say this is "invalid" in the swagger file (ie. not valid to use the title with the same name)  Or should this be handled within autorest?

**Comment by timotheeguerin** [comment]
I don't think it is an invalid swagger file itself. OpenAPI describe services in a flexible manner which can then be an issue for a generated SDK. As much as autorest should probably not be crashing in this case having it autogenerate models name due to conflict will not result in an optimal SDK.
