### ISSUE TITLE
Unable to locate the generated files

### ISSUE THREAD

**Issue by gkarnik05** [Azure/autorest#3711]
I'm trying to generate client with the below command. I'm running the command in PowerShell administrator mode. Even though the debug shows that the writing is complete, I'm unable to locate the files. Am I missing something?

`autorest --input-file=".\adventureworks2017-openapi.json" --namespace="AdventureWorks2017.RestApi" --debug --output-folder="c:\users\gpkar\source\repos\AdventureWorks.Blazor\autorest"`

<img width="865" alt="autorest-debug" src="https://user-images.githubusercontent.com/37911922/100691986-e3425280-33af-11eb-96c6-fdf732a4629b.png">

I do see some folders being created in the Temp folder but they are empty.
![image](https://user-images.githubusercontent.com/37911922/101236312-460c5480-36f6-11eb-94c8-da546d9cb642.png)

**Comment by sagoo33** [comment]
I had the same issue, after not running the command in a long time.
I found I needed to specify the generator as a parameter eg:

autorest --input-file=".\adventureworks2017-openapi.json" --namespace="AdventureWorks2017.RestApi" --debug --output-folder="c:\users\gpkar\source\repos\AdventureWorks.Blazor\autorest" **--v3 --csharp**

**Comment by daviwil** [comment]
@sagoo33 Is correct, you need to specify the language you want to generate for as a parameter.  Closing this for now, let me know if you still continue to have issues after passing the desired parameter (`--csharp`, `--powershell`, etc).
