### ISSUE TITLE
credential flag discussion

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3718]
discussed with @lmazuel, starting off discussion by saying: we should move to what Java has. i.e., one flag `--credential-types`, where you can specify a list of `TokenCredential`, `AzureKeyCredential`, or `None`. Default to `TokenCredential`, since all mgmt plane code uses `TokenCredential`, and as far as we know, all data plane libraries use credentials as well (even if they don't, we can talk to people since data plane is our team).

Java's credential types flag also accepts multiple values, and I think this is something all language should have as well, is this doable?

**Comment by iscai-msft** [comment]
python: currently, by default we don't generate any credentials. If you want to generate with a credential, we make users set flag `--add-credential`. By default, from this we generate a `TokenCredential`.

If you want to generate with an `AzureKeyCredential`, you also have to specify specify this through a credential default policy. You have to set `credential-default-policy-type=AzureKeyCredentialPolicy` (by default, this flag's value is `BearerTokenCredentialPolicy`). We also have a separate flag `--credential-key-header-name` for azure key credential, which defaults to `api-key`. You use this flag to specify the name of the header you want your credential to go into.

Here is a [sample readme](https://github.com/Azure/autorest.python/blob/autorestv3/docs/samples/specification/azure_key_credential/readme.md) I have for this scenario.

Final note: python likes the java approach more and wants to follow their design more

**Comment by tjprescott** [comment]
We don't have any flags in Swift for this. Our initializers accept anything that conforms to the Credential protocol, whether supplied by AzureCore or the client SDK. It hasn't (yet) come up that we need to customize this.

**Comment by srnagar** [comment]
For Java, as @iscai-msft mentioned, we use `--credential-types` flag that accepts comma-separated values - `AzureKeyCredential` and `TokenCredential`.

 If `TokenCredential` is included in the values, we look at an additional flag `--credential-scopes` that again accepts a comma-separated list of scopes. If no scopes are set then `<endpoint>/.default` scope will be used.

**Comment by ShivangiReja** [comment]
We should consider adding support for https://swagger.io/docs/specification/authentication/ properties in Autorest, so that autorest/modelerfour can pass the information to all the languages about what type of credentials we should generate.

CC: @daviwil @timotheeguerin @lmazuel

**Comment by timotheeguerin** [comment]
So the security settings of openapi are very flexible and here we are talking about about allowing a fixed set of authentication.
Now we could definitly make use of the security system using something like where we still manage the security definitions for the user(It is this hard coded list) and then they can reference the security this way
```yaml
security:
  - AzureKeyCredential: []
  - TokenCredential:
      - https://myservice.azure.com/.default
```

**Comment by timotheeguerin** [comment]
A proposition on for the spec of this change https://gist.github.com/timotheeguerin/3103e7dfa1be80d96bdcf392e76d5632

**Comment by chamons** [comment]
Test project in autorest.csharp - https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/PublicClientCtor

**Comment by timotheeguerin** [comment]
I have a PR implementing the proposal above #4018. Could generators team give it a try and see if that infromation is good to generate the credentials from the m4 model and without using any cli/config flags
