### ISSUE TITLE
credential scopes discussion

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3719]
All languages should be able to support a list of credential scopes (with flag `--credential-scopes`), so users won't have to pass credential scopes themselves. Agree with @lmazuel that in ARM mode, we should default the credential scope to `https://management.azure.com/.default`, since that's always the case for ARM mode.

**Comment by lmazuel** [comment]
@daviwil @timotheeguerin We should do that in autorest.core: if azure-arm and not credential-scopes, then credentials-scopes: https://management.azure.com/.default

**Comment by timotheeguerin** [comment]
Trying to understand, right now this flag is just being handled by the language generators themself? What is expected to happen here is that autorest core will inject `--credential-scopes=https://management.azure.com/.default` if the `--azure-arm` flag is being passed?

**Comment by iscai-msft** [comment]
yep! currently some languages are doing this themselves, go into it a little bit in the `credential-scopes` section of [flag docs](https://github.com/Azure/autorest/blob/new_docs/docs/generate/flags.md). Since there's this different behavoir and we want unified, would be nice for autorest core to handle it.

side note: if users input `--azure-arm --credential-scopes=myscopes`, we should respect their inputted credential scopes and not override to `https://management.azure.com/.default`.

**Comment by lmazuel** [comment]
+42 for everything @iscai-msft said ;)

Taking an extra step back, we have several rules right now to change autorest configuration is `azure-arm: true`, we should probably make sure we centralize them in one place.

**Comment by jianghaolu** [comment]
There are a couple of issues that are still unsolved:

1. What's the default behavior if `credential-scopes` isn't provided on cmd or in readme? Is there a default we fall back to?
2. What if the `credential-scopes` is a dynamic value dependent on the endpoint (like for storage blob, the scope would be `https://{account}.blob.windows.net/.default`.
3. How does our SDK adapt to other clouds or Azure Stack if we hard code a `credential-scopes` in our generated code?

Currently the Java's approach (advertised as a Java-only feature for now, but should be consistent with other languages eventually) is:
1. We use the host of the base URL + "/.default" as the default `credential-scopes` if none provided. This works well for `azure-arm` ("https://management.azure.com/.default"), storage blob ("https://mystorageaccount.blob.windows.net/.default"), and other clouds ("https://management.chinacloudapi.cn/.default").
2. If an SDK Developer passes `credential-scopes` during generation we honor that - but users won't be able to deploy the same code to other clouds and expect it to work.

A catch-all solution for `credential-scopes` would be an SDK-developer provided `Func<String, String>()` that's applied on the base URL. The challenge would be how to pass such a func through String to AutoRest. It's even more challenging if we want a standard format across languages. But I'm not sure if that would necessary.

**Comment by iscai-msft** [comment]
@jianghaolu didn't think about having a parameterized credential scope. I like the idea of adding `/.default` to the end of credential scopes and warning users this is what we're doing. It seems like a good default ;)
