### ISSUE TITLE
Generated C# code should avoid using JsonConvert

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#372]
See related issue in the pre-AutoRest Search SDK: https://github.com/Azure/azure-sdk-for-net/issues/1438

`JsonConvert` has a static `DefaultSettings` property. Unfortunately, even if you pass your own `JsonSerializerSettings` to `SerializeObject`/`DeserializeObject`, they do not completely replace the default settings. Some settings like `JsonConverters` are merged rather than replaced.

What this means is that code using an AutoRest-generated client library might modify `JsonConvert.DefaultSettings` in ways that disrupt the serialization/deserialization of payloads by the client library. Instead, the generated code should call `JsonSerializer` directly. It is simple to write some wrappers that mimic `JsonConvert` (see this PR for an example: https://github.com/Azure/azure-sdk-for-net/pull/1451).

**Comment by stankovski** [comment]
Tracking via https://www.pivotaltracker.com/story/show/107069918

**Comment by brjohnstmsft** [comment]
I'm going to try to fix this.
