### ISSUE TITLE
Error: No 'title' in provided OpenAPI definition(s) - but there is

### ISSUE THREAD

**Issue by forteddyt** [Azure/autorest#3729]
I'm working on a [swagger spec for the azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/pull/11955/checks?check_run_id=1534255363) repo and am running into this issue both in the PR pipeline and locally.

The local command I am running is `autorest --reset && autorest --validation --azure-validator --message-format=json --openapi-type=arm --use=@microsoft.azure/classic-openapi-validator@1.1.5 --use=@microsoft.azure/openapi-validator@1.6.0 --tag=package-2020-12-01-preview readme.md`

The two input files in files are `machineLearningServices.json` and `mfe.json`

From `machineLearningServices.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Azure Machine Learning Workspaces",
    "description": "These APIs allow end users to operate on Azure Machine Learning Workspace resources.",
    "version": "2020-12-01-preview"
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
...
}
```
From `mfe.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Azure Machine Learning Workspaces",
    "description": "These APIs allow end users to operate on MFE Workspace resources.",
    "version": "2020-12-01-preview"
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
...
}
```

There is a 'title' provided in both OpenApi definitions, contrary to what the error is suggesting. Am I missing something?

**Comment by daviwil** [comment]
When you use multiple files as inputs, AutoRest doesn't know which file's title it should use so it expects that you will specify `--title` either via the CLI or in a Markdown configuration section.  The latter option is the practice we use for the azure-rest-api-specs repo:

https://github.com/Azure/azure-rest-api-specs/search?l=Markdown&q=title

**Comment by forteddyt** [comment]
Thanks for the quick response! I added an explicit title in the markdown configuration and executed the command mentioned above locally, but that did not resolve the error. More specifically, the markdown now looks
```md
``` yaml $(tag) == 'package-2020-12-01-preview'
title:
  Azure Machine Learning Workspaces
input-file:
- Microsoft.MachineLearningServices/preview/2020-12-01-preview/machineLearningServices.json
- Microsoft.MachineLearningServices/preview/2020-12-01-preview/mfe.json
```

**Comment by forteddyt** [comment]
It looks like the issue was that I removed the following from package-2020-08-01 in the readme
```yaml
``` yaml
openapi-type: arm
tag: package-2020-08-01
```

adding that back (at line 27, in my case) resolved my issue

**Comment by daviwil** [comment]
Great, glad to hear you were able to get it resolved!
