### ISSUE TITLE
Swagger basepath ignored

### ISSUE THREAD

**Issue by suddenelfilio** [Azure/autorest#373]
When using a swagger basepath 
```son
{
    "swagger": "2.0",
    "info": {
        "title": "Zoho Invoice API",
        "description": "Zoho invoice api",
        "version": "3.0.0"
    },
    "host": "invoice.zoho.com",
    "schemes": [
        "https"
    ],
    "basePath": "/api/v3",
...
```

it gets misformed when the uri is constructed

for example the BaseUri = https://invoice.zoho.com/api/v3
and the code does: var url = new Uri(this.BaseUri, "/contacts").ToString();

the url will become https://invoice.zoho.com/contacts instead of https://invoice.zoho.com/api/v3/contacts

**Comment by devigned** [comment]
We'll fix this, but .net looks at your uri and expect a trailing slash. If there is no trailing slash, it just thinks it's a fragment rather than a path segment. This is quite frustrating... 

If you would like this to work for you today, make base path end with a slash - BaseUri = https://invoice.zoho.com/api/v3/.

**Comment by tom3m** [comment]
We got in to this as well.
When we create client we pass base uri containing host + some postfix. Like www.mysite.com/api/
In the result Uri class class cut's postfix when combining final Uri.

Any idea when this could be fixed?

**Comment by devigned** [comment]
https://github.com/Azure/autorest/pull/387 merged in dev and can be used via the Nightly builds in the [MyGet feed](https://www.myget.org/gallery/autorest).

**Comment by suddenelfilio** [comment]
Excellent! thanks! any idea as to when this will be released?
