### ISSUE TITLE
ERROR: Syntax error: No mapping value found. swagger.yaml:1:1

### ISSUE THREAD

**Issue by bugproof** [Azure/autorest#3733]
1st line: `openapi: 3.0.0`

invocation: `autorest --v3 --csharp --input-file=swagger.yaml`

**Comment by timotheeguerin** [comment]
This looks like there is something invalid in the yaml. I cannot reproduce with a file only having
```yaml
openapi: 3.0.0
```
I think from trying to reproducing the error, the line `1:1` is not accurate, seems to always be returning that.

**Comment by bugproof** [comment]
> This looks like there is something invalid in the yaml. I cannot reproduce with a file only having
> 
> ```yaml
> openapi: 3.0.0
> ```
> 
> I think from trying to reproducing the error, the line `1:1` is not accurate, seems to always be returning that.

Here's the full yaml http://developer.allegro.pl/swagger.yaml

**Comment by timotheeguerin** [comment]
So looking at it the issue seems to be that you have some property which have no value. For example line 7277, `path:` has not value. ![image](https://user-images.githubusercontent.com/1031227/102091865-3c5cae00-3dd4-11eb-94b9-e8d1021e84cc.png)

I am not sure why though it is not showing the correct lines for the errors, as it should be working. So I'll look into that.

**Comment by timotheeguerin** [comment]
@bugproof I have a fix for showing the right error line. In the meantime this is the output of running it on your yaml
```
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7324:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7326:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7640:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7642:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7761:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7763:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7904:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7906:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7324:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7326:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7640:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7642:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7761:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7763:26
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7904:29
ERROR: Syntax error: No mapping value found.
    - http://developer.allegro.pl/swagger.yaml:7906:26
```

**Comment by RobBowman** [comment]
@timotheeguerin I'm hitting the same problem when running against the attached yaml - can you see what's wrong?

AutoRest code generation utility [cli version: 3.2.3; node: v16.1.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\rob\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
   Loading AutoRest extension '@autorest/azure-functions-csharp' (latest->0.2.0-preview-dev.321054549)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
ERROR: Syntax error: No mapping value found.
    - file:///c:/RobDev/SMS%20Router.openapi.yaml:1:1
[SmsRoutingOpenApi3.yaml.txt](https://github.com/Azure/autorest/files/6748441/SmsRoutingOpenApi3.yaml.txt)

**Comment by RobBowman** [comment]
@timotheeguerin I have found the cause of the failure - line 89 description for the /hello-world url was missing a value. Not sure why autorest reports an error in position 1:1 though?
