### ISSUE TITLE
Target DOTNET instead of DNXCore50

### ISSUE THREAD

**Issue by npnelson** [Azure/autorest#374]
I'm still trying to get my head around all the ramifications of ASPNET5, CoreCLR, UWP, etc, but I'm pretty sure that you want to replace all the DNXCore50 references in #340 with DOTNET references.  Oren Novotny has a decent summary here (especially in the "Call to Action" section) 

https://oren.codes/2015/07/29/targeting-net-core/

**Comment by stankovski** [comment]
@npnelson thanks for the heads up
