### ISSUE TITLE
References $ref to the local files are not being processed

### ISSUE THREAD

**Issue by iorlas** [Azure/autorest#3752]
**Describe the bug**
We've been trying to get an advantage or $ref linking for the paths to split almost 10k-lines sized spec. The issue is, even on a simple spec file, we are unable to produce the client with autorest for the **TypeScript**. The input file was successfully validated with IBM OpenAPI Validator, so there should be 0 issues from the spec itself.

With the file provided below, autorest successfully generates a client that has the route missing, and it does not even produce an error! It feels like it skips all the external $ref definitions.

Initially, we faced the same issue with schemas, but we have found it is the issue with paths as well. So we believe there is something reallly wrong here.

_Ignore the workaround path, it is a workaround for #3751_

**Expected behavior**
TypeScript client should be generated, it should have 2 routes generated: one is for the inline workaround, another one is for the post_my_path which is sourced from the $ref, which points to the local file (my_path.yaml).

If autorest is unable to product the client for the given route, it should produce an error.

**Additional context**
Command: `autorest --azure-validator --input-file=./openapi.yaml --v3 --typescript --output-folder=typescript`

```
WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.4.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
INFORMATION: Autorest.Typescript took 355ms
[2.57 s] Generation Complete
```

openapi.yaml:
```
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: Test
    description: Test my API

paths:
  /api/workaround:
    get:
      operationId: get_workaround
      tags:
        - Test
      summary: Workaround
      description: Workaround
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: number

  /api/v1/my_path:
    $ref: "my_path.yaml"

components:
  schemas: {}
```

my_path.yaml
```
post:
  operationId: post_my_path
  tags:
    - Test
  summary: Test summary
  description: Test description
  requestBody:
    content:
      application/json:
        schema:
          type: boolean
  responses:
    200:
      description: Ok
      content:
        application/json:
          schema:
            type: boolean

```

**Comment by iorlas** [comment]
I've tried to debug it a bit, to get an idea is it the TypeScript generator went crazy, or it is something really wrong with the autorest core. I've tried to create autorest clients using other languages: golang, java, csharp.

So, it turns out everything is much worse in other stacks:

**GoLang** fails with `System.InvalidOperationException: Nullable object must have a value.`
Command: `autorest --azure-validator --input-file=./openapi.yaml --v3 --go --output-folder=golang --enum-types --verbose --debug`
<details>
<summary>Run result</summary>
 autorest --azure-validator --input-file=./openapi.yaml --v3 --go --output-folder=golang --enum-types --verbose --debug

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.4.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from /Users/iorlas/.autorest/@autorest_core@3.0.6349
   Loading AutoRest core      '/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist' (3.0.6349)
No configuration found at 'file:///Users/iorlas/Projects/projects/x/clients/'.
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/inspect.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-trenton.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-azure-functions.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/help-configuration.md'
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47->2.1.165)
   Including extension configuration file 'file:///Users/iorlas/.autorest/@microsoft.azure_autorest.go@2.1.165/node_modules/@microsoft.azure/autorest.go/README.md'
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Including extension configuration file 'file:///Users/iorlas/.autorest/@microsoft.azure_classic-openapi-validator@1.0.14/node_modules/@microsoft.azure/classic-openapi-validator/readme.md'
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
   Including extension configuration file 'file:///Users/iorlas/.autorest/@microsoft.azure_openapi-validator@1.0.4/node_modules/@microsoft.azure/openapi-validator/readme.md'
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
   Including extension configuration file 'file:///Users/iorlas/.autorest/@microsoft.azure_autorest.modeler@2.3.38/node_modules/@microsoft.azure/autorest.modeler/readme.md'
DEBUG [2.5 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.5 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.5 s]: pipeline-emitter - START inputs = 0
DEBUG [2.52 s]: configuration-emitter - START inputs = 0
DEBUG [2.53 s]: pipeline-emitter - END [0.02 s]
DEBUG [2.53 s]: configuration-emitter - END [0.02 s]
VERBOSE [2.53 s]: Reading OpenAPI 3.0 file file:///Users/iorlas/Projects/projects/x/clients/openapi.yaml
DEBUG [2.53 s]: swagger-document/loader-swagger - END [0.03 s]
DEBUG [2.53 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2.53 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2.53 s]: swagger-document/identity - SKIPPING
DEBUG [2.54 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2.54 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [2.54 s]: swagger-document/classic-openapi-validator - SKIPPING
DEBUG [2.54 s]: swagger-document/openapi-validator - SKIPPING
DEBUG [2.54 s]: swagger-document/individual/classic-openapi-validator - SKIPPING
DEBUG [2.54 s]: swagger-document/individual/openapi-validator - SKIPPING
DEBUG [2.54 s]: openapi-document/loader-openapi - END [0.04 s]
DEBUG [2.54 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [2.55 s]: openapi-document/individual/transform - END [0 s]
DEBUG [2.55 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [2.55 s]: openapi-document/individual/schema-validator-openapi - END [0 s]
DEBUG [2.55 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [2.55 s]: openapi-document/individual/identity - END [0 s]
DEBUG [2.55 s]: openapi-document/transform - START inputs = 1
DEBUG [2.56 s]: openapi-document/transform - END [0 s]
DEBUG [2.56 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [2.56 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [2.56 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [2.57 s]: openapi-document/tree-shaker - END [0 s]
DEBUG [2.57 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2.58 s]: openapi-document/multi-api-merger - END [0 s]
DEBUG [2.58 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [2.58 s]: openapi-document/components-cleaner - END [0 s]
DEBUG [2.58 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [2.59 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [2.59 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [2.59 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [2.59 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.59 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.59 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.59 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.59 s]: openapi-document/emitter - END [0 s]
DEBUG [2.59 s]: openapi-document/model-deduplicator - END [0 s]
DEBUG [2.59 s]: openapi-document/compose - START inputs = 1
DEBUG [2.61 s]: openapi-document/compose - END [0.01 s]
DEBUG [2.61 s]: openapi-document/identity - START inputs = 1
DEBUG [2.61 s]: openapi-document/identity - END [0 s]
DEBUG [2.61 s]: go/imodeler1 - START inputs = 1
DEBUG [3.19 s]: go/imodeler1 - END [0.57 s]
DEBUG [3.19 s]: go/commonmarker - START inputs = 1
DEBUG [3.19 s]: go/commonmarker - END [0 s]
DEBUG [3.19 s]: go/cm/transform - START inputs = 1
DEBUG [3.19 s]: go/cm/transform - END [0 s]
DEBUG [3.19 s]: go/cm/emitter - START inputs = 1
DEBUG [3.19 s]: go/generate - START inputs = 1
DEBUG [3.19 s]: Emitting 'code-model-v1' at file:///Users/iorlas/Projects/projects/x/clients/golang/code-model-v1
DEBUG [3.19 s]: go/cm/emitter - END [0 s]
FATAL: New<AutoRest.Core.Model.CodeModel() threw exception TargetInvocationException - Exception has been thrown by the target of an invocation.
FATAL: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at AutoRest.Go.Model.CodeModelGo..ctor() in /home/vsts/work/1/s/src/Model/CodeModelGo.cs:line 33
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at lambda_method(Closure )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at AutoRest.Core.Utilities.Factory`1.Invoke() in /home/vsts/work/1/s/autorest.common/src/Utilities/Factory.cs:line 157
   at AutoRest.Core.Utilities.DependencyInjection.New[T]() in /home/vsts/work/1/s/autorest.common/src/Utilities/DependencyInjection.cs:line 345
   at AutoRest.Core.Utilities.JsonExtensions.Populate[T](JsonSerializer serializer, JsonReader reader) in /home/vsts/work/1/s/autorest.common/src/Utilities/JsonExtensions.cs:line 27
   at AutoRest.Core.Utilities.DependencyInjectionJsonConverter`1.ReadJson(JObject jObject, Type objectType, Object existingValue, JsonSerializer serializer) in /home/vsts/work/1/s/autorest.common/src/Utilities/DependencyInjectionJsonConverter.cs:line 71
   at AutoRest.Core.Utilities.DeserializingJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /home/vsts/work/1/s/autorest.common/src/Utilities/DependencyInjectionJsonConverter.cs:line 42
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AutoRest.Core.ModelSerializer`1.Load(String jsonText) in /home/vsts/work/1/s/autorest.common/src/ModelSerializer.cs:line 18
   at AutoRest.Go.Program.<ProcessInternal>d__3.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist/lib/pipeline/pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin go reported failure. / Error: Plugin go reported failure.
    at /Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist/lib/pipeline/plugins/external.js:27:19
    at async ScheduleNode (/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist/lib/pipeline/pipeline.js:314:33)
  Error: Plugin go reported failure.
[3.69 s] Shutting Down.
[3.69 s] Exiting.
</details>

**Java** fails to be installed.
Command: `autorest --azure-validator --input-file=./openapi.yaml --v3 --java --output-folder=java --enum-types --verbose --debug`
<details>
<summary>Run result</summary>
autorest --azure-validator --input-file=./openapi.yaml --v3 --java --output-folder=java --enum-types --verbose --debug

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.4.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from /Users/iorlas/.autorest/@autorest_core@3.0.6349
   Loading AutoRest core      '/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist' (3.0.6349)
No configuration found at 'file:///Users/iorlas/Projects/project/x/clients/'.
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/inspect.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-trenton.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/plugin-azure-functions.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/resources/help-configuration.md'
Failed to install or start extension '@autorest/java' (^4.0.4)
  SyntaxError: Unexpected end of JSON input
[1.4 s] Shutting Down.
[1.4 s] Exiting.
</details>


**C#** is the only one that is able to produce the result. 
Command: `autorest --azure-validator --input-file=./openapi.yaml --v3 --go --output-folder=golang --enum-types --verbose --debug`
<details>
<summary>code-model-v1, the core result</summary>
{
 "$id": "1",
 "name": "TestAPI",
 "namespace": "",
 "modelsName": "Models",
 "apiVersion": "1.0.0",
 "baseUrl": "http://localhost:8080",
 "operations": [
  {
   "$id": "2",
   "methods": [
    {
     "$id": "3",
     "name": {
      "$id": "4",
      "fixed": false,
      "raw": "workaround"
     },
     "group": {
      "$id": "5",
      "fixed": false,
      "raw": "get"
     },
     "serializedName": "get_workaround",
     "url": "/api/workaround",
     "isAbsoluteUrl": false,
     "httpMethod": "get",
     "responses": {
      "OK": {
       "$id": "6",
       "body": {
        "$id": "7",
        "$type": "PrimaryType",
        "knownPrimaryType": "double",
        "name": {
         "$id": "8",
         "fixed": false,
         "raw": "Double"
        },
        "deprecated": false
       },
       "extensions": {
        "$id": "9",
        "x-ms-metadata": {
         "apiVersions": [
          "1.0.0"
         ],
         "filename": [
          "mem:///114?oai3.shaken.json"
         ],
         "name": "paths·1wej6cw·api-workaround·get·responses·200",
         "originalLocations": [
          "file:///Users/iorlas/Projects/project/x/clients/openapi.yaml#/components/responses/paths·1wej6cw·api-workaround·get·responses·200"
         ]
        }
       },
       "isNullable": true
      }
     },
     "defaultResponse": {
      "$id": "10",
      "isNullable": true
     },
     "returnType": {
      "$id": "11",
      "body": {
       "$ref": "7"
      },
      "isNullable": true
     },
     "description": "Workaround",
     "summary": "Workaround",
     "requestContentType": "application/json; charset=utf-8",
     "responseContentTypes": [
      "application/json"
     ],
     "extensions": {
      "servers": [
       {
        "url": "http://localhost:8080"
       }
      ]
     },
     "deprecated": false,
     "hidden": false
    }
   ],
   "name": {
    "$id": "12",
    "fixed": false,
    "raw": "Get"
   },
   "typeName": {
    "$id": "13",
    "fixed": false
   },
   "nameForProperty": "Get"
  }
 ]
}
</details>

As we can see from the CSharp generator, it also has this issue. So the referencing issue is common, it is certainly an issue with the core.

I feel like we should remove autorest usage in our project at all, since it is unable to produce the client even for the GoLang and Java.

**Comment by timotheeguerin** [comment]
Believe your 2 issues(with #3751) are the same problem which is $ref is not supported right under path. I'll take a look

**Comment by timotheeguerin** [comment]
understanding more, this is not something we support at all at the moment. I created a new feature request  #3759. Will close this one.

**Comment by iorlas** [comment]
@timotheeguerin That is so unfortunate... But understandable, considering there are so many things in the backlog.

I'm just curious, if it is not possible to use refs with autorest right now, how you guys compose complex openapi specs? I don't believe you are writing 5k-lines length files, you gotta be using preprocessors of some sort, right? What is your best practice here (or maybe in MS/Azure)?

**Comment by timotheeguerin** [comment]
It is possible to use `$refs` but you have to have the secondary files also follow the same structure.
e.g.

In `main.json`
```json
{
   "myProperty": {"$ref": "foo.json#/components/schemas/SharedType"}
}
```

In `foo.json`

```json
{
   "components": {
     "schemas": {
       "SharedType": { "type": "object", ... }
     }
   }
}
```

**Comment by iorlas** [comment]
@timotheeguerin So we can split the components into multiple files, got ya.

But what about the paths? 

Like, it also becomes an issue. Even when all the payloads and query params are offloaded into separate files. Each endpoint will take 14-20 lines, even a simple API with 5-10 entities becomes a headache in the same yaml file.

Is it considered a problem in your practice, how you manage it?
I know I can find related answers on the internet, we already use some related solutions in our company, but I'm really curious about the best practices in MS, Azure, information from the actual maintainer :)

Thanks a lot for your answers, especially during the holidays :)

**Comment by timotheeguerin** [comment]
Yeah, it can be a little tricky to work like that on large openapi specs. Autorest support taking multiple input-files as input which can all have a seperation of concern but still require some verbosity and not really optimal if you want to use 1 file per path. Using a readme.md you can list all the configuration and input files there

See https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cdn/resource-manager for example.

There is also a vscode Autorest extension(If you are using vscode) that should be helping you with writing openapi specs(I have never used it so can't comment on its feature set).

**Comment by iorlas** [comment]
Ah, so we can split it into multiple files to group paths and resources by the scope and feed it into the autorest. Sounds nice, we'll try it out, thank you so much! 🍺
