### ISSUE TITLE
XML comment on Enums

### ISSUE THREAD

**Issue by deaktomi** [Azure/autorest#3755]
**Describe the bug**
When I create an enum in my swagger.json, something like this:
```
"MyType": {
  "description": "My own description about the values.\r\n'value1': Description about value1\r\n'value2': Descripiton about value2",
  "enum": [
	"value1",
	"value2",
  ],
  "type": "string"
},
```
I get the following XML comments for a method that has a `MyType` parameter:

> Gets or sets possible values include: 'value1', 'value2'

**Expected behavior**
I believe it should be something like this:

> Gets or Sets my own description of the values.\r\n'value1': Description about value1\r\n'value2'

Can it be achieved somehow?

**Comment by timotheeguerin** [comment]
when you mean xml comment are you refering to CSharp xmldoc?

**Comment by deaktomi** [comment]
Yes

**Comment by timotheeguerin** [comment]
It does seem this might be an issue with the [csharp genertor](https://github.com/Azure/autorest.csharp) as it seems like autorest doesn't modify the description. 
![image](https://user-images.githubusercontent.com/1031227/103523626-00e05d00-4e31-11eb-9894-c5758b3ddaec.png)

You can create an issue there instead.
