### ISSUE TITLE
xml name not showing up

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3756]
Hey guys, it appears we're not outputting an xml name where I would expect m4 to output it. @tasherif-msft found when generating storage, [this](https://github.com/Azure/azure-rest-api-specs/blob/3901b436d624fad088010fe9554b626d4ee01fd1/specification/storage/data-plane/Microsoft.FileStorage/preview/2020-04-08/file.json#L5600) swagger wasn't outputting an xml name section. While previously it would output. Looking at the output artifact, it appears that m4 isn't giving us this information.

Here is the yaml given to us for this model
 
![image](https://user-images.githubusercontent.com/43154838/103029585-1cda2980-4528-11eb-927e-de3a7c69e7a5.png)

and here's what I'd expect to see to know to include a `name` in the `xml` map:

![image](https://user-images.githubusercontent.com/43154838/103029683-501cb880-4528-11eb-991b-c3d91f3ddf1f.png)

Want to clarify I don't know too much about `xml`, so if this was meant to be please disregard.

cc @tasherif-msft

**Comment by timotheeguerin** [comment]
Seems to be an issue with using a `$ref` along side. It works just fine, with the type inline  or with having the xml attribute in the referenced type 
![image](https://user-images.githubusercontent.com/1031227/103529904-57529900-4e3b-11eb-8297-71d4fd9a96b3.png)


This however seems to be the expected behiavor of the openapi specs. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#reference-object

```
This object cannot be extended with additional properties and any properties added SHALL be ignored.
```

Closing this as this seems to me to be working as expected. Please reopen if you have any other concerns with this.

**Comment by iscai-msft** [comment]
ok thanks @timotheeguerin! @tasherif-msft looks like some swagger changes need to be made
