### ISSUE TITLE
Support self-signed certificates

### ISSUE THREAD

**Issue by eluchsinger** [Azure/autorest#3757]
**Describe the bug**

When trying to get the OpenAPI Specification from a remote place, like `https://localhost:5001/swagger/v1/swagger.json`, autorest will fail to read teh file: Error: Could not read 'https://localhost:5001/swagger/v1/swagger.json'.

Apparently, this has to do with the certificate being self-signed because that's how Visual Studio works.

**Expected behavior**

Autorest should be able to handle the situation correctly and generate the client. 

**Additional context**

This bug is also related (and was first mentioned) in: https://github.com/Azure/autorest/issues/2670

**Comment by timotheeguerin** [comment]
can you try adding `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable and see if that works. I guess we could add a dedicated flag/environment variable to support this scenario
