### ISSUE TITLE
Unable to find a valid AutoRest core package '@autorest/core' 

### ISSUE THREAD

**Issue by MikhailTryakhov** [Azure/autorest#3764]
**Describe the bug**

Installed autorest using command ```npm install -g autorest```
I need autorest 2.0.4413 version but changing version I have failure from 2 different machines...
```autorest --version=2.0.4413
AutoRest code generation utility [cli version: 3.0.6322; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Package '@microsoft.azure/autorest-core' - '2.0.4413' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest-core/-/autorest-core-2.0.4413.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest-core/-/autorest-core-2.0.4413.tgz' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
```

**Expected behavior**
Successful update to the version specified

**Comment by timotheeguerin** [comment]
Hey @MikhailTryakhov what is the command line you are using to get this error?

**Comment by MikhailTryakhov** [comment]
@timotheeguerin  different ones. Command prompt (regular one), node.js cmd, Dev cmd from VS 2019

**Comment by MikhailTryakhov** [comment]
same issue everywhere

**Comment by daviwil** [comment]
@MikhailTryakhov I believe Tim is asking what is the exact `autorest` command invocation are you using, meaning what paremeters are you passing to it?

**Comment by MikhailTryakhov** [comment]
@daviwil @timotheeguerin  oh sorry I'm using autorest --version:2.0.4413

**Comment by timotheeguerin** [comment]
@MikhailTryakhov have you tried running `autorest --reset`? If that doesnt work could you try running `npm install @microsoft.azure_autorest-core@2.0.4413` somewhere and see if the package succeed in installing on your machine.

**Comment by MikhailTryakhov** [comment]
That helped! Thanks a lot!
