### ISSUE TITLE
x-ms-pageable examples missing

### ISSUE THREAD

**Issue by rikogeln** [Azure/autorest#3766]
docs/extensions/readme.md mentions example files for the use of the swagger x-ms-pageable extension. 
"Full code: example1.yaml, example1.cs" in line 908 and 909 - the mentioned files do not exist and lead to a 404 

i'd expect the samples to be present

**Comment by timotheeguerin** [comment]
hhm looking at the history seems like those samples were never added with the links. @iscai-msft would you know if those samples are somewhere else?

**Comment by iscai-msft** [comment]
i've never heard of those ssamples, I'll remove them from the docs to avoid confusion

**Comment by iscai-msft** [comment]
removed these erroneous links, closing this issue thanks @rikogeln !
