### ISSUE TITLE
Add flag printing the configuration used

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3769]
An example , if I want to dump the csharp generator runtime config:
autorest --dumpConfig --csharp   path-to-readme/readme.md

The output is config map like , but the generator won't run exactly:
```
title: AutomationClient
description: Automation Client
openapi-type: arm
tag: package-2018-06-preview
```
As the config may impact the generator behavior , I want to know whether the **readme file change**  in PR reviewing will impact the code generator . so that I can detect the change before it being merged.
Any useful information would be appreciate.

**Comment by timotheeguerin** [comment]
You can actually add `--output-artifact:configuration.yaml` which will create a `configuration.yaml` in the `output-folder` with the entire config.

**Comment by jianyexi** [comment]
> --output-artifact:configuration.yaml
Thanks , this solve my problem in part , is there a way to get the config while not run the generator exactlly.

**Comment by timotheeguerin** [comment]
Do you mean not generate the code? What if you don't use the `--csharp`

**Comment by jianyexi** [comment]
> Do you mean not generate the code? What if you don't use the `--csharp`

Yes, I think if not specify the `--csharp` , the config inside the csharp generator won't be dump to the configuration.yaml   , right ?

**Comment by jianyexi** [comment]
In addition,  sometimes it takes too much time to generate a large RP,  and I  want to know the config is changed or not to decide whether I need to re-generate the code  against last generation.
