### ISSUE TITLE
WriteOnly property is not supported by Autorest v3

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#3780]
WriteOnly property throws `EXEC : error : Schema violation: Additional properties not allowed: writeOnly`. Looks like it is not supported by autorest. It is useful for the password type property where the property is required when sending a request and not required in response.

Here's the openapi docs for writeonly property https://swagger.io/docs/specification/data-models/data-types/ 

Can we add support for that?

**Comment by lmazuel** [comment]
Let's discuss concretete scenario, I have a doubt we need something here:
- If service doesn't return the password, you don't have a problem
- If the service does, do we want SDK to decide for us we don't want to show it when the service wanted to show it to us?

**Comment by timotheeguerin** [comment]
writeOnly not exists for swagger 2.0 this error was coming swagger 2.0 schema validation.
