### ISSUE TITLE
how should we generate clients with no host

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3781]
Got an [issue](If host is not specified, it is assumed to be the same host where the API documentation is being served.) on the autorest.python repo that partially arose since the person didn't define a `host` in their swagger. I told them to use a host, but from this, it does look like we're not handling a "no host" client very well.

Accordinig to the [open api docs](https://swagger.io/docs/specification/2-0/api-host-and-base-path/),
```
If host is not specified, it is assumed to be the same host where the API documentation is being served.
```

This isn't something we're doinig rn. I'm thinking for implementation of this that m4 should set the `cliientDefaultValue` to the host where the API documentation is, does this sound right / doable? Thanks!

Task: 
- [ ] Add docs for generators #3793
- [ ] Python generator make host required if not provided Azure/autorest.python/pull/868
- [ ] CSharp generator make host required if not provided
- [ ] Typescript generator make host required if not provided
- [ ] Golang generator make host required if not provided

cc @daviwil @lmazuel @timotheeguerin

**Comment by lmazuel** [comment]
This is not sustainable in our scenario, we need a host in the Swagger. And this means we make it required, so bet it. I don't see how we could do otherwise.

**Comment by timotheeguerin** [comment]
@lmazuel why do we say we should require the host for sure? Couldn't we get the default host to be where the file is hosted?(as the specs specify).
We could probably exclude some domains like `github.com` where it will not default to be from that url.

**Comment by iscai-msft** [comment]
to add to the discussion, @agniveshadhikari has replied to the original python issue

```
adding a host to the swagger is not an option, since the use case is to generate a client for a multitenant application where each tenant has a different base url.
```

I'm waiting to see if this. can be something solved by a parameterized host. However, if that is not the case, would we be able to accept no host and instead rely solely on user input (and make it a required user parameter)? I know t his would't fully conform to swagger standards, but not allowinng a host would also not conform. Either way ([at least in python](https://github.com/Azure/autorest.python/blob/autorestv3/test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/_auto_rest_swagger_bat_array_service.py#L33)), we still allow users to input a host (we refer to it as `base_url`), we just default to whatever the user has inputted.

**Comment by timotheeguerin** [comment]
@iscai-msft Doesn't right now the generated code lets you change the host on creation of the client?

Is there goal to generate a different SDK per tenant? Because supporting this default value would result in them generating one per tenant. That doesn't seem like the right thing to do? 

Maybe as you said a parametrized host might do the trick or as we have it now(With maybe a way to mark the host as required if it's not provided)

**Comment by iscai-msft** [comment]
For Python, we currently always have `base_url` as optional for users to input, and we default to the value of the host. Took a quick look through c# and I don't believe this is always the case for them (they sometimes have it as required). Edited my previous comment to make the point I had more clear, but I'm trying to see if in this case, we should make the `base_url` param required for users to input. This part of the issue might be more python-specific though.

cc @lmazuel

**Comment by pakrym** [comment]
.net generates an optional parameter for the endpoint(host) but we can also generate a required one just as easily.

**Comment by iscai-msft** [comment]
ok thanks @pakrym , def makes me like the idea of making it required in the case of no defined host more

**Comment by lmazuel** [comment]
That would make sense then, if no host in Swagger then it's a required parameter. I can deal with that. But using the host where the Swagger is is a non-concept in SDK, that will never give something useful (my two cents)

**Comment by timotheeguerin** [comment]
Decided that generator should fail if `host` or `x-ms-paramiterized-host` is not provided.
