### ISSUE TITLE
Could not find a declaration file for module 'autorest'

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3787]
**Describe the bug**
```
When import the 'autorest' package from other npm package used by typescript  , it always reports this error
```
The code is like below:

`import * as autorest from "autorest";`

I think it's caused by the incorrect 'typings' defined in the package.json

**Comment by jianyexi** [comment]
The 'autorest/core' also has this issue.

**Comment by jianyexi** [comment]
> **Describe the bug**
> 
> ```
> When import the 'autorest' package from other npm package used by typescript  , it always reports this error
> ```
> 
My code is like this:
`import * as autorest from "autorest";`

> I think it's caused by the incorrect 'typings' defined in the package.json

**Comment by jianyexi** [comment]
@timotheeguerin  I am wondering if you have any plan to publish a new version ?

**Comment by timotheeguerin** [comment]
@jianyexi I have a PR out to renable automatic publishing of `autorest` and `@autorest/core`. Should hopefully get that merged today or I'll do a manual release
