### ISSUE TITLE
Rename definiation or property name

### ISSUE THREAD

**Issue by LucasYao93** [Azure/autorest#3792]
**Describe the issue or request**
When the object model name and one of its complex property name are same in swagger.json, an exception was throw when generating csharp.

Details as flows:

EXEC : error (): **Duplicate object schemas with 'Capabilities' name  detected.**[D:\azure-sdk-net\master\azure-sdk-for-net\sdk\containerinstance\Azure.ResourceManager.ContainerInstance\src\Azure.ResourceManager.ContainerInstance.csproj]
FATAL : error : 1 errors occured -- cannot continue. [D:\azure-sdk-net\master\azure-sdk-for-net\sdk\containerinstance\Azure.ResourceManager.ContainerInstance\src\Azure.ResourceManager.ContainerInstance.csproj]
EXEC : error : Plugin checker reported failure. [D:\azure-sdk-net\master\azure-sdk-for-net\sdk\containerinstance\Azure.ResourceManager.ContainerInstance\src\Azure.ResourceManager.ContainerInstance.csproj]

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2020-11-01/containerInstance.json#L1818-L1867
``` json
"definitions": {
   "Capabilities": {
      "description": "The regional capabilities.",
      "type": "object",
      "properties": {
        "resourceType": {
          "type": "string",
          "readOnly": true,
          "description": "The resource type that this capability describes."
        },
        "osType": {
          "type": "string",
          "readOnly": true,
          "description": "The OS type that this capability describes."
        },
        "location": {
          "type": "string",
          "readOnly": true,
          "description": "The resource location."
        },
        "ipAddressType": {
          "type": "string",
          "readOnly": true,
          "description": "The ip address type that this capability describes."
        },
        "gpu": {
          "type": "string",
          "readOnly": true,
          "description": "The GPU sku that this capability describes."
        },
        "capabilities": {
          "type": "object",
          "readOnly": true,
          "description": "The supported capabilities.",
          "properties": {
            "maxMemoryInGB": {
              "type": "number",
              "readOnly": true,
              "description": "The maximum allowed memory request in GB."
            },
            "maxCpu": {
              "type": "number",
              "readOnly": true,
              "description": "The maximum allowed CPU request in cores."
            },
            "maxGpuCount": {
              "type": "number",
              "readOnly": true,
              "description": "The maximum allowed GPU count."
            }
          }
        }
      }
    },
}
```
Environment:
@autorest_core@3.0.6326
autorest.csharp/3.0.0-beta.20210105.3

**Describe your ideas for solutions**
NA

**Comment by timotheeguerin** [comment]
@LucasYao93 I believe this was already fixed in modelerfour. Could you try using the following flag:
```
--use:@autorest/modelerfour@4.15.448
```

**Comment by LucasYao93** [comment]
@timotheeguerin 
Resolved issue. Thanks for you help.
