### ISSUE TITLE
Invalid doc link to C# in "Using the Generated Client"

### ISSUE THREAD

**Issue by zxue** [Azure/autorest#3799]
The C# hyperlink is invalid. Should it be this, "https://github.com/Azure/autorest.csharp"?

**Comment by timotheeguerin** [comment]
@zxue which link are you referring to?

**Comment by timotheeguerin** [comment]
I see the link referenced here https://github.com/Azure/autorest/blob/master/docs/client/readme.md. 

This is done on purpose. The CSharp documentation will be updated to respect that strcture.
