### ISSUE TITLE
Codegenerator fails on large API definition

### ISSUE THREAD

**Issue by kamilkosek** [Azure/autorest#3801]
Hi all,
I´ve got quite a large API Definition file from OpenHAB v3 (Smarthome Automation Software), where I cannot generate the code from.
You can find the definition file here: [OpenHAB Swagger JSON](https://gist.github.com/kamilkosek/fa7d9a97fcdcb7233e038c3d601d0438)

I can´t resolve if the issue is related to the model or if its a bug in modelerfour 🤔

This is the debug output from autorest: 

`PS C:\dev\openhab-ps> autorest --powershell --input-file:.\apiDefinition.json --verbose --namespace:OpenHab --debug --max-memory-size=8912

AutoRest code generation utility [cli version: 3.0.6322; node: v14.0.0, max-memory: 8960 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\k\.autorest\@autorest_core@3.0.6365
   Loading AutoRest core      'C:\Users\k\.autorest\@autorest_core@3.0.6365\node_modules\@autorest\core\dist' (3.0.6365)
No configuration found at 'file:///C:/dev/openhab-ps/'.
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/inspect.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-trenton.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/plugin-azure-functions.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_core@3.0.6365/node_modules/@autorest/core/resources/help-configuration.md'

The default version of @autorest/powershell has been bummped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

   Loading AutoRest extension '@autorest/powershell' (~3.0.0->3.0.418)
   Including extension configuration file 'file:///C:/Users/k/.autorest/@autorest_powershell@3.0.418/node_modules/@autorest/powershell/readme.md'
   Including configuration file 'file:///C:/Users/k/.autorest/@autorest_powershell@3.0.418/node_modules/@autorest/powershell/autorest-configuration.md'
   Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
   Including extension configuration file 'file:///C:/Users/k/.autorest/@autorest_modelerfour@4.15.414/node_modules/@autorest/modelerfour/readme.md'
DEBUG [1.62 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.62 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.62 s]: pipeline-emitter - START inputs = 0
DEBUG [1.67 s]: configuration-emitter - START inputs = 0
DEBUG [1.67 s]: pipeline-emitter - END [0.05 s]
DEBUG [1.67 s]: configuration-emitter - END [0.05 s]
VERBOSE [1.93 s]: Reading OpenAPI 3.0 file file:///C:/dev/openhab-ps/apiDefinition.json
DEBUG [1.99 s]: swagger-document/loader-swagger - END [0.37 s]
DEBUG [1.99 s]: swagger-document/individual/transform - SKIPPING
DEBUG [1.99 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [1.99 s]: swagger-document/identity - SKIPPING
DEBUG [1.99 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [2.14 s]: openapi-document/loader-openapi - END [0.52 s]
DEBUG [2.14 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [2.19 s]: openapi-document/individual/transform - END [0.04 s]
DEBUG [2.19 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [2.29 s]: openapi-document/individual/schema-validator-openapi - END [0.1 s]
WARNING: Schema violation: Data does not match any schemas from 'oneOf' (components > securitySchemes > oauth2)
    - file:///C:/dev/openhab-ps/apiDefinition.json:7060:3
WARNING: Schema violation: Data does not match any schemas from 'oneOf' (paths > /rules > post > responses > 201)
    - file:///C:/dev/openhab-ps/apiDefinition.json:830:5
DEBUG [2.3 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [2.3 s]: openapi-document/individual/identity - END [0 s]
DEBUG [2.3 s]: openapi-document/transform - START inputs = 1
DEBUG [2.32 s]: openapi-document/transform - END [0.02 s]
DEBUG [2.32 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [2.33 s]: openapi-document/allof-cleaner - END [0.01 s]
DEBUG [2.34 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [2.53 s]: openapi-document/tree-shaker - END [0.19 s]
DEBUG [2.53 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2.84 s]: openapi-document/multi-api-merger - END [0.3 s]
DEBUG [2.84 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [3.23 s]: openapi-document/components-cleaner - END [0.39 s]
DEBUG [3.23 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [3.3 s]: openapi-document/component-modifiers - END [0.06 s]
DEBUG [3.3 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [3.3 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [3.3 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [3.3 s]: openapi-document/profile-filter - END [0 s]
DEBUG [3.3 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [3.3 s]: openapi-document/emitter - START inputs = 1
DEBUG [3.3 s]: openapi-document/model-deduplicator - END [0 s]
DEBUG [3.3 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [3.3 s]: openapi-document/emitter - END [0 s]
DEBUG [3.63 s]: openapi-document/enum-deduplicator - END [0.32 s]
DEBUG [3.63 s]: openapi-document/subset-reducer - START inputs = 1
DEBUG [3.63 s]: openapi-document/subset-reducer - END [0 s]
DEBUG [3.63 s]: openapi-document/quick-check - START inputs = 1
DEBUG [3.63 s]: openapi-document/multi-api/reset-identity - START inputs = 1
DEBUG [3.7 s]: openapi-document/quick-check - END [0.06 s]
DEBUG [3.7 s]: openapi-document/multi-api/reset-identity - END [0.06 s]
DEBUG [3.7 s]: openapi-document/multi-api/identity - START inputs = 1
DEBUG [3.7 s]: openapi-document/multi-api/identity - END [0 s]
DEBUG [3.7 s]: openapi-document/multi-api/emitter - START inputs = 1
DEBUG [3.7 s]: prechecker - START inputs = 1
DEBUG [3.7 s]: openapi-document/multi-api/emitter - END [0 s]

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
DEBUG [3.91 s]: prechecker - END [0.2 s]
DEBUG [3.91 s]: modelerfour - START inputs = 2
VERBOSE [3.98 s]:   ModelerFour/api-version-mode:client
VERBOSE [3.98 s]:   ModelerFour/api-version-parameter:constant
VERBOSE [3.98 s]:   ModelerFour/use-model-namespace:false
C:\Users\k\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\modeler\plugin-modelerfour.js - FAILURE  "Unresolved item." undefined
PLUGIN FAILURE: undefined, undefined, "Unresolved item."
FATAL: Unresolved item.
C:\Users\k\.autorest\@autorest_core@3.0.6365\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin modelerfour reported failure. / Error: Plugin modelerfour reported failure.
    at C:\Users\k\.autorest\@autorest_core@3.0.6365\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:27:19
    at async ScheduleNode (C:\Users\k\.autorest\@autorest_core@3.0.6365\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:314:33)
  Error: Plugin modelerfour reported failure.
[4.03 s] Shutting Down.
[4.03 s] Exiting.
PS C:\dev\openhab-ps>
`

**Comment by timotheeguerin** [comment]
You have in your spec a `Location` header which has no schema. 

```json
// Is
"Location": {
  "description": "Newly created Rule",
  "style": "simple"
}

// Should be
"Location": {
  "description": "Newly created Rule",
  "style": "simple", 
  "schema": {
    "type": "string"
  }
}
```

I am not sure however why it is not failing before to tell you the specs are invalid

**Comment by timotheeguerin** [comment]
Sorry I guess it does but just as a warning 
```
WARNING: Schema violation: Data does not match any schemas from 'oneOf' (components > securitySchemes > oauth2)
- file:///C:/dev/openhab-ps/apiDefinition.json:7060:3
WARNING: Schema violation: Data does not match any schemas from 'oneOf' (paths > /rules > post > responses > 201)
- file:///C:/dev/openhab-ps/apiDefinition.json:830:5
```
