### ISSUE TITLE
OpenAPI 3 Parsing Errors

### ISSUE THREAD

**Issue by kevin-weir** [Azure/autorest#3803]
I'm using the latest version of AutoRest (3.0.6322) and have two separate parsing bugs to share with you when parsing the OpenApi document openapi.txt

[openapi.txt](https://github.com/Azure/autorest/files/5867258/openapi.txt)

When I run the following command against openapi.txt I get two separate parsing errors:

`autorest --debug --version=3.0.6365 --csharp --input-file=openapi.txt --output-folder=TestCS`

### **Error 1 is caused by the x-generator field:**

"x-generator": "NSwag v13.10.1.0 NJsonSchema v10.3.3.0 (Newtonsoft.Json v12.0.0.0))"

![error1](https://user-images.githubusercontent.com/39222151/105721722-7ef0ca80-5eea-11eb-8fde-7d4f7b5a00ba.PNG)

**Expected behavior**
According to the OpenAPI 3.x specification the string primitive is an acceptable value for x-generator.  This should not be producing an error.

https://swagger.io/specification/#specification-extensions

![Extensions](https://user-images.githubusercontent.com/39222151/105722333-2bcb4780-5eeb-11eb-8f1d-5ead11618784.PNG)

### **Error 2 is caused by the additionalProperties of the ToDoItem component:**

"additionalProperties": false

![error2](https://user-images.githubusercontent.com/39222151/105723559-89ac5f00-5eec-11eb-9112-cf24f3e1d44b.PNG)

**Expected behavior**
According to the OpenAPI 3.x specification a boolean value of false is a valid value for additionalProperties and should not produce a parsing error.

https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.18

![AdditionalProperties](https://user-images.githubusercontent.com/39222151/105724014-06d7d400-5eed-11eb-8ccf-1c7daf3df0ea.PNG)

**Comment by timotheeguerin** [comment]
Hi @kevin-weir, found the issue for the first error, I have a PR up to fix it in the underlying package. For the 2nd issue this seems to be a problem with the `autorest.csharp` generator itself. I would create a new issue on this repo https://github.com/Azure/autorest.csharp for that.(Don't want to transfer this issue as it has the first problem which is autorest core problem.)

**Comment by kevin-weir** [comment]
Thanks Tim
