### ISSUE TITLE
Inconsistent property field naming

### ISSUE THREAD

**Issue by cxfll** [Azure/autorest#3830]
Generated entity, property name is inconsistent with the original, the underline is lost, how can I configure it。

Examples：

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPS_GID")]
        public string GPSGID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPS_ID")]
        public string GPSID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPS_NAME")]
        public string GPSNAME { get; set; }

I want the property name to be the same as the original。

**Comment by timotheeguerin** [comment]
Hi, @cxfll this is by design, autorest handles generation for many languages and convert naming to the convention of each language(PascalCase for c#). If you want to force keep this naming you can have this configuration:

You can add this configuration to the readme configuration.
```yaml
modelerfour:
  naming: 
    override: 
        GPS_GID: GPS_GID
```

**Comment by cxfll** [comment]
Do you want to set the method globally, because I only use C#

**Comment by timotheeguerin** [comment]
Hey @ckfll I am not sure what you mean, here is the doc on how to use the configuration https://github.com/Azure/autorest/blob/master/docs/user/configuration.md

**Comment by MarcErdmann** [comment]
@timotheeguerin Is this still working or was it replaced by having transformations?
