### ISSUE TITLE
Documentation link on how to use generated client for C# is broken

### ISSUE THREAD

**Issue by apattath** [Azure/autorest#3836]
**Describe the bug**
```
Documentation link on 'How to use the Generated Client' for C# is broken. The link for C# on https://github.com/Azure/autorest/blob/master/docs/client/readme.md points to https://github.com/Azure/autorest.csharp/tree/v3/docs/client/readme.md, which gives a 404 error.
```

**Expected behavior**
Takes me to the documentation page for C# on how to use generated client.

**Comment by timotheeguerin** [comment]
We are in the process of rewritting docs. Those links were added as placeholder for where the docs will be. You can see the progress in that PR https://github.com/Azure/autorest.csharp/pull/962
