### ISSUE TITLE
Make autorest --csharp default to track2

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#3849]
Currently `autorest --chsharp` default to [V2 version of C# generator](https://github.com/Azure/autorest/blob/master/packages/extensions/core/resources/plugin-csharp.md) and uses "@microsoft.azure/autorest.csharp" package. Now that we added command line support for track-2 C# generator, we should update the default to V3 C# generator and use "@autorest/csharp" package instead.

We can have --legacy flag as [Java](https://github.com/Azure/autorest/blob/master/packages/extensions/core/resources/plugin-java.md) to enable the use of the V2 C# generator and for this we can use `2.3.91` preview version of "@microsoft.azure/autorest.csharp" package.

**Comment by ShivangiReja** [comment]
CC: @daviwil @timotheeguerin @lmazuel

**Comment by timotheeguerin** [comment]
@ShivangiReja What version of the csharp package should I configure it to be?

**Comment by timotheeguerin** [comment]
also do you actually want to default to using v3 or should we just support the `--v3` flag and make it the default later.

**Comment by daviwil** [comment]
We want to make this package the new default for v3 like we did for TypeScript, Python, and Java

**Comment by ShivangiReja** [comment]
@timotheeguerin we can use [@autorest/csharp@3.0.0-beta.20210205.1](https://www.npmjs.com/package/@autorest/csharp/v/3.0.0-beta.20210205.1) version or above.

CC: @pakrym
