### ISSUE TITLE
Renaming a definition using a custom transformation not working

### ISSUE THREAD

**Issue by seaki-msft** [Azure/autorest#3854]
**Describe the bug**
This is for the [API Connector](https://github.com/Azure/Connectors) project. I am trying to rename one of the definitions using a custom transformation and it's not working. The below example is when I tried to remove a definition called `Queue` and hard-code a new definition called `AzureQueue`

- Link to swagger file: [azurequeues.json](https://github.com/Azure/Connectors/blob/seaki/azurequeues/sdk/swaggers/ms-services/released/azurequeues.json)
- custom transformation snippet
```
  - from: swagger-document
    where: $
    transform: >-
      delete $.definitions["Queue"];
      $.definitions.AzureQueue = {​​​​​​
        "properties": {​​​​​​
          "Name": {​​​​​​
            "description": "The name of the queue.",
            "type": "string",
            "x-ms-summary": "Name"
          }​​​​​​
        }​​​​​​,
        "type": "object"
      }​​​​​​
      $.definitions.QueueArray.items.$ref = "#/definitions/AzureQueue"
```
- AutoRest command: ` autorest ./$($path_to_config_) --input-file:./sdk/swaggers/ms-services/released/azurequeues.json --output-folder:./ScriptGenerated/AzureQueue --override-client-name:AzureQueueConnector --namespace:Azure.Connectors.AzureQueue --csharp-only`

**Expected behavior**
Generate `AzureQueue.cs` instead of `Queue.cs`. But currently it is generating `Queue.cs`. 

**Additional Context**
We noticed that [x-ms-client-name](https://azure.github.io/autorest/extensions/#x-ms-client-name) allows us to rename a query/header parameter and properties schema but not a definition. Is there another directive that we can use to easily rename a definition?

**Comment by timotheeguerin** [comment]
Hhm, can't seem to reproduce, I get the right expected name in the model
![image](https://user-images.githubusercontent.com/1031227/107291215-aaac9e00-6a1c-11eb-8cee-67294b1b909f.png)

This is the config I used 
````md
### Basic Information

> see https://aka.ms/autorest

```yaml
# version: 3.0.6369

directives:
  - from: swagger-document
    where: $
    transform: >-
      delete $.definitions["Queue"];
      $.definitions.AzureQueue = {​​​​​​
        "properties": {​​​​​​
          "Name": {​​​​​​
            "description": "The name of the queue.",
            "type": "string",
            "x-ms-summary": "Name"
          }​​​​​​
        }​​​​​​,
        "type": "object"
      }​​​​​​
      $.definitions.QueueArray.items.$ref = "#/definitions/AzureQueue"
```
````

**Comment by timotheeguerin** [comment]
Talked offline and using the built in `rename-model` directive solved the problem

```yaml
- rename-model:
    from: Queue
    to: AzureQueue
```

**Comment by seaki-msft** [comment]
Thanks for the help!
