### ISSUE TITLE
Parameter with type string generates yaml with object schema

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#3856]
After doing some digging on https://github.com/azure/autorest.csharp/issues/986 I've isolated a sample that @pakrym suggested was possibly an autorest issue.

Here is a [simplified test swagger](https://gist.github.com/chamons/fe395252f960bee052bceef2615f6744#file-foo-json-L47).

```
        "Grant_type": {
            "name": "grant_type",
            "description": "Can take a value of access_token_refresh_token, or access_token, or refresh_token",
            "type": "string",
            "in": "formData",
```

And here is [the generated yaml](https://gist.github.com/chamons/d62b4c5a4b1f7ce4e24a7d708b46332c#file-foo-yaml-L67).

**Comment by timotheeguerin** [comment]
Resolved in latest modelerfour
