### ISSUE TITLE
Process() cancelled due to exception : Cannot resolve pipeline stage 'identity'. 

### ISSUE THREAD

**Issue by vsarunov** [Azure/autorest#3873]
Not able to generate
```
Please provide as much information as you can. This would be: 
- Autorest command used
```

**Expected behavior**
Generates expected files

**Additional context**

Command used via ps

&autorest --input-file=$filePath --output-folder=$generationPath --namespace=mynamespace --use-datetimeoffset --package-name=mypackage --version=latest 

error debug level

```
Network Enabled: true
Starting @autorest/core from C:\Users\*******\.autorest\@autorest_core@3.0.6372
   Loading AutoRest core      'C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist' (3.0.6372)
   Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210210.5)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.456->4.15.456)
Process() cancelled due to exception : Cannot resolve pipeline stage 'identity'. / Error: Cannot resolve pipeline stage 'identity'.
    at resolvePipelineStageName (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2743:15)
    at C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2767:43
    at Array.map (<anonymous>)
    at createNodesAndSuffixes (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2767:32)
    at buildPipeline (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2817:9)
    at Object.runPipeline (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2917:22)
    at processInternal (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:170:17)
    at currentMain (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\app.js:347:24)
    at mainImpl (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\app.js:525:20)
    at main (C:\Users\*******\.autorest\@autorest_core@3.0.6372\node_modules\@autorest\core\dist\app.js:552:20)
  Error: Cannot resolve pipeline stage 'identity'.
[1.77 s] Shutting Down.
[1.77 s] Exiting.
```

Tried to use what is said in this thread https://github.com/Azure/autorest/issues/3693, still not luck.

Tried using previous version, worked like charm.

**Comment by samjegal** [comment]
I'm getting the same error. 
Even if I compile myself, the same result is produced, and it seems that the `openapi-document` plugin cannot be loaded.

```
AutoRest code generation utility [cli version: 3.0.6338; node: v14.15.4, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/****/.autorest/@autorest_core@3.0.6369/node_modules/@autorest/core/dist' (3.0.6369)
   Loading AutoRest extension '@autorest/modelerfour' (https://tinyurl.com/y5sqclzm->4.15.456)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47->2.1.171)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
  Error: Cannot resolve pipeline stage 'openapi-document/identity'.
```

**Comment by samjegal** [comment]
I think the document/identity configuration file should be used as document/individual/identity. After testing this in the autorest.go package, it was confirmed that the error passed.

**Comment by rasmuschristensen** [comment]
Are you targeting an ASPNET Core or ASPNET project? I had this issue targeting ASPNET and switched back to AutoRest V2 to solve it.... :(

**Comment by timotheeguerin** [comment]
Hi all, 
The csharp generation was updated to default to use v3 recently, guessing this is the source of those issues.

are you still having this issue after running `autorest --reset`?

If so could you try adding `--use%3D@microsoft.azure/autorest.csharp@2.3.82` to revert to v2 and let us know if that solve the problem. If it does there might be some other issues in the configuration preventing the use of v3

**Comment by timotheeguerin** [comment]
Believe we have found some issue, will keep you posted. In the meantime you can revert to v2 as shown above or I believe also specifying an older version of `@autorest/core` using `--version:` would solve the issue

**Comment by daviwil** [comment]
You can also just use `autorest --csharp --v2` without using the explicit version of `@microsoft.azure/autorest.csharp`

**Comment by timotheeguerin** [comment]
The fix should be out, please use `@autorest/core`  version `3.0.6373`. Running `autorest --reset` and running your command again should pull the latest. Otherwise you can force it using `--version:3.0.6373`
