### ISSUE TITLE
Error running autorest@3.0.6338 on node docker image

### ISSUE THREAD

**Issue by mbolesta** [Azure/autorest#3874]
**Describe the bug**
```
AutoRest code generation utility [cli version: 3.0.6338; node: v12.18.4, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/root/.autorest/@autorest_core@3.0.6372/node_modules/@autorest/core/dist' (3.0.6372)
   Installing AutoRest extension '@autorest/csharp' (latest)
   Installed AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210210.5)
   Installing AutoRest extension '@autorest/modelerfour' (4.15.456)
   Installed AutoRest extension '@autorest/modelerfour' (4.15.456->4.15.456)
  Error: Unable to resolve full path for executable 'dotnet' -- (cmdline 'dotnet --roll-forward Major ./AutoRest.CSharp.dll --server')
child_process.js:669
    throw err;
    ^


Command used:
autorest --csharp --input-file=swagger.json --namespace=MyNamespace --output-file=MyProxy.cs --output-folder=. --override-client-name=MyProxy --sync-methods=none --use-internal-constructors --v3
```

**Expected behavior**
AutoRest generates the proxy client.

**Additional context**
3.0.6336 works as expected.

**Comment by mbolesta** [comment]
Adding `--use=@microsoft.azure/autorest.csharp@2.3.79` to my command allowed me to work around the issue.

**Comment by timotheeguerin** [comment]
Hey @mbolesta does the docker image has dotnet installed and available on the path?

**Comment by mbolesta** [comment]
@timotheeguerin it does not, will that be a new requirement to generate a C# client?

**Comment by timotheeguerin** [comment]
I believe it is with the new csharp generator(v3), @pakrym can confirm the requirements for the v3 generator

**Comment by pakrym** [comment]
We have updated the default generator to the new version `V3`, which uses `@autorest/csharp` package and it will have few side effects:
   - It will generate code based on the [.NET SDK guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html), which will be totally different than the code generated by `V2` version.
   - dotnet core runtime 3.1+ is required to be available.
   - If you still want to generate code based on `V2` version, you can add `--legacy` flag to the command line to get the previous behavior.

**Comment by mbolesta** [comment]
@pakrym understood thanks!
