### ISSUE TITLE
Low Level Client (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/autorest#3882]
This tracks the work for Low Level Client

**Comment by ffMathy** [comment]
@AlexGhiondea would this help with #3982?

**Comment by AlexGhiondea** [comment]
@ffMathy I don't believe this issue would help with that. This issue tracks work that the Azure SDK team is doing to generate something that we call a low level client that allows users to use an Azure service.

@ramya-rao-a would you know if it is possible to achieve what @ffMathy is asking about?

**Comment by ramya-rao-a** [comment]
Thanks for looping me in @AlexGhiondea 
Responded in https://github.com/Azure/autorest.typescript/issues/887 to which #3982 got moved to
