### ISSUE TITLE
$ref to original location not found

### ISSUE THREAD

**Issue by leni-msft** [Azure/autorest#3885]
**Describe the bug**
When running the following command to generate Microsoft.Authorizaiton schemas, autorest pipeline failed at `openapi-document/emitter` (with `--debug`) :
```
autorest --azureresourceschema --tag=schema-authorization-2020-09-01 https://github.com/Azure/azure-rest-api-specs/blob/dfedab416d1c4fe521f6f3c58cdcb0da37107b84/specification/resources/resource-manager/readme.md
AutoRest code generation utility [cli version: 3.0.6339; node: v14.15.5, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/home/leni/.autorest/@autorest_core@3.0.6373/node_modules/@autorest/core/dist' (3.0.6373)
   Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.92)
  Error: $ref to original location '#/components/schemas/schemas:516' is not found in the new refs collection
```

Please provide as much information as you can. This would be: 
- OpenAPI files having the issues:
> https://github.com/Azure/azure-rest-api-specs/blob/dfedab416d1c4fe521f6f3c58cdcb0da37107b84/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json
- Autorest command used:
> autorest --azureresourceschema --tag=schema-authorization-2020-09-01 https://github.com/Azure/azure-rest-api-specs/blob/dfedab416d1c4fe521f6f3c58cdcb0da37107b84/specification/resources/resource-manager/readme.md

**Expected behavior**
The Microsoft.Authorization ARM Template schemas can be successfully generated.

**Additional context**
Tried to debug into autorest code, the `obj` value is as follows, when throwing the Error:
![image](https://user-images.githubusercontent.com/7233663/107933172-5e7fd180-6fb9-11eb-89b8-405f0f6911e3.png)

```
{
  "x-ms-metadata": {
    "apiVersions": [
      "2020-06-01"
    ],
    "filename": [
      "mem:///394?oai3.shaken.json"
    ],
    "name": "paths·1fnlsr8·providers-microsoft-resources-deployments-deploymentname-whatif·post·responses·202·headers·location",
    "originalLocations": [
      "file:///home/leni/workspace/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#/components/headers/paths·1fnlsr8·providers-microsoft-resources-deployments-deploymentname-whatif·post·responses·202·headers·location"
    ],
    "x-ms-secondary-file": true
  },
  "schema": {
    "$ref": "#/components/schemas/schemas:516"
  },
  "description": "URL to get status of this long-running operation."
}
```

**Comment by leni-msft** [comment]
@timotheeguerin Would you be able to take a look?

**Comment by timotheeguerin** [comment]
Hey @leni-msft I have a fix could you confirm it works for you https://github.com/Azure/autorest/pull/3886#issuecomment-780024531

**Comment by leni-msft** [comment]
@timotheeguerin cool! it works~. Thanks for the quick fix!

**Comment by tonianelope** [comment]
Hi am having a similar issue where I have the following definition see below: (RenamedExampleProperty is refrencing the definition of Example as it is the same property only with a different name). But the PR doesn't fix the issue for me. 
```
    "Language": {
      "description": "xxx",
      "allOf": [
        {
          "$ref": "#/definitions/CommonLanguageProperty"
        },
        {
          "type": "object",
          "properties": {
            "RemanedExampleProperty": {
              "$ref": "#/definitions/CommonExampleProperty/properties/Example"
            },
          },
        }
      ]
    },```

**Comment by timotheeguerin** [comment]
Hi @tonianelope could you open another issue with a swagger spec reproducing the erorr as this doesn't seem to be the exact same problem
