### ISSUE TITLE
[v3] Recording the input details in autorest

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest#3891]
There was request to the Typescript SDK Generator. The request is documented in the issue: https://github.com/Azure/autorest.typescript/issues/842. 

Basically, the ask is to document all the versions (Autorest Version/Modeler Version), tags, overrides, input file names(with commit ids),  and other customer input documented in a separate file. But most of that information is stripped out by the core and not available in the CodeModel. 

We could get some of that information by ```session.getValue('')```. But, the result object is not fixed (varies depending on the user input) and has several unrelated info. I think it would be a nice feature if we could create a more proper defined object in codemodel or session.

**Comment by timotheeguerin** [comment]
Hi @sarangan12, are you suggesting providing as part of the session a more define set of information that can be consumed?

**Comment by sarangan12** [comment]
Not as a part of codemodel. But as a part of session. such as ```session.userInput``` or ```session.inputConfig```

**Comment by qiaozha** [comment]
@sarangan12 @timotheeguerin hi, What's the conclusion of recording users autorest command input ?

**Comment by timotheeguerin** [comment]
Believe all the information needed is already provided by autorest, not sure what typescript generator is now doing with it.
