### ISSUE TITLE
Extra (unnecessary?) type generated when processing url encoded body swagger

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#3897]
**Describe the bug**

In [this PR](https://github.com/Azure/autorest.csharp/pull/1042) we found an extra type/class was generated: 

`Paths14Hl8BdFormsdataurlencodedPetAddPetidPostRequestbodyContentApplicationXWwwFormUrlencodedSchema` 

This was a minor annoyance for .NET, as we mark it internal, but might be more annoying for other languages.

[Swagger](https://github.com/Azure/autorest.testserver/blob/master/swagger/body-formdata-urlencoded.json)
[Generated File](https://github.com/Azure/autorest.csharp/blob/933d6149a3c30392cc6d0c36cd67611c686d34c5/test/TestServerProjects/body-formdata-urlencoded/Generated/Models/Paths14Hl8BdFormsdataurlencodedPetAddPetidPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.cs)

**Expected behavior**
@pakrym and I expected this type to be not added.

**Comment by timotheeguerin** [comment]
I think is this the same issue as #3668

**Comment by pakrym** [comment]
I don't think so. In that case, the schema is defined by the customer in the swagger. In this case, it's an artifact of the autorest transformations.

**Comment by timotheeguerin** [comment]
well it is arguable. In OpenAPI3 there is a schema like that

**Comment by pakrym** [comment]
I might be missing something. Can you refer to the openapi specification where it talks about explicitly defining schemas for urlencoded bodies?

**Comment by timotheeguerin** [comment]
As far as I understand in OpenApi3. You have a single entry for the schema `requestbody` and then you can define the schema per content type

https://swagger.io/docs/specification/describing-request-body/

**Comment by pakrym** [comment]
TIL. thank you
