### ISSUE TITLE
ISO8601 duration support needed for Azure.CSharp flavor

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#390]
@matthchr: Thanks for [your PR](https://github.com/Azure/autorest/pull/369) to add duration support to AutoRest!

There is one thing missing however. This code was added to the generic CSharp template:

    Converters = new List<JsonConverter> 
    { 
        new Iso8601TimeSpanConverter() 
    } 

But not to the [Azure.CSharp template](https://github.com/matthchr/autorest/blob/2872d6606f143d27c865e986efc45eb134df531c/AutoRest/Generators/CSharp/Azure.CSharp/Templates/AzureServiceClientTemplate.cshtml).

Is this in the works? We need it for the Azure Search .NET SDK.

**Comment by matthchr** [comment]
Good catch.  I had missed that in my initial PR.  I've got some other tests which I missed for Duration (nobody called me out on it in the initial PR but I realized later I didn't cover some cases).  If you're willing to wait till around the end of the week/early next week I can fix this along with adding my new tests.

If you can't wait that long it should be a pretty easy fix, you can submit a PR yourself probably.

Thanks!

**Comment by brjohnstmsft** [comment]
Seems like this would be good practice for me. :)  I'll follow up with you offline.
