### ISSUE TITLE
Unclear Realse Version

### ISSUE THREAD

**Issue by vkuehn** [Azure/autorest#3905]
Just found out about this project and it looks interesting.

However it is not clear which version to use as the only version labelt latest is from 2017.
What is the latest release to be used in production ?

**Comment by timotheeguerin** [comment]
Hi @vkuehn autorest is composed of many packages. You can look into the packages folder. The main package of intrest would be 

- `autorest` -> `packages/apps/autorest`  This is the cli 
- `@autiorest/core` -> `packages/extensions/core` This is the main orchestrator of the entire app
- `@autiorest/modelerfour` -> `packages/extensions/modelerfour` This is what convert openapi into a new model designed for SDK that can be consumed by generators 

For the specific language generator you can look for other github repo(add .[lanugage] in the repo name)
-  https://github.com/Azure/autorest.python
