### ISSUE TITLE
No Success with githubs own api

### ISSUE THREAD

**Issue by vkuehn** [Azure/autorest#3913]
**Describe the bug**
```
Please provide as much information as you can. This would be: 
- OpenAPI files having the issues
Tried all description I found in https://github.com/github/rest-api-description
 only the examples are working for me from  https://github.com/Azure/autorest.powershell
- Autorest command used e.g.
autorest --python --input-file:./ghes-3.0.yaml
autorest --powershell --input-file:./ghes-3.0.yaml
autorest --powershell --input-file:./api.github.com.yaml
```

**Expected behavior**
create the generated folder as in the examples
not many Syntax errors

**Additional context**
Tried on Windows 10 in Powershell 7.1 
Output starts with
AutoRest code generation utility [cli version: 3.1.1; node: v14.15.0, max-memory: 4096 MB]

**Comment by timotheeguerin** [comment]
Looking into this there seems to be a few issues causing autorest to crash
1. There is a component called `page-build` with a property called `status` and a component called `page-build-status`. Autorest normalize all schemas first and joins it in this format `ComponentName-propertyName` so it ends up being `page-build-status` here which conflict with the existing value. Will have to see what can be done for that. Though this could be worked around by renaming `build-page-status` to `BuildPageStatus` either manually or using an autorest directive
2. There is a `enum: [null]` which is not supported in autorest right now. You can remove this entry
3. Make sure to add `--modelerfour.lenient-model-deduplication` flag so it can generate model names sequentially for duplicates.

**Comment by vkuehn** [comment]
would it stay in the Backlog if I close the issue ?

**Comment by timotheeguerin** [comment]
It will stay in the millestone but as a closed issue.

**Comment by vkuehn** [comment]
okay as this has been not touched since ages. And I can't help as a lack of skill. It will be reopened if important to someone more active
