### ISSUE TITLE
linter gives wrong message for path syntax error

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest#3929]
**Describe the bug**
I was trying to generate a Swagger file that contained a syntax error. Specifically, the path did not start with `/`. However, instead, Autorest gave me the following error
```
ERROR: Schema violation: Additional properties not allowed: multivariate/models?$skip=0&$top=5 (x-ms-paths)
```
It took a long time to diagnose (thanks @lmazuel or I would probably still be pulling my hair out!). 

**Expected behavior**
It would be great if the linter called out the syntax error in the Swagger.

**Comment by timotheeguerin** [comment]
This one is interesting. the error comes from the json schema validator which expect properties to start with `x-` or `/` under `paths` hence the error when forgetting to start with `/`.

I guess we could remove this condition from the swagger JSON schema and maybe do the validation ourself(or just add some manual validation ourself first).

**Comment by timotheeguerin** [comment]
Been looking at what editor.swagger.com does and seems like they are using a different validator library that support custom messages so you can have errors like that. So I'll look into that
![image](https://user-images.githubusercontent.com/1031227/109194436-40029e80-774e-11eb-8759-3e0576a4af94.png)
