### ISSUE TITLE
"x-ms-parameterized-host" parameters don't respect "format" property

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#3948]
[Here](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L22) in this example I added `Endpoint` parameter for  `"x-ms-parameterized-host"`. [Here](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L94) I added `"format": "url"` for `Endpoint` but the generated [CodeModel.yaml](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L138-L156) is referencing [*ref_0](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L139) which is [StringSchema](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L7), it should respect the url format and reference to [UriSchema](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L66).

`"format": "url"` works fine for model properties, for example check `Code` property [here](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L64) and it is referencing the correct [UriSchema](https://github.com/ShivangiReja/autorest.csharp/blob/Test/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L56-L65).

**Comment by timotheeguerin** [comment]
Looking at how modlerfour handles `servers` variables(or `x-ms-parameterized-host`  parameters in swagger) it just seem to handle enums or it defaults as a string. Will look into that.

**Comment by timotheeguerin** [comment]
Hhm actually this is against the specs of OpenAPi3. It can either be a string or an enum as implemented https://swagger.io/docs/specification/api-host-and-base-path/
