### ISSUE TITLE
LRO spec documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3951]
We should have a more explicit doc about LRO behavior, that we can update as necessary to check if we do the expected thing.

Example: Just got a talk with @jhendrixMSFT about what happens if there is two status code and only one has a schema.

**Comment by jhendrixMSFT** [comment]
Here is the truth table per the discussion.

```
200 Foo / 20x Bar - we take Foo and display a warning
201 Foo / 202 Bar - this is a hard error (no 200)
200 void / 20x Bar - we take Bar
```

**Comment by timotheeguerin** [comment]
Test server LRO spec rewrite should cover this.
