### ISSUE TITLE
Modeler4 : TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3961]
**Describe the bug**
```
Please provide as much information as you can. This would be: 
- OpenAPI files having the issues
- Autorest command used
- npx autorest https://github.com/Azure/azure-rest-api-specs/blob/9ef8493edc35ee8ebf5f82799883f112f21a44ca/specification/compute/resource-manager/readme.md --tag=package-2020-12-01  --v3 --output-artifact:code-model-v4 --use:@autorest/modelerfour@latest --debug --modelerfour.lenient-model-deduplication 
```

**Expected behavior**

**Additional context**

**Comment by timotheeguerin** [comment]
@jianyexi which version of `@autorest/core` and `@autorest/modelerfour` are you using?

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE which version of `@autorest/core` and `@autorest/modelerfour` are you using?

'@autorest/core' (3.0.6374) , '@autorest/modelerfour' (4.16.2)

**Comment by timotheeguerin** [comment]
Could you try updating to @autorest/core `3.1.2` or reverting to `3.0.6371`?

**Comment by jianyexi** [comment]
> Could you try updating to @autorest/core `3.1.2` or reverting to `3.0.6371`?

Seems the M4 has  @autorest/core version binding? when I run the cmd it chooses the version 3.0.6375 , and there is still this error
```
PS C:\code> autorest --info
AutoRest code generation utility [cli version: 3.1.2; node: v12.16.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6371     C:\Users\jianyxi\.autorest\@autorest_core@3.0.6371
 core       @autorest/core                           3.0.6375     C:\Users\jianyxi\.autorest\@autorest_core@3.0.6375
 core       @autorest/core                           3.1.2        C:\Users\jianyxi\.autorest\@autorest_core@3.1.2
```

**Comment by timotheeguerin** [comment]
modelerfour shouldn't have any core version requirement. There might be something else defaulting to `~3.0.0`. How are you trying to set version `3.1.0`?
