### ISSUE TITLE
schema-validator-swagger failed if there is location header in response of example file

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest#3976]
**Describe the bug**
I meet below example error when running "autorest xxx\readme.md"
![image](https://user-images.githubusercontent.com/59815250/110723194-a14a6780-824e-11eb-88d8-353bdbabd8a6.png)

And I checked my example file finding that this error is come from below part of the example file:
![image](https://user-images.githubusercontent.com/59815250/110723418-fa1a0000-824e-11eb-95fb-d944912a173a.png)

If I remove the "location" header in the example file, the validator can get pass.

**Expected behavior**
1. Since location is a valid header in some operation, expect no errors reported for it.
2. Also would like to know the rule/schema for example files. Thanks!

**Additional context**

**Comment by timotheeguerin** [comment]
The error is not really helpful(will look into improving that), but the issue here is that it is expecting a url in the value

```json
 "headers": {
        "location": "https://foo.com"
      },
```

This works

**Comment by timotheeguerin** [comment]
The latest preview version actually shows better error messages
![image](https://user-images.githubusercontent.com/1031227/110820997-7e1aba80-8244-11eb-80a0-794b3987a721.png)

**Comment by changlong-liu** [comment]
Thank you @timotheeguerin !
