### ISSUE TITLE
Can we detect Paths with parameters not defined in parameters list below and error our before hitting language specific generators

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#3991]
Originally from:

https://github.com/Azure/autorest.csharp/issues/1083

> On this input file: https://github.com/Azure/azure-sdk-for-js/blob/8642ffaf0354502860d31b4b07a506299cbed3f4/sdk/containerregistry/container-registry/swagger/containerregistry.json

> The C# code generator fails with the error below. The JS generator succeeds on the same swagger file.

>So, it looks like what was crashing the C# generator was this line:
https://github.com/Azure/azure-sdk-for-js/blob/8642ffaf0354502860d31b4b07a506299cbed3f4/sdk/containerregistry/container-registry/swagger/containerregistry.json#L929

>It was referring to a reference input parameter that wasn't defined in the parameters list below.

This feels like something m4 should be able to detect and error out, as it's an invalid swagger definition.

**Comment by timotheeguerin** [comment]
I see, having something similar to what editor.swagger.io do
![image](https://user-images.githubusercontent.com/1031227/111493255-9f731f00-86fa-11eb-8f50-3535481a492f.png)
