### ISSUE TITLE
Question about autorest v3 and v2

### ISSUE THREAD

**Issue by yifan-zhou922** [Azure/autorest#4000]
Hi, I want to ask whether autorest v3 is compatible with v2. If not, what are the new features? 
I am from the Purview Catalog Team. Our swagger now supports autorest@v2 but not autorest@v3. So I want to investigate the reasons why autorest@v3 only generates parts of the SDK codes, not the complete SDK. 
Many thanks in advance.

**Comment by timotheeguerin** [comment]
v3 should be taking the same inputs as v2, it is a change on how it works internally to call plugins/generators. The generators v3 however will have some difference to v2. The first one being a different set of core library is being imported (`Azure.Core` ). 

If v3 is not generating as you'd expect please open an issue with those details.
