### ISSUE TITLE
Add ContentType parameter when there is a same set of parameters for a operation which differs by content type

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#4002]
If we take below swagger as an example it generates two same set of parameters for `OperationModel` operation which only differs by Content-Type(`application/json` and `application/octet-stream`), so instead of generating two same set of parameters, can we generate only one set of parameters and add ContentType parameter? so that it can resolve the method signature conflict.

```
{
    "swagger": "2.0",
    "info": {
        "title": "Test swagger",
        "description": "Test swagger",
        "version": "1.0.0"
    },
    "schemes": [
        "http"
    ],
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json",
        "application/octet-stream"
    ],
    "paths": {
        "/op": {
            "get": {
                "operationId": "OperationModel",
                "description": "",
                "parameters": [
                    {
                        "name": "value",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "format": "binary",
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}
```

**Comment by timotheeguerin** [comment]
Looking at this, m4 will corectly add the content-type parameter if there is multiple binary content types and group those under 1 method, the issue here is if you have binary + json content types(with a binary body) but I think this is the same problem if you have 2 different content types regardless of the schema of the body.(Server could accept xml and json)

**Comment by ShivangiReja** [comment]
@timotheeguerin I don't think there is a problem if we have multiple content types, for example if we have "text/plain" and "application/octet-stream" content types for a single operation then it would generate 2 different sets of parameters i.e. text and binary and in this case there will be no conflict of method singatures.

**Comment by timotheeguerin** [comment]
Yeah I guess it isn't an issue because right now if you have both `json` and `xml` content type it ignores `xml`
