### ISSUE TITLE
profile initialized as an empty array causing it fail to get !$(profile) configuration 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest#4013]
Originally created here https://github.com/Azure/autorest.typescript/issues/880 

This cause typescript can't generate track2 SDK for resources RP without manually remove the !$(profile) yaml condition.

**Comment by qiaozha** [comment]
@timotheeguerin @joheredi

**Comment by timotheeguerin** [comment]
I think moving `--profile` to be an array was done as some work for multi api support where you'd be able to define a list of api you want to include. As this was disabled a long time ago I think we should be fine keeping profile as a single value.  I have a pr changing that. Can you test that https://github.com/Azure/autorest/pull/4015 and confirm if this works

**Comment by timotheeguerin** [comment]
So talked with Laurent about this issue and the thing is `profile` is an autorest v3 reserved configuration  for built-in multi-api version(It is disabled now but could be enabled in the future).

Recommendation is to change the name of profile to something else that is not reserved.

**Comment by qiaozha** [comment]
I thought we are going to use  batch for  multi-api ?

**Comment by timotheeguerin** [comment]
Autorest has this logic to define some profile and filter  api version and only certain operations/resources. For that `profiles` and `profile` are reserved.

**Comment by qiaozha** [comment]
Just curious, in the multi-api scenario, Are you going to have something like min api, max api, as long as the version or version range defined in the profile within the min api and max api, then this operation/schema will show up in this profile ? 
Also, we still need to handle non multi-api cases even if multi-api is supported in the future.  I wonder what should we do to indicate some part are non multi-api ?

**Comment by timotheeguerin** [comment]
This logic was added early in autorest v3 design, it was shown problematic in its current design so it was disabled. There is no fixed plans to bring this back yet but those config keys will remain reserved for that potential come back.

**Comment by qiaozha** [comment]
I see
