### ISSUE TITLE
Access to .exe

### ISSUE THREAD

**Issue by RonFrick** [Azure/autorest#402]
Hello, I just wanted to say how awesome this project is. I also wanted to see if someone could simply provide me with a zip file that contains the actual .exe file so I can generate some code. I was able to get the master branch to build but not the dev version. I need a fix that is only in the dev version so if someone could please provide a link (drop box, one drive etc.) with the exe that would be amazing. 

Thanks so much!

**Comment by rosoft2001** [comment]
+1

**Comment by yugangw-msft** [comment]
@RonFrick, we publish out autorest nuget package every day to myget. You can download any version you like from the below link. Unzip it and you will see autorest.exe under tools folder. 
https://www.myget.org/feed/autorest/package/nuget/autorest
