### ISSUE TITLE
 TypeError: pathOrUri.startsWith is not a function

### ISSUE THREAD

**Issue by darkoa-msft** [Azure/autorest#4027]
**Describe the bug**
I haven't used autorest in a while, installed the latest, failed to run Azure validator.
Tried resetting, installing previous, uninstalling, nothing helps.
Windows 10, both VS Dev and bash terminal windows.

```
$ autorest --azure-validator --input-file <path_to_swagger.json> --verbose
AutoRest code generation utility [cli version: 3.1.3; node: v12.16.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'D:\Users\Darko\.autorest\@autorest_core@3.2.1\node_modules\@autorest\core\dist' (3.2.1)
  TypeError: pathOrUri.startsWith is not a function

```

**Expected behavior**
autorest should check the swagger

**Additional context**
autorest fails with the above error

**Comment by timotheeguerin** [comment]
Hi @darkoa, could you try running with the `--debug` flag as well to get the stacktrace?

Could you also try runnning `autorest --reset` then running your command again to check if this is still hapennening.

**Comment by darkoa-msft** [comment]
Well, I guess we have more info now :)
```
$ autorest --azure-validator --input-file <swagger.json> --debug
AutoRest code generation utility [cli version: 3.1.3; node: v12.16.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from D:\Users\Darko\.autorest\@autorest_core@3.2.1
   Loading AutoRest core      'D:\Users\Darko\.autorest\@autorest_core@3.2.1\node_modules\@autorest\core\dist' (3.2.1)
  TypeError: pathOrUri.startsWith is not a function
[0.65 s] Shutting Down.
[0.65 s] Exiting.
```

**Comment by timotheeguerin** [comment]
Do you have a space between `--input-file` and the swagger file? `autorest` args format needs to be `--arg=value` or `--arg:value`

**Comment by darkoa-msft** [comment]
That is embarrassing - yes, I used a space.
Thanks for the help :)
