### ISSUE TITLE
[Research] Bundling autorest and dependencies in self contained package

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4048]
**Is your feature request related to a problem? Please describe.**

In discussions with @KrzysztofCwalina the lack of self-contained'ness of autorest.csharp (and implicitly autorest core) was raised. 

You need npm installed, along with node, and for those who occasionally run things (or customers) this can be annoying to setup.

We could look into bundling all of autorest's dependencies in a self contained bundle that the backends add their respective plugins to.

I'm no JS expert, but I've seen other applications ship node within their application folder.

**Describe the solution you'd like**
Look into the costs and benefits of shipping autorest as a self-contained tool.

**Describe alternatives you've considered**
The alternative is to keep the status quo.

**Additional context**
FYI @lmazuel

**Comment by timotheeguerin** [comment]
This is a tricky problem here, there is a lot of potential dependencies and this create a large matrix of conditions, how many packages do we deploy
- Each platform(windows, linux, osx)
- Different plugin needs different requirements(those would need to be kept somewhat up to date)
   - CSharp -> dotnet
   - typescript, golang -> nodejs
   - Java -> jdk
   - Swift -> swift

- Need an update for each version of core?
- Are the plugins bundled too? Don't see this maintainable with all the versions 

So we'd have to create some sort of installer that contains all those dependencies.

There is a task in the backlog to republish to docker hub #3452 which would solve his problem at a lower cost(but requires docker).

Another options is just to package autorest cli  to an executable. Each plugin might still need their requirements(dotnet, etc.) but if you don't need nodejs for one of the plugins then you might save on this.

**Comment by kant2002** [comment]
As external to MS party, I would like to keep temporary status quo, since Autorest would benefit greatly from stabilisation of what it currently have. Sometimes if you update autorest, and have something slightly non-standard it stops working, and I have to find working combination of extensions + core.

Right now system is somewhat hackable, but if introduce publishing, it will diver resources from quality. At least given current state of staffig, and appears to be large test matrix, separate executable can make problem worse.

**Comment by kjacobsen** [comment]
As a PowerShell developer who wants to be able to easily generate modules based off an API, I really don't want to install node etc. A (up-to-date) Docker image would be perfect!

**Comment by timotheeguerin** [comment]
Docker images were brought back https://github.com/Azure/autorest/blob/main/docs/docker.md
