### ISSUE TITLE
Autorest 3.1.* fails to generate SDK saying "produces: [contnet-type]" is not available, but it is present.

### ISSUE THREAD

**Issue by jviau** [Azure/autorest#4056]
**Describe the bug**

Running autorest against our API spec we have encountered an issue upgrading to Autorest 3.1.

Command used:
```
autorest readme.md --csharp --csharp-sdks-folder=../../CSharp/ --target=Api.Labs --nsversion=v2020_05_01_preview --typescript-sdks-folder=../../TypeScript --typescript
```

Autorest 3.0.6339, no problem.
Autorest 3.1.* - errors out with 
```
 Error: Operation response '/paths/~1api~1subscriptions~1{subscriptionId}~1coreUsage/get/responses/200' produces type couldn't be resolved. Operation is probably is missing a produces field and there isn't any global value. Please add "produces": [<contentType>]"
```

Our top-level input yaml file includes this line near the top, so it is a global value:

```yaml
produces: [application/json]
```

**Expected behavior**
SDK generates successfully.

**Comment by timotheeguerin** [comment]
This validation was added recently to prevent a failure latter in the pipeline when it couldn't resolve the . Could you share the entire spec or a spec that reproduce?

**Comment by jviau** [comment]
@timotheeguerin helped me understand the issue offline. In v3 all of the input files need to declare `produces` - not just the top level one.
