### ISSUE TITLE
Hard to remove leftover of temporary files

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#4057]
**Describe the bug**
Normal operations of running autorest produce files with 3 dots in names. These files is extremely hard to remove using Windows explorer.
For example: 
- C:\Users\user\AppData\Local\Temp\autorest-jv97C5\mem-135-merged-20oai3-20doc...
- C:\Users\user\AppData\Local\Temp\autorest-jv97C5\mem-138-composed-20oai3-20doc...

**Expected behavior**
Change names for the temp files.

**Comment by timotheeguerin** [comment]
Can't you just delete the folders starting with `autorest-`?

**Comment by kant2002** [comment]
only from command line. and since all of them in separate folders, it's annoying to remove. Not even rename allowed. Issue probably related to extension-less files creation in Explorer where you have to put . in the end of file, but not sure.

**Comment by timotheeguerin** [comment]
So we actually have a `autorest --clear-temp` flag that lets you do just that.
