### ISSUE TITLE
FAIL src/json-path/json-path.test.ts 

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#4063]
**Describe the bug**
Run `rush test:ci`

```
==[ @azure-tools/datastore ]======================================[ 2 of 19 ]==
FAIL src/json-path/json-path.test.ts
  ● Test suite failed to run

    src/json-path/json-path.ts:6:31 - error TS2307: Cannot find module '@azure-tools/codegen' or its corresponding type declarations.

    6 import { createSandbox } from "@azure-tools/codegen";
                                    ~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kant2002** [comment]
It run successfully if I run `rush build` before running `rush test:ci` on fresh repository. Let you guys decide if this is bug, or expected. Was confused by fact that tests start running at all.

**Comment by kant2002** [comment]
Actually after I run second time, it fails, but later

```
--[ FAILURE: autorest ]----------------------------[ 2 minutes 12.3 seconds ]--

PASS test/basic-test.test.ts (7.562 s)
  Hello
    √ works (6 ms)

FAIL test/args.test.ts (8.846 s)
  Args
    √ defaults to undefined (3 ms)
    √ parse flags (1 ms)
    √ parse flags with explicity value=true
    √ parse flags with explicity value:true (1 ms)
  ...21 lines omitted...
      49 |     );
      50 |   });

      at Object.<anonymous> (test/args.test.ts:47:85)
```

**Comment by kant2002** [comment]
```
  ● Args › parse args with ~ path

    expect(received).toEqual(expected) // deep equality

    Expected: "C:\\Users\\user\\path\\to\\folder"
    Received: "C:\\Users\\user/path/to/folder"
```

**Comment by kant2002** [comment]
Issue on Windows due to fact that package https://github.com/sindresorhus/untildify/blob/main/index.js#L11 do not bother use `path.join` and manually replace `~` with `homedir`. So on Windows that fails,

Is there any place where this smallish function can be placed, so you do not depend on the external party. it is used only in 4 places.

Aargh. I see that you trying to solve something here https://github.com/Azure/autorest/commit/a3c85f5aecc58057a9e44574359940b1a0279b16

Sigh. Have to wait for tomorrow then.

**Comment by timotheeguerin** [comment]
Yeah you need to run build before test. It needs the other packages to be build

**Comment by timotheeguerin** [comment]
for the path error, it does indeed seem to not be consistent with what it returns on windows. This should be an easy fix in the test if you want to look at it.

**Comment by kant2002** [comment]
> Yeah you need to run build before test. It needs the other packages to be build

Yeah, I got it.

@timotheeguerin do you want me fix the test? Or are you up to get rid of `untidify` and bring that function with fix directly in the source code. It would introduce some sort of code duplication, but IMO that can be a small price for that stuff.

**Comment by timotheeguerin** [comment]
I don't think there is an issue with untidify but just with the test. The expect should add a join() so just make sure both the expect and actual are normalized to the same file separator.

**Comment by kant2002** [comment]
Look here. `path.join`already there

https://github.com/Azure/autorest/blob/44c110ad8311c72ed3e6764c0a8fa5e5c9961df3/packages/apps/autorest/test/args.test.ts#L46-L50

And whole untildify is just glorified regex without any account for Windows platform.

https://github.com/sindresorhus/untildify/blob/80bef741d185b9e98165a5ba78bc6802395c80b9/index.js#L10-L11

**Comment by kant2002** [comment]
@timotheeguerin you actually broke test, just to silence it. It give correct error reporting, since `untildify` simply does not attempt to normalise path on Windows and thus produce incorrect results. That `path` call should be inside `untildify`.
