### ISSUE TITLE
Troubleshooting guide has missing links to Java guide

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#4070]
On the page https://github.com/Azure/autorest.java/tree/v4/docs/troubleshooting.md

All 2 links to Java troubleshooting guide do not works. These links lead to https://github.com/Azure/autorest.java/tree/v4/docs/troubleshooting.md and file `docs/troubleshooting.md` not present at all in the https://github.com/Azure/autorest.java repo on v4 branch.

Not sure should links to be removed, or troubleshooting guide page should be created.

**Comment by timotheeguerin** [comment]
Believe its missing /client/ in the name https://github.com/Azure/autorest.java/blob/v4/docs/client/troubleshooting.md

**Comment by kant2002** [comment]
I saw that. From my understanding, this is for troubleshooting of the generated code, not for the generation process itself.
