### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Olgaian** [Azure/autorest#4089]
Seems hitting out of memory for bigger swaggers,: network, apimanagement and sql.

Sample run:

> Executing: autorest.cmd --use=c:\tools\src\autorest.azureuxtypes --azureresourceschema --output-folder=C:\types/network --multiapi --title=none c:\gittemp\azure-rest-api-specs\specification\network\resource-manager\readme.md

Log:

> 2021-04-19T22:36:52.8234497Z <--- Last few GCs --->
> 2021-04-19T22:36:52.8234779Z 
> 2021-04-19T22:36:52.8235317Z [968:00000286FB3F5990]   609878 ms: Mark-sweep 2037.1 (2062.2) -> 2030.6 (2063.7) MB, 1585.8 / 0.0 ms  (average mu = 0.105, current mu = 0.010) allocation failure scavenge might not succeed
> 2021-04-19T22:36:52.8236425Z [968:00000286FB3F5990]   611500 ms: Mark-sweep 2038.7 (2063.7) -> 2032.3 (2065.5) MB, 1605.8 / 0.0 ms  (average mu = 0.058, current mu = 0.010) allocation failure scavenge might not succeed
> 2021-04-19T22:36:52.8236926Z 
> 2021-04-19T22:36:52.8237017Z 
> 2021-04-19T22:36:52.8237322Z <--- JS stacktrace --->
> 2021-04-19T22:36:52.8237443Z 
> 2021-04-19T22:36:52.8237882Z FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 2021-04-19T22:36:53.1552607Z  1: 00007FF7CBF3046F napi_wrap+109311
> 2021-04-19T22:36:53.1553844Z  2: 00007FF7CBED5156 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+33302
> 2021-04-19T22:36:53.1554546Z  3: 00007FF7CBED5F26 node::OnFatalError+294
> 2021-04-19T22:36:53.1555199Z  4: 00007FF7CC7A2B4E v8::Isolate::ReportExternalAllocationLimitReached+94
> 2021-04-19T22:36:53.1555748Z  5: 00007FF7CC78792D v8::SharedArrayBuffer::Externalize+781
> 2021-04-19T22:36:53.1556360Z  6: 00007FF7CC631CCC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
> 2021-04-19T22:36:53.1556961Z  7: 00007FF7CC63D04A v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
> 2021-04-19T22:36:53.1557569Z  8: 00007FF7CC63A1F9 v8::internal::Heap::PageFlagsAreConsistent+2457
> 2021-04-19T22:36:53.1558114Z  9: 00007FF7CC62EDE1 v8::internal::Heap::CollectGarbage+2033
> 2021-04-19T22:36:53.1558664Z 10: 00007FF7CC62D005 v8::internal::Heap::AllocateExternalBackingStore+1317
> 2021-04-19T22:36:53.1559269Z 11: 00007FF7CC647166 v8::internal::Factory::AllocateRaw+166
> 2021-04-19T22:36:53.1559858Z 12: 00007FF7CC65AB44 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller+84
> 2021-04-19T22:36:53.1560529Z 13: 00007FF7CC64F039 v8::internal::Factory::NewJSArrayStorage+201
> 2021-04-19T22:36:53.1561061Z 14: 00007FF7CC64E686 v8::internal::Factory::NewJSArray+150
> 2021-04-19T22:36:53.1561732Z 15: 00007FF7CC50BB85 v8::internal::FeedbackNexus::ic_state+59285
> 2021-04-19T22:36:53.1562361Z 16: 00007FF7CC74B735 v8::internal::Builtins::builtin_handle+303781
> 2021-04-19T22:36:53.1562974Z 17: 00007FF7CC7493E6 v8::internal::Builtins::builtin_handle+294742
> 2021-04-19T22:36:53.1563576Z 18: 00007FF7CC748E23 v8::internal::Builtins::builtin_handle+293267
> 2021-04-19T22:36:53.1564139Z 19: 00007FF7CC82B5ED v8::internal::SetupIsolateDelegate::SetupHeap+464173
> 2021-04-19T22:36:53.1564663Z 20: 0000037756DAF89E 
> 2021-04-19T22:36:53.5201707Z Exited with code 134

**Comment by timotheeguerin** [comment]
I don't really seem to be able to reproduce, do you have more information in the logs? Can you get the full logs with `--debug --verbose`? I see you use multiapi, is it always failing during a specific tag? Is that tag failing by itself?

**Comment by anthony-c-martin** [comment]
I'm hitting the same issue in the Bicep type generator, which this code was forked from. Will get you a `--debug` & `--verbose` log soon.

Adding repro notes for my own purposes:
* Clone https://github.com/Azure/bicep-types-az/
* `get checkout typescript`
* `cd src/autorest.bicep`
* `npm ci`
* `npm run build`
* `cd src/generator`
* `npm ci`
* `npm run generate -- --specs-dir <path_to_azure_rest_api_specs_repo> --single-path network --verbose`
