### ISSUE TITLE
Consider erroring loudly on node < 14

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4090]
We've had a number of internal uses crash or have incorrect behavior with node 10 installed.

Could we bump the node check to yell if < 14?

**Comment by chamons** [comment]
cc @timotheeguerin

**Comment by timotheeguerin** [comment]
Node 10+ is meant to be supported, what errors have you seen?

**Comment by timotheeguerin** [comment]
Seems to be saving the files in the wrong location for some reason
![image](https://user-images.githubusercontent.com/1031227/115445531-d4c3ce80-a1ca-11eb-980b-e9d1a6b905ea.png)

**Comment by timotheeguerin** [comment]
Ok so actually this was a bug in an older version of node 10 https://github.com/nodejs/node/issues/25265, using the latest node 10 resolve it. Have to figure out which version this was solved.
