### ISSUE TITLE
`rename-property` actually changes the expected model and not the generated client name

### ISSUE THREAD

**Issue by heaths** [Azure/autorest#4095]
According to [documentation](https://github.com/Azure/autorest/blob/9243ef7a4484e444958253e5ee94f2c926f46f31/docs/generate/built-in-directives.md#rename-property), the `rename-property` directive renames a property. When using it, though, I see it actually changes the generated code (at least for C#, but I suspect this happens lower-level in AutoRest itself) to actually check for that property name in the JSON payload.

If that is indeed the case (and really too late to change it anyway), the documentation should state this clearly.

In addition, it would be great to have a macro set the client name instead, like `rename-client-property` with a similar pattern. For now we can use a transform to set the `x-ms-client-name` but this is more involved and could be simpler.

**Comment by timotheeguerin** [comment]
Hi @heaths, `rename-property` rename the property itself as it should. I guess this can be confusing as the other built-in reference things that are only relevant on the sdk side(Model name, operationid, etc.). I'll add a note to the docs to make this clearer.

For the rename-client-property, I am not sure this is worth adding, reason those built-in directives exists are to simplify complex directives. Just setting or changing the sdk name is straightforward with existing directives:

```
directive:
  - where-model: NameOfModel
    transform: $.MyProperty["x-ms-client-name"] = "MyClientName"
```
