### ISSUE TITLE
Duplicate operation 'Get' detected

### ISSUE THREAD

**Issue by clay-xianlan** [Azure/autorest#4112]
hi,I am having problems after updating autorest, can you help me out? Thank you!

Duplicate Operation 'Get' 

`C:\Code>autorest --input-file=beta.json --csharp --verbose
AutoRest code generation utility [cli version: 3.2.0; node: v14.15.0, max-memory
: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
No configuration found at 'file:///C:/Code/'.
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/default-configuration.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/inspect.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/directives.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/pipeline.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/loader-openapi.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/miscellaneous.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/patches.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-powershell.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-azureresourceschema.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-csharp.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-go.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-java.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-nodejs.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-php.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-python.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-ruby.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-typescript.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-validators.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-az.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-terraform.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/plugin-azure-functions.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/graphs.md'
> Including configuration file 'file:///C:/Users/Administrator/AppData/Roaming/n
pm/node_modules/autorest/dist/resources/help-configuration.md'
> Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210504.2)
> Including extension configuration file 'file:///C:/Users/Administrator/.autore
st/@autorest_csharp@3.0.0-beta.20210504.2/node_modules/@autorest/csharp/readme.m
d'
> Including configuration file 'file:///C:/Users/Administrator/.autorest/@autore
st_csharp@3.0.0-beta.20210504.2/node_modules/@autorest/csharp/readme.md'
> Loading AutoRest extension '@autorest/modelerfour' (4.19.0->4.19.0)
> Including extension configuration file 'file:///C:/Users/Administrator/.autore
st/@autorest_modelerfour@4.19.0/node_modules/@autorest/modelerfour/readme.md'
> Including configuration file 'file:///C:/Users/Administrator/.autorest/@autore
st_modelerfour@4.19.0/node_modules/@autorest/modelerfour/readme.md'
NOTE: AutoRest core version selected from configuration: ~3.1.0.
   Loading AutoRest core      'C:\Users\Administrator\.autorest\@autorest_core@3
.1.3\node_modules\@autorest\core\dist' (3.1.3)
VERBOSE [0.73 s]: No configuration found at 'file:///C:/Code/'.
VERBOSE [0.74 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/default-co
nfiguration.md'
VERBOSE [0.77 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/inspect.md
'
VERBOSE [0.79 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/directives
.md'
VERBOSE [0.81 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/pipeline.m
d'
VERBOSE [0.83 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/loader-ope
napi.md'
VERBOSE [0.84 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/miscellane
ous.md'
VERBOSE [0.87 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/patches.md
'
VERBOSE [0.89 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-pow
ershell.md'
VERBOSE [0.92 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-azu
reresourceschema.md'
VERBOSE [0.93 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-csh
arp.md'
VERBOSE [0.95 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-go.
md'
VERBOSE [0.97 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-jav
a.md'
VERBOSE [0.99 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-nod
ejs.md'
VERBOSE [1.01 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-php
.md'
VERBOSE [1.03 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-pyt
hon.md'
VERBOSE [1.05 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-rub
y.md'
VERBOSE [1.07 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-typ
escript.md'
VERBOSE [1.1 s]: > Including configuration file 'file:///C:/Users/Administrator/
.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-vali
dators.md'
VERBOSE [1.13 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-az.
md'
VERBOSE [1.15 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-ter
raform.md'
VERBOSE [1.18 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-azu
re-functions.md'
VERBOSE [1.21 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/graphs.md'

VERBOSE [1.25 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/help-confi
guration.md'
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta
.20210504.2)
VERBOSE [1.88 s]: > Including extension configuration file 'file:///C:/Users/Adm
inistrator/.autorest/@autorest_csharp@3.0.0-beta.20210504.2/node_modules/@autore
st/csharp/readme.md'
VERBOSE [1.88 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_csharp@3.0.0-beta.20210504.2/node_modules/@autorest/csharp/
readme.md'
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.0->4.19.
0)
VERBOSE [2.01 s]: > Including extension configuration file 'file:///C:/Users/Adm
inistrator/.autorest/@autorest_modelerfour@4.19.0/node_modules/@autorest/modeler
four/readme.md'
VERBOSE [2.01 s]: > Including configuration file 'file:///C:/Users/Administrator
/.autorest/@autorest_modelerfour@4.19.0/node_modules/@autorest/modelerfour/readm
e.md'
VERBOSE [3.15 s]: Reading OpenAPI 2.0 file file:///C:/Code/beta.json

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this c
ould take a (long) while.  Run with --verbose for more detail.
VERBOSE [7.64 s]: Found and removed 0 duplicate schema
VERBOSE [8.42 s]:   ModelerFour/api-version-mode:client
VERBOSE [8.43 s]:   ModelerFour/api-version-parameter:constant
VERBOSE [8.43 s]:   ModelerFour/use-model-namespace:false

ERROR (): Duplicate Operation 'Get' detected.
FATAL: Error: 1 errors occured -- cannot continue.
  Error: Plugin checker reported failure.`

**Comment by timotheeguerin** [comment]
Hi @clay-xianlan that means you have 2 operations with the same `operationId` (Get) or if it doesn't have operationId the tag names are the same.
