### ISSUE TITLE
x-ms-secret missing from readme

### ISSUE THREAD

**Issue by mentat9** [Azure/autorest#4115]
**Describe the bug**
Extension for x-ms-secret is undocumented

**Expected behavior**
Readme should include documentation for x-ms-secret along with the other extensions.

**Additional context**
N/A

**Comment by timotheeguerin** [comment]
Hey @mentat9 where have you seen this extension being referenced? autorest core itself doesn't any use for it

**Comment by mentat9** [comment]
This extension is used in in many Azure RP swaggers, e.g. Microsoft.ApiManagement, Microsoft.Botservice, Microsoft.ContainerRegistry, Microsoft.DocumentDB, etc. It's needed to flag secrets in ARM APIs and has been in use for well over a year.

**Comment by timotheeguerin** [comment]
`x-ms-secret` isn't supported  right now in autorest nor the generators. This was a tentative to solve logging secrets but this was resolved differently. Not sure why so many RP still have that as it does nothing during the generation. 
Where do you see this being a needed flag?

**Comment by mentat9** [comment]
I know that ARM What-If relies on it to ensure handling secrets correctly. ARM Policy also uses it to provide correct metadata on aliases. There may well be others. SDK generation is far from the only consumer of swagger files.

**Comment by lmazuel** [comment]
Hi @mentat9 I don't deny at all that SDK is not the only consumer of Swagger :). Though you open this issue on the autorest repo, which is mostly about SDK generation. I have 0 context on what this is about, so even if I would want to document it, I wouldn't know where to start :)

This might be something that should go on the azure-rest-api-spec repo doc if it's not used by any autorest tooling.

CC @johanste

**Comment by anthony-c-martin** [comment]
As part of this documentation, it would also be good to specify how this extension is expected to interact with `x-ms-mutability` and `readonly` properties.

In the context of the ARM control plane, we wouldn't expect a field marked `"x-ms-mutability: ["read"]` to also specify `"x-ms-secret": true`. However, IMO it feels like the two extensions serve semantically different purposes, and shouldn't prevent setting both, or use `x-ms-secret` to infer anything about mutability.

**Comment by majastrz** [comment]
IIRC The autorest team was involved in the original discussions around `x-ms-secret` (@fearthecowboy). So I'm confused why there's pushback about documenting it now. It is also news to me that it's a temporary solution.

**Comment by timotheeguerin** [comment]
fixed by https://github.com/Azure/autorest/pull/4365
