### ISSUE TITLE
invalid flag input should return error instead of being ignored

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest#4130]
**Describe the bug**

- Run `autorest --input-file=xxx.json -go`, and it will return success like below.
```
AutoRest code generation utility [cli version: 3.2.0; node: v14.16.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\xxx\.autorest\@autorest_core@3.4.1\node_modules\@autorest\core\dist' (3.4.1)
[1.94 s] Generation Complete
```

- The correct input should be `autorest --input-file=xxx.json --go`, and it will successfully generate the codes.

```
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\xxx\.autorest\@microsoft.azure_autorest-core@2.0.4419\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4419)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47->2.1.181)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
```
- Furthermore, I found that any invalid input flag like `--gogo` can result in the same false success.

**Expected behavior**

Invalid flag input should trigger and error.

**Additional context**

A better experience is that we can accept `-go` as an alias of `--go`.

**Comment by timotheeguerin** [comment]
Hey @archerzz,
This is on purpose, autorest is very flexible with its configuration. User can provide custom flags for use in their configuration so we unfortunately cannot fail on unknown flags. 
For supporting `-go`, this would go against the GNU convention for flags where it should mean the same as `-g` `-o`.
