### ISSUE TITLE
Security should include "anonymous auth" along side key and token

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4135]
In https://github.com/Azure/autorest.csharp/pull/1128 we are defining a "unauthed" case for some SDKs that want a anonymous auth by leaving it blank.

Maybe we should promote that to a named concept?

cc - @timbasham  @pakrym

**Comment by timotheeguerin** [comment]
What is the difference with not specifying any security model or `security` flags in the config? 
Is it that you want to allow anonymous authentication but also a security scheme?

**Comment by timotheeguerin** [comment]
Seems like we could achieve this 

In openapi document
```yaml
security:
  - {}
  - AADToken: ["https://foo.com"]
```

In configuration
```yaml
security:
  - Anonymous
  - AADToken
```

**Comment by chamons** [comment]
Right now I'm assuming nothing = un auth for LLC, but I think it'd be better to be explicit that I really wanted that instead of being implicit.
