### ISSUE TITLE
what's the behavior of readonly alongside the "$ref"

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4136]
Before asking the question:
- [ ] have you checked the documentation in the [docs folder(https://github.com/Azure/autorest/tree/master/docs) and couldn't find the information there
- [ ] have you checked existing issues for a similar question?

For example 
```
  House:
    readOnly: true
    $ref: '#/definitions/MyHouse'
```
Will this readonly  be ignored ?

**Comment by timotheeguerin** [comment]
`readonly` next to a $ref that is  property should mark the property as readonly(same for nullable)
https://github.com/Azure/autorest/blob/master/packages/extensions/modelerfour/src/modeler/modelerfour.ts#L857

**Comment by timotheeguerin** [comment]
Forgot too I wrote some docs for all those properties https://github.com/Azure/autorest/blob/master/docs/openapi/howto/$ref-siblings.md
