### ISSUE TITLE
additionalProperties: true and additionalProperties: {} should be equivalent

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4138]
**Describe the bug**
It would appear that additionalProperties: true is not equivalent to additionalProperties: {}.  The former treats the dictionary value as SchemaType.AnyObject, latter doesn’t.

**Expected behavior**
Per swagger spec the two should be equivalent and create SchemaType.Any

**Additional context**
autorest --use=\git\Azure\autorest.go --license-header=MICROSOFT_MIT_NO_VERSION --file-prefix="zz_generated_" --input-file=\git\Azure\autorest.go\src\node_modules\@microsoft.azure\autorest.testserver\swagger\additionalProperties.json --output-folder=\git\Azure\autorest.go\test\autorest\additionalpropsgroup --head-as-boolean=true

M4 version 4.19.1

**Comment by timotheeguerin** [comment]
Seems to be a directive somewhere converting this 
![image](https://user-images.githubusercontent.com/1031227/118860733-99332780-b890-11eb-89af-a3468149ffa8.png)
