### ISSUE TITLE
PowerShell Support

### ISSUE THREAD

**Issue by kjacobsen** [Azure/autorest#4143]
Before asking the question:
- [X] have you checked the documentation in the [docs folder(https://github.com/Azure/autorest/tree/master/docs) and couldn't find the information there
- [X] have you checked existing issues for a similar question?

What is the current state of PowerShell support? There are almost no mentions of PowerShell generation in the docs.

**Comment by timotheeguerin** [comment]
Hi @kjacobsen, it is supported.
You can see the powershell docs on the powershell generator repo https://github.com/Azure/autorest.powershell/blob/master/docs/readme.md

Not sure why its missing from the readme table, I'll make a fix for that.
