### ISSUE TITLE
Required properties

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest#4157]
This was closed in 2015. But TypeScript is different now in a way where it's worth revisiting.
https://github.com/Azure/autorest/issues/219

The argument that was used there was:
> This was done on purpose. Having nullable primitive types everywhere simplifies logic for PATCH like operations and null validation. Additionally having primitive types in the response insures that deserialization does not throw when the data is missing on the wire (e.g. server changed the field to be nullable but the client was not regenerated with the latest swagger spec).

However, handling things like `PATCH` can be done in TypeScript by wrapping the type in a `Partial<T>`. And in other languages, it should be possible to generate a patch-version of the type as well as a general type.

So we have (for instance in C# with non-nullable reference types):
```csharp
class MyRequest {
  public string Name {get;set;} = null!;
}

class MyRequestPatch {
  public string? Name {get;set;}
}
```

The value add of this is huge. We can catch validation errors at compile time, not runtime.

Related: https://github.com/Azure/autorest.typescript/issues/994

**Comment by timotheeguerin** [comment]
Hey @ffMathy, I think this is up to the typescript generator to change how they generate the models(and your other issue should cover that). Is there something you think autorest itself is doing wrong?

**Comment by ffMathy** [comment]
@timotheeguerin thanks for the fast response!

Not necessarily. It depends on whether or not the "nullable" information is respected by Autorest itself, so that the TypeScript generator can "read" that information.

If it's already available, then no need for this issue! :pray:

**Comment by timotheeguerin** [comment]
Yeah autorest should respect that information, if it is not then this is a bug.

**Comment by ffMathy** [comment]
Ah, my bad @timotheeguerin then. I'll close the issue.
