### ISSUE TITLE
empty operation group name if `operationId` of path in swagger doesn't have `_`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest#4162]
**Describe the bug**

If `operationId` of an API path doesn't have `_`, then the name of the operation group generated by autorest is empty.

**Expected behavior**

If an operation group cannot be identified, we could consider:

- throw an error
- or assign the `operationId` as the name of the operation group

**Additional context**

- See the attached [autorest_bastionHost.md](https://github.com/Azure/autorest/files/6639364/autorest_bastionHost.md). It links to `Network` service `bastionHost.json` which contains operation IDs without any underscore. For example, [PutBastionShareableLink](https://github.com/Azure/azure-rest-api-specs/blob/ac3be41ee22ada179ab7b970e98f1289188b3bae/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/bastionHost.json#L272)
- If you run `autorest autorest_bastionHost.md --azureresourceschema`. In the generated [code-model-v1.txt](https://github.com/Azure/autorest/files/6639371/code-model-v1.txt), you will find definition like below:

```
"name": {
      "$id": "594",
      "fixed": false,
      "raw": "PutBastionShareableLink"
     },
     "group": {
      "$id": "595",
      "fixed": false,
      "raw": ""
     },

```

**Comment by timotheeguerin** [comment]
Hi @archerzz, I don't see this being a problem, believe this is by design. If there is no `_` it will just add the operation at the root of the client.

**Comment by archerzz** [comment]
Hi @timotheeguerin,

I see. Then maybe we should not generate the operation group? Is there any specific reason we should keep an operation group with empty name? Thanks.

**Comment by timotheeguerin** [comment]
yeah, with an empty operation group it means the operation are at the root of the client.


```ts
// So you have
client.doSomething()

// Instead of
client.MyGroup.doSomething()
```

This could make sense if there is some generic operations that don't belong in a group or that there is a small SDK where adding a  group would add unnecessary nesting

**Comment by archerzz** [comment]
@timotheeguerin Thanks for the explanation. Closing, as it's expected.
