### ISSUE TITLE
Custom authorization key headers are not supported

### ISSUE THREAD

**Issue by heaths** [Azure/autorest#4163]
When I specify `add-credentials: true` in my autorest config, I get a warning for Cognitive Services that "apim_key" isn't supported - that only "AADToken,AzureKey" are supported. However, [this specification](https://github.com/Azure/azure-sdk-for-net/pull/21810/files#diff-5b75bf5979728caf42023bd9250fd31575618d795d6fd88afcc9f55d1884b6d5R17) is an implementation of a key - just with a different header name. We still have to write a client (by hand currently; this will be a problem for low-level client generation) that uses the `AzureKeyCredential`:

```json
  "securityDefinitions": {
    "apim_key": {
      "type": "apiKey",
      "name": "Ocp-Apim-Subscription-Key",
      "in": "header"
    }
  },
  "security": [
    {
      "apim_key": []
    }
  ],
```

Ideally, this is recognized as just a "custom" key auth strategy and [code like this](https://github.com/Azure/azure-sdk-for-net/pull/21810/files#diff-416cdb4cefa22e6bfbfe102c16c750ad348b0fa1024e8fb22096e5fd83563df7R34-R48) is added for us automatically:

```csharp
        public QuestionAnsweringClient(Uri endpoint, AzureKeyCredential credential, QuestionAnsweringClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));
            Argument.AssertNotNull(credential, nameof(credential));

            Endpoint = endpoint;
            options ??= new QuestionAnsweringClientOptions();

            Diagnostics = new ClientDiagnostics(options);
            Pipeline = HttpPipelineBuilder.Build(
                options,
                new AzureKeyCredentialPolicy(credential, AuthorizationHeader));

            // TODO: The api-version is hard-coded into the path and needs to be parameterized.
        }
```

/cc @timotheeguerin @chamons

**Comment by timotheeguerin** [comment]
Yes it is a warning telling you that autorest doesn't know what to do with it. You can ignore it if this is meant to be there.
If you want autorest to add credential automatically for you we added some support for known pattern(AAD token or a auth key) as described here in the doc https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md#authentication-in-generated-sdks

In your case you could just rename `apim_key` to be `AzureKey`(Just the definition key not the name of the header)

**Comment by heaths** [comment]
That doesn't seem to be working. I'll ping you offline. Maybe a quick screenshare could help clear the workaround up.

Still, though, I know we're trying to get away from using transforms for the Azure SDK. That doesn't necessarily mean we have to eliminate them, but if we could equate what's in swagger with AzureKey or or something, that would be great as a feature request.
