### ISSUE TITLE
"a bit ambiguous" error is noisy and non actionable

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#4178]
I haven't seen anyone react to it and fix it but some swaggers have a lot of violations resulting in a wall of warnings that drown other, more useful ones.

```
The schema 'MetricNamespaceCollection' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
```
cc @timotheeguerin

**Comment by timotheeguerin** [comment]
It is actionallable and I have a new tool to help fix this https://github.com/Azure/autorest/pull/4103.
This will soon become an error and we'll run the tool on all the specs in the azure-specs repo

See issue #4101

**Comment by pakrym** [comment]
Awesome!
