### ISSUE TITLE
Case-sensitive param matching fails in cases where param has been redeclared with different casing.

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/autorest#4211]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
I'm using the following logic in an autorest extension to match method parameters with placeholders in the method URL:
https://github.com/Azure/bicep-types-az/blob/afeb074286d0a7bcf8f7b0f68b3f6cee2afcc06f/src/autorest.bicep/src/resources.ts#L107

This works generally, but fails when parsing this PUT method in this particular swagger file: https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/virtualWan.json#L83

Despite both the method URL containing `VirtualWANName` (upper-case V), and the param name matching **exactly**, the value of `p.language.default.name` in the sample I shared above ends up being `virtualWANName` (lower-case v). I can see that the same parameter is declared in a totally independent method definition with a lower-case v ([here](https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/virtualWan.json#L760), for example), so I'm wondering if autorest is carrying out some parameter de-duplication case-insensitively?

The full autorest command I'm using:
`autorest --use=@autorest/modelerfour --use=/workspaces/bicep-types-az/src/autorest.bicep --bicep --output-folder=/tmp/_bcp_1626203053905/network --multiapi --title=none --skip-semantics-validation /workspaces/azure-rest-api-specs/specification/network/resource-manager/readme.md --debug --verbose --bicep.debugger`

The versions of autorest installed:
* @autorest/core": "3.5.0-dev.6"
* @autorest/modelerfour": "^4.19.3"

**Expected behavior**
I'd have expected case-sensitive matching logic to work in this scenario as both parameter and method placeholder are declared with the same casing.

**Comment by timotheeguerin** [comment]
Don't think this is an issue(or I am misunderstanding)

`language.default.name` represent the name of the parameter for the SDK(the actual language parameter) so it get styled according to the language conventions(default being camelCase for parameters)

If you want the parameter actual name in the url then `serializedName` will have that value.
![image](https://user-images.githubusercontent.com/1031227/125523373-da8f28e3-e1d3-4906-8f9a-2be3e25408fa.png)

**Comment by anthony-c-martin** [comment]
Yup, you're totally right - sorry for wasting your time! I'm using this library to get at these properties - totally missed that `Language` is extending a `Dictionary`: https://github.com/Azure/autorest/blob/7c68312403154a29770a1783fdca152a67fcc180/packages/libs/codemodel/src/model/common/metadata.ts#L33-L39

**Comment by anthony-c-martin** [comment]
Closing this as it's a non-issue.
