### ISSUE TITLE
Not able to process media type */* at this moment

### ISSUE THREAD

**Issue by lstanden** [Azure/autorest#4244]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**
Attempting to run the generator gives an error
```
FATAL: Error: Not able to process media type */* at this moment.
  Error: Plugin modelerfour reported failure.
```

These appear to be caused by clauses such as:
```
"responses": {
          "403": {
            "description": "Forbidden",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MultiErrorMessage"
                }
              }
            }
          },
```

**Expected behavior**
This should probably be a warning state rather than error state, and assume JSON or similar.

**Additional context**

**Comment by timotheeguerin** [comment]
Hi @lstanden, this is by design right now. There is no guessing what the content type should be as it could be anything and defaulting to `application/json` will most likely result in other unwanted behaviors.
