### ISSUE TITLE
Add validation for response examples to make sure keys are media types defined.

### ISSUE THREAD

**Issue by twsl** [Azure/autorest#4248]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues (probably related to #4244)

**Describe the bug**

<details>
  <summary>Swagger config</summary>

```
{
  "swagger": "2.0",
  "info": {
    "version": "v2",
    "title": "API",
    "description": ""
  },
  "host": "example.com",
  "basePath": "/rest",
  "schemes": [
    "https",
    "http"
  ],
  "paths": {
    "/api/Actions/{id}": {
      "get": {
        "tags": [
          "Actions"
        ],
        "summary": "Get an action by it's identifier.",
        "operationId": "Actions_GetOne",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The action identifier (UID)",
            "required": true,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ValidationError"
            },
            "example": {
              "Message": "The provided text was too long. Expected < 150 characters",
              "Key": "text"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ResponseMessage"
            },
            "example": {
              "Message": "Restr"
            }
          },
          "401": {
            "description": "Unauthorised - a bearer token is required."
          }
        },
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    }
  },
  "definitions": {
    "ResponseMessage": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "ValidationError": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        },
        "Key": {
          "type": "string"
        }
      }
    }
  }
}
```
</details>

<details>
  <summary>Autorest config</summary>

```
input-file: test.json
verbose: true
debug: true
csharp:
  namespace: Example.Client
  output-folder: csharp/Client
  enable-xml: true
  add-credentials: true
```

</details>

Validation via swagger-cli: `yarn run swagger-cli validate test.json`:
> test.json is valid

`yarn run autorest`
Error message:
```
AutoRest code generation utility [cli version: 3.3.2; node: v12.22.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.1.0.
Network Enabled: true
   Loading AutoRest core      'C:\Users\twsl\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist' (3.1.3)
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210803.1)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.3->4.19.3)

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\modelerfour\dist\main.js - FAILURE  {} Error: Not able to process media type Message at this moment.
    at ModelerFour.filterMediaTypes (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:1369:21)
    at ModelerFour.processResponses (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:2058:36)
    at ModelerFour.processOperation (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:1672:10)
    at ModelerFour.process (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:2327:14)
    at processRequest (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\plugin-modelerfour.ts:23:31)
    at C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\libs\extension-base\dist\extension-base.js:55:1
PLUGIN FAILURE: Not able to process media type Message at this moment., Error: Not able to process media type Message at this moment.
    at ModelerFour.filterMediaTypes (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:1369:21)
    at ModelerFour.processResponses (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:2058:36)
    at ModelerFour.processOperation (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:1672:10)
    at ModelerFour.process (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\modelerfour.ts:2327:14)
    at processRequest (C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\@autorest\src\modeler\plugin-modelerfour.ts:23:31)
    at C:\Users\twsl\.autorest\@autorest_modelerfour@4.19.3\node_modules\libs\extension-base\dist\extension-base.js:55:1, {}
FATAL: Error: Not able to process media type Message at this moment.
C:\Users\twsl\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE {}
  Error: Plugin modelerfour reported failure.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Create a simple API client.

**Additional context**
Autorest version: 3.3.2
Node version: tested with 12.22.4, 14.17.4, 16.6.1
Switching to v3 context via `--v3` produces the same results.
At some point with an earlier version of the api and autorest i was able to generate a client successfully. Unfortunately I don't remember the version of autorest used.

**Comment by timotheeguerin** [comment]
Hey @twsl believe the issue here is you have an operation that has a consume or produce being `Message` but the body is not described as binary and `Message` is not a content-type autorest handles(not sure what you expect it to be).

**Comment by twsl** [comment]
The endpoint should produce the model as defined by the schema ref. I expect autorest to handle valid swagger files.

**Comment by timotheeguerin** [comment]
What do you expect `Message` content type to be? What does the payload looks like? The only reference of this content type I can see seems to be related to emails https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa494204(v=exchg.140), is this what you are defining? If so this is most likely not going to be something autorest will ever support.

**Comment by twsl** [comment]
The datatype is defined as under the definitions; check the swagger config I attached in the original post. There you can see, that Message is defined as string.

**Comment by timotheeguerin** [comment]
Sorry didn't see you linked the spec. 
The issue is the spec is not valid. If you paste it in https://editor.swagger.io, you'll have the error. Autorest latest version also will have the error logged correctly.

The problem is you are using `example` under responses and it is expecting `examples` where the keys are the mediaType. Should change the example to this: 
```yaml
examples:
    application/json:
      Message: The provided text was too long. Expected < 150 characters
      Key: text
```

The reason this was happening is:
- 1 the schema validation had some issue and it wasn't failing at that point(solved in latest version of autorest).
![image](https://user-images.githubusercontent.com/1031227/128399408-8e1535bb-61d0-4fe2-91e2-1322eaca4096.png)

- For some reason autorest was taking the `example` or `examples` property 
- It was then going over each of the keys(`Message`, `Key`) and try to find the matching content-type for it and failed there.

**Comment by twsl** [comment]
I made a mistake: In my original swagger config it actually says `examples`, the s was removed by error while minifying the file.
`All examples are free-form, meaning their interpretation is up to tools and libraries.` is probably the reason why swagger-cli didn't catch it. However, replacing example with examples validates in https://editor.swagger.io/ without issue. Now I'm wondering if it's simply ignoring the section as well.
But apparently, the mime type can be `inherited from the global scope`, so I'm wondering if this is something that allows my current swagger config.

**Comment by timotheeguerin** [comment]
Yes, the actual [specificiation](https://swagger.io/specification/v2/)(can't link the actual section "Example Object") define the type of `examples` under response as `Dict<mimeType, any>` and the content under the mimeType being freeform.

![image](https://user-images.githubusercontent.com/1031227/128423456-bc8aa1af-d302-42d2-862f-5a9947a26704.png)

Seems like neither editor.swagger.io nor autorest will do validation on that. Should probably change that to prevent this confusing error later down the pipeline.

**Comment by twsl** [comment]
I guess that's a good idea, simply validating whether the key is included in the produces section should be an easy fix.

**Comment by twsl** [comment]
After reflecting for a few more minutes, I don't think failing to parse or validate the example section should crash autorest while creating a client.
Given the fact, that the whole `examples` section is still described as free-form, autorest should be able to create a client regardless of whats in the section. This is probably why I was able to generate a client with an earlier version.
In case the mime type keys are cannot be found within the `produces` section, a warning about an invalid config would be helpful nonetheless.

**Comment by timotheeguerin** [comment]
From what I understand in the specs. The content of responses `examples` is not freeform. It must be using having keys being the media types defined in the produce(either local or global). Then the content of those are  freeform. 
![image](https://user-images.githubusercontent.com/1031227/128426766-e7894e05-ec8c-468d-a2e1-028f0e5d8e13.png)
The 2nd part referring to each example being freeform not the entire section.

Now this is a problem specific to swagger 2.0 as in openAPI 3 the examples are already under the given media type so they can be anything.

```yaml
responses:
  '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        example: 
          # Properties of the referenced object
          id: 10
          name: Jessica Smith
```

**Comment by twsl** [comment]
Alright, then it might make sense to validate that.
However, does the examples section serve any purpose in autorest in the generation of a client? Apart from being part of the swagger/OpenAPI spec? Is there a NEED for that?

**Comment by timotheeguerin** [comment]
Well yes and no. Client generation don't make use of it now but autorest is not limited to client generation and some other tools might.
Either way the main problem is actually due to the fact that autorest convert swagger 2.0 to openapi 3.0 first and during this conversion if you have invalid examples then it creates new responses with those mime types.

For example on editor.swagger.io if you convert your spec it produces this(About the same is produced by autorest):
![image](https://user-images.githubusercontent.com/1031227/128433237-b46d2689-e31e-4548-81a0-fe295aa6a0d6.png)
And this is definitely incorrect.

However it could maybe just be a warning that remove the invalid examples instead of a strict error.
