### ISSUE TITLE
Include example filename (path) in x-ms-examples

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest#4251]
**Is your feature request related to a problem? Please describe.**

Is it possible to know (from certain step in autorest pipeline) the filename of the $ref in x-ms-examples? E.g., we would like to know "./examples/ServerCreate.json" (preferably the complete one as "Microsoft.DBforMySQL/stable/2017-12-01/examples/ServerCreate.json" in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json#L43-L46
 
After m4, we can only see the content, but no longer the filename.
 
Background, SDK is trying to generate example code with the same filename (e.g. "./examples-java/ServerCreate.java"), so that we or MSDocs team would able to match the JSON example and the SDK example, according to the filename pattern.

**Describe the solution you'd like**

right now it just loads the content of the example file and insert it. guess we could look into injecting a extension property in the examples content( x-ms-original-source or similar)

**Describe alternatives you've considered**

A fallback for me is to print the path/method/api-version in SDK sample and then try to match it back to the json and $ref. But looks a bit too tricky as postprocess.

**Additional context**

**Comment by timotheeguerin** [comment]
@weidongxu-microsoft does this https://github.com/Azure/autorest/pull/4255#issuecomment-899802550 give the necessary information

**Comment by weidongxu-microsoft** [comment]
@timotheeguerin 

Yes, this is enough information. I can see following
```
x-ms-original-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/examples/getDataPolicyManifest.json
```
and I should be able to break the path to what I need.

Thank you!

**Comment by weidongxu-microsoft** [comment]
@timotheeguerin

Any plan for the PR get merged and shipped in m4?

**Comment by timotheeguerin** [comment]
Merged the pr a new preview version of modelerfour should be published momentarily. For the next stable version might try early next week

**Comment by weidongxu-microsoft** [comment]
Sure, will try it. Thanks very much!
