### ISSUE TITLE
x-ms-client-default vs default

### ISSUE THREAD

**Issue by forteddyt** [Azure/autorest#4258]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

I'm confused on what the difference is between [x-ms-client-default](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-default) and "default" as defined in the [swagger 2.0 spec](https://swagger.io/specification/v2/):
> Declares the value of the parameter that the server will use if none is provided, for example a "count" to control the number of results per page might default to 100 if not supplied by the client in the request.

The x-ms-client-default documentation of
> This is different than the default value you can specify

is not very helpful...

What's the difference?

**Comment by timotheeguerin** [comment]
- `default` refer to what value will the service will have in case no value is passed. This means this value is just ignored completely by autorest.
- `x-ms-client-default` refer to the initial value on the client if you don't pass the value but that value will be sent to the service.

This is a subtle difference that result in mostly the same thing if your service handle the default value. If not this is a way to set a default in the client.
