### ISSUE TITLE
AzureKey in-query support?

### ISSUE THREAD

**Issue by ambientlight** [Azure/autorest#4266]
**Is your feature request related to a problem? Please describe.**
In addition to Azure AD, Azure Maps services support [API Key auth in query.](https://docs.microsoft.com/en-us/azure/azure-maps/azure-maps-authentication#shared-key-authentication)

Using [AzureKey](https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md#key-authentication) in securityDefinitions  with `"in": "query"` will fail at validation at https://github.com/Azure/autorest/blob/main/packages/extensions/modelerfour/src/modeler/security-processor.ts#L201

**Describe the solution you'd like**:
Curious to hear what approach is recommended in this case thus far?

1. Add `subscription-key` explicitly to all paths via:
  ```json 
  "SubscriptionKey": {
        "name": "subscription-key",
        "description": "One of the Azure Maps keys provided from an Azure Map Account. Please refer to this [article](https://docs.microsoft.com/azure/azure-maps/how-to-manage-authentication) for details on how to manage authentication.",
        "type": "string",
        "in": "query",
        "required": false,
        "x-ms-parameter-location": "client"
  },
  ```
  This is nice since generated documentation will explicitly list `subscription-key` in `URI Parameters`, but each path will need to contain it.

2. Renaming AzureKey from security definition to other name (for the sake of having it appear in generated doc) and adding custom middleware that will append the subscription-key to created requests. This would look similar to how ouath2 bearer auth  is added in generated clients, but adds manual work on top of generated clients and also doesn't show in generated documentation uri parameters and examples. 
3. both 1. and 2.

Ref: https://github.com/Azure/azure-rest-api-specs/pull/15747

**Comment by daniel-rocha** [comment]
@ambientlight We've validated that the APIs support the subscription key in the header as well, so I believe we should stop sending the key via query string, it's better for security as well, given query string is logged everywhere.
