### ISSUE TITLE
Duplicate enum inline causes issue when merging schemas

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest#4267]
**Before filling a bug**

- [ ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ ] have you checked existing issues

**Describe the bug**

[This type here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v2/types.json#L511) has two different instances of an enum added inline.  If we add the following directive in autorest.md

```yaml
- from: types.json
    where: $.definitions.*.properties[?(@.enum)]
    transform: >
      $["x-namespace"] = "Azure.ResourceManager.Resources.Models"
```
What appears to happen is that the x-namespace attribute gets removed when the two enums get combined in autorest. This is based on my very basic understanding of autorest however I did remove one of the inline definitions and the x-namespace shows up in codemodel.yaml as expected. 

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v2/types.json#L511
- Autorest command used
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/autorest.md
change the input line to use the url instead of the local file to reproduce the issue and run dotnet build /t:GenerateCode from ./sdk/resourcemanager/Azure.ResourceManager
```

**Expected behavior**
Expected that the x-namespace would be maintined during deduplication and exist in the codemode.yaml

**Additional context**

**Comment by timotheeguerin** [comment]
@m-nash could you try this out and confirm this resolve the issue https://github.com/Azure/autorest/pull/4273#issuecomment-910400873
