### ISSUE TITLE
while --version works for the cli, version: in the yaml section of the md file does not work. 

### ISSUE THREAD

**Issue by roquedaime** [Azure/autorest#4268]
Adding a version tag to the yaml doesn't set the version of autorest core. I've tried several variations, including:

```
version:
   '@autorest/core': 3.0.6274
```

or even 

```
version: 3.0.6274
```
Doing the same thing with the command line will show you that the specified version has been chosen and will generate using that version (see the "Loading AutoRest core" output).

https://github.com/Azure/autorest/blob/main/docs/install/autorest-versioning.md suggests that it should be possible. 

**Expected behavior**
I would expect it to behave the same as the --version command line parameter works. IE:

```
autorest .\configuration.md --version:3.0.6274
```

**Additional context**
If this is a question of syntax, please document it [here](https://github.com/Azure/autorest/blob/main/docs/install/autorest-versioning.md) because I've scoured the web for how to do this and I'm drawing a blank.

**Comment by timotheeguerin** [comment]
Your 2nd variation is correct 
```yaml
version: 3.0.6274
```

If I add this to my config
![image](https://user-images.githubusercontent.com/1031227/131691973-d6cab8c8-24d4-440a-ae5a-6e32d4945dff.png)

The resulting run will do that:
![image](https://user-images.githubusercontent.com/1031227/131691950-64fecc4e-8fc0-44cb-9dbe-3977fad27670.png)

Can you share the log you are seeing, version of the cli(`autorest`) package and try updating that one to the latest.
