### ISSUE TITLE
Generating Powershell Cmdlets for Kaseya BMS API V2 

### ISSUE THREAD

**Issue by denismcapple** [Azure/autorest#4281]
Hi All,

I am trying to generate cmdlets for the Kaseya BMS API 

The Specifications are here: https://api.bmsemea.kaseya.com/swagger/index.html
The JSON is here: https://api.bmsemea.kaseya.com/swagger/v2/swagger.json

I am getting errors when I try to run:
> autorest --powershell --input:file:./swagger.json

The first error I got was 

```
PS C:\Users\denis\Desktop\BMS-Swagger> autorest --powershell --input-file:swagger.json
AutoRest code generation utility [cli version: 3.3.2; node: v14.17.6]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\denis\.autorest\@autorest_core@3.5.1\node_modules\@autorest\core\dist' (3.5.1)
INFORMATION:
The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

INFORMATION: > Loading AutoRest extension '@autorest/powershell' (~3.0.0->3.0.448)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
Process() cancelled due to failure
ERROR: Schema violation: must match pattern "^/" (basePath)
  pattern: ^/
    - file:///C:/Users/denis/Desktop/BMS-Swagger/swagger.json:9:1 ($)
ERROR: Schema violation: must match pattern "^/" (basePath)
  pattern: ^/
    - file:///C:/Users/denis/Desktop/BMS-Swagger/swagger.json:9:1 ($)
PS C:\Users\denis\Desktop\BMS-Swagger>
```

Then, I tried updating the basepath to "/" and got a little further

```
PS C:\Users\denis\Desktop\BMS-Swagger> autorest --powershell --input-file:swagger2.json
AutoRest code generation utility [cli version: 3.3.2; node: v14.17.6]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\denis\.autorest\@autorest_core@3.5.1\node_modules\@autorest\core\dist' (3.5.1)
INFORMATION:
The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

INFORMATION: > Loading AutoRest extension '@autorest/powershell' (~3.0.0->3.0.448)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
  Error: Operation response '/paths/~1v2~1crm~1accounts~1{accountId}~1alerts~1{accountAlertType}/get/responses/200' produces type couldn't be resolved. Operation is probably is missing a produces field and there isn't any global value. Please add "produces": [<contentType>]"
```

But, I am now totally lost - Hoping someone can give me a pointer in the right direction.

Thanks a million
Denis

**Comment by timotheeguerin** [comment]
Hey @denismcapple for the 1st error this is indeed incorrect according to the spec. You can paste that spec into editor.swagger.io and see there is also a lot of other schema errors with this swagger.

For the 2nd error it just seems that you have no `consumes` and `produces` field(they are empty) so it can't know which content-type the server returns and accept.

**Comment by denismcapple** [comment]
Hey @timotheeguerin - Thanks for getting back to me.

Yeah, it seems like it's got a few problems there alright. I will try to figure it out and post here if I make any progress.

If anyone else has any ideas or suggestions, would be happy to hear them! :)

Thanks again

**Comment by timotheeguerin** [comment]
Hey @denismcapple, I'll close this issue as this seems to just have been an invalid spec. Please create another one if you are getting into a autorest bug.
