### ISSUE TITLE
Autorest docker update

### ISSUE THREAD

**Issue by jongio** [Azure/autorest#4283]
This page: https://hub.docker.com/r/azuresdk/autorest

Is outdated, dead links, etc.

Can we please get it updated?

**Comment by jongio** [comment]
This: 
https://hub.docker.com/r/azuresdk/autorest

Still points to:
https://github.com/Azure/autorest/blob/feature/docker/docs/docker.md

Which 404s.

Can you reactivate this issue?  Thanks

**Comment by timotheeguerin** [comment]
Should be resolved now, seems to have been an issue with the patching of the readme

**Comment by jongio** [comment]
Confirming fix.  Thank you!
