### ISSUE TITLE
ServiceClient ApiVersion should default to "version" element from Swagger

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/autorest#429]
Gen using the Azure.CSharp generator.
Create an instance of the generated client.
Call a method on it.

Expected: Version from swagger is used as the default for ServiceClient.ApiVersion
Actual: exception that ApiVersion must not be null.

**Comment by matt-gibbs** [comment]
was specifying -Generator instead of -CodeGenerator so it was using generic C#.
Why doesn't the generic C# generator provide the same convenience?

**Comment by stankovski** [comment]
There is no way to tell whether an operation property with name "apiVersion" should default to API version from the swagger document. Currently we follow the convention that in Azure the parameter name is "api-version" and it's location is in query. This is not always true for generic clients.
