### ISSUE TITLE
M4 4.21.0 fails building body-string.json from test server

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4293]
M4 version 4.21.0

This is due to the behavior change of treating single-value enums as constants.  There are two failure cases.

https://github.com/Azure/autorest.testserver/blob/dc0fde45b200836099f79079427b71e5f9c81afd/swagger/body-string.json#L95
https://github.com/Azure/autorest.testserver/blob/dc0fde45b200836099f79079427b71e5f9c81afd/swagger/body-string.json#L159

Both of these cause build failures.

debug   | [3.65 s] modelerfour/pre-namer - START inputs = 2
fatal   | Error: Name is empty!
fatal   | Process() cancelled due to exception : Plugin pre-namer reported failure. / Error: Plugin pre-namer reported failure.
    at C:\Users\jhendrix\.autorest\@autorestcore@3.6.0\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2752:19
    at ScheduleNode (C:\Users\jhendrix\.autorest\@autorestcore@3.6.0\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1316:33)
[3.67 s] Shutting Down.
[3.67 s] Exiting.
 
stderr: C:\Users\jhendrix\.autorest\@autorest_modelerfour@4.21.0\node_modules\@autorest\modelerfour\dist\main.js - FAILURE  {} Error: Name is empty!
    at setName (C:\Users\jhendrix\.autorest\@autorest_modelerfour@4.21.0\node_modules\@autorest\src\prenamer\naming-utils.ts:48:11

**Comment by timotheeguerin** [comment]
@jhendrixMSFT is there anything additional here than this issue I created for name is empty #4292

**Comment by jhendrixMSFT** [comment]
Oh I thought #4292 was about improving the error message.

**Comment by timotheeguerin** [comment]
Well it is, but empty string name for enums are invalid(or need a new name at least).

**Comment by timotheeguerin** [comment]
Yeah so I don't think we can do much about it appart from improving the error. We could default the enum property name but that would bring us back to all the naming issues we can from auto generating things.

**Comment by jhendrixMSFT** [comment]
I think this is still a problem even if we specifcy `x-ms-enum`, let me check.

**Comment by jhendrixMSFT** [comment]
My mistake, `x-ms-enum` it works as expected.  If the error message can be improved that would be helpful though.

**Comment by timotheeguerin** [comment]
ok will close in favor of #4292 with the added case of the non ascii characters
