### ISSUE TITLE
M4 4.21.0 incorrectly changes const type to string

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4294]
M4 version 4.21.0

This is presumably due to the behavior change of treating single-value enums as constants.

For operation [`bool_putFalse`](https://github.com/Azure/autorest.testserver/blob/dc0fde45b200836099f79079427b71e5f9c81afd/swagger/body-boolean.json#L107), after fixing up the parameter as follows.

```json
"parameters": [
  {
    "name": "boolBody",
    "in": "body",
    "schema" : {
      "type": "boolean",
      "enum": [false],
      "x-ms-enum": { "name": "falseConst", "modelAsString": false }
    },
    "required": true
  }
],
```

The `schema.valueType.type` has a type of `SchemaType.String` which is unexpected.

**Comment by timotheeguerin** [comment]
Interesting this actually seems to have been broken before too.

**Comment by timotheeguerin** [comment]
hhm, actually I think I was mixing up things. I can't seem to repro that the valueType is a boolean not a string
![image](https://user-images.githubusercontent.com/1031227/133514767-64016118-4eb3-47dc-a9cf-79f1d6b34aba.png)

![image](https://user-images.githubusercontent.com/1031227/133514727-7d88dffc-25ba-4b96-8530-2e9e7c4d84c4.png)

![image](https://user-images.githubusercontent.com/1031227/133514693-21b05701-e281-4607-b2e0-f979a9ced22a.png)

**Comment by jhendrixMSFT** [comment]
Hmm let me take a closer look at my repro.

**Comment by jhendrixMSFT** [comment]
OK there's a bit more to this.  You have to apply the same fix to the enum response in [`bool_getFalse`](https://github.com/Azure/autorest.testserver/blob/dc0fde45b200836099f79079427b71e5f9c81afd/swagger/body-boolean.json#L80) or it doesn't repro.

**Comment by timotheeguerin** [comment]
ok, I can repro now, yeah I guess might have had something repo like that earlier but it does seem to have always been broken. will dig into it

**Comment by timotheeguerin** [comment]
Think it has to due to a bug in the enum deduplicator as now you specify the same name it tries to deduplicate but drops the type

**Comment by jhendrixMSFT** [comment]
In the case where we want this to be a constant, it would be nice if we didn't have to specify the `name` as it's really just a dummy value.

**Comment by timotheeguerin** [comment]
yeah so there was 2 issues: 
1. as said above it would hard code `type: string` when merging enums
2. if `name` was not provided but `x-ms-enum` was it would either crash(before 3.5.0) or just act like if the name is `undefined` and still merge it causing this issue but if `x-ms-enum` wasn't there then it would use the auto generated name

Both should be fixed in the PR linked.  Can you verify it works https://github.com/Azure/autorest/pull/4295#issuecomment-920451075

**Comment by jhendrixMSFT** [comment]
Verified fix is working.
