### ISSUE TITLE
How to generate a valid Swagger without $ref-siblings and with "allOf" without having Autorest generating duplicated models

### ISSUE THREAD

**Issue by niander** [Azure/autorest#4300]
I have found relevant information [here](https://github.com/Azure/autorest/blob/main/docs/openapi/howto/$ref-siblings.md), but I still have some questions.

We are using [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) to enrich our swagger avoiding any manual modification before passing it to Autorest. Swashbuckle correctly use "allOf" for definitions that have a reference to other definitions to be able to add other properties such as "readOnly". However, since Autorest seems to consider "allOf" as signal of inheritance, it is creating two identical models, one inhering from the other one just because "allOf" was used.

I understand that Autorest still interpret some $ref-siblings like "readOnly" (from this [page](https://github.com/Azure/autorest/blob/main/docs/openapi/howto/$ref-siblings.md)). However, because we are using an automated tool to enrich the swagger I am not sure if we can force the tool to create an "incorrect swagger" with $ref-siblings properties.

Is there a way of configuring Autorest, either through an extension or directive, to not consider some particular "allOf" as inheritance? That is, not generate duplicate models when the properties next to "allOf" are just descriptive like "description" or "readOnly".

**Comment by timotheeguerin** [comment]
Yeah there is definitely a lot of problems created around this.

Can you try using `--modelerfour.remove-empty-child-schemas` and see if that resolve the issue.

**Comment by niander** [comment]
That worked! Does that mean we could add stuff like "desctiption" and "readOnly" alongside the "allOf" and this switch `--modelerfour.remove-empty-child-schemas` would still remove the "unnecessary" allOf ?

**Comment by timotheeguerin** [comment]
Yes, basically autorest was originally written with this modified swagger functionality and this flags make the official "workaround" work but I think it can also cause other unexpected issues.

**Comment by niander** [comment]
Understood. We are testing with this new flag and for our case, it seems that up until now it is not causing unexpected issues. We will continue testing. Do you have the modeler flags documented anywhere?

**Comment by timotheeguerin** [comment]
https://github.com/Azure/autorest/blob/main/packages/extensions/modelerfour/readme.md#modelfour-options

**Comment by niander** [comment]
Thank you. I am curious of a situation that could create unexpected issues when using this flag. Anyways, we are happy to just use that for now.

**Comment by timotheeguerin** [comment]
Here is the PR that added this flag and reintroduced this behavior. https://github.com/Azure/autorest.modelerfour/pull/377
The main case where this will fail is if you actually meant to create this new child schema with a different name,

We could however be a little smarter on when to decide to merge the relation or not: If only properties meant to describe a model property and the allOf is present then it means this otherwise don't try to remove it.

**Comment by niander** [comment]
Will Autorest always issue a warning for all cases where `modelerfour.remove-empty-child-schemas` is replacing "allOf" for a $ref instead? In our testing, it does show a warning for all the stuff we were expecting it to work on. However, we are not sure if it is removing others and not issuing a warning.
