### ISSUE TITLE
Compatibility issues with latest autorest 

### ISSUE THREAD

**Issue by purneshpatreon** [Azure/autorest#4333]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
Previously version of autorest 3.1 started giving problems and i was forced to upgrade.
The latest autorest 3.4 is using latest extensions of core and python which inherently is forcing us change versions of 
other packages likes moto, boto, boto3, botocore ..etc. 

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```

**Expected behavior**

After generating the autorest latest client, when making the request 
firstly it showed an error for the 
from azure.core.rest import HttpRequest 
rest not found -- I was using azure-core 1.12, updating it to 1.18 resolved the problem.
Then it started giving
AttributeError: '_patch' object has no attribute 'is_local
Then updating mock version resolved this issue. 
However from mock, it depends/ has compatibility issues with moto, which indeed forced me to update versions of 
boto, boto3, botocore.
 
**Additional context**
These are the current versions i'm using. 
Autorest versions [cli version: 3.4.0; node: v14.18.0]
autorest/core -- 3.6.3
info | Installing AutoRest extension '@autorest/python' (latest)
info | Installed AutoRest extension '@autorest/python' (latest->5.9.1)
info | Installing AutoRest extension '@autorest/modelerfour' (~4.19.1)
info | Installed AutoRest extension '@autorest/modelerfour' (~4.19.1->4.19.3)

Previously was using 3.1 -- is there any way, we can still continue using 3.1 and not upgrade or forced to update ?

**Comment by timotheeguerin** [comment]
@purneshpatreon did you follow the doc here? https://github.com/Azure/autorest/blob/main/docs/install/autorest-versioning.md#core-module.
