### ISSUE TITLE
ASP.NET Core Swashbuckle's Open API SDK does not generate 'x-ms-client-flatten'

### ISSUE THREAD

**Issue by kichalla** [Azure/autorest#4338]
I am from the Azure Container Registry team. We currently use legacy ASP.NET Web API + Swashbuckle to generate Swagger 2.0 document. In this generated Swagger document we are able to provide extensions like 'x-ms-client-flatten', 'description', 'readOnly' etc. for our reference objects.

We are migrating this application to ASP.NET Core and would like keep using Swashbuckle to generate Swagger 2.0 document. But this version of Swashbuckle uses Open API SDK to generate the document which does[ _not_](https://spec.openapis.org/oas/v3.0.2#fixed-fields-18) allow providing extensions like 'x-ms-client-flatten', 'description' etc. when used with a referenced object schema. We would like to keep generating these extensions so that our clients do not break.

I came across following issues when researching about this problem.
- https://github.com/Azure/autorest/issues/3411
- https://github.com/microsoft/OpenAPI.NET/issues/393 (the 3.1 spec seems to have fixed the 'description' issue)

Seems like my alternatives are:
- Use an autorest configuration file to set the extensions.
OR
- We write a tool that modifies the generated swagger document's json to explicitly add these extensions that Open API SDK extension excluded.

Both these alternatives add lot of work and could be error-prone.

**Question**: Since ASP.NET Core + Swashbuckle is a popular combination of writing web api apps, I am curious to know of any plan going forward from AutoRest team regarding this issue. I am suspecting you do not have many options from your side since Open API SDK is not providing a way to give the information in the Swagger doc. How is this problem going to be solved? I guess one approach for my team going forward is to _not_ have deeply nested models to begin with and avoid using `x-ms-client-flatten`, but at this point we do not want to break existing clients. Please let me know if I am missing anything and if there are any other better alternatives here. Thanks.

cc @darrelmiller

**Comment by kichalla** [comment]
Thanks for the prompt response @timotheeguerin and thanks for the workaround!

**Comment by darrelmiller** [comment]
When we finally get around to adding 3.1 support in OpenAPI.NET we will need to accommodate adding properties alongside refs.  I will make sure that you can add any arbitrary content even though the spec currently only recognizes a few values.  Our plan it to allow others in the future, as long as we can define clear rules on how those values get merged.
