### ISSUE TITLE
Erroneous documentation for --add-credential when used for Python generation

### ISSUE THREAD

**Issue by vbossica** [Azure/autorest#4339]
When generating Python code, `--add-credential` doesn't add the credentials constructor parameter while `--add-credentials` does.

The documentation seems to mention that `--add-credential` must be used for Python.

**Comment by timotheeguerin** [comment]
Hey @vbossica which version of autorest and the python extension are you using? `--add-credentials`  was the old parameter in v2 but has been renamed to `--add-credential` (with support for --add-credentials for backward compatibility).

**Comment by vbossica** [comment]
Here's the setup:

```
AutoRest code generation utility [cli version: 3.4.1; node: v12.18.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version
 core       @autorest/core                           3.0.6274
 extension  @microsoft.azure/autorest.csharp         2.3.91
 extension  @microsoft.azure/autorest.java           2.1.95
 extension  @microsoft.azure/autorest.modeler        2.3.38
 extension  @microsoft.azure/autorest.modeler        2.3.44
 extension  @microsoft.azure/autorest.modeler        2.3.55
 extension  @microsoft.azure/autorest.nodejs         2.1.128
 extension  @microsoft.azure/autorest.python         3.0.62
 ```
 
It seems like it's quite an old version. Updating the versions should fix it.
I'll double check the installation script that I ran.
