### ISSUE TITLE
Add logging to the ExtensionManager

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest#4349]
https://github.com/Azure/autorest/blob/55646b82001b05d4e1c8530f53af979ad39aea89/packages/libs/extension/src/main.ts#L496
If spawn fails, it doesn't show any useful information what error has happened or at least what extension has failed to start. Would be good to print the cmdline.

**Comment by timotheeguerin** [comment]
Believe the spawn Unknown error is the only information that is sent when it crash. If there is more information it is logged. 
![image](https://user-images.githubusercontent.com/1031227/140231283-22ca6c38-94ab-4f92-8d4f-f89c32faa888.png)

There seems to have been some errors logged like that in older version of node. If this repro, please include all the versions and the repro steps.
