### ISSUE TITLE
Cannot read property 'key' of undefined / TypeError: Cannot read property 'key' of undefined 

### ISSUE THREAD

**Issue by krptodr** [Azure/autorest#4361]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
I am attempting to generate a client from the rundeck api specs. My configuration file is pretty basic and likely to be incomplete, however the error indicates it doesn't have knowledge of my input-files even though they're loaded right before the output you see below. 
[rundeck-api-specs](https://github.com/rundeck/rundeck-api-specs)

Please provide as much information as you can. This would be:

- OpenAPI files having the issues
```
DEBUG [4.66 s]: openapi-document/loader-openapi - END [2.09 s]
DEBUG [4.66 s]: openapi-document/individual/transform - SKIPPING
DEBUG [4.66 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [4.66 s]: swagger-document/loader-swagger - END [2.09 s]
DEBUG [4.66 s]: openapi-document/individual/identity - SKIPPING
DEBUG [4.66 s]: swagger-document/individual/transform - SKIPPING
DEBUG [4.66 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [4.66 s]: swagger-document/identity - SKIPPING
DEBUG [4.66 s]: swagger-document/individual/identity - SKIPPING
DEBUG [4.66 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [4.66 s]: openapi-document/transform - START inputs = 0
DEBUG [4.66 s]: openapi-document/transform - END [0 s]
DEBUG [4.66 s]: openapi-document/allof-cleaner - START inputs = 0
DEBUG [4.66 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [4.66 s]: openapi-document/tree-shaker - START inputs = 0
DEBUG [4.66 s]: openapi-document/tree-shaker - END [0 s]
DEBUG [4.66 s]: openapi-document/multi-api-merger - START inputs = 0
C:\Users\Chad.Robinson\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE {}
Process() cancelled due to exception : **Cannot read property 'key' of undefined / TypeError: Cannot read property 'key' of undefined**
    at MultiAPIMerger.get currentInputFilename [as currentInputFilename] (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:12732:31)
    at MultiAPIMerger.finish (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:3419:94)
    at MultiAPIMerger.runProcess (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:12741:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MultiAPIMerger.getOutput (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:12672:9)
    at merge (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:3616:54)
    at ScheduleNode (C:\Users\<insert_name_here>\.autorest\@autorestcore@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1809:33)
```
- Autorest command used
```
 autorest .\config-file.json --csharp --verbose --debug
```

**Expected behavior**
The command should have finished for generating a csharp client.

**Additional context**
AutoRest code generation utility [cli version: 3.4.2; node: v12.19.1]

**Comment by timotheeguerin** [comment]
Hi @krptdor, could you share what configuration you used?

You @autorest/core version is also quite outdated(3.1.3). Can you try setting it to latest with `--version=3.6.6`

**Comment by krptodr** [comment]
I'm suprised autorest defaulted to using 3.1.3. I installed the latest for the first time yesterday. Why is it not defaulting to 3.6.6?

I played further and was able to generate something using (However, I'd like to understand if that was absolutely needed. ):

``autorest .\config-file.json --csharp --verbose --debug --memory=8g --v2``

**Config File Used**
```json
{  
  "title":"Test",
  "output-folder": "./src",
  "log-file": "./log.txt",
  "input-file": [
    "./rundeck/execution.yaml",
    "./rundeck/job.yaml",
    "./rundeck/metric.yaml",
    "./rundeck/project.yaml",
    "./rundeck/storage.yaml",
    "./rundeck/system.yaml",
    "./rundeck/user.yaml"
  ],
  "directive": [
    {
      "from": "swagger-document",
      "where": "$.components.schemas.*.additionalProperties",
      "transform": "return typeof $ === \"boolean\"\n  ? ($ ? { type: \"object\" } : undefined)\n  : $\n",
      "reason": "polyfill"
    },
    {
      "from": "swagger-document",
      "where": "$.paths.*.get.parameters[?(@.schema.type === \"array\")]",
      "transform": "if ($.style === undefined) {\n    $.style = \"form\";\n    $.explode = true;\n}\n",
      "reason": "polyfill"
    }
  ]
}
```

**Comment by timotheeguerin** [comment]
Yeah, seems like the default csharp configuration (and some other language) have the default core version set to `~3.1.0`

**Comment by krptodr** [comment]
Running the following command:
``autorest .\config-file.json --csharp --verbose --debug --memory=8g --v2 --version=3.6.6``

it generates the same error. The difference is adding the `--v2` flag which was found to be successful prior to adding the --`version=3.6.6` flag

**Comment by timotheeguerin** [comment]
--v2 is just an "helper" that does the same as `--version=^2.0.0` but `--version takes precedence

**Comment by krptodr** [comment]
So it seems that using --v2 I can successfully generate a client. However, I have to remove the definitions file from the configurations input-file section. 

However, if using --version=3.6.6 it needs the definitions file in there otherwise it throws the following exception:
``error   |   Error: $ref to original location 'file:///rundeck/execution.yaml#/components/schemas/JobInputFileInfo' is not found in the new refs collection``

Adding the definitions file solves that but returns the initial error presented in the issue.

**Comment by timotheeguerin** [comment]
Ok, so I have an idea of what is going on:
1. You are adding `./definitions.yaml` to the inputs file. This is not a valid swagger/openapi file. Input file should always be swagger files that can be merged together. Now I need to see why this error is happening, it seems because of this file it doesn't load anything.
2. If you remove it you still have a problem, autorest doesn't support $ref to a whole file for now. https://github.com/Azure/autorest/issues/3759

Are you saying it actually works with `--v2` , I see it actually failing with a more meaningful error 
![image](https://user-images.githubusercontent.com/1031227/141507504-6db89312-3cb5-4dc0-87e5-27327a675d01.png)

**Comment by timotheeguerin** [comment]
The problem with the $ref to the whole file is happening in v3 due to the oai2-> oai3 conversion which wasn't happening in v2.

The alternative is to have `./definitions.yaml` be valid swagger file and then you can reference it from the other files with:
```yaml
$ref: ./definitions.yaml#/definitions/MyDef
```

**Comment by krptodr** [comment]
I'll try this, but in an effort to save time. Do you have recommendations on tools that can generate YAML OpenAPI 3 files from scratch?

I also would like to know what is missing to make definitions.yaml a valid swagger file.

**Comment by timotheeguerin** [comment]
To make it valid just move the defintions under the `definitions` key and add the swagger required properties(swagger, info, paths)
![image](https://user-images.githubusercontent.com/1031227/141510231-bcb0f0d4-a134-4501-b1e2-602e462566fb.png)

What do you mean by generate from scratch?

**Comment by krptodr** [comment]
Thank you @timotheeguerin. I will follow your instructions for the definitions file. 

Well RunDeck, much like others, had to generate the yaml files with details based off of their projects. Where do I go to generate these yaml files, myself if I have a project and want to make an API specification?

**Comment by timotheeguerin** [comment]
Well there is 3 ways you can go about it: 
- Use some kind of swagger emitter if you control the code(like swashbuckle for dotnet). You add anotation to the controllers and it will generate the swagger spec:
  - Pros: 
    - Little work required
  - Cons: 
    - Swagger is not meant to describe a SDK and those tools will most likely not generate optimal spec for describing a SDK which might result in bad experience for sdk user.
    - Much harded to noticed that you are producing breaking change to your SDK(if it matters)
- Write the swagger specs by hand. This is the most tedious but recommended for the best SDK.
  - Pros:
    - You can define the spec in a correct manner that is more meaningful for a SDK.
    - As you have to define everything here you can pay more attention to breaking changes.
  - Cons:
    - Very tedious, swagger is very verbose, hard to write and validate.
- Use an alternate language: [Cadl](https://github.com/Azure/cadl) (Or some other ones)
  - Pros:
     - all of the aboves
     - much nicer experience: provide live validation in vscode, strict compile, etc.
  - Cons:
    - another language to learn
    - not released yet, might be some breaking changes in the language as we move forward.

**Comment by krptodr** [comment]
Thank you, I can appreciate the time you took to help me out today. I will take a look into those options you provided.
