### ISSUE TITLE
TypeScript generator fails; npm package does not install any files @autorest/typescript 6.0.0-beta.15

### ISSUE THREAD

**Issue by jeremyfiel** [Azure/autorest#4371]
- [x ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x ] have you checked existing issues

trying to generate docs with --typescript and the package installed path does not contain any files or folders; the generator fails.

![image](https://user-images.githubusercontent.com/32110157/142128189-df5022bf-1651-4b76-81ca-29665a09bd07.png)
![image](https://user-images.githubusercontent.com/32110157/142128166-1156b3a0-45ef-42dc-b3ef-c32c4d29568c.png)

```
Please provide as much information as you can. This would be:
- Autorest command used
available in the screenshot
```

**Expected behavior**
I expect the docs to be generated in TypeScript language.

**Comment by timotheeguerin** [comment]
Hi @jeremyfiel, I see the version of core is 3.1.0, can you try updating to the latest by setting `--version=latest`  and running with `--debug --verbose` in case that still fails. Can you also try `autorest --reset` before to make sure the `.autorest` dir is clean.

**Comment by jeremyfiel** [comment]
thanks Timothee. 

![image](https://user-images.githubusercontent.com/32110157/142255144-33dd6926-2ae3-4c74-87ba-30e801e90fb4.png)

i did notice the installed package folder has an underscore in the path where the error is looking for a path without the underscore.

![image](https://user-images.githubusercontent.com/32110157/142255336-5b388112-3b24-4361-9fa5-3221036ec15f.png)

**Comment by timotheeguerin** [comment]
Can you try upgrading the @autorest/core version with `--version=3.6.6` or `--version=latest` on the run?

One common issue that used to happen is if a parent directory to that folder contained a `package.json`. if this is the case it's most likely the issue and the latest core version should resolve this problem.

**Comment by jeremyfiel** [comment]
yep. latest is working and generated the docs as expected

**Comment by timotheeguerin** [comment]
@jeremyfiel is it then not an issue anymore? Can this be closed?

**Comment by jeremyfiel** [comment]
It appears to be working now with latest flag.

Ok to close if you don't want to figure out the earlier version issue.

Thanks

**Comment by timotheeguerin** [comment]
well there isn't going to be any patch for a previous version so if the latest works this is the fix
