### ISSUE TITLE
x-ms-identifiers not allowed when generating ARM template schemas

### ISSUE THREAD

**Issue by leni-msft** [Azure/autorest#4390]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Please provide as much information as you can. This would be:
- OpenAPI files having the issues: https://github.com/leni-msft/azure-rest-api-specs/blob/d76689fc4d/specification/oep/resource-manager/readme.md
- Autorest command used:
```
➜  azure-rest-api-specs git:(pr-17105) autorest --version=3.0.6375 --azureresourceschema --multiapi ~/workspace/azure-rest-api-specs/specification/oep/resource-manager/readme.md --debug
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: 3.0.6375.
debug   | [0.67 s] Network Enabled: true
debug   | [0.74 s] The most recent installed version is 3.7.3
debug   | [0.74 s] Starting @autorest/core from /home/leni/.autorest/@autorestcore@3.0.6375/nodemodules/@autorest/core
   Loading AutoRest core      '/home/leni/.autorest/@autorestcore@3.0.6375/nodemodules/@autorest/core/dist' (3.0.6375)
   Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.103)
Processing batch task - {"tag":"schema-2021-06-01-preview"} .
DEBUG [1.51 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.51 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.51 s]: configuration-emitter - START inputs = 0
DEBUG [1.51 s]: pipeline-emitter - START inputs = 0
DEBUG [1.55 s]: configuration-emitter - END [0.03 s]
DEBUG [1.55 s]: pipeline-emitter - END [0.03 s]
DEBUG [1.59 s]: openapi-document/loader-openapi - END [0.07 s]
DEBUG [1.59 s]: openapi-document/individual/transform - SKIPPING
DEBUG [1.59 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [1.59 s]: openapi-document/individual/identity - SKIPPING
DEBUG [1.68 s]: swagger-document/loader-swagger - END [0.16 s]
DEBUG [1.68 s]: swagger-document/individual/transform - START inputs = 3
DEBUG [1.77 s]: swagger-document/individual/transform - END [0.09 s]
DEBUG [1.77 s]: swagger-document/individual/schema-validator-swagger - START inputs = 3
ERROR: Schema violation: Additional properties not allowed: x-ms-identifiers (definitions > OepProperties > properties > dataPartitionNames)
    - file:///home/leni/workspace/azure-rest-api-specs/specification/oep/resource-manager/Microsoft.OpenEnergyPlatform/preview/2021-06-01-preview/oep.json:668:4
/home/leni/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js - FAILURE {"exitCode":1}
ERROR: Schema violation: Additional properties not allowed: x-ms-identifiers (definitions > OepProperties > properties > dataPartitionNames)
    - file:///home/leni/workspace/azure-rest-api-specs/specification/oep/resource-manager/Microsoft.OpenEnergyPlatform/preview/2021-06-01-preview/oep.json:668:4
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting. / Error: [OperationAbortedException] Error occurred. Exiting.
    at /home/leni/.autorest/@autorestcore@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:7062:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/leni/.autorest/@autorestcore@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:1855:29
    at async ScheduleNode (/home/leni/.autorest/@autorestcore@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:2543:33)
Failure during batch task - {"tag":"schema-2021-06-01-preview"} -- false.
[1.82 s] Shutting Down.
[1.82 s] Exiting.
```

**Expected behavior**
ARM template schemas should be successfully generated without errors.

**Additional context**
This `x-ms-identifiers` is a [new swagger extension](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-identifiers), and it seems the [swagger-extension.json](https://github.com/Azure/autorest/blob/6700485486607bdc4f08f630f9efcafb90567ae9/packages/libs/autorest-schemas/swagger-extensions.json) doesn't define it yet.
CI pipeline output can be found [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1257160&view=logs&j=2b4a2910-f027-53b2-4397-cc9d62dced0f&t=8239b243-d1b9-5f8b-bfeb-b8cea9964242).

**Comment by timotheeguerin** [comment]
@leni-msft I see the core version you are using is old (3.0.6375) a newer version relaxed the validation for unknown extension. Can you first verify that using the latest not complain before we have to do a release for that.

**Comment by leni-msft** [comment]
@timotheeguerin thanks for the reply. I tried the latest core version, it complains plugin `commonmarker` not found:
```
➜  workspace autorest --azureresourceschema --multiapi ~/workspace/azure-rest-api-specs/specification/oep/resource-manager/readme.md  SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/home/leni/.autorest/@autorestcore@3.7.3/nodemodules/@autorest/core/dist' (3.7.3)
info    |    Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.103)
info    | Processing batch task - {"tag":"schema-2021-06-01-preview"} .
info    |    Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.103)
warning | IgnoredPropertyNextToRef | Semantic violation: Sibling values alongside $ref will be ignored. See https://github.com/Azure/autorest/blob/main/docs/openapi/howto/$ref-siblings.md for allowed values (components > schemas > Resource > properties > systemData)
  keys: [ 'readOnly', 'type' ]
fatal   | Process() cancelled due to failure 
error   | Batch/Error | Failure during batch task - {"tag":"schema-2021-06-01-preview"}  -- Error: Plugin 'commonmarker' not found.
error   |   Error: Plugin 'commonmarker' not found.
```

**Comment by leni-msft** [comment]
@timotheeguerin I found the plugin was removed in https://github.com/Azure/autorest/commit/d6091fb497c67909536ec119adbff0ccac62c0e3#diff-f0e2a14b57b9dfaeb85b1447d431bc57003846634f6b538d214e4a235d5907aeL61 , and I could hotfix the issue with latest version `3.5.1` containing `commonmark` . Could you explain why the plugin was removed? and what's the autorest extension which depends on the plugin supposed to do?

**Comment by leni-msft** [comment]
Several different errors found after upgrading autorest/core to `3.5.1` (Search `fatal:` in the [pipeline log](https://dev.azure.com/Azure/azure-resource-manager-schemas/_build/results?buildId=34432&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d)):

The errors could be reproduced with swagger in https://github.com/leni-msft/azure-rest-api-specs/commit/c1427f23380f8358463efe5b82fd28ee4c35b301 :
```
autorest --version=3.5.1 --use=@autorest/azureresourceschema@3.0.103 --azureresourceschema ~/workspace/azure-rest-api-specs/specification/automation/resource-manager/readme.md --multiapi --debug

...
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup, XmsMetadata metadata) in /home/vsts/work/1/s/autorest.common/src/OperationBuilder.cs:line 162
```

```
autorest --version=3.5.1 --use=@autorest/azureresourceschema@3.0.103 --azureresourceschema ~/workspace/azure-rest-api-specs/specification/chaos/resource-manager/readme.md --multiapi --debug

...
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value True to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.schemas:1432.additionalProperties', line 1, position 851643.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /home/vsts/work/1/s/autorest.common/src/SwaggerParser.cs:line 56
```

@timotheeguerin any suggestions?
cc. @anthony-c-martin

**Comment by timotheeguerin** [comment]
Not fully sure what those errors are about(at least the 1st one) as its for the old autorest csharp code. The 2nd one is a long running bug where autorest v2 including this didn't support `additionalProperties: true`

The plugin was removed because it is not needed in Autorest Core V3, didn't realized it was needed by the resource manager extension. Do you know how you are using it? If this is the only extension using it maybe you should include that plugin inside your own extension. Otherwise I should be able to add it back however those errors are going to still be there. There is something else that needs to be resolved.

**Comment by leni-msft** [comment]
The commonmark extension seems to "sanitize" markdown to plain text, according to https://github.com/Azure/autorest/pull/2090/commits/5decd2cc9086a4350fb0f4e9d6e939b4d6bcbf47 , and only takes affect on _DocumentationField_. @anthony-c-martin Do you know if the extension is needed in generating schemas?

Also @timotheeguerin since there're quite several issues with the autorest csharp code, do you think it's okay to hotfix the swagger schema with https://github.com/Azure/autorest/pull/4391 ? and (if necessary? @anthony-c-martin) resolve the issues in the future by upgrading the ARM schemas extension to modelerfour?

**Comment by anthony-c-martin** [comment]
> The commonmark extension seems to "sanitize" markdown to plain text, according to [5decd2c](https://github.com/Azure/autorest/commit/5decd2cc9086a4350fb0f4e9d6e939b4d6bcbf47) , and only takes affect on _DocumentationField_. @anthony-c-martin Do you know if the extension is needed in generating schemas?

I think we could probably get away without sanitizing markdown - it'll probably just make the odd description a bit less readable.

> Also @timotheeguerin since there're quite several issues with the autorest csharp code, do you think it's okay to hotfix the swagger schema with #4391 ? and (if necessary? @anthony-c-martin) resolve the issues in the future by upgrading the ARM schemas extension to modelerfour?

FYI https://github.com/Azure/bicep-types-az/tree/main/src/autorest.bicep is a good starting point for migrating to modelerfour, as it was originally forked from the autorest.azureresourceschema (C#) extension, and then rewritten for modelerfour.

**Comment by leni-msft** [comment]
@timotheeguerin @anthony-c-martin Thanks for the explanation. For now, I'll use `--pass-thru:schema-validator-swagger` to bypass the swagger schema validation while keeping the autorest version unchanged. And I'll rewrite the schema extension based on modelerfour.
