### ISSUE TITLE
Modeler cannot automatically merge models with recursive references

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest#4397]
I was generating DotNet track 2 storage SDK: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/src/autorest.md

Since the `modelerfour.lenient-model-deduplication` is going to be deprecated and it is a potential source of sdk breaking changes, we decide to remove it from all the generated sdks. But if I remove this flag in storage, I will get the duplicate schema issue on CloudError and CloudErrorBody:
![image](https://user-images.githubusercontent.com/10554446/149119059-df6962fd-cc12-4614-b25f-d5b84c504dbe.png)
The CloudError and CloudErrorBody do have two definitions in the set of swagger files:
- first: https://github.com/Azure/azure-rest-api-specs/blob/691920cda83cc0b89a8c821d0bb285100fad22b4/specification/storage/resource-manager/Microsoft.Storage/stable/2021-04-01/blob.json#L1467
- second: https://github.com/Azure/azure-rest-api-specs/blob/691920cda83cc0b89a8c821d0bb285100fad22b4/specification/storage/resource-manager/Microsoft.Storage/stable/2021-04-01/file.json#L1009

These two definitions are identical, but they are all referencing themselves, I believe this is the difference modeler is reporting.

Should we be able to merge these two models?

**Comment by timotheeguerin** [comment]
I am not sure this is worth doing. This gets very complex and would potentially have a very large performance hit.
Even this simplest case is problematic as the `details` type gets extracted as a separate definition at some point so you have 2 duplicate reference to resolve.

```
From file 1:
CloudErrorBody -> CloudErrorBody-Details -> CloudErrorBody
From file 2:
CloudErrorBody -> CloudErrorBody-Details -> CloudErrorBody
```

This could easily be worked around by sharing the same model across the different files and referencing it.

**Comment by ArcturusZhang** [comment]
Thank you @timotheeguerin 
Let me turn to the storage team to see if they could move this to their common.json and remove the extra definition
