### ISSUE TITLE
Make return headers strongly typed in C#

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#440]
* Add HttpOperationResponse with 2 generic arguments - one for body and one for header type
* Update C# generator to generate a header type with a property per header (GetWebsitesResponseHeaders)
* Add tests

**Comment by stankovski** [comment]
Tracking via: https://www.pivotaltracker.com/story/show/107091712

**Comment by matthchr** [comment]
@stankovski This plan sounds good.  Please note here if there is any issues/questions that come up.

Thanks
