### ISSUE TITLE
Represent Named list of strings in autorest swagger

### ISSUE THREAD

**Issue by amitprat** [Azure/autorest#4400]
Before asking the question:

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [X] have you checked existing issues for a similar question?

My backend code returns response in following json format:

```json
{
   "myItems" : ["item1", "item2"]
}
```

I am trying to get the following output in generated c# code using autorest 2.0 so that it can parse above json response body.

```c#
class MyItemsResponse{
  jsonProperty("myItems")
  IEnumerable<string> MyItems;
}

```

I tried following swagger definition for achieve above code generation:

```json
"responses": {
    "200": {
      "schema": {
        "$ref": "#/definitions/MyItemsResponse"
      }
    }
}

"MyItemsResponse": {
  "type": "object",
  "properties": {
    "myItems": {
      "$ref": "#/definitions/Items"
    }
  }
}
"Items": {
  "type": "array",
  "items": {
    "$ref": "#/definitions/ItemName"
  }
}
```
but above code doesn't generate 'MyItemsResponse' in response. Instead it only generate IEnumerable<string> which isn't able to parse the backend response correctly.

Could someone please suggest what is correct way to achieve above result?

**Comment by timotheeguerin** [comment]
Hey @amitprat This looks correct and it should generate that way. Could you share more about the configuration and the logs?

**Comment by amitprat** [comment]
command used:
 autorest .\readme.md --tag=package-xxxx-xx --csharp --version=v2 --reflect-api-versions --csharp-sdks-folder=<target folder>

configuration file:

```yaml $(tag) == 'package-xxxx-xxx'
input-file:
    file1.json
    file2.json
    etc..
```

i tried generating logfile using input (log-file: <filename>), but wasn't able to generate any output from it.

Is there any easy workaround to fix this problem?

**Comment by timotheeguerin** [comment]
@amitprat just tried with this swagger and it generate as you'd expect

```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.0",
    "title": "Test",
    "description": "test"
  },
  "host": "localhost:3000",
  "schemes": ["http"],
  "produces": ["application/json"],
  "consumes": ["application/json"],
  "paths": {
    "/test": {
      "get": {
        "operationId": "doSomething",
        "description": "Do",
        "responses": {
          "200": {
            "description": "ok.",
            "schema": {
              "$ref": "#/definitions/MyItemsResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "MyItemsResponse": {
      "type": "object",
      "properties": {
        "myItems": {
          "$ref": "#/definitions/Items"
        }
      }
    },
    "Items": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ItemName"
      }
    },
    "ItemName": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1031227/150183928-d2051318-8ca2-480c-b719-1be56c209aa0.png)

Are you sure you don't have any other configs or values in the swagger that could cause this(like `x-ms-pageable` or `x-ms-flatten`)

**Comment by amitprat** [comment]
Thank you so much Timothee.

I had following header under response which seems to be causing problem. After removing it, i got the expected code generation.

```json
"x-ms-pageable": {
          "nextLinkName": null
        }
```

Just wondering, is there a way to get the array/list response paginated in above response format?

**Comment by timotheeguerin** [comment]
x-ms-pageable has 2 features:
1. Define continuation token pagination. `nextLinkName` defines the property name for the next link.
2. Can flatten the object and return an array directly(Issue you were having)

To use pagination you need to have a property providing the next link See the docs for details https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-pageable

**Comment by amitprat** [comment]
Thank you Timothee.
