### ISSUE TITLE
error   |   Error: ENAMETOOLONG: name too long, open [DUE TO:] [WINDOWS limitation of 255 chars / path segment length] [Linux limitation of 255 chars / path length]

### ISSUE THREAD

**Issue by ader1990** [Azure/autorest#4410]
Hello,

I have tried to generate the csharp code from a swagger that has a pretty deep level of nesting and got this error:

```bash

autorest readme.md --csharp

>> error I got:
error   |   Error: ENAMETOOLONG: name too long, open 'C:/swagger/generated/Models/ComponentsPidniwSchemasNfadevicePropertiesSpecPropertiesDeviceEos4271FPropertiesNetworkinstanceItemsPropertiesProtocolItemsPropertiesBgpPropertiesRibPropertiesAfisafiItemsPropertiesIpv4UnicastPropertiesLocribPropertiesRouteItemsPropertiesUnknownattributeItems.cs'
```
This issue looks like a regression of https://github.com/Azure/autorest/issues/3474

I have tried with the latest version of autorest. The version from https://github.com/Azure/autorest/issues/3474 just blocks, probably it is not supported anymore by the dotnet version I have installed.

Thank you.

**Comment by ader1990** [comment]
@fearthecowboy @pakrym

**Comment by ader1990** [comment]
I used the following versions for the reproduction:

```bash
# also fails with the stable version
node --version
v17.4.0

# autorest
# AutoRest code generation utility [cli version: 3.5.1; node: v14.16.1]
# also AutoRest code generation utility [cli version: 3.5.1; node: v17.4.0]

dotnet --version
5.0.202
```

**Comment by timotheeguerin** [comment]
Hi @ader1990, do you have long paths enabled on windows? Are you also able to make this basic node script work, I think the difference here compared to the other one is that this is on windows and windows has path lengths issues.

```js
const fs = require("fs");

const path = "C:/swagger/generated/Models/ComponentsPidniwSchemasNfadevicePropertiesSpecPropertiesDeviceEos4271FPropertiesNetworkinstanceItemsPropertiesProtocolItemsPropertiesBgpPropertiesRibPropertiesAfisafiItemsPropertiesIpv4UnicastPropertiesLocribPropertiesRouteItemsPropertiesUnknownattributeItems.cs"

fs.writeFileSync(path, "foo");
```

I am not despite the folder `C:/swagger/generated/Models` existing. However if I reduce the length of the file it works fine. But I do get a different error `ENOENT: no such file or directory`

Could you also share the logs with `--debug --verbose` enabled?

**Comment by ader1990** [comment]
Hello,

First of all, long paths are enabled on the system, I run Windows 10 with the latest updates.

I have the same issue right now on Windows, I have built latest nodejs from source, and used the --preview for autorest:

```bash

Error: ENOENT: no such file or directory, open 'C:\t\generated\Models\Components15SyogiSchemasKPropertiesSpecPropertiesDeviceEos4271FPropertiesNetworkinstanceItemsPropertiesProtocolItemsPropertiesBgpPropertiesRibPropertiesAfisafiItemsPropertiesIpv4UnicastPropertiesNeighborItemsPropertiesAdjribinpostPropertiesRouteItemsPropertiesUnknownattributeItems.cs'
```
I ran your script and it fails with the error `ENOENT: no such file or directory`.

**Comment by ader1990** [comment]
I verified and this is the breaking point length:

```bash

# fails
const path = 'C:/t/generated/Models/ComponentsYv3Rz6SchemasKPropertiesStatusPropertiesDeviceEos4271FPropertiesNetworkinstanceItemsPropertiesProtocolItemsPropertiesIsisPropertiesLevelItemsPropertiesLspItemsPropertiesTlvItemsPropertiesMtisnPropertiesNeighborItemsPropertiesInstanceItems-2345.cs'

# does not fail
const path = 'C:/t/generated/Models/ComponentsYv3Rz6SchemasKPropertiesStatusPropertiesDeviceEos4271FPropertiesNetworkinstanceItemsPropertiesProtocolItemsPropertiesIsisPropertiesLevelItemsPropertiesLspItemsPropertiesTlvItemsPropertiesMtisnPropertiesNeighborItemsPropertiesInstanceItems-234.cs'
```

For 277 characters works, 278 chars does not work anymore.

**Comment by timotheeguerin** [comment]
If you notice the 1st one the filename is 256 char long and the 2nd is 255 which as far as I can tell is still the limit for path segments regardless of the total path limit.

If you just try to create the file in windows it will fail as well.
![image](https://user-images.githubusercontent.com/1031227/153029044-378eddef-7e64-47a0-bb45-8767d0568686.png)

There isn't anything autorest can do here unless this isn't the case. That filename anyway must be due to a very nested set of anonymous definitions which have no names and would result in a terrible SDK.
