### ISSUE TITLE
Autorest reports error in valid OpenAPI v2 file

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest#4424]
**Describe the bug**

Autorest fails on a valid OpenAPI v2 file.  It seems to expect `info` at the top level to be a boolean.

```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>autorest --python bug.json 
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.17.6]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/Users/mikekistler/.autorest/@autorestcore@3.7.5/nodemodules/@autorest/core/dist' (3.7.5)
error   | [OperationAbortedException] Error occurred. Exiting.
error   |   Error: [OperationAbortedException] Error occurred. Exiting.
error   | invalidType | Expected a boolean but got object: {
  title: 'Bug',
  version: '2022-02-13',
  description: 'Valid OpenAPI v2',
  contact: { email: 'foo@bar.com' }
}
    - file:///Users/mikekistler/Projects/autorest-test/bug.json:3:3
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>
```

Input file is attached. 

[bug.json.txt](https://github.com/Azure/autorest/files/8056031/bug.json.txt)

**Expected behavior**

Autorest should process any valid OpenAPI v2 file, or clearly explain what feature is not supported.

**Comment by timotheeguerin** [comment]
I am not able to reproduce this error with the file you shared using the same core version. Is this exactly what was failing?

**Comment by mikekistler** [comment]
Hmmm. Then something in my environment is causing this?

BTW ... I realized that I had not done `autorest --reset` before trying this, but after doing that the problem still occurs (for me).

My environment:
- OS: MacOS Version 11.6.3
- node: v14.17.6
- npm: 6.14.15     
- dotnet: 3.1.416

Any of this look suspicious?  Any other information I should gather?

**Comment by timotheeguerin** [comment]
You shouldn't really need `autorest --reset` anymore.

Nothing jumps out of the ordinary.
Can you rerun with `--debug --verbose` might have more info.

**Comment by mikekistler** [comment]
Not much more info from that:
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>autorest --debug --verbose --python bug.json
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.17.6]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
debug   | [0.64 s] Network Enabled: true
debug   | [1.20 s] The most recent installed version is 3.7.6
debug   | [1.20 s] Starting @autorest/core from /Users/mikekistler/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/Users/mikekistler/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist' (3.7.6)
verbose | [0.63 s]    Initial configuration file 'file:///Users/mikekistler/Projects/autorest-test/bug.json'
verbose | [0.63 s]    Including configuration file 'file:///Users/mikekistler/Projects/autorest-test/bug.json'
error   | [OperationAbortedException] Error occurred. Exiting.
error   |   Error: [OperationAbortedException] Error occurred. Exiting.
debug   | [0.63 s] Shutting Down.
error   | invalidType | Expected a boolean but got object: {
  title: 'Bug',
  version: '2022-02-13',
  description: 'Valid OpenAPI v2',
  contact: { email: 'foo@bar.com' }
}
    - file:///Users/mikekistler/Projects/autorest-test/bug.json:3:3
debug   | [0.63 s] Exiting.
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>
```

**Comment by timotheeguerin** [comment]
oh..., its because of how you are using the file. `autorest --input-file=bug.json` here it treats the bug.json as the configuration file.

**Comment by timotheeguerin** [comment]
and `info: true|false` is a config flag

**Comment by mikekistler** [comment]
Hmmm.  Okay, but I think we should give a better error message in this case.

As for using `--input-file`, that does get me past the previous problem, but then I hit a new one:
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>autorest --python --input-file=bug.json
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.17.6]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/Users/mikekistler/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist' (3.7.6)
info    |    Loading AutoRest extension '@autorest/python' (latest->5.12.6)
info    |    Loading AutoRest extension '@autorest/modelerfour' (~4.19.1->4.19.3)
Executing: /Users/mikekistler/.autorest/@autorest_python@5.12.6/node_modules/@autorest/python/venv/bin/python3.9 -m autorest.jsonrpc.server
error   | JsonSpec/SyntaxError | Syntax Error Encountered:  Unexpected token } in JSON
    - file:///Users/mikekistler/Projects/autorest-test/bug.json:44:9
error   | JsonSpec/SyntaxError | Syntax Error Encountered:  Unexpected token } in JSON
    - file:///Users/mikekistler/Projects/autorest-test/bug.json:44:9
fatal   | Process() cancelled due to failure 
error   |   Error: The 'title' across provided OpenAPI definitions has to match. Found: 'Bug', 'Polymorphism'. Please adjust or provide an override (--title=...).
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>
```

I'm only giving one input file, and that input file only has one title.
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>grep title bug.json       
    "title": "Bug",
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>
```

I _do_ have another API definition in this directory with `title: Polymorphism`
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>grep title openapi.json
    "title": "Polymorphism",
[mikekistler@Mikes-MacBook-Pro] ~/Projects/autorest-test>
```

but I don't reference it from bug.json -- so why would autorest be looking at it?

**Comment by timotheeguerin** [comment]
do you have a readme.md in the cwd? with input-file defined in there. 

It is a bit confusing but I am not sure how it can give a better message, it validate the parameter is a valid configuration file, can't really know that you passed a swagger file instead. I guess could try to see if it looks like swagger/openapi and give an error here.

**Comment by mikekistler** [comment]
Yes there is a readme.md in cwd.  So autorest looks at this file even if I did not ask it to?  Hmmm ... that also seems like it is contrary to what users would expect.

Thank you for helping to puzzle this out.  I need to think about how we could make it better.

**Comment by timotheeguerin** [comment]
yeah autorest always look for the config `readme.md` in the current working directory unless you pass the config file via the command line. 
It is similar to how a lot of other tools will look for a config file in the current working directory.

**Comment by mikekistler** [comment]
Okay, I guess this is just a newbie error on my part, but there might be lots of newbies using our tools soon so we should try to be as newbie-friendly as possible.  I propose:
- checking the configuration file for either `swagger:` or `openapi:` and reporting that _before_ the check on `info:`
- Add this to the `troubleshooting.md` -- if you see this message the likely error is ...
- If the configuration file is not supplied, print a message to say what it was defaulted to.  There is a message when `--verbose` is enabled, but when it is defaulted it should be printed even without `--verbose`.
