### ISSUE TITLE
"type: oauth2" is enough to deduce AAD is needed for autorest

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#4426]
Instead of looking for a hardcoded name AADToken

cc @mikekistler @schaabs

**Comment by timotheeguerin** [comment]
well oauth2 means we can have any authorization server. AADToken means it needs to be AAD. I think that would be a wrong assumption to do that.

**Comment by timotheeguerin** [comment]
If the generators actually support any OAuth2 authority then we should rename the type if modelerfour as well to just be OAuth2

**Comment by mikekistler** [comment]
My understanding (feeble at best) is that the _generator_ only needs to know that the authorization is "token based" -- which I think is the same as saying that it is Oauth2.  All the other details are handed by the TokenCredential class (not generated).  But I could be wrong here ...

**Comment by timotheeguerin** [comment]
I'll bring this up to the autorest scrum this week. The reason I made this being specific to AAD was the current implemnetation with each generator having their own flags used some AAD naming for the flag.
