### ISSUE TITLE
Include Swagger Operation ID in modeler4 model

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest#4427]
As part of our plans to tie Swagger PRs to language-specific APIViews, one of the things we need is a "CrossLanguageReferenceID" that is the same across languages. The only source of truth for these is Swagger, but currently modeler4 applies transformations to the Operation IDs in the Swagger to determine names. For operations, we need the raw Operation ID from the Swagger to be preserved in the modeler4 model alongside the transformed, language-specific name so the language-specific Autorest plugins can pass that information along to their corresponding APIView extension.

cc/ @lmazuel, @johanste, @iscai-msft

**Comment by iscai-msft** [comment]
@timotheeguerin I know you mentioned yesterday that operation id doesn't always exist, so in the case where operation id doesn't exist for a swagger, we can use tags instead
