### ISSUE TITLE
If anything in autorest fails, make sure we aka.ms / give indication on where to declare the issues

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#4442]

**Comment by timotheeguerin** [comment]
This is just the case where we get an unexpected error? Not sure want to encourage reporting issue if it is clearly a user error.

**Comment by lmazuel** [comment]
Any bad status code you get from a plugin, we should have a sentence at the end.

Your plugin ended with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing
