### ISSUE TITLE
ability to handle combination of multiple swaggers in v3

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4443]
**Is your feature request related to a problem? Please describe.**
our [linter](https://github.com/Azure/azure-openapi-validator)  is based on autorest v2 which provides the ability to merge multiple swagger into one swagger , While we want to migrate our linting to autorest v3, this missing feature blocks us , as the linter tool is designed to handle swagger one by one.

below kind of  linting rules  rely on this feature:
1. need to check another swagger when linting one swagger
   swagger A defines a resource foo,  but operation of this resouce defines in B ,  when linting A we need to check B as well 
2.  need to check duplicate model name or operationId  or other property names among multiple swaggers
3. need to check  some operations/resources/other entities are defined in one/any of the swaggers 

**Describe the solution you'd like**
A similar merging mechanism is good for us , so that  we don't need modify our existing linting rule logic when migrating to autorest v3 , but need to figure out a way to handle conflict ( I know autorest M4 already support detect some conflicts ,and have a solution , like give it a generated name)

**Describe alternatives you've considered**
one way is to navigate swaggers one by one, but needs to have a big change on our existing rule logic 
I know autorest has some functions to do the navigation, if it can be more general and exported , we can benefit from it

**Comment by timotheeguerin** [comment]
This seems to me like this can be relatively completed by just iterating over all the input files.
1. How is the operation and the resource linked? How do you check the operation is the correct one? Is it just that it $ref the resource definition?
2. Feels like this is pretty basic and should just be able to add the iteration of the input files with no other changes
3. Also seems like this would just be a question of adding the iteration of all the input files.

**Comment by timotheeguerin** [comment]
My point is that for 2. and 3. there isn't much I can provide to make it easier. The change is super simple. For 1. wondering what can be done to help with that check.
Making a merged swagger will NOT happen in core, the file cannot be a correct representation of all the input files. There is no point doing this just for the linter when fixing the rules is much simpler. If having that merged swagger file is really the way to go then I suggest you implement that in the linter. 

My goal here is to see if there is some helper that can help navigate multiple files like providing a `getRef(ref): Schema`  which works cross file.

**Comment by jianyexi** [comment]
For 1, you are right, it happens when an operation in anther swagger is referring the resource definition , so when linting current file,  we need to check the swaggers that are referring this resource, I wonder if you have some ideas with it, 
Currently I can scan all the swaggers in linter to find this relationships

**Comment by jianyexi** [comment]
I will implement this feature in the linter plugin , so close it
