### ISSUE TITLE
ability to get resolved swagger in v3

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4444]
**Is your feature request related to a problem? Please describe.**
current  [ swagger linter](https://github.com/Azure/azure-openapi-validator)  is based on the output swagger emitted by autorest v2 internal pipeline , 
autorest v2 used to resolve the external reference in a special way :  convert the external reference into local reference
but one bad effect is that it's possible to override the local model with the same name. 

**Describe the solution you'd like**
just like v2 , the ability to emit an resolved swagger to autorest plugin is necessary

**Describe alternatives you've considered**
provide an API that can return the resolved external model 
input : ../../../../../common-types/resource-management/v2/types.json#/definitions/Resource
output:
```
"Resource": {
      "title": "Resource",
      "type": "object",
      "properties": {
        ...
    }
```

**Comment by timotheeguerin** [comment]
This one should be easy to do by just taking the OAI2 converter helpers out.

**Comment by timotheeguerin** [comment]
What I suggest here is we can have interface like that
```ts
interface SwaggerFile {
   path: string;  // Absolute path. This should already have been resolved by autorest by that point
   spec: OpenAPI2Spec;
}

function createSwaggerWorkspaces(files: SwaggerFile[]) : SwaggerWorkspace;


interface SwaggerWorkspace {
   getRef<T>(ref: string): T;
}
```

**Comment by jianyexi** [comment]
Wonder if the getRef can has an option to return either a fully resolved (also resolve the child level $refs) schema or a resolved schema which only resolve the top level "$refs" , because sometimes we need to keep the child $refs

**Comment by timotheeguerin** [comment]
I could potentially do a full expansion
