### ISSUE TITLE
Improve performance for autorest cli 

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4445]
**Is your feature request related to a problem? Please describe.**
the CLI seems to take a lot of time to load autorest core and plugin in every runs,  as you can see below run , it take 1.8s before starting run the plugin,  if we want to implement a swagger linter base autorest , it can not bring good experience, as most swagger linter like spectral is  very fast , 

```
 > You can install the newer version with with npm install -g autorest@latest

debug   | [1.51 s] Starting @autorest/core from C:\Users\jianyxi\.autorest\@autorestcore@3.7.6\nodemodules\@autorest\core
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      'C:\Users\jianyxi\.autorest\@autorestcore@3.7.6\nodemodules\@autorest\core\dist' (3.7.6)
verbose | [1.08 s] No configuration found at 'file:///D:/codes/openapi-env-test/'.
verbose | [1.09 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/default-configuration.md'
verbose | [1.13 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/inspect.md'
verbose | [1.14 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/directives.md'
verbose | [1.16 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/pipeline.md'
verbose | [1.19 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/loader-openapi.md'
verbose | [1.21 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/miscellaneous.md'
verbose | [1.24 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-powershell.md'
verbose | [1.25 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-azureresourceschema.md'
verbose | [1.27 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-csharp.md'
verbose | [1.30 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-go.md'
verbose | [1.31 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-java.md'
verbose | [1.33 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-nodejs.md'
verbose | [1.35 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-php.md'
verbose | [1.37 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-python.md'
verbose | [1.39 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-ruby.md'
verbose | [1.40 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-typescript.md'
verbose | [1.42 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-validators.md'
verbose | [1.45 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-az.md'
verbose | [1.47 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-terraform.md'
verbose | [1.49 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-azure-functions.md'
verbose | [1.52 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/graphs.md'
verbose | [1.54 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/help-configuration.md'
debug   | [1.64 s] azure:@azure-tools/extension:error Error resolving package C:\Users\jianyxi\.autorest\@autorestcore@3.7.4\node_modules\@autorest\core Error: ENOENT: no such file or directory, open 'C:\Users\jianyxi\.autorest\@autorest_core@3.7.4\nodemodules\@autorest\core\package.json'
info    |    Loading AutoRest extension '@microsoft.azure/openapi-validator' (^1.7.0->1.12.1)
verbose | [1.69 s]    Including extension configuration file 'file:///C:/Users/jianyxi/.autorest/@microsoft.azureopenapi-validator@1.12.1/nodemodules/@microsoft.azure/openapi-validator/readme.md'
verbose | [1.69 s]    Including configuration file 'file:///C:/Users/jianyxi/.autorest/@microsoft.azureopenapi-validator@1.12.1/nodemodules/@microsoft.azure/openapi-validator/readme.md'
```

**Describe the solution you'd like**
1 can simplify the loading , may be we can have static autorest CLI which do not need to load autorest/core dynamic
2 autorest can run typescript plugin in its own process , not launch a new process . this can fast plugin as well

**Comment by timotheeguerin** [comment]
Option 1 is not possible it defeats the entire architecture of autorest.
Option 2 could be something we consider but I don't think this is what really brings down performance.

How are the linter expected to run? The linter, autorest core got to be installed some way or another. It is the type to run a `npm install @autorest/core`. It should however be very quick after the 1st use. The alternative to this is to install core and extension in a package.json where running autorest and running `npm install` separately then the Autorest CLI can use those versions.

Also note that you were using a very old CLI version. There has been many perf and UI improvement to help user see what is happening since.

**Comment by jianyexi** [comment]
this is run by latest autorest , not sure if I was running as  you mentioned , but seem there is no difference and the internal pipeline is too long for us , and takes 1.6s to load all the plugins and take a 5.8  before run into my plugin 
``` 
package.json
{
  "name": "linter",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@autorest/core": "^3.7.6",
    "autorest": "^3.5.1"
  }
}
``

```
PS D:\codes\contoso\linter> npx autorest --azure-validator  --v3 --use=C:\code\azure-openapi-validator\src\typescript --input-file=D:/codes/openapi-env-test/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json --message-format=json --debug
SourceMapConsumer.initialize is a no-op when running in node.js
{"level":"information","message":"AutoRest core version selected from configuration: \u001b[33m\u001b[1m^3.2.0\u001b[22m\u001b[39m."}
{"level":"debug","message":"Network Enabled: true","uptime":"1.03"}
{"level":"debug","message":"The most recent installed version is 3.7.6","uptime":"1.55"}
{"level":"debug","message":"Starting @autorest/core from C:\\Users\\jianyxi\\.autorest\\@autorest_core@3.7.6\\node_modules\\@autorest\\core","uptime":"1.55"}
SourceMapConsumer.initialize is a no-op when running in node.js
{"level":"verbose","message":"No configuration found at 'file:///D:/codes/contoso/linter/'.","uptime":"1.09"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/default-configuration.md'","uptime":"1.11"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/inspect.md'","uptime":"1.14"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/directives.md'","uptime":"1.15"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/pipeline.md'","uptime":"1.16"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/loader-openapi.md'","uptime":"1.19"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/miscellaneous.md'","uptime":"1.21"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-powershell.md'","uptime":"1.23"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-azureresourceschema.md'","uptime":"1.24"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-csharp.md'","uptime":"1.26"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-go.md'","uptime":"1.29"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-java.md'","uptime":"1.32"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-nodejs.md'","uptime":"1.34"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-php.md'","uptime":"1.36"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-python.md'","uptime":"1.37"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-ruby.md'","uptime":"1.40"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-typescript.md'","uptime":"1.42"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-validators.md'","uptime":"1.45"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-az.md'","uptime":"1.48"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-terraform.md'","uptime":"1.51"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/plugin-azure-functions.md'","uptime":"1.54"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/graphs.md'","uptime":"1.57"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/Users/jianyxi/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/resources/help-configuration.md'","uptime":"1.58"}
{"level":"information","message":"> Loading local AutoRest extension '@microsoft.azure/openapi-validator' (C:/code/azure-openapi-validator/src/typescript)"}
{"level":"verbose","message":"> Including extension configuration file 'file:///C:/code/azure-openapi-validator/src/typescript/readme.md'","uptime":"1.65"}
{"level":"verbose","message":"> Including configuration file 'file:///C:/code/azure-openapi-validator/src/typescript/readme.md'","uptime":"1.65"}
{"level":"debug","message":"swagger-document/loader-swagger - START inputs = 0","uptime":"2.20"}
{"level":"debug","message":"openapi-document/loader-openapi - START inputs = 0","uptime":"2.20"}
{"level":"debug","message":"pipeline-emitter - START inputs = 0","uptime":"2.21"}
{"level":"debug","message":"configuration-emitter - START inputs = 0","uptime":"2.21"}
{"level":"debug","message":"pipeline-emitter - END [0.02 s][75 MB]","uptime":"2.21"}
{"level":"debug","message":"configuration-emitter - END [0.02 s][75 MB]","uptime":"2.21"}
{"level":"verbose","message":"Reading OpenAPI 2.0 file file:///D:/codes/openapi-env-test/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json","uptime":"2.32"}
{"level":"debug","message":"openapi-document/loader-openapi - END [0.13 s][77 MB]","uptime":"2.34"}
{"level":"debug","message":"openapi-document/individual/transform - SKIPPING","uptime":"2.65"}
{"level":"debug","message":"openapi-document/individual/schema-validator-openapi - SKIPPING","uptime":"2.65"}
{"level":"debug","message":"openapi-document/individual/identity - SKIPPING","uptime":"2.65"}
{"level":"debug","message":"swagger-document/loader-swagger - END [0.78 s][107 MB]","uptime":"2.97"}
{"level":"debug","message":"swagger-document/individual/transform - START inputs = 1","uptime":"2.97"}
{"level":"debug","message":"swagger-document/individual/transform - END [0.05 s][118 MB]","uptime":"3.02"}
{"level":"debug","message":"swagger-document/individual/schema-validator-swagger - START inputs = 1","uptime":"3.02"}
{"level":"debug","message":"swagger-document/individual/schema-validator-swagger - END [0.38 s][92 MB]","uptime":"3.41"}
{"level":"debug","message":"swagger-document/identity - START inputs = 1","uptime":"3.41"}
{"level":"debug","message":"swagger-document/individual/identity - START inputs = 1","uptime":"3.41"}
{"level":"debug","message":"swagger-document/identity - END [0 s][92 MB]","uptime":"3.41"}
{"level":"debug","message":"swagger-document/individual/identity - END [0 s][92 MB]","uptime":"3.41"}
{"level":"debug","message":"openapi-document/openapi-document-converter - START inputs = 1","uptime":"3.41"}
{"level":"debug","message":"swagger-document/openapi-validator - START inputs = 1","uptime":"3.41"}
{"level":"debug","message":"openapi-document/openapi-document-converter - END [0.29 s][112 MB]","uptime":"3.70"}
{"level":"debug","message":"openapi-document/transform - START inputs = 1","uptime":"3.70"}
{"level":"debug","message":"openapi-document/transform - END [0.06 s][125 MB]","uptime":"3.77"}
{"level":"debug","message":"openapi-document/semantic-validator - START inputs = 1","uptime":"3.77"}
{"level":"debug","message":"openapi-document/semantic-validator - END [0.02 s][134 MB]","uptime":"3.79"}
{"level":"debug","message":"openapi-document/allof-cleaner - START inputs = 1","uptime":"3.79"}
{"level":"debug","message":"openapi-document/allof-cleaner - END [0.06 s][139 MB]","uptime":"3.86"}
{"level":"debug","message":"openapi-document/tree-shaker - START inputs = 1","uptime":"3.86"}
{"level":"debug","message":"openapi-document/tree-shaker - END [0.65 s][193 MB]","uptime":"4.51"}
{"level":"debug","message":"openapi-document/multi-api-merger - START inputs = 1","uptime":"4.52"}
{"level":"debug","message":"openapi-document/multi-api-merger - END [0.56 s][253 MB]","uptime":"5.09"}
{"level":"debug","message":"openapi-document/components-cleaner - START inputs = 1","uptime":"5.09"}
{"level":"debug","message":"openapi-document/components-cleaner - END [0.5 s][312 MB]","uptime":"5.60"}
{"level":"debug","message":"openapi-document/component-modifiers - START inputs = 1","uptime":"5.60"}
{"level":"debug","message":"openapi-document/component-modifiers - END [0.14 s][212 MB]","uptime":"5.74"}
{"level":"debug","message":"openapi-document/api-version-parameter-handler - START inputs = 1","uptime":"5.75"}
{"level":"debug","message":"openapi-document/api-version-parameter-handler - END [0 s][213 MB]","uptime":"5.75"}
{"level":"debug","message":"openapi-document/profile-filter - START inputs = 1","uptime":"5.75"}
{"level":"debug","message":"openapi-document/profile-filter - END [0 s][213 MB]","uptime":"5.75"}
{"level":"debug","message":"openapi-document/model-deduplicator - START inputs = 1","uptime":"5.75"}
{"level":"verbose","message":"Validating 'file:///D:/codes/openapi-env-test/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json'","uptime":"5.87"}
{"level":"fatal","message":"Failed validating: 'file:///D:/codes/openapi-env-test/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json', error encountered: TypeError: Cannot read property 'properties' of undefined"}
{"level":"debug","message":"swagger-document/openapi-validator - END [2.63 s][214 MB]","uptime":"6.05"}
{"level":"debug","message":"openapi-document/model-deduplicator - END [7.76 s][344 MB]","uptime":"13.51"}
{"level":"debug","message":"openapi-document/compose - START inputs = 1","uptime":"13.51"}
{"level":"debug","message":"openapi-document/compose - END [0.67 s][400 MB]","uptime":"14.19"}
{"level":"debug","message":"openapi-document/identity - START inputs = 1","uptime":"14.19"}
{"level":"debug","message":"openapi-document/identity - END [0 s][400 MB]","uptime":"14.19"}
{"level":"debug","message":"openapi-document/emitter - START inputs = 1","uptime":"14.19"}
{"level":"debug","message":"openapi-document/emitter - END [0 s][400 MB]","uptime":"14.19"}
{"level":"debug","message":"Clearing Folders.","uptime":"14.19"}
{"level":"debug","message":"Writing Outputs.","uptime":"14.19"}
{"level":"information","message":"Generation Complete"}
{"level":"debug","message":"Shutting Down.","uptime":"14.19"}
{"level":"debug","message":"Exiting.","uptime":"14.20"}
```

**Comment by timotheeguerin** [comment]
Ok so the local dependency. thing doesn't seem to work. Will look into this.
However this is. the performance I am seeing:

1. A fresh run after running `autorest --reset` is coming down to ~1s for autorest core to be started but then the validator extension is taking a long time to intall `~9s`
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1031227/156608970-00a82e2c-b54f-420d-976b-5df1fa5b3950.png">

To speed up the install of your package you can do the same as core and modelerfour do which is create a single output file with no dependency. What really takes a while is for `npm` or `yarn` to resolve the package dependency tree. 

2. On a following. run it completes in 1.5s and start the pipeline in 1s. 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1031227/156609116-3cdd9880-5348-44a3-a439-fe202e042c06.png">
