### ISSUE TITLE
Failed resolving '%cd%' against <path>

### ISSUE THREAD

**Issue by vreddyb** [Azure/autorest#4446]
When i am trying to run autorest to generate client libraries from api docs json file, i get this error "**Failed resolving '%cd%' against <C:/Users/<MyFolder>"** If i just type in autorest also i get the same error. I believe some configuration is missing somewhere. I tried to reinstall the autorest still the same issue. 
I tried with autorest core versions @3.7.6, @3.0.6320 & autorest versions 3.5.1 and 3.4.2

**Comment by timotheeguerin** [comment]
Hi @vreddyb can you share more information;
- The exact command line used
- The `.md` configuration if any
- Operating system
- Node version
- Full logs with `--debug --verbose`

**Comment by vreddyb** [comment]
the error was  appearing because there was a folder with “%cd%” in the parent of package folder. it worked fine after deleting this folder.
