### ISSUE TITLE
Install autorest link broken

### ISSUE THREAD

**Issue by piyushdubey** [Azure/autorest#4453]
**Before filling a bug**

- [ Y] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ Y] have you checked existing issues

**Describe the bug**
The link to autorest install page is broken on readme.md under [synapse data-plane](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/synapse/data-plane) folder.

```
This would be:
- Documentation
```

**Expected behavior**
The actual issue is that the link to https://aka.ms/autorest/install points to https://github.com/Azure/autorest/blob/main/README.md#installing-autorest instead of https://github.com/Azure/autorest/blob/main/docs/install/readme.md which is the correct location of autorest install instructions page.

**Comment by timotheeguerin** [comment]
@piyushdubey sorry about the delay on this one, this link permissions got some issues and took a while to get access fixed. The link should be updated now.
