### ISSUE TITLE
Why do you use text-based `.md` file for configuration?

### ISSUE THREAD

**Issue by Invertisment** [Azure/autorest#4457]
We were trying to discover some details about the autorest-based generator code from an existing codebase and somehow all generation was working magically.
It really seemed like pure magic.

We couldn't figure out why was it working without any command-line options and config files.

But then we looked up in the internet that you provide a `README.md`-based configuration file (which is also implicitly loaded from working directory).
Which immediately triggered the WTFs because we didn't even think to look in that file.
We know it's only text and shouldn't do anything. But it did. It contained YAML-based configuration which was the most important piece of the code.

Is it possible to have configuration option where you could specify a YAML config file to use (`autorest --config=config.yaml`)? Because it's not only that `.md` parser slows down the start-up (marginally) but it's very misleading.

Do you think it's a good idea?

**Comment by timotheeguerin** [comment]
The config file can also be a yaml file. The reason it is markdown dates quite a while back and can't really say the full reasoning for that. One of the "advantage" of the markdown file is each code block can provide guard `yaml $(typescript)` so that config block only get loaded if the guard is true letting you have different config depending on which cli flags are passed.

**Comment by Invertisment** [comment]
But if you provide one command line flag then why not provide all of them... Or choose between configs which would be source-controlled in separate files instead of one file.

When I run `autorest --help` I get this as one of the output lines:

```
Usage: autorest [configuration-file.md] with [...options]
```
So it suggests that the config should be in `.md`.

Version:
```
autorest --version
AutoRest code generation utility [cli version: 3.5.1; node: v17.6.0]
```

**Comment by timotheeguerin** [comment]
You are free to do that if you prefer but the current one unlocks quite a complex configuration system and ability to reuse configuration much more without creating a million files. You can check example in the azure rest api sepcs repo where this is heavily used for things like specifying the different version 
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/compute/resource-manager/readme.md
