### ISSUE TITLE
should not convert local reference to absolute reference 

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4475]
the swagger emitted by below , transformed the '#/definition/foo' to 'file:///\<absolute path\>#defintion/foo'
``` 
input: swagger-document/loader-swagger
```
this convert is useless, brings trouble to external tool . Also it increase the size of the swagger 
**Expected behavior**
keep local reference

**Additional context**

**Comment by timotheeguerin** [comment]
this should not be the case anymore with the latest version of core 3.8.0

**Comment by jianyexi** [comment]
Seem the latest swagger-loader only resolves the refs for x-ms-examples , this seems not expected behaviors
