### ISSUE TITLE
empty "source" in message  

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4481]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

when there is the "jsonpath in the message which is emitted by plugins , the output message would be constituted with  empty 'source', for example
Message emitted by linter
```
  {
  Channel: "error",
  Text: "The schema 'operationListResult' is considered an object but without a 'type:object', please add the missing 'type:object'.",
  Key: [
    "MissingTypeObject",
  ],
  Source: [
    {
      document: "file:///C:/code/azure-rest-api-specs/specification/resourcehealth/resource-manager/Microsoft.ResourceHealth/stable/2020-05-01/ResourceHealth.json",
      Position: {
        path: [
          "$",
          "definitions",
          "operationListResult"
        ],
      },
    },
  ],
  Details: {
  },
}
```
output by autorest 

```
{
  "pluginName": "spectral",
  "extensionName": "@microsoft.azure/openapi-validator",
  "level": "error",
  "message": "The schema 'operationListResult' is considered an object but without a 'type:object', please add the missing 'type:object'.",
  "code": "MissingTypeObject",
  "details": {
  },
  "source": []
}

```

**Expected behavior**
the jsonpath would be converted into  source location info which contains column and line 

**Additional context**

**Comment by timotheeguerin** [comment]
@jianyexi I see potentially 2 issues with the source you reported:
1. The document shouldn't be that, it should be the `key` of the DataHandle. For example in the schema validation it is looking something like that `mem:///113?file%3A%2F%2F%2FC%3A%2Fdev%2Fazsdk%2Fplayground%2Fswagger.yaml`. Or if you are ussing the `@autorest/extension-base` package this is also the value of the Session filename
2. The path is also wrong: Should not have teh `$` to start and then is there also not a casing issue with `operationListResult`?

**Comment by jianyexi** [comment]
Thanks, after use remove the `$` , it works

**Comment by jianyexi** [comment]
there is a reproduce for this issue, when the path contains "x-ms-examples"

**Comment by jianyexi** [comment]
@timotheeguerin another case is that if the error location is in the reference file of the input-file, the output source will be empty as well
