### ISSUE TITLE
Autorest sorting is inconsistent based on host platform

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest#4488]
**Describe the bug**

In today's LLC Scrum, @pshao25 reported that autorest sorts fields containing "_" and "$" in different orders when run in Windows vs in CI (presumably on Linux). 

**Expected behavior**

Autorest sorting should be consistent across all platforms.

**Additional context**

**Comment by pshao25** [comment]
An example from C# side is swaggers:
- dpg`_`initial.json
- dpg`_`update1.json
- dpg`-`customization.json

when generating launchsettings by running script eng\Generate.ps1, in windows the order is 
1. dpg_initial-LowLevel
2. dpg_update1-LowLevel
3. dpg-customization-LowLevel

while in Linux the order is
1. dpg-customization-LowLevel
2. dpg_initial-LowLevel
3. dpg_update1-LowLevel

I already changed the swagger name to fix these three files in https://github.com/Azure/autorest.testserver/pull/372/files

**Comment by timotheeguerin** [comment]
Which field are we talking about? Not sure how those file names are related to autorest core

**Comment by pshao25** [comment]
> Which field are we talking about? Not sure how those file names are related to autorest core

It's not about the autorest core. It is about the CI process. We have a script "eng\Generate.ps1" to create launchSetting file for project, in which process all the swaggers will be sorted by name. Then when we submit this change to CI pipeline, the build agent will run this script again to check whether the generated launchSetting file is the same as what you submitted, but at this time the swaggers are sorted in the Linux platform. Then the build failed. This is scenario in C# side. Other languages still unknown.

**Comment by timotheeguerin** [comment]
So is just about seeing if the naming of the swagger files affect other generator test? this scenario feels very particular to the c# generator.

**Comment by pshao25** [comment]
> So is just about seeing if the naming of the swagger files affect other generator test? this scenario feels very particular to the c# generator.

The naming of swagger files is where this potential issue found. But I believe what @mikekistler want to do is to make sure all the languages and components do not have such inconsistent sorting issue.
BTW: fix a typo in description, it's about `-` and `_`, not `$`.

**Comment by timotheeguerin** [comment]
I see, @mikekistler was this your understanding of the problem? Not sure there is anything to do. If another generator has this problem(though I doubt it) it will be discovered.

Looking into it this seems to be a known issue with dotnet cross platform. Here talks about `-` and `.` order. https://blog.jetbrains.com/dotnet/2020/05/13/sorting-order-depends-runtime-operating-system/

Regardless of this issue the files in the `swagger` folder should be named with `-` and not `_` to keep consistency so might just add a validation to the CI for that.

**Comment by mikekistler** [comment]
I agree that this problem appears to be specific to the csharp generator (nice job finding that article @timotheeguerin !).  I'll try to transfer the issue over there.

**Comment by mikekistler** [comment]
Issue moved to [Azure/autorest.csharp #2101](https://github.com/Azure/autorest.csharp/issues/2101) via [**ZenHub**](https://www.zenhub.com/)
