### ISSUE TITLE
Autorest validation crash for provider operations list when using common-types

### ISSUE THREAD

**Issue by bryan-strassner** [Azure/autorest#4489]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**

When using autorest to validate our RP's swagger, the Autorest program is crashing unexpectedly while validating a `/providers/Microsoft.RPName/operations` path that:

* Uses a reference to common-types (that are copied locally and successfully used in other parts of the swagger
* Is returning a `200` response
* Has `x-ms-pageable` specified

**I have a minimal example**:

```json
{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A simple sample",
    "title": "simple",
    "version": "2022-03-17-preview"
  },
  "host": "management.azure.com",
  "paths": {
    "/providers/Microsoft.SimpleSample/operations": {
      "get": {
        "description": "Get a list of all available resource provider operations. It contains a URL link to get the next set of results.",
        "summary": "List resource provider operations.",
        "operationId": "Operations_List",
        "parameters": [
          {
            "$ref": "./common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "./common-types/resource-management/v2/types.json#/definitions/OperationListResult"
            }
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "schema": {
              "$ref": "./common-types/resource-management/v2/types.json#/definitions/ErrorResponse"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    }
  },
  "securityDefinitions": {
    "azure_auth": {
        "type": "oauth2",
        "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
        "flow": "implicit",
        "description": "Azure Active Directory OAuth2 Flow",
        "scopes": {
            "user_impersonation": "impersonate your user account"
        }
    }
  },
  "security": [
    {
      "azure_auth": [
        "user_impersonation"
      ]
    }
  ]
}
```

**The stack trace**:

```
fatal   | System.ArgumentException: Reference path 'OperationListResult' does not exist in the definition section of the Swagger document.
   at OpenAPI.Validator.SchemaResolver.DereferenceInner(String referencePath, List`1 visitedReferences)
   at OpenAPI.Validator.SchemaResolver.Unwrap(Schema schema)
   at OpenAPI.Validator.Validation.Extensions.PageableRequires200Response.IsValid(Object pageable, RuleContext context)
  ...
```

**When run using**:

```
autorest --input-file=./api/ex.json --azure-validator --version=3.7.6
```

_Note: same results for --version=3.6.4 and --version=3.8.0_

_Note: yes, the common-types are available in the local environment at the paths specified_

**What prevents the crash**:

* Changing the response to any code other than `200`
* Removing the `x-ms-pageable` definition.
* declaring the common-types/v2/types.json#/definitions/OperationListResult as a local type instead.
* omitting --version (runs with ~2.0.4413)

Wondering if:  `OpenAPI.Validator.Validation.Extensions.PageableRequires200Response.IsValid` is not liking the remote file reference?

**Finally the question**:
What is the expected behavior or configuration that I'm missing here? I'd like to appropriately reference common-types, and I'd like to locally use autorest, but this makes our gating fail.

**Expected behavior**
Be able to add x-ms-pageable and reference common-types at the same time for a 200 response.

**Comment by timotheeguerin** [comment]
Hey @bryan-strassner I am not able to reproduce this issue with the spec you have and the azure-specs-repo `types.json`. Could you also share the file referenced here `"./common-types/resource-management/v2/types.json#/definitions/OperationListResult"`. From the error it seems like that file is missing the `OperationListResult` definition.

That error also seems to be coming from the OpenAPI validator instead of autorest https://github.com/Azure/azure-openapi-validator

**Comment by bryan-strassner** [comment]
It's the standard v2/types.json found here: [https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSDev/specification/common-types/resource-management/v2/types.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSDev/specification/common-types/resource-management/v2/types.json)

(also, running in WSL2 / Ubuntu, if that makes a difference)

Since this is coming from the OpenAPI validator, I'll take this over there. Thanks for the help!

**Comment by bryan-strassner** [comment]
Closing issue for Autorest, as this has been opened: [https://github.com/Azure/azure-openapi-validator/issues/269](https://github.com/Azure/azure-openapi-validator/issues/269)
