### ISSUE TITLE
Failed to load dotnet plugin 

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4491]
**Before filling a bug**

- [ ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ ] have you checked existing issues

**Describe the bug**

this is transfered from the https://github.com/Azure/azure-openapi-validator/issues/257
![image](https://user-images.githubusercontent.com/59603451/160735760-bbb556e6-5310-47ae-a60d-e0a048f450f0.png)

**Expected behavior**

**Additional context**

**Comment by mikekistler** [comment]
More context: attempting to install `@microsoft.azure/classic-openapi-validator` by hand fails with more diagnostic info:
```
>npm install @microsoft.azure/classic-openapi-validator@latest
npm ERR! code 1
npm ERR! path /Users/mikekistler/Projects/mikekistler/test/node_modules/dotnet-2.0.0
npm ERR! command failed
npm ERR! command sh -c node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
npm ERR! Unable to install/use dotnet framework.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mikekistler/.npm/_logs/2022-03-30T02_09_08_306Z-debug-0.log
```

I already have dotnet installed ...
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects/mikekistler/test>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
[mikekistler@Mikes-MacBook-Pro] ~/Projects/mikekistler/test>dotnet --version
3.1.416
```

**Comment by timotheeguerin** [comment]
If the npm install doesn’t work this is completely out of autorest hand and is a problem with the validator package. I don’t know what are the requirement of this package and what this errror really mean. Does seem to I be related to an invalid dotnet install but that all I can guess

**Comment by jianyexi** [comment]
Thanks, I used to think the plugin can be installed successfully via 'npm install ' locally but seems not
