### ISSUE TITLE
@autorest/common has security issue

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4493]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug

the @autorest/common seems rely on the 'jison' which contains security issue, see [11481401](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/openapi-alps/alert/6843553?typeId=11481401)

![image](https://user-images.githubusercontent.com/59603451/160784370-d7721737-9e2f-4217-a139-cb03c0f26e71.png)

**Expected behavior**

**Additional context**

**Comment by timotheeguerin** [comment]
So that library hasn’t been updated in 5 years it is a dependency of jsonpath which also doesn’t have much maintaining.

**Comment by jianyexi** [comment]
jsonpath-plus has not been updated for 9 months, also jsonpath-plus use "string[]" as JsonPath type which is not compatible with most implementation

**Comment by timotheeguerin** [comment]
Yeah, we might have to fork one of them. What do you mean by 
```
also jsonpath-plus use "string[]" as JsonPath type which is not compatible with most implementation
```

**Comment by jianyexi** [comment]
the 'JsonPath'  is declared as '(string|number)' []  but, jsonpath plus define JsonPath type as 'string[]' , which means the array index is also a string

**Comment by timotheeguerin** [comment]
yeah but this is not really a problem we don't really care about the json path, it is used as a query system
Pr changing it https://github.com/Azure/autorest/pull/4517

**Comment by jianyexi** [comment]
It's ok If you don't use the 'stringify' function

**Comment by jianyexi** [comment]
@timotheeguerin  do we have a plan to release a new version , since this issue is blocking us

**Comment by jianyexi** [comment]
I think we have both requirements.  let me try using @next, also we have a unified pipeline to run sdk generation and validation, the sdk generation owner want to upgrade the autorest
