### ISSUE TITLE
Error on constant String

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [Azure/autorest#4501]
When running autorest, it errors out to this: 
`fatal   | Error: Unknown type for constant value for String 'string'--cannot create constant value.
fatal   | Process() cancelled due to failure 
error   |   Error: Plugin modelerfour reported failure.`

Is there any documentation on this error? what would be a fix?

**Comment by timotheeguerin** [comment]
hhm this looks like you have a schema somewhere with `type: string, format: string` and autorest doesn't know what to do with that `format: string`. Error comes from here https://github.com/Azure/autorest/blob/61aff363307502ff422f51e74b3e2edeaa2ff0b3/packages/extensions/modelerfour/src/modeler/interpretations.ts#L152

**Comment by ChiefMateStarbuck** [comment]
thank you
