### ISSUE TITLE
model deduplicate not working for CloudError

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest#4508]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Repo for reproduce https://github.com/weidongxu-microsoft/m4-dulicate-sample/

There is no difference of all types between [artifacts.json](https://github.com/weidongxu-microsoft/m4-dulicate-sample/blob/main/artifacts.json) and [artifacts-v2.json](https://github.com/weidongxu-microsoft/m4-dulicate-sample/blob/main/artifacts-v2.json), except the api-version.

However `CloudError` type is duplicated in m4 output, while the other `LinkedServiceReference` type is not duplicated (my guess the cause is the recursive reference in `CloudErrorBody`?).

```
AutoRest code generation utility [cli version: 3.6.1; node: v16.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
gitinfo    |    Loading AutoRest core      'C:\Users\weidxu\.autorest\@autorestcore@3.8.1\nodemodules\@autorest\core\dist' (3.8.1)
 statuinfo    |    Loading AutoRest extension '@autorest/modelerfour' (4.23.1->4.23.1)
s -s
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
warning | PreCheck/DuplicateSchema | Duplicate Schema named 'CloudError' (1 differences):
  - properties.error.$ref: "#/components/schemas/schemas:5" => "#/components/schemas/schemas:15"
warning | PreCheck/DuplicateSchema | Duplicate Schema named 'CloudErrorBody' (1 differences):
  - properties.details.$ref: "#/components/schemas/schemas:9" => "#/components/schemas/schemas:19"
warning | PreNamer/DeduplicateName | Deduplicating schema name: 'CloudError' -> 'CloudErrorAutoGenerated'
warning | PreNamer/DeduplicateName | Deduplicating schema name: 'CloudErrorBody' -> 'CloudErrorBodyAutoGenerated'
info    | Autorest completed in 2.64s. 1 files generated.
```

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues https://github.com/weidongxu-microsoft/m4-dulicate-sample
- Autorest command used `autorest readme.md --output-artifact=code-model-v4-no-tag --output-folder=.`

- core 3.8.1
- m4 4.23.1
```

**Expected behavior**

There is no difference of all types between [artifacts.json](https://github.com/weidongxu-microsoft/m4-dulicate-sample/blob/main/artifacts.json) and [artifacts-v2.json](https://github.com/weidongxu-microsoft/m4-dulicate-sample/blob/main/artifacts-v2.json).
And hence there should not be duplicate type in m4 output.

**Additional context**

**Comment by timotheeguerin** [comment]
Believe this issue came up before and the deduplication doesn't handle recursive models.

**Comment by weidongxu-microsoft** [comment]
Thanks @timotheeguerin @lmazuel 
Then it had to be fixed in swagger.
It just less convincing for us to ask service to refactor their swagger because deduplicate works for some type but not for some other :-(

@msyyc @qiaozha @pshao25 @MaryGao for awareness. Kudos to Yuchao adding a PR for the huge refactoring to synapse.
