### ISSUE TITLE
swagger-loader emit yaml format swagger

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4512]
**Describe the bug**
the swagger-loader should emit a json format swagger , but for some swaggers , it emits a yaml format swagger. It will incur a failure to swagger linter 

after debugging locally , I found it occurs when there is an example file being referred twice in the swagger, for example
https://github.com/Azure/azure-rest-api-specs/blob/82313c6a2b7f78e835f0731548886858bde6765b/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L389-L393

in the writeObject use fastStringify to serialize the swagger 
https://github.com/Azure/autorest/blob/main/packages/libs/datastore/src/data-store/data-sink.ts#L59

the  fastStringify function will return yaml when the losslessJsonSerializable return false , as the same object already been seen 
![image](https://user-images.githubusercontent.com/59603451/162871166-23bb8fc4-0eee-4e65-87f2-adb26f82d373.png)

I think if we can separate the example resolver as https://github.com/Azure/autorest/issues/4499 , we will avoid this issue

**Expected behavior**

**Additional context**

**Comment by timotheeguerin** [comment]
@jianyexi can you try that version of core https://github.com/Azure/autorest/pull/4516 and confirm this does what you expect.

**Comment by jianyexi** [comment]
@timotheeguerin  
in my env, I run 
```PS 
C:\code\forks\linter\azure-openapi-validator> npx autorest --v3 --azure-validator  --openapiType=arm --use=../packages/azure-openapi-validator/autorest --debug --input-file=C:\code\forks\linter\azure-openapi-validator\regression\azure-rest-api-specs\specification\compute\resource-manager\Microsoft.Compute\stable\2021-10-01\gallery.json --version:https://tinyurl.com/y93yk3xa
```
but get the following errors
```
error   |   Error: Package 'C:\code\forks\linter\packages\azure-openapi-validator\autorest' - '*' is not a valid package reference:
  Invalid package name "C:\code\forks\linter\packages\azure-openapi-validator\autorest" of package "C:\code\forks\linter\packages\azure-openapi-validator\autorest@*": name can only contain URL-friendly characters.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
debug   | [1.89 s] Shutting Down.
fatal   | Failed to install extension 'C:\code\forks\linter\packages\azure-openapi-validator\autorest' (*)
debug   | [1.89 s] Exiting.

```

**Comment by jianyexi** [comment]
https://github.com/Azure/autorest/issues/4512#issuecomment-1097797344 this issue seems only occurs in node v16

**Comment by jianyexi** [comment]
> @jianyexi can you try that version of core #4516 and confirm this does what you expect.

this is not fixed by #4516

**Comment by jianyexi** [comment]
this issue is fixed, but the plugin will fail to read example files
```
Could not read file: file:///mnt/c/code/forks/linter/azure-openapi-validator/regression/azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/stable/2021-10-01/examples/gallery/DeleteAGalleryImage.json 
```

**Comment by timotheeguerin** [comment]
When you mean the plugin you are talking about your plugin?

I think this might be due to the only files you have access to are the ones returned by the previous plugin.

**Comment by jianyexi** [comment]
> When you mean the plugin you are talking about your plugin?
> 
> I think this might be due to the only files you have access to are the ones returned by the previous plugin.

I mean an autorest extension , like linter , code generator . it reads file from the autorest core

**Comment by timotheeguerin** [comment]
Yeah then this is the issue I'm talking about. The readFile only reads file in the scope returned by the previous plugin.

**Comment by timotheeguerin** [comment]
Maybe could update the readFile to allow trying to load external files as well

**Comment by jianyexi** [comment]
But it can also read configuration in the readme, I think it make sense to read related examples files

**Comment by timotheeguerin** [comment]
How are you reading the configuration? There is a dedicated method for that but you are not reading the config files manually?

**Comment by jianyexi** [comment]
Sorry it uses GetValue method
```
await initiator.GetValue('openapi-type');
```

**Comment by timotheeguerin** [comment]
Ok updated the external plugin interface to workaround this. We already had a workaround to allow loading from the output-folder seems like so I don't feel bad expending it.

**Comment by jianyexi** [comment]
Great, it works perfectly
