### ISSUE TITLE
Trimming down the generated data definitions

### ISSUE THREAD

**Issue by rpocha** [Azure/autorest#4513]
Hi Team,
 
   I am from AFO team and using  AutoRest to generate the GoLang Bindings. We observed that the data definitons names are lenghty one. Is there any way that we can trim down the data definitions names to shorter ones.

In below example., observed that the data definitions are lenghty one,
     - NetworkFabricInfoPropertiesNetworkToNetworkInterconnectLagConfigType
     - NetworkFabricInfoPropertiesNetworkToNetworkInterconnectIpv4ConfigurationType
     - NetworkFabricInfoPropertiesNetworkToNetworkInterconnectIpv6ConfigurationType    

I want to trim down the names to shorter ones. Please let me know are there any options to do the same.
// NetworkFabricInfoPropertiesNetworkToNetworkInterconnectType ...
type NetworkFabricInfoPropertiesNetworkToNetworkInterconnectType struct {
	LagConfig            *NetworkFabricInfoPropertiesNetworkToNetworkInterconnectLagConfigType            `json:"lagConfig,omitempty"`
	Ipv4Configuration    *NetworkFabricInfoPropertiesNetworkToNetworkInterconnectIpv4ConfigurationType    `json:"ipv4Configuration,omitempty"`
	Ipv6Configuration    *NetworkFabricInfoPropertiesNetworkToNetworkInterconnectIpv6ConfigurationType    `json:"ipv6Configuration,omitempty"`
	PeeringConfiguration *NetworkFabricInfoPropertiesNetworkToNetworkInterconnectPeeringConfigurationType `json:"peeringConfiguration,omitempty"`
}

**Comment by timotheeguerin** [comment]
Hey @rpocha this looks like those names are generated from the path of the model definitions. Recommend you move those definitions into their own definitions with a name that you can choose.
