### ISSUE TITLE
Autorest doesn't load configuration file if file is starting with yaml block 

### ISSUE THREAD

**Issue by CoolDadTx** [Azure/autorest#4520]
**Before filling a bug**

- [X ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ X] have you checked existing issues

Trying to run the simple example where you can just use `autorest readme.md` and it'll use the configuration file `readme.md`. No matter what I do I always get an error saying `No input files provided`.

The contents of my `readme.md`.

```
```yaml
input-file: openapi.yaml
csharp: true
namespace: 'Test.Clients'
clear-output-folder: true
```

I have tried various command lines as shown in the documentation and they all produce the same error. Passing those same options directly on the command line works correctly.

```
autorest
autorest readme.md
autorest .\readme.md
```

Output:

```
AutoRest code generation utility [cli version: 3.6.1; node: v16.13.0]
(C) 2018 Microsoft Corporation. 
https://aka.ms/autorest
info    |    Loading AutoRest core      'C:\Users\...\.autorest\@autorestcore@3.8.3\nodemodules\@autorest\core\dist' (3.8.3)                                                                                                             
error   | [Exception] No input files provided.                                                                                                                                                                                                  

Use --help to get help information or see https://aka.ms/autorest/cli for additional documentation                      
error   |   Error: [Exception] No input files provided.                                                                                                                                                                                         

Use --help to get help information or see https://aka.ms/autorest/cli for additional documentation                      
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.              
```

I'm doing this from a PS Core window.

**Expected behavior**
Based upon the documentation I should be able to put my configuration into a `.md` file and point autorest to it. Autorest will then use the configuration file.

**Additional context**

**Comment by timotheeguerin** [comment]
Seems like autorest doesn't like the `yaml` code block to start right at the top can you try adding something like `# My Autorest config` on the 1st line 

````md
# Autorest config

```yaml
input-file: openapi.yaml
csharp: true
namespace: 'Test.Clients'
clear-output-folder: true

````

**Comment by CoolDadTx** [comment]
@timotheeguerin  That resolved the issue for me. Thanks.
