### ISSUE TITLE
Ordering by Resource NOT by Operation?

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [Azure/autorest#4522]
when generating code for autorest, is there a way to group functions by resource type rather than operation?

For example, grouping all the VM calls together like `client.VM.Create()` instead of `client.creat.VM()` ?

**Comment by timotheeguerin** [comment]
if you name the operation with this format `<groupName>_<operationName>` it should group them using the groupName.

In your example having `VM_Create` for the operation Id should result in this.

**Comment by timotheeguerin** [comment]
which language are you generating? CSharp? I do not believe so, but you can file an issue here https://github.com/Azure/autorest.charp to confirm/request the feature.

**Comment by ChiefMateStarbuck** [comment]
This is for python. Also the link is broken. 

Tidbit: the file name produced is `_VM_operations.py`

**Comment by iscai-msft** [comment]
@ChiefMateStarbuck the property on the main client should just be `vm` even though the operation group class itself will be called `VMOperations`. This means that you should be able to access the code as `client.vm.create()`. If this is not the case, can you show me the generated code and the swagger you wrote?

The filename is also private, so it doesn't super matter what the filename is described as, are you having an issue with the filename?

**Comment by ChiefMateStarbuck** [comment]
Thank you guys! i now understand
