### ISSUE TITLE
When operationId is `onPremisesPublishingProfiles_GetAgents`, `Get-OnPremisPublishingProfileAgent` gets generated as the cmdlet name with a missing `e` on `OnPremis`.

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest#4530]
When operationId is `onPremisesPublishingProfiles_GetAgents`, `Get-OnPremisPublishingProfileAgent` gets generated as the cmdlet name instead of `Get-OnPremisePublishingProfileAgent`. It looks like `EnglishPluralizationService` is singularizing `onPremises` to `OnPremis` instead of `OnPremise` in https://github.com/Azure/autorest.powershell/blob/9b3eb34c6d32248429c4034941297d52cd6cf36a/powershell/plugins/create-commands-v2.ts#L457.

**Comment by timotheeguerin** [comment]
The pluralization service is a port of ` System.Data.Entity.Infrastructure.Pluralization.EnglishPluralizationService` in csharp which has this exact same issue.

![image](https://user-images.githubusercontent.com/1031227/167021992-4b7551c3-abb1-4e06-b091-f305674bc3d2.png)

The `pluralize` library in js doesn't seem to have this issue. I am a bit skeptical to fix this as everytime there was something about trying to fix the naming logic it would cause breaking changes for other services.

HOwever this seems like this is not used by autorest directly. Could powershell use the `pluralize` library directily  https://www.npmjs.com/package/pluralize
