### ISSUE TITLE
Errant types when generating body-formdata.json

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4533]
https://github.com/Azure/autorest.testserver/blob/main/swagger/body-formdata.json

There are two extra types which don't appear to be used for anything.

```
Paths1MqqetpFormdataStreamUploadfilePostRequestbodyContentMultipartFormDataSchema
Paths1P3Stk3FormdataStreamUploadfilesPostRequestbodyContentMultipartFormDataSchema
```

Unclear on their purpose, maybe just junk types that can be removed?  They aren't referenced anywhere.

M4 version 4.23.1
core 3.8.2

**Comment by timotheeguerin** [comment]
Is it because that's the form data body that gets spread as individual parameters?

**Comment by timotheeguerin** [comment]
As dicussed in the meeting closing as wont fix due to the complexity of figuring out which models should be included or not and some services wanting non referenced models to be included.
