### ISSUE TITLE
error   | Interpretations | NEED 'operationId' for 'get' operation on path, transforming 

### ISSUE THREAD

**Issue by M-U-X** [Azure/autorest#4534]
Read the accepted answer [here](https://stackoverflow.com/questions/60819169/fatal-operationid-is-required-for-all-operations-please-add-it-for-get-opera) 

The solution [here](https://github.com/Azure/autorest/issues/2647#issuecomment-335282240)

and check this [swagger API definition](https://app.swaggerhub.com/apis/Henrik-3/HenrikDev-API/2.0.1), Export>Download API> Json Resolved is what I'm using, it doesn't even have tags for the operation or operation IDs
NSawg generates C# code just fine, but autorest can't

**Comment by timotheeguerin** [comment]
Hey @M-U-X, what is your question here? `operationId` is a requirement for autorest and that will not change. The goal is to generate a good SDK that can evolve without breaking changes and guessing operation name is a great source of variability and would most likely not give a great operation name.
