### ISSUE TITLE
Request body standardization with multiple content types accepted

### ISSUE THREAD

**Issue by jeskew** [Azure/autorest#4540]
I use Autorest and the ModelerFour plugin to generate resource types for the Azure Bicep project. ModelerFour has not been able to process some ARM swagger documents since https://github.com/Azure/autorest/pull/4405; specifically, resources under the `Microsoft.Web` namespace can no longer be generated because the ARM resource provider can consume the same object structure as either JSON or form data.

Should ModelerFour permit requests with the same structured input over two different content types? I saw that there is [a special case to allow operations to consume both XML and JSON](https://github.com/Azure/autorest/blob/284dfd619bbe140f00e17891deb20de560ab32ba/packages/extensions/modelerfour/src/modeler/body-processor.ts#L136-L142) but was wondering if a more general solution would be possible.

Before asking the question:

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [X] have you checked existing issues for a similar question?

**Comment by timotheeguerin** [comment]
what was the behavior before, it would just ignore the form data?

**Comment by jeskew** [comment]
The Swagger document didn't distinguish between the two input types. For example, [this operation](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2015-08-01/service.json#L66) declares that it consumes JSON or form data but only provides a single schema to describe the request body. I don't believe it's possible to do something like that in OpenAPI 3, but it does seem to be a fairly common pattern with Swagger 2 documents.

**Comment by timotheeguerin** [comment]
It is possible in openapi3 to do, what it means here is that the payload schema is the same but it can be serialized as json or formData. I was just asking on what was m4 behavior before if you know, was it just ignoring the formData type and acting like this was just application/json.
As far as I know the generators don't support different serializion types for the same schema which is why this check is there complaining but we could have the same special case as with xml where if json is specified it takes precendence

**Comment by jeskew** [comment]
I believe the previous behavior was that m4 would act like the body was just application/json. The Bicep plugin doesn't generate any request serializers, so it has been ignoring content types.

**Comment by timotheeguerin** [comment]
Hey @jeskew can you confirm this PR resolve the issue following the instruction on this comment https://github.com/Azure/autorest/pull/4543#issuecomment-1139753611

**Comment by jeskew** [comment]
> Hey @jeskew can you confirm this PR resolve the issue following the instruction on this comment [#4543 (comment)](https://github.com/Azure/autorest/pull/4543#issuecomment-1139753611)

It does! Thanks for the quick work on this.
