### ISSUE TITLE
Sealed enum with only one value should not be generated as `ConstantSchema` when the parameter/property is optional

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest#4548]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Our current modeler v4 will generate the sealed enums with only one value (its "modelAsString" is false) to a `ConstantSchema`. But when this happens to an operation, taking [this operation](https://github.com/Azure/azure-rest-api-specs/blob/178dde3308a5fb253a6cababf51d5069136170bf/specification/storage/resource-manager/Microsoft.Storage/stable/2021-09-01/storage.json#L538) as an example, the parameter `$expand` is optional, we should provide our customer a chance to pass nothing for this parameter and enforce them if they want to pass anything, the only value to choose is the `kerb`.
Generating the schema of this parameter as a `SealedChoiceSchema` will be a perfect solution.
BTW java generator has done that for quite a long time: https://github.com/Azure/autorest.java/blob/956bf0dbf75bea1bfcec4f6cc1cd18c3df57f8ca/preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java#L128-L169

**Expected behavior**

We expect the modeler should generate the seale choice with only one value a `SealedChoiceSchema` when its carrier parameter or property is not required.

**Additional context**

**Comment by timotheeguerin** [comment]
This is by design. The fact that the schema is a constant is true but the fact that it is required or not depends on where it is used and shouldn’t affect the schema itself. 
The same constant could be used in places where it’s required and some where it’s optional and then now you have a problem if we do that logic.
