### ISSUE TITLE
Incorrect value for api-version when used as a separate parameter

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4559]
Building NRP package-2021-08

https://github.com/Azure/azure-rest-api-specs/blob/2d6cb29af754f48a08f94cb6113bb1f01a4e0eb9/specification/network/resource-manager/readme.md#tag-package-2021-08

Operation [PublicIPAddresses_ListVirtualMachineScaleSetPublicIPAddresses](https://github.com/Azure/azure-rest-api-specs/blob/2d6cb29af754f48a08f94cb6113bb1f01a4e0eb9/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/vmssPublicIpAddress.json#L39) has parameter `ApiVersionVmssParameter` which is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/2d6cb29af754f48a08f94cb6113bb1f01a4e0eb9/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/network.json#L344).  As you can see, this parameter has a value of `2017-03-30` which is different from the version specified in [vmssPublicIpAddress.json](https://github.com/Azure/azure-rest-api-specs/blob/2d6cb29af754f48a08f94cb6113bb1f01a4e0eb9/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/vmssPublicIpAddress.json#L6).

There are two problems.

- generating the code uses the wrong API version `2021-08-01`, it should be `2017-03-30`
- the swagger defines `ApiVersionVmssParameter` as an extensible enum however autorest treats it as a constant

Example of bad codegen [here](https://github.com/Azure/azure-sdk-for-go/blob/99b75a8afb53866794167edc4c0081f0b5ab0f79/sdk/resourcemanager/network/armnetwork/zz_generated_publicipaddresses_client.go#L744).

M4 4.23.6
Core 3.8.4

**Comment by timotheeguerin** [comment]
Believe you need to set `x-ms-api-version-parameter: false` to use your custom parameter

**Comment by jhendrixMSFT** [comment]
Confirmed this resolves the issue.  However, something still seems a little weird here.  It seems like there are two conflicting definitions for `api-version`.  Shouldn't an error have been generated?

**Comment by timotheeguerin** [comment]
yeah there is an issue for that https://github.com/Azure/autorest/issues/4425 but like any breaking change this always create a cascade of mess in the azure-rest-api-specs repo as nobody wants to do any work fixing the specs.
