### ISSUE TITLE
`where-operation-match` does not work

### ISSUE THREAD

**Issue by heaths** [Azure/autorest#4566]
I've tried to use `where-operation-match` for a number of transforms or other built-in directives and it never works. For example, I tried this:

```yaml
directive:
- where-operation-match: ConversationalAnalysisAuthoring_((List(Projects|Deployments|TrainedModels|TrainingJobs|TrainingConfigVersions))|Get(ModelEvaluationResults|SupportedLanguages|SupportedPrebuiltEntities))
  transform: |
    var paramRefs = [
      "common.json#/parameters/TopParameter",
      "common.json#/parameters/SkipParameter",
      "common.json#/parameters/MaxPageSizeParameter"
    ];
    $.parameters = $.parameters.filter(param => !paramRefs.includes(param["$ref"]))
```

But the output doesn't change. This is to remove parameters that are `$ref`'d, for which `remove-parameter` doesn't work (see #4565).

The regex is valid, as proven by:

```js
/ConversationalAnalysisAuthoring_((List(Projects|Deployments|TrainedModels|TrainingJobs|TrainingConfigVersions))|Get(ModelEvaluationResults|SupportedLanguages|SupportedPrebuiltEntities))/.test("ConversationalAnalysisAuthoring_ListProjects")
```

**Comment by timotheeguerin** [comment]
You need to provide the full regex with `/` wrapping and the flags as the docs specify https://github.com/Azure/autorest/blob/main/docs/generate/built-in-directives.md#selecting-operation
