### ISSUE TITLE
No support for zip MediaType

### ISSUE THREAD

**Issue by aliabufoul** [Azure/autorest#4570]
When running autoRest.csharp I get an internal error.
After looking into the code based on the stack of the exception, I see it crashes at this function:
https://github.com/Azure/autorest.csharp/blob/beb9a380e2bbad1993afdf7217a211ec11b8764b/src/AutoRest.CSharp/Common/Output/Builders/SerializationBuilder.cs#L33

with NotImplementedException.

Seems that there is no support for zip mediaType yet. Only Json and xml are supported.

After removing APIs that use zip mediaType from swagger, running autoRest succeeded.

Could you please provide an ETA for adding support for it?
Is there a workaround meanwhile for this issue? 

Thanks

**Comment by timotheeguerin** [comment]
Hey @aliabufoul what is the schema of the body? It should be defined as binary. My guess is here it is defined as an object but doesn't know what zip means as its not a structured seriualization format.
