### ISSUE TITLE
x-ms-client-name not work in an endpoint parameter

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest#4573]
**Before filling a bug**

- [ ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ ] have you checked existing issues

**Describe the bug**
We have this [parameter](https://github.com/shurd/azure-rest-api-specs/blob/f5cb6fb416ae0a06329599db9dc17c8fdd7f95c7/specification/cosmos-db/data-plane/Microsoft.TablesStorage/preview/2018-10-10/table.json#L1406-L1414) which serves as an endpoint. We want to rename it to "endpoint" by adding `"x-ms-client-name": "endpoint"` like 
```
"Url": {
    "name": "url",
    "x-ms-parameter-location": "client",
    "description": "The URL of the service account or table that is the targe of the desired operation.",
    "required": true,
    "type": "string",
    "in": "path",
    "x-ms-skip-url-encoding": true,
    "x-ms-client-name": "endpoint"
  }
```

**Actual behavior**
![image](https://user-images.githubusercontent.com/97225342/175516369-0bf150b2-4f96-4003-864d-890af916231c.png)

**Expected behavior**
We should have the client name as "endpoint".

**Comment by timotheeguerin** [comment]
This works fine for me. 

```yaml

swagger: "2.0"
info:
  version: 2021-06-15-preview
  title: Test
  description: test
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-ms-parameterized-host:
  hostTemplate: "{url}"
  useSchemePrefix: false
  positionInOperation: "first"
  parameters: [{ "$ref": "#/parameters/Url" }]

paths:
  "/calling":
    get:
      parameters: [{ "$ref": "#/parameters/Url" }]
      summary: Test
      operationId: getTest
      responses:
        "401":
          "$ref": "#/responses/401"
responses:
  "401":
    description: Unauthorized
    schema:
      type: object

parameters:
  Url:
    name: "url"
    x-ms-parameter-location: "client"
    x-ms-client-name: MyCustomRename
    description: "The URL of the service account or table that is the targe of the desired operation."
    required: true
    type: "string"
    in: "path"
    x-ms-skip-url-encoding: true

```

and in the codemodel 
![image](https://user-images.githubusercontent.com/1031227/177622619-6ff72d83-16cf-4fe5-9f11-05bbe79fe157.png)
