### ISSUE TITLE
Supply Chain Compliance - AutoRest Docker

### ISSUE THREAD

**Issue by scbedd** [Azure/autorest#4575]
- [x] [Adjust base image to pull from internal w/ argument](https://github.com/Azure/autorest/blob/main/docker/base/ubuntu/Dockerfile)
- [x] Upload resulting image to private CR
   - [ ] This is a build change in yaml
   - [x] Builds already failing, going to leave this up to @timotheeguerin when he's back on the 5th. 
- [x] Target private (with anonymous access enabled) CR from each "child" image
- [x] ~Get exception for private CR from supply chain compliance team.~ Turns out we just needed to enable Cloud Defender on our sub. That's done.

**Comment by timotheeguerin** [comment]
@scbedd thanks for doing this, I made a PR fixing the dockerfile https://github.com/Azure/autorest/pull/4590, guessing I also need to update the build pipeline to publish to `azsdkengsys.azurecr.io`, is there anything I need to do to get it authenticated?

**Comment by scbedd** [comment]
@timotheeguerin yes exactly. You're on the same backing devops, so you can just az acr login [like this.](https://github.com/Azure/azure-sdk-tools/blob/8516bbfa5c87143b08c540539ffada7a0bd747f5/eng/pipelines/publish-docker-image.yml#L99) `azsdkengsys` is the name of the container registry. Devops will use the backing service connection to the test sub to auth to the container registry.

Before invoking your docker publish. Feel free to crib any build yaml you want from the tools repo!
