### ISSUE TITLE
-SdkRepoPath parameter not Found

### ISSUE THREAD

**Issue by Selekena** [Azure/autorest#4579]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
The two error messages together are throwing me off. A parameter is recommended only to not found when one tries to use it. Am I missing something here
```
Please provide as much information as you can. This would be:
- Autorest command used

Start-AutoRestCodeGeneration: **Could not find root for output directory since script is not run from SDK repo, please provide this using the -SdkRepoPath parameter!**
PS C:\selekena-dot-net-swagger\sdk\deviceprovisioningservices\Microsoft.Azure.Management.DeviceProvisioningServices\src> Start-AutoRestCodeGeneration -ResourceProvider "deviceprovisioningservices/resource-manager" -AutoRestVersion "v2" -SpecsRepoFork "https://github.com/Selekena/azure-rest-api-specs/" -SpecsRepoBranch "selekena/deviceprovisioningservice-readme-armflag-2022-02-05" -SdkRepoPath "/."
**Start-AutoRestCodeGeneration: A parameter cannot be found that matches parameter name 'SdkRepoPath'**.

```

**Expected behavior**

I am trying to generate csharp sdk code from a private branch.

**Additional context**

**Comment by timotheeguerin** [comment]
Hey @selekena, not sure what this powershell command is, this is not something provided by autorest itself. That seems to be something tied to the net sdk repo, I would file the issue there.
