### ISSUE TITLE
Is the sample about `x-ms-discriminator-value` wrong?

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/autorest#4583]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

In the file https://github.com/Azure/autorest/tree/main/docs/extensions/swagger-extensions-examples/x-ms-discriminator-value, the `x-ms-discriminator-value` indicates a base type, but from usage in the the spec repo, `x-ms-discriminator-value` should be "cat", "dog" in the [sample](https://github.com/Azure/autorest/blob/main/docs/extensions/swagger-extensions-examples/x-ms-discriminator-value/x-ms-discriminator.yaml)

**Comment by timotheeguerin** [comment]
indeed, you are right the sample here is wrong thanks for reporting this.
