### ISSUE TITLE
TypeError: extension.updatePythonPath is not a function after CLI version 3.6.2 was made available.

### ISSUE THREAD

**Issue by bryan-strassner** [Azure/autorest#4599]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

Until the 3.6.2 version of the cli was made available, the following command worked for us to setup/install autorest dependencies in a CI pipeline:

```
node_modules/autorest/entrypoints/app.js --az --python --use=@autorest/python@5.4.0 --azure-validator --version=3.7.6 --help
```
Coinciding with the 3.6.2 message showing up: 
```
AutoRest code generation utility [cli version: 3.6.1; node: v18.6.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: 3.7.6.
debug   | [0.79 s] Network Enabled: true

There is a new version of AutoRest available (3.6.2).
 > You can install the newer version with with npm install -g autorest@latest
```

Prior to this version advertisement, the pipelines were able to successfully acquire the modules and produce the help messages. Even without moving to the new 3.6.2 version (still running 3.6.1), we now receive the following exception:

```
TypeError: extension.updatePythonPath is not a function
fatal   | Process() cancelled due to exception : [Exception] AutoRest extension '@autorest/python' terminated. / Error: [Exception] AutoRest extension '@autorest/python' terminated.
    at /home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:1549:17
    at CallbackList.invoke (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:107995:39)
    at Emitter.fire (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:108059:36)
    at closeHandler (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:108636:26)
    at CallbackList.invoke (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:107995:39)
    at Emitter.fire (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:108059:36)
    at StreamMessageReader.exports.modules.../../../common/temp/nodemodules/.pnpm/vscode-jsonrpc@3.6.2/node_modules/vscode-jsonrpc/lib/messageReader.js.AbstractMessageReader.fireClose (/home/bstrassner/.autorest/@autorest_core@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:109430:27)
    at Socket.<anonymous> (/home/bstrassner/.autorest/@autorestcore@3.7.6/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_object-comparison_3_0_253_node_modulesazur-23729e.js:109483:62)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:757:14)
error   | [Exception] AutoRest extension '@autorest/python' terminated.
```

I was able to reproduce this locally (as you can see from the paths in the snips above), by doing:
```
node_modules/autorest/entrypoints/app.js –reset
node_modules/autorest/entrypoints/app.js --az --python --use=@autorest/python@5.4.0 --azure-validator --version=3.7.6 --debug --help
```

**Expected behavior**
The expectation is that the help command output is produced without exception.

**Additional context**
[autorest3.6.2exception.log](https://github.com/Azure/autorest/files/9161799/autorest3.6.2exception.log)
[autorest3.6.1success.log](https://github.com/Azure/autorest/files/9161810/autorest3.6.1success.log)

**Comment by timotheeguerin** [comment]
Guessing this is an issue with the dependency not being pinned.
Can you update the python generator version with `--use=@autorest/python@5.19.0`. I believe there is also some other issues with older version of the python generator and its python dependencies.

**Comment by bryan-strassner** [comment]
Yes- have tried pinning to 5.19.0. It fails with a different problem.  In fact, other versions > 5.4.0 gets this error.  I've also tried 5.5.0, 6.1.1:
```
fatal   | Process() cancelled due to exception : Cannot resolve pipeline stage 'python/namer' for stage 'az/merger'. Looked for pipeline stages:
 - az/python/namer
 - python/namer
 / Error: Cannot resolve pipeline stage 'python/namer' for stage 'az/merger'. Looked for pipeline stages:
 - az/python/namer
 - python/namer
```
See log attached:
[autorest3.6.1wPy5.19.0.failure.log](https://github.com/Azure/autorest/files/9162904/autorest3.6.1wPy5.19.0.failure.log)

**Comment by timotheeguerin** [comment]
can you remove `--az` and `--azure-validator` those depends on autorest v2

**Comment by bryan-strassner** [comment]
This indeed succeeds in running but doesn't change that there was a behavior change... back to the drawing board I suppose.

The goal here is to preinstall modules, such that we can use autorest to:
`--az to generate a CLI extension`
`--go to generate a go SDK`
`--azure-validator --semantic-validator=true --model-validator=true --openapi-type=arm` to validate swagger

Seems quite the maze of dependencies and not a real clear way to achieve all in the same environment. (what we had before worked until 2 days ago... but maybe we're doing it wrong !!!) 

Any thoughts or guidance on a path?

**Comment by timotheeguerin** [comment]
Agree with you that autorest dependency is a mess, the ability to get download on the fly make you loose the ability to have locked dependencies which cause those issues where things randomly start failing due to a dep of a dep getting updated.

For the `v2` vs `v3` problem this is also indeed frustrating but v2 has been deprecated for a while as well, I can't tell why they still haven't updated their extension to v3.

If you want to preload things you can always them one by one and all the various different version should get installed and be ready for next use.

Which command was working well 2 days ago, the 1st one on the issue? Did you have the packages cached on your machine by chance?

**Comment by vtahiliani** [comment]
I have been facing similar issues with python version:5.4.0, core: 3.7.6 and cli: 3.6.2
Is there any working compatible version for autorest cli generation? Any thoughts or guidance on a path?

**Comment by bfjelds** [comment]
Our team is seeing this as well when trying to create an az cli sdk:
``` powershell
> autorest --az  .\readme.md
AutoRest code generation utility [cli version: 3.6.2; node: v18.4.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    |    Loading AutoRest core      'C:\Users\bfjelds\.autorest\@autorestcore@3.9.0\nodemodules\@autorest\core\dist' (3.9.0)
info    |    Loading AutoRest extension '@autorest/az' (latest->1.8.0)
info    |    Loading AutoRest extension '@autorest/python' (5.4.0->5.4.0)
info    |    Loading AutoRest extension '@autorest/clicommon' (0.6.2->0.6.2)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)
TypeError: extension.updatePythonPath is not a function
fatal   | Process() cancelled due to failure 
error   | [Exception] AutoRest extension '@autorest/python' terminated.
error   |   Error: [Exception] AutoRest extension '@autorest/python' terminated.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

Any help in understanding how we can workaround this would be super appreciated!

**Comment by timotheeguerin** [comment]
You can find the particular issue with using `--az` here https://github.com/Azure/autorest.az/issues/893 with a workaround described here https://github.com/Azure/autorest.az#take-logz-extension-as-a-dry-run
