### ISSUE TITLE
remove-operation{-match} directive removes non-matching operations

### ISSUE THREAD

**Issue by andrewsomething** [Azure/autorest#4602]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

According to the documentation, the `remove-operation` built-in directive can accept a regex:

```yaml
directive:
  - remove-operation: <operationId>  | <regex>
```
https://github.com/Azure/autorest/blob/66c3f70a8ad9ba1c5c8fdedd0378c921c06a32ce/docs/generate/built-in-directives.md#remove-operation

This does not seem to be true. After some digging, `remove-operation` does not  accept a regex, but `remove-operation-match` does:

https://github.com/Azure/autorest/blob/main/packages/libs/configuration/resources/directives.md#removal

Unfortunately, that does not work as expected.  `remove-operation-match` seems to be over matching. Generating a client using it removes all operations, not just ones matching the regex. 

**Please provide as much information as you can. This would be:**
- OpenAPI files having the issues: https://github.com/Azure/autorest/blob/d021dadda293256d3bf18f6c057ba474aaab37af/packages/extensions/core/test/resources/tiny.yaml
- Autorest command used: `autorest --python --input-file=https://raw.githubusercontent.com/Azure/autorest/d021dadda293256d3bf18f6c057ba474aaab37af/packages/extensions/core/test/resources/tiny.yaml --output-folder=generated/  --directive="remove-operation-match: /^cowbell_g.*/i"`

**Expected behavior**

A client would be generated with a `cowbell.add()` method but not a `cowbell.get()`. Instead, no operations are generated at all.

**Additional context**

The following integration test demonstrates the issue. `/^cowbell_g.*/i` should only match and remove `Cowbell_Get`, but the test fails as both operations are undefined.

```diff
diff --git a/packages/extensions/core/test/modifiers.e2e.ts b/packages/extensions/core/test/modifiers.e2e.ts
index 357205098..865724720 100644
--- a/packages/extensions/core/test/modifiers.e2e.ts
+++ b/packages/extensions/core/test/modifiers.e2e.ts
@@ -97,6 +97,17 @@ describe("Modifiers", () => {
     expect(findOperation(code, "Cowbell_Get")).toBe(undefined);
   });
 
+  it("remove an operation using a regex", async () => {
+    const code = await generate({
+      directive: {
+        "remove-operation-match": /^cowbell_g.*/i,
+      },
+    });
+
+    expect(findOperation(code, "Cowbell_Get")).toBe(undefined);
+    expect(findOperation(code, "Cowbell_Add")).toBeDefined();
+  });
+
   it("rename an operation", async () => {
     const code = await generate({
       directive: {
```

```
  ● Modifiers › remove an operation using a regex

    expect(received).toBeDefined()

    Received: undefined

      106 |
      107 |     expect(findOperation(code, "Cowbell_Get")).toBe(undefined);
    > 108 |     expect(findOperation(code, "Cowbell_Add")).toBeDefined();
          |                                                ^
      109 |   });
      110 |
      111 |   it("rename an operation", async () => {

      at Object.<anonymous> (test/modifiers.e2e.ts:108:48)
```

Seeing as `remove-operation-match` uses `where-operation-match`, I suspect that the problem is in the JSONPath query there. I was unable to tell just which JSONPath implementation is being used. 

Potentially related:  https://github.com/Azure/autorest/issues/4566

**Comment by timotheeguerin** [comment]
@andrewsomething thanks for the detail report, looks like a breaking change with the recent change to `jsonpath-plus`, will take a look

**Comment by timotheeguerin** [comment]
Hey @andrewsomething could you give this fix a try and confirm everything is resolved https://github.com/Azure/autorest/pull/4603#issuecomment-1197107321

**Comment by andrewsomething** [comment]
@timotheeguerin  :+1:  Looks great. Thanks for the quick fix.
