### ISSUE TITLE
`format: arm-id` metadata getting lost during processing pipeline

### ISSUE THREAD

**Issue by jeskew** [Azure/autorest#4614]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**

~~Using `@autorest/core` version 3.9.1 and `@autorest/modelerfour` version 4.24.1, the string format of `arm-id` and the `x-ms-arm-id-details` extensions seem to be getting inconsistently dropped somewhere along the processing pipeline. When processing [the `ManagedClusterAgentPoolProfileProperties` shape in version 2022-06-01 of the `containerservice` resource manager spec](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2612) in a custom plugin at the end of the processing pipeline, I expected to see [`vnetSubnetID`](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2637), [`podSubnetID`](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2650), [`nodePublicIPPrefixID`](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2741), [`proximityPlacementGroupID`](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2789), and [`hostGroupID`](https://github.com/Azure/azure-rest-api-specs/blob/1b3b9c1dd4d2c875997ea0b392dc71418fb1f28d/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01/managedClusters.json#L2823) use an instance of `ArmIdSchema` as their schemas, but the lattermost used an instance of `Aspect` (with the `x-ms-arm-id-details` extension data present in the schema) and the rest used an instance of `StringSchema` (with no `format` or `x-ms-arm-id-details` extension data present in the schema).~~ 

Using `@autorest/core` version 3.9.1 and `@autorest/modelerfour` version 4.24.1, plugins downstream on the processing pipeline from modelerfour do not see instances of `ArmIdSchema` used. Instead, the schema will be an instance of `Aspect` with a type of `arm-id`.

Autorest command used:

```
autorest --use=@autorest/modelerfour --use=/home/jeskew/Workspaces/bicep-types-az/src/autorest.bicep --bicep --output-folder=/tmp/_bcp_1660150886081/containerservice --level=verbose --multiapi --title=none --skip-semantics-validation /home/jeskew/Workspaces/azure-rest-api-specs/specification/containerservice/resource-manager/readme.md --level=verbose --bicep.debugger
```

**Additional context**
I put a few `debugger` statements in the modelerfour extension and saw that `hostGroupID`'s was being correctly represented as an instance of `ArmIdSchema`, so the conversion to `Aspect` is probably happening either where data is being returned to autorest from the plugin process or where data is being provided to my custom plugin. The plugin uses `autorest` version 3.6.2, `@autorest/codemodel` version 4.19.1, and `@autorest/extension-base` version 3.5.0.

~~All other properties of `ManagedClusterAgentPoolProfileProperties` that I was expecting to be ARM IDs had already shed their `format` and `x-ms-arm-id-details` schema properties, presumably in a plugin placed before modelerfour in the processing pipeline.~~

**Comment by timotheeguerin** [comment]
This looks fine to me when using modelerfour 4.24.1, can you confirm this is actually what is being used and if so share the logs and output modelerfour with the issue and idealy create a smaller repro.
![image](https://user-images.githubusercontent.com/1031227/184400442-e39e965d-6510-4b05-bcde-5f57408b26e4.png)
and the schema is an `arm-id`
![image](https://user-images.githubusercontent.com/1031227/184400484-4aae0a53-95d4-4966-9a81-1cee92515b10.png)

**Comment by jeskew** [comment]
I can confirm that modelerfour 4.24.1 is being used.

I was able to get the schema `hostGroupID` to be represented correctly as an instance of `ArmIdSchema` by adding a new entry for `ArmIdSchema` to the [YAML schema](https://github.com/Azure/autorest/blob/72a33f2e079440adf4cc2b7260bad587746bf2b8/packages/libs/codemodel/src/model/yaml-schema.ts#L52) (perhaps `arm-id` can be written to the YAML intermediate artifact but cannot be read back without this change?). I am not sure how to write a test for this but am happy to open a PR.

The other items not showing up as ARM IDs was caused by an out-of-sync local copy of azure-rest-api-specs (in which only `hostGroupID` used the `arm-id` string format).

**Comment by timotheeguerin** [comment]
aah I see, this is an issue with the tagged yaml output with the "class" names

**Comment by timotheeguerin** [comment]
I'll make a PR, don't believe we ever had test for the tagged output so probably a little out of scope to get those setup right now. I'll fix it and bump the version to make a patch release.

**Comment by timotheeguerin** [comment]
Thanks for the investigation @jeskew, I have a PR with the fix here, could you just confirm this works fine following the instruction here https://github.com/Azure/autorest/pull/4616. Guessing it must as this is the change you probably did locally to make it work.

**Comment by jeskew** [comment]
Everything is working correctly using the version of modelerfour from the linked PR. Thanks for the quick work on this!
