### ISSUE TITLE
Modelerfour doesn't support recursive array

### ISSUE THREAD

**Issue by BrunoASP2001** [Azure/autorest#4624]
**Describe the bug**
Hello everyone, this is my first time here. I'm trying to generate a class library from LiveTiles Reach API with AutoRest.
The json with the API can be found in this link:
https://api.condense.ch/swagger/index.html?__hstc=96799296.1fd31d1f6864b24263374fad6ff35cf3.1608636891257.1608636891257.1608640595673.2&__hssc=96799296.1.1608640595673&__hsfp=528994668
I'll also send the json file in case you can't access the link.
The command I used to generate the file was the following:
autorest --input-file=ReachAPI.json --csharp --namespace=reach --verbose
I have read the documentation and I think I'm doing everything right, but whenever I try to generate a file, it gives an error, saying:

fatal   | Error: RECURSING!  Saw schema Newtonsoft.Json.Linq.JToken more than once.
fatal   | Process() cancelled due to failure
error   |   Error: Plugin modelerfour reported failure.

I have tried editing the json of the API and using an yaml custom file to replace some other errors, but it either ends up giving me another error, or when it generates a file and I try to use it with my code, it gives an error on my code because it can't access the endpoints. I'm not sure what I'm doing wrong here, or if the problem is with AutoRest or the API, could you guys help?

**Expected behavior**
I expected AutoRest to generate a class library from Reach's API, so I could after that convert it into a nuget and implement it on Visual Studio so I could access Reach's endpoints.

**Additional context**
I will send attached the Output AutoRest generated, the json with Reach's API and also the yaml file I created to fix another error, even tho it ended up still not working in the end. other than that, as I said before, it's my first time posting here, so if I'm missing something or sent something I shouldn't, tell me so I can correct it.
[AutoRest Output.txt](https://github.com/Azure/autorest/files/9445471/AutoRest.Output.txt)
[ReachAPI.zip](https://github.com/Azure/autorest/files/9445476/ReachAPI.zip)
[readme-reach.md](https://github.com/Azure/autorest/files/9445479/readme-reach.md)

**Comment by timotheeguerin** [comment]
Hey @BrunoASP2001 does seems like we have a bug, however your spec does seem to have some weird elements. In particular the piece that is failing `Newtonsoft.Json.Linq.JToken` that doesn't seem like something that should be a element in the openapi as this refer to dotnet internal json manipulation structure.

**Comment by timotheeguerin** [comment]
So this seems to be due to having a recursive array type

```yaml
openapi: 3.0.1
info:
  title: Recursive Array
  version: 0.1.0
paths:
  /test:
    patch:
      requestBody:
        description: ok
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RecursiveArray'
      responses:
        '200':
          description: Success
components:
  schemas:
    RecursiveArray:
      type: array
      items:
        $ref: '#/components/schemas/RecursiveArray'
```

Not really sure what that would even mean in a generated client. The array never has a type it is just `array of array of array of array....`

**Comment by BrunoASP2001** [comment]
Hi @timotheeguerin ! Sorry for the delay and thanks for the response. I was discussing the issue with my colleagues and we are kind of lost, we are developing an app for Reach, we weren't involved in the creation of it's API, so we don't know why they made it that way, thing is, to follow deadlines, I ended up making the app with "manual" endpoints, by making the http client and such manually, and the API worked fine without any problems, we just wanted to use AutoRest because the package it creates has other important uses, but we always ended up with that error. Until now our thought process was to remove everything related to Newtonsoft from the API's json, after that AutoRest would give another error, saying there's multiple variables using the same ID, so that's when I created the yaml file I sent, where I gave new ID's to all variables with an error. After this, it finally generated a class library, where I than used nuget to create a package, than I connected to Visual Studio and started calling the functions, like for example new reach.ReachAPIClient(uri, null).About();, I'm still a bit lost what the created file ReachAPIClienteOptions does, but with this it called the endpoint, with a problem, this API requires a Bearer token to be given in order to work, but I have no idea where to give this token with the file AutoRest created, how do I create a field to insert a Bearer token on a library created by AutoRest? (Sorry for the long text)

**Comment by BrunoASP2001** [comment]
Hi again, sorry for the late response, but I made some progress.
After messing around with some of the code I managed to get it to work and send me a response, problem is, to do so, I had to add the authentication token manually to the Client that AutoRest generated, as you can see in the screenshot bellow:
![image](https://user-images.githubusercontent.com/104068064/187422949-3d0c20b6-4d9b-40b3-809b-7861bf903525.png)

By using the request.Headers.Add, I can add the authorization and the token, problem is that I would need to add this manually to all generated endpoints (which are a lot). Is there any way to do this automatically?
