### ISSUE TITLE
Flags like add-credentials don't do anything

### ISSUE THREAD

**Issue by BrunoASP2001** [Azure/autorest#4625]
**Describe the bug**
Hi everyone, as sort of a continuation of this issue https://github.com/Azure/autorest/issues/4624, I have found another problem, after messing around, I couldn't find a way to authenticate in the code generated from AutoRest with my jwt token, it was when I was searching for examples of generated code (like this one https://github.com/affinda/affinda-dotnet), I found that flags like add-credentials or azure-arm didn't do anything.
For example, on the Affinda project mencioned earlier, in their generated code they have this:

```
public AffindaAPIClient(TokenCredential credential, Uri endpoint = null, AffindaAPIClientOptions options = null)
{
            if (credential == null)
            {
                throw new ArgumentNullException(nameof(credential));
            }
            endpoint ??= new Uri("https://api.affinda.com/v2");
            options ??= new AffindaAPIClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            string[] scopes = { "https://management.azure.com/.default" };
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, scopes));
            RestClient = new AffindaAPIRestClient(_clientDiagnostics, _pipeline, endpoint);
}
```

In here they have a TokenCredentials added by AutoRest, which allows to use credentials, meanwhile, even with add-credentials = true, mine generated this:

```
public ReachAPIClient(Uri endpoint, ReachAPIClientOptions options)
{
            Argument.AssertNotNull(endpoint, nameof(endpoint));
            options ??= new ReachAPIClientOptions();
            ClientDiagnostics = new ClientDiagnostics(options, true);
            _pipeline = HttpPipelineBuilder.Build(options, Array.Empty<HttpPipelinePolicy>(), Array.Empty<HttpPipelinePolicy>(), new ResponseClassifier());
            _endpoint = endpoint;
}
```

As you can see, in my case it doesn't add the TokenCredentials, which means I can't use credentials, what could the issue be here? Is it with AutoRest or is there something missing in the API?

**Expected behavior**
By using flags like add-credentials and azure-arm, AutoRest should generate a code which allows to add credentials in order to authenticate.

**Additional context**
All of the needed info like the API and yaml used, as well as some of the outputs can be found in the previous issue here https://github.com/Azure/autorest/issues/4624.
Other than this, another doubt I have regarding the credentials is that I see in a lot of the docs that the authentication is done trough azure, which in a lot of cases means the service must be hosted in Azure, which isn't my case, in my case they gave me a jwt token which I just inject directly into the code to validate my calls. This is pretty easy to use when I'm making the Http connections manually, but I can't find anything about it with AutoRest generated clients, can I use this token with AutoRest?

**Comment by timotheeguerin** [comment]
Can you try using `--security` flags instead  https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md#configure-using-flagsconfig
