### ISSUE TITLE
Unable to generate python from vsts-rest-api-specs

### ISSUE THREAD

**Issue by jabbera** [Azure/autorest#4641]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**
When attempting to generate python code from [the azure devops specs](https://github.com/MicrosoftDocs/vsts-rest-api-specs) I get the following error:

```
error   | PreCheck/AllOfTypeDifferent | Schema 'JsonPatchDocument' has an allOf reference to 'components·5lk5um·schemas·jsonpatchdocument·allof·0' but those schema have different types:
  - JsonPatchDocument: object
  - components·5lk5um·schemas·jsonpatchdocument·allof·0: array
    - file:///home/<snip>/vsts-rest-api-specs/specification/git/7.1/git.json:15227:9
fatal   | Error: 1 errors occured -- cannot continue.
```

```
git clone https://github.com/MicrosoftDocs/vsts-rest-api-specs.git
autorest --input-file=./vsts-rest-api-specs/specification/git/7.1/git.json --python
```

**Expected behavior**
Code should be generated

**Additional context**
If the azure devops team maintained an updated python api I wouldn't be doing this:-)

**Comment by timotheeguerin** [comment]
hey @jabbera not really sure what this spec would even want to generate.
JsonPatchDocument is both an object and an array 

```yaml
  "JsonPatchDocument": {
      "description": "The JSON model for JSON Patch Operations",
      "type": "object",
      "allOf": [
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/JsonPatchOperation"
          }
        }
      ],
      "properties": {}
    },
```

**Comment by mattmelton** [comment]
I hit this bug today - confirm not not fixed.

I was able to work around it by updating the type to "object" (or removing it). Unfortunately I then hit a YAML parsing exception with the Feed API. I suspect the VSTS team aren't dogfooding/using autorest.
