### ISSUE TITLE
Entry under `paths` getting combined with variant entry under `x-ms-paths`

### ISSUE THREAD

**Issue by jeskew** [Azure/autorest#4652]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**

When an entry in `paths` and a separate entry in `x-ms-paths` are distinguished only by a querystring parameter, Modelerfour appears to be combining the two entries. I'm running into this issue specifically on [Microsoft.ApiManagement@2021-08-01](https://github.com/Azure/azure-rest-api-specs/blob/6c81b8f165ec787728ad1ec286d2d7feabb64da0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json), which defines [a `Microsoft.ApiManagement/service/{serviceName}/apis/{apiId}` path under `paths`](https://github.com/Azure/azure-rest-api-specs/blob/6c81b8f165ec787728ad1ec286d2d7feabb64da0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L113) and [a `Microsoft.ApiManagement/service/{serviceName}/apis/{apiId}?export=true` path under `x-ms-paths`](https://github.com/Azure/azure-rest-api-specs/blob/6c81b8f165ec787728ad1ec286d2d7feabb64da0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4412). When Autorest passes the API definition the Bicep extension, the PUT operation uses the request schema for the entry under `paths` and the GET operation uses the response schema for the entry under `x-ms-paths`:

![image](https://user-images.githubusercontent.com/705500/196250711-63cc195a-c31d-4caa-8c4d-d4285c37e544.png)

**Expected behavior**

The two path entries should result in the creation of two resource type names. I'm not sure what the one based on the `?export=true` variant would be called.

**Additional context**

I assumed this was intended behavior and was going to file a bug against Microsoft.ApiManagement's swagger document, but per my reading of [the `x-ms-paths` docs](https://github.com/stankovski/AutoRest/blob/master/Documentation/swagger-extensions.md#x-ms-paths), this is the kind of scenario for which `x-ms-paths` was designed. If this reading is incorrect, please let me know and I can work with the RP to get their Swagger updated.

**Comment by timotheeguerin** [comment]
Hey @jeskew, I believe what is is doing is expected. The path to use is still that /apis (without query params) but the parameter `export=true` is also specified in the list of parameters.

**Comment by jeskew** [comment]
[The response shape for the path with the `export=true` parameter](https://github.com/Azure/azure-rest-api-specs/blob/6c81b8f165ec787728ad1ec286d2d7feabb64da0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4507) is very different from [the response shape without it](https://github.com/Azure/azure-rest-api-specs/blob/6c81b8f165ec787728ad1ec286d2d7feabb64da0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L198), though. By the time the `microsoft.apimanagement/service/apis` resource type gets passed to the Bicep autorest plugin, the GET operation's response schema is presented as always being of the type used by the `export=true` variant.

Is there any way at that point to recover the response schema for the operation without the additional parameter?

**Comment by timotheeguerin** [comment]
So both operations are there(at least with the repro I tried). You are showing the export one but there should be another operation without that export param that will return the right reaponse

**Comment by jeskew** [comment]
:facepalm: You're absolutely right. There's some logic earlier in the plugin pipeline that is flattening operations into resources based on paths; that is what's getting tripped up on the operation groups with overlapping paths.
