### ISSUE TITLE
 [M4] Test and enable CI for node18

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest#4662]
Node12 has reached EOL and the azure-sdk-for-js repository has officially dropped support for it which prevents yarn from installing @autorest/typescript.

We should validate and enable support for Node18 for our pipeline validation.

**Comment by timotheeguerin** [comment]
That would be great but this is blocked on this https://github.com/Azure/autorest/issues/4639

tree-sitter is not compatible with node 18 yet which is a bit annoying as its just used for regression testing.
