### ISSUE TITLE
[OPENAPI to CADL][question] Package.json is outputting older versions of the CADL packages. 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest#4665]
Command used: `autorest --input-file=<path to swagger> --cadl-init --use=https://aka.ms/autorest.cadl --output-folder=./`

Issue/Question: Several of the packages that are automatically added to the package.json are out of date with the latest version. Should the default behavior be to output these packages pointing to "latest"?

Example package.json ouput:
```
{
  "name": "@cadl-api-spec/anomaly-detector-client",
  "author": "Microsoft Corporation",
  "description": "Multivariate Time-Series Anomaly Detection API",
  "license": "MIT",
  "dependencies": {
    "@cadl-lang/compiler": "^0.35.0",
    "@cadl-lang/rest": "^0.17.0",
    "@cadl-lang/versioning": "^0.8.0",
    "@cadl-lang/prettier-plugin-cadl": "^0.5.15",
    "@azure-tools/cadl-azure-core": "^0.7.0",
    "@azure-tools/cadl-autorest": "^0.20.0",
    "@azure-tools/cadl-python": "^0.2.5",
    "prettier": "^2.7.1"
  },
  "private": true
}
```

**Comment by joheredi** [comment]
This has been resolved in the latest version of the plugin
