### ISSUE TITLE
A bug related to the directive transform

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#4681]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

I use a transform directive as below to make a change on the generated C# code.
```
  - from: TrackedResourceTags.dictionary.cs
    where: $
    transform: $ =  $.replace(/null != property.Key && null != property.Value/g, 'null != property.Key');
```
The weird thing is it works in Linux but not in Windows.

If you want to reproduce the issue, you may add the directive above in https://github.com/Azure/azure-powershell/blob/generation/src/Databricks/README.md and then run autorest in the Databricks folder in a Windows machine.

I run autorest --debug in both Windows and Linux. The only different I can see from the log is that in Linux, we have something like below in the log while Windows not.

```
debug   | [13.02 s] Running text transform 'TrackedResourceTags.dictionary.cs/undefined' on mem:///267?generated%2Fapi%2FModels%2FApi20210401Preview%2FTrackedResourceTags.dictionary.cs
```

I tend to think the issue is in https://github.com/Azure/autorest/blob/main/packages/extensions/core/src/lib/plugins/transformer/transformer.ts#L28.

BTW, I use node 14.15.5 and autorest core version is 3.9.3.

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```

**Expected behavior**

**Additional context**

**Comment by timotheeguerin** [comment]
@dolauli have you followed the directive debug steps to see what is going on? https://github.com/Azure/autorest/blob/main/docs/generate/directives.md#debug-a-directive

**Comment by dolauli** [comment]
> @dolauli have you followed the directive debug steps to see what is going on? https://github.com/Azure/autorest/blob/main/docs/generate/directives.md#debug-a-directive
@timotheeguerin Thanks for sharing the link.
I try to turn on the debug based on the link you provided as below, but it seems not to make a difference, and no more valuable logs are printed out.
And according to what I observe, it seems the file TrackedResourceTags.dictionary.cs is not picked out to do the transform in Windows. And if I change it to `source-file-csharp`, it works in both Windows and Linux, but I do not want to apply the replace in all generated C# files.

```
  - from: TrackedResourceTags.dictionary.cs
    where: $
    debug: true
    transform: |
        $lib.log($);
        $ =  $.replace(/null != property.Key && null != property.Value/g, 'null != property.Key');
```

**Comment by timotheeguerin** [comment]
@dolauli is there something maybe about the casing of the file emitted? Because windows is not case sensitive maybe its written as a different name but then in the directive it check case sensitively?

**Comment by timotheeguerin** [comment]
Ok this seems to be because on windows the csharp file is being emitted with `\` ....

```
/generated\api\Models\Api20220401Preview\TrackedResourceTags.dictionary.cs
```

**Comment by timotheeguerin** [comment]
@dolauli can you verify this is fixing the problem? https://github.com/Azure/autorest/pull/4683#issuecomment-1339729111

**Comment by dolauli** [comment]
@timotheeguerin Verified the issue is fixed.
