### ISSUE TITLE
Autorest started failing for any swagger endpoint

### ISSUE THREAD

**Issue by HEBOS** [Azure/autorest#4682]
**Before filling a bug**

- [x ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x ] have you checked existing issues

**Describe the bug**
Running autorest for any endpoint just fails.
For example:
It stuck on CheckDuplicateSchemas.

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```
autorest --typescript --output-folder=./test --input-file=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/json/api-with-examples.json --license-header=MICROSOFT_MIT_NO_VERSION --sync-methods=none --verbose --version:3.6.2

or with the increased memory

SET NODE_OPTIONS=--max_old_space_size=8192&&autorest --typescript --output-folder=./test --input-file=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/json/api-with-examples.json --license-header=MICROSOFT_MIT_NO_VERSION --sync-methods=none --verbose --version:3.6.2

**Expected behavior**

Autorest to complete

**Additional context**

**Comment by HEBOS** [comment]
If I leave out parameter "version", then it works.

autorest --typescript --output-folder=./test --input-file=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/json/api-with-examples.json --license-header=MICROSOFT_MIT_NO_VERSION --sync-methods=none --verbose

**Comment by timotheeguerin** [comment]
hey @HEBOS could you share the logs of the failure? Version 3.6.2 is also not the latest, does it still fail with 3.9.3?
