### ISSUE TITLE
Autorest fails with Syntax error: unexpected end of the stream within a flow collection

### ISSUE THREAD

**Issue by amandalim95** [Azure/autorest#4686]
Before asking the question:

- [ x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [ x] have you checked existing issues for a similar question?

Running the following command:
autorest --az --version=3.0.6370 --use=@autorest/az@latest --tag=v2022-11-11-preview --azure-cli-extension-folder={azure-cli-extension folder} specification/devcenter/resource-manager/readme.md --debug

Output:
AutoRest code generation utility [cli version: 3.6.0; node: v16.13.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: 3.0.6370.
debug   | [0.80 s] Network Enabled: true

There is a new version of AutoRest available (3.6.2).
 > You can install the newer version with with npm install -g autorest@latest

debug   | [0.88 s] The most recent installed version is 3.0.6370
debug   | [0.88 s] Starting @autorest/core from C:\Users\amlim\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core
  Error: Syntax error: unexpected end of the stream within a flow collection

Any advice on how to fix this issue?

**Comment by timotheeguerin** [comment]
Hey @amandalim95 can you try updating autorest the `--version` you are using is 3 years old.

**Comment by amandalim95** [comment]
Hi, @timotheeguerin there seems to be some issues with generating the CLI with newer autorest versions (https://github.com/Azure/autorest.az/issues/898) and the suggestion is to use version 3.0.6370. When updating our rest API spec for our previous 10-12 version last month, this generation worked. I was wondering whether our newer API version has any issues and is there any way to debug this if it is from our API spec?

**Comment by timotheeguerin** [comment]
You can try using `--debug --verbose` to have more information but there is a lot of information lacking  at that old version.
