### ISSUE TITLE
Default Constructor

### ISSUE THREAD

**Issue by phil000** [Azure/autorest#469]
The default constructor of the generated service client sets the base URI of the service to the value provided in the swagger specification, which would typically only be correct for the single environment where the client was generated from. Given you would typically generate the client once the default constructor is not going to work in any of the other environments you may have ... local dev, dev integration, test, UAT, production,... so serves virtually no useful purpose and perhaps should just be removed to avoid ambiguity. (Would anybody generate the client again off a different spec for a new environment that would pickup a new base URI)

I note that the version is still 0.12.0, so according to the semantic versioning spec major version zero is for initial development and anything may change at any time, as this would be a breaking change.

**Comment by stankovski** [comment]
Actually in general scenarios (non-Azure) as well as in Azure specific scenarios, having a default URI that points to the production end-point makes for a more user-friendly API. Test, UAT, and dev environments are usually associated with internal tests and are not the primary scenarios. As such while we attempt to enable all scenarios, we optimize for the primary scenarios first.
