### ISSUE TITLE
Changing attributes with a directive

### ISSUE THREAD

**Issue by t0mk** [Azure/autorest#4694]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

Hey, thanks for autorest, I'm using it to generate Python SDK and it looks really promising.

I'm struggling with directives. I need to fix my OpenAPI spec, I need to change `format: integer` to `format: int64`. I also need to change `type: number` to `type: integer`. 

I need to go from this:

```
      "BgpNeighborData": {
        "properties": {
          "address_family": {
            "description": "Address Family for IP Address. Accepted values are 4 or 6",
            "example": 4,
            "format": "integer", <<
            "type": "number" <<
          },
```

to this:

```
      "BgpNeighborData": {
        "properties": {
          "address_family": {
            "description": "Address Family for IP Address. Accepted values are 4 or 6",
            "example": 4,
            "format": "int64", <<
            "type": "integer" <<
          },
```

Could someone help me to write the directive? Or point me to some example? Thanks!

**Comment by timotheeguerin** [comment]
Hey @t0mk did you see the directive docs here with some of the examples https://github.com/Azure/autorest/blob/main/docs/generate/directives.md

There is a debug section that guides you to diagnostic why your directive might not do what you expect https://github.com/Azure/autorest/blob/main/docs/generate/directives.md#debug-a-directive

Let me know if you are still having issues

**Comment by t0mk** [comment]
Hey, I decided to manipulate the API doc by preprocessing it in Python, it's just easier for me. You can close this if you want.
