### ISSUE TITLE
Codegen bug Circular refrenced models

### ISSUE THREAD

**Issue by anthony-affinda** [Azure/autorest#4705]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Having a directory like this: (files below)
```
  readme.md
  generated/api_spec/api_spec.yaml
```
[readme.md](https://github.com/Azure/autorest/files/10519737/readme.md)
[api_spec.txt](https://github.com/Azure/autorest/files/10519762/api_spec.txt) (change to .yaml file)

And running this autorest command: ``autorest readme.md --python``

We get this error:
```
in property: 0 
  in property: immediate 
  in property: children 
  in property: 0 
  in property: immediate 
  in property: parents 
  in property: schema 
  in property: 0 
  in property: properties 
  in property: schema 
fatal   | Error: Circular refrenced models are not permitted in apply() initializers.
fatal   | Process() cancelled due to failure 
error   |   Error: Plugin modelerfour reported failure.
```

**Expected behavior**
Python client library generates successfully.

**Additional context**
When we remove the $ref to ``Annotation_v2`` (comment this line out: ``- $ref: '#/components/schemas/Annotation_v2'``), the client lib is generated successfully.

**Comment by anthony-affinda** [comment]
Update: if I change the requestBody's content type from `multipart/form-data` to `application/json`, it doesn't complain. But if I keep it as `multipart/form-data`, and explicitly write out  the spec (instead of using $refs), it also doesn't complain.

**Comment by timotheeguerin** [comment]
Hey @anthony-affinda this does looks like a bug, thanks for reporting, simplified your spec a little bit with minimal repro.

```yaml
openapi: 3.0.3
info:
  version: v3
  title: API
paths:
  /v2/job_descriptions:
    post:
      operationId: testCircularRefIssue
      responses:
        '200':
          description: Ok
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              title: JobDescriptionRequestBody
              additionalProperties: false
              properties:
                data:
                  $ref: '#/components/schemas/JobDescriptionData'
components:
  schemas:
    Annotation_v2:
      type: object
      properties:
        raw:
          type: string
          nullable: true
    TextAnnotation_v2:
      type: object
      nullable: true
      allOf:
        - $ref: '#/components/schemas/Annotation_v2'
    JobDescriptionData:
      type: object
      additionalProperties: false
      nullable: true
      properties:
        contactEmail:
          $ref: '#/components/schemas/TextAnnotation_v2'

```

**Comment by anthony-affinda** [comment]
Thanks @timotheeguerin ! Looking forward to the merge 👍
