### ISSUE TITLE
Autorest on build/continuous integration

### ISSUE THREAD

**Issue by damienpontifex** [Azure/autorest#471]
I was interested in generating client libraries on each build with continuous integration (possible as a Visual Studio post build step). Although Swagger/Swashbuckle with Web API seem to only expose the json metadata document as a REST endpoint.

The point being to potentially generate nuget packages for our libraries internally without other projects having to generate them off Azure API App endpoints.

Is it possible to use the autorest tool to generate these client libraries as such? Or to combine the autorest tool with another to solve this case?

**Comment by stankovski** [comment]
I apologize but I'm not quite sure what you're asking about. You should be able to generate the client via `autorest.exe` [see documentation](https://github.com/Azure/autorest/tree/master/Documentation). Then you can use nuget.exe to package the generated client.

**Comment by damienpontifex** [comment]
Sorry @stankovski my main point was with swashbuckle, the json file is not generated to disk and usually accessible at /swagger/docs/v1. 

Considering this, I was wondering if there was a method to utilise autorest.exe without starting up the project and pointing it to the REST endpoint? i.e. generate it from the same c# metadata that swashbuckle uses to generate the json file originally?

**Comment by stankovski** [comment]
In autorest.exe you can provide a URI as input parameter. So assuming swashbuckle provides an endpoint with swagger json you'll be able to achieve your scenario.

**Comment by damienpontifex** [comment]
Yes, I had done this, but requires the web process to startup so it can access the endpoint. Probably the only way for now, but thought I'd ask.

Thanks @stankovski

**Comment by weitzhandler** [comment]
I reposted this as a feature request [here](#1823).
