### ISSUE TITLE
Suppression doesn't work for rule OperationsAPIImplementation

### ISSUE THREAD

**Issue by live1206** [Azure/autorest#4723]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

```
npx autorest --v3 --version:next --spectral --validation --azure-validator --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/openapi-validator@beta --tag=package-deploymentstacks-2022-08-preview https://github.com/Azure/azure-rest-api-specs/blob/0bbb664b337da64df7ff939884818e67b4b11094/specification/resources/resource-manager/readme.md
```

**Expected behavior**
Doesn't report error of `OperationsAPIImplementation`.

**Additional context**
Tried both `directive` and `suppression` in [readme.md](https://github.com/Azure/azure-rest-api-specs/blob/0bbb664b337da64df7ff939884818e67b4b11094/specification/resources/resource-manager/readme.md#suppression)

**Comment by timotheeguerin** [comment]
Seems to have been an issue with suppression conflicting each other and only the last one defined really matter. I have a fix in PR now.
