### ISSUE TITLE
Schema violation: No enum match for: operation-location

### ISSUE THREAD

**Issue by am-lim** [Azure/autorest#4730]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

Running autorest on our swagger and get the following error, how do we resolve this schema violation? Was not seeing this error in our previous API version that used operation-location and nothing has changed.
operation-location should be valid https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options

Link to swagger file: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json

Error details:
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:restart > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:1120:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:stop > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:1041:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:start > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:960:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName} > delete > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:878:5
C:\Users\amlim\.autorest\@autorest_core@3.0.6370\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:restart > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:1120:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:stop > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:1041:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName}:start > post > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:960:5
ERROR: Schema violation: No enum match for: operation-location (paths > /projects/{projectName}/users/{userId}/devboxes/{devBoxName} > delete > x-ms-long-running-operation-options > final-state-via)
    - file:///C:/Users/amlim/source/repos/azure-rest-api-specs/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json:878:5

**Comment by timotheeguerin** [comment]
Hey @am-lim, I am not seeing this issue, are you using an outdated autorest version by chance?

**Comment by am-lim** [comment]
@timotheeguerin, closing the issue because after investigation autorest.az is deprecated and does not work for data plane APIs
