### ISSUE TITLE
I can't generate c# classes

### ISSUE THREAD

**Issue by naturalspirit-dev** [Azure/autorest#4735]
Before asking the question:
![Screenshot_26](https://user-images.githubusercontent.com/128178042/236627369-b1dd78f1-b4fd-4666-a249-c32a4d70b061.png)

**Comment by timotheeguerin** [comment]
Hey @naturalspirit-dev do you have `dotnet` installed?

**Comment by naturalspirit-dev** [comment]
Of course.
I had a problem with the json file and now I have solved.
Thank you.
