### ISSUE TITLE
autorest spectral validation hanging

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest#4747]
Hi, I'm working on https://github.com/Azure/azure-rest-api-specs-pr/pull/11977 and trying to reproduce these validation failures https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/2818784/logs/361 . When I try to reproduce the validation errors, autorest appears to hang in both Windows and WSL Debian instances.

autorest appears hung in Windows here:
![image](https://github.com/Azure/autorest/assets/87583576/33a5d476-e047-40d8-9dd6-803b8cde1e4b)

autorest appears hung in WSL Debian here:
![image](https://github.com/Azure/autorest/assets/87583576/cc752b5b-9f1a-42bf-86d7-4fe8340905c0)

For Windows, I ran:
```
PS C:\Users\cataggar\ms\azure-rest-api-specs-pr> node --version
v18.15.0
PS C:\Users\cataggar\ms\azure-rest-api-specs-pr> echo $env:NODE_OPTIONS
--max-old-space-size=8192
PS C:\Users\cataggar\ms\azure-rest-api-specs-pr> autorest --v3 --spectral --azure-validator --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/openapi-validator@2.1.2 --tag=package-2023-09-01 specification\vmware\resource-manager\readme.md
```

For WSL Debian, I ran:
```
cataggar@CPC-catag-TL2L0:~/ms/azure-rest-api-specs-pr$ node --version
v20.2.0
cataggar@CPC-catag-TL2L0:~/ms/azure-rest-api-specs-pr$ autorest --v3 --spectral --azure-validator --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/openapi-validator@2.1.2 --tag=package-2023-09-01 specification/vmware/resource-manager/readme.md
```

If I try adding `--use=@autorest.core@3.9.6`, it still reports that `3.2.0` is being used:
``` json
{"level":"information","message":"AutoRest core version selected from configuration: \u001b[33m\u001b[1m^3.2.0\u001b[22m\u001b[39m."}
```

**Comment by cataggar** [comment]
I was on the right track. Bumping the version worked, but it is done with `--version` . This worked.
```
autorest --version=3.9.6 --spectral --azure-validator --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/openapi-validator@2.1.2 --tag=package-2023-09-01 specification/vmware/resource-manager/readme.md
```

I'm guessing that the older 3.2.0 has problems with my nodejs versions.

**Comment by cataggar** [comment]
I runs now, but I am only seeing `{​​​​​​​​​"pluginName":"classic-openapi-validator"` messages and nothing from `{​​​​​​​​"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator"`.

**Comment by cataggar** [comment]
I needed both `--v3` and `--version`, but I still do not have the details. These instructions are definitely incomplete:
https://github.com/Azure/azure-rest-api-specs-pr/blob/main/documentation/ci-fix.md#lintdiff-validation

```
autorest --v3 --version=3.9.6 --spectral --azure-validator --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/openapi-validator@2.1.2 --tag=package-2023-09-01 --verbose specification/vmware/resource-manager/readme.md 
```

I get the overview:
```
{"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"Spectral rule, severity 'Error': 'PutResponseSchemaDescription'"}
```

But I'm still missing the details like:
```
2023-06-02T08:57:08.6692669Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"error","message":"Description of 200 response code of a PUT operation MUST include term \"update\".","code":"PutResponseSchemaDescription","details":{"jsonpath":["paths","/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}","put","responses"],"providerNamespace":false,"resourceType":false,"range":{"start":{"line":572,"column":20},"end":{"line":588,"column":112}}},"source":[{"document":"file:///mnt/vss/_work/1/azure-rest-api-specs-pr/specification/vmware/resource-manager/Microsoft.AVS/stable/2023-09-01/vmware.json","position":{"line":572,"column":9}}]}
```

**Comment by cataggar** [comment]
Nevermind, it is there. It is not missing.

**Comment by konrad-jamrozik** [comment]
@cataggar:

- https://github.com/Azure/azure-rest-api-specs/pull/24280
