### ISSUE TITLE
Hang when generating container registry with latest core/M4

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4749]
core: 3.9.6
m4: 4.26.2

repro:
have rush installed
git clone -b update_core_m4 --single-branch https://github.com/jhendrixMSFT/autorest.go.git
rush update
rush build (ignore build error for autorest.gotest)

git clone https://github.com/Azure/azure-sdk-for-go.git
cd azure-sdk-for-go/sdk/containers/azcontainerregistry
edit autorest.md line 15 to `use: <path to autorest.go code generator built earlier>`
autorest autorest.md

results:
build hangs, presumably somewhere in the prechecker
```
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
verbose | [5.79 s] Found and removed 0 duplicate schema
^C
```

**Comment by timotheeguerin** [comment]
hhm I can't seem to repro, running this 
```
autorest --use="~/dev/azsdk/autorest.go/packages/autorest.go" autorest.md --debug
```

and I am on your branch in autorest.go 
![image](https://github.com/Azure/autorest/assets/1031227/dec148cd-5739-4aac-954e-c58883a4d612)

**Comment by jhendrixMSFT** [comment]
Appears to be Windows only.

**Comment by jhendrixMSFT** [comment]
This was due to shenanigans with the control-plane build scripts.  They were overriding the core version to 3.8.2.

**Comment by timotheeguerin** [comment]
For anybody else getitng into this issue using the latest core `3.9.6` solves the issue.
