### ISSUE TITLE
How to generate examples with x-ms-examples?

### ISSUE THREAD

**Issue by danaelhe** [Azure/autorest#4756]
Before asking the question:

- [ x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x ] have you checked existing issues for a similar question?

To my understanding, the x-ms-examples extension can generate examples for you in an `examples` folder. I can't seem to get the examples to be generated with my basic openapi 3.0 example:

```
openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
      x-ms-examples:
        basicExample:
          summary: Basic example
          value:
            requestBody:
              name: John Doe
              email: john@example.com
        advancedExample:
          summary: Advanced example
          value:
            requestBody:
              name: Jane Smith
              email: jane@example.com
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
```

Then I run:
`autorest --input-file=spec.yaml --python`

and according to the documentation, I'm expecting there to be an examples folder generated with examples inside but it does not get generated. What am I doing wrong?

Thanks!

**Comment by timotheeguerin** [comment]
Hi @danaelhe autorest itself doesn't provide example generation. This is provided as part of `oav generate-examples` See here https://github.com/Azure/oav
