### ISSUE TITLE
Go SDK generation failure via autorest

### ISSUE THREAD

**Issue by thomasricci** [Azure/autorest#4757]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
I've created a new API spec version recently and now I'm trying to generate SDKs for it. This is the PR for the swagger changes:
https://github.com/Azure/azure-rest-api-specs/pull/24618

The PR is currently blocked by a check to validate the creation of the go SDK via autorest

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2878222&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```

**Expected behavior**
Running the autorest command I was able to generate the go SDK successfully on my local machine.

C:\workspace\azure-rest-api-specs\specification\dnc\resource-manager (thomasricci-dnc-Microsoft.DelegatedNetwork-2023-05-18-preview)
λ autorest readme.md --go
AutoRest code generation utility [cli version: 3.6.3; node: v14.17.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    |    Loading AutoRest core      'C:\Users\thricci\.autorest\@autorestcore@3.9.4\nodemodules\@autorest\core\dist' (3.9.4)
info    |    Loading AutoRest extension '@autorest/go' (~4.0.0-preview.42->4.0.0-preview.51)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.23.1->4.23.1)
warning | PreCheck/SchemaMissingType | The schema 'OrchestratorResourceUpdateParameters' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
    - file:///C:/workspace/azure-rest-api-specs/specification/dnc/resource-manager/Microsoft.DelegatedNetwork/preview/2023-05-18-preview/orchestrators.json:365:5
warning | PreCheck/SchemaMissingType | The schema 'OrchestratorIdentity' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
    - file:///C:/workspace/azure-rest-api-specs/specification/dnc/resource-manager/Microsoft.DelegatedNetwork/preview/2023-05-18-preview/orchestrators.json:466:5
warning | PreCheck/SchemaMissingType | The schema 'ResourceUpdateParameters' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
    - file:///C:/workspace/azure-rest-api-specs/specification/dnc/resource-manager/Microsoft.DelegatedNetwork/preview/2023-05-18-preview/delegatedSubnets.json:348:5
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
warning | UsingTemporaryFlag | modelerfour.treat-type-object-as-anything options is a temporary flag. It WILL be removed in the future.
info    | Autorest completed in 5.56s. 9 files generated.

**Additional context**

**Comment by mikekistler** [comment]
This does not appear to be a bug in autorest, since you showed that autorest will generate the Go SDK successfully.

For help in unblocking your PR, please use the [Service API Toolset Teams channel](https://aka.ms/azsdk/support/spectools-channel).

**Comment by thomasricci** [comment]
It was mentioned in that pipeline to open an issue here for support.
Thanks, I'll close the issue then since today it seems the check is happy.
