### ISSUE TITLE
Need flag to give folder name for tests

### ISSUE THREAD

**Issue by tomrlake** [Azure/autorest#4769]
**Is your feature request related to a problem? Please describe.**
The main set of files are generated in the folder the is set with the output flag.  Unfortunately, the tests are created in a folder named tests.  I like the placement of the folder but would like to be able to choose the name that is used.

**Describe the solution you'd like**
Add new flag --tests-folder-name so that the user can decide what the name is.

**Describe alternatives you've considered**
The user needs to rename the folder manually, or if they have previously done this, they need to copy all the files from the newly generated tests folder into the folder that they want them to be in.

**Additional context**
No

**Comment by timotheeguerin** [comment]
Hi @tomrlake which SDK language is this feature request?
