### ISSUE TITLE
VS Code - TypeError: js_yaml_1.Schema.create is not a function - Node v18 - Autorest 3.0.6320

### ISSUE THREAD

**Issue by oragain** [Azure/autorest#4770]
Attempted to generate api code from openapi spec on Windows 11 in Visual Studio Code using autorest

**Command**: autorest --input-file:"c:\Users\olivi\OneDrive\Code\Optima\APIs\alphaapi.yaml" --version:3.0.6173 --azure-functions-typescript --no-namespace-folders:True --generate-metadata:false --output-folder:"c:\Users\olivi\OneDrive\Code\Optima\APIs"

AutoRest code generation utility [cli version: 3.6.3; node: v18.17.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: 3.0.6320.
   Loading AutoRest core      'C:\Users\olivi\.autorest\@autorestcore@3.0.6320\nodemodules\@autorest\core\dist' (3.0.6320)
   Loading AutoRest extension '@autorest/azure-functions-typescript' (latest->0.0.1-preview)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.396->4.15.396)
C:\Users\olivi\.autorest\@autorest_azure-functions-typescript@0.0.1-preview\node_modules\@azure-tools\codemodel\dist\model\yaml-schema.js:38
exports.codeModelSchema = js_yaml_1.Schema.create(js_yaml_1.DEFAULT_SAFE_SCHEMA, [
                                           ^

TypeError: js_yaml_1.Schema.create is not a function

**Expected behavior**
Generating the api code in typescript

**Additional context**
Node.js v18.17.1

**Comment by timotheeguerin** [comment]
Hi @oragain  I am not sure the azure functions typescript generator is being maintained(no new version in last 3 years https://www.npmjs.com/package/@autorest/azure-functions-typescript) , this looks like a lot of out of date versions.
