### ISSUE TITLE
[openapi-to-tsp] Improve tspconfig.yaml

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest#4787]
Can we emit a tspconfig.yaml with the following configuration for typespec-autorest: 

```
"@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/ContosoWidget.json"
```

This config is the default necessary for checking in specs in the azure rest api specs repo. Maybe this needs a flag to specify that we do this only for Azure specs?

**Comment by catalinaperalta** [comment]
It might be best to simply copy the tspconfig.yaml that the TypeSpec team adds when doing `tsp init`. Likewise we could try running `tsp init` under the hood and remove/rewrite the other files with the converter output, keeping only the tspconfig.yaml...this way there is one source of truth for the recommended tspconfig.yaml.

**Comment by joheredi** [comment]
@catalinaperalta I agree with the idea of running `tsp init`. Do you think this is something that tsp-client can do when running `convert`?

**Comment by catalinaperalta** [comment]
My concern with doing this in tsp-client is if we ever have a use case of someone having to run the openapi-to-typespec extension directly they wont get a complete output. Let me know what you think

**Comment by joheredi** [comment]
Yeah, that's fair. I'll start by updating the config that gets generated to unblock this use case. In my initial exploration spawning processes from the autorest extension has some challenges, so starting with the simple fix to move forward.
