### ISSUE TITLE
Duplicate object schemas with 'ArrayItemschema' name  detected.

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/autorest#4840]
What does this error mean?

I cannot find anything in the JSON that matches any variation of `ArrayItemschema`, `ArrayItems`, `ArrayItem` and so on.

Is there a way to ignore this error or a hint as to were to look? The spec for this API is 40K lines long..

```
PS D:\> autorest .\regenerate.yaml
AutoRest code generation utility [cli version: 3.7.1; node: v20.10.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    |    Loading AutoRest core      'C:\Users\strandedpirate\.autorest\@autorestcore@3.10.1\nodemodules\@autorest\core\dist' (3.10.1)
info    |    Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20231212.1)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.26.0->4.26.0)
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
warning | ? | Operation 'Orders/DeleteOrderItems' really should not have a media type (because there should be no body)
warning | ? | Operation 'PurchaseOrders/DeletePurchaseOrderItems' really should not have a media type (because there should be no body)
error   | Duplicate object schemas with 'ArrayItemschema' name  detected.
fatal   | Error: 1 errors occured -- cannot continue.
fatal   | Process() cancelled due to failure
error   |   Error: Plugin checker reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
````

**Comment by timotheeguerin** [comment]
This can often happen when you have anonymous schemas in your spec and autorest will try to give it a name like the parent schema name + the property name (e.g. `Array` + `Itemschema`) 

I do not believe you can suppress that and if you did it would then cause some invalid code to be generated where 2 classes/type will have the same name.

**Comment by Strandedpirate** [comment]
Thanks, yes, the spec is here. Unfortunately its a third party that we are about to pay for their service, and its not likely they will fix their spec.

[https://af.api.sellercloud.com/rest/swagger/docs/v1](https://af.api.sellercloud.com/rest/swagger/docs/v1)

**Comment by timotheeguerin** [comment]
Hi @Strandedpirate the errors seems to be coming from non named enums inside of arrays there is 9 of them. for example if you search for the one with this description
```
 0 = Local_Store ,  1 = eBayOrder ,  2 = eBaySingleItem ,  3 = Yahoo ,  4 = Amazon ,  5 = PriceGrabber ,  6 = Website ,  7 = Buy ,  12 = NewEggMall ,  15 = Magento ,  16 = QuickBooks ,  17 = RMS ,  18 = Cart32 ,  19 = Sears ,  20 = FBA ,  21 = Wholesale ,  22 = Overstock ,  23 = NewEggdotcom ,  24 = Etsy ,  25 = Bonanza ,  26 = PriceFalls ,  27 = Wayfair ,  28 = UnbeatableSale ,  29 = VendorCentral ,  30 = Hayneedle ,  31 = SmartBargains ,  32 = uBid ,  33 = ATGStores ,  34 = StacksAndStacks ,  35 = Sharkstores ,  36 = BestBuy ,  37 = Kohls ,  38 = Staples ,  39 = OneStopPlus ,  40 = Meijer ,  41 = Sonsi ,  42 = Walmart ,  43 = HSN ,  44 = NewEgg_Business ,  45 = KMart ,  46 = Wish ,  47 = SPRichards ,  48 = FingerHut ,  49 = Groupon ,  50 = Walmart_Marketplace ,  51 = ShopHQ ,  52 = PriceMinister ,  53 = GS ,  54 = DrugStore ,  55 = MercadoLibre ,  56 = JET ,  57 = ElevenMain ,  58 = SearsVendor ,  59 = Choxi ,  60 = TradeMe ,  61 = Tanga ,  62 = Target ,  63 = GrouponMarketplace ,  64 = Reverb ,  65 = BedBathAndBeyond ,  66 = Dropship_Central ,  67 = DSW ,  68 = Houzz ,  69 = Gilt ,  70 = BestBuyDS ,  71 = TopHatter ,  72 = HomeDepot ,  73 = MassGenie ,  74 = Cdiscount ,  75 = GrouponGateway ,  76 = SBN ,  77 = GoogleExpress ,  78 = Target_Plus ,  79 = WFS ,  80 = BackMarket
```

Autorest is currently in maintenance mode as we are moving to a new language for defining apis so changing anything related to naming or investing too much time here is not something we can really do.

I know the experience here is pretty bad to figure out which ones are the offending schemas but autorest does also provide some directive you can use to patch the swagger so you don't need to actually change the file. 
For example: https://github.com/Azure/autorest/blob/main/docs/generate/directives.md

I would maybe look at some alternative openapi generators as autorest might not see much upgrades in the future

**Comment by Strandedpirate** [comment]
Ok, thanks. I'll check out the directive and see if I can get around this issue.
