### ISSUE TITLE
[TSP] Support flatten in TSP conversion tool

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest#4850]
**Is your feature request related to a problem? Please describe.**
Based on decision for the archboard review for 'Flatten', we will introduce a new decorator for flattening. https://github.com/Azure/typespec-azure/issues/13

We need to support that in Swagger TSP conversion tool as well.

**Describe the solution you'd like**
support the new decorator for flattening in Swagger TSP conversion tool.

**Comment by joheredi** [comment]
@lirenhe should we tag this with `Brownfield`? IIRC this would be discouraged for new specs, so `greenfield` conversions wouldn't need this, correct?

**Comment by tadelesh** [comment]
for conversion, we will always add it, original swagger is the grand truth. if the service does not need it, then we shall remove them manually.

**Comment by joheredi** [comment]
But do we expect greenfield services to flatten? My understanding was that flattening was introduced for backwards compatibility but discouraged for new specs

**Comment by lirenhe** [comment]
There are green field services that still want to flatten.  ElasticSan is a simple that they required 'flatten' to be enabled for their dotnet SDK as they don't want the behavior change from their released preview SDK.
