### ISSUE TITLE
[TSP] Escape character issue of */

### ISSUE THREAD

**Issue by dvbb** [Azure/autorest#4876]
### Impacted RP

Blueprint

### Description

SWAGGER
![image](https://github.com/Azure/autorest/assets/61542202/e7dd84b3-c1d0-4957-ae03-09478db8b174)
TSP:
![image](https://github.com/Azure/autorest/assets/61542202/95f20a93-b2d9-44b2-8cee-e8840c6de896)

**Comment by tadelesh** [comment]
Also need to escape `@`, wait for TSP [suggestion](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1707198801882?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1707198801882&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1707198801882).

**Comment by tadelesh** [comment]
Will fall back to use @doc if contains `@` and `*/`.
