### ISSUE TITLE
Autorest doesn't support produces/consumes other than Json

### ISSUE THREAD

**Issue by schmitch** [Azure/autorest#490]
Hello, currently we have some endpoints with 
```
     produces:
        - text/plain
      consumes: 
        - "text/plain; charset=utf-8"
```

However autorest assumes it is json anyway.

**Comment by devigned** [comment]
We are focused on JSON only at this point. We will be adding others, but that's probably a little farther down the line (after the turn of the year). If you would like to contribute a pull request for this functionality, we'll gladly review it.

**Comment by schmitch** [comment]
Sorry but I'm not a C# Guy so I can't help you. I'm just using to generate a Rest Client for a Java/Scala API.

**Comment by devigned** [comment]
@schmitch got it. We'd love for you to use autorest for your code generation, but this might fit better with the [swagger codegen](https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library). Do you think this would work for your case?

**Comment by xingwu1** [comment]
This is actually a bug in Java autorest. It will be fixed sooon.

**Comment by stankovski** [comment]
Closing as there are currently no plans to support formats other than JSON
