### ISSUE TITLE
Error on converting Swagger API to TypeSpec

### ISSUE THREAD

**Issue by satravi** [Azure/autorest#4906]
Before asking the question:

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [X] have you checked existing issues for a similar question?

The conversion script from https://azure.github.io/typespec-azure/docs/category/convert-swagger-to-typespec has 2 stages.
GenerateMetadata => Completed successfully and the .cs files got generated.
DoConvert => Throws below error

`Error: ENOENT: no such file or directory, open 'C:\Users\<user>\.autorest\@autorestopenapi-to-typespec@0.7.0-dev.12\nodemodules\@autorest\openapi-to-typespec\typeSpec\resources.json'`

Below is the command that we executed for DoConvert

`autorest  --version=3.10.1 --openapi-to-typespec --isArm --use="@autorest/openapi-to-typespec@0.7.0-dev.12" --output-folder="typeSpec" .\readme.md`

**Comment by timotheeguerin** [comment]
I believe this was resolved offline, feel free to comment with the solution or reopen if not.

**Comment by satravi** [comment]
Have successfully converted the APIs to TypeSpec format.
Our readme.md directory path had a space in the directory name. After removing the space from the directory name, it worked fine.
