### ISSUE TITLE
Handle recent change for tsp arm template

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest#4940]
1. Deprecated: Use Azure.Core.armResourceIdentifier<AllowedResourceTypes> instead。
2. @azure-tools/typespec-azure-resource-manager/arm-resource-name-pattern: The resource name parameter should be defined with a 'pattern' restriction.  Decorate the "name" property in the resource definition using the @pattern decorator, with a regular expression indicating the allowed characters in the resource name.
3. @azure-tools/typespec-azure-resource-manager/retry-after: For long-running operations, the Retry-After header indicates how long the client should wait before polling the operation status, please add this header to the 201 or 202 response for this operation.

**Comment by pshao25** [comment]
I think all of these resolved. Let me know if I missed anything.
