### ISSUE TITLE
Generated TypeScript interfaces should be prefixed with an I

### ISSUE THREAD

**Issue by areijngoudt** [Azure/autorest#498]
The TypeScript interfaces are now named after there classes. Convention is that they are prefixed with an I, so export interface IClassName { ... }

**Comment by devigned** [comment]
@BretJohnson please give this a look.

**Comment by BretJohnson** [comment]
@areijngoudt Those interfaces are essentially the type definitions that go with the JavaScript classes.   Plus TypeScript conventions here https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines explicitly suggest not using an I prefix for interfaces.   So I think we'd want to leave it as is.   Still, let us know if you can point to counterexamples or a specific concern.

**Comment by devigned** [comment]
Thank you, Bret. I'm going to close the issue for now.
