### ISSUE TITLE
[tsp-client convert] ARM converter adds @useAuth to main.tsp

### ISSUE THREAD

**Issue by darkoa-msft** [Azure/autorest#5001]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

`tsp-client convert --arm` adds `@useAuth(AadOauth2Auth<["user_impersonation"]>)` to main.tsp, which causes the wrong security definition to be created in ARM swagger. 

**Expected behavior**
After conversion, running `tsp compile` should produce the standard security definition.

**Additional context**
To repro, take an existing swagger, convert it and check main.tsp

**Comment by pshao25** [comment]
@darkoa-msft it's known issue now. Please fix it manually on the generated specs directly.

**Comment by pshao25** [comment]
We don't have solution because of M4 limitation. Close it for now.
