### ISSUE TITLE
why the nuget package Microsoft.Rest.ClientRuntime.Azure.Authentication restrict the dependency Microsoft.IdentityModel.Clients.ActiveDirectory only to 2.18

### ISSUE THREAD

**Issue by liuhongbo** [Azure/autorest#518]
Can we loose the restriction to <3.0?   there is already a new version 2.19 released? 
The restriction made it hard to use it with some other packages also dependent on the Microsoft.IdentityModel.Clients.ActiveDirectory.

**Comment by stankovski** [comment]
Microsoft.IdentityModel.Clients.ActiveDirectory library owners change AssemblyVersion for every build. As such we have to have exact dependency since we compile against specific AssemblyVersion.
