### ISSUE TITLE
Fails on YAML comments

### ISSUE THREAD

**Issue by swegner** [Azure/AutoRest#53]
I'm just getting started with Swagger and AutoRest, but it appears that your tool doesn't support comments in the Swagger YAML specification.

The swagger spec I'm using is [here](https://github.com/swegner/swagger-playground/blob/e581fc131be774539e66f9cb353fc127bdbe0be2/vso-git.yaml), which starts with some comments:

```
# this is an example of the Visual Studio Online Git AP
# as a demonstration of an API spec in YAML
swagger: '2.0'
```

This works in the [Swagger Editor](http://editor.swagger.io/), but fails when using AutoRest:

```
> .\AutoRest.0.9.7\tools\AutoRest.exe -Input .\vso-git.yaml -Namespace 'VSOGit.Client' -OutputDirectory 'Client' 
error: [FATAL] Error parsing swagger file. Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
Finished generating CSharp code for .\vso-git.yaml.
```

**Comment by matt-gibbs** [comment]
AutoRest has a Swagger modeler. If you are writing in YAML, you would need to use the editor option to save a Swagger client and use that as the input to AutoRest. We may add a YAML modeler in the future.

**Comment by swegner** [comment]
Bummer. It sounds like AutoRest only supports Swagger spec files that it generates. I had hoped it was a general tool for codegen clients based on any valid Swagger spec.

**Comment by stankovski** [comment]
Please also note that while not required by the Swagger specification, OperationIds are required for AutoRest.

**Comment by markcowl** [comment]
@swegner No, any valid swagger 2.0 should be supported- with the proviso that we do not support xml or formdata (yet).  As Denis noted, OperationId is *expressly* required according to the Swagger spec, but the json schema for swagger is a bit lax on this, so you can have a swagger spec that is valid according to the schema, but not logically valid :-).
