### ISSUE TITLE
C# Code generator with empty models

### ISSUE THREAD

**Issue by henning-krause** [Azure/autorest#546]
When you have an empty model, the C# generator creates an invalid model: It has two empty constructors.

This is because of a bug in the ModelTemplate.cshtml file (https://github.com/Azure/autorest/blob/master/AutoRest/Generators/CSharp/CSharp/Templates/ModelTemplate.cshtml).

The lines 37-47 need to be wrapped in an if-statement:

    if (!string.IsNullOrEmpty(Model.ConstructorParameters) {
       ...
    }

**Comment by brjohnstmsft** [comment]
This was fixed in the dev branch.
