### ISSUE TITLE
Where is the proxy generation code

### ISSUE THREAD

**Issue by cmshawns** [Azure/AutoRest#55]
I'm not finding the code that generates the client classes (i.e. that builds AutoRest.exe). Is this repository just the `Microsoft.Rest.ClientRuntime` library and samples, or am I missing something?

If this repository doesn't include the code for AutoRest.exe, then the name is quite misleading.

**Comment by devigned** [comment]
You are correct. The repo doesn't include the code for AutoRest.exe. Stay tuned. We're working towards that right now.

**Comment by centur** [comment]
Any updates on this issue ? The code behind AutoRest.exe is most interesting bit and it also may need some improvements

**Comment by devigned** [comment]
You can expect to see this code in the public repo in the next week or two.

**Comment by centur** [comment]
:+1:

**Comment by cmshawns** [comment]
:+1:

**Comment by centur** [comment]
Is there any update on this ?

**Comment by devigned** [comment]
It's in the dev branch. Feel free to dig into the code. It'll make its way into master shortly.
