### ISSUE TITLE
Node serialization issue - models is not defined

### ISSUE THREAD

**Issue by wbreza** [Azure/autorest#557]
I'm seeing an issue with the Node generated models.  I have a common "links" property in all my models which exposes hypermedia links to other actions available within the API.

When the models are created some of the nested types are not requiring the models.

```var models = require('./index');``` <-- is missing

Lower within the file there is a call to ```new models['{{TypeName}}'](...)``` which is failing.

See attached swagger.txt (It is a JSON formatted file) to repro.
[swagger.txt](https://github.com/Azure/autorest/files/61908/swagger.txt)

**Comment by stankovski** [comment]
Will be available in 0.14.0 release
