### ISSUE TITLE
Custom Headers in AuroRest CSharp

### ISSUE THREAD

**Issue by spaswin** [Azure/autorest#568]
Hi,

by using the blow command line we are generating the CSharp files. here we want to pass the custom header values from the client.  Custom Header parameter option is available  in the the file FIleNameAPI.cs. But  the Custom Header  parameter value is hard-coded as null in this file FIleNameAPIExtensions.cs. We want to pass the  CustomHeader parameter in FIleNameAPIExtensions.cs methods also.Kindly advice.

Command Line :
AutoRest -input "*.json" -CodeGenerator CSharp -Modeler Swagger -Namespace.Swagger.Test

Generated Files : 
1) *FIleNameAPI.cs
1) *FIleNameAPIExtensions.cs
1) *IFIleNameAPI.cs

**Comment by Nexusger** [comment]
@spaswin this sounds related to the issue #446 . Would you mind to check that issue out and confirm that? Also I hope we get your requested feature :-)

**Comment by stankovski** [comment]
Looks like a duplicate
