### ISSUE TITLE
Generate Client constructors are protected (csharp)

### ISSUE THREAD

**Issue by dotdot2** [Azure/autorest#570]
With the 0.13 version the client class has protected constructors. I remember earlier it was public.

Why the change? Should I just modify the protected to public?

**Comment by stankovski** [comment]
Protected ctors are not meant to be used by end users as they would put the client in the non-usable state (e.g. if no credentials are passed). We recommend that only public ctors be exposed.

**Comment by dotdot2** [comment]
I understand that. But in this case I did not see even a single public constructor. Is that expected?

Btw, can we keep this issue open before a clear resolution is reached?

**Comment by stankovski** [comment]
Can you please provide a sample swagger for repro?

**Comment by dotdot2** [comment]
[projectconfig.zip](https://github.com/Azure/autorest/files/70528/projectconfig.zip)

**Comment by maxkeller** [comment]
I've got the same issue. Commit was https://github.com/Azure/autorest/commit/85b8055087ebc3842acaefc8347df3c25f459617

Looking at the templates for it, it seems like this option just went untested ;) I can provide a proper constructor for this if you want me to - whether it be the empty constructor that I use now or one that takes Credentials as an argument. I might need some help setting up that build for testing it, though.

**Comment by stankovski** [comment]
Thanks for the sample. The issue should be fixed in #592.

**Comment by dotdot2** [comment]
Awesone, thanks
