### ISSUE TITLE
Code generation failed

### ISSUE THREAD

**Issue by jordanhoff** [Azure/autorest#580]
I receive the below error when trying to generate the client libraries against the following swagger file:

https://studioapi.bluebeam.com/PublicAPI/swagger/docs/v1 

Code generation failed.
AutoRest.exe -Input C:\Users\jhoff\Source\Workspaces\PrologBB\PrologBB\AutoRest\
Resources\v1.json -Namespace BBConnector -Modeler Swagger -CodeGenerator CSharp
error: [FATAL] Error parsing swagger file. Error reading string. Unexpected toke
n: StartObject. Path 'default', line 2, position 15.

Any help in diagnosing the issue is appreciated. I'm a third party however the source developers are on board if changes need to made to their swagger definition to support autorest. 

Thanks.

**Comment by object88** [comment]
I think the problem is in your swagger file.  You have `default` defined at the root of your definition schemas, ala this for Word2PdfOptionsDto:
````
{
  "default": {
    "StartPage": -1,
    [SNIP]
  },
  "type": "object",
  "properties": {
    "StartPage": {
      "format": "int32",
      "type": "integer"
    },
    [SNIP]
  }
}
````
If I'm reading the swagger spec correctly, the defaults should be assigned on the properties themselves:
````
{
  "type": "object",
  "properties": {
    "StartPage": {
      "format": "int32",
      "type": "integer",
      "default": -1
    },
    [SNIP]
  }
}
````
That said, I didn't edit your whole file to try to make it work, so best of luck...

**Comment by jordanhoff** [comment]
Thanks, much appreciated on where to look. I’ll follow up with the source developers and report back if this is indeed the issue.

**Comment by stankovski** [comment]
Thanks @object88 for your help!
