### ISSUE TITLE
CustomSettings behaviour changed between 0.12.0 and 0.13.0

### ISSUE THREAD

**Issue by ricot** [Azure/autorest#589]
I've created a custom generator: a slight modification of the default CSharp generator, enabling me to use already existing models instead of the created ones. This worked well with version 0.12.0, and in the AutoRest.json file for my generator I've used custom settings for a list of namespaces to include, etc.

When upgrading my tools to version 0.13.0, the settings validation in 'AutoRest.Core\Settings.cs' pick up the existing custom settings and report them as 'is not expected'. The validation changed between versions, and since the settings object is filled with my custom settings by the extensions loader, the subsequent validation fails, as the validation basically requires the 'CustomSettings' property to be empty. As far as I can understand, these changes make it impossible to use custom settings.

Is this the intended behaviour, or is there a "new" recommended way to deal with settings to extensions? (Or did I completely oversee something very obvious?)

**Comment by devigned** [comment]
> I've created a custom generator: a slight modification of the default CSharp generator, enabling me to use already existing models instead of the created ones.

*Awesome!!* It's fantastic to hear you went down the path of creating your own custom generator. We have hoped community members would create specialized generators or functionality to help them accomplish their own scenarios.

@stankovski, perhaps you could shed some light on this issue.

**Comment by stankovski** [comment]
The intention behind the CustomSettings has changed slightly. You are still allowed to pass CustomSettings to the AutoRest.exe, however your generator now needs to have a strongly-typed settings to accept them. They are still custom as far as AutoRest.exe is concerned, however they are no longer custom with regards to your generator. 

This can be done by decorating a property with a matching name with SettingsInfo attribute:
```cs
[SettingsInfo("Documentation.", false)]
[SettingsAlias("foo")]
public string FooBar { get; set; }
```
this will work with `autorest.exe -foo myval` and `autorest.exe -FooBar myval`

**Comment by stankovski** [comment]
Let us know if you are unblocked now so we can close the issue.

**Comment by ricot** [comment]
I already had strongly-typed settings in the generator, and decorating them with the above attributes makes no difference in this case. As I have a great deal of settings to pass to the generator, using the command line arguments is really not an option. Instead I use the 'settings' section of the 'AutoRest.json' file. Will this no longer be supported? (If settings from the json file _should_ be supported, I suspect that this is a bug. The rest of the code suggests that it should work.)

The settings themselves do make it into the generator, no problem there, but are also copied out into the settings object by the ```LoadTypeFromAssembly<CodeGenerator>``` method called from ```GetCodeGenerator. That is what makes the ```settings.Validate()``` call fail in 'AutoRest.cs'. The code in 'Settings.cs':

```csharp
if (CustomSettings != null)
{
    foreach (var unmatchedSetting in CustomSettings.Keys)
    {
        Logger.LogError(new ArgumentException(unmatchedSetting),
        Resources.ParameterIsNotValid, unmatchedSetting);
    }
}
```

I guess there is a mix-up here; there are no 'unmatched' settings on my end, just settings. (I would be happy to provide a fix if needed, when the image is clearer.)

**Comment by stankovski** [comment]
PR #595 fixes the issue
