### ISSUE TITLE
AutoRest should not include full version number in copyright notice

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#598]
Every time the AutoRest version changes and we regenerate code, every file changes because of the version number in the copyright header. Normally this wouldn't be a big deal, but we hand-modify several generated files to workaround issues in AutoRest, so this causes us a lot of merge pain.

It would be great if there were a way to turn off the version number in the copyright header.

**Comment by stankovski** [comment]
You can overwrite header by either passing it in the console or specifying it in swagger:
```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.13",
    "title": "Swagger Custom Paths",
    "x-ms-code-generation-settings": {
      "header": "Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT License. See License.txt in the project root for license information."
    }    
  },
...
```

**Comment by brjohnstmsft** [comment]
Thanks!

**Comment by stankovski** [comment]
@brjohnstmsft I changed my mind :)

**Comment by brjohnstmsft** [comment]
Less work for me. :)
