### ISSUE TITLE
Web Api Batch support

### ISSUE THREAD

**Issue by suddenelfilio** [Azure/autorest#600]
Hello 

any plans on supporting ASP.NET Multipart content Batch processing?

regards,

Filip

**Comment by stankovski** [comment]
@suddenelfilio please provide an example of the swagger spec

**Comment by suddenelfilio** [comment]
I don't think you should look for this in the swagger spec but rather provide the functionality in the generated client. It is in fact nothing more than aggregating multiple HttpRequestMessages (yes this is C#, but that is my main concern here) into 1 request as explained on the microsoft ASP.NET website: https://aspnetwebstack.codeplex.com/wikipage?title=Web+API+Request+Batching

Or this too specific for this project as it is too tight to the technology stack?

**Comment by sharadagarwal** [comment]
I also would like to see multipart batch support in Autorest. It's not clear to me yet how my Swagger spec would be different, other than perhaps having another API that receives batched requests - the Autorest client would need some way to stuff multiple API calls into the single batch API call using multipart.

**Comment by stankovski** [comment]
@suddenelfilio we do have support for [multipart form data](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object), but I'm not sure if it will work with ASP.NET batching. If you want to propose a design for generated C# clients (as well as a way to determine it from swagger) please add it to the thread and we will consider adding it.

**Comment by sharadagarwal** [comment]
What I'd need is a way to get at the system.net.http.httprequestmessage that is being constructed when I make an API call. For every API call that AutoRest generates a method for, perhaps it can generate another method where it doesn't actually make the API call but rather returns an HttpRequestMessage that is properly filled out. Then I would collect a list of HttpRequestMessages and issue those as a batch request. On receiving a batch response, then I'd need to properly deserialize them, so some support for that would also be useful.

**Comment by sharadagarwal** [comment]
I've issued a pull request for this : #914

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-1.0 planning cycle.

It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 1.0. 🏇 🏇 🏇

We'll make sure we pick this back up at that point. 🎉
