### ISSUE TITLE
Generated C# code should be decorated with GeneratedCodeAttribute attribute

### ISSUE THREAD

**Issue by RemcoHulshoff** [Azure/autorest#609]
in order to prevent static code analysis warnings

**Comment by stankovski** [comment]
Would recommend adding this attribute instead of `// Code generated by Microsoft` header and allow command line switch to enable-disable it.

**Comment by turowicz** [comment]
:+1: this is something that would really help

**Comment by RemcoHulshoff** [comment]
I'm looking into creating a pull request for this but I'm having a hard time getting the environment to work. 

I followed the instructions and it's building but then it appears to fail on 'test:xunit:dnx' with a 'System.InvalidOperationException: The current runtime target framework is not compatible with 'Azure.CSharp.Tests'.' 

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-rc1-16231

I have several flavors of 1.0.0-rc (final and update1) installed and the update1 clr x86 win is both default and active.

A little help would be appreciated :-)

**Comment by tbombach** [comment]
@RemcoHulshoff The issue is that the tests should be running with the x64 version of DNX. You can run `dnvm upgrade -r coreclr` to install and make the correct version active. I'll add it to the documentation so that people don't run into this problem.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
