### ISSUE TITLE
Node JS Generation issue with OData routes

### ISSUE THREAD

**Issue by wbreza** [Azure/autorest#614]
I'm seeing an issue with the generated Node JS code specially when it contains OData routes.  I've attached the following Swagger JSON.

1. OData Paths that contain single quotes are not being escaped
2. OData Context params with '@' is also causing compile issues

[swagger.json](https://github.com/Azure/autorest/files/90944/swagger.txt)

**Comment by amarzavery** [comment]
Fixes single quotes in the url https://github.com/Azure/autorest/pull/620
