### ISSUE TITLE
Add setting for C# gen to specify constructor protection level

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#618]
If set constructors should be generated as internal

**Comment by brjohnstmsft** [comment]
What's the scenario for this?

**Comment by stankovski** [comment]
Allow to generate clients with "internal" ctor so that the client can not be initialized directly. Customization layer would be used to wrap the client and customize it as needed. This is necessary for scenarios where clients need to be forcefully pre-configured (e.g. custom delegating halndlers, custom retry policy, etc.).

**Comment by brjohnstmsft** [comment]
Cool, that's something we're interested in for the Search SDK as well. But why stop at the constructor? Why not make the classes themselves internal?

**Comment by stankovski** [comment]
@brjohnstmsft keeping class public allows developers to re-use the entire client and just hide the ctor. For example you can have a custom ctor that takes in an account name and appends it to base Uri as is the case in DataLake
