### ISSUE TITLE
Generated properties that are prefixed with an underscore are named "Lowline" or "lowline"

### ISSUE THREAD

**Issue by HEDIDIN** [Azure/autorest#638]
I used the Console app to generate code for a Swagger.  I tried the Add REST API Client in VS 2015 and it failed there.

It succeeded in the Console, but parameters that were prefixed with an underscore, are prefixed with "LowLine" a shown below.

  [JsonProperty(PropertyName = "_ts")]
   public string LowLinets { get; set; }

The Swagger I used is:
[HEDIDIN-DocumentDBRestAPI-1.0.7-swagger.zip](https://github.com/Azure/autorest/files/101195/HEDIDIN-DocumentDBRestAPI-1.0.7-swagger.zip)

The Model Class that shows the issue is attached
[Udf.zip](https://github.com/Azure/autorest/files/101197/Udf.zip)

**Comment by stankovski** [comment]
This part of the renaming logic for all models. Need to update it for model properties in the case there is no conflict.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
