### ISSUE TITLE
Generate client side JavaScript usable in browser

### ISSUE THREAD

**Issue by henning-krause** [Azure/autorest#639]
Are there any plans to implement a generator which produces browser-usable javascript?

Based on a fetch client or similar.

**Comment by amarzavery** [comment]
@henning-krause - Currently we generate Node.js clients. We are investigating and prototyping on how will this work end to end : SwaggerSpec --> Node.js client using AutoRest  --> Client side javascript using [Browserify](http://browserify.org/) or [webpack](https://github.com/webpack/webpack). You can try it out as well and let us know  your thoughts.

**Comment by henning-krause** [comment]
I tried using it without browserify and it failed with an error stating that "tls" cannot be used in the browser.

**Comment by henning-krause** [comment]
Hmm.. just calling browserrify with my client libary and using the resulting bundle did not work in my case. Do you have some kind of example on how to do this?

**Comment by amarzavery** [comment]
I had created a sample for the swagger petstore and it worked. I made 2 modifications
1. I had to modify the swagger file a bit as we only support csv collectionFormat and not multi. 
2. I had to make a minor modification in the request library for it to support http protocol

After that the generated bundle.js file worked. I will zip everything and post it here in 15 minutes.

**Comment by amarzavery** [comment]
@henning-krause - You can download this zip file [petstore.zip](https://github.com/Azure/autorest/files/101410/petstore.zip). Follow the instructions in README.txt and let me know if you find any issues.

**Comment by henning-krause** [comment]
Excellent. I'll have a look into this.

**Comment by henning-krause** [comment]
@amarzavery - Okay, tried your example and it indeed works. However, I have these observations:

1. Just adding your very small sample adds an overhead of nearly 2 MB for the bundled client. This is unminified and not gzipped, but it's a significant overhead nonetheless. A client building on top of fetch would surely by smaller, because no additional http client (includinf TLS and ASN.1 library) would be needed.

2. You are not really interacting with the PetStore client via javascript in a browser. You are running a node application in the browser and outputting the result. We have a systemjs based application which needs to communicate with our REST-based service. I have no idea how to bridge the gap between node and plain javavscript. But then, my javascript knowledge is thin, at best. Do you have any idea on how to accomplish this?

Do you think it would be difficult to remove the JSON (de-)serialization code from the ms-rest package and use it outside of a node environment? In this case I could call my webservice via fetch and parse the response via the msrest package.

**Comment by amarzavery** [comment]
The primary use case for Autorest was to generate Node.js code. We havent really focused on client side javascript code generation. We are doing an initial investigation of how browserify/webpack could help us achieve this. It should not be difficult to rip out the serialization/deserialization logic out of ms-rest. It is independent of the request library. As an example - [The serialization tests](https://github.com/Azure/autorest/blob/master/ClientRuntimes/NodeJS/ms-rest/test/serializationTests.js) do not make any request calls. So if you can replace the request library [pipeline] (https://github.com/Azure/autorest/blob/master/ClientRuntimes/NodeJS/ms-rest/lib/serviceClient.js#L57) with fetch you should be pretty much all set. 

Every operation on the client calls the pipeline to make the request. Take a look at this [example](https://github.com/Azure/autorest/blob/master/AutoRest/Generators/NodeJS/NodeJS.Tests/Expected/AcceptanceTests/BodyComplex/operations/basicOperations.js#L86).

**Comment by amarzavery** [comment]
Take a look at this closed [PR](https://github.com/Azure/autorest/pull/421) where we were experimenting to replace node request library with superagent. 
We did not switch to superagent because we generate code for our node sdk which is later consumed by a CLI. With strict deadlines for releases we were not able to test all our scenarios.  

However, this could very well solve your problem.

**Comment by henning-krause** [comment]
Thanks @amarzavery , I'll have a look into that.

**Comment by amarzavery** [comment]
@henning-krause - Did you replace the request library with browserify or xhr ? Just curious to know the outcome and your take on it.

**Comment by henning-krause** [comment]
@amarzavery , unfortunately, I haven't had the time to do that. But it's high on my list....
