### ISSUE TITLE
Microsoft.Rest.ClientRuntime 2.0.0 can not be installed in Xamarin PCL Project

### ISSUE THREAD

**Issue by brentonw** [Azure/autorest#650]
Attempting to add Microsoft.Rest.ClientRuntime v2.0.0 via Nuget to a standard Xamarin PCL project results in the following error:

Could not install package 'Microsoft.Rest.ClientRuntime 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework.

The targets for the project as as follows:

![default targets](https://cloud.githubusercontent.com/assets/1224381/12570539/48076766-c38d-11e5-941a-e311e3a3a3ed.png)

Is there a reason why AutoRest doesn't support generating code that is compatible with Xamarin?

**Comment by stankovski** [comment]
We do support Profile 111 which includes Xamarin support (http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/). I believe you may need to remove Windows Phone Silverlight 8 to get that profile.

**Comment by tschennie** [comment]
I get the same error message with following targets for profile 111:
![portable](https://user-images.githubusercontent.com/2771121/31850744-300c832a-b658-11e7-8b1d-f9a6470b6bc7.PNG)
What can I do?

**Comment by saadhaffar025** [comment]
It's not working for me. While Add a REST API client using swagger specifications, I got the same error telling me that I can't install package Microsoft.Rest.ClientRuntime 2.3.2 . Profile target was 78.
