### ISSUE TITLE
Code Gen broken for NodeJS when using internalConstructors

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#652]
You get the following error if your specs have the "internalConstructors" in it when generating code for Node.js:

C:\SRC\AzureSDK\azure-sdk-for-node\lib\services\dataLake.Analytics>C:\SRC\AzureSDK\azure-sdk-for-node\Tools\..\packages\autorest.0.14.0-Nightly20160125\tools\AutoRest.exe -Modeler Swagger -CodeGenerator Azure.NodeJS -Input "https://raw.githubusercontent.com/begoldsm/azure-rest-api-specs/master/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json" -outputDirectory C:\SRC\AzureSDK\azure-sdk-for-node\lib\services\dataLake.Analytics\lib\account -Header MICROSOFT_MIT
**Code generation failed.**
AutoRest.exe -Modeler Swagger -CodeGenerator Azure.NodeJS -Input https://raw.githubusercontent.com/begoldsm/azure-rest-api-specs/master/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json -outputDirectory C:\SRC\AzureSDK\azure-sdk-for-node\lib\services\dataLake.Analytics\lib\account -Header MICROSOFT_MIT
error: Parameter 'internalConstructors' is not expected.

**Comment by amarzavery** [comment]
This PR https://github.com/Azure/autorest/pull/677 fixes it.
