### ISSUE TITLE
Code generation tool should honor accept headers specified 'paths.{path}.{verb}.produces' swagger json file

### ISSUE THREAD

**Issue by naveedaz** [Azure/autorest#656]
Currently no accept headers are sent as part of the request. For some of our APIs there is a proxy in the middle whose default response is XML instead of JSON. AutoRest clients can only parse json. Each time the client is generated we have to manually add the code to send accept headers.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by xplicit** [comment]
Is there a chance that this issue will be fixed?
