### ISSUE TITLE
x-ms-external types should not require for properties to be declared

### ISSUE THREAD

**Issue by iouri-s** [Azure/autorest#660]
Repro:
In a JSON spec declare a type definition:
```json
    "CloudError": {
      "x-ms-external": true
    }
```
Declare a response using it:
```json
          "default": { "schema": { "$ref": "#/definitions/CloudError" } }
```
Result - generated code deserializes errors to System.Object, instead of CloudError

**Comment by brjohnstmsft** [comment]
Why should `x-ms-external` not allow properties to be declared? That would break an important scenario: When you have modeled a type in Swagger but discover that AutoRest cannot yet generate optimal code for it. In this case `x-ms-external` is a convenient way of turning off codegen for a single type without completely removing it from the Swagger spec.

**Comment by iouri-s** [comment]
You are correct, x-ms-external should be allowed.  Thanks for the correction!

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
