### ISSUE TITLE
Streaming non file content using C# client generator

### ISSUE THREAD

**Issue by henning-krause** [Azure/autorest#673]
I have a Web API controller which is used to upload images. To avoid Base64 conversion I would like to upload the data using the new Stream feature of Autorest. 

My action definition now looks liks this:
```javascript
"/api/Images/new": {
			"post": {
				"tags": [ "Image" ],
				"operationId": "Image_Add",
				"consumes": [ "application/octet-stream" ],
				"produces": [ "application/json", "text/json" ],
				"parameters": [
					{
						"name": "File",
						"required": true,
						"allowMultiple": false,
						"type": "object",
						"format": "file",
						"in": "formdata"
					}
				],
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": { "$ref": "#/definitions/ImageInfo" }
					}
				},
				"deprecated": false
			}
		}
```

AutoRest correctly builds the stream request with this. However, itwill only add a Content-Disposition header with a "filename" value when the input stream is a FileStream.

Would it be possible to change the signature of the generated method from

```cs
Task<HttpOperationResponse<ImageInfo>> AddWithHttpMessagesAsync(System.IO.Stream file, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

to 

```cs
Task<HttpOperationResponse<ImageInfo>> AddWithHttpMessagesAsync(System.IO.Stream file, string fileName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```
and use the second parameter as the filename? It could even be optional. Naming convention would be <Name of the stream parameter> + "Name".

**Comment by smax48** [comment]
Actually there is a problem with the current version of C# generator. Generated code tries to cast the input Stream parameter to the FileStream and then creates a ContentDisposition header.

The problem is that the FileStream class is NOT available for PCL assemblies. So the generated code cannot be compiled for .NET Portable profiles :(. We have Android / iOS clients and this issue is quite important for us. Now I have to suppress the generated code manually with conditional compilation directives for PCL builds, but this is not convenient.

**Comment by centur** [comment]
Well we have similar issue for UWP application, so I subscribe to this either. I hope not having a working code on Microsoft's UWP  - most pushed forward Windows 10 apps platform makes this issue progress a bit faster.

**Comment by devigned** [comment]
This is definitely on the backlog. With that said, we are open to pull requests if someone from the community would like to contribute this functionality.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
