### ISSUE TITLE
Generated C# SDK cannot update optional properties to null

### ISSUE THREAD

**Issue by kuangweizhang** [Azure/autorest#681]
In the generated SDK, update method takes a *Parameters object as the way to update the entity.
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Cdn/Microsoft.Azure.Management.Cdn/Generated/OriginsOperations.cs#L668
Let's use Origin Parameter as an example:
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Cdn/Microsoft.Azure.Management.Cdn/Generated/Models/OriginParameters.cs
HttpPort and HttpsPort is null-able as specified in swagger so it is optional in the constructor.

Case 1: I want to update host name of the origin. I would do 
var parameter = new OriginParameter("hostname.com")
In this case, I didn't specify the httpPort and httpsPort because I thought they are optional and I don't want to update them so I just specified the host name in the constructor. In this case, the patch payload will be:

``` json
{
  "properties": {
    "hostName": "hostname.com"
  }
}
```

Case 2: I want to update host name, httpPort and httpsPort and I want to update value of both port to null. I would do:
var parameters = OriginParameter("hostname.com", null, null);
In this case, I do want to update httpPort and httpsPort because I want them to be null. However, in this case, the patch payload is still:

``` json
{
  "properties": {
    "hostName": "hostname.com"
  }
}
```

The user is never able to update port to null.

I understand it is hard to achieve the goal with optional parameter design. However, in this case, the user of the SDK stuck in one of the acceptable states of the resource state machine.

**Comment by stankovski** [comment]
This is somewhat related: https://github.com/OAI/OpenAPI-Specification/issues/229

For now there doesn't seem to be a good way to indicate that the property should be sent as a `null` via the spec

**Comment by amarzavery** [comment]
cant we explicitly set the default value of the optional property to "null". So if the property is not specified then it is set to null.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
