### ISSUE TITLE
Add "x-ms-uuid" extension that would generate unique values

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#688]
This extension can be used together with "constant" properties to auto-generate unique values

**Comment by amarzavery** [comment]
https://github.com/Azure/autorest/issues/690

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
