### ISSUE TITLE
Windows App Certification Kit Fails

### ISSUE THREAD

**Issue by iwbo** [Azure/autorest#714]
Hi

We are unable to publish our apps that have code generated with Autorest in them to Windows Store.
The problem isn't with Autorest but with one of the dependencies: **Microsoft.Rest.ClientRuntime.dll**

I have already contacted the package owners form Nuget: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/
But I still don't have an response from them. The "Project Site" link on the Nuget page is linking back to this (Autorest) project on Github. So I asume it's okey for me to post the issue here.

**Issue:**
After running our Windows 10 app in Windows App Certification Kit, the test fails and says: 

> Debug configuration test
> 
> FAILED
> 
> Debug configuration
> 
> •Error Found: The debug configuration test detected the following errors:
        ◦**The binary Microsoft.Rest.ClientRuntime.dll is built in debug mode.**
> 
> •Impact if not fixed:  Windows Store doesn’t allow a debug version of an app. 
> 
> •How to fix:  Please make sure the app isn’t linking to any debug versions of a framework and it is built with release configuration with optimization enabled. If this is a managed app please make sure you have installed the correct version of .NET framework. 

This happens with both versions 2.0.0 and 2.0.1

If it's the right place to ask, then can somebody please make sure that the **Microsoft.Rest.ClientRuntime DLL** is built with **realease** configuration and with **optimization** enabled.    

Would really appreciate the help, as we have two apps waiting behind this issue!

**Comment by stankovski** [comment]
Fixed

**Comment by iwbo** [comment]
Hi

When should we expect a new public version of the nuget package, where this fix is applied?

**Comment by Toolenaar** [comment]
@iwbo I am running into the same problem with Microsoft.Rest.ClientRuntime.dll uploading to the windows store. Did you manage to fix this? And if so how ?

**Comment by iwbo** [comment]
@Toolenaar Yes, the issue was resolved. I think I just updated to the latest packages after they where available.

**Comment by princetomy92** [comment]
how to solve the issue?
