### ISSUE TITLE
mzrestazure on PyPi missing readme.rst

### ISSUE THREAD

**Issue by phyber** [Azure/autorest#718]
As the subject says, the release of `msrestazure` on PyPi is missing the `readme.rst` file which is used to generate the `long_description` in `setup.py`. This means that installations of `msrestazure` from `pip` fail.
This also affects other software that ends up pulling in `msrestazure` long the way.

**Comment by stankovski** [comment]
@xingwu1 please take a look at this

**Comment by lmazuel** [comment]
Got it, will do a PR soon

**Comment by lmazuel** [comment]
Associated release of msrest/msrestazure
https://github.com/Azure/autorest/pull/761
