### ISSUE TITLE
Support x-ms-parameterized-host in ruby.

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#722]
x-ms-parameterized-host support is currently enabled for C#, Nodejs and Java. There is a gap for python and ruby. This issue tracks the integration for ruby. Currently ruby support is in active development, so this should be tracked as part of that overall work.

**Comment by vishrutshah** [comment]
Support for x-ms-parameterized-host in ruby has been checked-in. Issue should be closed now.

**Comment by amarzavery** [comment]
Wohooo... As you say Sir @vishrutshah !!
