### ISSUE TITLE
ms-azure-rest is broken in Webpack due to json-schema being broken in Webpack

### ISSUE THREAD

**Issue by dukedougal** [Azure/autorest#734]
https://github.com/kriszyp/json-schema/issues/59

**Comment by amarzavery** [comment]
@dukedougal - "ms-rest" does not use "json-schema" directly. request library has a dependency on "json-schema" via "http-signature".
so the dependency chain goes like this:
```
ms-rest -> request -> http-signature -> jsprim ->json-schema
where -> = "depends on"
```
I installed the latest version of request: "2.69.0" locally.
Webpack needs to fix this issue. By the download numbers it seems json-schema is a commonly used module.
ms-rest depends on the request library for making requests. There is nothing much that I can do in this.
I have removed the depenedency on "tough-cookie" as it was not required.

**Comment by dukedougal** [comment]
The outcome is still that Azure is broken with Webpack.

Azure say its not their problem, Webpack seem to think everyone else needs to make their packages compatible with it instead of the other way around, and the guy behind the json-schema package appears to have no interest in making his package to work with webpack.

It's a mexican standoff in which no-one wants to do what it takes to make their software work with each other.

https://github.com/webpack/webpack/issues/2101
https://github.com/kriszyp/json-schema/issues/59

What can be done?
