### ISSUE TITLE
Generate report for test coverage

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#736]
- [ ] Add method to test server to dump report to disk (with file name matching code gen language)
- [ ] Add a document that contains mapping between high level feature and coverage tests along with human readable description of each feature
- [ ] Add gulp task that generates a markup file based on the above with a table where rows correspond to features, columns to languages, and cells to coverage (Covered, Not covered, Partial)

**Comment by tbombach** [comment]
We also need to have a standardized way of excluding particular languages from code coverage for a given test. This is needed for tests that don't apply to certain languages and for scenarios that have not yet been implemented in all languages.

The proposed way of doing this is to have a mask for each language that would be applied in the report route on the test server, while the report that gets dumped on disk contains the raw coverage. That way we can still generate a markup file with information on which scenarios still need to be covered by each language.
