### ISSUE TITLE
Java: hide DateTimeRfc1123 or any internal type from end user

### ISSUE THREAD

**Issue by xingwu1** [Azure/autorest#742]
When we specify the property with format "date-time-rfc1123" in the swagger spec. The Java codegen create the class with the property type as DateTimeRfc1123. However, we should hide the type from end user by change the setter/getter type to standard Joda datetime type.

**Comment by jianghaolu** [comment]
The PR above gets all the `DateTimeRfc1123` typed objects correct, but lists or maps of that were not supported. They are now supported in [Parameter model](https://github.com/Azure/autorest/blob/master/AutoRest/Generators/Java/Java/TypeModels/ParameterModel.cs#L105) and [Response model](https://github.com/Azure/autorest/blob/master/AutoRest/Generators/Java/Java/TypeModels/ResponseModel.cs#L242).
