### ISSUE TITLE
Java: Azure paging list method is not using Iterable for sync iteration, it uses List

### ISSUE THREAD

**Issue by xingwu1** [Azure/autorest#745]
We didn't implement Lazy listNext when use List as return type since it is very difficult to implement size() and index function. However, we should just return Iterable type instead of List type, and implement the Lazy listNext inside the next() and hasNext() function of Iterable type. So we can prevent copy the whole result set into memory.

**Comment by jianghaolu** [comment]
This is supported in https://github.com/Azure/autorest/pull/851.
