### ISSUE TITLE
CSharp: HttpOperationException response content is null

### ISSUE THREAD

**Issue by jhancock93** [Azure/autorest#746]
When handling an unexpected status code, the current CSharp generator generators an HttpOperationException with null response content. If there was an HttpError in the response content, the error is lost to the client. In addition, because AutoRest currently handles error response codes like 400 as a success, this provides no good way to return an error.

The current code looks like:
            **string _responseContent = null;**
            if ((int)_statusCode != 200)
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                ex.Request = new HttpRequestMessageWrapper(_httpRequest, _requestContent);
                ex.Response = new HttpResponseMessageWrapper(_httpResponse, **_responseContent**);
                if (_shouldTrace)
                {
                    ServiceClientTracing.Error(_invocationId, ex);
                }
                _httpRequest.Dispose();
                if (_httpResponse != null)
                {
                    _httpResponse.Dispose();
                }
                throw ex;
            }

As can be seen, the responseContent is null. The responseContent string is only grabbed from the message in case of a success.

**Comment by stankovski** [comment]
@jhancock93 this should only happen if the swagger spec does not indicate that the operation returns a model (e.g. DELETE operation with void response). If you have a model in "default" response and your operation has "produces" with JSON you should get details in the error. Alternatively if you have any response coming back from the operation (e.i. we understand that there is a payload) the code gen will read it and add it to the exception even if there is no error model. This is similar to #647.

**Comment by jhancock93** [comment]
This is a change from AutoRest v0.13 when the response was contained in the HttpOperationException regardless. This is a pretty simple code fix in the method template to address the issue and I will generate a pull request shortly. The suggestion in #647 seems like a workaround instead of a fix.

**Comment by stankovski** [comment]
@jhancock93 thanks for the PR. I left a comment regarding your approach.

**Comment by jhancock93** [comment]
Issue has been addressed with merged PR.
