### ISSUE TITLE
CSharp: auto-generated constructors seem brittle

### ISSUE THREAD

**Issue by jhancock93** [Azure/autorest#747]
The current CSharp generator can create model class constructors with a very large number of default parameters (as many are in the model). Clients who use these constructors are more likely to break if model properties get rearranged. Although it is typically a best practice to specifically control the order of properties in a data contract, sometimes this is not possible. I think it would be much better to NOT generate these constructors and encourage the user to use object initializers with the default constructor instead. Because object initializers force a name for every property, they are less brittle.

If it is necessary to keep the constructor for backwards compatibility, I would recommend adding an option for AutoRest and default it to not create the constructors.

**Comment by brodyberg** [comment]
I avoid object initializer syntax makes it more difficult to implement immutable classes.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
