### ISSUE TITLE
All Languages: provide package name and package version options

### ISSUE THREAD

**Issue by devigned** [Azure/autorest#751]
AutoRest should be able to understand how things are packaged. By including package name and package version, we can start down the path of creating packages of code, rather than simply source. This would reduce the time to use for most language significantly and lessen the need to understand package dependencies.

For example: if I generate out a ruby client, I'd like that to include the version.rb file and perhaps, a gemspec, so that I can quickly publish out a working package for my HTTP API. At a minimum, it could scaffold the skeleton of the project.

**Comment by NiklasGustafsson** [comment]
Could we generalize this request to also include generating project/build files so that the output can be immediately built after Autorest is run?

**Comment by amarzavery** [comment]
How about having a new extension named 
```
"x-ms-package-info" : { 
  name: "azure-arm-compute",
  version: "1.2.0",
}
```
Or having a setting on the generator: --packageName and --packagVersion which specifies the values respectively for the generated package.json/ nuget package/ruby gem/java maven file etc.

**Comment by devigned** [comment]
@NiklasGustafsson that was precisely the direction this issue.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
