### ISSUE TITLE
Generate Handlers According to Swagger.json input

### ISSUE THREAD

**Issue by OzBob** [Azure/autorest#768]
Labels: Enhancement, HelpWanted

I've just written a bunch of oAuth and Header Token Handlers. Like those from 
[AspNet WebApi Todo Sample](https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/Todo/Account.Client/OAuth2BearerTokenHandler.cs
)
As they are specified in the swagger document produced (in my case via Swashbuckle) from the Api Controllers.   What is the community's reaction to codegen'ing the DelegatingHandlers(?) and plumbing them into the Client Generation in a ClientFactory.

Also, the Todo sample uses HttpAuthenticationHandler. Is this a better pattern that DelegationHandlers? Is calling order guaranteed when base.SendAsync is called?

**Comment by stankovski** [comment]
Can you please clarify how this is different from https://github.com/Azure/autorest/blob/master/Documentation/clients-auth.md

**Comment by OzBob** [comment]
Yes, that's the one.
My suggestion is just one extra step, of creating a ClientFactory class. https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/Todo/Todo.WindowsStore/ClientFactory.cs
that implements the API's Credentials contracts, creating varying clients per combination of swagger 'security' requirements per path, from Credentials from the 'securityDefinitions' section.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
