### ISSUE TITLE
Streaming large streams results in an OutOfMemoryException (in C#, Python, Java)

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#769]
The generated code which issues a request currently does this:
`_httpResponse = await this.Client.HttpClient.SendAsync(_httpRequest, cancellationToken).ConfigureAwait(false);`

The problem with doing this is that HttpClient's default behavior is to read the entire response into memory, which causes an out of memory exception if the response stream is large enough (for example in the case of large file downloads).

In methods which return `Stream`, this should be changed to be: `_httpResponse = await this.Client.HttpClient.SendAsync(_httpRequest, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);`

**Comment by amarzavery** [comment]
@matthchr - This is what we do in node.js as well.
```
var result = response; // response is the entire stream
return callback(null, result, httpRequest, response);
```
The user can then decide to buffer it or write it to a file.
```javascript
readStreamToBuffer(result, function (err, buff) {
  if (!err) {
   //process buff
  }
});

var readStreamToBuffer = function (strm, callback) {
    var bufs = [];
    strm.on('data', function (d) {
        bufs.push(d);
    });
    strm.on('end', function () {
        callback(null, Buffer.concat(bufs));
    });
};
```

Some users complained that they don't want to do the above step and would rather want this to be done by the generated code.

If we have an optional parameter called BufferSteamResponse set to true, then we can do it for the end user. The default value of this optional parameter is false and we return the stream back.

In this way, if the user wants the generated code to buffer it in mem, then he has the option to do it and will be very well aware of what he is doing. The parameter documentation on the method can have a warning message "This should be done for small streams only. Large streams could result in out of memory exception"

**Comment by matthchr** [comment]
Interesting:
In C#, even if you don't read the whole stream into memory (i.e. if you apply the fix I suggested above) the client experience is not really impacted.  They still get a `Stream` object back (like they do now), it's just that the `Stream` object they get back happens to be backed by a `NetworkStream` rather than by a `MemoryStream` -- so they're limited in what they can/can't do with the stream (i.e. they can't call `.Seek`

**Comment by matthchr** [comment]
@annatisch I authored a test for this in Python and while the test passes, the Python process seems to gobble up a ton of memory -- I've skipped executing this test for now but we should fix Python up to resolve this bug

**Comment by matthchr** [comment]
@jianghaolu This impacts Java too.

**Comment by jianghaolu** [comment]
@matthchr Is this already a test in AutoRest? If so I'll give it a try too.

We should check the upload scenario as well - however as far as it seems the Java HTTP client doesn't like working with Express server with files > 512k; using other servers works fine. Not sure about the behaviors on C# or Node.

**Comment by matthchr** [comment]
@jianghaolu I haven't tried the upload scenario, but I added tests for the download scenario [here](https://github.com/Azure/autorest/pull/869).  Currently skipping the Python/Java tests since both fail.

**Comment by annatisch** [comment]
@jianghaolu  This can be closed for Python now

**Comment by jianghaolu** [comment]
Closing.
