### ISSUE TITLE
long-running-operation without a response body doesn't compile

### ISSUE THREAD

**Issue by emgerner-msft** [Azure/autorest#776]
Long running operations (like below) result in output code that doesn't compile. 

        "responses": {
          "202": {
            "description": ""
          }
        },
        "x-ms-long-running-operation": true

The output error is:

The type arguments for method 'AzureClientExtensions.GetPutOrPatchOperationResultAsync<TBody>(IAzureClient, AzureOperationResponse<TBody>, Dictionary<string, List<string>>, CancellationToken)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by parvezah** [comment]
i am facing a similar issue with my spec. is there any work around for this?

**Comment by amarzavery** [comment]
It is in the backlog. We will take this up soon.

**Comment by devigned** [comment]
@parvezah, please open a pull request if it is blocking you. We're happy to review it :).

**Comment by parvezah** [comment]
[https://github.com/Azure/autorest/pull/917](url) Raised a PR. Can you have a look.
