### ISSUE TITLE
Change constant behavior to not initialize parent of child is a constant

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#782]
Currently in the below example if `zoo` is a constant `bar` will be initialized in `foo` object. It should not be. `bar` should only be initialized if `bar` is required.

``` 
   foo
       bar
          zoo
```

**Comment by amarzavery** [comment]
I am fixing this right now in node.js. 
@jianghaolu, @annatisch , @devigned - Please make sure that this issue does not occur in Java, Python and Ruby.
