### ISSUE TITLE
Add concept of "flighting" to code generators

### ISSUE THREAD

**Issue by stankovski** [Azure/autorest#806]
Each code generator should expose metadata about features is support.
E.g.
```cs
public bool IsFeatureSupported(string feature) {
   switch (feature) {
      case Features.Constants: return true;
      case Features.ParameterFlattening: return false;
      default:
        return false;
   }
}
```

Whenever a feature is added to the core, each language code generator should be updated with a feature flag indicating whether the feature is supported or not.

This information should be used by Extensions.NormalizeClientModel to apply a given extension to a code generator. This information can also be exposed to the modeler if needed and be used for reporting.

This will enable features to be implemented gradually across languages and will make it obvious for each language team what features they are missing.

**Comment by amarzavery** [comment]
:+1:

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
