### ISSUE TITLE
CompositeType parameters incorrectly being marked as constants

### ISSUE THREAD

**Issue by annatisch** [Azure/autorest#819]
Hi - I'm seeing some strange behavior where non-constant complex type parameters are being incorrectly described as constant.

As example can be seen when generating this swagger spec:
[https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json](url)
In particular, the model NetworkInterfaceIPConfiguration has a complex parameter Subnet - subnet is being classified as "constant" when I can't see a reason that it should be (i.e. it's not a string enum of one value, nor are all of it's parameters constant).

I stepped through the code, and I see that things seem to be going wrong in AutoRest.Modeler.Swagger.ObjectBuilder - line 169. It seems that in this particular scenario, compositeType.ComposedProperties is empty, so the if statement passes and the model is marked as constant.
I can fix this particular issue by simply replacing the code with:
```
var compositeType = parameter.Type as CompositeType;
if (compositeType != null and compositeType.ComposedProperties.Any())
{
    if (compositeType.ComposedProperties.All(p => c.IsConstant))
    {
        parameter.DefaultValue = "{}";
        parameter.IsConstant = true;
    }
}

```
However I don't know what other implications this change may have, and the bigger problem seems to be why ComposedProperties was empty in the first place (which I didn't investigate)....
Anyways - I hope this helps! We have some customers who are affected by this issue due to how we handle constants in the Python generator. If this is determined to not be a bug, let me know and I can change the Python implementation to work around this scenario.

Thanks!

**Comment by lmazuel** [comment]
For the record, this created this issue in the Python SDK:
https://github.com/Azure/azure-sdk-for-python/pull/536

**Comment by annatisch** [comment]
We need a fix for this issue pretty soon @devigned  and @yugangw-msft .
Would it help if I submitted the workaround above as a PR? I don't know if it's the correct approach or what impact it may have on the other languages, so your thoughts would be appreciated :)

**Comment by amarzavery** [comment]
@annatisch - That is a correct fix. I have verified this fix with Azure.NodeJS on the network spec as well. After applying your fix the generated code looked better. CompositeTypes were not being marked as constant where they shouldn't be.
Just one comment: 
if (compositeType != null **&&** compositeType.ComposedProperties.Any())

Please send a PR, and possibly a test in the modeler over [here](https://github.com/Azure/autorest/blob/master/AutoRest/Modelers/Swagger.Tests/SwaggerModelerTests.cs#L450) to make sure that this does not regress.
You can create a new swagger doc with few model classes from the network swagger spec that reproduce this problem and then assert that subnet is not a constant property in NetworkInterfaceIPConfiguration class.

**Comment by annatisch** [comment]
Aww but the Python 'and' is so much more elegant than the C# '&&'... ;P
Thanks - I'll try and get a PR out tomorrow.

**Comment by amarzavery** [comment]
I agree. I used to write in Perl and loved that elegance. However this is still better than Powers**H**ell -gt, -lt, -eq :)
