### ISSUE TITLE
Validator.validate() goes into infinite loop trying validate TextNode from Load Balancer ARM template

### ISSUE THREAD

**Issue by scotmoor** [Azure/autorest#820]
Using com.microsoft.rest:client-runtime:1.0.0-beta1

We are trying to deploy the attached template via the createOrUpdate method of the ResourceManagementClient in the Azure SDK for Java 1.0.0 beta 1 

When the Validator.validate() starts to parse the "template", it is encountering a TextNode with a value of """", which it does not know how to handle and it eventually will call Valdator.validate() passing in the TextNode. These leads to an infinite loop, which is never returns from. 

I don't know why it's seeing the value of the TextNode as """" since there is in fact a value ("https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#")

This was working with the version of the Azure SDK for Java 1.0.0 - SNAPSHOT that we were using from http://adxsnpashorts.azurewebsites.com prior to the release of Beta1. 

[LoadBalancerTemplate.zip](https://github.com/Azure/autorest/files/164081/LoadBalancerTemplate.zip)

**Comment by jianghaolu** [comment]
I assigned this to myself but @azuresdkci did not allow it.

**Comment by jianghaolu** [comment]
Nevertheless, it's fixed in this PR: https://github.com/Azure/autorest/pull/821.
