### ISSUE TITLE
XML content for body is JSON encoded in CSharp Generator

### ISSUE THREAD

**Issue by antmeehan** [Azure/autorest#823]
If a method has a body parameter which is specified as XML:

``` json
{
    "swagger" : "2.0",
    "info" : {
        "version" : "1.0",
        "title" : "XmlValidator"
    },
    "host" : "localhost:50971",
    "schemes" : ["https"],
    "paths" : {
        "/api/Schema/{fileName}/{friendlyName}" : {
            "post" : {
                "tags" : ["Schema"],
                "operationId" : "Schema_Upload",
                "consumes" : [
                    "application/xml"
                ],
                "produces" : ["application/json", "text/json", "application/xml", "text/xml"],
                "parameters" : [ {
                        "name" : "content",
                        "in" : "body",
                        "required" : true,
                        "type" : "string",
                        "schema" : {
                            "type" : "string"
                        }
                    }
                ],
                "responses" : {
                    "201" : {
                        "description" : "OK",
                        "schema" : {
                            "$ref" : "#/definitions/Object"
                        }
                    }
                },
                "deprecated" : false
            }
        }
    },
    "definitions" : {
        "Object" : {
            "type" : "object",
            "properties" : {}
        }
    }
}
```

The CSharp Generator always assumes the content needs to JSON encoded:

``` csharp
 // Serialize Request
string _requestContent = null;
_requestContent = SafeJsonConvert.SerializeObject(content, this.Client.SerializationSettings);
_httpRequest.Content = new StringContent(_requestContent, Encoding.UTF8);
_httpRequest.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/xml");`
```

Unfortunately this creates an invalid request, as the XML content will be escaped, and is no longer a valid document.

I'm guessing in the case the content type is not JSON, we should skip this step?

**Comment by devigned** [comment]
We do not support XML at this point. We do plan on adding support in an upcoming milestone.

/cc @NiklasGustafsson

**Comment by antmeehan** [comment]
Great! Thanks for the update.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by fearthecowboy** [comment]
Re-opening this issue and tagging for 1.0 release -- new 1.0 criteria includes supporting petstore.

**Comment by olydis** [comment]
The C# generator has added XML support few months ago! The Petstore Swagger example should work now.

I'll close this as it should be resolved, but feel free to reopen if you encounter any issues.
