### ISSUE TITLE
useDateTimeOffset only works with regular CSharp Generation, not AzureCSharp Generation

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#825]
After resolution of issue: https://github.com/Azure/autorest/issues/500 we can properly generate clients in C# to use DateTimeOffset, however the same is not true for AzureCSharperGenerator. Based on my  investigation the problem is that the property is set properly only for regular CSharpCodeGenerator, not the AzureCSharpCodeGenerator. It looks like the reason for this is that the CSharp settings are not also being propagated to the AzureCSharp settings, so the _namer in AzureCSharp will always have the value set to false.

I am not sure how to resolve this issue @stankovski can you take a look?

**Comment by devigned** [comment]
Thank you, @begoldsm. @stankovski might be delayed in responding. I'll see if we can get some other eyes on this.

**Comment by begoldsm** [comment]
@devigned thanks! Let me know who is looking at it and I can help them out, since I know where in the code the problem is, I am just not quite sure how to fix it/get the settings propagated :)

**Comment by begoldsm** [comment]
@devigned I think I have a fix for this now, but I would like it looked at to make sure it fits within the AutoRest design.

**Comment by devigned** [comment]
@sphibbs would you direct this to the right folks?

**Comment by begoldsm** [comment]
This issue is now resolved by the merged change above. I am closing this out now as all new builds of AutoRest nightly will have this change.
