### ISSUE TITLE
Generate decimal types?

### ISSUE THREAD

**Issue by monotore** [Azure/autorest#83]
I'm dealing with money, and have to use a decimal type to avoid "unatural" floating point rounding. [See Wikipedia for examples] (http://en.wikipedia.org/wiki/Floating_point#Accuracy_problems).

I have changed my Swagger config to generate number with decimal format:
c.MapType<decimal>(() => new Schema { type = "number", format = "decimal" });

The swagger.json now has decimal fields described like this:
"interestRateField":{"format":"decimal","type":"number"}

Autorest still use float fot this field:
public double? InterestRateField

How do I make Autorest use decimal instead of floating point? I can't see that I ever need floating point in my external interfaces, and decimal can by used in all situations if this makes a fix easier.

**Comment by markcowl** [comment]
@monotore Thanks for reporting this issue.  Unfortunately, there is currently no **standard** way to describe a number that is required to be a decimal in Swagger, see: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#dataTypeFormat  for a list of formats.

We are comtemplating an extension or new understood format in AutoRest that would enable expressing this restriction, but only tools that understand the extension will be able to use it - for a general solution, an addition would be needed to the swagger spec itself.  Note that Json schema validation would allow using 'multipleOf' (i.e. multipleOf 0.01) to express this constraint, but multipleOf is not a supported validation for Swagger schemas.

I suggest filing an issue with the swagger spec here: https://github.com/swagger-api/swagger-spec/issues for a general solution.

Meanwhile, we will keep this issue open to track adding an extension (or adding another format that we recognize).

If you are looking to simply use decimal in the case of all floating point numbers, it would be quite simple to extend the current C# generator to accomplish this.

**Comment by enkafan** [comment]
We went down the route of writing our own Swagger C# proxy generator a while back and ran into these same concerns. Constant battle where we have devs writing an API in C# and consuming the proxy from C# and want all the intrinsic types to match up. Nullable types are another pain that doesn't have a good answer in the swagger spec for us.

I'm halfway tempted to have swashbuckle emit a "x-dotnet-intrinsic-type" for these situations and have our proxy support them. Feels incredibly dirty, but short of waiting for a new spec I'm not quite sure what a better short term solution would be

**Comment by jkonecki** [comment]
@markcowl I would like to argue that since the *format* is an extensible string field a support for `decimal` could be easily added. Would you accept a PR?

**Comment by devigned** [comment]
We always accept pull requests! Please target the dev branch.

**Comment by Driedas** [comment]
Hey, is there any estimate on when this branch will be merged into master, and a new release published? In the current project we are dealing with money as well, so this would be very useful.
Thanks...

**Comment by stankovski** [comment]
https://github.com/Azure/autorest/pull/416
