### ISSUE TITLE
Support for non-string enum

### ISSUE THREAD

**Issue by hyonholee** [Azure/autorest#833]
Currently only string types are supported as an enum.  

However, some API restricts only a certain set of integers or a certain set of non-string values for a parameter.

**Comment by devigned** [comment]
@hyonholee do we have a mail thread regarding this request?

**Comment by amarzavery** [comment]
@devigned - This was the [reason](https://github.com/Azure/azure-rest-api-specs/pull/174#discussion-diff-55878545R242) behind filing this issue.

**Comment by devigned** [comment]
Thank you for adding the context, @amarzavery.
