### ISSUE TITLE
Autorest should never serialize dates with 5 places for milliseconds

### ISSUE THREAD

**Issue by andrerod** [Azure/autorest#834]
Javascript etc only understand 3. Which means that if a date is serialized using the "o" format in .net it wont be understood by a node etc backend. JSON doesn't have a hardrequirement on it, but it is a best practice.

**Comment by devigned** [comment]
@amarzavery any thoughts on this one?

**Comment by stankovski** [comment]
According to ISO 8601 format: 
> Decimal fractions may be added to any of the three time elements ... However, the number of decimal places needs to be agreed to by the communicating parties.

As such having milliseconds as decimals is technically legal as far as ISO 8601 goes and in line with the swagger format. It's just not always understood by all backends (SQL being an example).

**Comment by amarzavery** [comment]
closing this per Denis' comment.
