### ISSUE TITLE
TestClientNamePythonNormalization fails with 'subscription' != 'subscription_id'

### ISSUE THREAD

**Issue by brodyberg** [Azure/autorest#836]
Steps to reproduce: 
- pull master
- build
- Run all tests

Observed: 

```
Test Name:	Microsoft.Rest.Generator.Tests.ExtensionsTests.TestClientNamePythonNormalization
Test FullName:	Microsoft.Rest.Generator.Tests.ExtensionsTests.TestClientNamePythonNormalization
Test Source:	C:\...\autorest\AutoRest\Generators\Extensions\Extensions.Tests\ExtensionsTests.cs : line 267
Test Outcome:	Failed
Test Duration:	0:00:00.08

Result StackTrace:	at Microsoft.Rest.Generator.Tests.ExtensionsTests.TestClientNamePythonNormalization() in C:\...\autorest\AutoRest\Generators\Extensions\Extensions.Tests\ExtensionsTests.cs:line 287
Result Message:	
Assert.Equal() Failure
                      ↓ (pos 12)
Expected: subscription
Actual:   subscription_id
                      ↑ (pos 12)

```

This is the change which introduced the test: https://github.com/Azure/autorest/commit/939a90d6267895f17c58c5ee862f382527977831

**Comment by devigned** [comment]
@NiklasGustafsson any ideas?

**Comment by NiklasGustafsson** [comment]
I'll take a look.

**Comment by amarzavery** [comment]
@brodyberg - I tested it and the test passes for me as well. Subsequent PRs have been passing with Jenkins and Travis CI. Hence this should be a non issue. 
Please pull from upstream master.
git clean -dfx  (save changes if any before doing that)
Build the sln and run the test.
I am quite positive that the test would pass.

**Comment by brodyberg** [comment]
Thanks @amarzavery & @niklasgustafsson - I'll check again - and ensure I have a completely clean build.

**Comment by amarzavery** [comment]
closing this for now. Feel free to reopen if required.
