### ISSUE TITLE
swagger-recursive-type.json is invalid

### ISSUE THREAD

**Issue by b-filip** [Azure/autorest#838]
If you import autorest/AutoRest/Modelers/Swagger.Tests/Swagger/swagger-recursive-type.json in swagger-editor, it reports errors:

```
Reference could not be resolved: Product
Jump to line 40


Reference could not be resolved: Product
Jump to line 47

Reference could not be resolved: Error
Jump to line 51

Reference could not be resolved: Product
Jump to line 59

Reference could not be resolved: Product
Jump to line 63
```

**Comment by devigned** [comment]
Thank you for the feedback. I believe this is caused by the $ref not using the relative path within the document.

**Comment by b-filip** [comment]
I believe you should use `$ref: '#/definition/TypeName'`
Philip B.
14 марта 2016 г. 7:24 PM пользователь David Justice <notifications@github.com> написал:Thank you for the feedback. I believe this is caused by the $ref not using the relative path within the document.
