### ISSUE TITLE
Custom Generator Support

### ISSUE THREAD

**Issue by phil000** [Azure/autorest#843]
Hi,
We're needing to create and use our own generator, or at least augment one of the exiting ones but can cannot find the extensibility point.

We've found -CodeGenerator command line switch but this does not seem to give an option for a custom type\assembly.

We've found AutoRest.json but are unsure how to override or replace this to include our own generator.

Any clues?

**Comment by brodyberg** [comment]
Maybe more context will help - but AutoRest.json allows plugging in your own generator. Do you need/expect something else?

**Comment by phil000** [comment]
AutoRest.json (where we found it) was within the Tools directory of the NuGet package, so not directly affect'able by us. 
However, by inspecting the code it appears we can place our own AutoRest.json somewhere and a fallback process will find it bedfor the default one in \Tools.

**Comment by devigned** [comment]
@phil000 that is correct. Does this solve your issue?

**Comment by phil000** [comment]
Yes, although it'd book good it there were some documentation on this extensibility point and how to leverage it. At least we didn't find any.

**Comment by devigned** [comment]
@phil000 I agree. Would you be interested in submitting a pull request with what would have helped you?

**Comment by phil000** [comment]
We can certainly add it into our product backlog for consideration next sprint.
