### ISSUE TITLE
Specify customize exception type even there is no body

### ISSUE THREAD

**Issue by xingwu1** [Azure/autorest#855]
In the current design, we have to specify error body in order to return a customized exception type. However, in some situation, there will be no body return by server. For example, in HEAD request, server will not return body no matter what kind of error. If swagger spec to honor the real server behavior, we will not get desired exception type (we will get CloudException in this situation which doesn't make sense to client).

To resolve this issue, two possible approach:
1. Have ability to specify exception type without body
2. Create a HttpRestException which inherits RestException, it has httprequest/httpresponse properties, but no body property. Then customized exception/CloudException/HttpOperationException all inherit from HttpRestException. If no body is specified in swagger spec, we should throw this exception instead of CloudException. So client can catch HttpRestException to check the http result.

**Comment by stankovski** [comment]
Currently we have a constraint on models that they need to have at least one property. We can remove this constraint for exceptions.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
