### ISSUE TITLE
AutoRest swagger-extensions schema missing x-ms-client-name

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#857]
See this:
https://travis-ci.org/Azure/azure-rest-api-specs/builds/116772493

The build is failing due to `x-ms-client-name` not being defined in this schema: https://raw.githubusercontent.com/Azure/autorest/master/schema/swagger-extensions.json

**Comment by NiklasGustafsson** [comment]
My mistake -- I will fix it.

**Comment by NiklasGustafsson** [comment]
This should be fixed at this point -- can you try again?

**Comment by matthchr** [comment]
@NiklasGustafsson It works

**Comment by NiklasGustafsson** [comment]
Closed based on thread above.
