### ISSUE TITLE
[Python] msrest does not enforce JSON Accept header

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#867]
Hi,

msrest does no content negotiation currently and then does not fill the Accept header in any request.
Unfortunately, not all provider use JSON by default when the Accept header is not present (this leads to problem like this https://github.com/Azure/azure-sdk-for-python/issues/553, solved by adding the right Accept header)

In addition, msrest cannot currently handle XML data. All requests have to be JSON.

I suggest to force `Accept: application/json` in all requests done using msrest. This can be made at several places:
- In msrest directly (here  https://github.com/Azure/autorest/blob/master/ClientRuntimes/Python/msrest/msrest/service_client.py#L119)
- In each operation, between these two lines:
```python
# Construct headers
header_parameters = {}
header_parameters['Content-Type'] = 'application/json; charset=utf-8'
```

What do you think?

I don't mind adding directly in msrest core code, since as I said msrest cannot parse XML anyway. 

I can do the PR once you we agreed on the result.

@annatisch

**Comment by annatisch** [comment]
I would be keen to know how the other clients/languages support or enforce this.
The generated code will often set the Content-type header if the content-type is specified in the swagger spec so I'm not sure we should be simply overwriting it. Particularly for stream requests/responses.
Though perhaps we should set it where it doesn't already exist.

**Comment by devigned** [comment]
I believe we select the first accept type from the swagger that corresponds to application/json.

**Comment by lmazuel** [comment]
@devigned 

Are you saying that if the Swagger file has:
```json
  "produces": [
    "application/json"
  ],
```

We should add an Accept for application/json, if not leave the server decides?

**Comment by lmazuel** [comment]
Side effect: do we have to refuse generate Python code if "produces" does not contains `application/json` (since anyway we can'do anything with something else notJSON)?

**Comment by annatisch** [comment]
@lmazuel - I think it's okay to put this is msrest,
I can add:
session.headers['Accept'] = 'application/json'
at line 120 as you suggest.

**Comment by lmazuel** [comment]
Thank you @annatisch I will do a PR that way!

**Comment by annatisch** [comment]
@amarzavery 
This can be closed now :)
