### ISSUE TITLE
When swagger.json contains "Client" entity, generated C# code doesn't compile

### ISSUE THREAD

**Issue by jmalczak** [Azure/autorest#88]
Hey 

When I generate client using autorest.exe and swagger.json contains "Client" entity, generated C# code doesn't compile since name of the generated class is Client and each class contains Client property and both can't have the same name. Also where I can find source code of the acctual autorest.exe since I couldn't locate the code in repository? 

Thanks a lot

**Comment by brenovieira** [comment]
Same problem here. 'Client': member names cannot be the same as their enclosing type

Please edit issue title to "Client" instead of "Clint" (typo).

**Comment by jmalczak** [comment]
Where is the source code of autorest.exe tool?  I can't locate it in source control?

**Comment by matt-gibbs** [comment]
Source code is still in private source control. We will get it here in a couple of weeks.

**Comment by matt-gibbs** [comment]
@jmalczak Is your repro the same as @brenovieira? If not, can you please attach your swagger. We have a fix for the other repro, but want to make sure it covers what you are seeing too.

**Comment by jmalczak** [comment]
Hey

Unfortunately I can't attach swagger.json, but my case is really simple, one of the services was accessible via http://url/client and due to that generated client class was named Client. I can confirm that it's working when you will publish fix though.

**Comment by stankovski** [comment]
@jmalczak 
The Client name is based on the title field in swagger. Try changing the title and reopen the issue if it is not resolved.
