### ISSUE TITLE
Default Stream value should be empty instead of null

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#884]
Right now for all optional parameters in C# we use default(<type>). This is a great design that I like a lot, however it has a limitation for us that I was wondering if we can fix in code gen: the default value for a Stream is null instead of an empty stream. The problem with this is that it causes PUTs to fail where we have optional stream content, since you can’t pass null in as the body of a put, it has to be an empty stream instead. 

We should handle this logic in code gen and, if stream types that are optional are not specified then give them an empty default instead of null.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
