### ISSUE TITLE
ODataQuery.ToString() does not properly encode strings

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#899]
The toString method on ODataQuery<T> does not properly encoding strings, which can result in bad URIs. For example, in our previous (hydra spec generated) sdk we would get this URI when trying to filter by a specific DateTimeOffset:

https://sandbox.azuredatalakeanalytics.net/Jobs?$filter=submitTime%20lt%20DateTimeOffset%272016-03-28T08%3A15%3A00.0971693%2B00%3A00%27%20and%20state%20ne%20%27Ended%27&api-version=2015-11-01-preview

Note the bold for the escaped characters. This is now what the string looks like when using the ODataQuery objects ToString() method:
https://sandbox.azuredatalakeanalytics.net/Jobs?$filter=submitTime%20lt%20DateTimeOffset'2016-03-28T08:15:34.3429300+00:00'%20and%20state%20ne%20'Ended'&api-version=2015-11-01-preview

Note that all the special characters are left intact, invalidating the URI. The fix here is to change how the formatting works for the ToString method to work as follows for each section:

queryStringList.Add(string.Format(CultureInfo.InvariantCulture,
                    "$filter={0}", **Uri.EscapeDataString(Filter)));**

**Comment by begoldsm** [comment]
I am fixing this right now and will be sending out a PR shortly.

**Comment by begoldsm** [comment]
@amarzavery can you deactivate this now that my change has been reverted? This still needs to ideally be fixed as part of the object model and not rely on the caller to know what strings to encode/not encode for their odata queries that are constructed in our objects.

**Comment by begoldsm** [comment]
Sorry, re-activate, not deactivate. Phone typing is hard :)

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
