### ISSUE TITLE
Generated ServiceClient constructor no longer accessible

### ISSUE THREAD

**Issue by deanwiles** [Azure/autorest#907]
Thank you for the autorest library. It has been very helpful in quickly implementing rest client code. Unfortunately I ran into a compilation problem in my C# consumer app after I upgraded from autorest v0.9.6 to v2.1.0. 

In fix #592, some public constructors for the generated ServiceClient-derived class were made protected, however I think one should still be public. The following code used to work but now won't compile "due to its protection level":

`var api = new MyServiceClient(new HttpClientHandler() { UseDefaultCredentials = true });`

My service is an ASP.NET Web API using Windows Authentication so the client only needs the user's windows credentials via the code above. Is there a better way to do this, or do you concur that the following constructor should be public?

`public MyServiceClient(HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : base(rootHandler, handlers)`

BTW, several of the generated <param name=...> comments list parameters (e.g. baseUri) as Optional when they are really Required since an exception is thrown if not supplied.

Thanks,
Dean

**Comment by koolraap** [comment]
@deanwiles FWIW I use Reflection to access that constructor.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
