### ISSUE TITLE
IntDate is not supported in AutoRest

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#909]
IntDate is integer representation of UNIX origin time used in JSON Web Token(JWT). Key Vault REST API has an attribute class containing properties of type IntDate such as [exp and nbf](https://msdn.microsoft.com/en-us/library/azure/dn903634.aspx). However, IntDate is not supported in the AutoRest to convert the Unix time to DateTime which is consumable by the client side code. Is it possible to add IntDate support to AutoRest? This is similar to [this issue](https://github.com/Azure/autorest/issues/805).

To do so, we need to define a UnixTimeConverter that [converts type of long to DateTime](https://github.com/Azure/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault/UnixEpoch.cs). 
[JsonConverter(typeof (UnixTimeConverter))]

**Comment by markcowl** [comment]
@pomortaz Is there a specification somewhere for exactly what intDate is?  The JsonConverter is nice, but we will need to implement this in multiple languages, so a specification of the format would be useful

**Comment by pomortaz** [comment]
According to [JSON Web Token (JWT) draft](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32), InDate (which is called [NumericDate now](http://static.javadoc.io/org.bitbucket.b_c/jose4j/0.4.4/org/jose4j/jwt/IntDate.html)) is "A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds."

This is also known as [Unix Time](https://en.wikipedia.org/wiki/Unix_time).
