### ISSUE TITLE
[Python] Add basic type checking

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#915]
Hi,

I have a few feedback from people who waste time because we are not doing a minimal type checking. For instance this code:
```python
creds = ServicePrincipalCredentials(client_id=client_id, secret=client_secret, tenant=tenant_id)
resource_client = ResourceManagementClient(ResourceManagementClientConfiguration(subscription_id, creds))
resource_groups = resource_client.resource_groups.list()
```

We have switched `subscription_id` and `creds` and an exception in only send for the `list()` call with a bad error:
```python
  File "/usr/local/lib/python2.7/dist-packages/msrest/service_client.py", line 166, in send
    session = self.creds.signed_session()
AttributeError: 'str' object has no attribute 'signed_session'
```

Doing a simple (for instance here for str)
```python
if not isinstance(subscription_id, str):
  raise ValueError('subscription_id must be a str, not a %r' %  subscription_id.__class__.__name__)
```
based on the `str` type on Swagger should be enough

@annatisch ?

**Comment by annatisch** [comment]
Thanks @lmazuel,
So you would like to see this in the generated code, rather than at the runtime level?

**Comment by lmazuel** [comment]
Yes, stick to this one already generated in each client:
```python
if subscription_id is None:
            raise ValueError('subscription_id must not be None.')
```

**Comment by lmazuel** [comment]
In other words, when I see `required=True` in Swagger, I want the `is None` test. When I see `type=string` I want the `isinstance` test.

**Comment by annatisch** [comment]
Okay - sounds reasonable - I will see what I can do :)

**Comment by annatisch** [comment]
@amarzavery - this can be closed now.
