### ISSUE TITLE
[Java, Python, Ruby] CSV / Arrays / Lists in URL's are not replaced correctly

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#916]
I have fixed this in C# and node.js. This needs to be fixed in Java, Python and Ruby.
I have added tests in Java and python. The tests were failing so have commented them.
@jianghaolu, @annatisch, @devigned  - please make sure that the feature is supported  in the languages that you own.

Actual issue #900.

**Comment by annatisch** [comment]
@amarzavery ,
This should now be resolved for Python

**Comment by vishrutshah** [comment]
Removing Ruby label as fix is in.

**Comment by fearthecowboy** [comment]
This issue has not been handled in over a year. . 

@jianghaolu -- If this is still a concern, reopen it with new details
