### ISSUE TITLE
New Feature: Make Input parameter accept url to swagger.json

### ISSUE THREAD

**Issue by brenovieira** [Azure/autorest#93]
It would be nice to pass an url to Input parameter and AutoRest download the content and generate the files.

For example,
AutoRest.exe -Input http://petstore.swagger.io/v2/swagger.json -Namespace PetStore

**Comment by matt-gibbs** [comment]
Yes, @brenovieira, agreed. It's on the backlog.

**Comment by stankovski** [comment]
@brenovieira this has been implemented in dev branch. Will be available in the next release.

**Comment by brenovieira** [comment]
Thanks @stankovski and @matt-gibbs .

**Comment by hovsepm** [comment]
Fixed in Release 0.10.0 - [nuget](https://www.nuget.org/packages/AutoRest/), [chocolatey](https://chocolatey.org/packages/AutoRest), [github] (https://github.com/Azure/autorest/releases/tag/AutoRest-0.10.0)
