### ISSUE TITLE
Make Credentials optional

### ISSUE THREAD

**Issue by henning-krause** [Azure/autorest#930]
I generated a C# client for my REST service. This service has some operations requiring authentication, but others do not. So I've created my client with the -AddCredential parameter.

But now, I can't create a service instance without credentials. 

Looking at the constructor, the code is rather odd:

```
if (credentials == null)
{
    throw new ArgumentNullException("credentials");
}
this.Credentials = credentials;
if (this.Credentials != null)
{
    this.Credentials.InitializeServiceClient(this);
}
```

Now, the latter part of the constructor makes the credential parameter look like it's optional. But the null check in the first lines prevent this.

Now, I've worked around this issue by creating a custom ServiceCredential class, which simply does nothing:

```
private class AnonymousCredential : ServiceClientCredentials
{
	public static ServiceClientCredentials Instance { get; } = new AnonymousCredential();

	private AnonymousCredential()
	{
	}
}
```

But this is rather inconvenient. Could the null check be removed from the generated constructor?

**Comment by amarzavery** [comment]
If you generated the client with -AddCredentials parameter then it means that the client needs credentials. 
I agree about the redundant check before doing ``` this.Credentials.InitializeServiceClient(this);```.

You can do two things:
1. Generate two clients (with -AddCrendentials and one without it) and use them accordingly.
2. You can generate without credentials. You can add a delefating handler to the pipeline to check for creds and add the bearer token to the request header.

Hope this helps :).

**Comment by chrisklepeis** [comment]
I'm in a similar boat. Since the service class is partial, you could also add onto it to add the expected behavior:

    public partial class MyServiceClient : ServiceClient<MyServiceClient>, IMyServiceClient
    {
        /// <summary>
        /// Initializes a new instance of the SolidServices class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        public MyServiceClient(Uri baseUri)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this.BaseUri = baseUri;
        }

        public void SetCredentials(ServiceClientCredentials credentials)
        {
            if(credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }

            this.Credentials = credentials;
            this.Credentials.InitializeServiceClient(this);
        }
    }
