### ISSUE TITLE
Difference between constructors for UserTokenProvider and ApplicationTokenProvider

### ISSUE THREAD

**Issue by matt1883** [Azure/autorest#933]
In the `Microsoft.Rest.ClientRuntime.Azure.Authentication` package, there is a difference between the constructors for `UserTokenProvider` and `ApplicationTokenProvider` that doesn't seem necessary:

UserTokenProvider’s constructor accepts **Uri** tokenAudience, while `ApplicationTokenProvider` accepts **string** `tokenAudience`.

Perhaps both of these should be of type **string**.

**Comment by fearthecowboy** [comment]
We've moved the C# ClientRuntime to https://github.com/Azure/azure-sdk-for-net

If this is still a concern, can you refle refile this bug in that repo?

Thanks!
