### ISSUE TITLE
AutoRest.exe does not set ERRORLEVEL to non-zero value on failure

### ISSUE THREAD

**Issue by koolraap** [Azure/autorest#935]
AutoRest.exe should return a non-zero value indicating failure if an error occurs. This would allow scripts calling AutoRest to behave correctly when the input Swagger file is invalid.

To reproduce:

     autorest -rhubarb
     echo %errorlevel%

Expected result is non-zero, actual result is 0.

Looking at the code, seems like an easy fix: assume failure unless success occurs. In Main() in Program.cs change from void Main() to int Main()

        private static int Main(string[] args)
        {
            // ADD THIS
            var exitCode = 1;

SNIP

                    if (settings != null && !settings.ShowHelp)
                    {
                        if (Logger.Entries.Any(e => e.Severity == LogEntrySeverity.Error || e.Severity == LogEntrySeverity.Fatal))
                        {
                            Console.WriteLine(Resources.GenerationFailed);
                            Console.WriteLine(string.Format(CultureInfo.InvariantCulture, "{0} {1}",
                                typeof(Program).Assembly.ManifestModule.Name,
                                string.Join(" ", args)));
                        }
                        else
                        {
                            Console.WriteLine(Resources.GenerationComplete,
                                settings.CodeGenerator, settings.Input);
                           
                            // ADD THIS
                            exitCode = 0;
                        }
                    }

SNIP

           // ADD THIS
           return exitCode;
     }

**Comment by yugangw-msft** [comment]
+1

**Comment by amarzavery** [comment]
Thanks for reporting this. The fix will be in for the next release.
