### ISSUE TITLE
Ambiguous reference for entities on namespace System

### ISSUE THREAD

**Issue by brenovieira** [Azure/autorest#94]
I have a class **Action**.

AutoRest generates a class Action on namespace MyNamespace.Models and
ActionOperations, ActionOperationsExtensions and IActionOperations on namespace MyNamespace.

Methods on both ActionOperations, ActionOperationsExtensions and IActionOperations reference Action and have "using System" which causes an ambigous reference between 'System.Action' and 'MyNamespace.Models.Action'.

I see four solutions:
* Detect conflit and rename the entity as it already does for ActionOperations.

> warning: Client operation with name 'Action' was renamed to 'ActionOperations' because it conflicts with following entities: Action (already used in schema definition)
> Please consider changing your swagger specification to avoid naming conflicts.

* Put all classes and interfaces related to the entity on the same namespace.

For example, put both Action, ActionOperations, ActionOperationsExtensions and IActionOperations on MyNamespace.

* Add using statement Entity = MyNamespace.Models.Entity on each class and interface generated.

For example, adding "using Action = MyNamespace.Models.Action".

* Use the entity's full description (MyNamespace.Models.Entity) every time.

`Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MyNamespace.Models.Action>> result = await operations.GetWithOperationResponseAsync(authorization, cancellationToken).ConfigureAwait(false);`

**Comment by matt-gibbs** [comment]
Thanks @brenovieira 
I am wary of renaming. I think it will lead to confusion, especially when it comes to the Models.
The full namespace would work but gets a bit ugly to look at.  We'll get something worked out. Expect a new release in a few weeks along with the sources to get populated into the repo too. Leaving this open 'til we get the fix in place.

**Comment by stankovski** [comment]
This scenario should work as of 0.11.0 since now we are generating usings inside the namespace

**Comment by brenovieira** [comment]
@stankovski , :+1: 

I believe that is right !

**Comment by brenovieira** [comment]
@stankovski , please open this issue again.

I updated to 0.12.0 and it generated the same problem, even with usings inside the namespace.

Please, see what it generated (part of) in this [gist](https://gist.github.com/brenovieira/97854a602657292d60c9).

The lines - [59](https://gist.github.com/brenovieira/97854a602657292d60c9#file-api-client-generated-cs-L59), [135](https://gist.github.com/brenovieira/97854a602657292d60c9#file-api-client-generated-cs-L135), [142](https://gist.github.com/brenovieira/97854a602657292d60c9#file-api-client-generated-cs-L142) - don't compile since it has Action, which is defined in namespace Models and System.

On [line 7](https://gist.github.com/brenovieira/97854a602657292d60c9#file-api-client-generated-cs-L7) you add `using System` and
on [line 20](https://gist.github.com/brenovieira/97854a602657292d60c9#file-api-client-generated-cs-L20), you add my namespace `using Models`.

So you define both and it has an ambigous reference.

note:
I have the same issue with a class called Group. Error:
'Group' is an ambigous reference between 'API.Cliente.Models.Group' and 'System.Text.RegularExpressions.Group'.

note2:
I'm not sure I had this issue with 0.11.0 as well or not.

**Comment by stankovski** [comment]
Tracking via: https://www.pivotaltracker.com/story/show/107076350
