### ISSUE TITLE
Getting 403 forbidden when providing a URL as Input parameter

### ISSUE THREAD

**Issue by alesvi** [Azure/autorest#940]
If I provide a URL for the input parameter I get:

> AutoRest.exe : error: [FATAL] Error generating client model: The remote server returned an error: (403) Forbidden.

The JSON definition URL is correct and available. This works prefectly and I get a 200 response:

> wget http://myapi/swagger/docs/v1

Any idea what can be wrong? Any help will be appreciated

**Comment by devigned** [comment]
Can you provide the swagger file associated with that uri? The uri you specified is unreachable for me.

**Comment by alesvi** [comment]
[swagger.json.txt](https://github.com/Azure/autorest/files/217316/swagger.json.txt)

This is the swagger.json file for a simplified version of my API. But I don't know if the file will help you reproducing my problem. As I said before, if I provide the uri in the input parameter, I get the 403 error. 
But the uri is correct. And if I save the json in a file and provide the file name as input parameter, it works and AutoRest generates the code without any problem.

**Comment by brodyberg** [comment]
What's the full command-line you are passing to autorest.exe?

**Comment by alesvi** [comment]
AutoRest.exe -Input http://localhost:60615/swagger/docs/v1 -Namespace Client -OutputDirectory .\code -CodeGenerator CSharp

**Comment by amarzavery** [comment]
Just pointing out some difference after looking at your url and the one that swagger petstore provides..
If you look at the petstore api http://petstore.swagger.io/ and the link that it provides for its swagger 
is like this: http://petstore.swagger.io/v2**/swagger.json**. It contains **/swagger.json** in the end. Are you sure that when you access **http://localhost:60615/swagger/docs/v1** it like this in the browser, it displays the json in the browser? Will this link **http://localhost:60615/swagger/docs/v1/swagger.json** work ?

**Comment by alesvi** [comment]
Thanks for your comment @amarzavery , but I saw what the problem is and it's not that. My API has a request validator that requires a UserAgent header. That's why I can get the JSON definition in the browser but I get the 403 when running AutoRest, because the command doesn't send any UserAgent header.

I've submitted a PR that adds the header, in case you think it could be useful: #947
