### ISSUE TITLE
x-ms-client-name ignored on flattened nested properties

### ISSUE THREAD

**Issue by BurtBiel** [Azure/autorest#941]
I have a flattened object structure like (flattened at each level):
   obj -> params -> object -> params -> parameter

the default name is obj_params_object_params_parameter

I added the extension to have a shorter name:
   obj -> params -> object -> params -> parameter("x-ms-client-name": "shortName")

Expected: the short name is generated for parameter
Actual: the long name is still generated

**Comment by amarzavery** [comment]
@annatisch - I tested this for Azure.NodeJS and it works fine. This may be a python related issue.

**Comment by annatisch** [comment]
@amarzavery ,
Thanks! Burt supplied me with the applicable swagger spec and I'm investigating :)

**Comment by amarzavery** [comment]
@annatisch - Can this be closed?

**Comment by annatisch** [comment]
@amarzavery  - yes I've had confirmation that this is resolved. Thanks!
