### ISSUE TITLE
Flattened property required attribute lost

### ISSUE THREAD

**Issue by BurtBiel** [Azure/autorest#946]
I have a flattened object structure like (flattened at each level):
 obj -> params -> object -> params -> parameter(required)

Generate obj_params_object_params_parameter with the AzurePython output type:

Expected: _params_object_params_parameter is generated with no default value 
 Actual: _params_object_params_parameter is generated with a default value, making it optional

**Comment by annatisch** [comment]
Hi @BurtBiel ,
Would it be possible to have a sample swagger spec the reproduces this? (And possibly the AutoRest cmd used to generate, if you make use of the flattening flag).
Thanks!

**Comment by amarzavery** [comment]
If a property that is nested 4 levels deep and if somewhere in the middle an ancestor is optional, it is hard to decide, whether the property will end up as required or optional. So we came up with a basic requirement:

> “If a child property that is nested at least two levels deep and needs to be flattened all the way up then all of its parents must be required.” 

For example: In the following object - 
foo: {bar: { baz: { zoo: “I would like to be a required parameter”}, zoo must be a required property of baz,baz must be a required property of bar, and bar must be a required property of foo, for zoo to be a required parameter, when it is flattened all the way up.

**Comment by amarzavery** [comment]
If you modify the spec accordingly then things should work as expected.

**Comment by annatisch** [comment]
@BurtBiel ,
Were you able to get this working? Let us know if you'd like us to close this.

**Comment by BurtBiel** [comment]
Yes, I was able to get the properties working, so we can close this issue.  Thanks!
