### ISSUE TITLE
Expose ARM Async operation progress

### ISSUE THREAD

**Issue by tudordid** [Azure/autorest#960]
We have an use case where our RP resource provisioning can take tens of seconds. Because of this, the call is implemented as an async operation, and defined accordingly as a long running operation. While AutoRest today generates the code to handle this operation and poll for the resource's provisioning state until it reaches a final status, it would be great if it can also expose the completion rate of the provisioning process (the **percentComplete ** element) that is exposed on every status get call:

GET https://api-dogfood.resources.windows-int.net/subscriptions/325f8243-f630-45ec-8a57-6c173a30cfca/providers/Microsoft.MachineLearning/locations/southcentralus/operationsStatus/8997f319-f6f1-4ecf-bcf5-3cb5c1af8b1d?api-version=2016-04-01-privatepreview 

Response:

{
  "id": "/subscriptions/325f8243-f630-45ec-8a57-6c173a30cfca/providers/Microsoft.MachineLearning/locations/southcentralus/operationsStatus/8997f319-f6f1-4ecf-bcf5-3cb5c1af8b1d",
  "name": "8997f319-f6f1-4ecf-bcf5-3cb5c1af8b1d",
  "status": "Succeeded",
  "startTime": "2016-04-18T23:46:50.0632851Z",
  "endTime": "2016-04-18T23:46:58.3827099Z",
**  "percentComplete": 1.0**
}

This information can maybe be streamed back to the client, such that it can be displayed in , for example, a PS session window to show that the resource provisioning is progressing.

**Comment by devigned** [comment]
Yes! This needs to be done. I'd also like to add a block / callback for all languages on the async long running operations to provide the progress update.

@Azure/adx-dotnet-contributor, @Azure/ruby-admins, @jianghaolu, @lmazuel

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
