### ISSUE TITLE
Json serialization exception causes response content to be null in thrown Exception

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest#961]
For example, see:  https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/Generated/ResourceGroupsOperations.cs#L884

The assignment of _responseContent should occur outside the try/catch in generate code

**Comment by tbombach** [comment]
Looks like the link to the example isn't working for some reason. Look at the line here: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/ResourceGroupsOperations.cs#L886

**Comment by kirthik** [comment]
Assigning to @markcowl to provide more information.

**Comment by fearthecowboy** [comment]
Looping back around...

Hey @markcowl ,  Is this really just moving the line :

https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/ResourceGroupsOperations.cs#L1034

Up so it's outside the try? 

Doesn't look dangerous to me.

**Comment by dsgouda** [comment]
@fearthecowboy should we follow up on this?
