### ISSUE TITLE
Preserve original request id for async operations

### ISSUE THREAD

**Issue by tudordid** [Azure/autorest#970]
Today, when handling long running operations, the AutoRest generated client first makes a PUT/PATCH/POST/DELETE request to the server, and then proceeds to poll the for the status of that operation to show a completion or failure. 

In case of an error, the CloudException raised does not contain a request id in its dedicated property, and the http response included is that of the latest GET (polling) call made, which does not really reflect the error when searching logs by that request id. 

This issue is an ask to cache the original request id from the server's response to the initial PUT/PATCH/POST/DELETE request, as that allows us to filter only logs recorded by the actual async operation.

**Comment by devigned** [comment]
I thought we have a correlation id to tie this together rather than the request id. @amarzavery or @markcowl do you recall? We should be be able to correlate this as a singe set of requests.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
