### ISSUE TITLE
Support for datetimeoffset in ODataQuery

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#975]
Spoke with @hovsepm about this. Opening an issue to tracking adding support for datetimeoffset parsing and formatting as part of ODataQuery construction (currently only DateTime and TimeSpan have custom formatting).

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
