### ISSUE TITLE
Can't Mock my AutoRest generated extension methods

### ISSUE THREAD

**Issue by daviddunkley** [Azure/autorest#976]
I am having trouble trying to Mock the behaviour of my AutoREST generated C# SDK Client.
__Problem__
* In the Unit Tests for my calling code (it calls my API via an AutoRest generated SDK) I would like to Mock the behaviour of the AutoRest SDK Client so I am only testing my code not the code in the AutoRest class
* I would like my test to verify the SDK was called, ideally something like this
```
    var myIdentityClient = new Mock<IMyIdentity>();
    myIdentityClient.Setup(m => m.Identities.Create(It.IsAny<IdentityModel>(), It.IsAny<string>()));

    myIdentityClient.Object.Identities.Create(_identityModel, _internalApiKey);

    myIdentityClient.Verify(m => m.Identities.Create(It.IsAny<IdentityModel>(), It.IsAny<string>()));
```
* Problem is that the `Create` extension method is not Mocked despite being part of the IIdentity, so when I call the `.Setup` I get the following Exception
```
System.NotSupportedException was unhandled by user code
  HResult=-2146233067
  Message=Expression references a method that does not belong to the mocked object: m => m.Identities.Create(It.IsAny<IdentityModel>(), It.IsAny<String>())
  Source=Moq
  StackTrace:
       at Moq.Mock.ThrowIfNotMember(Expression setup, MethodInfo method)
       at Moq.Mock.<>c__DisplayClass1c`2.<Setup>b__1b()
       at My.Identity.SDK.Tests.IdentityTests.MockIdentitySdk() in C:\Source\Origin\my.identity\my.Identity.SDK.Tests\IdentityTests.cs:line 63
  InnerException: 
``` 
* I could Mock the lower level `IIdentity` method `CreateWithHttpMessagesAsync` but this seems like my Unit Test needs to know a lot more than it should about the SDK

__Solutions__
1. Find some way to Mock the extension methods. I have tried various ways but as yet no joy. Any help would be appreciated
2. Change the behaviour of the AutoRest CLI to not use extension methods and include the `Create` method in the `IIdentity` interface, so it can be Mocked, maybe this could be a `-Style` parameter passed to the CLI
3. as a last resort, I know I can always wrap the extension methods in an interface of my own, whose implementation will just call them, thereby some what defeating the whole benefit of generating the SDK

__Background__
* I am running Visual Studio 2015 Professional and all the code is in C#
* I have generated the proxies using the NuGet AutoRest.0.15.0 autorest CLI from a swagger.json produced by an API
* I am using the Moq NuGet package, version 4.2.1510.2205
* The AutoRest generated code has a Client interface
```
public partial interface IMyIdentity : IDisposable
{

}
```
* And a Client implementation class
```
public partial class MyIdentity : ServiceClient<MyIdentity>, IMyIdentity
{
    IIdentities Identities { get; }
}
```
* The `IIdentities` interface has a method which corresponds directly to the Create method in my API
```
public partial interface IIdentities
{
    Task<HttpOperationResponse<object>> CreateWithHttpMessagesAsync(IdentityModel identity, string xApiKey, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
}
```
* There is an implementation class Identity of `IIdentities`, which calls the API
* There is also an extension method called `Create` and `CreateAsync`, which hides all the HTTP'ness
```
public static partial class IdentitiesExtensions
{
    public static object Create(this IIdentities operations, IdentityModel identity, string xApiKey)
    {
    }

    public static async Task<object> CreateAsync(this IIdentities operations, IdentityModel identity, string xApiKey, CancellationToken cancellationToken = default(CancellationToken))
    {
    }
}
```

**Comment by devigned** [comment]
I like this enhancement request. We should be able to mock out calls to generated code. In fact, it would be pretty cool to add mocking helpers or something to assist.

@markcowl do you have any thoughts on how you'd approach this?

**Comment by gitfool** [comment]
I'm hitting this problem as well. What's the reason for using extension methods?

The common use case seems to be the wrong way around - the `WithHttpMessagesAsync` methods are not needed unless you want much more control; I always use just the higher level abstractions (in the extension methods).

Doesn't it make more sense that the interface is a generic 'proxy' using just external contract types and therefore should abstract and hide the implementation details that it fronts a HTTP / REST service? It certainly makes more sense when you want to mock it and so shouldn't have to be burdened with such irrelevant details.

The simplest solution is just to fold the extension methods in with the interface. If the original idea was to have better code separation when generating multiple source files, then this can be preserved as is; just change the extension methods to be methods on the partial interface instead. It's not as though you get a different experience at design-time - you always see all methods with intellisense anyway!

**Comment by gitfool** [comment]
@daviddunkley Meanwhile, the simplest workaround is to mock `CreateWithHttpMessagesAsync`, as you mentioned above:
```c#
var myIdentityClient = new Mock<IMyIdentity>();
myIdentityClient.Setup(m => m.Identities.CreateWithHttpMessagesAsync(It.IsAny<IdentityModel>(), It.IsAny<string>(), null, CancellationToken.None));

myIdentityClient.Object.Identities.Create(_identityModel, _internalApiKey);

myIdentityClient.Verify(m => m.Identities.CreateWithHttpMessagesAsync(It.IsAny<IdentityModel>(), It.IsAny<string>(), null, CancellationToken.None));
```
Which adds a couple of redundant parameters (`null` and `CancellationToken.None`) to the end. Not pretty, but not too bad either.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by hoeflerm** [comment]
@fearthecowboy 
Was there any progress since your last post from 15 Jun 2016?
Thanks in advance

**Comment by andrew-buckley** [comment]
@fearthecowboy has this been revisited?

**Comment by fearthecowboy** [comment]
O_o  well.... Sorta.

We're not going to do significant changes to the existing c# generator, mostly because it's overly rigid in it's design, and too many things depend on how it's already working.  

As part of creating a PowerShell cmdlet generator, I've begun the process of creating a whole new generator for c#. It'll be in two layers, a low-level (underlying REST implementation that's designed for code ) and then a high-level consumer SDK layer (designed for consumer convenience).

In the next couple weeks I should have the first cut of the low-level generator working, and then I'll be spending the next several months on the PowerShell generator that goes on top of that.

Later this summer, I should be creating the generator for the high-level (consumer) SDK for C#.  I don't anticipate using extension methods for anything this time around.   (I've thought that was kind weird for a long time).

**Comment by cdesewell** [comment]
@fearthecowboy I'm using a client generated by this tool and find that I still can't mock anything. Has this issue moved forward at all?

**Comment by fearthecowboy** [comment]
I am still working on the new generator. It's going slower than I would like, but we're making progress.

**Comment by mabead** [comment]
Can this issue be re-opened since it is not fixed?

**Comment by jwenger100** [comment]
Is there any update on this issue? I'm still having a similar problem.

**Comment by williamb-egov** [comment]
Still an issue .. maybe this shouldn't be closed?

**Comment by suhas92** [comment]
Similar problem!

**Comment by mathiash98** [comment]
This should be quite high priority. Testability is very important. We can write a wrapper but that sort of ruins the point for autogenerated code.

**Comment by spygi** [comment]
+1 to this feature.

Probably I am missing something but isn't this as simple as making all generated methods `virtual` so that they could be overwritten by mocks?

**Comment by amithegde** [comment]
@fearthecowboy - while the team is working on rewirting the geneator for last couple of years, can we have a simple fix in the short term that helps us write tests while using autogenerated client?
