### ISSUE TITLE
Azure.CSharp should generate a constructor which includes all required properties

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#977]
Today a constructor is generated with parameters according to the below code snippet (taken from: https://github.com/Azure/autorest/blob/master/AutoRest/Generators/CSharp/CSharp/TemplateModels/ServiceClientTemplateModel.cs#L57)

```
        public string RequiredConstructorParameters
        {
            get
            {
                var requireParams = new List<string>();
                this.Properties.Where(p => p.IsRequired && p.IsReadOnly)
                    .ForEach(p => requireParams.Add(string.Format(CultureInfo.InvariantCulture, 
                        "{0} {1}", 
                        p.Type.Name, 
                        p.Name.ToCamelCase())));
                return string.Join(", ", requireParams);
            }
        }
           
```
The issue is that this checks `IsRequired` and `IsReadOnly`, which means a parameter which is merely `IsRequired` will not be included in the constructor.  There should be a constructor which takes all required parameters in it, to easily convey which parameters are required (and avoid the client having to discover them at runtime...)

I propose one of the following two changes: 
1. Change this condition to: `this.Properties.Where(p => p.IsRequired || p.IsReadOnly)`
2. Add another constructor which has the condition: `this.Properties.Where(p => p.IsRequired || p.IsReadOnly)` -- note that if you do this you have ot handle the case where the two constructors are the same (to avoid conflict).

I personally feel that option 1 is better, even though it is a breaking change because it increases clarity for all users of the client, but at the very least option 2 should be done.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by olydis** [comment]
Whoops, this one is actually solved for as long as I can remember. There's a constructor that contains all (non-constant) properties. This behavior is actually controversial now, since that way any change in optional properties becomes a breaking change for the SDK.

**Comment by matthchr** [comment]
@olydis In this case it was about just the required parameters, and if it's fixed that's great.
