### ISSUE TITLE
Support for cpprestsdk

### ISSUE THREAD

**Issue by Danielku15** [Azure/autorest#980]
Microsoft has developed a really nice SDK for consuming rest APIs on C++: 
https://github.com/Microsoft/cpprestsdk

It would be awesome if you can support code generation compatible with this SDK.

**Comment by devigned** [comment]
It would be awesome. C++ is not very high on our backlog right now, but we'd be happy to review pull requests if it was added through community contribution.

**Comment by Danielku15** [comment]
How complete is the current C# code generator regarding the OpenAPI / Swagger Specification? Are validators, exceptions, documentation, authentication etc fully supported? Based on this I might consider this code generator as base on how to generate the C++ code.

**Comment by devigned** [comment]
Authentication is pretty weak. Right now, it's just an authentication provider which is provided to the constructor of the service client. We intend on improving the functionality.

We are also focused on JSON and bin. We don't handle XML as of yet. Again, it's on the TODO list.

Outside of that, I think you will find C# is pretty well done.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
