### ISSUE TITLE
Adding `Operations` to each Operations class name

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#986]
This is an extension of https://github.com/Azure/azure-rest-api-specs/issues/203 focused on the Autorest side, to be able to trace modifications in Autorest.

We have a problem of consistency in the way Autorest generates the name of the class for each Operations class. Some language append `Operations`, some don't. Some language like Python append it in `Azure.Python` extension but not `Python` extension.

After the meeting today and last minute discussion with @devigned and @markcowl we should keep everything the most simple possible with a simple rule:

> Every generator _must_ append `Operations`. Always.

This keeps the guidance for a language generator really simple that an Operations class must ends with `Operations`. No language specific rule, no test like `if ends with Operations, do not append` which will reach a limit one day for sure.

This might implied a modification in the modeler if several `object` are named the same, as stated by @amarzavery in the Swagger side of this issue using GraphRbac.

Should this issue be splitted in an issue by language and each issue listed here?

**Comment by fearthecowboy** [comment]
>> Should this issue be splitted in an issue by language and each issue listed here?

Yes.
