### ISSUE TITLE
[Ruby] Fix ruby generator for datetime to reduce  'pending' tests

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#991]
Running gulp test:ruby outputs these "pending" tests:

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ArrayModule::Array should put dateTimeRfc1123 valid
     # Ruby DateTime -> RFC1123 serialization thinks DateTime.new(1492, 10, 12, 10, 15, 1, 'Z') is a Friday, but NodeJS/C# think it's a Wed
     Failure/Error: fail MsRest::HttpOperationError.new(request, http_response, error_model)

```
 MsRest::HttpOperationError:
   {
     "message": "MsRest::HttpOperationError",
     "request": {
       "base_uri": "http://localhost:3435",
       "path_template": "/array/prim/date-time-rfc1123/valid",
       "method": "put",
       "path_params": null,
       "skip_encoding_path_params": null,
       "query_params": null,
       "skip_encoding_query_params": null,
       "headers": {
         "Content-Type": "application/json; charset=utf-8"
       },
       "body": "[\"Fri, 01 Dec 2000 00:00:01 GMT\",\"Wed, 02 Jan 1980 00:11:35 GMT\",\"Fri, 12 Oct 1492 10:15:01 GMT\"]",
       "middlewares": [
         [
           "MsRest::RetryPolicyMiddleware",
           {
             "times": 3,
             "retry": 0.02
           }
         ],
         [
           "cookie_jar"
         ]
       ],
       "log": null
     },
     "response": {
       "body": "{\"message\":\"Did not like date-time-rfc1123 array req '[ 'Fri, 01 Dec 2000 00:00:01 GMT',\\n  'Wed, 02 Jan 1980 00:11:35 GMT',\\n  'Fri, 12 Oct 1492 10:15:01 GMT' ]'\",\"status\":400}",
       "headers": {
         "x-powered-by": "Express",
         "date": "Fri, 29 Apr 2016 20:18:54 GMT",
         "connection": "close",
         "content-length": "177"
       },
       "status": 400
     }
   }
 # ./RspecTests/Generated/array/body_array/array.rb:3143:in `block in put_date_time_rfc1123valid_async'
```

  2) Complex should put dateTimeRfc1123
     # DateTime.new(1, 1, 1, 0, 0, 0, 'Z') is interpreted as Sat, 01 Jan 0001 00:00:00 GMT, but other languages interpret it as Mon, 01 Jan 0001...
     Failure/Error: expect(date_time_rfc1123_wrapper.field.new_offset(0).strftime('%a, %d %b %Y %H:%M:%S GMT')).to eq(nil)

```
   expected: nil
        got: "Sat, 01 Jan 0001 00:00:00 GMT"

   (compared using ==)
 # ./RspecTests/complex_spec.rb:441:in `block (2 levels) in <module:ComplexModule>'
```

  3) DatetimeRfc1123Module::Datetimerfc1123 should get invalid
     # DateTime parsing of RFC1123 formats is not that robust, so the below doesnt throw an exception... is this okay?
     Failure/Error: expect(DateTime.parse('Tue, 01 Yoink FOOBAR 00:00:0A ABC')).to eq(nil)

```
   expected: nil
        got: #<DateTime: 2016-04-01T00:00:00+01:00 ((2457479j,82800s,0n),+3600s,2299161j)>

   (compared using ==)
 # ./RspecTests/datetime_rfc1123_spec.rb:36:in `block (2 levels) in <top (required)>'
```

  4) Date should put local negative offset max date time
     # proper working with datetime isnt implemented yet
     Failure/Error: fail MsRest::HttpOperationError.new(request, http_response, error_model)

```
 MsRest::HttpOperationError:
   {
     "message": "MsRest::HttpOperationError",
     "request": {
       "base_uri": "http://localhost:3435",
       "path_template": "/datetime/max/localnegativeoffset",
       "method": "put",
       "path_params": null,
       "skip_encoding_path_params": null,
       "query_params": null,
       "skip_encoding_query_params": null,
       "headers": {
         "Content-Type": "application/json; charset=utf-8"
       },
       "body": "\"10000-01-01T13:59:59Z\"",
       "middlewares": [
         [
           "MsRest::RetryPolicyMiddleware",
           {
             "times": 3,
             "retry": 0.02
           }
         ],
         [
           "cookie_jar"
         ]
       ],
       "log": null
     },
     "response": {
       "body": "{\"message\":\"Did not like the value provided for max datetime in the req '10000-01-01T13:59:59Z'\",\"status\":400}",
       "headers": {
         "x-powered-by": "Express",
         "date": "Fri, 29 Apr 2016 20:18:56 GMT",
         "connection": "close",
         "content-length": "110"
       },
       "status": 400
     }
   }
 # ./RspecTests/Generated/datetime/body_datetime/datetime.rb:817:in `block in put_local_negative_offset_max_date_time_async'
```

  5) Header should get response min date
     # proper working with datetime isnt implemented yet
     Failure/Error: fail
     RuntimeError:
     # ./RspecTests/header_spec.rb:211:in `block (2 levels) in module:HeaderModule'

  6) Header should post valid param dateTime
     # proper working with datetime isnt implemented yet
     Failure/Error: fail
     RuntimeError:
     # ./RspecTests/header_spec.rb:219:in `block (2 levels) in module:HeaderModule'

  7) Header should post min param dateTime
     # proper working with datetime isnt implemented yet
     Failure/Error: fail
     RuntimeError:
     # ./RspecTests/header_spec.rb:226:in `block (2 levels) in module:HeaderModule'

  8) Header should get response valid dateTime
     # proper working with datetime isnt implemented yet
     Failure/Error: fail
     RuntimeError:
     # ./RspecTests/header_spec.rb:233:in `block (2 levels) in module:HeaderModule'

  9) Header should get response min dateTime
     # proper working with datetime isnt implemented yet
     Failure/Error: fail
     RuntimeError:
     # ./RspecTests/header_spec.rb:241:in `block (2 levels) in module:HeaderModule'

  10) Header should post min param dateTimeRfc1123
      # proper working with minimum value datetime isnt implemented yet
      Failure/Error: fail MsRest::HttpOperationError.new(request, http_response, error_model)

```
  MsRest::HttpOperationError:
    {
      "message": "MsRest::HttpOperationError",
      "request": {
        "base_uri": "http://localhost:3435",
        "path_template": "/header/param/prim/datetimerfc1123",
        "method": "post",
        "path_params": null,
        "skip_encoding_path_params": null,
        "query_params": null,
        "skip_encoding_query_params": null,
        "headers": {
          "scenario": "min",
          "value": "Sat, 01 Jan 0001 00:00:00 GMT"
        },
        "body": null,
        "middlewares": [
          [
            "MsRest::RetryPolicyMiddleware",
            {
              "times": 3,
              "retry": 0.02
            }
          ],
          [
            "cookie_jar"
          ]
        ],
        "log": null
      },
      "response": {
        "body": "{\"message\":\"Did not like datetimerfc1123 scenario \\\"min\\\" with value Sat, 01 Jan 0001 00:00:00 GMT\",\"status\":400}",
        "headers": {
          "x-powered-by": "Express",
          "date": "Fri, 29 Apr 2016 20:18:58 GMT",
          "connection": "close",
          "content-length": "113"
        },
        "status": 400
      }
    }
  # ./RspecTests/Generated/header_folder/header/header.rb:1582:in `block in param_datetime_rfc1123_async'
```

  11) Header should post valid byte
      # proper working with unicode isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/header_spec.rb:272:in `block (2 levels) in module:HeaderModule'

  12) Header should get response valid byte
      # proper working with unicode isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/header_spec.rb:279:in `block (2 levels) in module:HeaderModule'

  13) UrlModule::Paths should get date null
      # Appropriately disallowed together with CSharp
      Failure/Error: expect { @paths_client.date_null_async('null').value! }.to raise_error(ArgumentError)

```
    expected ArgumentError, got #<MsRest::HttpOperationError: {
      "message": "MsRest::HttpOperationError",
      "request": {
        "base_uri": "http://localhost:3435",
        "path_template": "/paths/date/null/{datePath}",
        "method": "get",
        "path_params": {
          "datePath": "null"
        },
        "skip_encoding_path_params": null,
        "query_params": null,
        "skip_encoding_query_params": null,
        "headers": {
        },
        "body": null,
        "middlewares": [
          [
            "MsRest::RetryPolicyMiddleware",
            {
              "times": 3,
              "retry": 0.02
            }
          ],
          [
            "cookie_jar"
          ]
        ],
        "log": null
      },
      "response": {
        "body": "",
        "headers": {
          "x-powered-by": "Express",
          "date": "Fri, 29 Apr 2016 20:18:59 GMT",
          "connection": "close",
          "content-length": "0"
        },
        "status": 200
      }
    }> with backtrace:
      # ./RspecTests/Generated/url_items/url/paths.rb:1369:in `block in date_null_async'
  # ./RspecTests/path_spec.rb:113:in `block (2 levels) in <top (required)>'
```

  14) UrlModule::Paths should get dateTime valid
      # Appropriately disallowed together with CSharp
      Failure/Error: result = @paths_client.date_time_valid(DateTime.new(2012, 1, 1, 1, 1, 1, 'Z')).value!

```
  TypeError:
    no implicit conversion of DateTime into Hash
  # ./RspecTests/Generated/url_items/url/paths.rb:1420:in `merge'
  # ./RspecTests/Generated/url_items/url/paths.rb:1420:in `date_time_valid_async'
  # ./RspecTests/Generated/url_items/url/paths.rb:1389:in `date_time_valid'
  # ./RspecTests/path_spec.rb:118:in `block (2 levels) in <top (required)>'
```

  15) UrlModule::Paths should get dateTime null
      # Appropriately disallowed together with CSharp
      Failure/Error: fail MsRest::HttpOperationError.new(request, http_response, error_model)

```
  MsRest::HttpOperationError:
    {
      "message": "MsRest::HttpOperationError",
      "request": {
        "base_uri": "http://localhost:3435",
        "path_template": "/paths/datetime/null/{dateTimePath}",
        "method": "get",
        "path_params": {
          "dateTimePath": "null"
        },
        "skip_encoding_path_params": null,
        "query_params": null,
        "skip_encoding_query_params": null,
        "headers": {
        },
        "body": null,
        "middlewares": [
          [
            "MsRest::RetryPolicyMiddleware",
            {
              "times": 3,
              "retry": 0.02
            }
          ],
          [
            "cookie_jar"
          ]
        ],
        "log": null
      },
      "response": {
        "body": "",
        "headers": {
          "x-powered-by": "Express",
          "date": "Fri, 29 Apr 2016 20:18:59 GMT",
          "connection": "close",
          "content-length": "0"
        },
        "status": 200
      }
    }
  # ./RspecTests/Generated/url_items/url/paths.rb:1501:in `block in date_time_null_async'
```

  16) UrlModule::Queries should get byte multi byte
      # proper working with unicode isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:93:in `block (2 levels) in <top (required)>'

  17) UrlModule::Queries should get byte empty
      # proper working with unicode isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:101:in `block (2 levels) in <top (required)>'

  18) UrlModule::Queries should get byte null
      # proper working with unicode isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:108:in `block (2 levels) in <top (required)>'

  19) UrlModule::Queries should get date valid
      # proper working with datetime isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:115:in `block (2 levels) in <top (required)>'

  20) UrlModule::Queries should get date null
      # proper working with datetime isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:122:in `block (2 levels) in <top (required)>'

  21) UrlModule::Queries should get dateTime valid
      # proper working with datetime isnt implemented yet
      Failure/Error: fail
      RuntimeError:
      # ./RspecTests/query_spec.rb:129:in `block (2 levels) in <top (required)>'

**Comment by fearthecowboy** [comment]
@veronicagg and @sarangan12  -- is this still an issue? 

If this is still necessary, reopen it with new details.
