### ISSUE TITLE
Deserialize response for HTTP status codes other than 200?

### ISSUE THREAD

**Issue by Fabio-Marini** [Azure/autorest#994]
I have seen #931 and #693 and this is similar. My API returns Created (201) when a resource is created on the server, but the client that is generated only populates the response if the status is 200.

Shouldn't the response be populated regardless of the status code returned?

**Comment by amarzavery** [comment]
@Fabio-Marini 
- Have you described 201 as a valid response in your spec? 
- Can you provide a snapshot of that operation in the swagger doc?
- Which language are you trying to generate. (I assume C#) ?

**Comment by Fabio-Marini** [comment]
Ah! Looking at the Swagger documentation for my POST method, I see a Response class of 200 and Response Messages of 201 (see screenshot). What's the difference? And how do I set 201 as a valid response? I already have  [SwaggerResponse(HttpStatusCode.Created)]... Yes, I'm using C#...

![image](https://cloud.githubusercontent.com/assets/10209472/14958648/9e1699ea-1083-11e6-8bf2-7570edbd8fb3.png)

Thanks,
Fabio

**Comment by amarzavery** [comment]
I am not able to see a schema for the 201 response in the attached screenshot.
Take a look at [this example](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2015-08-01/swagger/redis.json#L78) of the swagger spec and the corresponding [C# code where 201 response is deserialized](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Redis/Generated/RedisOperations.cs#L229) and 200 is deserialized at line 247.

Also take a look at [this document](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#responses) to understand how AutoRest deserializes Responses, Negative (4xx, 5xx) responses and generates an error.

**Comment by Fabio-Marini** [comment]
OK, I think I have figured it out...

I was returning a IEnumerable<ChildModel> and Swashbuckle doesn't seem to understand that - strange though because it doesn't have a problem with the same type as an input parameter...

Anyway thanks for the input Amar, it definitely steered me in the right direction!

Fabio
