### ISSUE TITLE
Supporting schema-less swagger files

### ISSUE THREAD

**Issue by VitaliyKurokhtin** [Azure/autorest#997]
If no schema is present in swagger file AutoRest generates operations that do not return result (just Task) even for GET operations. Should we consider returning a string instead with response content received from server?

**Comment by devigned** [comment]
Seems like a completely reasonable default. 

Would it be more appropriate to return a deserialized object based on content type (application/json would return JObject)?

**Comment by VitaliyKurokhtin** [comment]
I think it would. It might definitely break clients that return payload that does not correspond with content type, but I don't think that these scenarios are important. Because at least one's API should comply with swagger file.

**Comment by brjohnstmsft** [comment]
This would be very useful for data plane APIs. It would also be useful for the same thing to work for request bodies as well.

**Comment by koolraap** [comment]
Does this contradict the reasons for not implementing #931 / #693 "No, we won't do this because the swagger file doesn't specify it"? That'd be useful, too :-)

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:

**Comment by brjohnstmsft** [comment]
A note for when this issue comes back... For our scenarios, string would be better than `JObject` (or the equivalent in other languages) because our data plane SDK needs type information from an external source to ensure that the response is deserialized correctly.

From a perf perspective, you could go one step further and just return a Stream. That would be ideal.
